### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  id: UnhandledExceptionEventArgs
  children:
  - Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.#ctor(System.Boolean,System.Exception)
  - Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.ExitApplication
  langs:
  - csharp
  name: UnhandledExceptionEventArgs
  nameWithType: UnhandledExceptionEventArgs
  fullName: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  type: Class
  summary: "Provides data for the <xref uid=&quot;langword_csharp_My.Application.UnhandledException&quot; name=&quot;My.Application.UnhandledException&quot; href=&quot;&quot;></xref> event."
  remarks: "The <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.UnhandledException> event occurs when an unhandled exception occurs in an application that implements the Visual Basic Application Model. For more information, see [Overview of the Visual Basic Application Model](../Topic/Overview%20of%20the%20Visual%20Basic%20Application%20Model.md).       UnhandledExceptionEventArgs contains the <xref:System.Exception> that occurred and indicates whether the application should exit upon exiting the exception handler."
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]

      [System.Runtime.InteropServices.ComVisible(false)]

      public class UnhandledExceptionEventArgs : System.Threading.ThreadExceptionEventArgs
  inheritance:
  - System.EventArgs
  - System.Threading.ThreadExceptionEventArgs
  implements: []
  inheritedMembers:
  - System.Threading.ThreadExceptionEventArgs.Exception
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.#ctor(System.Boolean,System.Exception)
  id: '#ctor(System.Boolean,System.Exception)'
  parent: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  langs:
  - csharp
  name: UnhandledExceptionEventArgs(Boolean,Exception)
  nameWithType: UnhandledExceptionEventArgs.UnhandledExceptionEventArgs(Boolean,Exception)
  fullName: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.UnhandledExceptionEventArgs(Boolean,Exception)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Initializes a new instance of the <see cref=&quot;T:Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs&quot;></see> class."
  remarks: "The <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.UnhandledException> event occurs when an unhandled exception occurs in an application that implements the Visual Basic Application Model. For more information, see [Overview of the Visual Basic Application Model](../Topic/Overview%20of%20the%20Visual%20Basic%20Application%20Model.md).       <xref:Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs> contains the <xref:System.Exception> that occurred and indicates whether the application should exit upon exiting the exception handler."
  syntax:
    content: public UnhandledExceptionEventArgs (bool exitApplication, Exception exception);
    parameters:
    - id: exitApplication
      type: System.Boolean
      description: "A <xref:System.Boolean> that indicates whether the application should exit upon exiting the exception handler."
    - id: exception
      type: System.Exception
      description: "The <xref:System.Exception> that occurred."
  overload: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.ExitApplication
  id: ExitApplication
  parent: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  langs:
  - csharp
  name: ExitApplication
  nameWithType: UnhandledExceptionEventArgs.ExitApplication
  fullName: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.ExitApplication
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Indicates whether the application should exit upon exiting the exception handler."
  remarks: "The Visual Basic Application Model checks the value of this property after running the handlers of the <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.UnhandledException> event. If ExitApplication is `True`, then the application exits. Otherwise, the application continues to run. For more information, see [Overview of the Visual Basic Application Model](../Topic/Overview%20of%20the%20Visual%20Basic%20Application%20Model.md)."
  syntax:
    content: public bool ExitApplication { get; set; }
    return:
      type: System.Boolean
      description: "A &lt;xref:System.Boolean&gt; that indicates whether the application should exit upon exiting the exception handler."
  overload: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.ExitApplication*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Threading.ThreadExceptionEventArgs
  isExternal: false
  name: System.Threading.ThreadExceptionEventArgs
- uid: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.#ctor(System.Boolean,System.Exception)
  parent: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  isExternal: false
  name: UnhandledExceptionEventArgs(Boolean,Exception)
  nameWithType: UnhandledExceptionEventArgs.UnhandledExceptionEventArgs(Boolean,Exception)
  fullName: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.UnhandledExceptionEventArgs(Boolean,Exception)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.ExitApplication
  parent: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  isExternal: false
  name: ExitApplication
  nameWithType: UnhandledExceptionEventArgs.ExitApplication
  fullName: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.ExitApplication
- uid: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.#ctor*
  parent: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  isExternal: false
  name: UnhandledExceptionEventArgs
  nameWithType: UnhandledExceptionEventArgs.UnhandledExceptionEventArgs
- uid: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs.ExitApplication*
  parent: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventArgs
  isExternal: false
  name: ExitApplication
  nameWithType: UnhandledExceptionEventArgs.ExitApplication
