### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  id: StartupEventArgs
  children:
  - Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String})
  - Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
  langs:
  - csharp
  name: StartupEventArgs
  nameWithType: StartupEventArgs
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  type: Class
  summary: "Provides data for the <xref uid=&quot;langword_csharp_My.Application.Startup&quot; name=&quot;My.Application.Startup&quot; href=&quot;&quot;></xref> event."
  remarks: "The <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Startup> event occurs when the application starts, if the application implements the Visual Basic Application Model. For more information, see [Overview of the Visual Basic Application Model](../Topic/Overview%20of%20the%20Visual%20Basic%20Application%20Model.md).       StartupEventArgs contains the command-line arguments of the application and indicates whether the application startup should be canceled."
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]

      [System.Runtime.InteropServices.ComVisible(false)]

      public class StartupEventArgs : System.ComponentModel.CancelEventArgs
  inheritance:
  - System.ComponentModel.CancelEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String})
  id: '#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String})'
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  langs:
  - csharp
  name: StartupEventArgs(ReadOnlyCollection<String>)
  nameWithType: StartupEventArgs.StartupEventArgs(ReadOnlyCollection<String>)
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.StartupEventArgs(ReadOnlyCollection<String>)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Initializes a new instance of the <see cref=&quot;T:Microsoft.VisualBasic.ApplicationServices.StartupEventArgs&quot;></see> class."
  remarks: "The <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Startup> event occurs when the application starts, if the application implements the Visual Basic Application Model. For more information, see [Overview of the Visual Basic Application Model](../Topic/Overview%20of%20the%20Visual%20Basic%20Application%20Model.md).       <xref:Microsoft.VisualBasic.ApplicationServices.StartupEventArgs> contains the command-line arguments of the application and indicates whether the application startup should be canceled."
  syntax:
    content: public StartupEventArgs (System.Collections.ObjectModel.ReadOnlyCollection<string> args);
    parameters:
    - id: args
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: "A <xref:System.Collections.ObjectModel.ReadOnlyCollection%601> object that contains the command-line arguments of the application."
  overload: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
  id: CommandLine
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  langs:
  - csharp
  name: CommandLine
  nameWithType: StartupEventArgs.CommandLine
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Gets the command-line arguments of the application."
  remarks: "The <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Startup> event occurs when the application starts, if the application implements the Visual Basic Application Model. For more information, see [Overview of the Visual Basic Application Model](../Topic/Overview%20of%20the%20Visual%20Basic%20Application%20Model.md)."
  syntax:
    content: public System.Collections.ObjectModel.ReadOnlyCollection<string> CommandLine { get; }
    return:
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: "A &lt;xref:System.Collections.ObjectModel.ReadOnlyCollection%601&gt; object that contains the command-line arguments of the application."
  overload: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ComponentModel.CancelEventArgs
  isExternal: false
  name: System.ComponentModel.CancelEventArgs
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String})
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  isExternal: false
  name: StartupEventArgs(ReadOnlyCollection<String>)
  nameWithType: StartupEventArgs.StartupEventArgs(ReadOnlyCollection<String>)
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.StartupEventArgs(ReadOnlyCollection<String>)
- uid: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
  parent: System.Collections.ObjectModel
  isExternal: true
  name: ReadOnlyCollection<String>
  nameWithType: ReadOnlyCollection<String>
  fullName: System.Collections.ObjectModel.ReadOnlyCollection<System.String>
  spec.csharp:
  - uid: System.Collections.ObjectModel.ReadOnlyCollection`1
    name: ReadOnlyCollection
    nameWithType: ReadOnlyCollection
    fullName: ReadOnlyCollection<System.String>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  isExternal: false
  name: CommandLine
  nameWithType: StartupEventArgs.CommandLine
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.#ctor*
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  isExternal: false
  name: StartupEventArgs
  nameWithType: StartupEventArgs.StartupEventArgs
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine*
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  isExternal: false
  name: CommandLine
  nameWithType: StartupEventArgs.CommandLine
