### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  id: UpdateManifestForBrowserApplication
  children:
  - Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.#ctor
  - Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.ApplicationManifest
  - Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.Execute
  - Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.HostInBrowser
  langs:
  - csharp
  name: UpdateManifestForBrowserApplication
  nameWithType: UpdateManifestForBrowserApplication
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  type: Class
  summary: "Implements the `UpdateManifestForBrowserApplication` task. Use the `UpdateManifestForBrowserApplication` element in your project file to create and execute this task. For usage and parameter information, see [UpdateManifestForBrowserApplication](../Topic/UpdateManifestForBrowserApplication%20Task.md)."
  syntax:
    content: 'public sealed class UpdateManifestForBrowserApplication : Microsoft.Build.Utilities.Task'
  inheritance:
  - System.Object
  - Microsoft.Build.Utilities.Task
  implements: []
  inheritedMembers:
  - Microsoft.Build.Utilities.Task.BuildEngine
  - Microsoft.Build.Utilities.Task.BuildEngine2
  - Microsoft.Build.Utilities.Task.BuildEngine3
  - Microsoft.Build.Utilities.Task.BuildEngine4
  - Microsoft.Build.Utilities.Task.HelpKeywordPrefix
  - Microsoft.Build.Utilities.Task.HostObject
  - Microsoft.Build.Utilities.Task.Log
  - Microsoft.Build.Utilities.Task.TaskResources
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.#ctor
  id: '#ctor'
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  langs:
  - csharp
  name: UpdateManifestForBrowserApplication()
  nameWithType: UpdateManifestForBrowserApplication.UpdateManifestForBrowserApplication()
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.UpdateManifestForBrowserApplication()
  type: Constructor
  assemblies:
  - PresentationBuildTasks
  namespace: Microsoft.Build.Tasks.Windows
  summary: "Initializes a new instance of the <see cref=&quot;T:Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication&quot;></see> class."
  syntax:
    content: public UpdateManifestForBrowserApplication ();
    parameters: []
  overload: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.ApplicationManifest
  id: ApplicationManifest
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  langs:
  - csharp
  name: ApplicationManifest
  nameWithType: UpdateManifestForBrowserApplication.ApplicationManifest
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.ApplicationManifest
  type: Property
  assemblies:
  - PresentationBuildTasks
  namespace: Microsoft.Build.Tasks.Windows
  summary: "Gets or sets the path and name of the application manifest file that you want to add the `<hostInBrowser></hostInBrowser>` element to."
  syntax:
    content: public Microsoft.Build.Framework.ITaskItem[] ApplicationManifest { get; set; }
    return:
      type: Microsoft.Build.Framework.ITaskItem[]
      description: "The path and name of the application manifest file that you want to add the `<hostInBrowser></hostInBrowser>` element to."
  overload: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.ApplicationManifest*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.Execute
  id: Execute
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  langs:
  - csharp
  name: Execute()
  nameWithType: UpdateManifestForBrowserApplication.Execute()
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.Execute()
  type: Method
  assemblies:
  - PresentationBuildTasks
  namespace: Microsoft.Build.Tasks.Windows
  summary: "Executes a task."
  syntax:
    content: public override bool Execute ();
    parameters: []
    return:
      type: System.Boolean
      description: "To be added."
  overload: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.Execute*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.HostInBrowser
  id: HostInBrowser
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  langs:
  - csharp
  name: HostInBrowser
  nameWithType: UpdateManifestForBrowserApplication.HostInBrowser
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.HostInBrowser
  type: Property
  assemblies:
  - PresentationBuildTasks
  namespace: Microsoft.Build.Tasks.Windows
  summary: "Gets a value that indicates whether to modify the application manifest to include the **\\<hostInBrowser></hostInBrowser>** element."
  syntax:
    content: public bool HostInBrowser { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> to modify the application manifest to include the **\\<hostInBrowser></hostInBrowser>** element; otherwise, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>."
  overload: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.HostInBrowser*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: Microsoft.Build.Utilities.Task
  isExternal: false
  name: Microsoft.Build.Utilities.Task
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.#ctor
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  isExternal: false
  name: UpdateManifestForBrowserApplication()
  nameWithType: UpdateManifestForBrowserApplication.UpdateManifestForBrowserApplication()
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.UpdateManifestForBrowserApplication()
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.ApplicationManifest
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  isExternal: false
  name: ApplicationManifest
  nameWithType: UpdateManifestForBrowserApplication.ApplicationManifest
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.ApplicationManifest
- uid: Microsoft.Build.Framework.ITaskItem[]
  parent: Microsoft.Build.Framework
  isExternal: false
  name: ITaskItem
  nameWithType: ITaskItem
  fullName: Microsoft.Build.Framework.ITaskItem[]
  spec.csharp:
  - uid: Microsoft.Build.Framework.ITaskItem
    name: ITaskItem
    nameWithType: ITaskItem
    fullName: ITaskItem[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.Execute
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  isExternal: false
  name: Execute()
  nameWithType: UpdateManifestForBrowserApplication.Execute()
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.Execute()
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.HostInBrowser
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  isExternal: false
  name: HostInBrowser
  nameWithType: UpdateManifestForBrowserApplication.HostInBrowser
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.HostInBrowser
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.#ctor*
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  isExternal: false
  name: UpdateManifestForBrowserApplication
  nameWithType: UpdateManifestForBrowserApplication.UpdateManifestForBrowserApplication
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.ApplicationManifest*
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  isExternal: false
  name: ApplicationManifest
  nameWithType: UpdateManifestForBrowserApplication.ApplicationManifest
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.Execute*
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  isExternal: false
  name: Execute
  nameWithType: UpdateManifestForBrowserApplication.Execute
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.HostInBrowser*
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  isExternal: false
  name: HostInBrowser
  nameWithType: UpdateManifestForBrowserApplication.HostInBrowser
