### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.BuildEngine.ProjectLoadSettings
  id: ProjectLoadSettings
  children:
  - Microsoft.Build.BuildEngine.ProjectLoadSettings.IgnoreMissingImports
  - Microsoft.Build.BuildEngine.ProjectLoadSettings.None
  langs:
  - csharp
  name: ProjectLoadSettings
  nameWithType: ProjectLoadSettings
  fullName: Microsoft.Build.BuildEngine.ProjectLoadSettings
  type: Enum
  summary: "Defines how MSBuild loads a project."
  syntax:
    content: >-
      [System.Flags]

      public enum ProjectLoadSettings
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.BuildEngine.ProjectLoadSettings.IgnoreMissingImports
  id: IgnoreMissingImports
  parent: Microsoft.Build.BuildEngine.ProjectLoadSettings
  langs:
  - csharp
  name: IgnoreMissingImports
  nameWithType: ProjectLoadSettings.IgnoreMissingImports
  fullName: Microsoft.Build.BuildEngine.ProjectLoadSettings.IgnoreMissingImports
  type: Field
  assemblies:
  - Microsoft.Build.Engine
  namespace: Microsoft.Build.BuildEngine
  summary: "Ignore nonexistent .targets files when loading the project."
  syntax:
    content: IgnoreMissingImports
    return:
      type: Microsoft.Build.BuildEngine.ProjectLoadSettings
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.BuildEngine.ProjectLoadSettings.None
  id: None
  parent: Microsoft.Build.BuildEngine.ProjectLoadSettings
  langs:
  - csharp
  name: None
  nameWithType: ProjectLoadSettings.None
  fullName: Microsoft.Build.BuildEngine.ProjectLoadSettings.None
  type: Field
  assemblies:
  - Microsoft.Build.Engine
  namespace: Microsoft.Build.BuildEngine
  summary: "Load the project  normally."
  syntax:
    content: None
    return:
      type: Microsoft.Build.BuildEngine.ProjectLoadSettings
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: Microsoft.Build.BuildEngine.ProjectLoadSettings.IgnoreMissingImports
  parent: Microsoft.Build.BuildEngine.ProjectLoadSettings
  isExternal: false
  name: IgnoreMissingImports
  nameWithType: ProjectLoadSettings.IgnoreMissingImports
  fullName: Microsoft.Build.BuildEngine.ProjectLoadSettings.IgnoreMissingImports
- uid: Microsoft.Build.BuildEngine.ProjectLoadSettings
  parent: Microsoft.Build.BuildEngine
  isExternal: false
  name: ProjectLoadSettings
  nameWithType: ProjectLoadSettings
  fullName: Microsoft.Build.BuildEngine.ProjectLoadSettings
- uid: Microsoft.Build.BuildEngine.ProjectLoadSettings.None
  parent: Microsoft.Build.BuildEngine.ProjectLoadSettings
  isExternal: false
  name: None
  nameWithType: ProjectLoadSettings.None
  fullName: Microsoft.Build.BuildEngine.ProjectLoadSettings.None
