### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  id: ComClass
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.#ctor
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ClsId
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.Description
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ProgId
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ThreadingModel
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.TlbId
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlClsId
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlDescription
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlProgId
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlThreadingModel
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlTlbId
  langs:
  - csharp
  name: ComClass
  nameWithType: ComClass
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  type: Class
  summary: "Represents a COM class that is described in a manifest."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public class ComClass
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.#ctor
  id: '#ctor'
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  langs:
  - csharp
  name: ComClass()
  nameWithType: ComClass.ComClass()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ComClass()
  type: Constructor
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Initializes a new instance of the <see cref=&quot;T:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass&quot;></see> class."
  syntax:
    content: public ComClass ();
    parameters: []
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ClsId
  id: ClsId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  langs:
  - csharp
  name: ClsId
  nameWithType: ComClass.ClsId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ClsId
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Gets the class identifier (ClsId) for a <see cref=&quot;T:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass&quot;></see> object."
  syntax:
    content: public string ClsId { get; }
    return:
      type: System.String
      description: "A &lt;xref:System.String&gt; formatted in the pattern {xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}, where the value of the GUID is represented as a series of lower-case hexadecimal digits in groups of 8, 4, 4, 4, and 12 digits and separated by hyphens. An example of a return value is &quot;{382c74c3-721d-4f34-80e5-57657b6cbc27}&quot;."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ClsId*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.Description
  id: Description
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  langs:
  - csharp
  name: Description
  nameWithType: ComClass.Description
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.Description
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Gets the description of a <see cref=&quot;T:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass&quot;></see> object."
  syntax:
    content: public string Description { get; }
    return:
      type: System.String
      description: "A description of the <see cref=&quot;T:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass&quot;></see> object."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.Description*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ProgId
  id: ProgId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  langs:
  - csharp
  name: ProgId
  nameWithType: ComClass.ProgId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ProgId
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Gets the programmatic identifier (ProgId) of a <see cref=&quot;T:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass&quot;></see> object."
  syntax:
    content: public string ProgId { get; }
    return:
      type: System.String
      description: "The programmatic identifier of the <see cref=&quot;T:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass&quot;></see> object."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ProgId*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ThreadingModel
  id: ThreadingModel
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  langs:
  - csharp
  name: ThreadingModel
  nameWithType: ComClass.ThreadingModel
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ThreadingModel
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Gets the threading model of a <see cref=&quot;T:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass&quot;></see> object."
  syntax:
    content: public string ThreadingModel { get; }
    return:
      type: System.String
      description: "A string such as &quot;Apartment&quot;."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ThreadingModel*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.TlbId
  id: TlbId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  langs:
  - csharp
  name: TlbId
  nameWithType: ComClass.TlbId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.TlbId
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Gets a value that is the identifier of the type library that contains type information about the class."
  syntax:
    content: public string TlbId { get; }
    return:
      type: System.String
      description: "The identifier of the type library that contains type information about the class. A &lt;xref:System.String&gt; formatted in the pattern {xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}, where the value of the GUID is represented as a series of lower-case hexadecimal digits in groups of 8, 4, 4, 4, and 12 digits and separated by hyphens. An example of a return value is &quot;{382c74c3-721d-4f34-80e5-57657b6cbc27}&quot;."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.TlbId*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlClsId
  id: XmlClsId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  langs:
  - csharp
  name: XmlClsId
  nameWithType: ComClass.XmlClsId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlClsId
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Gets or sets a property that is used to serialize the &lt;xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ClsId%2A&gt; property to an XML file."
  syntax:
    content: public string XmlClsId { get; set; }
    return:
      type: System.String
      description: "The value of the &lt;xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ClsId%2A&gt; property."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlClsId*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlDescription
  id: XmlDescription
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  langs:
  - csharp
  name: XmlDescription
  nameWithType: ComClass.XmlDescription
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlDescription
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Gets or sets a property that is used to serialize the &lt;xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.Description%2A&gt; property to an XML file."
  syntax:
    content: public string XmlDescription { get; set; }
    return:
      type: System.String
      description: "The value of the &lt;xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.Description%2A&gt; property."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlDescription*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlProgId
  id: XmlProgId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  langs:
  - csharp
  name: XmlProgId
  nameWithType: ComClass.XmlProgId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlProgId
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Gets or sets a property that is used to serialize the &lt;xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ProgId%2A&gt; property to an XML file."
  syntax:
    content: public string XmlProgId { get; set; }
    return:
      type: System.String
      description: "The value of the &lt;xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ProgId%2A&gt; property."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlProgId*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlThreadingModel
  id: XmlThreadingModel
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  langs:
  - csharp
  name: XmlThreadingModel
  nameWithType: ComClass.XmlThreadingModel
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlThreadingModel
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Gets or sets a property that is used to serialize the &lt;xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ThreadingModel%2A&gt; property to an XML file."
  syntax:
    content: public string XmlThreadingModel { get; set; }
    return:
      type: System.String
      description: "The value of the &lt;xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ThreadingModel%2A&gt; property."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlThreadingModel*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlTlbId
  id: XmlTlbId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  langs:
  - csharp
  name: XmlTlbId
  nameWithType: ComClass.XmlTlbId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlTlbId
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Gets or sets a property that is used to serialize the &lt;xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.TlbId%2A&gt; property to an XML file."
  syntax:
    content: public string XmlTlbId { get; set; }
    return:
      type: System.String
      description: "The value of the &lt;xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.TlbId%2A&gt; property."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlTlbId*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.#ctor
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: ComClass()
  nameWithType: ComClass.ComClass()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ComClass()
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ClsId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: ClsId
  nameWithType: ComClass.ClsId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ClsId
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.Description
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: Description
  nameWithType: ComClass.Description
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.Description
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ProgId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: ProgId
  nameWithType: ComClass.ProgId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ProgId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ThreadingModel
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: ThreadingModel
  nameWithType: ComClass.ThreadingModel
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ThreadingModel
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.TlbId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: TlbId
  nameWithType: ComClass.TlbId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.TlbId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlClsId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: XmlClsId
  nameWithType: ComClass.XmlClsId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlClsId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlDescription
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: XmlDescription
  nameWithType: ComClass.XmlDescription
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlDescription
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlProgId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: XmlProgId
  nameWithType: ComClass.XmlProgId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlProgId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlThreadingModel
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: XmlThreadingModel
  nameWithType: ComClass.XmlThreadingModel
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlThreadingModel
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlTlbId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: XmlTlbId
  nameWithType: ComClass.XmlTlbId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlTlbId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.#ctor*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: ComClass
  nameWithType: ComClass.ComClass
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ClsId*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: ClsId
  nameWithType: ComClass.ClsId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.Description*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: Description
  nameWithType: ComClass.Description
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ProgId*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: ProgId
  nameWithType: ComClass.ProgId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.ThreadingModel*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: ThreadingModel
  nameWithType: ComClass.ThreadingModel
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.TlbId*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: TlbId
  nameWithType: ComClass.TlbId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlClsId*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: XmlClsId
  nameWithType: ComClass.XmlClsId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlDescription*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: XmlDescription
  nameWithType: ComClass.XmlDescription
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlProgId*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: XmlProgId
  nameWithType: ComClass.XmlProgId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlThreadingModel*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: XmlThreadingModel
  nameWithType: ComClass.XmlThreadingModel
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass.XmlTlbId*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ComClass
  isExternal: false
  name: XmlTlbId
  nameWithType: ComClass.XmlTlbId
