### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  id: CompatibleFrameworkCollection
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Add(Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Clear
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Count
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.GetEnumerator
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Item(System.Int32)
  langs:
  - csharp
  name: CompatibleFrameworkCollection
  nameWithType: CompatibleFrameworkCollection
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  type: Class
  summary: "Represents a collection of versions of the .NET Framework that an application prefers to run on."
  remarks: "If an application can run on multiple versions of the .NET Framework, the versions should be listed in priority order from most preferred to least preferred. If a version of the .NET Framework listed in the CompatibleFrameworkCollection class is installed on the end-user computer, the application can install and run."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class CompatibleFrameworkCollection : System.Collections.IEnumerable
  inheritance:
  - System.Object
  implements:
  - System.Collections.IEnumerable
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Add(Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework)
  id: Add(Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  langs:
  - csharp
  name: Add(CompatibleFramework)
  nameWithType: CompatibleFrameworkCollection.Add(CompatibleFramework)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Add(CompatibleFramework)
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Adds a framework to the <see cref=&quot;T:Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework&quot;></see> class."
  syntax:
    content: public void Add (Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework compatibleFramework);
    parameters:
    - id: compatibleFramework
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
      description: "The framework to add."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Add*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Clear
  id: Clear
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  langs:
  - csharp
  name: Clear()
  nameWithType: CompatibleFrameworkCollection.Clear()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Clear()
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Clears the collection."
  syntax:
    content: public void Clear ();
    parameters: []
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Clear*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Count
  id: Count
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  langs:
  - csharp
  name: Count
  nameWithType: CompatibleFrameworkCollection.Count
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Count
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Gets the number of .NET Framework versions listed in the <see cref=&quot;T:Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection&quot;></see> collection."
  syntax:
    content: public int Count { get; }
    return:
      type: System.Int32
      description: "A &lt;xref:System.Int32&gt; object that represents the number of .NET Framework versions listed in the <see cref=&quot;T:Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection&quot;></see> collection."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Count*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.GetEnumerator
  id: GetEnumerator
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  langs:
  - csharp
  name: GetEnumerator()
  nameWithType: CompatibleFrameworkCollection.GetEnumerator()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.GetEnumerator()
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Gets the enumerator for the collection."
  syntax:
    content: public System.Collections.IEnumerator GetEnumerator ();
    parameters: []
    return:
      type: System.Collections.IEnumerator
      description: "To be added."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.GetEnumerator*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Item(System.Int32)
  id: Item(System.Int32)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  langs:
  - csharp
  name: Item(Int32)
  nameWithType: CompatibleFrameworkCollection.Item(Int32)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Item(Int32)
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Gets a version of the .NET Framework that an application prefers to run on."
  syntax:
    content: public Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework this[int index] { get; }
    parameters:
    - id: index
      type: System.Int32
      description: "The version of .NET Framework to check for on the end-user computer."
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
      description: "A <see cref=&quot;T:Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework&quot;></see> object that represents the versions of the .NET Framework that an application prefers to run on."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Item*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Add(Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: Add(CompatibleFramework)
  nameWithType: CompatibleFrameworkCollection.Add(CompatibleFramework)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Add(CompatibleFramework)
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: CompatibleFramework
  nameWithType: CompatibleFramework
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Clear
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: Clear()
  nameWithType: CompatibleFrameworkCollection.Clear()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Clear()
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Count
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: Count
  nameWithType: CompatibleFrameworkCollection.Count
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Count
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.GetEnumerator
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: GetEnumerator()
  nameWithType: CompatibleFrameworkCollection.GetEnumerator()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.GetEnumerator()
- uid: System.Collections.IEnumerator
  parent: System.Collections
  isExternal: true
  name: IEnumerator
  nameWithType: IEnumerator
  fullName: System.Collections.IEnumerator
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Item(System.Int32)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: Item(Int32)
  nameWithType: CompatibleFrameworkCollection.Item(Int32)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Item(Int32)
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Add*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: Add
  nameWithType: CompatibleFrameworkCollection.Add
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Clear*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: Clear
  nameWithType: CompatibleFrameworkCollection.Clear
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Count*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: Count
  nameWithType: CompatibleFrameworkCollection.Count
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.GetEnumerator*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: GetEnumerator
  nameWithType: CompatibleFrameworkCollection.GetEnumerator
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Item*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: Item
  nameWithType: CompatibleFrameworkCollection.Item
