### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  id: FileAssociation
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.#ctor
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.DefaultIcon
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDefaultIcon
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDescription
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlExtension
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlProgId
  langs:
  - csharp
  name: FileAssociation
  nameWithType: FileAssociation
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  type: Class
  summary: "Represents a file name extension to be associated with the application."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class FileAssociation
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.#ctor
  id: '#ctor'
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  langs:
  - csharp
  name: FileAssociation()
  nameWithType: FileAssociation.FileAssociation()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.FileAssociation()
  type: Constructor
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Initializes a new instance of the <see cref=&quot;T:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation&quot;></see> class."
  syntax:
    content: public FileAssociation ();
    parameters: []
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.DefaultIcon
  id: DefaultIcon
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  langs:
  - csharp
  name: DefaultIcon
  nameWithType: FileAssociation.DefaultIcon
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.DefaultIcon
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Gets or sets the icon to use for files that use a particular &lt;xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension%2A&gt;."
  syntax:
    content: public string DefaultIcon { get; set; }
    return:
      type: System.String
      description: "The name of the file that contains the icon."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.DefaultIcon*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description
  id: Description
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  langs:
  - csharp
  name: Description
  nameWithType: FileAssociation.Description
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Gets or sets the description of the file type for use by the shell."
  syntax:
    content: public string Description { get; set; }
    return:
      type: System.String
      description: "A description of the file type."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension
  id: Extension
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  langs:
  - csharp
  name: Extension
  nameWithType: FileAssociation.Extension
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Gets or sets the file name extension to be associated with the application."
  syntax:
    content: public string Extension { get; set; }
    return:
      type: System.String
      description: "The file name extension to be associated with the application."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId
  id: ProgId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  langs:
  - csharp
  name: ProgId
  nameWithType: FileAssociation.ProgId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Gets or sets the name that uniquely identifies the file association&quot;s file type."
  syntax:
    content: public string ProgId { get; set; }
    return:
      type: System.String
      description: "The name that uniquely identifies the file type."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDefaultIcon
  id: XmlDefaultIcon
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  langs:
  - csharp
  name: XmlDefaultIcon
  nameWithType: FileAssociation.XmlDefaultIcon
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDefaultIcon
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Gets or sets a property that is used to serialize the file association&quot;s &lt;xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.DefaultIcon%2A&gt; property to an XML file."
  syntax:
    content: public string XmlDefaultIcon { get; set; }
    return:
      type: System.String
      description: "An XML representation of this file association&quot;s DefaultIcon."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDefaultIcon*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDescription
  id: XmlDescription
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  langs:
  - csharp
  name: XmlDescription
  nameWithType: FileAssociation.XmlDescription
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDescription
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Gets or sets a property that is used to serialize the file association&quot;s &lt;xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description%2A&gt; property to an XML file."
  syntax:
    content: public string XmlDescription { get; set; }
    return:
      type: System.String
      description: "An XML representation of this file association&quot;s &lt;xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description%2A&gt; value."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDescription*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlExtension
  id: XmlExtension
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  langs:
  - csharp
  name: XmlExtension
  nameWithType: FileAssociation.XmlExtension
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlExtension
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Gets or sets a property that is used to serialize the file association&quot;s &lt;xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension%2A&gt; property to an XML file."
  syntax:
    content: public string XmlExtension { get; set; }
    return:
      type: System.String
      description: "An XML representation of this file association&quot;s &lt;xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension%2A&gt; value."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlExtension*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlProgId
  id: XmlProgId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  langs:
  - csharp
  name: XmlProgId
  nameWithType: FileAssociation.XmlProgId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlProgId
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Gets or sets a property that is used to serialize the &lt;xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId%2A&gt; property to an XML file."
  syntax:
    content: public string XmlProgId { get; set; }
    return:
      type: System.String
      description: "An XML representation of this file association&quot;s &lt;xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId%2A&gt; value."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlProgId*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.#ctor
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: FileAssociation()
  nameWithType: FileAssociation.FileAssociation()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.FileAssociation()
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.DefaultIcon
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: DefaultIcon
  nameWithType: FileAssociation.DefaultIcon
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.DefaultIcon
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: Description
  nameWithType: FileAssociation.Description
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: Extension
  nameWithType: FileAssociation.Extension
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: ProgId
  nameWithType: FileAssociation.ProgId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDefaultIcon
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: XmlDefaultIcon
  nameWithType: FileAssociation.XmlDefaultIcon
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDefaultIcon
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDescription
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: XmlDescription
  nameWithType: FileAssociation.XmlDescription
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDescription
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlExtension
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: XmlExtension
  nameWithType: FileAssociation.XmlExtension
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlExtension
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlProgId
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: XmlProgId
  nameWithType: FileAssociation.XmlProgId
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlProgId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.#ctor*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: FileAssociation
  nameWithType: FileAssociation.FileAssociation
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.DefaultIcon*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: DefaultIcon
  nameWithType: FileAssociation.DefaultIcon
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Description*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: Description
  nameWithType: FileAssociation.Description
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.Extension*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: Extension
  nameWithType: FileAssociation.Extension
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.ProgId*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: ProgId
  nameWithType: FileAssociation.ProgId
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDefaultIcon*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: XmlDefaultIcon
  nameWithType: FileAssociation.XmlDefaultIcon
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlDescription*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: XmlDescription
  nameWithType: FileAssociation.XmlDescription
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlExtension*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: XmlExtension
  nameWithType: FileAssociation.XmlExtension
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation.XmlProgId*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileAssociation
  isExternal: false
  name: XmlProgId
  nameWithType: FileAssociation.XmlProgId
