### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  id: ApplicationIdentity
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.#ctor(System.String,Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity,Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.#ctor(System.String,System.String,System.String)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ToString
  langs:
  - csharp
  name: ApplicationIdentity
  nameWithType: ApplicationIdentity
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  type: Class
  summary: "Provides a unique identifier for a ClickOnce application."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class ApplicationIdentity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.#ctor(System.String,Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity,Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity)
  id: '#ctor(System.String,Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity,Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity)'
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  langs:
  - csharp
  name: ApplicationIdentity(String,AssemblyIdentity,AssemblyIdentity)
  nameWithType: ApplicationIdentity.ApplicationIdentity(String,AssemblyIdentity,AssemblyIdentity)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ApplicationIdentity(String,AssemblyIdentity,AssemblyIdentity)
  type: Constructor
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Initializes a new instance of the <see cref=&quot;T:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity&quot;></see> class."
  syntax:
    content: public ApplicationIdentity (string url, Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity deployManifestIdentity, Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity applicationManifestIdentity);
    parameters:
    - id: url
      type: System.String
      description: "The deployment provider URL for the ClickOnce deployment manifest."
    - id: deployManifestIdentity
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity
      description: "The assembly identity of the ClickOnce deployment manifest."
    - id: applicationManifestIdentity
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity
      description: "The assembly identity of the ClickOnce application manifest."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.#ctor(System.String,System.String,System.String)
  id: '#ctor(System.String,System.String,System.String)'
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  langs:
  - csharp
  name: ApplicationIdentity(String,String,String)
  nameWithType: ApplicationIdentity.ApplicationIdentity(String,String,String)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ApplicationIdentity(String,String,String)
  type: Constructor
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Initializes a new instance of the <see cref=&quot;T:Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity&quot;></see> class."
  syntax:
    content: public ApplicationIdentity (string url, string deployManifestPath, string applicationManifestPath);
    parameters:
    - id: url
      type: System.String
      description: "The deployment provider URL for the ClickOnce deployment manifest."
    - id: deployManifestPath
      type: System.String
      description: "The path to ClickOnce deployment manifest. The assembly identity will be obtained from the specified file."
    - id: applicationManifestPath
      type: System.String
      description: "The path to ClickOnce application manifest. The assembly identity will be obtained from the specified file."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ToString
  id: ToString
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  langs:
  - csharp
  name: ToString()
  nameWithType: ApplicationIdentity.ToString()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ToString()
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Returns the full ClickOnce application identity."
  syntax:
    content: public override string ToString ();
    parameters: []
    return:
      type: System.String
      description: "To be added."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ToString*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.#ctor(System.String,Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity,Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  isExternal: false
  name: ApplicationIdentity(String,AssemblyIdentity,AssemblyIdentity)
  nameWithType: ApplicationIdentity.ApplicationIdentity(String,AssemblyIdentity,AssemblyIdentity)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ApplicationIdentity(String,AssemblyIdentity,AssemblyIdentity)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: AssemblyIdentity
  nameWithType: AssemblyIdentity
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.#ctor(System.String,System.String,System.String)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  isExternal: false
  name: ApplicationIdentity(String,String,String)
  nameWithType: ApplicationIdentity.ApplicationIdentity(String,String,String)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ApplicationIdentity(String,String,String)
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ToString
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  isExternal: false
  name: ToString()
  nameWithType: ApplicationIdentity.ToString()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ToString()
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.#ctor*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  isExternal: false
  name: ApplicationIdentity
  nameWithType: ApplicationIdentity.ApplicationIdentity
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ToString*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  isExternal: false
  name: ToString
  nameWithType: ApplicationIdentity.ToString
