### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  id: AuthenticationMode
  children:
  - Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.ApplicationDefined
  - Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows
  langs:
  - csharp
  name: AuthenticationMode
  nameWithType: AuthenticationMode
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  type: Enum
  summary: "Indicates how a Visual Basic application authenticates the user for the <xref uid=&quot;langword_csharp_My.User&quot; name=&quot;My.User&quot; href=&quot;&quot;></xref> object."
  remarks: "You can set the authentication mode for an application by passing one of this enumeration's values to the <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.%23ctor%2A> constructor. For more information, see [Extending the Visual Basic Application Model](../Topic/Extending%20the%20Visual%20Basic%20Application%20Model.md).  \n  \n A Visual Basic application that uses the Visual Basic Application Model can specify whether it uses Windows authentication or custom authentication. You can also configure the authentication mode in the Visual Studio Integrated Development Environment. For more information, see [Application Page, Project Designer (Visual Basic)](../Topic/Application%20Page,%20Project%20Designer%20\\(Visual%20Basic\\).md)."
  syntax:
    content: public enum AuthenticationMode
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.ApplicationDefined
  id: ApplicationDefined
  parent: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  langs:
  - csharp
  name: ApplicationDefined
  nameWithType: AuthenticationMode.ApplicationDefined
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.ApplicationDefined
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "The &lt;xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.%23ctor%2A&gt; constructor does not initialize the principal for the application&quot;s main thread. The application needs to initialize the principal for the application&quot;s main thread."
  syntax:
    content: ApplicationDefined
    return:
      type: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows
  id: Windows
  parent: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  langs:
  - csharp
  name: Windows
  nameWithType: AuthenticationMode.Windows
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "The &lt;xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.%23ctor%2A&gt; constructor initializes the principal for the application&quot;s main thread with the current user&quot;s Windows user information."
  syntax:
    content: Windows
    return:
      type: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.ApplicationDefined
  parent: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  isExternal: false
  name: ApplicationDefined
  nameWithType: AuthenticationMode.ApplicationDefined
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.ApplicationDefined
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  parent: Microsoft.VisualBasic.ApplicationServices
  isExternal: false
  name: AuthenticationMode
  nameWithType: AuthenticationMode
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
- uid: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows
  parent: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode
  isExternal: false
  name: Windows
  nameWithType: AuthenticationMode.Windows
  fullName: Microsoft.VisualBasic.ApplicationServices.AuthenticationMode.Windows
