### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode
  id: UpdateMode
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode.Background
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode.Foreground
  langs:
  - csharp
  name: UpdateMode
  nameWithType: UpdateMode
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode
  type: Enum
  summary: "Specifies how the application checks for updates."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public enum UpdateMode
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode.Background
  id: Background
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode
  langs:
  - csharp
  name: Background
  nameWithType: UpdateMode.Background
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode.Background
  type: Field
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Check for updates in the background, after the application starts."
  syntax:
    content: Background
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode.Foreground
  id: Foreground
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode
  langs:
  - csharp
  name: Foreground
  nameWithType: UpdateMode.Foreground
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode.Foreground
  type: Field
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Check for updates in the foreground, before the application starts."
  syntax:
    content: Foreground
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode.Background
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode
  isExternal: false
  name: Background
  nameWithType: UpdateMode.Background
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode.Background
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: UpdateMode
  nameWithType: UpdateMode
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode.Foreground
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode
  isExternal: false
  name: Foreground
  nameWithType: UpdateMode.Foreground
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.UpdateMode.Foreground
