### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest
  id: AssemblyManifest
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.#ctor
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.ExternalProxyStubs
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.XmlExternalProxyStubs
  langs:
  - csharp
  name: AssemblyManifest
  nameWithType: AssemblyManifest
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest
  type: Class
  summary: "Describes a Win32 assembly manifest."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      [System.Xml.Serialization.XmlRoot("AssemblyManifest")]

      public class AssemblyManifest : Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
  inheritance:
  - System.Object
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
  implements: []
  inheritedMembers:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.AssemblyIdentity
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.AssemblyReferences
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.Description
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.EntryPoint
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.FileReferences
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.InputStream
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.OutputMessages
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.ReadOnly
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.ResolveFiles
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.ResolveFiles(System.String[])
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.SourcePath
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.ToString
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.UpdateFileInfo
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.UpdateFileInfo(System.String)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.Validate
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.ValidatePlatform
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.XmlAssemblyIdentity
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.XmlAssemblyReferences
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.XmlDescription
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.XmlFileReferences
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.XmlSchema
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.#ctor
  id: '#ctor'
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest
  langs:
  - csharp
  name: AssemblyManifest()
  nameWithType: AssemblyManifest.AssemblyManifest()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.AssemblyManifest()
  type: Constructor
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Initializes a new instance of the <see cref=&quot;T:Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest&quot;></see> class."
  syntax:
    content: public AssemblyManifest ();
    parameters: []
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.ExternalProxyStubs
  id: ExternalProxyStubs
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest
  langs:
  - csharp
  name: ExternalProxyStubs
  nameWithType: AssemblyManifest.ExternalProxyStubs
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.ExternalProxyStubs
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Gets the set of external proxy stubs referenced by the manifest for isolated applications and Reg-Free COM."
  syntax:
    content: public Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub[] ExternalProxyStubs { get; }
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub[]
      description: "Returns the set of external proxy stubs referenced by the manifest for isolated applications and Reg-Free COM."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.ExternalProxyStubs*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.XmlExternalProxyStubs
  id: XmlExternalProxyStubs
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest
  langs:
  - csharp
  name: XmlExternalProxyStubs
  nameWithType: AssemblyManifest.XmlExternalProxyStubs
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.XmlExternalProxyStubs
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Gets or sets the set of external proxy stubs referenced by the manifest for isolated applications and Reg-Free COM in XML format."
  syntax:
    content: public Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub[] XmlExternalProxyStubs { get; set; }
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub[]
      description: "Returns the set of external proxy stubs referenced by the manifest for isolated applications and Reg-Free COM in XML format."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.XmlExternalProxyStubs*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
  isExternal: false
  name: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.#ctor
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest
  isExternal: false
  name: AssemblyManifest()
  nameWithType: AssemblyManifest.AssemblyManifest()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.AssemblyManifest()
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.ExternalProxyStubs
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest
  isExternal: false
  name: ExternalProxyStubs
  nameWithType: AssemblyManifest.ExternalProxyStubs
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.ExternalProxyStubs
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub[]
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: ProxyStub
  nameWithType: ProxyStub
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub[]
  spec.csharp:
  - uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ProxyStub
    name: ProxyStub
    nameWithType: ProxyStub
    fullName: ProxyStub[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.XmlExternalProxyStubs
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest
  isExternal: false
  name: XmlExternalProxyStubs
  nameWithType: AssemblyManifest.XmlExternalProxyStubs
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.XmlExternalProxyStubs
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.#ctor*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest
  isExternal: false
  name: AssemblyManifest
  nameWithType: AssemblyManifest.AssemblyManifest
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.ExternalProxyStubs*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest
  isExternal: false
  name: ExternalProxyStubs
  nameWithType: AssemblyManifest.ExternalProxyStubs
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest.XmlExternalProxyStubs*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest
  isExternal: false
  name: XmlExternalProxyStubs
  nameWithType: AssemblyManifest.XmlExternalProxyStubs
