### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  id: CantStartSingleInstanceException
  children:
  - Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor
  - Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.String)
  - Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: CantStartSingleInstanceException
  nameWithType: CantStartSingleInstanceException
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  type: Class
  summary: "This exception is thrown when a subsequent instance of a single-instance application is unable to connect to the first application instance."
  remarks: "A single-instance application differs from a normal application in that only one instance of the application can be running at a time. When a subsequent application instance starts, it attempts to contact the first instance application to pass its command-line arguments. If the first instance cannot be contacted, the CantStartSingleInstanceException is raised in the subsequent application instance. The Visual Basic Application Model does not provide any context information in the exception.       For more information, see [Overview of the Visual Basic Application Model](../Topic/Overview%20of%20the%20Visual%20Basic%20Application%20Model.md)."
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]

      public class CantStartSingleInstanceException : Exception
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor
  id: '#ctor'
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  langs:
  - csharp
  name: CantStartSingleInstanceException()
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException()
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException()
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Initializes a new instance of the <see cref=&quot;T:Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException&quot;></see> class."
  remarks: "A single-instance application differs from a normal application in that only one instance of the application can be running at a time. When a subsequent application instance starts, it attempts to contact the first instance application to pass its command-line arguments. If the first instance cannot be contacted, the <xref:Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException> is raised in the subsequent application instance. For more information, see [Overview of the Visual Basic Application Model](../Topic/Overview%20of%20the%20Visual%20Basic%20Application%20Model.md).       The following table shows the initial property values for an instance of <xref:Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException>.      |||   |-|-|   |Property|Value|   |<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|   |<xref:System.Exception.Message%2A>|The localized error message string.|"
  syntax:
    content: public CantStartSingleInstanceException ();
    parameters: []
  overload: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  langs:
  - csharp
  name: CantStartSingleInstanceException(String)
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException(String)
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException(String)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Initializes a new instance of the <see cref=&quot;T:Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException&quot;></see> class with a specified error message."
  remarks: "The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.       <xref:Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException> inherits from <xref:System.Exception>. This constructor sets the properties of the <xref:System.Exception> object as shown in the following table.      |||   |-|-|   |Property|Value|   |<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic)|   |<xref:System.Exception.Message%2A>|The `message` string.|"
  syntax:
    content: public CantStartSingleInstanceException (string message);
    parameters:
    - id: message
      type: System.String
      description: "A message that describes the error."
  overload: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  langs:
  - csharp
  name: CantStartSingleInstanceException(SerializationInfo,StreamingContext)
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException(SerializationInfo,StreamingContext)
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Initializes a new instance of the <see cref=&quot;T:Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException&quot;></see> class with serialized data."
  remarks: "This constructor is called during deserialization to reconstitute the exception object transmitted over a stream."
  syntax:
    content: protected CantStartSingleInstanceException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "The  object that holds the serialized object data about the exception being thrown."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "The <xref:System.Runtime.Serialization.StreamingContext> object that contains contextual information about the source or destination."
  overload: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  langs:
  - csharp
  name: CantStartSingleInstanceException(String,Exception)
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException(String,Exception)
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException(String,Exception)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Initializes a new instance of the <see cref=&quot;T:Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException&quot;></see> class with a specified error message and a reference to the inner exception that is the cause of this exception."
  remarks: "The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.       An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or a null reference if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.       The following table shows the initial property values for an instance of <xref:System.ApplicationException>.      |||   |-|-|   |Property|Value|   |<xref:System.Exception.InnerException%2A>|The `inner` reference.|   |<xref:System.Exception.Message%2A>|The `message` string.|"
  syntax:
    content: public CantStartSingleInstanceException (string message, Exception inner);
    parameters:
    - id: message
      type: System.String
      description: "A <xref:System.String> object describing the error."
    - id: inner
      type: System.Exception
      description: "The <xref:System.Exception> object that is the cause of the current exception. If the <xref:System.Exception.InnerException%2A> parameter is not a null reference ( in Visual Basic), the current exception is raised in a  block that handles the inner exception."
  overload: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  isExternal: false
  name: CantStartSingleInstanceException()
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException()
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException()
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.String)
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  isExternal: false
  name: CantStartSingleInstanceException(String)
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException(String)
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  isExternal: false
  name: CantStartSingleInstanceException(SerializationInfo,StreamingContext)
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException(SerializationInfo,StreamingContext)
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor(System.String,System.Exception)
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  isExternal: false
  name: CantStartSingleInstanceException(String,Exception)
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException(String,Exception)
  fullName: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.CantStartSingleInstanceException(String,Exception)
- uid: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException.#ctor*
  parent: Microsoft.VisualBasic.ApplicationServices.CantStartSingleInstanceException
  isExternal: false
  name: CantStartSingleInstanceException
  nameWithType: CantStartSingleInstanceException.CantStartSingleInstanceException
