### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
  id: ShutdownMode
  children:
  - Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterAllFormsClose
  - Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
  langs:
  - csharp
  name: ShutdownMode
  nameWithType: ShutdownMode
  fullName: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
  type: Enum
  summary: "Indicates which condition should cause a Windows Forms application to shut down."
  remarks: "You can set the shutdown mode for an application through the <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.ShutdownStyle%2A> property. By default, the <xref:System.Windows.Forms.ApplicationContext.OnMainFormClosed%2A> method checks the value of the <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.ShutdownStyle%2A> property to determine if the application should shut down."
  syntax:
    content: public enum ShutdownMode
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterAllFormsClose
  id: AfterAllFormsClose
  parent: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
  langs:
  - csharp
  name: AfterAllFormsClose
  nameWithType: ShutdownMode.AfterAllFormsClose
  fullName: Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterAllFormsClose
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Shut down only after the last form closes."
  syntax:
    content: AfterAllFormsClose
    return:
      type: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
  id: AfterMainFormCloses
  parent: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
  langs:
  - csharp
  name: AfterMainFormCloses
  nameWithType: ShutdownMode.AfterMainFormCloses
  fullName: Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Shut down when the main form closes."
  syntax:
    content: AfterMainFormCloses
    return:
      type: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterAllFormsClose
  parent: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
  isExternal: false
  name: AfterAllFormsClose
  nameWithType: ShutdownMode.AfterAllFormsClose
  fullName: Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterAllFormsClose
- uid: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
  parent: Microsoft.VisualBasic.ApplicationServices
  isExternal: false
  name: ShutdownMode
  nameWithType: ShutdownMode
  fullName: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
- uid: Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
  parent: Microsoft.VisualBasic.ApplicationServices.ShutdownMode
  isExternal: false
  name: AfterMainFormCloses
  nameWithType: ShutdownMode.AfterMainFormCloses
  fullName: Microsoft.VisualBasic.ApplicationServices.ShutdownMode.AfterMainFormCloses
