### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings
  id: VisualBasicSettings
  children:
  - Microsoft.VisualBasic.Activities.VisualBasicSettings.#ctor
  - Microsoft.VisualBasic.Activities.VisualBasicSettings.Default
  - Microsoft.VisualBasic.Activities.VisualBasicSettings.ImportReferences
  langs:
  - csharp
  name: VisualBasicSettings
  nameWithType: VisualBasicSettings
  fullName: Microsoft.VisualBasic.Activities.VisualBasicSettings
  type: Class
  summary: "Contains settings that &lt;xref:Microsoft.VisualBasic.Activities.VisualBasicValue%601&gt; and &lt;xref:Microsoft.VisualBasic.Activities.VisualBasicReference%601&gt; instances use to compile the source text of the expressions they contain."
  remarks: "These settings include assembly references and imported namespaces required to compile an expression."
  syntax:
    content: >-
      [System.ComponentModel.TypeConverter(typeof(Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter))]

      [System.Windows.Markup.ValueSerializer(typeof(Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsValueSerializer))]

      public class VisualBasicSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings.#ctor
  id: '#ctor'
  parent: Microsoft.VisualBasic.Activities.VisualBasicSettings
  langs:
  - csharp
  name: VisualBasicSettings()
  nameWithType: VisualBasicSettings.VisualBasicSettings()
  fullName: Microsoft.VisualBasic.Activities.VisualBasicSettings.VisualBasicSettings()
  type: Constructor
  assemblies:
  - System.Activities
  namespace: Microsoft.VisualBasic.Activities
  summary: "Initializes a new instance of the <see cref=&quot;T:Microsoft.VisualBasic.Activities.VisualBasicSettings&quot;></see> class."
  syntax:
    content: public VisualBasicSettings ();
    parameters: []
  overload: Microsoft.VisualBasic.Activities.VisualBasicSettings.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings.Default
  id: Default
  parent: Microsoft.VisualBasic.Activities.VisualBasicSettings
  langs:
  - csharp
  name: Default
  nameWithType: VisualBasicSettings.Default
  fullName: Microsoft.VisualBasic.Activities.VisualBasicSettings.Default
  type: Property
  assemblies:
  - System.Activities
  namespace: Microsoft.VisualBasic.Activities
  summary: "Gets a <see cref=&quot;T:Microsoft.VisualBasic.Activities.VisualBasicSettings&quot;></see> that contains the default set of assembly references and imported namespaces. This set is available to all &lt;xref:Microsoft.VisualBasic.Activities.VisualBasicValue%601&gt; and &lt;xref:Microsoft.VisualBasic.Activities.VisualBasicReference%601&gt; instances in a given <see cref=&quot;T:System.AppDomain&quot;></see>."
  remarks: "The following table lists the default imported namespaces and assembly references.      |Imported Namespace|Assembly|   |------------------------|--------------|   |System|mscorlib|   |System|System|   |System.Collections|mscorlib|   |System.Collections.Generic|mscorlib|   |System.Collections.Generic|System|   |System.Activities|System.Activities|   |System.Activities.Statements|System.Activities|   |System.Activities.Expressions|System.Activities|"
  syntax:
    content: public static Microsoft.VisualBasic.Activities.VisualBasicSettings Default { get; }
    return:
      type: Microsoft.VisualBasic.Activities.VisualBasicSettings
      description: "A <see cref=&quot;T:Microsoft.VisualBasic.Activities.VisualBasicSettings&quot;></see> that contains the default set of assembly references and imported namespaces."
  overload: Microsoft.VisualBasic.Activities.VisualBasicSettings.Default*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings.ImportReferences
  id: ImportReferences
  parent: Microsoft.VisualBasic.Activities.VisualBasicSettings
  langs:
  - csharp
  name: ImportReferences
  nameWithType: VisualBasicSettings.ImportReferences
  fullName: Microsoft.VisualBasic.Activities.VisualBasicSettings.ImportReferences
  type: Property
  assemblies:
  - System.Activities
  namespace: Microsoft.VisualBasic.Activities
  summary: "Gets a collection of <see cref=&quot;T:Microsoft.VisualBasic.Activities.VisualBasicImportReference&quot;></see> objects, each of which represents an assembly reference and a namespace imported from that assembly."
  syntax:
    content: public System.Collections.Generic.ISet<Microsoft.VisualBasic.Activities.VisualBasicImportReference> ImportReferences { get; }
    return:
      type: System.Collections.Generic.ISet{Microsoft.VisualBasic.Activities.VisualBasicImportReference}
      description: "A collection of <see cref=&quot;T:Microsoft.VisualBasic.Activities.VisualBasicImportReference&quot;></see> objects, each of which represents an assembly reference and a namespace imported from that assembly."
  overload: Microsoft.VisualBasic.Activities.VisualBasicSettings.ImportReferences*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings.#ctor
  parent: Microsoft.VisualBasic.Activities.VisualBasicSettings
  isExternal: false
  name: VisualBasicSettings()
  nameWithType: VisualBasicSettings.VisualBasicSettings()
  fullName: Microsoft.VisualBasic.Activities.VisualBasicSettings.VisualBasicSettings()
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings.Default
  parent: Microsoft.VisualBasic.Activities.VisualBasicSettings
  isExternal: false
  name: Default
  nameWithType: VisualBasicSettings.Default
  fullName: Microsoft.VisualBasic.Activities.VisualBasicSettings.Default
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings
  parent: Microsoft.VisualBasic.Activities
  isExternal: false
  name: VisualBasicSettings
  nameWithType: VisualBasicSettings
  fullName: Microsoft.VisualBasic.Activities.VisualBasicSettings
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings.ImportReferences
  parent: Microsoft.VisualBasic.Activities.VisualBasicSettings
  isExternal: false
  name: ImportReferences
  nameWithType: VisualBasicSettings.ImportReferences
  fullName: Microsoft.VisualBasic.Activities.VisualBasicSettings.ImportReferences
- uid: System.Collections.Generic.ISet{Microsoft.VisualBasic.Activities.VisualBasicImportReference}
  parent: System.Collections.Generic
  isExternal: true
  name: ISet<VisualBasicImportReference>
  nameWithType: ISet<VisualBasicImportReference>
  fullName: System.Collections.Generic.ISet<Microsoft.VisualBasic.Activities.VisualBasicImportReference>
  spec.csharp:
  - uid: System.Collections.Generic.ISet`1
    name: ISet
    nameWithType: ISet
    fullName: ISet<Microsoft.VisualBasic.Activities.VisualBasicImportReference>
  - name: <
    nameWithType: <
    fullName: <
  - uid: Microsoft.VisualBasic.Activities.VisualBasicImportReference
    name: VisualBasicImportReference
    nameWithType: VisualBasicImportReference
    fullName: VisualBasicImportReference
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings.#ctor*
  parent: Microsoft.VisualBasic.Activities.VisualBasicSettings
  isExternal: false
  name: VisualBasicSettings
  nameWithType: VisualBasicSettings.VisualBasicSettings
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings.Default*
  parent: Microsoft.VisualBasic.Activities.VisualBasicSettings
  isExternal: false
  name: Default
  nameWithType: VisualBasicSettings.Default
- uid: Microsoft.VisualBasic.Activities.VisualBasicSettings.ImportReferences*
  parent: Microsoft.VisualBasic.Activities.VisualBasicSettings
  isExternal: false
  name: ImportReferences
  nameWithType: VisualBasicSettings.ImportReferences
