### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  id: ServiceModelActivationSectionGroup
  children:
  - System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.#ctor
  - System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.Diagnostics
  - System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.GetSectionGroup(System.Configuration.Configuration)
  - System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.NetPipe
  - System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.NetTcp
  langs:
  - csharp
  name: ServiceModelActivationSectionGroup
  nameWithType: ServiceModelActivationSectionGroup
  fullName: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  type: Class
  summary: "Contains the configuration section for the SMSvcHost.exe tool. This class cannot be inherited."
  remarks: "This class encapsulates the various configuration elements for the SMSvcHost.exe tool. Specifically, it represents the configuration elements that can be configured in the SMSvcHost.exe.config file."
  syntax:
    content: 'public sealed class ServiceModelActivationSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  langs:
  - csharp
  name: ServiceModelActivationSectionGroup()
  nameWithType: ServiceModelActivationSectionGroup.ServiceModelActivationSectionGroup()
  fullName: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.ServiceModelActivationSectionGroup()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup&quot;></see> class."
  syntax:
    content: public ServiceModelActivationSectionGroup ();
    parameters: []
  overload: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.Diagnostics
  id: Diagnostics
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  langs:
  - csharp
  name: Diagnostics
  nameWithType: ServiceModelActivationSectionGroup.Diagnostics
  fullName: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.Diagnostics
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "Gets the diagnostics configuration section."
  syntax:
    content: public System.ServiceModel.Activation.Configuration.DiagnosticSection Diagnostics { get; }
    return:
      type: System.ServiceModel.Activation.Configuration.DiagnosticSection
      description: "A <see cref=&quot;T:System.ServiceModel.Activation.Configuration.DiagnosticSection&quot;></see> instance that contains the diagnostics configuration section."
  overload: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.Diagnostics*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.GetSectionGroup(System.Configuration.Configuration)
  id: GetSectionGroup(System.Configuration.Configuration)
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  langs:
  - csharp
  name: GetSectionGroup(Configuration)
  nameWithType: ServiceModelActivationSectionGroup.GetSectionGroup(Configuration)
  fullName: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.GetSectionGroup(Configuration)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "Gets the <xref uid=&quot;langword_csharp_System.ServiceModel.Activation&quot; name=&quot;System.ServiceModel.Activation&quot; href=&quot;&quot;></xref> configuration section group from the specified configuration file."
  remarks: "You can use this method to extract the activation configuration settings from a configuration file."
  syntax:
    content: public static System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup GetSectionGroup (System.Configuration.Configuration config);
    parameters:
    - id: config
      type: System.Configuration.Configuration
      description: "A  that represents a configuration file."
    return:
      type: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
      description: "To be added."
  overload: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.GetSectionGroup*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.NetPipe
  id: NetPipe
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  langs:
  - csharp
  name: NetPipe
  nameWithType: ServiceModelActivationSectionGroup.NetPipe
  fullName: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.NetPipe
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "Gets the configuration settings for the NetPipeActivator sharing service."
  syntax:
    content: public System.ServiceModel.Activation.Configuration.NetPipeSection NetPipe { get; }
    return:
      type: System.ServiceModel.Activation.Configuration.NetPipeSection
      description: "A <see cref=&quot;T:System.ServiceModel.Activation.Configuration.NetPipeSection&quot;></see> that contains configuration settings for the NetPipeActivator sharing service."
  overload: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.NetPipe*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.NetTcp
  id: NetTcp
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  langs:
  - csharp
  name: NetTcp
  nameWithType: ServiceModelActivationSectionGroup.NetTcp
  fullName: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.NetTcp
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "Gets the configuration settings for the NetTcpPortSharing sharing service."
  syntax:
    content: public System.ServiceModel.Activation.Configuration.NetTcpSection NetTcp { get; }
    return:
      type: System.ServiceModel.Activation.Configuration.NetTcpSection
      description: "A <see cref=&quot;T:System.ServiceModel.Activation.Configuration.NetTcpSection&quot;></see> that contains configuration settings for the NetTcpPortSharing sharing service."
  overload: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.NetTcp*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: System.Configuration.ConfigurationSectionGroup
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.#ctor
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  isExternal: false
  name: ServiceModelActivationSectionGroup()
  nameWithType: ServiceModelActivationSectionGroup.ServiceModelActivationSectionGroup()
  fullName: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.ServiceModelActivationSectionGroup()
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.Diagnostics
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  isExternal: false
  name: Diagnostics
  nameWithType: ServiceModelActivationSectionGroup.Diagnostics
  fullName: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.Diagnostics
- uid: System.ServiceModel.Activation.Configuration.DiagnosticSection
  parent: System.ServiceModel.Activation.Configuration
  isExternal: false
  name: DiagnosticSection
  nameWithType: DiagnosticSection
  fullName: System.ServiceModel.Activation.Configuration.DiagnosticSection
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.GetSectionGroup(System.Configuration.Configuration)
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  isExternal: false
  name: GetSectionGroup(Configuration)
  nameWithType: ServiceModelActivationSectionGroup.GetSectionGroup(Configuration)
  fullName: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.GetSectionGroup(Configuration)
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  parent: System.ServiceModel.Activation.Configuration
  isExternal: false
  name: ServiceModelActivationSectionGroup
  nameWithType: ServiceModelActivationSectionGroup
  fullName: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
- uid: System.Configuration.Configuration
  parent: System.Configuration
  isExternal: false
  name: Configuration
  nameWithType: Configuration
  fullName: System.Configuration.Configuration
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.NetPipe
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  isExternal: false
  name: NetPipe
  nameWithType: ServiceModelActivationSectionGroup.NetPipe
  fullName: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.NetPipe
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection
  parent: System.ServiceModel.Activation.Configuration
  isExternal: false
  name: NetPipeSection
  nameWithType: NetPipeSection
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.NetTcp
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  isExternal: false
  name: NetTcp
  nameWithType: ServiceModelActivationSectionGroup.NetTcp
  fullName: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.NetTcp
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection
  parent: System.ServiceModel.Activation.Configuration
  isExternal: false
  name: NetTcpSection
  nameWithType: NetTcpSection
  fullName: System.ServiceModel.Activation.Configuration.NetTcpSection
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.#ctor*
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  isExternal: false
  name: ServiceModelActivationSectionGroup
  nameWithType: ServiceModelActivationSectionGroup.ServiceModelActivationSectionGroup
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.Diagnostics*
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  isExternal: false
  name: Diagnostics
  nameWithType: ServiceModelActivationSectionGroup.Diagnostics
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.GetSectionGroup*
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  isExternal: false
  name: GetSectionGroup
  nameWithType: ServiceModelActivationSectionGroup.GetSectionGroup
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.NetPipe*
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  isExternal: false
  name: NetPipe
  nameWithType: ServiceModelActivationSectionGroup.NetPipe
- uid: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup.NetTcp*
  parent: System.ServiceModel.Activation.Configuration.ServiceModelActivationSectionGroup
  isExternal: false
  name: NetTcp
  nameWithType: ServiceModelActivationSectionGroup.NetTcp
