### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsGroupDescriptionAttribute
  id: SettingsGroupDescriptionAttribute
  children:
  - System.Configuration.SettingsGroupDescriptionAttribute.#ctor(System.String)
  - System.Configuration.SettingsGroupDescriptionAttribute.Description
  langs:
  - csharp
  name: SettingsGroupDescriptionAttribute
  nameWithType: SettingsGroupDescriptionAttribute
  fullName: System.Configuration.SettingsGroupDescriptionAttribute
  type: Class
  summary: "Provides a string that describes an application settings property group. This class cannot be inherited."
  remarks: "An application settings class, derived from <xref:System.Configuration.ApplicationSettingsBase>, defines one or more properties that belong to the same application property group. SettingsGroupDescriptionAttribute is an optional attribute that you can use to provide descriptive text for a settings property group. This text is intended to assist both design-time tools and administrative run-time tools in identifying and describing the associated property group.      > [!NOTE] >  This attribute can only be applied at the wrapper class level."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class)]

      public sealed class SettingsGroupDescriptionAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SettingsGroupDescriptionAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  langs:
  - csharp
  name: SettingsGroupDescriptionAttribute(String)
  nameWithType: SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute(String)
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.SettingsGroupDescriptionAttribute&quot;></see> class."
  remarks: "Although the theoretical maximum length of the `description` parameter is constrained by the upper bounds of an <xref:System.Int32>, practical limits, determined by usability and quota limitations imposed by the settings provider, will be much smaller."
  syntax:
    content: public SettingsGroupDescriptionAttribute (string description);
    parameters:
    - id: description
      type: System.String
      description: "A <xref:System.String> containing the descriptive text for the application settings group."
  overload: System.Configuration.SettingsGroupDescriptionAttribute.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SettingsGroupDescriptionAttribute.Description
  id: Description
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  langs:
  - csharp
  name: Description
  nameWithType: SettingsGroupDescriptionAttribute.Description
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.Description
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "The descriptive text for the application settings properties group."
  remarks: "The Description property value is set in the <xref:System.Configuration.SettingsGroupDescriptionAttribute.%23ctor%2A> constructor."
  syntax:
    content: public string Description { get; }
    return:
      type: System.String
      description: "A &lt;xref:System.String&gt; containing the descriptive text for the application settings group."
  overload: System.Configuration.SettingsGroupDescriptionAttribute.Description*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsGroupDescriptionAttribute.#ctor(System.String)
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  isExternal: false
  name: SettingsGroupDescriptionAttribute(String)
  nameWithType: SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute(String)
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsGroupDescriptionAttribute.Description
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  isExternal: false
  name: Description
  nameWithType: SettingsGroupDescriptionAttribute.Description
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.Description
- uid: System.Configuration.SettingsGroupDescriptionAttribute.#ctor*
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  isExternal: false
  name: SettingsGroupDescriptionAttribute
  nameWithType: SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute
- uid: System.Configuration.SettingsGroupDescriptionAttribute.Description*
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  isExternal: false
  name: Description
  nameWithType: SettingsGroupDescriptionAttribute.Description
