### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConnectionStringsSection
  id: ConnectionStringsSection
  children:
  - System.Configuration.ConnectionStringsSection.#ctor
  - System.Configuration.ConnectionStringsSection.ConnectionStrings
  - System.Configuration.ConnectionStringsSection.GetRuntimeObject
  - System.Configuration.ConnectionStringsSection.Properties
  langs:
  - csharp
  name: ConnectionStringsSection
  nameWithType: ConnectionStringsSection
  fullName: System.Configuration.ConnectionStringsSection
  type: Class
  summary: "Provides programmatic access to the connection strings configuration-file section."
  remarks: "The ConnectionStringsSection class allows you to programmatically modify the `connectionStrings` section of the configuration file. The connection strings are provided as a <xref:System.Configuration.ConnectionStringSettingsCollection> of <xref:System.Configuration.ConnectionStringSettings>`add` configuration elements."
  example:
  - "The following example shows how to use the ConnectionStringsSection.  \n  \n [!code-cs[System.Configuration.ConnectionStrings#1](~/add/codesnippet/CSharp/t-system.configuration.c_17_1.cs)]\n [!code-vb[System.Configuration.ConnectionStrings#1](~/add/codesnippet/VisualBasic/t-system.configuration.c_17_1.vb)]  \n  \n The following excerpt shows the configuration used by the previous example.  \n  \n```  \n<?xml version=\"1.0\" encoding=\"utf-8\"?>  \n<configuration>  \n  <connectionStrings>  \n    <add name=\"ConnStr1\" connectionString=\"LocalSqlServer: data source=127.0.0.1;Integrated Security=SSPI;Initial Catalog=aspnetdb\"  \n      providerName=\"System.Data.SqlClient\" />  \n  </connectionStrings>  \n</configuration>  \n```"
  syntax:
    content: 'public sealed class ConnectionStringsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConnectionStringsSection.#ctor
  id: '#ctor'
  parent: System.Configuration.ConnectionStringsSection
  langs:
  - csharp
  name: ConnectionStringsSection()
  nameWithType: ConnectionStringsSection.ConnectionStringsSection()
  fullName: System.Configuration.ConnectionStringsSection.ConnectionStringsSection()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.ConnectionStringsSection&quot;></see> class."
  syntax:
    content: public ConnectionStringsSection ();
    parameters: []
  overload: System.Configuration.ConnectionStringsSection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConnectionStringsSection.ConnectionStrings
  id: ConnectionStrings
  parent: System.Configuration.ConnectionStringsSection
  langs:
  - csharp
  name: ConnectionStrings
  nameWithType: ConnectionStringsSection.ConnectionStrings
  fullName: System.Configuration.ConnectionStringsSection.ConnectionStrings
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets a <see cref=&quot;T:System.Configuration.ConnectionStringSettingsCollection&quot;></see> collection of <see cref=&quot;T:System.Configuration.ConnectionStringSettings&quot;></see> objects."
  remarks: ''
  example:
  - "The following example shows how to use the ConnectionStrings property of the <xref:System.Configuration.ConnectionStringsSection> object.  \n  \n [!code-cs[System.Configuration.ConnectionStrings#2](~/add/codesnippet/CSharp/p-system.configuration.c_25_1.cs)]\n [!code-vb[System.Configuration.ConnectionStrings#2](~/add/codesnippet/VisualBasic/p-system.configuration.c_25_1.vb)]"
  syntax:
    content: public System.Configuration.ConnectionStringSettingsCollection ConnectionStrings { get; }
    return:
      type: System.Configuration.ConnectionStringSettingsCollection
      description: "A <see cref=&quot;T:System.Configuration.ConnectionStringSettingsCollection&quot;></see> collection of <see cref=&quot;T:System.Configuration.ConnectionStringSettings&quot;></see> objects."
  overload: System.Configuration.ConnectionStringsSection.ConnectionStrings*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConnectionStringsSection.GetRuntimeObject
  id: GetRuntimeObject
  parent: System.Configuration.ConnectionStringsSection
  langs:
  - csharp
  name: GetRuntimeObject()
  nameWithType: ConnectionStringsSection.GetRuntimeObject()
  fullName: System.Configuration.ConnectionStringsSection.GetRuntimeObject()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: protected override object GetRuntimeObject ();
    parameters: []
    return:
      type: System.Object
      description: "To be added."
  overload: System.Configuration.ConnectionStringsSection.GetRuntimeObject*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConnectionStringsSection.Properties
  id: Properties
  parent: System.Configuration.ConnectionStringsSection
  langs:
  - csharp
  name: Properties
  nameWithType: ConnectionStringsSection.Properties
  fullName: System.Configuration.ConnectionStringsSection.Properties
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Configuration.ConnectionStringsSection.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Configuration.ConnectionStringsSection.#ctor
  parent: System.Configuration.ConnectionStringsSection
  isExternal: false
  name: ConnectionStringsSection()
  nameWithType: ConnectionStringsSection.ConnectionStringsSection()
  fullName: System.Configuration.ConnectionStringsSection.ConnectionStringsSection()
- uid: System.Configuration.ConnectionStringsSection.ConnectionStrings
  parent: System.Configuration.ConnectionStringsSection
  isExternal: false
  name: ConnectionStrings
  nameWithType: ConnectionStringsSection.ConnectionStrings
  fullName: System.Configuration.ConnectionStringsSection.ConnectionStrings
- uid: System.Configuration.ConnectionStringSettingsCollection
  parent: System.Configuration
  isExternal: false
  name: ConnectionStringSettingsCollection
  nameWithType: ConnectionStringSettingsCollection
  fullName: System.Configuration.ConnectionStringSettingsCollection
- uid: System.Configuration.ConnectionStringsSection.GetRuntimeObject
  parent: System.Configuration.ConnectionStringsSection
  isExternal: false
  name: GetRuntimeObject()
  nameWithType: ConnectionStringsSection.GetRuntimeObject()
  fullName: System.Configuration.ConnectionStringsSection.GetRuntimeObject()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.ConnectionStringsSection.Properties
  parent: System.Configuration.ConnectionStringsSection
  isExternal: false
  name: Properties
  nameWithType: ConnectionStringsSection.Properties
  fullName: System.Configuration.ConnectionStringsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Configuration.ConnectionStringsSection.#ctor*
  parent: System.Configuration.ConnectionStringsSection
  isExternal: false
  name: ConnectionStringsSection
  nameWithType: ConnectionStringsSection.ConnectionStringsSection
- uid: System.Configuration.ConnectionStringsSection.ConnectionStrings*
  parent: System.Configuration.ConnectionStringsSection
  isExternal: false
  name: ConnectionStrings
  nameWithType: ConnectionStringsSection.ConnectionStrings
- uid: System.Configuration.ConnectionStringsSection.GetRuntimeObject*
  parent: System.Configuration.ConnectionStringsSection
  isExternal: false
  name: GetRuntimeObject
  nameWithType: ConnectionStringsSection.GetRuntimeObject
- uid: System.Configuration.ConnectionStringsSection.Properties*
  parent: System.Configuration.ConnectionStringsSection
  isExternal: false
  name: Properties
  nameWithType: ConnectionStringsSection.Properties
