### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.BuildProvider
  id: BuildProvider
  children:
  - System.Web.Configuration.BuildProvider.#ctor(System.String,System.String)
  - System.Web.Configuration.BuildProvider.Equals(System.Object)
  - System.Web.Configuration.BuildProvider.Extension
  - System.Web.Configuration.BuildProvider.GetHashCode
  - System.Web.Configuration.BuildProvider.Properties
  - System.Web.Configuration.BuildProvider.Type
  langs:
  - csharp
  name: BuildProvider
  nameWithType: BuildProvider
  fullName: System.Web.Configuration.BuildProvider
  type: Class
  summary: "Provides functionality to parse a particular file type and generate code during compilation of a dynamic resource. This class cannot be inherited."
  syntax:
    content: 'public sealed class BuildProvider : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.BuildProvider.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.BuildProvider
  langs:
  - csharp
  name: BuildProvider(String,String)
  nameWithType: BuildProvider.BuildProvider(String,String)
  fullName: System.Web.Configuration.BuildProvider.BuildProvider(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Creates an instance of a <see cref=&quot;T:System.Web.Configuration.BuildProvider&quot;></see> class, initialized to the provided values."
  syntax:
    content: public BuildProvider (string extension, string type);
    parameters:
    - id: extension
      type: System.String
      description: "The file extension of the dynamic resource used during compilation."
    - id: type
      type: System.String
      description: "The type that represents the  instance to use when parsing and compiling the given extension."
  overload: System.Web.Configuration.BuildProvider.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.BuildProvider.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.Web.Configuration.BuildProvider
  langs:
  - csharp
  name: Equals(Object)
  nameWithType: BuildProvider.Equals(Object)
  fullName: System.Web.Configuration.BuildProvider.Equals(Object)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Determines whether the specified build provider object is equal to the current object."
  remarks: "The serializer uses this method to determine whether the same object already exists in the parent collection and whether it needs to be serialized at a lower level if it is not inherited."
  syntax:
    content: public override bool Equals (object provider);
    parameters:
    - id: provider
      type: System.Object
      description: "The build provider object to compare with the current object."
    return:
      type: System.Boolean
      description: "To be added."
  overload: System.Web.Configuration.BuildProvider.Equals*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.BuildProvider.Extension
  id: Extension
  parent: System.Web.Configuration.BuildProvider
  langs:
  - csharp
  name: Extension
  nameWithType: BuildProvider.Extension
  fullName: System.Web.Configuration.BuildProvider.Extension
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets or sets the file extension to map to during compilation of a dynamic resource."
  syntax:
    content: public string Extension { get; set; }
    return:
      type: System.String
      description: "A string specifying the file extension to map to during compilation of a dynamic resource."
  overload: System.Web.Configuration.BuildProvider.Extension*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.BuildProvider.GetHashCode
  id: GetHashCode
  parent: System.Web.Configuration.BuildProvider
  langs:
  - csharp
  name: GetHashCode()
  nameWithType: BuildProvider.GetHashCode()
  fullName: System.Web.Configuration.BuildProvider.GetHashCode()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Generates the hash code for the build provider."
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: "To be added."
  overload: System.Web.Configuration.BuildProvider.GetHashCode*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.BuildProvider.Properties
  id: Properties
  parent: System.Web.Configuration.BuildProvider
  langs:
  - csharp
  name: Properties
  nameWithType: BuildProvider.Properties
  fullName: System.Web.Configuration.BuildProvider.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Web.Configuration.BuildProvider.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.BuildProvider.Type
  id: Type
  parent: System.Web.Configuration.BuildProvider
  langs:
  - csharp
  name: Type
  nameWithType: BuildProvider.Type
  fullName: System.Web.Configuration.BuildProvider.Type
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets or set the comma-separated class and assembly combination that indicates the <see cref=&quot;T:System.Web.Configuration.BuildProvider&quot;></see> instance to use."
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "A comma-separated class and assembly combination that indicates the <see cref=&quot;T:System.Web.Configuration.BuildProvider&quot;></see> instance to use."
  overload: System.Web.Configuration.BuildProvider.Type*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.BuildProvider.#ctor(System.String,System.String)
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: BuildProvider(String,String)
  nameWithType: BuildProvider.BuildProvider(String,String)
  fullName: System.Web.Configuration.BuildProvider.BuildProvider(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.BuildProvider.Equals(System.Object)
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Equals(Object)
  nameWithType: BuildProvider.Equals(Object)
  fullName: System.Web.Configuration.BuildProvider.Equals(Object)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.BuildProvider.Extension
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Extension
  nameWithType: BuildProvider.Extension
  fullName: System.Web.Configuration.BuildProvider.Extension
- uid: System.Web.Configuration.BuildProvider.GetHashCode
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: GetHashCode()
  nameWithType: BuildProvider.GetHashCode()
  fullName: System.Web.Configuration.BuildProvider.GetHashCode()
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.BuildProvider.Properties
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Properties
  nameWithType: BuildProvider.Properties
  fullName: System.Web.Configuration.BuildProvider.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.BuildProvider.Type
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Type
  nameWithType: BuildProvider.Type
  fullName: System.Web.Configuration.BuildProvider.Type
- uid: System.Web.Configuration.BuildProvider.#ctor*
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: BuildProvider
  nameWithType: BuildProvider.BuildProvider
- uid: System.Web.Configuration.BuildProvider.Equals*
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Equals
  nameWithType: BuildProvider.Equals
- uid: System.Web.Configuration.BuildProvider.Extension*
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Extension
  nameWithType: BuildProvider.Extension
- uid: System.Web.Configuration.BuildProvider.GetHashCode*
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: GetHashCode
  nameWithType: BuildProvider.GetHashCode
- uid: System.Web.Configuration.BuildProvider.Properties*
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Properties
  nameWithType: BuildProvider.Properties
- uid: System.Web.Configuration.BuildProvider.Type*
  parent: System.Web.Configuration.BuildProvider
  isExternal: false
  name: Type
  nameWithType: BuildProvider.Type
