### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.RegistrationConfig
  id: RegistrationConfig
  children:
  - System.EnterpriseServices.RegistrationConfig.#ctor
  - System.EnterpriseServices.RegistrationConfig.Application
  - System.EnterpriseServices.RegistrationConfig.ApplicationRootDirectory
  - System.EnterpriseServices.RegistrationConfig.AssemblyFile
  - System.EnterpriseServices.RegistrationConfig.InstallationFlags
  - System.EnterpriseServices.RegistrationConfig.Partition
  - System.EnterpriseServices.RegistrationConfig.TypeLibrary
  langs:
  - csharp
  name: RegistrationConfig
  nameWithType: RegistrationConfig
  fullName: System.EnterpriseServices.RegistrationConfig
  type: Class
  summary: "Provides configuration information for installing assemblies into the COM+ catalog."
  syntax:
    content: >-
      [System.Runtime.InteropServices.Guid("36dcda30-dc3b-4d93-be42-90b2d74c64e7")]

      public class RegistrationConfig
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.EnterpriseServices.RegistrationConfig.#ctor
  id: '#ctor'
  parent: System.EnterpriseServices.RegistrationConfig
  langs:
  - csharp
  name: RegistrationConfig()
  nameWithType: RegistrationConfig.RegistrationConfig()
  fullName: System.EnterpriseServices.RegistrationConfig.RegistrationConfig()
  type: Constructor
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "Initializes a new instance of the <see cref=&quot;T:System.EnterpriseServices.RegistrationConfig&quot;></see> class."
  syntax:
    content: public RegistrationConfig ();
    parameters: []
  overload: System.EnterpriseServices.RegistrationConfig.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.EnterpriseServices.RegistrationConfig.Application
  id: Application
  parent: System.EnterpriseServices.RegistrationConfig
  langs:
  - csharp
  name: Application
  nameWithType: RegistrationConfig.Application
  fullName: System.EnterpriseServices.RegistrationConfig.Application
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "Gets or sets the name of the COM+ application in which the assembly is to be installed."
  syntax:
    content: public string Application { get; set; }
    return:
      type: System.String
      description: "The name of the COM+ application in which the assembly is to be installed."
  overload: System.EnterpriseServices.RegistrationConfig.Application*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.EnterpriseServices.RegistrationConfig.ApplicationRootDirectory
  id: ApplicationRootDirectory
  parent: System.EnterpriseServices.RegistrationConfig
  langs:
  - csharp
  name: ApplicationRootDirectory
  nameWithType: RegistrationConfig.ApplicationRootDirectory
  fullName: System.EnterpriseServices.RegistrationConfig.ApplicationRootDirectory
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "Gets or sets the name of the root directory of the application."
  syntax:
    content: public string ApplicationRootDirectory { get; set; }
    return:
      type: System.String
      description: "The name of the root directory of the application."
  overload: System.EnterpriseServices.RegistrationConfig.ApplicationRootDirectory*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.EnterpriseServices.RegistrationConfig.AssemblyFile
  id: AssemblyFile
  parent: System.EnterpriseServices.RegistrationConfig
  langs:
  - csharp
  name: AssemblyFile
  nameWithType: RegistrationConfig.AssemblyFile
  fullName: System.EnterpriseServices.RegistrationConfig.AssemblyFile
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "Gets or sets the file name of the assembly to install."
  syntax:
    content: public string AssemblyFile { get; set; }
    return:
      type: System.String
      description: "The file name of the assembly to install."
  overload: System.EnterpriseServices.RegistrationConfig.AssemblyFile*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.EnterpriseServices.RegistrationConfig.InstallationFlags
  id: InstallationFlags
  parent: System.EnterpriseServices.RegistrationConfig
  langs:
  - csharp
  name: InstallationFlags
  nameWithType: RegistrationConfig.InstallationFlags
  fullName: System.EnterpriseServices.RegistrationConfig.InstallationFlags
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "Gets or sets a flag that indicates how to install the assembly."
  syntax:
    content: public System.EnterpriseServices.InstallationFlags InstallationFlags { get; set; }
    return:
      type: System.EnterpriseServices.InstallationFlags
      description: "One of the <see cref=&quot;T:System.EnterpriseServices.InstallationFlags&quot;></see> values."
  overload: System.EnterpriseServices.RegistrationConfig.InstallationFlags*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.EnterpriseServices.RegistrationConfig.Partition
  id: Partition
  parent: System.EnterpriseServices.RegistrationConfig
  langs:
  - csharp
  name: Partition
  nameWithType: RegistrationConfig.Partition
  fullName: System.EnterpriseServices.RegistrationConfig.Partition
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "Gets or sets the name of the COM+ partition."
  syntax:
    content: public string Partition { get; set; }
    return:
      type: System.String
      description: "The name of the COM+ partition."
  overload: System.EnterpriseServices.RegistrationConfig.Partition*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.EnterpriseServices.RegistrationConfig.TypeLibrary
  id: TypeLibrary
  parent: System.EnterpriseServices.RegistrationConfig
  langs:
  - csharp
  name: TypeLibrary
  nameWithType: RegistrationConfig.TypeLibrary
  fullName: System.EnterpriseServices.RegistrationConfig.TypeLibrary
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "Gets or sets the name of the output Type Library Exporter (Tlbexp.exe) file."
  syntax:
    content: public string TypeLibrary { get; set; }
    return:
      type: System.String
      description: "The name of the output Type Library Exporter (Tlbexp.exe) file."
  overload: System.EnterpriseServices.RegistrationConfig.TypeLibrary*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.EnterpriseServices.RegistrationConfig.#ctor
  parent: System.EnterpriseServices.RegistrationConfig
  isExternal: false
  name: RegistrationConfig()
  nameWithType: RegistrationConfig.RegistrationConfig()
  fullName: System.EnterpriseServices.RegistrationConfig.RegistrationConfig()
- uid: System.EnterpriseServices.RegistrationConfig.Application
  parent: System.EnterpriseServices.RegistrationConfig
  isExternal: false
  name: Application
  nameWithType: RegistrationConfig.Application
  fullName: System.EnterpriseServices.RegistrationConfig.Application
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.EnterpriseServices.RegistrationConfig.ApplicationRootDirectory
  parent: System.EnterpriseServices.RegistrationConfig
  isExternal: false
  name: ApplicationRootDirectory
  nameWithType: RegistrationConfig.ApplicationRootDirectory
  fullName: System.EnterpriseServices.RegistrationConfig.ApplicationRootDirectory
- uid: System.EnterpriseServices.RegistrationConfig.AssemblyFile
  parent: System.EnterpriseServices.RegistrationConfig
  isExternal: false
  name: AssemblyFile
  nameWithType: RegistrationConfig.AssemblyFile
  fullName: System.EnterpriseServices.RegistrationConfig.AssemblyFile
- uid: System.EnterpriseServices.RegistrationConfig.InstallationFlags
  parent: System.EnterpriseServices.RegistrationConfig
  isExternal: false
  name: InstallationFlags
  nameWithType: RegistrationConfig.InstallationFlags
  fullName: System.EnterpriseServices.RegistrationConfig.InstallationFlags
- uid: System.EnterpriseServices.InstallationFlags
  parent: System.EnterpriseServices
  isExternal: false
  name: InstallationFlags
  nameWithType: InstallationFlags
  fullName: System.EnterpriseServices.InstallationFlags
- uid: System.EnterpriseServices.RegistrationConfig.Partition
  parent: System.EnterpriseServices.RegistrationConfig
  isExternal: false
  name: Partition
  nameWithType: RegistrationConfig.Partition
  fullName: System.EnterpriseServices.RegistrationConfig.Partition
- uid: System.EnterpriseServices.RegistrationConfig.TypeLibrary
  parent: System.EnterpriseServices.RegistrationConfig
  isExternal: false
  name: TypeLibrary
  nameWithType: RegistrationConfig.TypeLibrary
  fullName: System.EnterpriseServices.RegistrationConfig.TypeLibrary
- uid: System.EnterpriseServices.RegistrationConfig.#ctor*
  parent: System.EnterpriseServices.RegistrationConfig
  isExternal: false
  name: RegistrationConfig
  nameWithType: RegistrationConfig.RegistrationConfig
- uid: System.EnterpriseServices.RegistrationConfig.Application*
  parent: System.EnterpriseServices.RegistrationConfig
  isExternal: false
  name: Application
  nameWithType: RegistrationConfig.Application
- uid: System.EnterpriseServices.RegistrationConfig.ApplicationRootDirectory*
  parent: System.EnterpriseServices.RegistrationConfig
  isExternal: false
  name: ApplicationRootDirectory
  nameWithType: RegistrationConfig.ApplicationRootDirectory
- uid: System.EnterpriseServices.RegistrationConfig.AssemblyFile*
  parent: System.EnterpriseServices.RegistrationConfig
  isExternal: false
  name: AssemblyFile
  nameWithType: RegistrationConfig.AssemblyFile
- uid: System.EnterpriseServices.RegistrationConfig.InstallationFlags*
  parent: System.EnterpriseServices.RegistrationConfig
  isExternal: false
  name: InstallationFlags
  nameWithType: RegistrationConfig.InstallationFlags
- uid: System.EnterpriseServices.RegistrationConfig.Partition*
  parent: System.EnterpriseServices.RegistrationConfig
  isExternal: false
  name: Partition
  nameWithType: RegistrationConfig.Partition
- uid: System.EnterpriseServices.RegistrationConfig.TypeLibrary*
  parent: System.EnterpriseServices.RegistrationConfig
  isExternal: false
  name: TypeLibrary
  nameWithType: RegistrationConfig.TypeLibrary
