### YamlMime:ManagedReference
items:
- uid: System.Web.UI.ValidationSettings
  id: ValidationSettings
  children:
  - System.Web.UI.ValidationSettings.UnobtrusiveValidationMode
  langs:
  - csharp
  name: ValidationSettings
  nameWithType: ValidationSettings
  fullName: System.Web.UI.ValidationSettings
  type: Class
  summary: "Provides client validation settings for the application."
  syntax:
    content: public static class ValidationSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.UI.ValidationSettings.UnobtrusiveValidationMode
  id: UnobtrusiveValidationMode
  parent: System.Web.UI.ValidationSettings
  langs:
  - csharp
  name: UnobtrusiveValidationMode
  nameWithType: ValidationSettings.UnobtrusiveValidationMode
  fullName: System.Web.UI.ValidationSettings.UnobtrusiveValidationMode
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.UI
  summary: "Gets or sets the client validation mode for the application."
  syntax:
    content: public static System.Web.UI.UnobtrusiveValidationMode UnobtrusiveValidationMode { get; set; }
    return:
      type: System.Web.UI.UnobtrusiveValidationMode
      description: "The client validation mode for the application."
  overload: System.Web.UI.ValidationSettings.UnobtrusiveValidationMode*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.UI.ValidationSettings.UnobtrusiveValidationMode
  parent: System.Web.UI.ValidationSettings
  isExternal: false
  name: UnobtrusiveValidationMode
  nameWithType: ValidationSettings.UnobtrusiveValidationMode
  fullName: System.Web.UI.ValidationSettings.UnobtrusiveValidationMode
- uid: System.Web.UI.UnobtrusiveValidationMode
  parent: System.Web.UI
  isExternal: false
  name: UnobtrusiveValidationMode
  nameWithType: UnobtrusiveValidationMode
  fullName: System.Web.UI.UnobtrusiveValidationMode
- uid: System.Web.UI.ValidationSettings.UnobtrusiveValidationMode*
  parent: System.Web.UI.ValidationSettings
  isExternal: false
  name: UnobtrusiveValidationMode
  nameWithType: ValidationSettings.UnobtrusiveValidationMode
