### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.WebApplicationLevel
  id: WebApplicationLevel
  children:
  - System.Web.Configuration.WebApplicationLevel.AboveApplication
  - System.Web.Configuration.WebApplicationLevel.AtApplication
  - System.Web.Configuration.WebApplicationLevel.BelowApplication
  langs:
  - csharp
  name: WebApplicationLevel
  nameWithType: WebApplicationLevel
  fullName: System.Web.Configuration.WebApplicationLevel
  type: Enum
  summary: "Specifies the path level of a Web-application configuration file."
  remarks: "The WebApplicationLevel class provides three levels that are used to distinguish where a configuration file is in relation to the root level of an ASP.NET Web application. The three path-level types are AboveApplication, AtApplication, and BelowApplication."
  syntax:
    content: public enum WebApplicationLevel
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.WebApplicationLevel.AboveApplication
  id: AboveApplication
  parent: System.Web.Configuration.WebApplicationLevel
  langs:
  - csharp
  name: AboveApplication
  nameWithType: WebApplicationLevel.AboveApplication
  fullName: System.Web.Configuration.WebApplicationLevel.AboveApplication
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifies that the configuration file is in a global directory in relation to the current ASP.NET Web application."
  syntax:
    content: AboveApplication
    return:
      type: System.Web.Configuration.WebApplicationLevel
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.WebApplicationLevel.AtApplication
  id: AtApplication
  parent: System.Web.Configuration.WebApplicationLevel
  langs:
  - csharp
  name: AtApplication
  nameWithType: WebApplicationLevel.AtApplication
  fullName: System.Web.Configuration.WebApplicationLevel.AtApplication
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifies that the configuration file is in the root directory of the current ASP.NET Web application."
  syntax:
    content: AtApplication
    return:
      type: System.Web.Configuration.WebApplicationLevel
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.WebApplicationLevel.BelowApplication
  id: BelowApplication
  parent: System.Web.Configuration.WebApplicationLevel
  langs:
  - csharp
  name: BelowApplication
  nameWithType: WebApplicationLevel.BelowApplication
  fullName: System.Web.Configuration.WebApplicationLevel.BelowApplication
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifies that the configuration file is in a sub-directory of the current ASP.NET Web application."
  syntax:
    content: BelowApplication
    return:
      type: System.Web.Configuration.WebApplicationLevel
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.WebApplicationLevel.AboveApplication
  parent: System.Web.Configuration.WebApplicationLevel
  isExternal: false
  name: AboveApplication
  nameWithType: WebApplicationLevel.AboveApplication
  fullName: System.Web.Configuration.WebApplicationLevel.AboveApplication
- uid: System.Web.Configuration.WebApplicationLevel
  parent: System.Web.Configuration
  isExternal: false
  name: WebApplicationLevel
  nameWithType: WebApplicationLevel
  fullName: System.Web.Configuration.WebApplicationLevel
- uid: System.Web.Configuration.WebApplicationLevel.AtApplication
  parent: System.Web.Configuration.WebApplicationLevel
  isExternal: false
  name: AtApplication
  nameWithType: WebApplicationLevel.AtApplication
  fullName: System.Web.Configuration.WebApplicationLevel.AtApplication
- uid: System.Web.Configuration.WebApplicationLevel.BelowApplication
  parent: System.Web.Configuration.WebApplicationLevel
  isExternal: false
  name: BelowApplication
  nameWithType: WebApplicationLevel.BelowApplication
  fullName: System.Web.Configuration.WebApplicationLevel.BelowApplication
