### YamlMime:ManagedReference
items:
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  id: ITransformerConfigurationControl
  children:
  - System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
  - System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
  langs:
  - csharp
  name: ITransformerConfigurationControl
  nameWithType: ITransformerConfigurationControl
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  type: Interface
  summary: "Defines the contract a control implements to act as a configuration control for a transformer in a Web Parts connection."
  remarks: "A configuration control can be displayed when a transformer requires a user to configure it. The configuration control provides a user interface (UI) that allows the user to select which values will be transformed. It is rendered in a connections zone. The <xref:System.Web.UI.WebControls.WebParts.WebPartTransformer.CreateConfigurationControl%2A?displayProperty=fullName> method returns a configuration control.       You can override the <xref:System.Web.UI.WebControls.WebParts.WebPartTransformer.CreateConfigurationControl%2A> method when your transformer requires a customized UI. The configuration control must implement the ITransformerConfigurationControl interface, which includes the <xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled> and <xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded> events. These events occur when a transformer control was either not configured or configured successfully, respectively."
  syntax:
    content: public interface ITransformerConfigurationControl
  implements: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
  id: Cancelled
  parent: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  langs:
  - csharp
  name: Cancelled
  nameWithType: ITransformerConfigurationControl.Cancelled
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
  type: Event
  assemblies:
  - System.Web
  namespace: System.Web.UI.WebControls.WebParts
  summary: "Occurs when transformer configuration is not completed."
  remarks: "The Web Parts control that implements <xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl> raises this event when a transformer configuration is not completed, either because the user canceled the configuration or because the configuration could not be performed."
  syntax:
    content: public event EventHandler Cancelled;
    return:
      type: System.EventHandler
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
  id: Succeeded
  parent: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  langs:
  - csharp
  name: Succeeded
  nameWithType: ITransformerConfigurationControl.Succeeded
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
  type: Event
  assemblies:
  - System.Web
  namespace: System.Web.UI.WebControls.WebParts
  summary: "Occurs when transformer configuration is successfully completed."
  remarks: "The Web Parts control that implements <xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl> raises this event when a transformer configuration is successfully completed."
  syntax:
    content: public event EventHandler Succeeded;
    return:
      type: System.EventHandler
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
  parent: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  isExternal: false
  name: Cancelled
  nameWithType: ITransformerConfigurationControl.Cancelled
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
- uid: System.EventHandler
  parent: System
  isExternal: true
  name: EventHandler
  nameWithType: EventHandler
  fullName: System.EventHandler
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
  parent: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  isExternal: false
  name: Succeeded
  nameWithType: ITransformerConfigurationControl.Succeeded
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
