### YamlMime:ManagedReference
items:
- uid: System.Configuration.TimeSpanValidatorAttribute
  id: TimeSpanValidatorAttribute
  children:
  - System.Configuration.TimeSpanValidatorAttribute.#ctor
  - System.Configuration.TimeSpanValidatorAttribute.ExcludeRange
  - System.Configuration.TimeSpanValidatorAttribute.MaxValue
  - System.Configuration.TimeSpanValidatorAttribute.MaxValueString
  - System.Configuration.TimeSpanValidatorAttribute.MinValue
  - System.Configuration.TimeSpanValidatorAttribute.MinValueString
  - System.Configuration.TimeSpanValidatorAttribute.TimeSpanMaxValue
  - System.Configuration.TimeSpanValidatorAttribute.TimeSpanMinValue
  - System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: TimeSpanValidatorAttribute
  nameWithType: TimeSpanValidatorAttribute
  fullName: System.Configuration.TimeSpanValidatorAttribute
  type: Class
  summary: "Declaratively instructs the .NET Framework to perform time validation on a configuration property. This class cannot be inherited."
  remarks: "You use the TimeSpanValidatorAttribute attribute to decorate a configuration property. This is to instruct the .NET Framework to validate the property using the <xref:System.Configuration.TimeSpanValidator> class and pass to it the value of the decorating parameters.       You can apply TimeSpanValidatorAttribute objects to property types only."
  example:
  - "The following example shows how to decorate the properties of a custom <xref:System.Configuration.ConfigurationSection> object using the TimeSpanValidatorAttribute attribute.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/VisualBasic/t-system.configuration.t_1_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/CSharp/t-system.configuration.t_1_1.cs)]  \n  \n The following example is an excerpt of the configuration file that contains the custom section used by the previous sample.  \n  \n```  \n<configuration xmlns=\"http://schemas.microsoft.com/.NetConfiguration/v2.0\">  \n  <configSections>  \n    <section name=\"custom\" type=\"Microsoft.Samples.AspNet.Configuration.SampleSection, ConfigurationValidatorAttribute\" />  \n  </configSections>  \n  <custom fileName=\"NewFile.txt\" maxSize=\"1000\" maxAttempts=\"101\" maxUsers=\"2500\" maxIdleTime=\"00:15:00\" />  \n</configuration>  \n```"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class TimeSpanValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: TimeSpanValidatorAttribute()
  nameWithType: TimeSpanValidatorAttribute.TimeSpanValidatorAttribute()
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.TimeSpanValidatorAttribute&quot;></see> class."
  remarks: "You use this constructor in the attributed model to ensure that the type of the value assigned to the related property is a <xref:System.TimeSpan> object."
  example:
  - "The following example shows how to use the <xref:System.Configuration.StringValidatorAttribute.%23ctor%2A> constructor.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#12](~/add/codesnippet/VisualBasic/m-system.configuration.t_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#12](~/add/codesnippet/CSharp/m-system.configuration.t_0_1.cs)]"
  syntax:
    content: public TimeSpanValidatorAttribute ();
    parameters: []
  overload: System.Configuration.TimeSpanValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanValidatorAttribute.ExcludeRange
  id: ExcludeRange
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: ExcludeRange
  nameWithType: TimeSpanValidatorAttribute.ExcludeRange
  fullName: System.Configuration.TimeSpanValidatorAttribute.ExcludeRange
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets or sets a value that indicates whether to include or exclude the integers in the range as defined by &lt;xref:System.Configuration.TimeSpanValidatorAttribute.MinValueString%2A&gt; and &lt;xref:System.Configuration.TimeSpanValidatorAttribute.MaxValueString%2A&gt;."
  remarks: "The range is inclusive of the <xref:System.Configuration.TimeSpanValidatorAttribute.MinValueString%2A> and <xref:System.Configuration.TimeSpanValidatorAttribute.MaxValueString%2A> properties. When the ExcludeRange property is `false`, the allowed values are outside the range."
  example:
  - "The following example shows how to use the ExcludeRange property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/VisualBasic/p-system.configuration.t_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/CSharp/p-system.configuration.t_0_1.cs)]"
  syntax:
    content: public bool ExcludeRange { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if the value must be excluded; otherwise, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>. The default is <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>."
  overload: System.Configuration.TimeSpanValidatorAttribute.ExcludeRange*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanValidatorAttribute.MaxValue
  id: MaxValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: MaxValue
  nameWithType: TimeSpanValidatorAttribute.MaxValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.MaxValue
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets the absolute maximum &lt;xref:System.TimeSpan&gt; value."
  remarks: "This is the absolute maximum value allowed by the .NET Framework. Its value is defined by the <xref:System.TimeSpan> field."
  syntax:
    content: public TimeSpan MaxValue { get; }
    return:
      type: System.TimeSpan
      description: "The allowed maximum &lt;xref:System.TimeSpan&gt; value."
  overload: System.Configuration.TimeSpanValidatorAttribute.MaxValue*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanValidatorAttribute.MaxValueString
  id: MaxValueString
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: MaxValueString
  nameWithType: TimeSpanValidatorAttribute.MaxValueString
  fullName: System.Configuration.TimeSpanValidatorAttribute.MaxValueString
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets or sets the relative maximum &lt;xref:System.TimeSpan&gt; value."
  remarks: "This is the relative maximum value as set by the user."
  example:
  - "The following example shows how to use the MaxValueString property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/VisualBasic/p-system.configuration.t_1_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/CSharp/p-system.configuration.t_1_1.cs)]"
  syntax:
    content: public string MaxValueString { get; set; }
    return:
      type: System.String
      description: "The allowed maximum &lt;xref:System.TimeSpan&gt; value."
  overload: System.Configuration.TimeSpanValidatorAttribute.MaxValueString*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "The selected value represents less than <xref:System.Configuration.TimeSpanValidatorAttribute.MinValue%2A>."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanValidatorAttribute.MinValue
  id: MinValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: MinValue
  nameWithType: TimeSpanValidatorAttribute.MinValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.MinValue
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets the absolute minimum &lt;xref:System.TimeSpan&gt; value."
  remarks: "This is the absolute minimum value allowed by the .NET Framework. Its value is defined by the <xref:System.TimeSpan> field."
  syntax:
    content: public TimeSpan MinValue { get; }
    return:
      type: System.TimeSpan
      description: "The allowed minimum &lt;xref:System.TimeSpan&gt; value."
  overload: System.Configuration.TimeSpanValidatorAttribute.MinValue*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanValidatorAttribute.MinValueString
  id: MinValueString
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: MinValueString
  nameWithType: TimeSpanValidatorAttribute.MinValueString
  fullName: System.Configuration.TimeSpanValidatorAttribute.MinValueString
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets or sets the relative minimum &lt;xref:System.TimeSpan&gt; value."
  remarks: "This is the relative minimum value as set by the user."
  example:
  - "The following example shows how to use the MinValueString property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/VisualBasic/p-system.configuration.t_2_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/CSharp/p-system.configuration.t_2_1.cs)]"
  syntax:
    content: public string MinValueString { get; set; }
    return:
      type: System.String
      description: "The minimum allowed &lt;xref:System.TimeSpan&gt; value."
  overload: System.Configuration.TimeSpanValidatorAttribute.MinValueString*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "The selected value represents more than <xref:System.Configuration.TimeSpanValidatorAttribute.MaxValue%2A>."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMaxValue
  id: TimeSpanMaxValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: TimeSpanMaxValue
  nameWithType: TimeSpanValidatorAttribute.TimeSpanMaxValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMaxValue
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets the absolute maximum value allowed."
  remarks: "The string that contains the maximum allowed value for the time interval."
  example:
  - "The following example shows how to use the TimeSpanMaxValue field.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#10](~/add/codesnippet/VisualBasic/f-system.configuration.t_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#10](~/add/codesnippet/CSharp/f-system.configuration.t_0_1.cs)]"
  syntax:
    content: public const string TimeSpanMaxValue;
    return:
      type: System.String
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMinValue
  id: TimeSpanMinValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: TimeSpanMinValue
  nameWithType: TimeSpanValidatorAttribute.TimeSpanMinValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMinValue
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets the absolute minimum value allowed."
  remarks: "The string that contains the minimum allowed value for the time interval."
  example:
  - "The following example shows how to use the TimeSpanMinValue field.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#11](~/add/codesnippet/VisualBasic/f-system.configuration.t_1_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#11](~/add/codesnippet/CSharp/f-system.configuration.t_1_1.cs)]"
  syntax:
    content: public const string TimeSpanMinValue;
    return:
      type: System.String
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: TimeSpanValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets an instance of the <see cref=&quot;T:System.Configuration.TimeSpanValidator&quot;></see> class."
  remarks: "You use the ValidatorInstance property to perform string validation by calling its <xref:System.Configuration.TimeSpanValidator.Validate%2A> method."
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "The <see cref=&quot;T:System.Configuration.ConfigurationValidatorBase&quot;></see> validator instance."
  overload: System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.Configuration.TimeSpanValidatorAttribute.#ctor
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: TimeSpanValidatorAttribute()
  nameWithType: TimeSpanValidatorAttribute.TimeSpanValidatorAttribute()
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanValidatorAttribute()
- uid: System.Configuration.TimeSpanValidatorAttribute.ExcludeRange
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: ExcludeRange
  nameWithType: TimeSpanValidatorAttribute.ExcludeRange
  fullName: System.Configuration.TimeSpanValidatorAttribute.ExcludeRange
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.TimeSpanValidatorAttribute.MaxValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MaxValue
  nameWithType: TimeSpanValidatorAttribute.MaxValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.MaxValue
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Configuration.TimeSpanValidatorAttribute.MaxValueString
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MaxValueString
  nameWithType: TimeSpanValidatorAttribute.MaxValueString
  fullName: System.Configuration.TimeSpanValidatorAttribute.MaxValueString
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.TimeSpanValidatorAttribute.MinValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MinValue
  nameWithType: TimeSpanValidatorAttribute.MinValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.MinValue
- uid: System.Configuration.TimeSpanValidatorAttribute.MinValueString
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MinValueString
  nameWithType: TimeSpanValidatorAttribute.MinValueString
  fullName: System.Configuration.TimeSpanValidatorAttribute.MinValueString
- uid: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMaxValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: TimeSpanMaxValue
  nameWithType: TimeSpanValidatorAttribute.TimeSpanMaxValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMaxValue
- uid: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMinValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: TimeSpanMinValue
  nameWithType: TimeSpanValidatorAttribute.TimeSpanMinValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMinValue
- uid: System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: TimeSpanValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.TimeSpanValidatorAttribute.#ctor*
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: TimeSpanValidatorAttribute
  nameWithType: TimeSpanValidatorAttribute.TimeSpanValidatorAttribute
- uid: System.Configuration.TimeSpanValidatorAttribute.ExcludeRange*
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: ExcludeRange
  nameWithType: TimeSpanValidatorAttribute.ExcludeRange
- uid: System.Configuration.TimeSpanValidatorAttribute.MaxValue*
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MaxValue
  nameWithType: TimeSpanValidatorAttribute.MaxValue
- uid: System.Configuration.TimeSpanValidatorAttribute.MaxValueString*
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MaxValueString
  nameWithType: TimeSpanValidatorAttribute.MaxValueString
- uid: System.Configuration.TimeSpanValidatorAttribute.MinValue*
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MinValue
  nameWithType: TimeSpanValidatorAttribute.MinValue
- uid: System.Configuration.TimeSpanValidatorAttribute.MinValueString*
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MinValueString
  nameWithType: TimeSpanValidatorAttribute.MinValueString
- uid: System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: TimeSpanValidatorAttribute.ValidatorInstance
