### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel
  id: ProcessModelComImpersonationLevel
  children:
  - System.Web.Configuration.ProcessModelComImpersonationLevel.Anonymous
  - System.Web.Configuration.ProcessModelComImpersonationLevel.Default
  - System.Web.Configuration.ProcessModelComImpersonationLevel.Delegate
  - System.Web.Configuration.ProcessModelComImpersonationLevel.Identify
  - System.Web.Configuration.ProcessModelComImpersonationLevel.Impersonate
  langs:
  - csharp
  name: ProcessModelComImpersonationLevel
  nameWithType: ProcessModelComImpersonationLevel
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel
  type: Enum
  summary: "Specifies the authentication level for COM security."
  remarks: "The ProcessModelComImpersonationLevel class enumerates the values to use when you set the <xref:System.Web.Configuration.ProcessModelSection.ComImpersonationLevel%2A> property.       The default value is Impersonate."
  example:
  - "The following code example shows how to access the <xref:System.Web.Configuration.ProcessModelSection.ComImpersonationLevel%2A> property.  \n  \n [!code-cs[System.Web.Configuration.ProcessModelSection#22](~/add/codesnippet/CSharp/t-system.web.configurati_52_1.cs)]\n [!code-vb[System.Web.Configuration.ProcessModelSection#22](~/add/codesnippet/VisualBasic/t-system.web.configurati_52_1.vb)]"
  syntax:
    content: public enum ProcessModelComImpersonationLevel
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Anonymous
  id: Anonymous
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  langs:
  - csharp
  name: Anonymous
  nameWithType: ProcessModelComImpersonationLevel.Anonymous
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Anonymous
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifies that the client is anonymous to the server. This field is constant."
  remarks: "The server can impersonate the client, but the impersonation token will not contain any information."
  syntax:
    content: Anonymous
    return:
      type: System.Web.Configuration.ProcessModelComImpersonationLevel
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Default
  id: Default
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  langs:
  - csharp
  name: Default
  nameWithType: ProcessModelComImpersonationLevel.Default
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Default
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifies that DCOM determines the impersonation level. This field is constant."
  remarks: "DCOM determines the impersonation level, using its normal security-negotiation algorithm."
  syntax:
    content: Default
    return:
      type: System.Web.Configuration.ProcessModelComImpersonationLevel
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Delegate
  id: Delegate
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  langs:
  - csharp
  name: Delegate
  nameWithType: ProcessModelComImpersonationLevel.Delegate
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Delegate
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifies that the server process can impersonate the client&quot;s security context while acting on behalf of the client. This field is constant."
  remarks: "The server process can make outgoing calls to other servers while acting on behalf of the client, using cloaking. The server can use the client&quot;s security context on other computers to access local and remote resources as the client. When the process is impersonating the client at this level, the impersonation token can be passed across any number of computer boundaries."
  syntax:
    content: Delegate
    return:
      type: System.Web.Configuration.ProcessModelComImpersonationLevel
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Identify
  id: Identify
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  langs:
  - csharp
  name: Identify
  nameWithType: ProcessModelComImpersonationLevel.Identify
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Identify
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifies that the server can obtain the client&quot;s identity. This field is constant."
  remarks: "The server can impersonate the client for access control list (ACL) checking, but it cannot access system objects as the client."
  syntax:
    content: Identify
    return:
      type: System.Web.Configuration.ProcessModelComImpersonationLevel
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Impersonate
  id: Impersonate
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  langs:
  - csharp
  name: Impersonate
  nameWithType: ProcessModelComImpersonationLevel.Impersonate
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Impersonate
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifies that the server process can impersonate the client&quot;s security context while acting on behalf of the client. This field is constant."
  remarks: "This level of impersonation can be used to access local resources such as files. When the process is impersonating the client at this level, the impersonation token can be passed across only one computer boundary."
  syntax:
    content: Impersonate
    return:
      type: System.Web.Configuration.ProcessModelComImpersonationLevel
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Anonymous
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  isExternal: false
  name: Anonymous
  nameWithType: ProcessModelComImpersonationLevel.Anonymous
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Anonymous
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel
  parent: System.Web.Configuration
  isExternal: false
  name: ProcessModelComImpersonationLevel
  nameWithType: ProcessModelComImpersonationLevel
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Default
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  isExternal: false
  name: Default
  nameWithType: ProcessModelComImpersonationLevel.Default
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Default
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Delegate
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  isExternal: false
  name: Delegate
  nameWithType: ProcessModelComImpersonationLevel.Delegate
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Delegate
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Identify
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  isExternal: false
  name: Identify
  nameWithType: ProcessModelComImpersonationLevel.Identify
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Identify
- uid: System.Web.Configuration.ProcessModelComImpersonationLevel.Impersonate
  parent: System.Web.Configuration.ProcessModelComImpersonationLevel
  isExternal: false
  name: Impersonate
  nameWithType: ProcessModelComImpersonationLevel.Impersonate
  fullName: System.Web.Configuration.ProcessModelComImpersonationLevel.Impersonate
