### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.IConfigMapPathFactory
  id: IConfigMapPathFactory
  children:
  - System.Web.Configuration.IConfigMapPathFactory.Create(System.String,System.String)
  langs:
  - csharp
  name: IConfigMapPathFactory
  nameWithType: IConfigMapPathFactory
  fullName: System.Web.Configuration.IConfigMapPathFactory
  type: Interface
  summary: "Maps the configuration file virtual and physical paths."
  remarks: "IConfigMapPathFactory is introduced in the .NET Framework version 3.5.  For more information, see [Versions and Dependencies](../Topic/.NET%20Framework%20Versions%20and%20Dependencies.md)."
  syntax:
    content: public interface IConfigMapPathFactory
  implements: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.IConfigMapPathFactory.Create(System.String,System.String)
  id: Create(System.String,System.String)
  parent: System.Web.Configuration.IConfigMapPathFactory
  langs:
  - csharp
  name: Create(String,String)
  nameWithType: IConfigMapPathFactory.Create(String,String)
  fullName: System.Web.Configuration.IConfigMapPathFactory.Create(String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Creates the interface for the mapping between configuration-file virtual and physical paths."
  remarks: "Create is introduced in the .NET Framework version 3.5.  For more information, see [Versions and Dependencies](../Topic/.NET%20Framework%20Versions%20and%20Dependencies.md)."
  syntax:
    content: public System.Web.Configuration.IConfigMapPath Create (string virtualPath, string physicalPath);
    parameters:
    - id: virtualPath
      type: System.String
      description: "The configuration-file virtual path."
    - id: physicalPath
      type: System.String
      description: "The configuration-file physical path."
    return:
      type: System.Web.Configuration.IConfigMapPath
      description: "To be added."
  overload: System.Web.Configuration.IConfigMapPathFactory.Create*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Web.Configuration.IConfigMapPathFactory.Create(System.String,System.String)
  parent: System.Web.Configuration.IConfigMapPathFactory
  isExternal: false
  name: Create(String,String)
  nameWithType: IConfigMapPathFactory.Create(String,String)
  fullName: System.Web.Configuration.IConfigMapPathFactory.Create(String,String)
- uid: System.Web.Configuration.IConfigMapPath
  parent: System.Web.Configuration
  isExternal: false
  name: IConfigMapPath
  nameWithType: IConfigMapPath
  fullName: System.Web.Configuration.IConfigMapPath
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.IConfigMapPathFactory.Create*
  parent: System.Web.Configuration.IConfigMapPathFactory
  isExternal: false
  name: Create
  nameWithType: IConfigMapPathFactory.Create
