### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.WebContext
  id: WebContext
  children:
  - System.Web.Configuration.WebContext.#ctor(System.Web.Configuration.WebApplicationLevel,System.String,System.String,System.String,System.String,System.String)
  - System.Web.Configuration.WebContext.ApplicationLevel
  - System.Web.Configuration.WebContext.ApplicationPath
  - System.Web.Configuration.WebContext.LocationSubPath
  - System.Web.Configuration.WebContext.Path
  - System.Web.Configuration.WebContext.Site
  - System.Web.Configuration.WebContext.ToString
  langs:
  - csharp
  name: WebContext
  nameWithType: WebContext
  fullName: System.Web.Configuration.WebContext
  type: Class
  summary: "Manages the path context for the current Web application. This class cannot be inherited."
  remarks: ''
  example:
  - "The following example shows how to use the WebContext class.  \n  \n [!code-cs[System.Web.Configuration.WebContext#1](~/add/codesnippet/CSharp/t-system.web.configurati_25_1.cs)]\n [!code-vb[System.Web.Configuration.WebContext#1](~/add/codesnippet/VisualBasic/t-system.web.configurati_25_1.vb)]"
  syntax:
    content: public sealed class WebContext
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.WebContext.#ctor(System.Web.Configuration.WebApplicationLevel,System.String,System.String,System.String,System.String,System.String)
  id: '#ctor(System.Web.Configuration.WebApplicationLevel,System.String,System.String,System.String,System.String,System.String)'
  parent: System.Web.Configuration.WebContext
  langs:
  - csharp
  name: WebContext(WebApplicationLevel,String,String,String,String,String)
  nameWithType: WebContext.WebContext(WebApplicationLevel,String,String,String,String,String)
  fullName: System.Web.Configuration.WebContext.WebContext(WebApplicationLevel,String,String,String,String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Web.Configuration.WebContext&quot;></see> class."
  remarks: ''
  example:
  - "The following example shows how to use this constructor. This code example is part of a larger example provided for the <xref:System.Web.Configuration.WebContext> class.  \n  \n [!code-cs[System.Web.Configuration.WebContext#2](~/add/codesnippet/CSharp/c8cb0c76-e300-49bb-8742-_1.cs)]\n [!code-vb[System.Web.Configuration.WebContext#2](~/add/codesnippet/VisualBasic/c8cb0c76-e300-49bb-8742-_1.vb)]"
  syntax:
    content: public WebContext (System.Web.Configuration.WebApplicationLevel pathLevel, string site, string applicationPath, string path, string locationSubPath, string appConfigPath);
    parameters:
    - id: pathLevel
      type: System.Web.Configuration.WebApplicationLevel
      description: "A  object."
    - id: site
      type: System.String
      description: "The name of the Web site."
    - id: applicationPath
      type: System.String
      description: "The virtual path of the root level of the current Web application."
    - id: path
      type: System.String
      description: "The virtual path of the Web.config file that the current configuration object represents."
    - id: locationSubPath
      type: System.String
      description: "The path value of the  element that is currently being edited."
    - id: appConfigPath
      type: System.String
      description: "The current Web application&quot;s configuration path."
  overload: System.Web.Configuration.WebContext.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.WebContext.ApplicationLevel
  id: ApplicationLevel
  parent: System.Web.Configuration.WebContext
  langs:
  - csharp
  name: ApplicationLevel
  nameWithType: WebContext.ApplicationLevel
  fullName: System.Web.Configuration.WebContext.ApplicationLevel
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets a <see cref=&quot;T:System.Web.Configuration.WebApplicationLevel&quot;></see> object that represents the path level of the current Web application."
  remarks: ''
  example:
  - "The following example shows how to use the ApplicationLevel property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.WebContext> class.  \n  \n [!code-cs[System.Web.Configuration.WebContext#3](~/add/codesnippet/CSharp/p-system.web.configurati_226_1.cs)]\n [!code-vb[System.Web.Configuration.WebContext#3](~/add/codesnippet/VisualBasic/p-system.web.configurati_226_1.vb)]"
  syntax:
    content: public System.Web.Configuration.WebApplicationLevel ApplicationLevel { get; }
    return:
      type: System.Web.Configuration.WebApplicationLevel
      description: "A <see cref=&quot;T:System.Web.Configuration.WebApplicationLevel&quot;></see> object."
  overload: System.Web.Configuration.WebContext.ApplicationLevel*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.WebContext.ApplicationPath
  id: ApplicationPath
  parent: System.Web.Configuration.WebContext
  langs:
  - csharp
  name: ApplicationPath
  nameWithType: WebContext.ApplicationPath
  fullName: System.Web.Configuration.WebContext.ApplicationPath
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets the application path of the current Web application."
  remarks: ''
  example:
  - "The following example shows how to use the ApplicationPath property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.WebContext> class.  \n  \n [!code-cs[System.Web.Configuration.WebContext#4](~/add/codesnippet/CSharp/p-system.web.configurati_313_1.cs)]\n [!code-vb[System.Web.Configuration.WebContext#4](~/add/codesnippet/VisualBasic/p-system.web.configurati_313_1.vb)]"
  syntax:
    content: public string ApplicationPath { get; }
    return:
      type: System.String
      description: "The application path of the current Web application."
  overload: System.Web.Configuration.WebContext.ApplicationPath*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.WebContext.LocationSubPath
  id: LocationSubPath
  parent: System.Web.Configuration.WebContext
  langs:
  - csharp
  name: LocationSubPath
  nameWithType: WebContext.LocationSubPath
  fullName: System.Web.Configuration.WebContext.LocationSubPath
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets the location subpath of the Web application."
  syntax:
    content: public string LocationSubPath { get; }
    return:
      type: System.String
      description: "The location subpath of the current Web application."
  overload: System.Web.Configuration.WebContext.LocationSubPath*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.WebContext.Path
  id: Path
  parent: System.Web.Configuration.WebContext
  langs:
  - csharp
  name: Path
  nameWithType: WebContext.Path
  fullName: System.Web.Configuration.WebContext.Path
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets the current virtual path of the Web application."
  remarks: ''
  example:
  - "The following example shows how to use the Path property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.WebContext> class.  \n  \n [!code-cs[System.Web.Configuration.WebContext#6](~/add/codesnippet/CSharp/p-system.web.configurati_335_1.cs)]\n [!code-vb[System.Web.Configuration.WebContext#6](~/add/codesnippet/VisualBasic/p-system.web.configurati_335_1.vb)]"
  syntax:
    content: public string Path { get; }
    return:
      type: System.String
      description: "The current virtual path of the Web application."
  overload: System.Web.Configuration.WebContext.Path*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.WebContext.Site
  id: Site
  parent: System.Web.Configuration.WebContext
  langs:
  - csharp
  name: Site
  nameWithType: WebContext.Site
  fullName: System.Web.Configuration.WebContext.Site
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets the name of the current Web application."
  remarks: ''
  example:
  - "The following example shows how to use the Site property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.WebContext> class.  \n  \n [!code-cs[System.Web.Configuration.WebContext#7](~/add/codesnippet/CSharp/p-system.web.configurati_287_1.cs)]\n [!code-vb[System.Web.Configuration.WebContext#7](~/add/codesnippet/VisualBasic/p-system.web.configurati_287_1.vb)]"
  syntax:
    content: public string Site { get; }
    return:
      type: System.String
      description: "The name of the current Web application."
  overload: System.Web.Configuration.WebContext.Site*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.WebContext.ToString
  id: ToString
  parent: System.Web.Configuration.WebContext
  langs:
  - csharp
  name: ToString()
  nameWithType: WebContext.ToString()
  fullName: System.Web.Configuration.WebContext.ToString()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Returns a string that represents the application&quot;s configuration path."
  syntax:
    content: public override string ToString ();
    parameters: []
    return:
      type: System.String
      description: "To be added."
  overload: System.Web.Configuration.WebContext.ToString*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Configuration.WebContext.#ctor(System.Web.Configuration.WebApplicationLevel,System.String,System.String,System.String,System.String,System.String)
  parent: System.Web.Configuration.WebContext
  isExternal: false
  name: WebContext(WebApplicationLevel,String,String,String,String,String)
  nameWithType: WebContext.WebContext(WebApplicationLevel,String,String,String,String,String)
  fullName: System.Web.Configuration.WebContext.WebContext(WebApplicationLevel,String,String,String,String,String)
- uid: System.Web.Configuration.WebApplicationLevel
  parent: System.Web.Configuration
  isExternal: false
  name: WebApplicationLevel
  nameWithType: WebApplicationLevel
  fullName: System.Web.Configuration.WebApplicationLevel
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.WebContext.ApplicationLevel
  parent: System.Web.Configuration.WebContext
  isExternal: false
  name: ApplicationLevel
  nameWithType: WebContext.ApplicationLevel
  fullName: System.Web.Configuration.WebContext.ApplicationLevel
- uid: System.Web.Configuration.WebContext.ApplicationPath
  parent: System.Web.Configuration.WebContext
  isExternal: false
  name: ApplicationPath
  nameWithType: WebContext.ApplicationPath
  fullName: System.Web.Configuration.WebContext.ApplicationPath
- uid: System.Web.Configuration.WebContext.LocationSubPath
  parent: System.Web.Configuration.WebContext
  isExternal: false
  name: LocationSubPath
  nameWithType: WebContext.LocationSubPath
  fullName: System.Web.Configuration.WebContext.LocationSubPath
- uid: System.Web.Configuration.WebContext.Path
  parent: System.Web.Configuration.WebContext
  isExternal: false
  name: Path
  nameWithType: WebContext.Path
  fullName: System.Web.Configuration.WebContext.Path
- uid: System.Web.Configuration.WebContext.Site
  parent: System.Web.Configuration.WebContext
  isExternal: false
  name: Site
  nameWithType: WebContext.Site
  fullName: System.Web.Configuration.WebContext.Site
- uid: System.Web.Configuration.WebContext.ToString
  parent: System.Web.Configuration.WebContext
  isExternal: false
  name: ToString()
  nameWithType: WebContext.ToString()
  fullName: System.Web.Configuration.WebContext.ToString()
- uid: System.Web.Configuration.WebContext.#ctor*
  parent: System.Web.Configuration.WebContext
  isExternal: false
  name: WebContext
  nameWithType: WebContext.WebContext
- uid: System.Web.Configuration.WebContext.ApplicationLevel*
  parent: System.Web.Configuration.WebContext
  isExternal: false
  name: ApplicationLevel
  nameWithType: WebContext.ApplicationLevel
- uid: System.Web.Configuration.WebContext.ApplicationPath*
  parent: System.Web.Configuration.WebContext
  isExternal: false
  name: ApplicationPath
  nameWithType: WebContext.ApplicationPath
- uid: System.Web.Configuration.WebContext.LocationSubPath*
  parent: System.Web.Configuration.WebContext
  isExternal: false
  name: LocationSubPath
  nameWithType: WebContext.LocationSubPath
- uid: System.Web.Configuration.WebContext.Path*
  parent: System.Web.Configuration.WebContext
  isExternal: false
  name: Path
  nameWithType: WebContext.Path
- uid: System.Web.Configuration.WebContext.Site*
  parent: System.Web.Configuration.WebContext
  isExternal: false
  name: Site
  nameWithType: WebContext.Site
- uid: System.Web.Configuration.WebContext.ToString*
  parent: System.Web.Configuration.WebContext
  isExternal: false
  name: ToString
  nameWithType: WebContext.ToString
