### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.WebPartsPersonalization
  id: WebPartsPersonalization
  children:
  - System.Web.Configuration.WebPartsPersonalization.#ctor
  - System.Web.Configuration.WebPartsPersonalization.Authorization
  - System.Web.Configuration.WebPartsPersonalization.DefaultProvider
  - System.Web.Configuration.WebPartsPersonalization.Properties
  - System.Web.Configuration.WebPartsPersonalization.Providers
  langs:
  - csharp
  name: WebPartsPersonalization
  nameWithType: WebPartsPersonalization
  fullName: System.Web.Configuration.WebPartsPersonalization
  type: Class
  summary: "Allows you to specify the personalization provider and set personalization authorizations. This class cannot be inherited."
  remarks: "WebPartsPersonalization provides configuration support for personalization options for Web Parts, such as the personalization provider and personalization authorizations."
  example:
  - "This example demonstrates how to specify values declaratively for several attributes of the `webParts` section, which can also be accessed as members of the WebPartsPersonalization class.  \n  \n The following configuration file example shows how to specify values declaratively for the `webParts` section.  \n  \n```  \n<system.web>  \n  <webParts>  \n    <personalization  \n      defaultProvider=\"AspNetSqlPersonalizationProvider\">  \n        <!â€”- Providers may only be defined at the   \n            application level -->  \n      <providers>  \n         <add name=\"AspNetSqlPersonalizationProvider\"  \ntype=\"System.Web.UI.WebControls.WebParts.SqlPersonalizationProvider\"  \n            connectionStringName=\"LocalSqlServer\"  \n            applicationName=\"/\" />        \n      </providers>  \n      <authorization>  \n        <deny users=\"*\" verbs=\"enterSharedScope\" />  \n        <allow users=\"*\" verbs=\"modifyState\" />  \n      </authorization>  \n    </personalization>  \n  </webParts>   \n</system.web>  \n```  \n  \n The following code example demonstrates how to use the WebPartsPersonalization class.  \n  \n This code example is part of a larger example provided for the <xref:System.Web.Configuration.WebPartsSection> class.  \n  \n [!code-cs[System.Web.Configuration.WebPartsSection#3](~/add/codesnippet/CSharp/t-system.web.configurati_85_1.cs)]\n [!code-vb[System.Web.Configuration.WebPartsSection#3](~/add/codesnippet/VisualBasic/t-system.web.configurati_85_1.vb)]"
  syntax:
    content: 'public sealed class WebPartsPersonalization : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.WebPartsPersonalization.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.WebPartsPersonalization
  langs:
  - csharp
  name: WebPartsPersonalization()
  nameWithType: WebPartsPersonalization.WebPartsPersonalization()
  fullName: System.Web.Configuration.WebPartsPersonalization.WebPartsPersonalization()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Web.Configuration.WebPartsPersonalization&quot;></see> class using default settings."
  remarks: "This constructor is not intended to be used directly from your code. It is called by the ASP.NET configuration system. An instance of this class is available from the <xref:System.Web.Configuration.WebPartsSection.Personalization%2A> property."
  syntax:
    content: public WebPartsPersonalization ();
    parameters: []
  overload: System.Web.Configuration.WebPartsPersonalization.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.WebPartsPersonalization.Authorization
  id: Authorization
  parent: System.Web.Configuration.WebPartsPersonalization
  langs:
  - csharp
  name: Authorization
  nameWithType: WebPartsPersonalization.Authorization
  fullName: System.Web.Configuration.WebPartsPersonalization.Authorization
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets an <see cref=&quot;T:System.Web.Configuration.AuthorizationSection&quot;></see> object containing the Web Parts personalization authorizations for the current Web application."
  remarks: "There must be at least one valid verb associated with each <xref:System.Web.Configuration.AuthorizationRule> object in the collection."
  example:
  - "The following code example shows how to use the Authorization property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.WebPartsSection> class.  \n  \n [!code-cs[System.Web.Configuration.WebPartsSection#15](~/add/codesnippet/CSharp/p-system.web.configurati_18_1.cs)]\n [!code-vb[System.Web.Configuration.WebPartsSection#15](~/add/codesnippet/VisualBasic/p-system.web.configurati_18_1.vb)]"
  syntax:
    content: public System.Web.Configuration.WebPartsPersonalizationAuthorization Authorization { get; }
    return:
      type: System.Web.Configuration.WebPartsPersonalizationAuthorization
      description: "An <see cref=&quot;T:System.Web.Configuration.AuthorizationSection&quot;></see> object containing the Web Parts personalization authorizations for the current Web application."
  overload: System.Web.Configuration.WebPartsPersonalization.Authorization*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.WebPartsPersonalization.DefaultProvider
  id: DefaultProvider
  parent: System.Web.Configuration.WebPartsPersonalization
  langs:
  - csharp
  name: DefaultProvider
  nameWithType: WebPartsPersonalization.DefaultProvider
  fullName: System.Web.Configuration.WebPartsPersonalization.DefaultProvider
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets or sets the name of the default Web Parts personalization provider."
  remarks: "The <xref:System.Web.Configuration.WebPartsPersonalization.Providers%2A> property contains the Web Parts personalization providers for the current Web application."
  example:
  - "The following code example shows how to use the DefaultProvider property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.WebPartsSection> class.  \n  \n [!code-cs[System.Web.Configuration.WebPartsSection#13](~/add/codesnippet/CSharp/p-system.web.configurati_333_1.cs)]\n [!code-vb[System.Web.Configuration.WebPartsSection#13](~/add/codesnippet/VisualBasic/p-system.web.configurati_333_1.vb)]"
  syntax:
    content: public string DefaultProvider { get; set; }
    return:
      type: System.String
      description: "The name of the default Web Parts personalization provider."
  overload: System.Web.Configuration.WebPartsPersonalization.DefaultProvider*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.WebPartsPersonalization.Properties
  id: Properties
  parent: System.Web.Configuration.WebPartsPersonalization
  langs:
  - csharp
  name: Properties
  nameWithType: WebPartsPersonalization.Properties
  fullName: System.Web.Configuration.WebPartsPersonalization.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Web.Configuration.WebPartsPersonalization.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.WebPartsPersonalization.Providers
  id: Providers
  parent: System.Web.Configuration.WebPartsPersonalization
  langs:
  - csharp
  name: Providers
  nameWithType: WebPartsPersonalization.Providers
  fullName: System.Web.Configuration.WebPartsPersonalization.Providers
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets a <see cref=&quot;T:System.Configuration.ProviderSettingsCollection&quot;></see> collection that contains the Web Parts personalization providers for the current Web application."
  remarks: "Web Parts personalization providers can only be defined at the Web-application level (in a Web.config file)."
  example:
  - "The following code example shows how to use the Providers property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.WebPartsSection> class.  \n  \n [!code-cs[System.Web.Configuration.WebPartsSection#14](~/add/codesnippet/CSharp/p-system.web.configurati_148_1.cs)]\n [!code-vb[System.Web.Configuration.WebPartsSection#14](~/add/codesnippet/VisualBasic/p-system.web.configurati_148_1.vb)]"
  syntax:
    content: public System.Configuration.ProviderSettingsCollection Providers { get; }
    return:
      type: System.Configuration.ProviderSettingsCollection
      description: "A <see cref=&quot;T:System.Configuration.ProviderSettingsCollection&quot;></see> collection that contains the Web Parts personalization providers for the current Web application."
  overload: System.Web.Configuration.WebPartsPersonalization.Providers*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.WebPartsPersonalization.#ctor
  parent: System.Web.Configuration.WebPartsPersonalization
  isExternal: false
  name: WebPartsPersonalization()
  nameWithType: WebPartsPersonalization.WebPartsPersonalization()
  fullName: System.Web.Configuration.WebPartsPersonalization.WebPartsPersonalization()
- uid: System.Web.Configuration.WebPartsPersonalization.Authorization
  parent: System.Web.Configuration.WebPartsPersonalization
  isExternal: false
  name: Authorization
  nameWithType: WebPartsPersonalization.Authorization
  fullName: System.Web.Configuration.WebPartsPersonalization.Authorization
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization
  parent: System.Web.Configuration
  isExternal: false
  name: WebPartsPersonalizationAuthorization
  nameWithType: WebPartsPersonalizationAuthorization
  fullName: System.Web.Configuration.WebPartsPersonalizationAuthorization
- uid: System.Web.Configuration.WebPartsPersonalization.DefaultProvider
  parent: System.Web.Configuration.WebPartsPersonalization
  isExternal: false
  name: DefaultProvider
  nameWithType: WebPartsPersonalization.DefaultProvider
  fullName: System.Web.Configuration.WebPartsPersonalization.DefaultProvider
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.WebPartsPersonalization.Properties
  parent: System.Web.Configuration.WebPartsPersonalization
  isExternal: false
  name: Properties
  nameWithType: WebPartsPersonalization.Properties
  fullName: System.Web.Configuration.WebPartsPersonalization.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.WebPartsPersonalization.Providers
  parent: System.Web.Configuration.WebPartsPersonalization
  isExternal: false
  name: Providers
  nameWithType: WebPartsPersonalization.Providers
  fullName: System.Web.Configuration.WebPartsPersonalization.Providers
- uid: System.Configuration.ProviderSettingsCollection
  parent: System.Configuration
  isExternal: false
  name: ProviderSettingsCollection
  nameWithType: ProviderSettingsCollection
  fullName: System.Configuration.ProviderSettingsCollection
- uid: System.Web.Configuration.WebPartsPersonalization.#ctor*
  parent: System.Web.Configuration.WebPartsPersonalization
  isExternal: false
  name: WebPartsPersonalization
  nameWithType: WebPartsPersonalization.WebPartsPersonalization
- uid: System.Web.Configuration.WebPartsPersonalization.Authorization*
  parent: System.Web.Configuration.WebPartsPersonalization
  isExternal: false
  name: Authorization
  nameWithType: WebPartsPersonalization.Authorization
- uid: System.Web.Configuration.WebPartsPersonalization.DefaultProvider*
  parent: System.Web.Configuration.WebPartsPersonalization
  isExternal: false
  name: DefaultProvider
  nameWithType: WebPartsPersonalization.DefaultProvider
- uid: System.Web.Configuration.WebPartsPersonalization.Properties*
  parent: System.Web.Configuration.WebPartsPersonalization
  isExternal: false
  name: Properties
  nameWithType: WebPartsPersonalization.Properties
- uid: System.Web.Configuration.WebPartsPersonalization.Providers*
  parent: System.Web.Configuration.WebPartsPersonalization
  isExternal: false
  name: Providers
  nameWithType: WebPartsPersonalization.Providers
