### YamlMime:ManagedReference
items:
- uid: System.Configuration.Assemblies.AssemblyHash
  id: AssemblyHash
  children:
  - System.Configuration.Assemblies.AssemblyHash.#ctor(System.Byte[])
  - System.Configuration.Assemblies.AssemblyHash.#ctor(System.Configuration.Assemblies.AssemblyHashAlgorithm,System.Byte[])
  - System.Configuration.Assemblies.AssemblyHash.Algorithm
  - System.Configuration.Assemblies.AssemblyHash.Clone
  - System.Configuration.Assemblies.AssemblyHash.Empty
  - System.Configuration.Assemblies.AssemblyHash.GetValue
  - System.Configuration.Assemblies.AssemblyHash.SetValue(System.Byte[])
  langs:
  - csharp
  name: AssemblyHash
  nameWithType: AssemblyHash
  fullName: System.Configuration.Assemblies.AssemblyHash
  type: Struct
  summary: "Represents a hash of an assembly manifest&quot;s contents."
  remarks: "AssemblyHash values are used throughout the common language runtime to detect a change in assembly contents."
  syntax:
    content: >-
      [System.Obsolete("The AssemblyHash class has been deprecated. http://go.microsoft.com/fwlink/?linkid=14202")]

      [System.Runtime.InteropServices.ComVisible(true)]

      public struct AssemblyHash : ICloneable
  inheritance:
  - System.ValueType
  implements:
  - System.ICloneable
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Assemblies.AssemblyHash.#ctor(System.Byte[])
  id: '#ctor(System.Byte[])'
  parent: System.Configuration.Assemblies.AssemblyHash
  langs:
  - csharp
  name: AssemblyHash(Byte[])
  nameWithType: AssemblyHash.AssemblyHash(Byte[])
  fullName: System.Configuration.Assemblies.AssemblyHash.AssemblyHash(Byte[])
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.Assemblies.AssemblyHash&quot;></see> structure with the specified hash value. The hash algorithm defaults to <see cref=&quot;T:System.Configuration.Assemblies.AssemblyHashAlgorithm&quot;></see>."
  syntax:
    content: public AssemblyHash (byte[] value);
    parameters:
    - id: value
      type: System.Byte[]
      description: "The hash value."
  overload: System.Configuration.Assemblies.AssemblyHash.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Assemblies.AssemblyHash.#ctor(System.Configuration.Assemblies.AssemblyHashAlgorithm,System.Byte[])
  id: '#ctor(System.Configuration.Assemblies.AssemblyHashAlgorithm,System.Byte[])'
  parent: System.Configuration.Assemblies.AssemblyHash
  langs:
  - csharp
  name: AssemblyHash(AssemblyHashAlgorithm,Byte[])
  nameWithType: AssemblyHash.AssemblyHash(AssemblyHashAlgorithm,Byte[])
  fullName: System.Configuration.Assemblies.AssemblyHash.AssemblyHash(AssemblyHashAlgorithm,Byte[])
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.Assemblies.AssemblyHash&quot;></see> structure with the specified hash algorithm and the hash value."
  syntax:
    content: public AssemblyHash (System.Configuration.Assemblies.AssemblyHashAlgorithm algorithm, byte[] value);
    parameters:
    - id: algorithm
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: "The algorithm used to generate the hash. Values for this parameter come from the  enumeration."
    - id: value
      type: System.Byte[]
      description: "The hash value."
  overload: System.Configuration.Assemblies.AssemblyHash.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Assemblies.AssemblyHash.Algorithm
  id: Algorithm
  parent: System.Configuration.Assemblies.AssemblyHash
  langs:
  - csharp
  name: Algorithm
  nameWithType: AssemblyHash.Algorithm
  fullName: System.Configuration.Assemblies.AssemblyHash.Algorithm
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "Gets or sets the hash algorithm."
  remarks: "The hash is made up of a byte array and a value from a class of supported algorithm types."
  syntax:
    content: public System.Configuration.Assemblies.AssemblyHashAlgorithm Algorithm { get; set; }
    return:
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: "An assembly hash algorithm."
  overload: System.Configuration.Assemblies.AssemblyHash.Algorithm*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Assemblies.AssemblyHash.Clone
  id: Clone
  parent: System.Configuration.Assemblies.AssemblyHash
  langs:
  - csharp
  name: Clone()
  nameWithType: AssemblyHash.Clone()
  fullName: System.Configuration.Assemblies.AssemblyHash.Clone()
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "Clones this object."
  syntax:
    content: public object Clone ();
    parameters: []
    return:
      type: System.Object
      description: "To be added."
  overload: System.Configuration.Assemblies.AssemblyHash.Clone*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Assemblies.AssemblyHash.Empty
  id: Empty
  parent: System.Configuration.Assemblies.AssemblyHash
  langs:
  - csharp
  name: Empty
  nameWithType: AssemblyHash.Empty
  fullName: System.Configuration.Assemblies.AssemblyHash.Empty
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "An empty <see cref=&quot;T:System.Configuration.Assemblies.AssemblyHash&quot;></see> object."
  syntax:
    content: public static readonly System.Configuration.Assemblies.AssemblyHash Empty;
    return:
      type: System.Configuration.Assemblies.AssemblyHash
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Assemblies.AssemblyHash.GetValue
  id: GetValue
  parent: System.Configuration.Assemblies.AssemblyHash
  langs:
  - csharp
  name: GetValue()
  nameWithType: AssemblyHash.GetValue()
  fullName: System.Configuration.Assemblies.AssemblyHash.GetValue()
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "Gets the hash value."
  syntax:
    content: public byte[] GetValue ();
    parameters: []
    return:
      type: System.Byte[]
      description: "To be added."
  overload: System.Configuration.Assemblies.AssemblyHash.GetValue*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Assemblies.AssemblyHash.SetValue(System.Byte[])
  id: SetValue(System.Byte[])
  parent: System.Configuration.Assemblies.AssemblyHash
  langs:
  - csharp
  name: SetValue(Byte[])
  nameWithType: AssemblyHash.SetValue(Byte[])
  fullName: System.Configuration.Assemblies.AssemblyHash.SetValue(Byte[])
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "Sets the hash value."
  syntax:
    content: public void SetValue (byte[] value);
    parameters:
    - id: value
      type: System.Byte[]
      description: "The hash value."
  overload: System.Configuration.Assemblies.AssemblyHash.SetValue*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ValueType
  isExternal: false
  name: System.ValueType
- uid: System.Configuration.Assemblies.AssemblyHash.#ctor(System.Byte[])
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: AssemblyHash(Byte[])
  nameWithType: AssemblyHash.AssemblyHash(Byte[])
  fullName: System.Configuration.Assemblies.AssemblyHash.AssemblyHash(Byte[])
- uid: System.Byte[]
  parent: System
  isExternal: true
  name: Byte
  nameWithType: Byte
  fullName: System.Byte[]
  spec.csharp:
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: Byte[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Configuration.Assemblies.AssemblyHash.#ctor(System.Configuration.Assemblies.AssemblyHashAlgorithm,System.Byte[])
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: AssemblyHash(AssemblyHashAlgorithm,Byte[])
  nameWithType: AssemblyHash.AssemblyHash(AssemblyHashAlgorithm,Byte[])
  fullName: System.Configuration.Assemblies.AssemblyHash.AssemblyHash(AssemblyHashAlgorithm,Byte[])
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm
  parent: System.Configuration.Assemblies
  isExternal: false
  name: AssemblyHashAlgorithm
  nameWithType: AssemblyHashAlgorithm
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm
- uid: System.Configuration.Assemblies.AssemblyHash.Algorithm
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: Algorithm
  nameWithType: AssemblyHash.Algorithm
  fullName: System.Configuration.Assemblies.AssemblyHash.Algorithm
- uid: System.Configuration.Assemblies.AssemblyHash.Clone
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: Clone()
  nameWithType: AssemblyHash.Clone()
  fullName: System.Configuration.Assemblies.AssemblyHash.Clone()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.Assemblies.AssemblyHash.Empty
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: Empty
  nameWithType: AssemblyHash.Empty
  fullName: System.Configuration.Assemblies.AssemblyHash.Empty
- uid: System.Configuration.Assemblies.AssemblyHash
  parent: System.Configuration.Assemblies
  isExternal: false
  name: AssemblyHash
  nameWithType: AssemblyHash
  fullName: System.Configuration.Assemblies.AssemblyHash
- uid: System.Configuration.Assemblies.AssemblyHash.GetValue
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: GetValue()
  nameWithType: AssemblyHash.GetValue()
  fullName: System.Configuration.Assemblies.AssemblyHash.GetValue()
- uid: System.Configuration.Assemblies.AssemblyHash.SetValue(System.Byte[])
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: SetValue(Byte[])
  nameWithType: AssemblyHash.SetValue(Byte[])
  fullName: System.Configuration.Assemblies.AssemblyHash.SetValue(Byte[])
- uid: System.Configuration.Assemblies.AssemblyHash.#ctor*
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: AssemblyHash
  nameWithType: AssemblyHash.AssemblyHash
- uid: System.Configuration.Assemblies.AssemblyHash.Algorithm*
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: Algorithm
  nameWithType: AssemblyHash.Algorithm
- uid: System.Configuration.Assemblies.AssemblyHash.Clone*
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: Clone
  nameWithType: AssemblyHash.Clone
- uid: System.Configuration.Assemblies.AssemblyHash.GetValue*
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: GetValue
  nameWithType: AssemblyHash.GetValue
- uid: System.Configuration.Assemblies.AssemblyHash.SetValue*
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: SetValue
  nameWithType: AssemblyHash.SetValue
