### YamlMime:ManagedReference
items:
- uid: System.Web.Management.WebApplicationInformation
  id: WebApplicationInformation
  children:
  - System.Web.Management.WebApplicationInformation.ApplicationDomain
  - System.Web.Management.WebApplicationInformation.ApplicationPath
  - System.Web.Management.WebApplicationInformation.ApplicationVirtualPath
  - System.Web.Management.WebApplicationInformation.FormatToString(System.Web.Management.WebEventFormatter)
  - System.Web.Management.WebApplicationInformation.MachineName
  - System.Web.Management.WebApplicationInformation.ToString
  - System.Web.Management.WebApplicationInformation.TrustLevel
  langs:
  - csharp
  name: WebApplicationInformation
  nameWithType: WebApplicationInformation
  fullName: System.Web.Management.WebApplicationInformation
  type: Class
  summary: "Provides information associated with health events."
  remarks: "ASP.NET health monitoring allows production and operations staff to manage deployed Web applications. The <xref:System.Web.Management?displayProperty=fullName> namespace contains the health-event types responsible for packaging application health-status data and the provider types responsible for processing this data. It also contains supporting types that help during the management of health events.       Instances of the WebApplicationInformation class contain information that is obtained using any of the types derived from the <xref:System.Web.Management.WebManagementEvent> type.       Your application needs the appropriate permissions to access protected information provided by this type.       The following is an excerpt of a configuration file you could use to enable ASP.NET to log error events that contain application information.      ```   <healthMonitoring      enabled=&quot;true&quot; heartBeatInterval=&quot;0&quot;>          <rules>        <add           name=&quot;All Errors Default&quot;          eventName=&quot;All Errors&quot;          provider=&quot;EventLogProvider&quot;          profile=&quot;Default&quot;          minInterval=&quot;00:01:00&quot; />       </rules>      </healthMonitoring>   ```      > [!NOTE] >  In most cases you will be able to use the ASP.NET health-monitoring types as implemented, and you will control the health-monitoring system by specifying values in the `healthMonitoring` configuration section. You can also derive from the health-monitoring types to create your own custom events and providers. For an example of creating a custom event class, see the example provided in this topic."
  example:
  - "The following code example has two parts. The first part is an excerpt of the configuration file that enables ASP.NET to use a custom event. The second shows how to create that custom event by using the WebApplicationInformation class.  \n  \n Ensure that your custom event is raised at the proper time, that is, when the equivalent system health event it replaces would be raised.  \n  \n```  \n<healthMonitoring   \n  enabled=\"true\" heartBeatInterval=\"0\">  \n  \n  <eventMappings>   \n    <add name=\"SampleApplicationInformation\"   \n        type=\"SamplesAspNet.SampleWebApplicationInformation, webapplicationinformation, Version=1.0.1585.27289, Culture=neutral, PublicKeyToken=3648e5c763a8239f, processorArchitecture=MSIL\"/>   \n  </eventMappings>  \n  \n  <rules>   \n    <add name=\"Custom Application Information\"  \n      eventName=\"SampleApplicationInformation\"   \n      provider=\"EventLogProvider\"    \n      profile=\"Default\"/>   \n</rules>  \n  \n</healthMonitoring>  \n```  \n  \n [!code-vb[System.Web.Management.WebApplicationInformation#1](~/add/codesnippet/VisualBasic/t-system.web.management._26_1.vb)]\n [!code-cs[System.Web.Management.WebApplicationInformation#1](~/add/codesnippet/CSharp/t-system.web.management._26_1.cs)]"
  syntax:
    content: public sealed class WebApplicationInformation
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Management.WebApplicationInformation.ApplicationDomain
  id: ApplicationDomain
  parent: System.Web.Management.WebApplicationInformation
  langs:
  - csharp
  name: ApplicationDomain
  nameWithType: WebApplicationInformation.ApplicationDomain
  fullName: System.Web.Management.WebApplicationInformation.ApplicationDomain
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Management
  summary: "Gets the current application domain name."
  remarks: ''
  example:
  - "The following code example shows how to obtain the application domain name.  \n  \n [!code-vb[System.Web.Management.WebApplicationInformation#4](~/add/codesnippet/VisualBasic/p-system.web.management._46_1.vb)]\n [!code-cs[System.Web.Management.WebApplicationInformation#4](~/add/codesnippet/CSharp/p-system.web.management._46_1.cs)]"
  syntax:
    content: public string ApplicationDomain { get; }
    return:
      type: System.String
      description: "Gets the application domain name."
  overload: System.Web.Management.WebApplicationInformation.ApplicationDomain*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Management.WebApplicationInformation.ApplicationPath
  id: ApplicationPath
  parent: System.Web.Management.WebApplicationInformation
  langs:
  - csharp
  name: ApplicationPath
  nameWithType: WebApplicationInformation.ApplicationPath
  fullName: System.Web.Management.WebApplicationInformation.ApplicationPath
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Management
  summary: "Gets the application physical path."
  remarks: "This property requires appropriate permissions to be accessed. Refer to the Permissions section."
  example:
  - "The following code example shows how to obtain the application physical path.  \n  \n [!code-vb[System.Web.Management.WebApplicationInformation#5](~/add/codesnippet/VisualBasic/p-system.web.management._44_1.vb)]\n [!code-cs[System.Web.Management.WebApplicationInformation#5](~/add/codesnippet/CSharp/p-system.web.management._44_1.cs)]"
  syntax:
    content: public string ApplicationPath { get; }
    return:
      type: System.String
      description: "The application physical path."
  overload: System.Web.Management.WebApplicationInformation.ApplicationPath*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Management.WebApplicationInformation.ApplicationVirtualPath
  id: ApplicationVirtualPath
  parent: System.Web.Management.WebApplicationInformation
  langs:
  - csharp
  name: ApplicationVirtualPath
  nameWithType: WebApplicationInformation.ApplicationVirtualPath
  fullName: System.Web.Management.WebApplicationInformation.ApplicationVirtualPath
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Management
  summary: "Gets the application logical path."
  remarks: ''
  example:
  - "The following code example shows how to obtain the application logical path.  \n  \n [!code-vb[System.Web.Management.WebApplicationInformation#6](~/add/codesnippet/VisualBasic/p-system.web.management._36_1.vb)]\n [!code-cs[System.Web.Management.WebApplicationInformation#6](~/add/codesnippet/CSharp/p-system.web.management._36_1.cs)]"
  syntax:
    content: public string ApplicationVirtualPath { get; }
    return:
      type: System.String
      description: "The application logical path."
  overload: System.Web.Management.WebApplicationInformation.ApplicationVirtualPath*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Management.WebApplicationInformation.FormatToString(System.Web.Management.WebEventFormatter)
  id: FormatToString(System.Web.Management.WebEventFormatter)
  parent: System.Web.Management.WebApplicationInformation
  langs:
  - csharp
  name: FormatToString(WebEventFormatter)
  nameWithType: WebApplicationInformation.FormatToString(WebEventFormatter)
  fullName: System.Web.Management.WebApplicationInformation.FormatToString(WebEventFormatter)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Management
  summary: "Formats the application information."
  remarks: "The FormatToString method provides a uniform format for event information, which is useful if the event data must be logged and later presented to the user. It is called internally when the provider invokes one of the <xref:System.Web.Management.WebBaseEvent.ToString%2A> methods.      > [!NOTE] >  When formatting your custom event information for display, override the FormatToString method rather than the <xref:System.Web.Management.WebApplicationInformation.ToString%2A> method. This will avoid overwriting or tampering with sensitive system information."
  example:
  - "The following code example shows how to format custom information.  \n  \n [!code-vb[System.Web.Management.WebApplicationInformation#9](~/add/codesnippet/VisualBasic/e7244ae1-98b8-46f8-b4c6-_1.vb)]\n [!code-cs[System.Web.Management.WebApplicationInformation#9](~/add/codesnippet/CSharp/e7244ae1-98b8-46f8-b4c6-_1.cs)]"
  syntax:
    content: public void FormatToString (System.Web.Management.WebEventFormatter formatter);
    parameters:
    - id: formatter
      type: System.Web.Management.WebEventFormatter
      description: "The  that contains the tab and indentation settings used to format the Web health event information."
  overload: System.Web.Management.WebApplicationInformation.FormatToString*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Management.WebApplicationInformation.MachineName
  id: MachineName
  parent: System.Web.Management.WebApplicationInformation
  langs:
  - csharp
  name: MachineName
  nameWithType: WebApplicationInformation.MachineName
  fullName: System.Web.Management.WebApplicationInformation.MachineName
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Management
  summary: "Gets the application machine name."
  remarks: ''
  example:
  - "The following code example shows how to obtain the machine name.  \n  \n [!code-vb[System.Web.Management.WebApplicationInformation#7](~/add/codesnippet/VisualBasic/p-system.web.management._25_1.vb)]\n [!code-cs[System.Web.Management.WebApplicationInformation#7](~/add/codesnippet/CSharp/p-system.web.management._25_1.cs)]"
  syntax:
    content: public string MachineName { get; }
    return:
      type: System.String
      description: "The name of the machine where the application is running."
  overload: System.Web.Management.WebApplicationInformation.MachineName*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Management.WebApplicationInformation.ToString
  id: ToString
  parent: System.Web.Management.WebApplicationInformation
  langs:
  - csharp
  name: ToString()
  nameWithType: WebApplicationInformation.ToString()
  fullName: System.Web.Management.WebApplicationInformation.ToString()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Management
  summary: "Formats event information for display purposes."
  remarks: "The <xref:System.Web.Management.WebBaseEvent.ToString%2A> method formats event information by calling the <xref:System.Web.Management.WebApplicationInformation.FormatToString%2A> method.      > [!NOTE] >  When formatting your custom event information for display, override the <xref:System.Web.Management.WebApplicationInformation.FormatToString%2A> method rather than this ToString method. This will avoid overwriting or tampering with sensitive system information."
  example:
  - For an example of using the ToString method, see <xref:System.Web.Management.WebEventProvider>.
  syntax:
    content: public override string ToString ();
    parameters: []
    return:
      type: System.String
      description: "To be added."
  overload: System.Web.Management.WebApplicationInformation.ToString*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Management.WebApplicationInformation.TrustLevel
  id: TrustLevel
  parent: System.Web.Management.WebApplicationInformation
  langs:
  - csharp
  name: TrustLevel
  nameWithType: WebApplicationInformation.TrustLevel
  fullName: System.Web.Management.WebApplicationInformation.TrustLevel
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Management
  summary: "Gets the application trust level."
  remarks: "This property requires appropriate permissions to be accessed. Refer to the Permissions section."
  example:
  - "The following example shows how to obtain the application-trust-level information.  \n  \n [!code-vb[System.Web.Management.WebApplicationInformation#8](~/add/codesnippet/VisualBasic/p-system.web.management._2_1.vb)]\n [!code-cs[System.Web.Management.WebApplicationInformation#8](~/add/codesnippet/CSharp/p-system.web.management._2_1.cs)]"
  syntax:
    content: public string TrustLevel { get; }
    return:
      type: System.String
      description: "The application trust level."
  overload: System.Web.Management.WebApplicationInformation.TrustLevel*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Management.WebApplicationInformation.ApplicationDomain
  parent: System.Web.Management.WebApplicationInformation
  isExternal: false
  name: ApplicationDomain
  nameWithType: WebApplicationInformation.ApplicationDomain
  fullName: System.Web.Management.WebApplicationInformation.ApplicationDomain
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Management.WebApplicationInformation.ApplicationPath
  parent: System.Web.Management.WebApplicationInformation
  isExternal: false
  name: ApplicationPath
  nameWithType: WebApplicationInformation.ApplicationPath
  fullName: System.Web.Management.WebApplicationInformation.ApplicationPath
- uid: System.Web.Management.WebApplicationInformation.ApplicationVirtualPath
  parent: System.Web.Management.WebApplicationInformation
  isExternal: false
  name: ApplicationVirtualPath
  nameWithType: WebApplicationInformation.ApplicationVirtualPath
  fullName: System.Web.Management.WebApplicationInformation.ApplicationVirtualPath
- uid: System.Web.Management.WebApplicationInformation.FormatToString(System.Web.Management.WebEventFormatter)
  parent: System.Web.Management.WebApplicationInformation
  isExternal: false
  name: FormatToString(WebEventFormatter)
  nameWithType: WebApplicationInformation.FormatToString(WebEventFormatter)
  fullName: System.Web.Management.WebApplicationInformation.FormatToString(WebEventFormatter)
- uid: System.Web.Management.WebEventFormatter
  parent: System.Web.Management
  isExternal: false
  name: WebEventFormatter
  nameWithType: WebEventFormatter
  fullName: System.Web.Management.WebEventFormatter
- uid: System.Web.Management.WebApplicationInformation.MachineName
  parent: System.Web.Management.WebApplicationInformation
  isExternal: false
  name: MachineName
  nameWithType: WebApplicationInformation.MachineName
  fullName: System.Web.Management.WebApplicationInformation.MachineName
- uid: System.Web.Management.WebApplicationInformation.ToString
  parent: System.Web.Management.WebApplicationInformation
  isExternal: false
  name: ToString()
  nameWithType: WebApplicationInformation.ToString()
  fullName: System.Web.Management.WebApplicationInformation.ToString()
- uid: System.Web.Management.WebApplicationInformation.TrustLevel
  parent: System.Web.Management.WebApplicationInformation
  isExternal: false
  name: TrustLevel
  nameWithType: WebApplicationInformation.TrustLevel
  fullName: System.Web.Management.WebApplicationInformation.TrustLevel
- uid: System.Web.Management.WebApplicationInformation.ApplicationDomain*
  parent: System.Web.Management.WebApplicationInformation
  isExternal: false
  name: ApplicationDomain
  nameWithType: WebApplicationInformation.ApplicationDomain
- uid: System.Web.Management.WebApplicationInformation.ApplicationPath*
  parent: System.Web.Management.WebApplicationInformation
  isExternal: false
  name: ApplicationPath
  nameWithType: WebApplicationInformation.ApplicationPath
- uid: System.Web.Management.WebApplicationInformation.ApplicationVirtualPath*
  parent: System.Web.Management.WebApplicationInformation
  isExternal: false
  name: ApplicationVirtualPath
  nameWithType: WebApplicationInformation.ApplicationVirtualPath
- uid: System.Web.Management.WebApplicationInformation.FormatToString*
  parent: System.Web.Management.WebApplicationInformation
  isExternal: false
  name: FormatToString
  nameWithType: WebApplicationInformation.FormatToString
- uid: System.Web.Management.WebApplicationInformation.MachineName*
  parent: System.Web.Management.WebApplicationInformation
  isExternal: false
  name: MachineName
  nameWithType: WebApplicationInformation.MachineName
- uid: System.Web.Management.WebApplicationInformation.ToString*
  parent: System.Web.Management.WebApplicationInformation
  isExternal: false
  name: ToString
  nameWithType: WebApplicationInformation.ToString
- uid: System.Web.Management.WebApplicationInformation.TrustLevel*
  parent: System.Web.Management.WebApplicationInformation
  isExternal: false
  name: TrustLevel
  nameWithType: WebApplicationInformation.TrustLevel
