### YamlMime:ManagedReference
items:
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  id: PeerApplicationLaunchInfo
  children:
  - System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data
  - System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message
  - System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication
  - System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact
  - System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint
  langs:
  - csharp
  name: PeerApplicationLaunchInfo
  nameWithType: PeerApplicationLaunchInfo
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  type: Class
  summary: "Represents the launch information required by a <see cref=&quot;T:System.Net.PeerToPeer.Collaboration.PeerApplication&quot;></see> that has initiated in response to a peer collaboration invitation."
  remarks: "An application can inspect the <xref:System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data%2A> and <xref:System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message%2A> properties in this class to get the information specific to the invitation that initiated the application launch.       Access to this class requires a <xref:System.Security.Permissions.PermissionState> of <xref:System.Security.Permissions.PermissionState>. This state is created when the <xref:System.Net.PeerToPeer.Collaboration.Peer> collaboration session begins."
  syntax:
    content: public class PeerApplicationLaunchInfo
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data
  id: Data
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  langs:
  - csharp
  name: Data
  nameWithType: PeerApplicationLaunchInfo.Data
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Gets or sets application-defined binary data associated with the <see cref=&quot;T:System.Net.PeerToPeer.Collaboration.PeerApplication&quot;></see> invitation."
  remarks: "This data blob is free form and is provided by the caller.  The maximum amount of data that can be provided is 4,096 bytes.       The Data cannot be `null`."
  syntax:
    content: public byte[] Data { get; }
    return:
      type: System.Byte[]
      description: "An array of bytes that containing the data associated with the <see cref=&quot;T:System.Net.PeerToPeer.Collaboration.PeerCollaboration&quot;></see> invitation."
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message
  id: Message
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  langs:
  - csharp
  name: Message
  nameWithType: PeerApplicationLaunchInfo.Message
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Get or set a message associated with the response to the <see cref=&quot;T:System.Net.PeerToPeer.Collaboration.PeerCollaboration&quot;></see> invitation."
  remarks: "The maximum length for the message is 255 Unicode characters. Unless explicitly specified, the default value for all properties is `null` for reference types."
  syntax:
    content: public string Message { get; }
    return:
      type: System.String
      description: "A text message associated with the <see cref=&quot;T:System.Net.PeerToPeer.Collaboration.PeerInvitationResponse&quot;></see> to the <see cref=&quot;T:System.Net.PeerToPeer.Collaboration.PeerCollaboration&quot;></see> invitation."
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication
  id: PeerApplication
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  langs:
  - csharp
  name: PeerApplication
  nameWithType: PeerApplicationLaunchInfo.PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Gets or sets the <see cref=&quot;T:System.Net.PeerToPeer.Collaboration.PeerApplication&quot;></see> for which the invitation was sent."
  remarks: "Unless explicitly specified, the default value for all properties is `null` for reference types."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerApplication PeerApplication { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerApplication
      description: "The <see cref=&quot;T:System.Net.PeerToPeer.Collaboration.PeerApplication&quot;></see> for which the <see cref=&quot;T:System.Net.PeerToPeer.Collaboration.PeerCollaboration&quot;></see> invitation was sent."
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact
  id: PeerContact
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  langs:
  - csharp
  name: PeerContact
  nameWithType: PeerApplicationLaunchInfo.PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Gets or sets the <see cref=&quot;T:System.Net.PeerToPeer.Collaboration.PeerContact&quot;></see> that sent the invitation."
  remarks: "Unless explicitly specified, the default value for all properties is `null` for reference types."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerContact PeerContact { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerContact
      description: "The <see cref=&quot;T:System.Net.PeerToPeer.Collaboration.PeerContact&quot;></see> that sent the invitation."
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint
  id: PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  langs:
  - csharp
  name: PeerEndPoint
  nameWithType: PeerApplicationLaunchInfo.PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Gets or sets the <see cref=&quot;T:System.Net.PeerToPeer.Collaboration.PeerEndPoint&quot;></see> from which the <see cref=&quot;T:System.Net.PeerToPeer.Collaboration.PeerApplication&quot;></see> invitation was sent."
  remarks: "Unless explicitly specified, the default value for all properties is `null` for reference types."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerEndPoint PeerEndPoint { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerEndPoint
      description: "The <see cref=&quot;T:System.Net.PeerToPeer.Collaboration.PeerEndPoint&quot;></see> from which the invitation was sent."
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: Data
  nameWithType: PeerApplicationLaunchInfo.Data
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data
- uid: System.Byte[]
  parent: System
  isExternal: true
  name: Byte
  nameWithType: Byte
  fullName: System.Byte[]
  spec.csharp:
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: Byte[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: Message
  nameWithType: PeerApplicationLaunchInfo.Message
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerApplication
  nameWithType: PeerApplicationLaunchInfo.PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.PeerApplication
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerApplication
  nameWithType: PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerContact
  nameWithType: PeerApplicationLaunchInfo.PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.PeerContact
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerContact
  nameWithType: PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerEndPoint
  nameWithType: PeerApplicationLaunchInfo.PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint
- uid: System.Net.PeerToPeer.Collaboration.PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerEndPoint
  nameWithType: PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.PeerEndPoint
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: Data
  nameWithType: PeerApplicationLaunchInfo.Data
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: Message
  nameWithType: PeerApplicationLaunchInfo.Message
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerApplication
  nameWithType: PeerApplicationLaunchInfo.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerContact
  nameWithType: PeerApplicationLaunchInfo.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerEndPoint
  nameWithType: PeerApplicationLaunchInfo.PeerEndPoint
