### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.PnrpPeerResolverElement
  id: PnrpPeerResolverElement
  children:
  - System.ServiceModel.Configuration.PnrpPeerResolverElement.#ctor
  - System.ServiceModel.Configuration.PnrpPeerResolverElement.BindingElementType
  - System.ServiceModel.Configuration.PnrpPeerResolverElement.CreateBindingElement
  langs:
  - csharp
  name: PnrpPeerResolverElement
  nameWithType: PnrpPeerResolverElement
  fullName: System.ServiceModel.Configuration.PnrpPeerResolverElement
  type: Class
  summary: "Specifies a configuration element for a Peer Name Resolution Protocol (PNRP) name resolution service."
  syntax:
    content: 'public class PnrpPeerResolverElement : System.ServiceModel.Configuration.BindingElementExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  - System.ServiceModel.Configuration.BindingElementExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.BindingElementExtensionElement.ApplyConfiguration(System.ServiceModel.Channels.BindingElement)
  - System.ServiceModel.Configuration.BindingElementExtensionElement.InitializeFrom(System.ServiceModel.Channels.BindingElement)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.PnrpPeerResolverElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.PnrpPeerResolverElement
  langs:
  - csharp
  name: PnrpPeerResolverElement()
  nameWithType: PnrpPeerResolverElement.PnrpPeerResolverElement()
  fullName: System.ServiceModel.Configuration.PnrpPeerResolverElement.PnrpPeerResolverElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.PnrpPeerResolverElement&quot;></see> class."
  syntax:
    content: public PnrpPeerResolverElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.PnrpPeerResolverElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.PnrpPeerResolverElement.BindingElementType
  id: BindingElementType
  parent: System.ServiceModel.Configuration.PnrpPeerResolverElement
  langs:
  - csharp
  name: BindingElementType
  nameWithType: PnrpPeerResolverElement.BindingElementType
  fullName: System.ServiceModel.Configuration.PnrpPeerResolverElement.BindingElementType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets the &lt;xref:System.Type&gt; object that represents the custom binding element."
  syntax:
    content: public override Type BindingElementType { get; }
    return:
      type: System.Type
      description: "A &lt;xref:System.Type&gt; object that represents the custom binding element."
  overload: System.ServiceModel.Configuration.PnrpPeerResolverElement.BindingElementType*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.PnrpPeerResolverElement.CreateBindingElement
  id: CreateBindingElement
  parent: System.ServiceModel.Configuration.PnrpPeerResolverElement
  langs:
  - csharp
  name: CreateBindingElement()
  nameWithType: PnrpPeerResolverElement.CreateBindingElement()
  fullName: System.ServiceModel.Configuration.PnrpPeerResolverElement.CreateBindingElement()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Creates a new custom binding element object whose properties are copied from the settings of this configuration element."
  syntax:
    content: protected override System.ServiceModel.Channels.BindingElement CreateBindingElement ();
    parameters: []
    return:
      type: System.ServiceModel.Channels.BindingElement
      description: "To be added."
  overload: System.ServiceModel.Configuration.PnrpPeerResolverElement.CreateBindingElement*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement
  isExternal: false
  name: System.ServiceModel.Configuration.BindingElementExtensionElement
- uid: System.ServiceModel.Configuration.PnrpPeerResolverElement.#ctor
  parent: System.ServiceModel.Configuration.PnrpPeerResolverElement
  isExternal: false
  name: PnrpPeerResolverElement()
  nameWithType: PnrpPeerResolverElement.PnrpPeerResolverElement()
  fullName: System.ServiceModel.Configuration.PnrpPeerResolverElement.PnrpPeerResolverElement()
- uid: System.ServiceModel.Configuration.PnrpPeerResolverElement.BindingElementType
  parent: System.ServiceModel.Configuration.PnrpPeerResolverElement
  isExternal: false
  name: BindingElementType
  nameWithType: PnrpPeerResolverElement.BindingElementType
  fullName: System.ServiceModel.Configuration.PnrpPeerResolverElement.BindingElementType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.PnrpPeerResolverElement.CreateBindingElement
  parent: System.ServiceModel.Configuration.PnrpPeerResolverElement
  isExternal: false
  name: CreateBindingElement()
  nameWithType: PnrpPeerResolverElement.CreateBindingElement()
  fullName: System.ServiceModel.Configuration.PnrpPeerResolverElement.CreateBindingElement()
- uid: System.ServiceModel.Channels.BindingElement
  parent: System.ServiceModel.Channels
  isExternal: true
  name: BindingElement
  nameWithType: BindingElement
  fullName: System.ServiceModel.Channels.BindingElement
- uid: System.ServiceModel.Configuration.PnrpPeerResolverElement.#ctor*
  parent: System.ServiceModel.Configuration.PnrpPeerResolverElement
  isExternal: false
  name: PnrpPeerResolverElement
  nameWithType: PnrpPeerResolverElement.PnrpPeerResolverElement
- uid: System.ServiceModel.Configuration.PnrpPeerResolverElement.BindingElementType*
  parent: System.ServiceModel.Configuration.PnrpPeerResolverElement
  isExternal: false
  name: BindingElementType
  nameWithType: PnrpPeerResolverElement.BindingElementType
- uid: System.ServiceModel.Configuration.PnrpPeerResolverElement.CreateBindingElement*
  parent: System.ServiceModel.Configuration.PnrpPeerResolverElement
  isExternal: false
  name: CreateBindingElement
  nameWithType: PnrpPeerResolverElement.CreateBindingElement
