### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingChangingEventArgs
  id: SettingChangingEventArgs
  children:
  - System.Configuration.SettingChangingEventArgs.#ctor(System.String,System.String,System.String,System.Object,System.Boolean)
  - System.Configuration.SettingChangingEventArgs.NewValue
  - System.Configuration.SettingChangingEventArgs.SettingClass
  - System.Configuration.SettingChangingEventArgs.SettingKey
  - System.Configuration.SettingChangingEventArgs.SettingName
  langs:
  - csharp
  name: SettingChangingEventArgs
  nameWithType: SettingChangingEventArgs
  fullName: System.Configuration.SettingChangingEventArgs
  type: Class
  summary: "Provides data for the <see cref=&quot;E:System.Configuration.ApplicationSettingsBase.SettingChanging&quot;></see> event."
  remarks: "The SettingChangingEventArgs class provides data for the <xref:System.Configuration.ApplicationSettingsBase.SettingChanging> event, which signals that the value of an application settings property is about to change. The most common source for this event is the `get` accessor of the <xref:System.Configuration.ApplicationSettingsBase.Item%2A> method in the <xref:System.Configuration.ApplicationSettingsBase> class.       Because SettingChangingEventArgs is derived from <xref:System.ComponentModel.CancelEventArgs>, the handler has the option of canceling the write operation."
  syntax:
    content: 'public class SettingChangingEventArgs : System.ComponentModel.CancelEventArgs'
  inheritance:
  - System.ComponentModel.CancelEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SettingChangingEventArgs.#ctor(System.String,System.String,System.String,System.Object,System.Boolean)
  id: '#ctor(System.String,System.String,System.String,System.Object,System.Boolean)'
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: SettingChangingEventArgs(String,String,String,Object,Boolean)
  nameWithType: SettingChangingEventArgs.SettingChangingEventArgs(String,String,String,Object,Boolean)
  fullName: System.Configuration.SettingChangingEventArgs.SettingChangingEventArgs(String,String,String,Object,Boolean)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initializes an instance of the <see cref=&quot;T:System.Configuration.SettingChangingEventArgs&quot;></see> class."
  remarks: "The SettingChangingEventArgs constructor just assigns the values of the parameters to the corresponding properties in the <xref:System.Configuration.SettingChangingEventArgs> class."
  syntax:
    content: public SettingChangingEventArgs (string settingName, string settingClass, string settingKey, object newValue, bool cancel);
    parameters:
    - id: settingName
      type: System.String
      description: "A <xref:System.String> containing the name of the application setting."
    - id: settingClass
      type: System.String
      description: "A <xref:System.String> containing a category description of the setting. Often this parameter is set to the application settings group name."
    - id: settingKey
      type: System.String
      description: "A <xref:System.String> containing the application settings key."
    - id: newValue
      type: System.Object
      description: "An <xref:System.Object> that contains the new value to be assigned to the application settings property."
    - id: cancel
      type: System.Boolean
      description: "\n     to cancel the event; otherwise, ."
  overload: System.Configuration.SettingChangingEventArgs.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SettingChangingEventArgs.NewValue
  id: NewValue
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: NewValue
  nameWithType: SettingChangingEventArgs.NewValue
  fullName: System.Configuration.SettingChangingEventArgs.NewValue
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Gets the new value being assigned to the application settings property."
  remarks: "The actual type of the NewValue property should be compatible with the settings property being set. The latter is available though the <xref:System.Configuration.SettingsProperty.PropertyType%2A> property of the <xref:System.Configuration.SettingsProperty> class."
  syntax:
    content: public object NewValue { get; }
    return:
      type: System.Object
      description: "An &lt;xref:System.Object&gt; that contains the new value to be assigned to the application settings property."
  overload: System.Configuration.SettingChangingEventArgs.NewValue*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SettingChangingEventArgs.SettingClass
  id: SettingClass
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: SettingClass
  nameWithType: SettingChangingEventArgs.SettingClass
  fullName: System.Configuration.SettingChangingEventArgs.SettingClass
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Gets the application settings property category."
  remarks: "All application settings belong to a application settings group. The group name can be explicitly supplied by decorating the class with a <xref:System.Configuration.SettingsGroupNameAttribute>; otherwise, one is generated using the name of the settings wrapper class."
  syntax:
    content: public string SettingClass { get; }
    return:
      type: System.String
      description: "A &lt;xref:System.String&gt; containing a category description of the setting. Typically, this parameter is set to the application settings group name."
  overload: System.Configuration.SettingChangingEventArgs.SettingClass*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SettingChangingEventArgs.SettingKey
  id: SettingKey
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: SettingKey
  nameWithType: SettingChangingEventArgs.SettingKey
  fullName: System.Configuration.SettingChangingEventArgs.SettingKey
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Gets the application settings key associated with the property."
  remarks: "Each settings wrapper class, derived from <xref:System.Configuration.ApplicationSettingsBase>, has an associated settings key, which is a string that helps disambiguate different instances of the same wrapper in a single application. Because each wrapper class defines a set of properties that represent application settings, the settings key can similarly help disambiguate their use."
  syntax:
    content: public string SettingKey { get; }
    return:
      type: System.String
      description: "A &lt;xref:System.String&gt; containing the application settings key."
  overload: System.Configuration.SettingChangingEventArgs.SettingKey*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SettingChangingEventArgs.SettingName
  id: SettingName
  parent: System.Configuration.SettingChangingEventArgs
  langs:
  - csharp
  name: SettingName
  nameWithType: SettingChangingEventArgs.SettingName
  fullName: System.Configuration.SettingChangingEventArgs.SettingName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Gets the name of the application setting associated with the application settings property."
  remarks: "Typically the settings wrapper class, derived from <xref:System.Configuration.ApplicationSettingsBase>, will be constructed so that the name of the application settings property will be the same as its associated application setting."
  syntax:
    content: public string SettingName { get; }
    return:
      type: System.String
      description: "A &lt;xref:System.String&gt; containing the name of the application setting."
  overload: System.Configuration.SettingChangingEventArgs.SettingName*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ComponentModel.CancelEventArgs
  isExternal: false
  name: System.ComponentModel.CancelEventArgs
- uid: System.Configuration.SettingChangingEventArgs.#ctor(System.String,System.String,System.String,System.Object,System.Boolean)
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingChangingEventArgs(String,String,String,Object,Boolean)
  nameWithType: SettingChangingEventArgs.SettingChangingEventArgs(String,String,String,Object,Boolean)
  fullName: System.Configuration.SettingChangingEventArgs.SettingChangingEventArgs(String,String,String,Object,Boolean)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.SettingChangingEventArgs.NewValue
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: NewValue
  nameWithType: SettingChangingEventArgs.NewValue
  fullName: System.Configuration.SettingChangingEventArgs.NewValue
- uid: System.Configuration.SettingChangingEventArgs.SettingClass
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingClass
  nameWithType: SettingChangingEventArgs.SettingClass
  fullName: System.Configuration.SettingChangingEventArgs.SettingClass
- uid: System.Configuration.SettingChangingEventArgs.SettingKey
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingKey
  nameWithType: SettingChangingEventArgs.SettingKey
  fullName: System.Configuration.SettingChangingEventArgs.SettingKey
- uid: System.Configuration.SettingChangingEventArgs.SettingName
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingName
  nameWithType: SettingChangingEventArgs.SettingName
  fullName: System.Configuration.SettingChangingEventArgs.SettingName
- uid: System.Configuration.SettingChangingEventArgs.#ctor*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingChangingEventArgs
  nameWithType: SettingChangingEventArgs.SettingChangingEventArgs
- uid: System.Configuration.SettingChangingEventArgs.NewValue*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: NewValue
  nameWithType: SettingChangingEventArgs.NewValue
- uid: System.Configuration.SettingChangingEventArgs.SettingClass*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingClass
  nameWithType: SettingChangingEventArgs.SettingClass
- uid: System.Configuration.SettingChangingEventArgs.SettingKey*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingKey
  nameWithType: SettingChangingEventArgs.SettingKey
- uid: System.Configuration.SettingChangingEventArgs.SettingName*
  parent: System.Configuration.SettingChangingEventArgs
  isExternal: false
  name: SettingName
  nameWithType: SettingChangingEventArgs.SettingName
