### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.PeerResolvers.PeerResolverSettings
  id: PeerResolverSettings
  children:
  - System.ServiceModel.PeerResolvers.PeerResolverSettings.#ctor
  - System.ServiceModel.PeerResolvers.PeerResolverSettings.Custom
  - System.ServiceModel.PeerResolvers.PeerResolverSettings.Mode
  - System.ServiceModel.PeerResolvers.PeerResolverSettings.ReferralPolicy
  langs:
  - csharp
  name: PeerResolverSettings
  nameWithType: PeerResolverSettings
  fullName: System.ServiceModel.PeerResolvers.PeerResolverSettings
  type: Class
  summary: "Defines the settings for a peer resolver service."
  syntax:
    content: public class PeerResolverSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.PeerResolvers.PeerResolverSettings.#ctor
  id: '#ctor'
  parent: System.ServiceModel.PeerResolvers.PeerResolverSettings
  langs:
  - csharp
  name: PeerResolverSettings()
  nameWithType: PeerResolverSettings.PeerResolverSettings()
  fullName: System.ServiceModel.PeerResolvers.PeerResolverSettings.PeerResolverSettings()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.PeerResolvers.PeerResolverSettings&quot;></see> class."
  syntax:
    content: public PeerResolverSettings ();
    parameters: []
  overload: System.ServiceModel.PeerResolvers.PeerResolverSettings.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.PeerResolvers.PeerResolverSettings.Custom
  id: Custom
  parent: System.ServiceModel.PeerResolvers.PeerResolverSettings
  langs:
  - csharp
  name: Custom
  nameWithType: PeerResolverSettings.Custom
  fullName: System.ServiceModel.PeerResolvers.PeerResolverSettings.Custom
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Gets the specific settings for a custom peer resolver."
  remarks: "This property is set only if <xref:System.ServiceModel.PeerResolvers.PeerResolverSettings.Mode%2A> is set to <xref:System.ServiceModel.PeerResolvers.PeerResolverMode>."
  syntax:
    content: public System.ServiceModel.PeerResolvers.PeerCustomResolverSettings Custom { get; }
    return:
      type: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
      description: "<see cref=&quot;T:System.ServiceModel.PeerResolvers.PeerCustomResolverSettings&quot;></see> that contains the settings and resolver instance for the associated custom peer resolver service."
  overload: System.ServiceModel.PeerResolvers.PeerResolverSettings.Custom*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.PeerResolvers.PeerResolverSettings.Mode
  id: Mode
  parent: System.ServiceModel.PeerResolvers.PeerResolverSettings
  langs:
  - csharp
  name: Mode
  nameWithType: PeerResolverSettings.Mode
  fullName: System.ServiceModel.PeerResolvers.PeerResolverSettings.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Gets or sets whether the peer resolver instance associated with this service is either PNRP-specific, a custom resolver, or automatically determined."
  syntax:
    content: public System.ServiceModel.PeerResolvers.PeerResolverMode Mode { get; set; }
    return:
      type: System.ServiceModel.PeerResolvers.PeerResolverMode
      description: "<see cref=&quot;T:System.ServiceModel.PeerResolvers.PeerResolverMode&quot;></see> enumeration value that specifies the mode of the peer resolver service."
  overload: System.ServiceModel.PeerResolvers.PeerResolverSettings.Mode*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.PeerResolvers.PeerResolverSettings.ReferralPolicy
  id: ReferralPolicy
  parent: System.ServiceModel.PeerResolvers.PeerResolverSettings
  langs:
  - csharp
  name: ReferralPolicy
  nameWithType: PeerResolverSettings.ReferralPolicy
  fullName: System.ServiceModel.PeerResolvers.PeerResolverSettings.ReferralPolicy
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Gets or sets the specific referral policy used by the peer resolver service."
  syntax:
    content: public System.ServiceModel.PeerResolvers.PeerReferralPolicy ReferralPolicy { get; set; }
    return:
      type: System.ServiceModel.PeerResolvers.PeerReferralPolicy
      description: "<see cref=&quot;T:System.ServiceModel.PeerResolvers.PeerReferralPolicy&quot;></see> that specifies whether peer referrals are shared or not."
  overload: System.ServiceModel.PeerResolvers.PeerResolverSettings.ReferralPolicy*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.PeerResolvers.PeerResolverSettings.#ctor
  parent: System.ServiceModel.PeerResolvers.PeerResolverSettings
  isExternal: false
  name: PeerResolverSettings()
  nameWithType: PeerResolverSettings.PeerResolverSettings()
  fullName: System.ServiceModel.PeerResolvers.PeerResolverSettings.PeerResolverSettings()
- uid: System.ServiceModel.PeerResolvers.PeerResolverSettings.Custom
  parent: System.ServiceModel.PeerResolvers.PeerResolverSettings
  isExternal: false
  name: Custom
  nameWithType: PeerResolverSettings.Custom
  fullName: System.ServiceModel.PeerResolvers.PeerResolverSettings.Custom
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  parent: System.ServiceModel.PeerResolvers
  isExternal: false
  name: PeerCustomResolverSettings
  nameWithType: PeerCustomResolverSettings
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
- uid: System.ServiceModel.PeerResolvers.PeerResolverSettings.Mode
  parent: System.ServiceModel.PeerResolvers.PeerResolverSettings
  isExternal: false
  name: Mode
  nameWithType: PeerResolverSettings.Mode
  fullName: System.ServiceModel.PeerResolvers.PeerResolverSettings.Mode
- uid: System.ServiceModel.PeerResolvers.PeerResolverMode
  parent: System.ServiceModel.PeerResolvers
  isExternal: false
  name: PeerResolverMode
  nameWithType: PeerResolverMode
  fullName: System.ServiceModel.PeerResolvers.PeerResolverMode
- uid: System.ServiceModel.PeerResolvers.PeerResolverSettings.ReferralPolicy
  parent: System.ServiceModel.PeerResolvers.PeerResolverSettings
  isExternal: false
  name: ReferralPolicy
  nameWithType: PeerResolverSettings.ReferralPolicy
  fullName: System.ServiceModel.PeerResolvers.PeerResolverSettings.ReferralPolicy
- uid: System.ServiceModel.PeerResolvers.PeerReferralPolicy
  parent: System.ServiceModel.PeerResolvers
  isExternal: false
  name: PeerReferralPolicy
  nameWithType: PeerReferralPolicy
  fullName: System.ServiceModel.PeerResolvers.PeerReferralPolicy
- uid: System.ServiceModel.PeerResolvers.PeerResolverSettings.#ctor*
  parent: System.ServiceModel.PeerResolvers.PeerResolverSettings
  isExternal: false
  name: PeerResolverSettings
  nameWithType: PeerResolverSettings.PeerResolverSettings
- uid: System.ServiceModel.PeerResolvers.PeerResolverSettings.Custom*
  parent: System.ServiceModel.PeerResolvers.PeerResolverSettings
  isExternal: false
  name: Custom
  nameWithType: PeerResolverSettings.Custom
- uid: System.ServiceModel.PeerResolvers.PeerResolverSettings.Mode*
  parent: System.ServiceModel.PeerResolvers.PeerResolverSettings
  isExternal: false
  name: Mode
  nameWithType: PeerResolverSettings.Mode
- uid: System.ServiceModel.PeerResolvers.PeerResolverSettings.ReferralPolicy*
  parent: System.ServiceModel.PeerResolvers.PeerResolverSettings
  isExternal: false
  name: ReferralPolicy
  nameWithType: PeerResolverSettings.ReferralPolicy
