### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  id: BrowserCapabilitiesCodeGenerator
  children:
  - System.Web.Configuration.BrowserCapabilitiesCodeGenerator.#ctor
  - System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create
  - System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(System.Boolean,System.String)
  - System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall
  langs:
  - csharp
  name: BrowserCapabilitiesCodeGenerator
  nameWithType: BrowserCapabilitiesCodeGenerator
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  type: Class
  summary: "The BrowserCapabilitiesCodeGenerator class is used internally by the <xref uid=&quot;langword_csharp_aspnet_regbrowsers&quot; name=&quot;aspnet_regbrowsers&quot; href=&quot;&quot;></xref> tool to parse .browser browser definition files and add browsers to the run-time collection of known browsers contained in the <see cref=&quot;T:System.Web.Configuration.BrowserCapabilitiesFactory&quot;></see> object."
  remarks: "This class generates the source code for an assembly for the <xref:System.Web.Configuration.BrowserCapabilitiesFactory> class, which, at run time, produces request-specific <xref:System.Web.Configuration.HttpCapabilitiesBase> objects to be publicly accessed through the ASP.NET intrinsic `Request.Browser` property."
  syntax:
    content: public class BrowserCapabilitiesCodeGenerator
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  langs:
  - csharp
  name: BrowserCapabilitiesCodeGenerator()
  nameWithType: BrowserCapabilitiesCodeGenerator.BrowserCapabilitiesCodeGenerator()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.BrowserCapabilitiesCodeGenerator()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Used internally to create a new instance of <see cref=&quot;T:System.Web.Configuration.BrowserCapabilitiesCodeGenerator&quot;></see>."
  syntax:
    content: public BrowserCapabilitiesCodeGenerator ();
    parameters: []
  overload: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create
  id: Create
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  langs:
  - csharp
  name: Create()
  nameWithType: BrowserCapabilitiesCodeGenerator.Create()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Used internally to coordinate the behavior of this class."
  remarks: "This method first iterates through the &quot;Browsers&quot; folder. It then calls <xref:System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles%2A>, which loads and parses the XML contained in a collection of browser-definition files and inserts the information contained therein into an internal collection of browsers. Then it calls an internal method which generates the source code compiles it, and registers it as an assembly in the global assembly cache for the <xref:System.Web.Configuration.BrowserCapabilitiesFactory> object. If necessary, this method then calls an internal method that restarts the Web server."
  syntax:
    content: public virtual void Create ();
    parameters: []
  overload: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(System.Boolean,System.String)
  id: ProcessBrowserFiles(System.Boolean,System.String)
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  langs:
  - csharp
  name: ProcessBrowserFiles(Boolean,String)
  nameWithType: BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(Boolean,String)
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(Boolean,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Loads and parses the XML contained in a collection of browser-definition files and inserts the information contained therein into an internal collection of browsers."
  syntax:
    content: protected void ProcessBrowserFiles (bool useVirtualPath, string virtualDir);
    parameters:
    - id: useVirtualPath
      type: System.Boolean
      description: "\n     to use a virtual path; otherwise, . The default is ."
    - id: virtualDir
      type: System.String
      description: "The path to the virtual directory that contains the browser-definition files. The default is <xref:System.String>."
  overload: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles*
  exceptions:
  - type: System.Web.HttpParseException
    commentId: T:System.Web.HttpParseException
    description: "One of the browser-definition files does not have a root element named \"browsers\".  \n  \n \\- or -  \n  \n One of the browser-definition files fails to load."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall
  id: Uninstall
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  langs:
  - csharp
  name: Uninstall()
  nameWithType: BrowserCapabilitiesCodeGenerator.Uninstall()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Removes the browser capabilities factory from the global assembly cache and deletes its strong name public key token file."
  remarks: "This method restarts the Web service. The browser capabilities factory is then removed from the global assembly cache, and its strong name public key token file is deleted. The Web service is then restarted again if the uninstall succeeds."
  syntax:
    content: public bool Uninstall ();
    parameters: []
    return:
      type: System.Boolean
      description: "To be added."
  overload: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.#ctor
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: BrowserCapabilitiesCodeGenerator()
  nameWithType: BrowserCapabilitiesCodeGenerator.BrowserCapabilitiesCodeGenerator()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.BrowserCapabilitiesCodeGenerator()
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: Create()
  nameWithType: BrowserCapabilitiesCodeGenerator.Create()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create()
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(System.Boolean,System.String)
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: ProcessBrowserFiles(Boolean,String)
  nameWithType: BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(Boolean,String)
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(Boolean,String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: Uninstall()
  nameWithType: BrowserCapabilitiesCodeGenerator.Uninstall()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall()
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.#ctor*
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: BrowserCapabilitiesCodeGenerator
  nameWithType: BrowserCapabilitiesCodeGenerator.BrowserCapabilitiesCodeGenerator
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create*
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: Create
  nameWithType: BrowserCapabilitiesCodeGenerator.Create
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles*
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: ProcessBrowserFiles
  nameWithType: BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall*
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: Uninstall
  nameWithType: BrowserCapabilitiesCodeGenerator.Uninstall
