### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.ApplicationNameAttribute
  id: ApplicationNameAttribute
  children:
  - System.EnterpriseServices.ApplicationNameAttribute.#ctor(System.String)
  - System.EnterpriseServices.ApplicationNameAttribute.Value
  langs:
  - csharp
  name: ApplicationNameAttribute
  nameWithType: ApplicationNameAttribute
  fullName: System.EnterpriseServices.ApplicationNameAttribute
  type: Class
  summary: "Specifies the name of the COM+ application to be used for the install of the components in the assembly. This class cannot be inherited."
  remarks: ''
  example:
  - "The following example demonstrates the use of this attribute to mark a <xref:System.EnterpriseServices.ServicedComponent> class.  \n  \n [!code-cpp[EnterpriseServices_Basic#1](~/add/codesnippet/CPP/t-system.enterpriseservi_8_1.cpp)]\n [!code-cs[EnterpriseServices_Basic#1](~/add/codesnippet/CSharp/t-system.enterpriseservi_8_1.cs)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Assembly, Inherited=true)]

      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class ApplicationNameAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.EnterpriseServices.ApplicationNameAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.EnterpriseServices.ApplicationNameAttribute
  langs:
  - csharp
  name: ApplicationNameAttribute(String)
  nameWithType: ApplicationNameAttribute.ApplicationNameAttribute(String)
  fullName: System.EnterpriseServices.ApplicationNameAttribute.ApplicationNameAttribute(String)
  type: Constructor
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "Initializes a new instance of the <see cref=&quot;T:System.EnterpriseServices.ApplicationNameAttribute&quot;></see> class, specifying the name of the COM+ application to be used for the install of the components."
  remarks: ''
  example:
  - "The following example illustrates the use of this attribute to mark a <xref:System.EnterpriseServices.ServicedComponent> class.  \n  \n [!code-cpp[EnterpriseServices_Basic#1](~/add/codesnippet/CPP/m-system.enterpriseservi_28_1.cpp)]\n [!code-cs[EnterpriseServices_Basic#1](~/add/codesnippet/CSharp/m-system.enterpriseservi_28_1.cs)]"
  syntax:
    content: public ApplicationNameAttribute (string name);
    parameters:
    - id: name
      type: System.String
      description: "The name of the COM+ application."
  overload: System.EnterpriseServices.ApplicationNameAttribute.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.EnterpriseServices.ApplicationNameAttribute.Value
  id: Value
  parent: System.EnterpriseServices.ApplicationNameAttribute
  langs:
  - csharp
  name: Value
  nameWithType: ApplicationNameAttribute.Value
  fullName: System.EnterpriseServices.ApplicationNameAttribute.Value
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "Gets a value indicating the name of the COM+ application that contains the components in the assembly."
  syntax:
    content: public string Value { get; }
    return:
      type: System.String
      description: "The name of the COM+ application."
  overload: System.EnterpriseServices.ApplicationNameAttribute.Value*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.EnterpriseServices.ApplicationNameAttribute.#ctor(System.String)
  parent: System.EnterpriseServices.ApplicationNameAttribute
  isExternal: false
  name: ApplicationNameAttribute(String)
  nameWithType: ApplicationNameAttribute.ApplicationNameAttribute(String)
  fullName: System.EnterpriseServices.ApplicationNameAttribute.ApplicationNameAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.EnterpriseServices.ApplicationNameAttribute.Value
  parent: System.EnterpriseServices.ApplicationNameAttribute
  isExternal: false
  name: Value
  nameWithType: ApplicationNameAttribute.Value
  fullName: System.EnterpriseServices.ApplicationNameAttribute.Value
- uid: System.EnterpriseServices.ApplicationNameAttribute.#ctor*
  parent: System.EnterpriseServices.ApplicationNameAttribute
  isExternal: false
  name: ApplicationNameAttribute
  nameWithType: ApplicationNameAttribute.ApplicationNameAttribute
- uid: System.EnterpriseServices.ApplicationNameAttribute.Value*
  parent: System.EnterpriseServices.ApplicationNameAttribute
  isExternal: false
  name: Value
  nameWithType: ApplicationNameAttribute.Value
