### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.CertificateElement
  id: CertificateElement
  children:
  - System.ServiceModel.Configuration.CertificateElement.#ctor
  - System.ServiceModel.Configuration.CertificateElement.EncodedValue
  - System.ServiceModel.Configuration.CertificateElement.Properties
  langs:
  - csharp
  name: CertificateElement
  nameWithType: CertificateElement
  fullName: System.ServiceModel.Configuration.CertificateElement
  type: Class
  summary: "Represents a configuration element that specifies an X.509 certificate used for authentication. This class cannot be inherited."
  syntax:
    content: 'public sealed class CertificateElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.CertificateElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.CertificateElement
  langs:
  - csharp
  name: CertificateElement()
  nameWithType: CertificateElement.CertificateElement()
  fullName: System.ServiceModel.Configuration.CertificateElement.CertificateElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.CertificateElement&quot;></see> class."
  syntax:
    content: public CertificateElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.CertificateElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.CertificateElement.EncodedValue
  id: EncodedValue
  parent: System.ServiceModel.Configuration.CertificateElement
  langs:
  - csharp
  name: EncodedValue
  nameWithType: CertificateElement.EncodedValue
  fullName: System.ServiceModel.Configuration.CertificateElement.EncodedValue
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets a value that indicates the value encoded by this certificate."
  syntax:
    content: public string EncodedValue { get; set; }
    return:
      type: System.String
      description: "The encoded value."
  overload: System.ServiceModel.Configuration.CertificateElement.EncodedValue*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.CertificateElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.CertificateElement
  langs:
  - csharp
  name: Properties
  nameWithType: CertificateElement.Properties
  fullName: System.ServiceModel.Configuration.CertificateElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.CertificateElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.CertificateElement.#ctor
  parent: System.ServiceModel.Configuration.CertificateElement
  isExternal: false
  name: CertificateElement()
  nameWithType: CertificateElement.CertificateElement()
  fullName: System.ServiceModel.Configuration.CertificateElement.CertificateElement()
- uid: System.ServiceModel.Configuration.CertificateElement.EncodedValue
  parent: System.ServiceModel.Configuration.CertificateElement
  isExternal: false
  name: EncodedValue
  nameWithType: CertificateElement.EncodedValue
  fullName: System.ServiceModel.Configuration.CertificateElement.EncodedValue
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.CertificateElement.Properties
  parent: System.ServiceModel.Configuration.CertificateElement
  isExternal: false
  name: Properties
  nameWithType: CertificateElement.Properties
  fullName: System.ServiceModel.Configuration.CertificateElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.CertificateElement.#ctor*
  parent: System.ServiceModel.Configuration.CertificateElement
  isExternal: false
  name: CertificateElement
  nameWithType: CertificateElement.CertificateElement
- uid: System.ServiceModel.Configuration.CertificateElement.EncodedValue*
  parent: System.ServiceModel.Configuration.CertificateElement
  isExternal: false
  name: EncodedValue
  nameWithType: CertificateElement.EncodedValue
- uid: System.ServiceModel.Configuration.CertificateElement.Properties*
  parent: System.ServiceModel.Configuration.CertificateElement
  isExternal: false
  name: Properties
  nameWithType: CertificateElement.Properties
