### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  id: StandardBindingReliableSessionElement
  children:
  - System.ServiceModel.Configuration.StandardBindingReliableSessionElement.#ctor
  - System.ServiceModel.Configuration.StandardBindingReliableSessionElement.ApplyConfiguration(System.ServiceModel.ReliableSession)
  - System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InactivityTimeout
  - System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InitializeFrom(System.ServiceModel.ReliableSession)
  - System.ServiceModel.Configuration.StandardBindingReliableSessionElement.Ordered
  - System.ServiceModel.Configuration.StandardBindingReliableSessionElement.Properties
  langs:
  - csharp
  name: StandardBindingReliableSessionElement
  nameWithType: StandardBindingReliableSessionElement
  fullName: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  type: Class
  summary: "Represents the configuration setting for WS-Reliable Messaging defined in a standard binding."
  syntax:
    content: 'public class StandardBindingReliableSessionElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  langs:
  - csharp
  name: StandardBindingReliableSessionElement()
  nameWithType: StandardBindingReliableSessionElement.StandardBindingReliableSessionElement()
  fullName: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.StandardBindingReliableSessionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.StandardBindingReliableSessionElement&quot;></see> class."
  syntax:
    content: public StandardBindingReliableSessionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.ApplyConfiguration(System.ServiceModel.ReliableSession)
  id: ApplyConfiguration(System.ServiceModel.ReliableSession)
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  langs:
  - csharp
  name: ApplyConfiguration(ReliableSession)
  nameWithType: StandardBindingReliableSessionElement.ApplyConfiguration(ReliableSession)
  fullName: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.ApplyConfiguration(ReliableSession)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Applies the content of a specified binding element to this configuration section."
  syntax:
    content: public void ApplyConfiguration (System.ServiceModel.ReliableSession reliableSession);
    parameters:
    - id: reliableSession
      type: System.ServiceModel.ReliableSession
      description: "The configuration element to apply."
  overload: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.ApplyConfiguration*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "\n    reliableSession is ."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InactivityTimeout
  id: InactivityTimeout
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  langs:
  - csharp
  name: InactivityTimeout
  nameWithType: StandardBindingReliableSessionElement.InactivityTimeout
  fullName: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InactivityTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets a &lt;xref:System.TimeSpan&gt; value that specifies the maximum duration the channel allows the other communicating party not to send any messages before faulting the channel."
  remarks: "Activity on a channel is defined as receiving an application or infrastructure message. This property controls the maximum amount of time to keep an inactive session alive. If there is a longer time with no activity, the session is terminated by the infrastructure and the channel faults."
  syntax:
    content: public TimeSpan InactivityTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "A &lt;xref:System.TimeSpan&gt; value that specifies the maximum duration the channel allows the other communicating party not to send any messages before faulting the channel. The default is 00:10:00."
  overload: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InactivityTimeout*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InitializeFrom(System.ServiceModel.ReliableSession)
  id: InitializeFrom(System.ServiceModel.ReliableSession)
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  langs:
  - csharp
  name: InitializeFrom(ReliableSession)
  nameWithType: StandardBindingReliableSessionElement.InitializeFrom(ReliableSession)
  fullName: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InitializeFrom(ReliableSession)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes this configuration element with values from the specified section."
  syntax:
    content: public void InitializeFrom (System.ServiceModel.ReliableSession reliableSession);
    parameters:
    - id: reliableSession
      type: System.ServiceModel.ReliableSession
      description: "The configuration element to be initialized from."
  overload: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InitializeFrom*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "\n    reliableSession is ."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.Ordered
  id: Ordered
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  langs:
  - csharp
  name: Ordered
  nameWithType: StandardBindingReliableSessionElement.Ordered
  fullName: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.Ordered
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets a Boolean value that specifies whether messages are guaranteed to arrive in the order they were sent."
  syntax:
    content: public bool Ordered { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if messages are guaranteed to arrive in the order they were sent; <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref> if messages can arrive out of order. The default is <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>."
  overload: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.Ordered*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  langs:
  - csharp
  name: Properties
  nameWithType: StandardBindingReliableSessionElement.Properties
  fullName: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets a <see cref=&quot;T:System.Configuration.ConfigurationPropertyCollection&quot;></see> instance that contains a collection of <see cref=&quot;T:System.Configuration.ConfigurationProperty&quot;></see> objects that can be attributes or <see cref=&quot;T:System.Configuration.ConfigurationElement&quot;></see> objects of this configuration element."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A <see cref=&quot;T:System.Configuration.ConfigurationPropertyCollection&quot;></see> instance that contains a collection of <see cref=&quot;T:System.Configuration.ConfigurationProperty&quot;></see> objects that can be attributes or <see cref=&quot;T:System.Configuration.ConfigurationElement&quot;></see> objects of this configuration element."
  overload: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.#ctor
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  isExternal: false
  name: StandardBindingReliableSessionElement()
  nameWithType: StandardBindingReliableSessionElement.StandardBindingReliableSessionElement()
  fullName: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.StandardBindingReliableSessionElement()
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.ApplyConfiguration(System.ServiceModel.ReliableSession)
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  isExternal: false
  name: ApplyConfiguration(ReliableSession)
  nameWithType: StandardBindingReliableSessionElement.ApplyConfiguration(ReliableSession)
  fullName: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.ApplyConfiguration(ReliableSession)
- uid: System.ServiceModel.ReliableSession
  parent: System.ServiceModel
  isExternal: false
  name: ReliableSession
  nameWithType: ReliableSession
  fullName: System.ServiceModel.ReliableSession
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InactivityTimeout
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  isExternal: false
  name: InactivityTimeout
  nameWithType: StandardBindingReliableSessionElement.InactivityTimeout
  fullName: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InactivityTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InitializeFrom(System.ServiceModel.ReliableSession)
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  isExternal: false
  name: InitializeFrom(ReliableSession)
  nameWithType: StandardBindingReliableSessionElement.InitializeFrom(ReliableSession)
  fullName: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InitializeFrom(ReliableSession)
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.Ordered
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  isExternal: false
  name: Ordered
  nameWithType: StandardBindingReliableSessionElement.Ordered
  fullName: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.Ordered
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.Properties
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  isExternal: false
  name: Properties
  nameWithType: StandardBindingReliableSessionElement.Properties
  fullName: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.#ctor*
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  isExternal: false
  name: StandardBindingReliableSessionElement
  nameWithType: StandardBindingReliableSessionElement.StandardBindingReliableSessionElement
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.ApplyConfiguration*
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  isExternal: false
  name: ApplyConfiguration
  nameWithType: StandardBindingReliableSessionElement.ApplyConfiguration
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InactivityTimeout*
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  isExternal: false
  name: InactivityTimeout
  nameWithType: StandardBindingReliableSessionElement.InactivityTimeout
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InitializeFrom*
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  isExternal: false
  name: InitializeFrom
  nameWithType: StandardBindingReliableSessionElement.InitializeFrom
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.Ordered*
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  isExternal: false
  name: Ordered
  nameWithType: StandardBindingReliableSessionElement.Ordered
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.Properties*
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  isExternal: false
  name: Properties
  nameWithType: StandardBindingReliableSessionElement.Properties
