### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.Ipv6Element
  id: Ipv6Element
  children:
  - System.Net.Configuration.Ipv6Element.#ctor
  - System.Net.Configuration.Ipv6Element.Enabled
  - System.Net.Configuration.Ipv6Element.Properties
  langs:
  - csharp
  name: Ipv6Element
  nameWithType: Ipv6Element
  fullName: System.Net.Configuration.Ipv6Element
  type: Class
  summary: "Determines whether Internet Protocol version 6 is enabled on the local computer. This class cannot be inherited."
  remarks: "This class corresponds to the `enabled` attribute of the [\\<ipv6> Element (Network Settings)](../Topic/%3Cipv6%3E%20Element%20\\(Network%20Settings\\).md) configuration element.  \n  \n This class is used to specify whether the IPv6 protocol is supported on the local computer. IPv6 is disabled by default.  \n  \n This class provides programmatic access to information that can be stored in configuration files."
  syntax:
    content: 'public sealed class Ipv6Element : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.Ipv6Element.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.Ipv6Element
  langs:
  - csharp
  name: Ipv6Element()
  nameWithType: Ipv6Element.Ipv6Element()
  fullName: System.Net.Configuration.Ipv6Element.Ipv6Element()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Net.Configuration.Ipv6Element&quot;></see> class."
  remarks: "This constructor adds the <xref:System.Net.Configuration.Ipv6Element.Enabled%2A> property to the <xref:System.Configuration.ConfigurationElement.Properties%2A> collection."
  syntax:
    content: public Ipv6Element ();
    parameters: []
  overload: System.Net.Configuration.Ipv6Element.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.Ipv6Element.Enabled
  id: Enabled
  parent: System.Net.Configuration.Ipv6Element
  langs:
  - csharp
  name: Enabled
  nameWithType: Ipv6Element.Enabled
  fullName: System.Net.Configuration.Ipv6Element.Enabled
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Gets or sets a Boolean value that indicates whether Internet Protocol version 6 is enabled on the local computer."
  syntax:
    content: public bool Enabled { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if IPv6 is enabled; otherwise, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>."
  overload: System.Net.Configuration.Ipv6Element.Enabled*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.Ipv6Element.Properties
  id: Properties
  parent: System.Net.Configuration.Ipv6Element
  langs:
  - csharp
  name: Properties
  nameWithType: Ipv6Element.Properties
  fullName: System.Net.Configuration.Ipv6Element.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Net.Configuration.Ipv6Element.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.Ipv6Element.#ctor
  parent: System.Net.Configuration.Ipv6Element
  isExternal: false
  name: Ipv6Element()
  nameWithType: Ipv6Element.Ipv6Element()
  fullName: System.Net.Configuration.Ipv6Element.Ipv6Element()
- uid: System.Net.Configuration.Ipv6Element.Enabled
  parent: System.Net.Configuration.Ipv6Element
  isExternal: false
  name: Enabled
  nameWithType: Ipv6Element.Enabled
  fullName: System.Net.Configuration.Ipv6Element.Enabled
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Net.Configuration.Ipv6Element.Properties
  parent: System.Net.Configuration.Ipv6Element
  isExternal: false
  name: Properties
  nameWithType: Ipv6Element.Properties
  fullName: System.Net.Configuration.Ipv6Element.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.Ipv6Element.#ctor*
  parent: System.Net.Configuration.Ipv6Element
  isExternal: false
  name: Ipv6Element
  nameWithType: Ipv6Element.Ipv6Element
- uid: System.Net.Configuration.Ipv6Element.Enabled*
  parent: System.Net.Configuration.Ipv6Element
  isExternal: false
  name: Enabled
  nameWithType: Ipv6Element.Enabled
- uid: System.Net.Configuration.Ipv6Element.Properties*
  parent: System.Net.Configuration.Ipv6Element
  isExternal: false
  name: Properties
  nameWithType: Ipv6Element.Properties
