### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.MembershipSection
  id: MembershipSection
  children:
  - System.Web.Configuration.MembershipSection.#ctor
  - System.Web.Configuration.MembershipSection.DefaultProvider
  - System.Web.Configuration.MembershipSection.HashAlgorithmType
  - System.Web.Configuration.MembershipSection.Properties
  - System.Web.Configuration.MembershipSection.Providers
  - System.Web.Configuration.MembershipSection.UserIsOnlineTimeWindow
  langs:
  - csharp
  name: MembershipSection
  nameWithType: MembershipSection
  fullName: System.Web.Configuration.MembershipSection
  type: Class
  summary: "Defines configuration settings to support the infrastructure for configuring and managing membership details. This class cannot be inherited."
  remarks: "The MembershipSection class provides a way to programmatically access and modify the `membership` section in a configuration file."
  example:
  - "This example demonstrates how to specify values declaratively for several attributes of the `membership` section, which can also be accessed as members of the MembershipSection class.  \n  \n The following configuration file example shows how to specify values declaratively for the `membership` section.  \n  \n```  \n<system.web>  \n  <membership   \n    defaultProvider=\"AspNetSqlMembershipProvider\"  \n    userIsOnlineTimeWindow=\"15\">  \n    <providers>  \n      <add   \n        name=\" AspNetSqlMembershipProvider\"  \n        type=\"System.Web.Security.SqlMembershipProvider, System.Web,   \n          Version=2.0.3600.0, Culture=neutral,   \n          PublicKeyToken=b03f5f7f11d50a3a\"  \n        connectionStringName=\"LocalSqlServer\"  \n        passwordAttemptThreshold=\"5\"  \n        passwordAttemptWindow=\"10\"  \n        enablePasswordRetrieval=\"false\"  \n        enablePasswordReset=\"true\"  \n        requiresQuestionAndAnswer=\"true\"  \n        applicationName=\"/\"  \n        requiresUniqueEmail=\"false\"  \n        passwordFormat=\"Hashed\"  \n        description=\"Stores and retrieves membership data from   \n          the local Microsoft SQL Server database.\"  \n      />  \n    </providers>  \n  </membership>  \n</system.web>  \n```  \n  \n The following code example demonstrates how to use the MembershipSection class.  \n  \n [!code-cs[System.Web.Configuration.MembershipSection#1](~/add/codesnippet/CSharp/t-system.web.configurati_44_1.cs)]\n [!code-vb[System.Web.Configuration.MembershipSection#1](~/add/codesnippet/VisualBasic/t-system.web.configurati_44_1.vb)]"
  syntax:
    content: 'public sealed class MembershipSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.MembershipSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.MembershipSection
  langs:
  - csharp
  name: MembershipSection()
  nameWithType: MembershipSection.MembershipSection()
  fullName: System.Web.Configuration.MembershipSection.MembershipSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Web.Configuration.MembershipSection&quot;></see> class."
  remarks: "The MembershipSection constructor is not intended to be used directly from your code. It is called by the ASP.NET configuration system. You obtain an instance of the <xref:System.Web.Configuration.MembershipSection> class by using the <xref:System.Configuration.Configuration.GetSection%2A> method."
  syntax:
    content: public MembershipSection ();
    parameters: []
  overload: System.Web.Configuration.MembershipSection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.MembershipSection.DefaultProvider
  id: DefaultProvider
  parent: System.Web.Configuration.MembershipSection
  langs:
  - csharp
  name: DefaultProvider
  nameWithType: MembershipSection.DefaultProvider
  fullName: System.Web.Configuration.MembershipSection.DefaultProvider
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets or sets the name of the default provider that is used to manage roles."
  remarks: "The DefaultProvider must match a named value in the `providers` subsection of the `membership` section of the configuration file. An empty string (`&quot;&quot;`) is not a valid value for the DefaultProvider property."
  example:
  - "The following code example demonstrates how to use the DefaultProvider property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.MembershipSection> class.  \n  \n [!code-cs[System.Web.Configuration.MembershipSection#2](~/add/codesnippet/CSharp/p-system.web.configurati_239_1.cs)]\n [!code-vb[System.Web.Configuration.MembershipSection#2](~/add/codesnippet/VisualBasic/p-system.web.configurati_239_1.vb)]"
  syntax:
    content: public string DefaultProvider { get; set; }
    return:
      type: System.String
      description: "The name of a provider in &lt;xref:System.Web.Configuration.MembershipSection.Providers%2A&gt;. The default is <xref uid=&quot;langword_csharp_AspNetSqlRoleProvider&quot; name=&quot;AspNetSqlRoleProvider&quot; href=&quot;&quot;></xref>."
  overload: System.Web.Configuration.MembershipSection.DefaultProvider*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.MembershipSection.HashAlgorithmType
  id: HashAlgorithmType
  parent: System.Web.Configuration.MembershipSection
  langs:
  - csharp
  name: HashAlgorithmType
  nameWithType: MembershipSection.HashAlgorithmType
  fullName: System.Web.Configuration.MembershipSection.HashAlgorithmType
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets or sets the type of encryption that is used for sensitive membership information."
  remarks: "At run time, the membership system binds to the appropriate hash algorithm type, and then uses this type when encrypting membership information. If the HashAlgorithmType property is not set, the membership system defaults to the <xref:System.Web.Configuration.MachineKeySection.Validation%2A> property within the <xref:System.Web.Configuration.MachineKeySection> class."
  example:
  - "The following code example demonstrates how to use the HashAlgorithmType property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.MembershipSection> class.  \n  \n [!code-cs[System.Web.Configuration.MembershipSection#3](~/add/codesnippet/CSharp/p-system.web.configurati_135_1.cs)]\n [!code-vb[System.Web.Configuration.MembershipSection#3](~/add/codesnippet/VisualBasic/p-system.web.configurati_135_1.vb)]"
  syntax:
    content: public string HashAlgorithmType { get; set; }
    return:
      type: System.String
      description: "The type of encryption used to encrypt sensitive membership information."
  overload: System.Web.Configuration.MembershipSection.HashAlgorithmType*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.MembershipSection.Properties
  id: Properties
  parent: System.Web.Configuration.MembershipSection
  langs:
  - csharp
  name: Properties
  nameWithType: MembershipSection.Properties
  fullName: System.Web.Configuration.MembershipSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Web.Configuration.MembershipSection.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.MembershipSection.Providers
  id: Providers
  parent: System.Web.Configuration.MembershipSection
  langs:
  - csharp
  name: Providers
  nameWithType: MembershipSection.Providers
  fullName: System.Web.Configuration.MembershipSection.Providers
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets a <see cref=&quot;T:System.Configuration.ProviderSettingsCollection&quot;></see> object of <see cref=&quot;T:System.Configuration.ProviderSettings&quot;></see> objects."
  remarks: "Membership providers are components that provide access to the membership for a site. You can specify membership providers in the `providers` subsection of the `membership` section of the configuration file.       The <xref:System.Web.Configuration.MembershipSection.DefaultProvider%2A> property contains the name of the provider that is used by default."
  example:
  - "The following code example demonstrates how to use the Providers property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.MembershipSection> class.  \n  \n [!code-cs[System.Web.Configuration.MembershipSection#5](~/add/codesnippet/CSharp/p-system.web.configurati_90_1.cs)]\n [!code-vb[System.Web.Configuration.MembershipSection#5](~/add/codesnippet/VisualBasic/p-system.web.configurati_90_1.vb)]"
  syntax:
    content: public System.Configuration.ProviderSettingsCollection Providers { get; }
    return:
      type: System.Configuration.ProviderSettingsCollection
      description: "A <see cref=&quot;T:System.Configuration.ProviderSettingsCollection&quot;></see> that contains the provider&quot;s settings, defined within the <xref uid=&quot;langword_csharp_providers&quot; name=&quot;providers&quot; href=&quot;&quot;></xref> subsection of the <xref uid=&quot;langword_csharp_membership&quot; name=&quot;membership&quot; href=&quot;&quot;></xref> section of the configuration file."
  overload: System.Web.Configuration.MembershipSection.Providers*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.MembershipSection.UserIsOnlineTimeWindow
  id: UserIsOnlineTimeWindow
  parent: System.Web.Configuration.MembershipSection
  langs:
  - csharp
  name: UserIsOnlineTimeWindow
  nameWithType: MembershipSection.UserIsOnlineTimeWindow
  fullName: System.Web.Configuration.MembershipSection.UserIsOnlineTimeWindow
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets or sets the length of time, in minutes, before a user is no longer considered to be online."
  remarks: "The value for the UserIsOnlineTimeWindow property is calculated by comparing the current time minus the UserIsOnlineTimeWindow property with the <xref:System.Web.Security.MembershipUser.LastActivityDate%2A> value for the user."
  example:
  - "The following code example demonstrates how to use the UserIsOnlineTimeWindow property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.MembershipSection> class.  \n  \n [!code-cs[System.Web.Configuration.MembershipSection#4](~/add/codesnippet/CSharp/p-system.web.configurati_39_1.cs)]\n [!code-vb[System.Web.Configuration.MembershipSection#4](~/add/codesnippet/VisualBasic/p-system.web.configurati_39_1.vb)]"
  syntax:
    content: public TimeSpan UserIsOnlineTimeWindow { get; set; }
    return:
      type: System.TimeSpan
      description: "A length of time in minutes."
  overload: System.Web.Configuration.MembershipSection.UserIsOnlineTimeWindow*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.MembershipSection.#ctor
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: MembershipSection()
  nameWithType: MembershipSection.MembershipSection()
  fullName: System.Web.Configuration.MembershipSection.MembershipSection()
- uid: System.Web.Configuration.MembershipSection.DefaultProvider
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: DefaultProvider
  nameWithType: MembershipSection.DefaultProvider
  fullName: System.Web.Configuration.MembershipSection.DefaultProvider
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.MembershipSection.HashAlgorithmType
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: HashAlgorithmType
  nameWithType: MembershipSection.HashAlgorithmType
  fullName: System.Web.Configuration.MembershipSection.HashAlgorithmType
- uid: System.Web.Configuration.MembershipSection.Properties
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: Properties
  nameWithType: MembershipSection.Properties
  fullName: System.Web.Configuration.MembershipSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.MembershipSection.Providers
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: Providers
  nameWithType: MembershipSection.Providers
  fullName: System.Web.Configuration.MembershipSection.Providers
- uid: System.Configuration.ProviderSettingsCollection
  parent: System.Configuration
  isExternal: false
  name: ProviderSettingsCollection
  nameWithType: ProviderSettingsCollection
  fullName: System.Configuration.ProviderSettingsCollection
- uid: System.Web.Configuration.MembershipSection.UserIsOnlineTimeWindow
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: UserIsOnlineTimeWindow
  nameWithType: MembershipSection.UserIsOnlineTimeWindow
  fullName: System.Web.Configuration.MembershipSection.UserIsOnlineTimeWindow
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Web.Configuration.MembershipSection.#ctor*
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: MembershipSection
  nameWithType: MembershipSection.MembershipSection
- uid: System.Web.Configuration.MembershipSection.DefaultProvider*
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: DefaultProvider
  nameWithType: MembershipSection.DefaultProvider
- uid: System.Web.Configuration.MembershipSection.HashAlgorithmType*
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: HashAlgorithmType
  nameWithType: MembershipSection.HashAlgorithmType
- uid: System.Web.Configuration.MembershipSection.Properties*
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: Properties
  nameWithType: MembershipSection.Properties
- uid: System.Web.Configuration.MembershipSection.Providers*
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: Providers
  nameWithType: MembershipSection.Providers
- uid: System.Web.Configuration.MembershipSection.UserIsOnlineTimeWindow*
  parent: System.Web.Configuration.MembershipSection
  isExternal: false
  name: UserIsOnlineTimeWindow
  nameWithType: MembershipSection.UserIsOnlineTimeWindow
