### YamlMime:ManagedReference
items:
- uid: System.Windows.Automation.ClientSettings
  id: ClientSettings
  children:
  - System.Windows.Automation.ClientSettings.RegisterClientSideProviderAssembly(System.Reflection.AssemblyName)
  - System.Windows.Automation.ClientSettings.RegisterClientSideProviders(System.Windows.Automation.ClientSideProviderDescription[])
  langs:
  - csharp
  name: ClientSettings
  nameWithType: ClientSettings
  fullName: System.Windows.Automation.ClientSettings
  type: Class
  summary: "Contains methods that make client-side providers available to the client."
  syntax:
    content: public static class ClientSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Windows.Automation.ClientSettings.RegisterClientSideProviderAssembly(System.Reflection.AssemblyName)
  id: RegisterClientSideProviderAssembly(System.Reflection.AssemblyName)
  parent: System.Windows.Automation.ClientSettings
  langs:
  - csharp
  name: RegisterClientSideProviderAssembly(AssemblyName)
  nameWithType: ClientSettings.RegisterClientSideProviderAssembly(AssemblyName)
  fullName: System.Windows.Automation.ClientSettings.RegisterClientSideProviderAssembly(AssemblyName)
  type: Method
  assemblies:
  - UIAutomationClient
  namespace: System.Windows.Automation
  summary: "Registers an assembly that contains client-side providers."
  remarks: "This method is called on startup by UI Automation clients that use client-side UI Automation providers loaded from an assembly. Applications that use providers implemented in their own assembly should call <xref:System.Windows.Automation.ClientSettings.RegisterClientSideProviders%2A>."
  example:
  - For example code, see [Register a Client-Side Provider Assembly](../Topic/Register%20a%20Client-Side%20Provider%20Assembly.md).
  syntax:
    content: public static void RegisterClientSideProviderAssembly (System.Reflection.AssemblyName assemblyName);
    parameters:
    - id: assemblyName
      type: System.Reflection.AssemblyName
      description: "Name of the assembly."
  overload: System.Windows.Automation.ClientSettings.RegisterClientSideProviderAssembly*
  exceptions:
  - type: System.Windows.Automation.ProxyAssemblyNotLoadedException
    commentId: T:System.Windows.Automation.ProxyAssemblyNotLoadedException
    description: "The assembly could not be loaded."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Windows.Automation.ClientSettings.RegisterClientSideProviders(System.Windows.Automation.ClientSideProviderDescription[])
  id: RegisterClientSideProviders(System.Windows.Automation.ClientSideProviderDescription[])
  parent: System.Windows.Automation.ClientSettings
  langs:
  - csharp
  name: RegisterClientSideProviders(ClientSideProviderDescription[])
  nameWithType: ClientSettings.RegisterClientSideProviders(ClientSideProviderDescription[])
  fullName: System.Windows.Automation.ClientSettings.RegisterClientSideProviders(ClientSideProviderDescription[])
  type: Method
  assemblies:
  - UIAutomationClient
  namespace: System.Windows.Automation
  summary: "Registers client-side providers."
  remarks: "This method is called on startup by clients that implement their own client-side providers. Clients that use providers from a separate assembly  must call <xref:System.Windows.Automation.ClientSettings.RegisterClientSideProviderAssembly%2A>."
  example:
  - For example code, see [Implement UI Automation Providers in a Client Application](../Topic/Implement%20UI%20Automation%20Providers%20in%20a%20Client%20Application.md).
  syntax:
    content: public static void RegisterClientSideProviders (System.Windows.Automation.ClientSideProviderDescription[] clientSideProviderDescription);
    parameters:
    - id: clientSideProviderDescription
      type: System.Windows.Automation.ClientSideProviderDescription[]
      description: "An array of provider descriptions."
  overload: System.Windows.Automation.ClientSettings.RegisterClientSideProviders*
  exceptions:
  - type: System.Windows.Automation.ProxyAssemblyNotLoadedException
    commentId: T:System.Windows.Automation.ProxyAssemblyNotLoadedException
    description: "The assembly could not be loaded."
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Windows.Automation.ClientSettings.RegisterClientSideProviderAssembly(System.Reflection.AssemblyName)
  parent: System.Windows.Automation.ClientSettings
  isExternal: false
  name: RegisterClientSideProviderAssembly(AssemblyName)
  nameWithType: ClientSettings.RegisterClientSideProviderAssembly(AssemblyName)
  fullName: System.Windows.Automation.ClientSettings.RegisterClientSideProviderAssembly(AssemblyName)
- uid: System.Reflection.AssemblyName
  parent: System.Reflection
  isExternal: true
  name: AssemblyName
  nameWithType: AssemblyName
  fullName: System.Reflection.AssemblyName
- uid: System.Windows.Automation.ClientSettings.RegisterClientSideProviders(System.Windows.Automation.ClientSideProviderDescription[])
  parent: System.Windows.Automation.ClientSettings
  isExternal: false
  name: RegisterClientSideProviders(ClientSideProviderDescription[])
  nameWithType: ClientSettings.RegisterClientSideProviders(ClientSideProviderDescription[])
  fullName: System.Windows.Automation.ClientSettings.RegisterClientSideProviders(ClientSideProviderDescription[])
- uid: System.Windows.Automation.ClientSideProviderDescription[]
  parent: System.Windows.Automation
  isExternal: false
  name: ClientSideProviderDescription
  nameWithType: ClientSideProviderDescription
  fullName: System.Windows.Automation.ClientSideProviderDescription[]
  spec.csharp:
  - uid: System.Windows.Automation.ClientSideProviderDescription
    name: ClientSideProviderDescription
    nameWithType: ClientSideProviderDescription
    fullName: ClientSideProviderDescription[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Windows.Automation.ClientSettings.RegisterClientSideProviderAssembly*
  parent: System.Windows.Automation.ClientSettings
  isExternal: false
  name: RegisterClientSideProviderAssembly
  nameWithType: ClientSettings.RegisterClientSideProviderAssembly
- uid: System.Windows.Automation.ClientSettings.RegisterClientSideProviders*
  parent: System.Windows.Automation.ClientSettings
  isExternal: false
  name: RegisterClientSideProviders
  nameWithType: ClientSettings.RegisterClientSideProviders
