### YamlMime:ManagedReference
items:
- uid: System.Management.Instrumentation.ManagementConfigurationType
  id: ManagementConfigurationType
  children:
  - System.Management.Instrumentation.ManagementConfigurationType.Apply
  - System.Management.Instrumentation.ManagementConfigurationType.OnCommit
  langs:
  - csharp
  name: ManagementConfigurationType
  nameWithType: ManagementConfigurationType
  fullName: System.Management.Instrumentation.ManagementConfigurationType
  type: Enum
  summary: "Represents the possible commit behaviors of a read/write property. It is used as the value of a parameter of the <see cref=&quot;T:System.Management.Instrumentation.ManagementConfigurationAttribute&quot;></see> attribute.       Note: the WMI .NET libraries are now considered in final state, and no further development, enhancements, or updates will be available for non-security related issues affecting these libraries. The [MI APIs](https://msdn.microsoft.com/en-us/library/jj152383%28v=vs.80%29.aspx) should be used for all new development."
  remarks: "This attribute is used as a parameter value for the <xref:System.Management.Instrumentation.ManagementConfigurationAttribute> attribute only if the <xref:System.Management.Instrumentation.ManagementCommitAttribute> attribute is used to identify a method to run to commit values. Otherwise, read/write property values are applied automatically."
  syntax:
    content: public enum ManagementConfigurationType
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Management.Instrumentation.ManagementConfigurationType.Apply
  id: Apply
  parent: System.Management.Instrumentation.ManagementConfigurationType
  langs:
  - csharp
  name: Apply
  nameWithType: ManagementConfigurationType.Apply
  fullName: System.Management.Instrumentation.ManagementConfigurationType.Apply
  type: Field
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "Set values take effect only when Commit is called."
  syntax:
    content: Apply
    return:
      type: System.Management.Instrumentation.ManagementConfigurationType
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Management.Instrumentation.ManagementConfigurationType.OnCommit
  id: OnCommit
  parent: System.Management.Instrumentation.ManagementConfigurationType
  langs:
  - csharp
  name: OnCommit
  nameWithType: ManagementConfigurationType.OnCommit
  fullName: System.Management.Instrumentation.ManagementConfigurationType.OnCommit
  type: Field
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "Set values are applied immediately."
  syntax:
    content: OnCommit
    return:
      type: System.Management.Instrumentation.ManagementConfigurationType
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Management.Instrumentation.ManagementConfigurationType.Apply
  parent: System.Management.Instrumentation.ManagementConfigurationType
  isExternal: false
  name: Apply
  nameWithType: ManagementConfigurationType.Apply
  fullName: System.Management.Instrumentation.ManagementConfigurationType.Apply
- uid: System.Management.Instrumentation.ManagementConfigurationType
  parent: System.Management.Instrumentation
  isExternal: false
  name: ManagementConfigurationType
  nameWithType: ManagementConfigurationType
  fullName: System.Management.Instrumentation.ManagementConfigurationType
- uid: System.Management.Instrumentation.ManagementConfigurationType.OnCommit
  parent: System.Management.Instrumentation.ManagementConfigurationType
  isExternal: false
  name: OnCommit
  nameWithType: ManagementConfigurationType.OnCommit
  fullName: System.Management.Instrumentation.ManagementConfigurationType.OnCommit
