### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup
  id: ScriptingWebServicesSectionGroup
  children:
  - System.Web.Configuration.ScriptingWebServicesSectionGroup.#ctor
  - System.Web.Configuration.ScriptingWebServicesSectionGroup.AuthenticationService
  - System.Web.Configuration.ScriptingWebServicesSectionGroup.JsonSerialization
  - System.Web.Configuration.ScriptingWebServicesSectionGroup.ProfileService
  - System.Web.Configuration.ScriptingWebServicesSectionGroup.RoleService
  langs:
  - csharp
  name: ScriptingWebServicesSectionGroup
  nameWithType: ScriptingWebServicesSectionGroup
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup
  type: Class
  summary: "Represents a group of related sections in a configuration file."
  remarks: "Use the ScriptingWebServicesSectionGroup class to programmatically set and retrieve the values of the `webServices` section of the configuration file."
  syntax:
    content: 'public sealed class ScriptingWebServicesSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  langs:
  - csharp
  name: ScriptingWebServicesSectionGroup()
  nameWithType: ScriptingWebServicesSectionGroup.ScriptingWebServicesSectionGroup()
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.ScriptingWebServicesSectionGroup()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Web.Configuration.ScriptingWebServicesSectionGroup&quot;></see> class."
  syntax:
    content: public ScriptingWebServicesSectionGroup ();
    parameters: []
  overload: System.Web.Configuration.ScriptingWebServicesSectionGroup.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.AuthenticationService
  id: AuthenticationService
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  langs:
  - csharp
  name: AuthenticationService
  nameWithType: ScriptingWebServicesSectionGroup.AuthenticationService
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.AuthenticationService
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Gets the <xref uid=&quot;langword_csharp_authenticationService&quot; name=&quot;authenticationService&quot; href=&quot;&quot;></xref> section that is contained in the configuration file."
  remarks: "The <xref:System.Web.Configuration.ScriptingAuthenticationServiceSection> object refers to the `authenticationService` section of the configuration file."
  syntax:
    content: public System.Web.Configuration.ScriptingAuthenticationServiceSection AuthenticationService { get; }
    return:
      type: System.Web.Configuration.ScriptingAuthenticationServiceSection
      description: "A <see cref=&quot;T:System.Web.Configuration.ScriptingAuthenticationServiceSection&quot;></see> object."
  overload: System.Web.Configuration.ScriptingWebServicesSectionGroup.AuthenticationService*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.JsonSerialization
  id: JsonSerialization
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  langs:
  - csharp
  name: JsonSerialization
  nameWithType: ScriptingWebServicesSectionGroup.JsonSerialization
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.JsonSerialization
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Gets the <xref uid=&quot;langword_csharp_jsonSerialization&quot; name=&quot;jsonSerialization&quot; href=&quot;&quot;></xref> section that is contained in the configuration file."
  remarks: "The <xref:System.Web.Configuration.ScriptingJsonSerializationSection> object refers to the `jsonSerialization` section of the configuration file."
  syntax:
    content: public System.Web.Configuration.ScriptingJsonSerializationSection JsonSerialization { get; }
    return:
      type: System.Web.Configuration.ScriptingJsonSerializationSection
      description: "A <see cref=&quot;T:System.Web.Configuration.ScriptingJsonSerializationSection&quot;></see> object."
  overload: System.Web.Configuration.ScriptingWebServicesSectionGroup.JsonSerialization*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.ProfileService
  id: ProfileService
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  langs:
  - csharp
  name: ProfileService
  nameWithType: ScriptingWebServicesSectionGroup.ProfileService
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.ProfileService
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Gets the <xref uid=&quot;langword_csharp_profileService&quot; name=&quot;profileService&quot; href=&quot;&quot;></xref> section that is contained in the configuration file."
  remarks: "The <xref:System.Web.Configuration.ScriptingProfileServiceSection> object refers to the `profileService` section of the configuration file."
  syntax:
    content: public System.Web.Configuration.ScriptingProfileServiceSection ProfileService { get; }
    return:
      type: System.Web.Configuration.ScriptingProfileServiceSection
      description: "A <see cref=&quot;T:System.Web.Configuration.ScriptingProfileServiceSection&quot;></see> object."
  overload: System.Web.Configuration.ScriptingWebServicesSectionGroup.ProfileService*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.RoleService
  id: RoleService
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  langs:
  - csharp
  name: RoleService
  nameWithType: ScriptingWebServicesSectionGroup.RoleService
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.RoleService
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Gets the <xref uid=&quot;langword_csharp_roleService&quot; name=&quot;roleService&quot; href=&quot;&quot;></xref> section that is contained in the configuration file."
  remarks: "The <xref:System.Web.Configuration.ScriptingRoleServiceSection> object refers to the `roleService` section of the configuration file."
  syntax:
    content: public System.Web.Configuration.ScriptingRoleServiceSection RoleService { get; }
    return:
      type: System.Web.Configuration.ScriptingRoleServiceSection
      description: "A <see cref=&quot;T:System.Web.Configuration.ScriptingRoleServiceSection&quot;></see> object."
  overload: System.Web.Configuration.ScriptingWebServicesSectionGroup.RoleService*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: System.Configuration.ConfigurationSectionGroup
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.#ctor
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: ScriptingWebServicesSectionGroup()
  nameWithType: ScriptingWebServicesSectionGroup.ScriptingWebServicesSectionGroup()
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.ScriptingWebServicesSectionGroup()
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.AuthenticationService
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: AuthenticationService
  nameWithType: ScriptingWebServicesSectionGroup.AuthenticationService
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.AuthenticationService
- uid: System.Web.Configuration.ScriptingAuthenticationServiceSection
  parent: System.Web.Configuration
  isExternal: false
  name: ScriptingAuthenticationServiceSection
  nameWithType: ScriptingAuthenticationServiceSection
  fullName: System.Web.Configuration.ScriptingAuthenticationServiceSection
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.JsonSerialization
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: JsonSerialization
  nameWithType: ScriptingWebServicesSectionGroup.JsonSerialization
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.JsonSerialization
- uid: System.Web.Configuration.ScriptingJsonSerializationSection
  parent: System.Web.Configuration
  isExternal: false
  name: ScriptingJsonSerializationSection
  nameWithType: ScriptingJsonSerializationSection
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.ProfileService
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: ProfileService
  nameWithType: ScriptingWebServicesSectionGroup.ProfileService
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.ProfileService
- uid: System.Web.Configuration.ScriptingProfileServiceSection
  parent: System.Web.Configuration
  isExternal: false
  name: ScriptingProfileServiceSection
  nameWithType: ScriptingProfileServiceSection
  fullName: System.Web.Configuration.ScriptingProfileServiceSection
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.RoleService
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: RoleService
  nameWithType: ScriptingWebServicesSectionGroup.RoleService
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup.RoleService
- uid: System.Web.Configuration.ScriptingRoleServiceSection
  parent: System.Web.Configuration
  isExternal: false
  name: ScriptingRoleServiceSection
  nameWithType: ScriptingRoleServiceSection
  fullName: System.Web.Configuration.ScriptingRoleServiceSection
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.#ctor*
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: ScriptingWebServicesSectionGroup
  nameWithType: ScriptingWebServicesSectionGroup.ScriptingWebServicesSectionGroup
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.AuthenticationService*
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: AuthenticationService
  nameWithType: ScriptingWebServicesSectionGroup.AuthenticationService
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.JsonSerialization*
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: JsonSerialization
  nameWithType: ScriptingWebServicesSectionGroup.JsonSerialization
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.ProfileService*
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: ProfileService
  nameWithType: ScriptingWebServicesSectionGroup.ProfileService
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup.RoleService*
  parent: System.Web.Configuration.ScriptingWebServicesSectionGroup
  isExternal: false
  name: RoleService
  nameWithType: ScriptingWebServicesSectionGroup.RoleService
