### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  id: StateElement
  children:
  - System.ServiceModel.Activities.Tracking.Configuration.StateElement.#ctor
  - System.ServiceModel.Activities.Tracking.Configuration.StateElement.ElementKey
  - System.ServiceModel.Activities.Tracking.Configuration.StateElement.Name
  - System.ServiceModel.Activities.Tracking.Configuration.StateElement.Properties
  langs:
  - csharp
  name: StateElement
  nameWithType: StateElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  type: Class
  summary: "A configuration element that specifies workflow instance state or activity instance state the user subscribes tracking information for."
  remarks: "This element is placed within a <xref:System.ServiceModel.Activities.Tracking.Configuration.StateElementCollection> within a <xref:System.ServiceModel.Activities.Tracking.Configuration.ActivityStateQueryElement> to specify the activity states the query should filter on."
  syntax:
    content: 'public class StateElement : System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement.GetStringPairKey(System.String,System.String)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  langs:
  - csharp
  name: StateElement()
  nameWithType: StateElement.StateElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateElement.StateElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Activities.Tracking.Configuration.StateElement&quot;></see> class."
  syntax:
    content: public StateElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Tracking.Configuration.StateElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.ElementKey
  id: ElementKey
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  langs:
  - csharp
  name: ElementKey
  nameWithType: StateElement.ElementKey
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateElement.ElementKey
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Gets a key that uniquely identifies the element query."
  syntax:
    content: public override object ElementKey { get; }
    return:
      type: System.Object
      description: "The element key."
  overload: System.ServiceModel.Activities.Tracking.Configuration.StateElement.ElementKey*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Name
  id: Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  langs:
  - csharp
  name: Name
  nameWithType: StateElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Name
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Gets or sets the state name to filter on."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "The state name to filter on. The default value is “*” (all)."
  overload: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Name*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  langs:
  - csharp
  name: Properties
  nameWithType: StateElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Gets a collection of <see cref=&quot;T:System.Configuration.ConfigurationProperty&quot;></see> properties."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A collection of configuration properties."
  overload: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  isExternal: false
  name: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.#ctor
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  isExternal: false
  name: StateElement()
  nameWithType: StateElement.StateElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateElement.StateElement()
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.ElementKey
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  isExternal: false
  name: ElementKey
  nameWithType: StateElement.ElementKey
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateElement.ElementKey
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  isExternal: false
  name: Name
  nameWithType: StateElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Name
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  isExternal: false
  name: Properties
  nameWithType: StateElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.#ctor*
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  isExternal: false
  name: StateElement
  nameWithType: StateElement.StateElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.ElementKey*
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  isExternal: false
  name: ElementKey
  nameWithType: StateElement.ElementKey
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Name*
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  isExternal: false
  name: Name
  nameWithType: StateElement.Name
- uid: System.ServiceModel.Activities.Tracking.Configuration.StateElement.Properties*
  parent: System.ServiceModel.Activities.Tracking.Configuration.StateElement
  isExternal: false
  name: Properties
  nameWithType: StateElement.Properties
