### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  id: WsdlHelpGeneratorElement
  children:
  - System.Web.Services.Configuration.WsdlHelpGeneratorElement.#ctor
  - System.Web.Services.Configuration.WsdlHelpGeneratorElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Web.Services.Configuration.WsdlHelpGeneratorElement.Href
  - System.Web.Services.Configuration.WsdlHelpGeneratorElement.Properties
  - System.Web.Services.Configuration.WsdlHelpGeneratorElement.Reset(System.Configuration.ConfigurationElement)
  langs:
  - csharp
  name: WsdlHelpGeneratorElement
  nameWithType: WsdlHelpGeneratorElement
  fullName: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  type: Class
  summary: "Represents <xref uid=&quot;langword_csharp_WsdlHelpGenerator&quot; name=&quot;WsdlHelpGenerator&quot; href=&quot;&quot;></xref> element in the configuration file that specifies the XML Web service Help page (an .aspx file) that is displayed to a browser when the browser navigates directly to an ASMX XML Web services page."
  syntax:
    content: 'public sealed class WsdlHelpGeneratorElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.#ctor
  id: '#ctor'
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  langs:
  - csharp
  name: WsdlHelpGeneratorElement()
  nameWithType: WsdlHelpGeneratorElement.WsdlHelpGeneratorElement()
  fullName: System.Web.Services.Configuration.WsdlHelpGeneratorElement.WsdlHelpGeneratorElement()
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Web.Services.Configuration.WsdlHelpGeneratorElement&quot;></see> class."
  syntax:
    content: public WsdlHelpGeneratorElement ();
    parameters: []
  overload: System.Web.Services.Configuration.WsdlHelpGeneratorElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  id: DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  langs:
  - csharp
  name: DeserializeElement(XmlReader,Boolean)
  nameWithType: WsdlHelpGeneratorElement.DeserializeElement(XmlReader,Boolean)
  fullName: System.Web.Services.Configuration.WsdlHelpGeneratorElement.DeserializeElement(XmlReader,Boolean)
  type: Method
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  syntax:
    content: protected override void DeserializeElement (System.Xml.XmlReader reader, bool serializeCollectionKey);
    parameters:
    - id: reader
      type: System.Xml.XmlReader
      description: "To be added."
    - id: serializeCollectionKey
      type: System.Boolean
      description: "To be added."
  overload: System.Web.Services.Configuration.WsdlHelpGeneratorElement.DeserializeElement*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Href
  id: Href
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  langs:
  - csharp
  name: Href
  nameWithType: WsdlHelpGeneratorElement.Href
  fullName: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Href
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Gets or sets the file path to the Help page."
  syntax:
    content: public string Href { get; set; }
    return:
      type: System.String
      description: "A &lt;xref:System.String&gt; that contains the file path to the Help page."
  overload: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Href*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Properties
  id: Properties
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  langs:
  - csharp
  name: Properties
  nameWithType: WsdlHelpGeneratorElement.Properties
  fullName: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Properties
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Reset(System.Configuration.ConfigurationElement)
  id: Reset(System.Configuration.ConfigurationElement)
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  langs:
  - csharp
  name: Reset(ConfigurationElement)
  nameWithType: WsdlHelpGeneratorElement.Reset(ConfigurationElement)
  fullName: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Reset(ConfigurationElement)
  type: Method
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  syntax:
    content: protected override void Reset (System.Configuration.ConfigurationElement parentElement);
    parameters:
    - id: parentElement
      type: System.Configuration.ConfigurationElement
      description: "To be added."
  overload: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Reset*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.#ctor
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  isExternal: false
  name: WsdlHelpGeneratorElement()
  nameWithType: WsdlHelpGeneratorElement.WsdlHelpGeneratorElement()
  fullName: System.Web.Services.Configuration.WsdlHelpGeneratorElement.WsdlHelpGeneratorElement()
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  isExternal: false
  name: DeserializeElement(XmlReader,Boolean)
  nameWithType: WsdlHelpGeneratorElement.DeserializeElement(XmlReader,Boolean)
  fullName: System.Web.Services.Configuration.WsdlHelpGeneratorElement.DeserializeElement(XmlReader,Boolean)
- uid: System.Xml.XmlReader
  parent: System.Xml
  isExternal: true
  name: XmlReader
  nameWithType: XmlReader
  fullName: System.Xml.XmlReader
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Href
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  isExternal: false
  name: Href
  nameWithType: WsdlHelpGeneratorElement.Href
  fullName: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Href
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Properties
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  isExternal: false
  name: Properties
  nameWithType: WsdlHelpGeneratorElement.Properties
  fullName: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Reset(System.Configuration.ConfigurationElement)
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  isExternal: false
  name: Reset(ConfigurationElement)
  nameWithType: WsdlHelpGeneratorElement.Reset(ConfigurationElement)
  fullName: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Reset(ConfigurationElement)
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.#ctor*
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  isExternal: false
  name: WsdlHelpGeneratorElement
  nameWithType: WsdlHelpGeneratorElement.WsdlHelpGeneratorElement
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.DeserializeElement*
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  isExternal: false
  name: DeserializeElement
  nameWithType: WsdlHelpGeneratorElement.DeserializeElement
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Href*
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  isExternal: false
  name: Href
  nameWithType: WsdlHelpGeneratorElement.Href
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Properties*
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  isExternal: false
  name: Properties
  nameWithType: WsdlHelpGeneratorElement.Properties
- uid: System.Web.Services.Configuration.WsdlHelpGeneratorElement.Reset*
  parent: System.Web.Services.Configuration.WsdlHelpGeneratorElement
  isExternal: false
  name: Reset
  nameWithType: WsdlHelpGeneratorElement.Reset
