### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.TicketCompatibilityMode
  id: TicketCompatibilityMode
  children:
  - System.Web.Configuration.TicketCompatibilityMode.Framework20
  - System.Web.Configuration.TicketCompatibilityMode.Framework40
  langs:
  - csharp
  name: TicketCompatibilityMode
  nameWithType: TicketCompatibilityMode
  fullName: System.Web.Configuration.TicketCompatibilityMode
  type: Enum
  summary: "Defines whether to use Coordinated Universal Time (UTC) or local time for the ticket expiration date for forms authentication."
  remarks: "The ticket expiration date for ASP.NET forms authentication can be stored by using Coordinated Universal Time (UTC) or the local time. For compatibility between applications, and for compatibility between different versions of the .NET Framework, the ticket expiration time can be specified by using the `ticketCompatilityMode` attribute of the  element. The default value for the `ticketCompatibilityMode` attribute is Framework20."
  example:
  - "The following example configures the forms authentication ticket expiration date as UTC time.  \n  \n```  \n<system.web>  \n  <authentication mode=\"Forms\">   \n    <forms ticketCompatilityMode=\"Framework40\">  \n    </forms>  \n  </authentication>  \n</system.web>  \n```"
  syntax:
    content: public enum TicketCompatibilityMode
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.TicketCompatibilityMode.Framework20
  id: Framework20
  parent: System.Web.Configuration.TicketCompatibilityMode
  langs:
  - csharp
  name: Framework20
  nameWithType: TicketCompatibilityMode.Framework20
  fullName: System.Web.Configuration.TicketCompatibilityMode.Framework20
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifies that the ticket expiration date is stored as local time. This is the default value."
  syntax:
    content: Framework20
    return:
      type: System.Web.Configuration.TicketCompatibilityMode
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.TicketCompatibilityMode.Framework40
  id: Framework40
  parent: System.Web.Configuration.TicketCompatibilityMode
  langs:
  - csharp
  name: Framework40
  nameWithType: TicketCompatibilityMode.Framework40
  fullName: System.Web.Configuration.TicketCompatibilityMode.Framework40
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifies that the ticket expiration date is stored as UTC."
  syntax:
    content: Framework40
    return:
      type: System.Web.Configuration.TicketCompatibilityMode
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.TicketCompatibilityMode.Framework20
  parent: System.Web.Configuration.TicketCompatibilityMode
  isExternal: false
  name: Framework20
  nameWithType: TicketCompatibilityMode.Framework20
  fullName: System.Web.Configuration.TicketCompatibilityMode.Framework20
- uid: System.Web.Configuration.TicketCompatibilityMode
  parent: System.Web.Configuration
  isExternal: false
  name: TicketCompatibilityMode
  nameWithType: TicketCompatibilityMode
  fullName: System.Web.Configuration.TicketCompatibilityMode
- uid: System.Web.Configuration.TicketCompatibilityMode.Framework40
  parent: System.Web.Configuration.TicketCompatibilityMode
  isExternal: false
  name: Framework40
  nameWithType: TicketCompatibilityMode.Framework40
  fullName: System.Web.Configuration.TicketCompatibilityMode.Framework40
