### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Tracking.Configuration.VariableElement
  id: VariableElement
  children:
  - System.ServiceModel.Activities.Tracking.Configuration.VariableElement.#ctor
  - System.ServiceModel.Activities.Tracking.Configuration.VariableElement.ElementKey
  - System.ServiceModel.Activities.Tracking.Configuration.VariableElement.Name
  - System.ServiceModel.Activities.Tracking.Configuration.VariableElement.Properties
  langs:
  - csharp
  name: VariableElement
  nameWithType: VariableElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.VariableElement
  type: Class
  summary: "A configuration element that specifies the variables to be extracted from an activity."
  syntax:
    content: 'public class VariableElement : System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement.GetStringPairKey(System.String,System.String)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Tracking.Configuration.VariableElement
  langs:
  - csharp
  name: VariableElement()
  nameWithType: VariableElement.VariableElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.VariableElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Activities.Tracking.Configuration.VariableElement&quot;></see> class."
  syntax:
    content: public VariableElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.ElementKey
  id: ElementKey
  parent: System.ServiceModel.Activities.Tracking.Configuration.VariableElement
  langs:
  - csharp
  name: ElementKey
  nameWithType: VariableElement.ElementKey
  fullName: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.ElementKey
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Gets a key that uniquely identifies the variable query."
  syntax:
    content: public override object ElementKey { get; }
    return:
      type: System.Object
      description: "The element key."
  overload: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.ElementKey*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.Name
  id: Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.VariableElement
  langs:
  - csharp
  name: Name
  nameWithType: VariableElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.Name
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Gets or sets the name of the variable to be extracted."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "The variable name."
  overload: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.Name*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.VariableElement
  langs:
  - csharp
  name: Properties
  nameWithType: VariableElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Gets the collection of properties."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "The collection of properties for the element."
  overload: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  isExternal: false
  name: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.#ctor
  parent: System.ServiceModel.Activities.Tracking.Configuration.VariableElement
  isExternal: false
  name: VariableElement()
  nameWithType: VariableElement.VariableElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.VariableElement()
- uid: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.ElementKey
  parent: System.ServiceModel.Activities.Tracking.Configuration.VariableElement
  isExternal: false
  name: ElementKey
  nameWithType: VariableElement.ElementKey
  fullName: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.ElementKey
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.VariableElement
  isExternal: false
  name: Name
  nameWithType: VariableElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.Name
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.VariableElement
  isExternal: false
  name: Properties
  nameWithType: VariableElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.#ctor*
  parent: System.ServiceModel.Activities.Tracking.Configuration.VariableElement
  isExternal: false
  name: VariableElement
  nameWithType: VariableElement.VariableElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.ElementKey*
  parent: System.ServiceModel.Activities.Tracking.Configuration.VariableElement
  isExternal: false
  name: ElementKey
  nameWithType: VariableElement.ElementKey
- uid: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.Name*
  parent: System.ServiceModel.Activities.Tracking.Configuration.VariableElement
  isExternal: false
  name: Name
  nameWithType: VariableElement.Name
- uid: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.Properties*
  parent: System.ServiceModel.Activities.Tracking.Configuration.VariableElement
  isExternal: false
  name: Properties
  nameWithType: VariableElement.Properties
