### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.AllowedAudienceUriElement
  id: AllowedAudienceUriElement
  children:
  - System.ServiceModel.Configuration.AllowedAudienceUriElement.#ctor
  - System.ServiceModel.Configuration.AllowedAudienceUriElement.AllowedAudienceUri
  - System.ServiceModel.Configuration.AllowedAudienceUriElement.Properties
  langs:
  - csharp
  name: AllowedAudienceUriElement
  nameWithType: AllowedAudienceUriElement
  fullName: System.ServiceModel.Configuration.AllowedAudienceUriElement
  type: Class
  summary: "Represents a configuration element specifying the URI of an audience that can access a particular service."
  remarks: "For more information on this element, see [\\<allowedAudienceUris>](../Topic/%3CallowedAudienceUris%3E.md)"
  syntax:
    content: 'public sealed class AllowedAudienceUriElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.AllowedAudienceUriElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.AllowedAudienceUriElement
  langs:
  - csharp
  name: AllowedAudienceUriElement()
  nameWithType: AllowedAudienceUriElement.AllowedAudienceUriElement()
  fullName: System.ServiceModel.Configuration.AllowedAudienceUriElement.AllowedAudienceUriElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.AllowedAudienceUriElement&quot;></see> class."
  syntax:
    content: public AllowedAudienceUriElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.AllowedAudienceUriElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.AllowedAudienceUriElement.AllowedAudienceUri
  id: AllowedAudienceUri
  parent: System.ServiceModel.Configuration.AllowedAudienceUriElement
  langs:
  - csharp
  name: AllowedAudienceUri
  nameWithType: AllowedAudienceUriElement.AllowedAudienceUri
  fullName: System.ServiceModel.Configuration.AllowedAudienceUriElement.AllowedAudienceUri
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets a string specifying the URI of an audience that can access a particular service."
  syntax:
    content: public string AllowedAudienceUri { get; set; }
    return:
      type: System.String
      description: "A string specifying the URI of an audience that can access a particular service."
  overload: System.ServiceModel.Configuration.AllowedAudienceUriElement.AllowedAudienceUri*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.AllowedAudienceUriElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.AllowedAudienceUriElement
  langs:
  - csharp
  name: Properties
  nameWithType: AllowedAudienceUriElement.Properties
  fullName: System.ServiceModel.Configuration.AllowedAudienceUriElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.AllowedAudienceUriElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.AllowedAudienceUriElement.#ctor
  parent: System.ServiceModel.Configuration.AllowedAudienceUriElement
  isExternal: false
  name: AllowedAudienceUriElement()
  nameWithType: AllowedAudienceUriElement.AllowedAudienceUriElement()
  fullName: System.ServiceModel.Configuration.AllowedAudienceUriElement.AllowedAudienceUriElement()
- uid: System.ServiceModel.Configuration.AllowedAudienceUriElement.AllowedAudienceUri
  parent: System.ServiceModel.Configuration.AllowedAudienceUriElement
  isExternal: false
  name: AllowedAudienceUri
  nameWithType: AllowedAudienceUriElement.AllowedAudienceUri
  fullName: System.ServiceModel.Configuration.AllowedAudienceUriElement.AllowedAudienceUri
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.AllowedAudienceUriElement.Properties
  parent: System.ServiceModel.Configuration.AllowedAudienceUriElement
  isExternal: false
  name: Properties
  nameWithType: AllowedAudienceUriElement.Properties
  fullName: System.ServiceModel.Configuration.AllowedAudienceUriElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.AllowedAudienceUriElement.#ctor*
  parent: System.ServiceModel.Configuration.AllowedAudienceUriElement
  isExternal: false
  name: AllowedAudienceUriElement
  nameWithType: AllowedAudienceUriElement.AllowedAudienceUriElement
- uid: System.ServiceModel.Configuration.AllowedAudienceUriElement.AllowedAudienceUri*
  parent: System.ServiceModel.Configuration.AllowedAudienceUriElement
  isExternal: false
  name: AllowedAudienceUri
  nameWithType: AllowedAudienceUriElement.AllowedAudienceUri
- uid: System.ServiceModel.Configuration.AllowedAudienceUriElement.Properties*
  parent: System.ServiceModel.Configuration.AllowedAudienceUriElement
  isExternal: false
  name: Properties
  nameWithType: AllowedAudienceUriElement.Properties
