### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingAttribute
  id: SettingAttribute
  children:
  - System.Configuration.SettingAttribute.#ctor
  langs:
  - csharp
  name: SettingAttribute
  nameWithType: SettingAttribute
  fullName: System.Configuration.SettingAttribute
  type: Class
  summary: "Represents a custom settings attribute used to associate settings information with a settings property."
  remarks: "The SettingAttribute class associates settings information with a settings property. The <xref:System.Configuration.ApplicationSettingsBase> class will ignore all properties not marked with this or a derived attribute."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public class SettingAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SettingAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.SettingAttribute
  langs:
  - csharp
  name: SettingAttribute()
  nameWithType: SettingAttribute.SettingAttribute()
  fullName: System.Configuration.SettingAttribute.SettingAttribute()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.SettingAttribute&quot;></see> class."
  syntax:
    content: public SettingAttribute ();
    parameters: []
  overload: System.Configuration.SettingAttribute.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingAttribute.#ctor
  parent: System.Configuration.SettingAttribute
  isExternal: false
  name: SettingAttribute()
  nameWithType: SettingAttribute.SettingAttribute()
  fullName: System.Configuration.SettingAttribute.SettingAttribute()
- uid: System.Configuration.SettingAttribute.#ctor*
  parent: System.Configuration.SettingAttribute
  isExternal: false
  name: SettingAttribute
  nameWithType: SettingAttribute.SettingAttribute
