### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  id: FederationConfigurationCreatedEventArgs
  children:
  - System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.#ctor(System.IdentityModel.Services.Configuration.FederationConfiguration)
  - System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration
  langs:
  - csharp
  name: FederationConfigurationCreatedEventArgs
  nameWithType: FederationConfigurationCreatedEventArgs
  fullName: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  type: Class
  summary: "Provides data for the <see cref=&quot;E:System.IdentityModel.Services.FederatedAuthentication.FederationConfigurationCreated&quot;></see> event."
  remarks: "The <xref:System.IdentityModel.Services.FederatedAuthentication.FederationConfigurationCreated?displayProperty=fullName> event is raised when the first HTTP module in the web application references the <xref:System.IdentityModel.Services.FederatedAuthentication.FederationConfiguration%2A?displayProperty=fullName> property. The first access of the this property causes a <xref:System.IdentityModel.Services.Configuration.FederationConfiguration> object to be created and initialized from configuration. The <xref:System.IdentityModel.Services.FederatedAuthentication.FederationConfigurationCreated?displayProperty=fullName> event is then raised. You can access the newly created <xref:System.IdentityModel.Services.Configuration.FederationConfiguration> object through the <xref:System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration%2A?displayProperty=fullName> property in an event handler in order to examine or modify it."
  syntax:
    content: 'public class FederationConfigurationCreatedEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.#ctor(System.IdentityModel.Services.Configuration.FederationConfiguration)
  id: '#ctor(System.IdentityModel.Services.Configuration.FederationConfiguration)'
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  langs:
  - csharp
  name: FederationConfigurationCreatedEventArgs(FederationConfiguration)
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfigurationCreatedEventArgs(FederationConfiguration)
  fullName: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfigurationCreatedEventArgs(FederationConfiguration)
  type: Constructor
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs&quot;></see> class with the specified federation configuration object."
  remarks: "Initializes the <xref:System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration%2A> property to the federation configuration object specified by `config`."
  syntax:
    content: public FederationConfigurationCreatedEventArgs (System.IdentityModel.Services.Configuration.FederationConfiguration config);
    parameters:
    - id: config
      type: System.IdentityModel.Services.Configuration.FederationConfiguration
      description: "The federation configuration object. A  object contains the configurable properties for the WS-Federation Authentication Module () and the Session Authentication Module () in a web application."
  overload: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration
  id: FederationConfiguration
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  langs:
  - csharp
  name: FederationConfiguration
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfiguration
  fullName: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration
  type: Property
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services.Configuration
  summary: "Gets or sets the federation configuration object that was initialized from the configuration file."
  remarks: "The <xref:System.IdentityModel.Services.Configuration.FederationConfiguration> object contains the configurable properties for the WS-Federation Authentication Module (<xref:System.IdentityModel.Services.WSFederationAuthenticationModule>) and the Session Authentication Module (<xref:System.IdentityModel.Services.SessionAuthenticationModule>) in a web application.       To modify the configuration settings, you can set properties on the <xref:System.IdentityModel.Services.Configuration.FederationConfiguration> object that is referenced by this property, or you can provide an new <xref:System.IdentityModel.Services.Configuration.FederationConfiguration> object."
  syntax:
    content: public System.IdentityModel.Services.Configuration.FederationConfiguration FederationConfiguration { get; set; }
    return:
      type: System.IdentityModel.Services.Configuration.FederationConfiguration
      description: "The federation configuration object that was initialized from configuration."
  overload: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.#ctor(System.IdentityModel.Services.Configuration.FederationConfiguration)
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  isExternal: false
  name: FederationConfigurationCreatedEventArgs(FederationConfiguration)
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfigurationCreatedEventArgs(FederationConfiguration)
  fullName: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfigurationCreatedEventArgs(FederationConfiguration)
- uid: System.IdentityModel.Services.Configuration.FederationConfiguration
  parent: System.IdentityModel.Services.Configuration
  isExternal: false
  name: FederationConfiguration
  nameWithType: FederationConfiguration
  fullName: System.IdentityModel.Services.Configuration.FederationConfiguration
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  isExternal: false
  name: FederationConfiguration
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfiguration
  fullName: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.#ctor*
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  isExternal: false
  name: FederationConfigurationCreatedEventArgs
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfigurationCreatedEventArgs
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration*
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  isExternal: false
  name: FederationConfiguration
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfiguration
