### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Discovery.Configuration.AnnouncementEndpointCollectionElement
  id: AnnouncementEndpointCollectionElement
  children:
  - System.ServiceModel.Discovery.Configuration.AnnouncementEndpointCollectionElement.#ctor
  langs:
  - csharp
  name: AnnouncementEndpointCollectionElement
  nameWithType: AnnouncementEndpointCollectionElement
  fullName: System.ServiceModel.Discovery.Configuration.AnnouncementEndpointCollectionElement
  type: Class
  summary: "Represents a container for <see cref=&quot;T:System.ServiceModel.Discovery.Configuration.AnnouncementEndpointElement&quot;></see> configuration elements."
  syntax:
    content: 'public class AnnouncementEndpointCollectionElement : System.ServiceModel.Configuration.StandardEndpointCollectionElement<System.ServiceModel.Discovery.AnnouncementEndpoint,System.ServiceModel.Discovery.Configuration.AnnouncementEndpointElement>'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.EndpointCollectionElement
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.EndpointCollectionElement.EndpointName
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.ConfiguredEndpoints
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.ContainsKey(System.String)
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.Endpoints
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.EndpointType
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.GetDefaultStandardEndpointElement
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.Properties
  - System.ServiceModel.Configuration.StandardEndpointCollectionElement`2.TryAdd(System.String,System.ServiceModel.Description.ServiceEndpoint,System.Configuration.Configuration)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Discovery.Configuration.AnnouncementEndpointCollectionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Discovery.Configuration.AnnouncementEndpointCollectionElement
  langs:
  - csharp
  name: AnnouncementEndpointCollectionElement()
  nameWithType: AnnouncementEndpointCollectionElement.AnnouncementEndpointCollectionElement()
  fullName: System.ServiceModel.Discovery.Configuration.AnnouncementEndpointCollectionElement.AnnouncementEndpointCollectionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Creates a new instance of <see cref=&quot;T:System.ServiceModel.Discovery.Configuration.AnnouncementEndpointCollectionElement&quot;></see> class."
  syntax:
    content: public AnnouncementEndpointCollectionElement ();
    parameters: []
  overload: System.ServiceModel.Discovery.Configuration.AnnouncementEndpointCollectionElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.StandardEndpointCollectionElement`2
  isExternal: false
  name: System.ServiceModel.Configuration.StandardEndpointCollectionElement<System.ServiceModel.Discovery.AnnouncementEndpoint,System.ServiceModel.Discovery.Configuration.AnnouncementEndpointElement>
- uid: System.ServiceModel.Discovery.Configuration.AnnouncementEndpointCollectionElement.#ctor
  parent: System.ServiceModel.Discovery.Configuration.AnnouncementEndpointCollectionElement
  isExternal: false
  name: AnnouncementEndpointCollectionElement()
  nameWithType: AnnouncementEndpointCollectionElement.AnnouncementEndpointCollectionElement()
  fullName: System.ServiceModel.Discovery.Configuration.AnnouncementEndpointCollectionElement.AnnouncementEndpointCollectionElement()
- uid: System.ServiceModel.Discovery.Configuration.AnnouncementEndpointCollectionElement.#ctor*
  parent: System.ServiceModel.Discovery.Configuration.AnnouncementEndpointCollectionElement
  isExternal: false
  name: AnnouncementEndpointCollectionElement
  nameWithType: AnnouncementEndpointCollectionElement.AnnouncementEndpointCollectionElement
