### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.ProxyElement.BypassOnLocalValues
  id: ProxyElement.BypassOnLocalValues
  children:
  - System.Net.Configuration.ProxyElement.BypassOnLocalValues.False
  - System.Net.Configuration.ProxyElement.BypassOnLocalValues.True
  - System.Net.Configuration.ProxyElement.BypassOnLocalValues.Unspecified
  langs:
  - csharp
  name: ProxyElement+BypassOnLocalValues
  nameWithType: ProxyElement+BypassOnLocalValues
  fullName: System.Net.Configuration.ProxyElement+BypassOnLocalValues
  type: Enum
  syntax:
    content: public enum ProxyElement.BypassOnLocalValues
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.ProxyElement.BypassOnLocalValues.False
  id: "False"
  parent: System.Net.Configuration.ProxyElement.BypassOnLocalValues
  langs:
  - csharp
  name: "False"
  nameWithType: ProxyElement+BypassOnLocalValues.False
  fullName: System.Net.Configuration.ProxyElement+BypassOnLocalValues.False
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: "False"
    return:
      type: System.Net.Configuration.ProxyElement.BypassOnLocalValues
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.ProxyElement.BypassOnLocalValues.True
  id: "True"
  parent: System.Net.Configuration.ProxyElement.BypassOnLocalValues
  langs:
  - csharp
  name: "True"
  nameWithType: ProxyElement+BypassOnLocalValues.True
  fullName: System.Net.Configuration.ProxyElement+BypassOnLocalValues.True
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: "True"
    return:
      type: System.Net.Configuration.ProxyElement.BypassOnLocalValues
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.ProxyElement.BypassOnLocalValues.Unspecified
  id: Unspecified
  parent: System.Net.Configuration.ProxyElement.BypassOnLocalValues
  langs:
  - csharp
  name: Unspecified
  nameWithType: ProxyElement+BypassOnLocalValues.Unspecified
  fullName: System.Net.Configuration.ProxyElement+BypassOnLocalValues.Unspecified
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: Unspecified
    return:
      type: System.Net.Configuration.ProxyElement.BypassOnLocalValues
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Net.Configuration.ProxyElement.BypassOnLocalValues.False
  parent: System.Net.Configuration.ProxyElement.BypassOnLocalValues
  isExternal: false
  name: "False"
  nameWithType: ProxyElement+BypassOnLocalValues.False
  fullName: System.Net.Configuration.ProxyElement+BypassOnLocalValues.False
- uid: System.Net.Configuration.ProxyElement.BypassOnLocalValues
  parent: System.Net.Configuration
  isExternal: false
  name: ProxyElement+BypassOnLocalValues
  nameWithType: ProxyElement+BypassOnLocalValues
  fullName: System.Net.Configuration.ProxyElement+BypassOnLocalValues
- uid: System.Net.Configuration.ProxyElement.BypassOnLocalValues.True
  parent: System.Net.Configuration.ProxyElement.BypassOnLocalValues
  isExternal: false
  name: "True"
  nameWithType: ProxyElement+BypassOnLocalValues.True
  fullName: System.Net.Configuration.ProxyElement+BypassOnLocalValues.True
- uid: System.Net.Configuration.ProxyElement.BypassOnLocalValues.Unspecified
  parent: System.Net.Configuration.ProxyElement.BypassOnLocalValues
  isExternal: false
  name: Unspecified
  nameWithType: ProxyElement+BypassOnLocalValues.Unspecified
  fullName: System.Net.Configuration.ProxyElement+BypassOnLocalValues.Unspecified
