### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ProvidersHelper
  id: ProvidersHelper
  children:
  - System.Web.Configuration.ProvidersHelper.InstantiateProvider(System.Configuration.ProviderSettings,System.Type)
  - System.Web.Configuration.ProvidersHelper.InstantiateProviders(System.Configuration.ProviderSettingsCollection,System.Configuration.Provider.ProviderCollection,System.Type)
  langs:
  - csharp
  name: ProvidersHelper
  nameWithType: ProvidersHelper
  fullName: System.Web.Configuration.ProvidersHelper
  type: Class
  summary: "Provides methods for creating provider instances, either singly or in a batch."
  syntax:
    content: public static class ProvidersHelper
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.ProvidersHelper.InstantiateProvider(System.Configuration.ProviderSettings,System.Type)
  id: InstantiateProvider(System.Configuration.ProviderSettings,System.Type)
  parent: System.Web.Configuration.ProvidersHelper
  langs:
  - csharp
  name: InstantiateProvider(ProviderSettings,Type)
  nameWithType: ProvidersHelper.InstantiateProvider(ProviderSettings,Type)
  fullName: System.Web.Configuration.ProvidersHelper.InstantiateProvider(ProviderSettings,Type)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initializes and returns a single provider of the given type using the supplied settings."
  syntax:
    content: public static System.Configuration.Provider.ProviderBase InstantiateProvider (System.Configuration.ProviderSettings providerSettings, Type providerType);
    parameters:
    - id: providerSettings
      type: System.Configuration.ProviderSettings
      description: "The settings to be passed to the provider upon initialization."
    - id: providerType
      type: System.Type
      description: "The <xref:System.Type> of the provider to be initialized."
    return:
      type: System.Configuration.Provider.ProviderBase
      description: "To be added."
  overload: System.Web.Configuration.ProvidersHelper.InstantiateProvider*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "The provider type defined in configuration was  or an empty string (\"\").  \n  \n \\- or -  \n  \n The provider type defined in configuration is not compatible with the type used by the feature that is attempting to create a new instance of the provider."
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "The provider threw an exception while it was being initialized.  \n  \n \\- or -  \n  \n An error occurred while attempting to resolve a <xref:System.Type> instance for the provider specified in providerSettings."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.ProvidersHelper.InstantiateProviders(System.Configuration.ProviderSettingsCollection,System.Configuration.Provider.ProviderCollection,System.Type)
  id: InstantiateProviders(System.Configuration.ProviderSettingsCollection,System.Configuration.Provider.ProviderCollection,System.Type)
  parent: System.Web.Configuration.ProvidersHelper
  langs:
  - csharp
  name: InstantiateProviders(ProviderSettingsCollection,ProviderCollection,Type)
  nameWithType: ProvidersHelper.InstantiateProviders(ProviderSettingsCollection,ProviderCollection,Type)
  fullName: System.Web.Configuration.ProvidersHelper.InstantiateProviders(ProviderSettingsCollection,ProviderCollection,Type)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initializes a collection of providers of the given type using the supplied settings."
  remarks: "This method calls the <xref:System.Web.Configuration.ProvidersHelper.InstantiateProvider%2A> method, and any exceptions thrown by that method will bubble up through the InstantiateProviders method."
  syntax:
    content: public static void InstantiateProviders (System.Configuration.ProviderSettingsCollection configProviders, System.Configuration.Provider.ProviderCollection providers, Type providerType);
    parameters:
    - id: configProviders
      type: System.Configuration.ProviderSettingsCollection
      description: "A collection of settings to be passed to the provider upon initialization."
    - id: providers
      type: System.Configuration.Provider.ProviderCollection
      description: "The collection used to contain the initialized providers after the method returns."
    - id: providerType
      type: System.Type
      description: "The <xref:System.Type> of the providers to be initialized."
  overload: System.Web.Configuration.ProvidersHelper.InstantiateProviders*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Configuration.ProvidersHelper.InstantiateProvider(System.Configuration.ProviderSettings,System.Type)
  parent: System.Web.Configuration.ProvidersHelper
  isExternal: false
  name: InstantiateProvider(ProviderSettings,Type)
  nameWithType: ProvidersHelper.InstantiateProvider(ProviderSettings,Type)
  fullName: System.Web.Configuration.ProvidersHelper.InstantiateProvider(ProviderSettings,Type)
- uid: System.Configuration.Provider.ProviderBase
  parent: System.Configuration.Provider
  isExternal: false
  name: ProviderBase
  nameWithType: ProviderBase
  fullName: System.Configuration.Provider.ProviderBase
- uid: System.Configuration.ProviderSettings
  parent: System.Configuration
  isExternal: false
  name: ProviderSettings
  nameWithType: ProviderSettings
  fullName: System.Configuration.ProviderSettings
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Web.Configuration.ProvidersHelper.InstantiateProviders(System.Configuration.ProviderSettingsCollection,System.Configuration.Provider.ProviderCollection,System.Type)
  parent: System.Web.Configuration.ProvidersHelper
  isExternal: false
  name: InstantiateProviders(ProviderSettingsCollection,ProviderCollection,Type)
  nameWithType: ProvidersHelper.InstantiateProviders(ProviderSettingsCollection,ProviderCollection,Type)
  fullName: System.Web.Configuration.ProvidersHelper.InstantiateProviders(ProviderSettingsCollection,ProviderCollection,Type)
- uid: System.Configuration.ProviderSettingsCollection
  parent: System.Configuration
  isExternal: false
  name: ProviderSettingsCollection
  nameWithType: ProviderSettingsCollection
  fullName: System.Configuration.ProviderSettingsCollection
- uid: System.Configuration.Provider.ProviderCollection
  parent: System.Configuration.Provider
  isExternal: false
  name: ProviderCollection
  nameWithType: ProviderCollection
  fullName: System.Configuration.Provider.ProviderCollection
- uid: System.Web.Configuration.ProvidersHelper.InstantiateProvider*
  parent: System.Web.Configuration.ProvidersHelper
  isExternal: false
  name: InstantiateProvider
  nameWithType: ProvidersHelper.InstantiateProvider
- uid: System.Web.Configuration.ProvidersHelper.InstantiateProviders*
  parent: System.Web.Configuration.ProvidersHelper
  isExternal: false
  name: InstantiateProviders
  nameWithType: ProvidersHelper.InstantiateProviders
