### YamlMime:ManagedReference
items:
- uid: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection
  id: NetDataContractSerializerSection
  children:
  - System.Runtime.Serialization.Configuration.NetDataContractSerializerSection.#ctor
  - System.Runtime.Serialization.Configuration.NetDataContractSerializerSection.EnableUnsafeTypeForwarding
  - System.Runtime.Serialization.Configuration.NetDataContractSerializerSection.Properties
  langs:
  - csharp
  name: NetDataContractSerializerSection
  nameWithType: NetDataContractSerializerSection
  fullName: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection
  type: Class
  summary: "Handles the XML elements used to configure serialization by the <see cref=&quot;T:System.Runtime.Serialization.NetDataContractSerializer&quot;></see>."
  syntax:
    content: 'public sealed class NetDataContractSerializerSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection.#ctor
  id: '#ctor'
  parent: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection
  langs:
  - csharp
  name: NetDataContractSerializerSection()
  nameWithType: NetDataContractSerializerSection.NetDataContractSerializerSection()
  fullName: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection.NetDataContractSerializerSection()
  type: Constructor
  assemblies:
  - System.Runtime.Serialization
  namespace: System.Runtime.Serialization.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Runtime.Serialization.Configuration.NetDataContractSerializerSection&quot;></see> class."
  syntax:
    content: public NetDataContractSerializerSection ();
    parameters: []
  overload: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection.EnableUnsafeTypeForwarding
  id: EnableUnsafeTypeForwarding
  parent: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection
  langs:
  - csharp
  name: EnableUnsafeTypeForwarding
  nameWithType: NetDataContractSerializerSection.EnableUnsafeTypeForwarding
  fullName: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection.EnableUnsafeTypeForwarding
  type: Property
  assemblies:
  - System.Runtime.Serialization
  namespace: System.Runtime.Serialization.Configuration
  summary: "Gets a value that indicates whether unsafe type forwarding is enabled."
  syntax:
    content: public bool EnableUnsafeTypeForwarding { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if unsafe type forwarding is enabled; otherwise, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>."
  overload: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection.EnableUnsafeTypeForwarding*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection.Properties
  id: Properties
  parent: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection
  langs:
  - csharp
  name: Properties
  nameWithType: NetDataContractSerializerSection.Properties
  fullName: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection.Properties
  type: Property
  assemblies:
  - System.Runtime.Serialization
  namespace: System.Runtime.Serialization.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection.#ctor
  parent: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection
  isExternal: false
  name: NetDataContractSerializerSection()
  nameWithType: NetDataContractSerializerSection.NetDataContractSerializerSection()
  fullName: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection.NetDataContractSerializerSection()
- uid: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection.EnableUnsafeTypeForwarding
  parent: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection
  isExternal: false
  name: EnableUnsafeTypeForwarding
  nameWithType: NetDataContractSerializerSection.EnableUnsafeTypeForwarding
  fullName: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection.EnableUnsafeTypeForwarding
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection.Properties
  parent: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection
  isExternal: false
  name: Properties
  nameWithType: NetDataContractSerializerSection.Properties
  fullName: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection.#ctor*
  parent: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection
  isExternal: false
  name: NetDataContractSerializerSection
  nameWithType: NetDataContractSerializerSection.NetDataContractSerializerSection
- uid: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection.EnableUnsafeTypeForwarding*
  parent: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection
  isExternal: false
  name: EnableUnsafeTypeForwarding
  nameWithType: NetDataContractSerializerSection.EnableUnsafeTypeForwarding
- uid: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection.Properties*
  parent: System.Runtime.Serialization.Configuration.NetDataContractSerializerSection
  isExternal: false
  name: Properties
  nameWithType: NetDataContractSerializerSection.Properties
