### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsLoadedEventHandler
  id: SettingsLoadedEventHandler
  langs:
  - csharp
  name: SettingsLoadedEventHandler
  nameWithType: SettingsLoadedEventHandler
  fullName: System.Configuration.SettingsLoadedEventHandler
  type: Delegate
  summary: "Represents the method that will handle the <see cref=&quot;E:System.Configuration.ApplicationSettingsBase.SettingsLoaded&quot;></see> event."
  remarks: "The <xref:System.Configuration.ApplicationSettingsBase.SettingsLoaded> event occurs when settings are retrieved from a provider. This event fires once for each provider."
  syntax:
    content: public delegate void SettingsLoadedEventHandler(object sender, SettingsLoadedEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
