### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  id: HttpCapabilitiesDefaultProvider
  children:
  - System.Web.Configuration.HttpCapabilitiesDefaultProvider.#ctor
  - System.Web.Configuration.HttpCapabilitiesDefaultProvider.#ctor(System.Web.Configuration.HttpCapabilitiesDefaultProvider)
  - System.Web.Configuration.HttpCapabilitiesDefaultProvider.AddDependency(System.String)
  - System.Web.Configuration.HttpCapabilitiesDefaultProvider.AddRuleList(System.Collections.ArrayList)
  - System.Web.Configuration.HttpCapabilitiesDefaultProvider.CacheTime
  - System.Web.Configuration.HttpCapabilitiesDefaultProvider.GetBrowserCapabilities(System.Web.HttpRequest)
  - System.Web.Configuration.HttpCapabilitiesDefaultProvider.ResultType
  - System.Web.Configuration.HttpCapabilitiesDefaultProvider.UserAgentCacheKeyLength
  langs:
  - csharp
  name: HttpCapabilitiesDefaultProvider
  nameWithType: HttpCapabilitiesDefaultProvider
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  type: Class
  summary: "The default extension of the <see cref=&quot;T:System.Web.Configuration.HttpCapabilitiesProvider&quot;></see> class that is included with ASP.NET."
  syntax:
    content: 'public class HttpCapabilitiesDefaultProvider : System.Web.Configuration.HttpCapabilitiesProvider'
  inheritance:
  - System.Object
  - System.Web.Configuration.HttpCapabilitiesProvider
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  langs:
  - csharp
  name: HttpCapabilitiesDefaultProvider()
  nameWithType: HttpCapabilitiesDefaultProvider.HttpCapabilitiesDefaultProvider()
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.HttpCapabilitiesDefaultProvider()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Web.Configuration.HttpCapabilitiesDefaultProvider&quot;></see> class."
  syntax:
    content: public HttpCapabilitiesDefaultProvider ();
    parameters: []
  overload: System.Web.Configuration.HttpCapabilitiesDefaultProvider.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.#ctor(System.Web.Configuration.HttpCapabilitiesDefaultProvider)
  id: '#ctor(System.Web.Configuration.HttpCapabilitiesDefaultProvider)'
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  langs:
  - csharp
  name: HttpCapabilitiesDefaultProvider(HttpCapabilitiesDefaultProvider)
  nameWithType: HttpCapabilitiesDefaultProvider.HttpCapabilitiesDefaultProvider(HttpCapabilitiesDefaultProvider)
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.HttpCapabilitiesDefaultProvider(HttpCapabilitiesDefaultProvider)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Web.Configuration.HttpCapabilitiesDefaultProvider&quot;></see> class with the values of the specified instance."
  syntax:
    content: public HttpCapabilitiesDefaultProvider (System.Web.Configuration.HttpCapabilitiesDefaultProvider parent);
    parameters:
    - id: parent
      type: System.Web.Configuration.HttpCapabilitiesDefaultProvider
      description: "The  instance to use for initializing a new instance."
  overload: System.Web.Configuration.HttpCapabilitiesDefaultProvider.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.AddDependency(System.String)
  id: AddDependency(System.String)
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  langs:
  - csharp
  name: AddDependency(String)
  nameWithType: HttpCapabilitiesDefaultProvider.AddDependency(String)
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.AddDependency(String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Adds an HTTP request string to use to parse browser capability information."
  remarks: "This method adds to the collection that is created by the `use` child element of the `browserCaps` element of the Web.config file."
  syntax:
    content: public void AddDependency (string variable);
    parameters:
    - id: variable
      type: System.String
      description: "The string to use to parse browser capability information."
  overload: System.Web.Configuration.HttpCapabilitiesDefaultProvider.AddDependency*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.AddRuleList(System.Collections.ArrayList)
  id: AddRuleList(System.Collections.ArrayList)
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  langs:
  - csharp
  name: AddRuleList(ArrayList)
  nameWithType: HttpCapabilitiesDefaultProvider.AddRuleList(ArrayList)
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.AddRuleList(ArrayList)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Adds a search string that modifies a browser definition."
  remarks: "This method adds to the collection that is created by the `filter` child element of the `browserCaps` element of the Web.config file."
  syntax:
    content: public virtual void AddRuleList (System.Collections.ArrayList ruleList);
    parameters:
    - id: ruleList
      type: System.Collections.ArrayList
      description: "The search string that modifies a browser definition."
  overload: System.Web.Configuration.HttpCapabilitiesDefaultProvider.AddRuleList*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.CacheTime
  id: CacheTime
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  langs:
  - csharp
  name: CacheTime
  nameWithType: HttpCapabilitiesDefaultProvider.CacheTime
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.CacheTime
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets or sets the length of time in seconds to retain the <see cref=&quot;T:System.Web.HttpBrowserCapabilities&quot;></see> object in the cache."
  syntax:
    content: public TimeSpan CacheTime { get; set; }
    return:
      type: System.TimeSpan
      description: "The length of time in seconds to retain the <see cref=&quot;T:System.Web.HttpBrowserCapabilities&quot;></see> object in the cache."
  overload: System.Web.Configuration.HttpCapabilitiesDefaultProvider.CacheTime*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.GetBrowserCapabilities(System.Web.HttpRequest)
  id: GetBrowserCapabilities(System.Web.HttpRequest)
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  langs:
  - csharp
  name: GetBrowserCapabilities(HttpRequest)
  nameWithType: HttpCapabilitiesDefaultProvider.GetBrowserCapabilities(HttpRequest)
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.GetBrowserCapabilities(HttpRequest)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets the <see cref=&quot;T:System.Web.HttpBrowserCapabilities&quot;></see> object for the specified <see cref=&quot;T:System.Web.HttpRequest&quot;></see> object."
  syntax:
    content: public override System.Web.HttpBrowserCapabilities GetBrowserCapabilities (System.Web.HttpRequest request);
    parameters:
    - id: request
      type: System.Web.HttpRequest
      description: "The  object."
    return:
      type: System.Web.HttpBrowserCapabilities
      description: "To be added."
  overload: System.Web.Configuration.HttpCapabilitiesDefaultProvider.GetBrowserCapabilities*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.ResultType
  id: ResultType
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  langs:
  - csharp
  name: ResultType
  nameWithType: HttpCapabilitiesDefaultProvider.ResultType
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.ResultType
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets or sets the type of the class that is used to hold the results from parsing the <xref uid=&quot;langword_csharp_browserCap&quot; name=&quot;browserCap&quot; href=&quot;&quot;></xref> element of the Web.config file."
  remarks: "This property corresponds to the `result` child element of the `browserCaps` element of the Web.config file."
  syntax:
    content: public Type ResultType { get; set; }
    return:
      type: System.Type
      description: "The type of the class that is used to hold the results from parsing the <xref uid=&quot;langword_csharp_browserCaps&quot; name=&quot;browserCaps&quot; href=&quot;&quot;></xref> element of the Web.config file."
  overload: System.Web.Configuration.HttpCapabilitiesDefaultProvider.ResultType*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.UserAgentCacheKeyLength
  id: UserAgentCacheKeyLength
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  langs:
  - csharp
  name: UserAgentCacheKeyLength
  nameWithType: HttpCapabilitiesDefaultProvider.UserAgentCacheKeyLength
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.UserAgentCacheKeyLength
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets or sets the number of characters from the user agent string to use for caching of the <see cref=&quot;T:System.Web.HttpBrowserCapabilities&quot;></see> object."
  syntax:
    content: public int UserAgentCacheKeyLength { get; set; }
    return:
      type: System.Int32
      description: "The number of characters from the supplied user agent string to use for caching of the <see cref=&quot;T:System.Web.HttpBrowserCapabilities&quot;></see> object."
  overload: System.Web.Configuration.HttpCapabilitiesDefaultProvider.UserAgentCacheKeyLength*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Web.Configuration.HttpCapabilitiesProvider
  isExternal: false
  name: System.Web.Configuration.HttpCapabilitiesProvider
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.#ctor
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: HttpCapabilitiesDefaultProvider()
  nameWithType: HttpCapabilitiesDefaultProvider.HttpCapabilitiesDefaultProvider()
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.HttpCapabilitiesDefaultProvider()
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.#ctor(System.Web.Configuration.HttpCapabilitiesDefaultProvider)
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: HttpCapabilitiesDefaultProvider(HttpCapabilitiesDefaultProvider)
  nameWithType: HttpCapabilitiesDefaultProvider.HttpCapabilitiesDefaultProvider(HttpCapabilitiesDefaultProvider)
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.HttpCapabilitiesDefaultProvider(HttpCapabilitiesDefaultProvider)
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  parent: System.Web.Configuration
  isExternal: false
  name: HttpCapabilitiesDefaultProvider
  nameWithType: HttpCapabilitiesDefaultProvider
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.AddDependency(System.String)
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: AddDependency(String)
  nameWithType: HttpCapabilitiesDefaultProvider.AddDependency(String)
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.AddDependency(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.AddRuleList(System.Collections.ArrayList)
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: AddRuleList(ArrayList)
  nameWithType: HttpCapabilitiesDefaultProvider.AddRuleList(ArrayList)
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.AddRuleList(ArrayList)
- uid: System.Collections.ArrayList
  parent: System.Collections
  isExternal: false
  name: ArrayList
  nameWithType: ArrayList
  fullName: System.Collections.ArrayList
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.CacheTime
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: CacheTime
  nameWithType: HttpCapabilitiesDefaultProvider.CacheTime
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.CacheTime
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.GetBrowserCapabilities(System.Web.HttpRequest)
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: GetBrowserCapabilities(HttpRequest)
  nameWithType: HttpCapabilitiesDefaultProvider.GetBrowserCapabilities(HttpRequest)
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.GetBrowserCapabilities(HttpRequest)
- uid: System.Web.HttpBrowserCapabilities
  parent: System.Web
  isExternal: false
  name: HttpBrowserCapabilities
  nameWithType: HttpBrowserCapabilities
  fullName: System.Web.HttpBrowserCapabilities
- uid: System.Web.HttpRequest
  parent: System.Web
  isExternal: false
  name: HttpRequest
  nameWithType: HttpRequest
  fullName: System.Web.HttpRequest
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.ResultType
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: ResultType
  nameWithType: HttpCapabilitiesDefaultProvider.ResultType
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.ResultType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.UserAgentCacheKeyLength
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: UserAgentCacheKeyLength
  nameWithType: HttpCapabilitiesDefaultProvider.UserAgentCacheKeyLength
  fullName: System.Web.Configuration.HttpCapabilitiesDefaultProvider.UserAgentCacheKeyLength
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.#ctor*
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: HttpCapabilitiesDefaultProvider
  nameWithType: HttpCapabilitiesDefaultProvider.HttpCapabilitiesDefaultProvider
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.AddDependency*
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: AddDependency
  nameWithType: HttpCapabilitiesDefaultProvider.AddDependency
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.AddRuleList*
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: AddRuleList
  nameWithType: HttpCapabilitiesDefaultProvider.AddRuleList
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.CacheTime*
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: CacheTime
  nameWithType: HttpCapabilitiesDefaultProvider.CacheTime
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.GetBrowserCapabilities*
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: GetBrowserCapabilities
  nameWithType: HttpCapabilitiesDefaultProvider.GetBrowserCapabilities
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.ResultType*
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: ResultType
  nameWithType: HttpCapabilitiesDefaultProvider.ResultType
- uid: System.Web.Configuration.HttpCapabilitiesDefaultProvider.UserAgentCacheKeyLength*
  parent: System.Web.Configuration.HttpCapabilitiesDefaultProvider
  isExternal: false
  name: UserAgentCacheKeyLength
  nameWithType: HttpCapabilitiesDefaultProvider.UserAgentCacheKeyLength
