### YamlMime:ManagedReference
items:
- uid: System.Printing.PrintJobSettings
  id: PrintJobSettings
  children:
  - System.Printing.PrintJobSettings.CurrentPrintTicket
  - System.Printing.PrintJobSettings.Description
  langs:
  - csharp
  name: PrintJobSettings
  nameWithType: PrintJobSettings
  fullName: System.Printing.PrintJobSettings
  type: Class
  summary: "Describes a print job."
  remarks: "The <xref:System.Printing.PrintTicket> object, which is the value of the <xref:System.Printing.PrintJobSettings.CurrentPrintTicket%2A> property, holds all the detailed settings for a print job. The parent, PrintJobSettings, adds only a description.      > [!CAUTION] >  Classes within the <xref:System.Printing> namespace are not supported for use within a Windows service or ASP.NET application or service. Attempting to use these classes from within one of these application types may produce unexpected problems, such as diminished service performance and run-time exceptions.       If you want to print from a Windows Forms application, see the <xref:System.Drawing.Printing> namespace."
  syntax:
    content: public class PrintJobSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Printing.PrintJobSettings.CurrentPrintTicket
  id: CurrentPrintTicket
  parent: System.Printing.PrintJobSettings
  langs:
  - csharp
  name: CurrentPrintTicket
  nameWithType: PrintJobSettings.CurrentPrintTicket
  fullName: System.Printing.PrintJobSettings.CurrentPrintTicket
  type: Property
  assemblies:
  - System.Printing
  namespace: System.Printing
  summary: "Gets or sets a <see cref=&quot;T:System.Printing.PrintTicket&quot;></see> object that holds all the detailed settings for the print job."
  remarks: "Setting this CurrentPrintTicket property does not validate or modify the specified <xref:System.Printing.PrintTicket> for a particular <xref:System.Printing.PrintQueue>.  If needed, use the <xref:System.Printing.PrintQueue.MergeAndValidatePrintTicket%2A> method to create a <xref:System.Printing.PrintQueue>-specific <xref:System.Printing.PrintTicket> that is valid for a given printer."
  syntax:
    content: public System.Printing.PrintTicket CurrentPrintTicket { get; set; }
    return:
      type: System.Printing.PrintTicket
      description: "A <see cref=&quot;T:System.Printing.PrintTicket&quot;></see> object that holds all the details about the print job, such as the number of copies to print, and whether stapling or duplex printing is used."
  overload: System.Printing.PrintJobSettings.CurrentPrintTicket*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Printing.PrintJobSettings.Description
  id: Description
  parent: System.Printing.PrintJobSettings
  langs:
  - csharp
  name: Description
  nameWithType: PrintJobSettings.Description
  fullName: System.Printing.PrintJobSettings.Description
  type: Property
  assemblies:
  - System.Printing
  namespace: System.Printing
  summary: "Gets or sets a description of a print job."
  syntax:
    content: public string Description { get; set; }
    return:
      type: System.String
      description: "A &lt;xref:System.String&gt; that describes the print job, for example, &quot;Quarterly Report.&quot;"
  overload: System.Printing.PrintJobSettings.Description*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Printing.PrintJobSettings.CurrentPrintTicket
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: CurrentPrintTicket
  nameWithType: PrintJobSettings.CurrentPrintTicket
  fullName: System.Printing.PrintJobSettings.CurrentPrintTicket
- uid: System.Printing.PrintTicket
  parent: System.Printing
  isExternal: false
  name: PrintTicket
  nameWithType: PrintTicket
  fullName: System.Printing.PrintTicket
- uid: System.Printing.PrintJobSettings.Description
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: Description
  nameWithType: PrintJobSettings.Description
  fullName: System.Printing.PrintJobSettings.Description
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Printing.PrintJobSettings.CurrentPrintTicket*
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: CurrentPrintTicket
  nameWithType: PrintJobSettings.CurrentPrintTicket
- uid: System.Printing.PrintJobSettings.Description*
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: Description
  nameWithType: PrintJobSettings.Description
