### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Discovery.UdpTransportSettings
  id: UdpTransportSettings
  children:
  - System.ServiceModel.Discovery.UdpTransportSettings.DuplicateMessageHistoryLength
  - System.ServiceModel.Discovery.UdpTransportSettings.MaxBufferPoolSize
  - System.ServiceModel.Discovery.UdpTransportSettings.MaxMulticastRetransmitCount
  - System.ServiceModel.Discovery.UdpTransportSettings.MaxPendingMessageCount
  - System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize
  - System.ServiceModel.Discovery.UdpTransportSettings.MaxUnicastRetransmitCount
  - System.ServiceModel.Discovery.UdpTransportSettings.MulticastInterfaceId
  - System.ServiceModel.Discovery.UdpTransportSettings.SocketReceiveBufferSize
  - System.ServiceModel.Discovery.UdpTransportSettings.TimeToLive
  langs:
  - csharp
  name: UdpTransportSettings
  nameWithType: UdpTransportSettings
  fullName: System.ServiceModel.Discovery.UdpTransportSettings
  type: Class
  summary: "Enables you to set UDP transport settings."
  syntax:
    content: public class UdpTransportSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Discovery.UdpTransportSettings.DuplicateMessageHistoryLength
  id: DuplicateMessageHistoryLength
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: DuplicateMessageHistoryLength
  nameWithType: UdpTransportSettings.DuplicateMessageHistoryLength
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.DuplicateMessageHistoryLength
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "Gets or sets a value that specifies the maximum number of message hashes used by the transport for identifying duplicate messages."
  remarks: "This property gives system administrators and developers a way to turn off duplicate message detection algorithms. Setting this value to 0 disables duplicate message detection. The default value is 4112."
  syntax:
    content: public int DuplicateMessageHistoryLength { get; set; }
    return:
      type: System.Int32
      description: "The maximum number of message hashes to use."
  overload: System.ServiceModel.Discovery.UdpTransportSettings.DuplicateMessageHistoryLength*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxBufferPoolSize
  id: MaxBufferPoolSize
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: MaxBufferPoolSize
  nameWithType: UdpTransportSettings.MaxBufferPoolSize
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxBufferPoolSize
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "Gets or sets the maximum size, in bytes, of any buffer pools used by the transport."
  syntax:
    content: public long MaxBufferPoolSize { get; set; }
    return:
      type: System.Int64
      description: "The maximum buffer pool size."
  overload: System.ServiceModel.Discovery.UdpTransportSettings.MaxBufferPoolSize*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxMulticastRetransmitCount
  id: MaxMulticastRetransmitCount
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: MaxMulticastRetransmitCount
  nameWithType: UdpTransportSettings.MaxMulticastRetransmitCount
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxMulticastRetransmitCount
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "Gets or sets a value that specifies the maximum number of times a multicast message should be retransmitted (In addition to the first send)."
  remarks: "The default value is 2."
  syntax:
    content: public int MaxMulticastRetransmitCount { get; set; }
    return:
      type: System.Int32
      description: "The maximum number of times a multicast message is retransmitted."
  overload: System.ServiceModel.Discovery.UdpTransportSettings.MaxMulticastRetransmitCount*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxPendingMessageCount
  id: MaxPendingMessageCount
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: MaxPendingMessageCount
  nameWithType: UdpTransportSettings.MaxPendingMessageCount
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxPendingMessageCount
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "Gets or sets a value that specifies the maximum number of messages that have been received but not yet removed from the input queue for an individual channel instance."
  remarks: "If the input queue has reached its pending message count limit, the message is dropped. The default value is 32."
  syntax:
    content: public int MaxPendingMessageCount { get; set; }
    return:
      type: System.Int32
      description: "The number of messages."
  overload: System.ServiceModel.Discovery.UdpTransportSettings.MaxPendingMessageCount*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize
  id: MaxReceivedMessageSize
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: MaxReceivedMessageSize
  nameWithType: UdpTransportSettings.MaxReceivedMessageSize
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "Gets or sets the maximum size, in bytes, of a message that can be processed by the binding."
  remarks: "The default value is 65507."
  syntax:
    content: public long MaxReceivedMessageSize { get; set; }
    return:
      type: System.Int64
      description: "The maximum size of a message."
  overload: System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxUnicastRetransmitCount
  id: MaxUnicastRetransmitCount
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: MaxUnicastRetransmitCount
  nameWithType: UdpTransportSettings.MaxUnicastRetransmitCount
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxUnicastRetransmitCount
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "Gets or sets a value that specifies the maximum number of times a unicast message should be retransmitted (in addition to the first send)."
  remarks: "The default value is 1."
  syntax:
    content: public int MaxUnicastRetransmitCount { get; set; }
    return:
      type: System.Int32
      description: "The maximum number of times a unicast message is retransmitted."
  overload: System.ServiceModel.Discovery.UdpTransportSettings.MaxUnicastRetransmitCount*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MulticastInterfaceId
  id: MulticastInterfaceId
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: MulticastInterfaceId
  nameWithType: UdpTransportSettings.MulticastInterfaceId
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MulticastInterfaceId
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "Gets or sets a value that uniquely identifies the network adapter that is used when sending and receiving multicast messages."
  remarks: "At runtime, the transport uses this value to look up the interface index, which is then used to set the `IP_MULTICAST_IF` and `IPV6_MULTICAST_IF` socket options. The same interface index is used when joining a multicast group. The default value is `null`."
  syntax:
    content: public string MulticastInterfaceId { get; set; }
    return:
      type: System.String
      description: "The network adapter identifier."
  overload: System.ServiceModel.Discovery.UdpTransportSettings.MulticastInterfaceId*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Discovery.UdpTransportSettings.SocketReceiveBufferSize
  id: SocketReceiveBufferSize
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: SocketReceiveBufferSize
  nameWithType: UdpTransportSettings.SocketReceiveBufferSize
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.SocketReceiveBufferSize
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "Gets or sets the receive buffer size on the underlying WinSock socket."
  remarks: "A user of a receiving channel can use this value on the binding to control how the system behaves when it receives data. For example, given an application that is accessing inbound [!INCLUDE[indigo2](~/add/includes/indigo2-md.md)] messages at the maximum threshold, using a higher value would allow messages to stack up in the WinSock buffer while waiting for the application to process them. Using a lower value in the same situation would result in messages getting dropped. This property exposes the underlying WinSock `SO_RCVBUF` socket setting. This property value must be at least the size of <xref:System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize%2A>. Setting it to a value smaller than the <xref:System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize%2A> results in a runtime exception. The default value is 65536."
  syntax:
    content: public int SocketReceiveBufferSize { get; set; }
    return:
      type: System.Int32
      description: "The receive buffer size."
  overload: System.ServiceModel.Discovery.UdpTransportSettings.SocketReceiveBufferSize*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Discovery.UdpTransportSettings.TimeToLive
  id: TimeToLive
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: TimeToLive
  nameWithType: UdpTransportSettings.TimeToLive
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.TimeToLive
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "Gets or sets a value that specifies the number of network segment hops that a multicast packet can traverse."
  remarks: "This property exposes the functionality associated with the `IP_MULTICAST_TTL` and `IP_TTL` socket options. The default value is 1."
  syntax:
    content: public int TimeToLive { get; set; }
    return:
      type: System.Int32
      description: "The number of network segment hops."
  overload: System.ServiceModel.Discovery.UdpTransportSettings.TimeToLive*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.Discovery.UdpTransportSettings.DuplicateMessageHistoryLength
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: DuplicateMessageHistoryLength
  nameWithType: UdpTransportSettings.DuplicateMessageHistoryLength
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.DuplicateMessageHistoryLength
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxBufferPoolSize
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxBufferPoolSize
  nameWithType: UdpTransportSettings.MaxBufferPoolSize
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxBufferPoolSize
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxMulticastRetransmitCount
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxMulticastRetransmitCount
  nameWithType: UdpTransportSettings.MaxMulticastRetransmitCount
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxMulticastRetransmitCount
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxPendingMessageCount
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxPendingMessageCount
  nameWithType: UdpTransportSettings.MaxPendingMessageCount
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxPendingMessageCount
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxReceivedMessageSize
  nameWithType: UdpTransportSettings.MaxReceivedMessageSize
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxUnicastRetransmitCount
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxUnicastRetransmitCount
  nameWithType: UdpTransportSettings.MaxUnicastRetransmitCount
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxUnicastRetransmitCount
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MulticastInterfaceId
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MulticastInterfaceId
  nameWithType: UdpTransportSettings.MulticastInterfaceId
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MulticastInterfaceId
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Discovery.UdpTransportSettings.SocketReceiveBufferSize
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: SocketReceiveBufferSize
  nameWithType: UdpTransportSettings.SocketReceiveBufferSize
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.SocketReceiveBufferSize
- uid: System.ServiceModel.Discovery.UdpTransportSettings.TimeToLive
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: TimeToLive
  nameWithType: UdpTransportSettings.TimeToLive
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.TimeToLive
- uid: System.ServiceModel.Discovery.UdpTransportSettings.DuplicateMessageHistoryLength*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: DuplicateMessageHistoryLength
  nameWithType: UdpTransportSettings.DuplicateMessageHistoryLength
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxBufferPoolSize*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxBufferPoolSize
  nameWithType: UdpTransportSettings.MaxBufferPoolSize
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxMulticastRetransmitCount*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxMulticastRetransmitCount
  nameWithType: UdpTransportSettings.MaxMulticastRetransmitCount
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxPendingMessageCount*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxPendingMessageCount
  nameWithType: UdpTransportSettings.MaxPendingMessageCount
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxReceivedMessageSize
  nameWithType: UdpTransportSettings.MaxReceivedMessageSize
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxUnicastRetransmitCount*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxUnicastRetransmitCount
  nameWithType: UdpTransportSettings.MaxUnicastRetransmitCount
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MulticastInterfaceId*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MulticastInterfaceId
  nameWithType: UdpTransportSettings.MulticastInterfaceId
- uid: System.ServiceModel.Discovery.UdpTransportSettings.SocketReceiveBufferSize*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: SocketReceiveBufferSize
  nameWithType: UdpTransportSettings.SocketReceiveBufferSize
- uid: System.ServiceModel.Discovery.UdpTransportSettings.TimeToLive*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: TimeToLive
  nameWithType: UdpTransportSettings.TimeToLive
