### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.SendSettings
  id: SendSettings
  children:
  - System.ServiceModel.Activities.SendSettings.#ctor
  - System.ServiceModel.Activities.SendSettings.Endpoint
  - System.ServiceModel.Activities.SendSettings.EndpointAddress
  - System.ServiceModel.Activities.SendSettings.EndpointConfigurationName
  - System.ServiceModel.Activities.SendSettings.IsOneWay
  - System.ServiceModel.Activities.SendSettings.OwnerDisplayName
  - System.ServiceModel.Activities.SendSettings.ProtectionLevel
  - System.ServiceModel.Activities.SendSettings.RequirePersistBeforeSend
  - System.ServiceModel.Activities.SendSettings.TokenImpersonationLevel
  langs:
  - csharp
  name: SendSettings
  nameWithType: SendSettings
  fullName: System.ServiceModel.Activities.SendSettings
  type: Class
  summary: "Represents the settings for an activity that sends a message."
  syntax:
    content: public sealed class SendSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.SendSettings.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.SendSettings
  langs:
  - csharp
  name: SendSettings()
  nameWithType: SendSettings.SendSettings()
  fullName: System.ServiceModel.Activities.SendSettings.SendSettings()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Activities.SendSettings&quot;></see> class."
  syntax:
    content: public SendSettings ();
    parameters: []
  overload: System.ServiceModel.Activities.SendSettings.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.SendSettings.Endpoint
  id: Endpoint
  parent: System.ServiceModel.Activities.SendSettings
  langs:
  - csharp
  name: Endpoint
  nameWithType: SendSettings.Endpoint
  fullName: System.ServiceModel.Activities.SendSettings.Endpoint
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Gets or sets the endpoint to send messages to."
  syntax:
    content: public System.ServiceModel.Endpoint Endpoint { get; set; }
    return:
      type: System.ServiceModel.Endpoint
      description: "The endpoint to send messages to."
  overload: System.ServiceModel.Activities.SendSettings.Endpoint*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.SendSettings.EndpointAddress
  id: EndpointAddress
  parent: System.ServiceModel.Activities.SendSettings
  langs:
  - csharp
  name: EndpointAddress
  nameWithType: SendSettings.EndpointAddress
  fullName: System.ServiceModel.Activities.SendSettings.EndpointAddress
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Gets or sets the address of the endpoint to send messages to."
  syntax:
    content: public Uri EndpointAddress { get; set; }
    return:
      type: System.Uri
      description: "The endpoint address."
  overload: System.ServiceModel.Activities.SendSettings.EndpointAddress*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.SendSettings.EndpointConfigurationName
  id: EndpointConfigurationName
  parent: System.ServiceModel.Activities.SendSettings
  langs:
  - csharp
  name: EndpointConfigurationName
  nameWithType: SendSettings.EndpointConfigurationName
  fullName: System.ServiceModel.Activities.SendSettings.EndpointConfigurationName
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Gets or sets the name of the endpoint configuration."
  syntax:
    content: public string EndpointConfigurationName { get; set; }
    return:
      type: System.String
      description: "The endpoint configuration name."
  overload: System.ServiceModel.Activities.SendSettings.EndpointConfigurationName*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.SendSettings.IsOneWay
  id: IsOneWay
  parent: System.ServiceModel.Activities.SendSettings
  langs:
  - csharp
  name: IsOneWay
  nameWithType: SendSettings.IsOneWay
  fullName: System.ServiceModel.Activities.SendSettings.IsOneWay
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Gets or sets a value that indicates whether communication is one-way."
  syntax:
    content: public bool IsOneWay { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if communication is one-way; <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref> if communication is two-way."
  overload: System.ServiceModel.Activities.SendSettings.IsOneWay*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.SendSettings.OwnerDisplayName
  id: OwnerDisplayName
  parent: System.ServiceModel.Activities.SendSettings
  langs:
  - csharp
  name: OwnerDisplayName
  nameWithType: SendSettings.OwnerDisplayName
  fullName: System.ServiceModel.Activities.SendSettings.OwnerDisplayName
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Gets or sets the display name of the owner."
  syntax:
    content: public string OwnerDisplayName { get; set; }
    return:
      type: System.String
      description: "The display name of the owner."
  overload: System.ServiceModel.Activities.SendSettings.OwnerDisplayName*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.SendSettings.ProtectionLevel
  id: ProtectionLevel
  parent: System.ServiceModel.Activities.SendSettings
  langs:
  - csharp
  name: ProtectionLevel
  nameWithType: SendSettings.ProtectionLevel
  fullName: System.ServiceModel.Activities.SendSettings.ProtectionLevel
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Gets or sets a value that indicates the protection level for the message."
  syntax:
    content: public Nullable<System.Net.Security.ProtectionLevel> ProtectionLevel { get; set; }
    return:
      type: System.Nullable{System.Net.Security.ProtectionLevel}
      description: "One of the enumeration values of the <see cref=&quot;T:System.Net.Security.ProtectionLevel&quot;></see> enumeration."
  overload: System.ServiceModel.Activities.SendSettings.ProtectionLevel*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.SendSettings.RequirePersistBeforeSend
  id: RequirePersistBeforeSend
  parent: System.ServiceModel.Activities.SendSettings
  langs:
  - csharp
  name: RequirePersistBeforeSend
  nameWithType: SendSettings.RequirePersistBeforeSend
  fullName: System.ServiceModel.Activities.SendSettings.RequirePersistBeforeSend
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Gets or sets a value that indicates whether the workflow service instance should be persisted before sending the message."
  syntax:
    content: public bool RequirePersistBeforeSend { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if the workflow service should be persisted before sending the message; otherwise, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>."
  overload: System.ServiceModel.Activities.SendSettings.RequirePersistBeforeSend*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.SendSettings.TokenImpersonationLevel
  id: TokenImpersonationLevel
  parent: System.ServiceModel.Activities.SendSettings
  langs:
  - csharp
  name: TokenImpersonationLevel
  nameWithType: SendSettings.TokenImpersonationLevel
  fullName: System.ServiceModel.Activities.SendSettings.TokenImpersonationLevel
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Gets or sets a value that indicates the token impersonation level allowed for the receiver of the message."
  syntax:
    content: public System.Security.Principal.TokenImpersonationLevel TokenImpersonationLevel { get; set; }
    return:
      type: System.Security.Principal.TokenImpersonationLevel
      description: "One of the enumeration values of the &lt;xref:System.Security.Principal.TokenImpersonationLevel&gt; enumeration."
  overload: System.ServiceModel.Activities.SendSettings.TokenImpersonationLevel*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.Activities.SendSettings.#ctor
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: SendSettings()
  nameWithType: SendSettings.SendSettings()
  fullName: System.ServiceModel.Activities.SendSettings.SendSettings()
- uid: System.ServiceModel.Activities.SendSettings.Endpoint
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: Endpoint
  nameWithType: SendSettings.Endpoint
  fullName: System.ServiceModel.Activities.SendSettings.Endpoint
- uid: System.ServiceModel.Endpoint
  parent: System.ServiceModel
  isExternal: false
  name: Endpoint
  nameWithType: Endpoint
  fullName: System.ServiceModel.Endpoint
- uid: System.ServiceModel.Activities.SendSettings.EndpointAddress
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: EndpointAddress
  nameWithType: SendSettings.EndpointAddress
  fullName: System.ServiceModel.Activities.SendSettings.EndpointAddress
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.ServiceModel.Activities.SendSettings.EndpointConfigurationName
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: EndpointConfigurationName
  nameWithType: SendSettings.EndpointConfigurationName
  fullName: System.ServiceModel.Activities.SendSettings.EndpointConfigurationName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Activities.SendSettings.IsOneWay
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: IsOneWay
  nameWithType: SendSettings.IsOneWay
  fullName: System.ServiceModel.Activities.SendSettings.IsOneWay
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Activities.SendSettings.OwnerDisplayName
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: OwnerDisplayName
  nameWithType: SendSettings.OwnerDisplayName
  fullName: System.ServiceModel.Activities.SendSettings.OwnerDisplayName
- uid: System.ServiceModel.Activities.SendSettings.ProtectionLevel
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: ProtectionLevel
  nameWithType: SendSettings.ProtectionLevel
  fullName: System.ServiceModel.Activities.SendSettings.ProtectionLevel
- uid: System.Nullable{System.Net.Security.ProtectionLevel}
  parent: System
  isExternal: true
  name: Nullable<ProtectionLevel>
  nameWithType: Nullable<ProtectionLevel>
  fullName: System.Nullable<System.Net.Security.ProtectionLevel>
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: Nullable<System.Net.Security.ProtectionLevel>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Net.Security.ProtectionLevel
    name: ProtectionLevel
    nameWithType: ProtectionLevel
    fullName: ProtectionLevel
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.ServiceModel.Activities.SendSettings.RequirePersistBeforeSend
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: RequirePersistBeforeSend
  nameWithType: SendSettings.RequirePersistBeforeSend
  fullName: System.ServiceModel.Activities.SendSettings.RequirePersistBeforeSend
- uid: System.ServiceModel.Activities.SendSettings.TokenImpersonationLevel
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: TokenImpersonationLevel
  nameWithType: SendSettings.TokenImpersonationLevel
  fullName: System.ServiceModel.Activities.SendSettings.TokenImpersonationLevel
- uid: System.Security.Principal.TokenImpersonationLevel
  parent: System.Security.Principal
  isExternal: true
  name: TokenImpersonationLevel
  nameWithType: TokenImpersonationLevel
  fullName: System.Security.Principal.TokenImpersonationLevel
- uid: System.ServiceModel.Activities.SendSettings.#ctor*
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: SendSettings
  nameWithType: SendSettings.SendSettings
- uid: System.ServiceModel.Activities.SendSettings.Endpoint*
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: Endpoint
  nameWithType: SendSettings.Endpoint
- uid: System.ServiceModel.Activities.SendSettings.EndpointAddress*
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: EndpointAddress
  nameWithType: SendSettings.EndpointAddress
- uid: System.ServiceModel.Activities.SendSettings.EndpointConfigurationName*
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: EndpointConfigurationName
  nameWithType: SendSettings.EndpointConfigurationName
- uid: System.ServiceModel.Activities.SendSettings.IsOneWay*
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: IsOneWay
  nameWithType: SendSettings.IsOneWay
- uid: System.ServiceModel.Activities.SendSettings.OwnerDisplayName*
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: OwnerDisplayName
  nameWithType: SendSettings.OwnerDisplayName
- uid: System.ServiceModel.Activities.SendSettings.ProtectionLevel*
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: ProtectionLevel
  nameWithType: SendSettings.ProtectionLevel
- uid: System.ServiceModel.Activities.SendSettings.RequirePersistBeforeSend*
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: RequirePersistBeforeSend
  nameWithType: SendSettings.RequirePersistBeforeSend
- uid: System.ServiceModel.Activities.SendSettings.TokenImpersonationLevel*
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: TokenImpersonationLevel
  nameWithType: SendSettings.TokenImpersonationLevel
