### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.DataContractSerializerElement
  id: DataContractSerializerElement
  children:
  - System.ServiceModel.Configuration.DataContractSerializerElement.#ctor
  - System.ServiceModel.Configuration.DataContractSerializerElement.BehaviorType
  - System.ServiceModel.Configuration.DataContractSerializerElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.DataContractSerializerElement.CreateBehavior
  - System.ServiceModel.Configuration.DataContractSerializerElement.IgnoreExtensionDataObject
  - System.ServiceModel.Configuration.DataContractSerializerElement.MaxItemsInObjectGraph
  - System.ServiceModel.Configuration.DataContractSerializerElement.Properties
  langs:
  - csharp
  name: DataContractSerializerElement
  nameWithType: DataContractSerializerElement
  fullName: System.ServiceModel.Configuration.DataContractSerializerElement
  type: Class
  summary: "Represents a configuration element that specifies the &lt;xref:System.Runtime.Serialization.DataContractSerializer&gt; to be used. This class cannot be inherited."
  syntax:
    content: 'public sealed class DataContractSerializerElement : System.ServiceModel.Configuration.BehaviorExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  - System.ServiceModel.Configuration.BehaviorExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.DataContractSerializerElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.DataContractSerializerElement
  langs:
  - csharp
  name: DataContractSerializerElement()
  nameWithType: DataContractSerializerElement.DataContractSerializerElement()
  fullName: System.ServiceModel.Configuration.DataContractSerializerElement.DataContractSerializerElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.DataContractSerializerElement&quot;></see> class."
  syntax:
    content: public DataContractSerializerElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.DataContractSerializerElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.DataContractSerializerElement.BehaviorType
  id: BehaviorType
  parent: System.ServiceModel.Configuration.DataContractSerializerElement
  langs:
  - csharp
  name: BehaviorType
  nameWithType: DataContractSerializerElement.BehaviorType
  fullName: System.ServiceModel.Configuration.DataContractSerializerElement.BehaviorType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets the type of this behavior element."
  syntax:
    content: public override Type BehaviorType { get; }
    return:
      type: System.Type
      description: "The type of the behavior element."
  overload: System.ServiceModel.Configuration.DataContractSerializerElement.BehaviorType*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.DataContractSerializerElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  id: CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.DataContractSerializerElement
  langs:
  - csharp
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: DataContractSerializerElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.DataContractSerializerElement.CopyFrom(ServiceModelExtensionElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Copies the values from the specified configuration element to this configuration element."
  syntax:
    content: public override void CopyFrom (System.ServiceModel.Configuration.ServiceModelExtensionElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.ServiceModelExtensionElement
      description: "The configuration element to be copied from."
  overload: System.ServiceModel.Configuration.DataContractSerializerElement.CopyFrom*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.DataContractSerializerElement.CreateBehavior
  id: CreateBehavior
  parent: System.ServiceModel.Configuration.DataContractSerializerElement
  langs:
  - csharp
  name: CreateBehavior()
  nameWithType: DataContractSerializerElement.CreateBehavior()
  fullName: System.ServiceModel.Configuration.DataContractSerializerElement.CreateBehavior()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override object CreateBehavior ();
    parameters: []
    return:
      type: System.Object
      description: "To be added."
  overload: System.ServiceModel.Configuration.DataContractSerializerElement.CreateBehavior*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.DataContractSerializerElement.IgnoreExtensionDataObject
  id: IgnoreExtensionDataObject
  parent: System.ServiceModel.Configuration.DataContractSerializerElement
  langs:
  - csharp
  name: IgnoreExtensionDataObject
  nameWithType: DataContractSerializerElement.IgnoreExtensionDataObject
  fullName: System.ServiceModel.Configuration.DataContractSerializerElement.IgnoreExtensionDataObject
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets a value that specifies whether to ignore data supplied by an extension of the class, when the class is being serialized or deserialized."
  syntax:
    content: public bool IgnoreExtensionDataObject { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> to omit the extension data; otherwise, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>."
  overload: System.ServiceModel.Configuration.DataContractSerializerElement.IgnoreExtensionDataObject*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.DataContractSerializerElement.MaxItemsInObjectGraph
  id: MaxItemsInObjectGraph
  parent: System.ServiceModel.Configuration.DataContractSerializerElement
  langs:
  - csharp
  name: MaxItemsInObjectGraph
  nameWithType: DataContractSerializerElement.MaxItemsInObjectGraph
  fullName: System.ServiceModel.Configuration.DataContractSerializerElement.MaxItemsInObjectGraph
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets the maximum number of items to serialize or deserialize."
  syntax:
    content: public int MaxItemsInObjectGraph { get; set; }
    return:
      type: System.Int32
      description: "The maximum number of items to serialize or deserialize. The default is 65536."
  overload: System.ServiceModel.Configuration.DataContractSerializerElement.MaxItemsInObjectGraph*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.DataContractSerializerElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.DataContractSerializerElement
  langs:
  - csharp
  name: Properties
  nameWithType: DataContractSerializerElement.Properties
  fullName: System.ServiceModel.Configuration.DataContractSerializerElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.DataContractSerializerElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.BehaviorExtensionElement
  isExternal: false
  name: System.ServiceModel.Configuration.BehaviorExtensionElement
- uid: System.ServiceModel.Configuration.DataContractSerializerElement.#ctor
  parent: System.ServiceModel.Configuration.DataContractSerializerElement
  isExternal: false
  name: DataContractSerializerElement()
  nameWithType: DataContractSerializerElement.DataContractSerializerElement()
  fullName: System.ServiceModel.Configuration.DataContractSerializerElement.DataContractSerializerElement()
- uid: System.ServiceModel.Configuration.DataContractSerializerElement.BehaviorType
  parent: System.ServiceModel.Configuration.DataContractSerializerElement
  isExternal: false
  name: BehaviorType
  nameWithType: DataContractSerializerElement.BehaviorType
  fullName: System.ServiceModel.Configuration.DataContractSerializerElement.BehaviorType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.DataContractSerializerElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.DataContractSerializerElement
  isExternal: false
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: DataContractSerializerElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.DataContractSerializerElement.CopyFrom(ServiceModelExtensionElement)
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelExtensionElement
  nameWithType: ServiceModelExtensionElement
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement
- uid: System.ServiceModel.Configuration.DataContractSerializerElement.CreateBehavior
  parent: System.ServiceModel.Configuration.DataContractSerializerElement
  isExternal: false
  name: CreateBehavior()
  nameWithType: DataContractSerializerElement.CreateBehavior()
  fullName: System.ServiceModel.Configuration.DataContractSerializerElement.CreateBehavior()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Configuration.DataContractSerializerElement.IgnoreExtensionDataObject
  parent: System.ServiceModel.Configuration.DataContractSerializerElement
  isExternal: false
  name: IgnoreExtensionDataObject
  nameWithType: DataContractSerializerElement.IgnoreExtensionDataObject
  fullName: System.ServiceModel.Configuration.DataContractSerializerElement.IgnoreExtensionDataObject
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.DataContractSerializerElement.MaxItemsInObjectGraph
  parent: System.ServiceModel.Configuration.DataContractSerializerElement
  isExternal: false
  name: MaxItemsInObjectGraph
  nameWithType: DataContractSerializerElement.MaxItemsInObjectGraph
  fullName: System.ServiceModel.Configuration.DataContractSerializerElement.MaxItemsInObjectGraph
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Configuration.DataContractSerializerElement.Properties
  parent: System.ServiceModel.Configuration.DataContractSerializerElement
  isExternal: false
  name: Properties
  nameWithType: DataContractSerializerElement.Properties
  fullName: System.ServiceModel.Configuration.DataContractSerializerElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.DataContractSerializerElement.#ctor*
  parent: System.ServiceModel.Configuration.DataContractSerializerElement
  isExternal: false
  name: DataContractSerializerElement
  nameWithType: DataContractSerializerElement.DataContractSerializerElement
- uid: System.ServiceModel.Configuration.DataContractSerializerElement.BehaviorType*
  parent: System.ServiceModel.Configuration.DataContractSerializerElement
  isExternal: false
  name: BehaviorType
  nameWithType: DataContractSerializerElement.BehaviorType
- uid: System.ServiceModel.Configuration.DataContractSerializerElement.CopyFrom*
  parent: System.ServiceModel.Configuration.DataContractSerializerElement
  isExternal: false
  name: CopyFrom
  nameWithType: DataContractSerializerElement.CopyFrom
- uid: System.ServiceModel.Configuration.DataContractSerializerElement.CreateBehavior*
  parent: System.ServiceModel.Configuration.DataContractSerializerElement
  isExternal: false
  name: CreateBehavior
  nameWithType: DataContractSerializerElement.CreateBehavior
- uid: System.ServiceModel.Configuration.DataContractSerializerElement.IgnoreExtensionDataObject*
  parent: System.ServiceModel.Configuration.DataContractSerializerElement
  isExternal: false
  name: IgnoreExtensionDataObject
  nameWithType: DataContractSerializerElement.IgnoreExtensionDataObject
- uid: System.ServiceModel.Configuration.DataContractSerializerElement.MaxItemsInObjectGraph*
  parent: System.ServiceModel.Configuration.DataContractSerializerElement
  isExternal: false
  name: MaxItemsInObjectGraph
  nameWithType: DataContractSerializerElement.MaxItemsInObjectGraph
- uid: System.ServiceModel.Configuration.DataContractSerializerElement.Properties*
  parent: System.ServiceModel.Configuration.DataContractSerializerElement
  isExternal: false
  name: Properties
  nameWithType: DataContractSerializerElement.Properties
