### YamlMime:ManagedReference
items:
- uid: System.Configuration.IntegerValidatorAttribute
  id: IntegerValidatorAttribute
  children:
  - System.Configuration.IntegerValidatorAttribute.#ctor
  - System.Configuration.IntegerValidatorAttribute.ExcludeRange
  - System.Configuration.IntegerValidatorAttribute.MaxValue
  - System.Configuration.IntegerValidatorAttribute.MinValue
  - System.Configuration.IntegerValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: IntegerValidatorAttribute
  nameWithType: IntegerValidatorAttribute
  fullName: System.Configuration.IntegerValidatorAttribute
  type: Class
  summary: "Declaratively instructs the .NET Framework to perform integer validation on a configuration property. This class cannot be inherited."
  remarks: "You use the IntegerValidatorAttribute attribute to decorate a configuration property, which will instruct the .NET Framework to validate the property using the <xref:System.Configuration.IntegerValidator> object and pass to it the value of the decorating parameters.       You can apply IntegerValidatorAttribute attributes to property types only."
  example:
  - "The following example shows how to decorate the properties of a custom <xref:System.Configuration.ConfigurationSection> object using the IntegerValidatorAttribute attribute.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#6](~/add/codesnippet/VisualBasic/t-system.configuration.i_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#6](~/add/codesnippet/CSharp/t-system.configuration.i_0_1.cs)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class IntegerValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.IntegerValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.IntegerValidatorAttribute
  langs:
  - csharp
  name: IntegerValidatorAttribute()
  nameWithType: IntegerValidatorAttribute.IntegerValidatorAttribute()
  fullName: System.Configuration.IntegerValidatorAttribute.IntegerValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Creates a new instance of the <see cref=&quot;T:System.Configuration.IntegerValidatorAttribute&quot;></see> class."
  remarks: "You use this constructor in the attributed model to assure that the value assigned to the related property is an integer."
  example:
  - "The following example shows how to use the IntegerValidatorAttribute constructor.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#5](~/add/codesnippet/VisualBasic/m-system.configuration.i_2_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#5](~/add/codesnippet/CSharp/m-system.configuration.i_2_1.cs)]"
  syntax:
    content: public IntegerValidatorAttribute ();
    parameters: []
  overload: System.Configuration.IntegerValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.IntegerValidatorAttribute.ExcludeRange
  id: ExcludeRange
  parent: System.Configuration.IntegerValidatorAttribute
  langs:
  - csharp
  name: ExcludeRange
  nameWithType: IntegerValidatorAttribute.ExcludeRange
  fullName: System.Configuration.IntegerValidatorAttribute.ExcludeRange
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets or sets a value that indicates whether to include or exclude the integers in the range defined by the &lt;xref:System.Configuration.IntegerValidatorAttribute.MinValue%2A&gt; and &lt;xref:System.Configuration.IntegerValidatorAttribute.MaxValue%2A&gt; property values."
  remarks: "The range is inclusive of the <xref:System.Configuration.IntegerValidatorAttribute.MinValue%2A> and <xref:System.Configuration.IntegerValidatorAttribute.MaxValue%2A> property values. When the ExcludeRange property value is `true`, the allowed values are outside the range."
  example:
  - "The following example shows how to use the ExcludeRange property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#6](~/add/codesnippet/VisualBasic/p-system.configuration.i_6_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#6](~/add/codesnippet/CSharp/p-system.configuration.i_6_1.cs)]"
  syntax:
    content: public bool ExcludeRange { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if the value must be excluded; otherwise, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>. The default is <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>."
  overload: System.Configuration.IntegerValidatorAttribute.ExcludeRange*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.IntegerValidatorAttribute.MaxValue
  id: MaxValue
  parent: System.Configuration.IntegerValidatorAttribute
  langs:
  - csharp
  name: MaxValue
  nameWithType: IntegerValidatorAttribute.MaxValue
  fullName: System.Configuration.IntegerValidatorAttribute.MaxValue
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets or sets the maximum value allowed for the property."
  remarks: "The MaxValue property value is included in the allowed range."
  example:
  - "The following example shows how to use the MaxValue property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#6](~/add/codesnippet/VisualBasic/p-system.configuration.i_3_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#6](~/add/codesnippet/CSharp/p-system.configuration.i_3_1.cs)]"
  syntax:
    content: public int MaxValue { get; set; }
    return:
      type: System.Int32
      description: "An integer that indicates the allowed maximum value."
  overload: System.Configuration.IntegerValidatorAttribute.MaxValue*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "The selected value is less than <xref:System.Configuration.IntegerValidatorAttribute.MinValue%2A>."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.IntegerValidatorAttribute.MinValue
  id: MinValue
  parent: System.Configuration.IntegerValidatorAttribute
  langs:
  - csharp
  name: MinValue
  nameWithType: IntegerValidatorAttribute.MinValue
  fullName: System.Configuration.IntegerValidatorAttribute.MinValue
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets or sets the minimum value allowed for the property."
  remarks: "The MinValue property value is included in the allowed range."
  example:
  - "The following example shows how to use the MinValue property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#6](~/add/codesnippet/VisualBasic/p-system.configuration.i_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#6](~/add/codesnippet/CSharp/p-system.configuration.i_0_1.cs)]"
  syntax:
    content: public int MinValue { get; set; }
    return:
      type: System.Int32
      description: "An integer that indicates the allowed minimum value."
  overload: System.Configuration.IntegerValidatorAttribute.MinValue*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "The selected value is greater than <xref:System.Configuration.IntegerValidatorAttribute.MaxValue%2A>."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.IntegerValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.IntegerValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: IntegerValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.IntegerValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets an instance of the <see cref=&quot;T:System.Configuration.IntegerValidator&quot;></see> class."
  remarks: "You use the ValidatorInstance property to perform string validation by calling its <xref:System.Configuration.IntegerValidator.Validate%2A> method."
  example:
  - "The following example shows how to use the ValidatorInstance property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#13](~/add/codesnippet/VisualBasic/p-system.configuration.i_2_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#13](~/add/codesnippet/CSharp/p-system.configuration.i_2_1.cs)]"
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "The <see cref=&quot;T:System.Configuration.ConfigurationValidatorBase&quot;></see> validator instance."
  overload: System.Configuration.IntegerValidatorAttribute.ValidatorInstance*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.Configuration.IntegerValidatorAttribute.#ctor
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: IntegerValidatorAttribute()
  nameWithType: IntegerValidatorAttribute.IntegerValidatorAttribute()
  fullName: System.Configuration.IntegerValidatorAttribute.IntegerValidatorAttribute()
- uid: System.Configuration.IntegerValidatorAttribute.ExcludeRange
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: ExcludeRange
  nameWithType: IntegerValidatorAttribute.ExcludeRange
  fullName: System.Configuration.IntegerValidatorAttribute.ExcludeRange
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.IntegerValidatorAttribute.MaxValue
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: MaxValue
  nameWithType: IntegerValidatorAttribute.MaxValue
  fullName: System.Configuration.IntegerValidatorAttribute.MaxValue
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.IntegerValidatorAttribute.MinValue
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: MinValue
  nameWithType: IntegerValidatorAttribute.MinValue
  fullName: System.Configuration.IntegerValidatorAttribute.MinValue
- uid: System.Configuration.IntegerValidatorAttribute.ValidatorInstance
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: IntegerValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.IntegerValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.IntegerValidatorAttribute.#ctor*
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: IntegerValidatorAttribute
  nameWithType: IntegerValidatorAttribute.IntegerValidatorAttribute
- uid: System.Configuration.IntegerValidatorAttribute.ExcludeRange*
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: ExcludeRange
  nameWithType: IntegerValidatorAttribute.ExcludeRange
- uid: System.Configuration.IntegerValidatorAttribute.MaxValue*
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: MaxValue
  nameWithType: IntegerValidatorAttribute.MaxValue
- uid: System.Configuration.IntegerValidatorAttribute.MinValue*
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: MinValue
  nameWithType: IntegerValidatorAttribute.MinValue
- uid: System.Configuration.IntegerValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.IntegerValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: IntegerValidatorAttribute.ValidatorInstance
