### YamlMime:ManagedReference
items:
- uid: System.Web.ClientServices.Providers.SettingsSavedEventArgs
  id: SettingsSavedEventArgs
  children:
  - System.Web.ClientServices.Providers.SettingsSavedEventArgs.#ctor(System.Collections.Generic.IEnumerable{System.String})
  - System.Web.ClientServices.Providers.SettingsSavedEventArgs.FailedSettingsList
  langs:
  - csharp
  name: SettingsSavedEventArgs
  nameWithType: SettingsSavedEventArgs
  fullName: System.Web.ClientServices.Providers.SettingsSavedEventArgs
  type: Class
  summary: "Provides data for the <see cref=&quot;E:System.Web.ClientServices.Providers.ClientSettingsProvider.SettingsSaved&quot;></see> event."
  remarks: "The <xref:System.Web.ClientServices.Providers.ClientSettingsProvider.SettingsSaved?displayProperty=fullName> event occurs after the settings provider accesses the settings service, even if the settings were not successfully saved. One reason that the provider might fail to save the settings is if the current user has been logged out. You can use the <xref:System.Web.ClientServices.Providers.SettingsSavedEventArgs.FailedSettingsList%2A> property to determine whether any settings were not successfully saved.       This event does not occur if the settings provider cannot access the settings service, which instead causes the provider to throw a <xref:System.Net.WebException>.       For more information about handling events, see [NIB: Consuming Events](http://msdn.microsoft.com/en-us/01e4f1bc-e55e-413f-98c7-6588493e5f67)."
  example:
  - "The following example code demonstrates how to use this class to display a list of settings that were not successfully saved.  \n  \n [!code-vb[ClientApplicationServices#304](~/add/codesnippet/VisualBasic/ClientAppServicesDemo/Class1.vb#304)]\n [!code-cs[ClientApplicationServices#304](~/add/codesnippet/CSharp/ClientAppServicesDemo/Class1.cs#304)]"
  syntax:
    content: 'public class SettingsSavedEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.ClientServices.Providers.SettingsSavedEventArgs.#ctor(System.Collections.Generic.IEnumerable{System.String})
  id: '#ctor(System.Collections.Generic.IEnumerable{System.String})'
  parent: System.Web.ClientServices.Providers.SettingsSavedEventArgs
  langs:
  - csharp
  name: SettingsSavedEventArgs(IEnumerable<String>)
  nameWithType: SettingsSavedEventArgs.SettingsSavedEventArgs(IEnumerable<String>)
  fullName: System.Web.ClientServices.Providers.SettingsSavedEventArgs.SettingsSavedEventArgs(IEnumerable<String>)
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ClientServices.Providers
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Web.ClientServices.Providers.SettingsSavedEventArgs&quot;></see> class."
  syntax:
    content: public SettingsSavedEventArgs (System.Collections.Generic.IEnumerable<string> failedSettingsList);
    parameters:
    - id: failedSettingsList
      type: System.Collections.Generic.IEnumerable{System.String}
      description: "The settings that the settings provider was unable to save."
  overload: System.Web.ClientServices.Providers.SettingsSavedEventArgs.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.ClientServices.Providers.SettingsSavedEventArgs.FailedSettingsList
  id: FailedSettingsList
  parent: System.Web.ClientServices.Providers.SettingsSavedEventArgs
  langs:
  - csharp
  name: FailedSettingsList
  nameWithType: SettingsSavedEventArgs.FailedSettingsList
  fullName: System.Web.ClientServices.Providers.SettingsSavedEventArgs.FailedSettingsList
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ClientServices.Providers
  summary: "Gets the settings that the <see cref=&quot;T:System.Web.ClientServices.Providers.ClientSettingsProvider&quot;></see> was unable to save to the server."
  remarks: "One reason that the provider might fail to save the settings is if the current user has been logged out. You can use the FailedSettingsList property to determine whether any settings were not successfully saved."
  example:
  - "The following example code demonstrates how to use this property to display a list of settings that were not successfully saved.  \n  \n [!code-vb[ClientApplicationServices#304](~/add/codesnippet/VisualBasic/ClientAppServicesDemo/Class1.vb#304)]\n [!code-cs[ClientApplicationServices#304](~/add/codesnippet/CSharp/ClientAppServicesDemo/Class1.cs#304)]"
  syntax:
    content: public System.Collections.ObjectModel.ReadOnlyCollection<string> FailedSettingsList { get; }
    return:
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: "The settings that were not saved."
  overload: System.Web.ClientServices.Providers.SettingsSavedEventArgs.FailedSettingsList*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Web.ClientServices.Providers.SettingsSavedEventArgs.#ctor(System.Collections.Generic.IEnumerable{System.String})
  parent: System.Web.ClientServices.Providers.SettingsSavedEventArgs
  isExternal: false
  name: SettingsSavedEventArgs(IEnumerable<String>)
  nameWithType: SettingsSavedEventArgs.SettingsSavedEventArgs(IEnumerable<String>)
  fullName: System.Web.ClientServices.Providers.SettingsSavedEventArgs.SettingsSavedEventArgs(IEnumerable<String>)
- uid: System.Collections.Generic.IEnumerable{System.String}
  parent: System.Collections.Generic
  isExternal: true
  name: IEnumerable<String>
  nameWithType: IEnumerable<String>
  fullName: System.Collections.Generic.IEnumerable<System.String>
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: IEnumerable<System.String>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Web.ClientServices.Providers.SettingsSavedEventArgs.FailedSettingsList
  parent: System.Web.ClientServices.Providers.SettingsSavedEventArgs
  isExternal: false
  name: FailedSettingsList
  nameWithType: SettingsSavedEventArgs.FailedSettingsList
  fullName: System.Web.ClientServices.Providers.SettingsSavedEventArgs.FailedSettingsList
- uid: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
  parent: System.Collections.ObjectModel
  isExternal: true
  name: ReadOnlyCollection<String>
  nameWithType: ReadOnlyCollection<String>
  fullName: System.Collections.ObjectModel.ReadOnlyCollection<System.String>
  spec.csharp:
  - uid: System.Collections.ObjectModel.ReadOnlyCollection`1
    name: ReadOnlyCollection
    nameWithType: ReadOnlyCollection
    fullName: ReadOnlyCollection<System.String>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Web.ClientServices.Providers.SettingsSavedEventArgs.#ctor*
  parent: System.Web.ClientServices.Providers.SettingsSavedEventArgs
  isExternal: false
  name: SettingsSavedEventArgs
  nameWithType: SettingsSavedEventArgs.SettingsSavedEventArgs
- uid: System.Web.ClientServices.Providers.SettingsSavedEventArgs.FailedSettingsList*
  parent: System.Web.ClientServices.Providers.SettingsSavedEventArgs
  isExternal: false
  name: FailedSettingsList
  nameWithType: SettingsSavedEventArgs.FailedSettingsList
