### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.HttpWebRequestElement
  id: HttpWebRequestElement
  children:
  - System.Net.Configuration.HttpWebRequestElement.#ctor
  - System.Net.Configuration.HttpWebRequestElement.MaximumErrorResponseLength
  - System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength
  - System.Net.Configuration.HttpWebRequestElement.MaximumUnauthorizedUploadLength
  - System.Net.Configuration.HttpWebRequestElement.PostDeserialize
  - System.Net.Configuration.HttpWebRequestElement.Properties
  - System.Net.Configuration.HttpWebRequestElement.UseUnsafeHeaderParsing
  langs:
  - csharp
  name: HttpWebRequestElement
  nameWithType: HttpWebRequestElement
  fullName: System.Net.Configuration.HttpWebRequestElement
  type: Class
  summary: "Represents the maximum length for response headers. This class cannot be inherited."
  remarks: "This class corresponds to the `maximumResponseHeadersLength` attribute of the [\\<httpWebRequest> Element (Network Settings)](../Topic/%3ChttpWebRequest%3E%20Element%20\\(Network%20Settings\\).md) configuration element.  \n  \n The information in this class applies to responses to requests made with the <xref:System.Net.WebRequest> and <xref:System.Net.WebClient> classes.  \n  \n This class provides programmatic access to information that can be stored in configuration files."
  syntax:
    content: 'public sealed class HttpWebRequestElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.HttpWebRequestElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.HttpWebRequestElement
  langs:
  - csharp
  name: HttpWebRequestElement()
  nameWithType: HttpWebRequestElement.HttpWebRequestElement()
  fullName: System.Net.Configuration.HttpWebRequestElement.HttpWebRequestElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Net.Configuration.HttpWebRequestElement&quot;></see> class."
  remarks: "This constructor adds a <xref:System.Configuration.ConfigurationProperty> object that represents the <xref:System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength%2A> to the <xref:System.Configuration.ConfigurationElement.Properties%2A> collection."
  syntax:
    content: public HttpWebRequestElement ();
    parameters: []
  overload: System.Net.Configuration.HttpWebRequestElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumErrorResponseLength
  id: MaximumErrorResponseLength
  parent: System.Net.Configuration.HttpWebRequestElement
  langs:
  - csharp
  name: MaximumErrorResponseLength
  nameWithType: HttpWebRequestElement.MaximumErrorResponseLength
  fullName: System.Net.Configuration.HttpWebRequestElement.MaximumErrorResponseLength
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Gets or sets the maximum allowed length of an error response."
  syntax:
    content: public int MaximumErrorResponseLength { get; set; }
    return:
      type: System.Int32
      description: "A 32-bit signed integer containing the maximum length in kilobytes (1024 bytes) of the error response. The default value is 64."
  overload: System.Net.Configuration.HttpWebRequestElement.MaximumErrorResponseLength*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength
  id: MaximumResponseHeadersLength
  parent: System.Net.Configuration.HttpWebRequestElement
  langs:
  - csharp
  name: MaximumResponseHeadersLength
  nameWithType: HttpWebRequestElement.MaximumResponseHeadersLength
  fullName: System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Gets or sets the maximum allowed length of the response headers."
  remarks: "The length is measured in kilobytes (1024 bytes) and it includes the response status line and the response headers, as well as all extra control characters received as part of the HTTP protocol.       A value of -1 means no limit is imposed on the response headers; a value of 0 means that all requests will fail."
  syntax:
    content: public int MaximumResponseHeadersLength { get; set; }
    return:
      type: System.Int32
      description: "A 32-bit signed integer containing the maximum length in kilobytes (1024 bytes) of the response headers. The default value is 64."
  overload: System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumUnauthorizedUploadLength
  id: MaximumUnauthorizedUploadLength
  parent: System.Net.Configuration.HttpWebRequestElement
  langs:
  - csharp
  name: MaximumUnauthorizedUploadLength
  nameWithType: HttpWebRequestElement.MaximumUnauthorizedUploadLength
  fullName: System.Net.Configuration.HttpWebRequestElement.MaximumUnauthorizedUploadLength
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Gets or sets the maximum length of an upload in response to an unauthorized error code."
  syntax:
    content: public int MaximumUnauthorizedUploadLength { get; set; }
    return:
      type: System.Int32
      description: "A 32-bit signed integer containing the maximum length (in multiple of 1,024 byte units) of an upload in response to an unauthorized error code. A value of -1 indicates that no size limit will be imposed on the upload. Setting the MaximumUnauthorizedUploadLength property to any other value will only send the request body if it is smaller than the number of bytes specified. So a value of 1 would indicate to only send the request body if it is smaller than 1,024 bytes.       The default value for this property is -1."
  overload: System.Net.Configuration.HttpWebRequestElement.MaximumUnauthorizedUploadLength*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.HttpWebRequestElement.PostDeserialize
  id: PostDeserialize
  parent: System.Net.Configuration.HttpWebRequestElement
  langs:
  - csharp
  name: PostDeserialize()
  nameWithType: HttpWebRequestElement.PostDeserialize()
  fullName: System.Net.Configuration.HttpWebRequestElement.PostDeserialize()
  type: Method
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override void PostDeserialize ();
    parameters: []
  overload: System.Net.Configuration.HttpWebRequestElement.PostDeserialize*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.HttpWebRequestElement.Properties
  id: Properties
  parent: System.Net.Configuration.HttpWebRequestElement
  langs:
  - csharp
  name: Properties
  nameWithType: HttpWebRequestElement.Properties
  fullName: System.Net.Configuration.HttpWebRequestElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Net.Configuration.HttpWebRequestElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.HttpWebRequestElement.UseUnsafeHeaderParsing
  id: UseUnsafeHeaderParsing
  parent: System.Net.Configuration.HttpWebRequestElement
  langs:
  - csharp
  name: UseUnsafeHeaderParsing
  nameWithType: HttpWebRequestElement.UseUnsafeHeaderParsing
  fullName: System.Net.Configuration.HttpWebRequestElement.UseUnsafeHeaderParsing
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Setting this property ignores validation errors that occur during HTTP parsing."
  remarks: "When this property is set to `false`, the following validations are performed during HTTP parsing:      -   In end-of-line code, use CRLF; using CR or LF alone is not allowed.      -   Headers names should not have spaces in them.      -   If multiple status lines exist, all additional status lines are treated as malformed header name/value pairs.      -   The status line must have a status description, in addition to a status code.      -   Header names cannot have non-ASCII chars in them. This validation is performed whether this property is set to `true` or `false`.       When a protocol violation occurs, a <xref:System.Net.WebException> exception is thrown with the status set to <xref:System.Net.WebExceptionStatus>. If the `UseUnsafeHeaderParsing` property is set to `true`, validation errors are ignored.       Setting this property to `true` has security implications, so it should only be done if backward compatibility with a server is required."
  syntax:
    content: public bool UseUnsafeHeaderParsing { get; set; }
    return:
      type: System.Boolean
      description: "Boolean that indicates whether this property has been set."
  overload: System.Net.Configuration.HttpWebRequestElement.UseUnsafeHeaderParsing*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.HttpWebRequestElement.#ctor
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: HttpWebRequestElement()
  nameWithType: HttpWebRequestElement.HttpWebRequestElement()
  fullName: System.Net.Configuration.HttpWebRequestElement.HttpWebRequestElement()
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumErrorResponseLength
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: MaximumErrorResponseLength
  nameWithType: HttpWebRequestElement.MaximumErrorResponseLength
  fullName: System.Net.Configuration.HttpWebRequestElement.MaximumErrorResponseLength
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: MaximumResponseHeadersLength
  nameWithType: HttpWebRequestElement.MaximumResponseHeadersLength
  fullName: System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumUnauthorizedUploadLength
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: MaximumUnauthorizedUploadLength
  nameWithType: HttpWebRequestElement.MaximumUnauthorizedUploadLength
  fullName: System.Net.Configuration.HttpWebRequestElement.MaximumUnauthorizedUploadLength
- uid: System.Net.Configuration.HttpWebRequestElement.PostDeserialize
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: PostDeserialize()
  nameWithType: HttpWebRequestElement.PostDeserialize()
  fullName: System.Net.Configuration.HttpWebRequestElement.PostDeserialize()
- uid: System.Net.Configuration.HttpWebRequestElement.Properties
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: Properties
  nameWithType: HttpWebRequestElement.Properties
  fullName: System.Net.Configuration.HttpWebRequestElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.HttpWebRequestElement.UseUnsafeHeaderParsing
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: UseUnsafeHeaderParsing
  nameWithType: HttpWebRequestElement.UseUnsafeHeaderParsing
  fullName: System.Net.Configuration.HttpWebRequestElement.UseUnsafeHeaderParsing
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Net.Configuration.HttpWebRequestElement.#ctor*
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: HttpWebRequestElement
  nameWithType: HttpWebRequestElement.HttpWebRequestElement
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumErrorResponseLength*
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: MaximumErrorResponseLength
  nameWithType: HttpWebRequestElement.MaximumErrorResponseLength
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumResponseHeadersLength*
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: MaximumResponseHeadersLength
  nameWithType: HttpWebRequestElement.MaximumResponseHeadersLength
- uid: System.Net.Configuration.HttpWebRequestElement.MaximumUnauthorizedUploadLength*
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: MaximumUnauthorizedUploadLength
  nameWithType: HttpWebRequestElement.MaximumUnauthorizedUploadLength
- uid: System.Net.Configuration.HttpWebRequestElement.PostDeserialize*
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: PostDeserialize
  nameWithType: HttpWebRequestElement.PostDeserialize
- uid: System.Net.Configuration.HttpWebRequestElement.Properties*
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: Properties
  nameWithType: HttpWebRequestElement.Properties
- uid: System.Net.Configuration.HttpWebRequestElement.UseUnsafeHeaderParsing*
  parent: System.Net.Configuration.HttpWebRequestElement
  isExternal: false
  name: UseUnsafeHeaderParsing
  nameWithType: HttpWebRequestElement.UseUnsafeHeaderParsing
