### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.BindingCollectionElement
  id: BindingCollectionElement
  children:
  - System.ServiceModel.Configuration.BindingCollectionElement.#ctor
  - System.ServiceModel.Configuration.BindingCollectionElement.BindingName
  - System.ServiceModel.Configuration.BindingCollectionElement.BindingType
  - System.ServiceModel.Configuration.BindingCollectionElement.ConfiguredBindings
  - System.ServiceModel.Configuration.BindingCollectionElement.ContainsKey(System.String)
  - System.ServiceModel.Configuration.BindingCollectionElement.GetDefault
  - System.ServiceModel.Configuration.BindingCollectionElement.TryAdd(System.String,System.ServiceModel.Channels.Binding,System.Configuration.Configuration)
  langs:
  - csharp
  name: BindingCollectionElement
  nameWithType: BindingCollectionElement
  fullName: System.ServiceModel.Configuration.BindingCollectionElement
  type: Class
  summary: "Represents a configuration section that contains a collection of binding elements, each of which describes an aspect of how an endpoint communicates with other endpoints, that is built, consistently, into a channel factory on the client and a channel listener on the service."
  syntax:
    content: 'public abstract class BindingCollectionElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.BindingCollectionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  langs:
  - csharp
  name: BindingCollectionElement()
  nameWithType: BindingCollectionElement.BindingCollectionElement()
  fullName: System.ServiceModel.Configuration.BindingCollectionElement.BindingCollectionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.BindingCollectionElement&quot;></see> class."
  syntax:
    content: protected BindingCollectionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.BindingCollectionElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.BindingCollectionElement.BindingName
  id: BindingName
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  langs:
  - csharp
  name: BindingName
  nameWithType: BindingCollectionElement.BindingName
  fullName: System.ServiceModel.Configuration.BindingCollectionElement.BindingName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets the name of the binding."
  syntax:
    content: public string BindingName { get; }
    return:
      type: System.String
      description: "The unique name of the binding."
  overload: System.ServiceModel.Configuration.BindingCollectionElement.BindingName*
  exceptions:
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "The current configuration collection name was not found.       -or-       The configuration section name was not found."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.BindingCollectionElement.BindingType
  id: BindingType
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  langs:
  - csharp
  name: BindingType
  nameWithType: BindingCollectionElement.BindingType
  fullName: System.ServiceModel.Configuration.BindingCollectionElement.BindingType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets the type of the binding."
  syntax:
    content: public abstract Type BindingType { get; }
    return:
      type: System.Type
      description: "A &lt;xref:System.Type&gt; that contains the type of the binding."
  overload: System.ServiceModel.Configuration.BindingCollectionElement.BindingType*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.BindingCollectionElement.ConfiguredBindings
  id: ConfiguredBindings
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  langs:
  - csharp
  name: ConfiguredBindings
  nameWithType: BindingCollectionElement.ConfiguredBindings
  fullName: System.ServiceModel.Configuration.BindingCollectionElement.ConfiguredBindings
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets all the binding configuration elements in this collection."
  syntax:
    content: public abstract System.Collections.ObjectModel.ReadOnlyCollection<System.ServiceModel.Configuration.IBindingConfigurationElement> ConfiguredBindings { get; }
    return:
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.ServiceModel.Configuration.IBindingConfigurationElement}
      description: "All the binding configuration elements in this collection."
  overload: System.ServiceModel.Configuration.BindingCollectionElement.ConfiguredBindings*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.BindingCollectionElement.ContainsKey(System.String)
  id: ContainsKey(System.String)
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  langs:
  - csharp
  name: ContainsKey(String)
  nameWithType: BindingCollectionElement.ContainsKey(String)
  fullName: System.ServiceModel.Configuration.BindingCollectionElement.ContainsKey(String)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Determines whether a binding exists in the collection using the specified name."
  syntax:
    content: public abstract bool ContainsKey (string name);
    parameters:
    - id: name
      type: System.String
      description: "The name of the binding to be located."
    return:
      type: System.Boolean
      description: "To be added."
  overload: System.ServiceModel.Configuration.BindingCollectionElement.ContainsKey*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.BindingCollectionElement.GetDefault
  id: GetDefault
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  langs:
  - csharp
  name: GetDefault()
  nameWithType: BindingCollectionElement.GetDefault()
  fullName: System.ServiceModel.Configuration.BindingCollectionElement.GetDefault()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets the default binding used."
  syntax:
    content: protected abstract System.ServiceModel.Channels.Binding GetDefault ();
    parameters: []
    return:
      type: System.ServiceModel.Channels.Binding
      description: "To be added."
  overload: System.ServiceModel.Configuration.BindingCollectionElement.GetDefault*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.BindingCollectionElement.TryAdd(System.String,System.ServiceModel.Channels.Binding,System.Configuration.Configuration)
  id: TryAdd(System.String,System.ServiceModel.Channels.Binding,System.Configuration.Configuration)
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  langs:
  - csharp
  name: TryAdd(String,Binding,Configuration)
  nameWithType: BindingCollectionElement.TryAdd(String,Binding,Configuration)
  fullName: System.ServiceModel.Configuration.BindingCollectionElement.TryAdd(String,Binding,Configuration)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Adds the specified binding to the collection."
  syntax:
    content: protected abstract bool TryAdd (string name, System.ServiceModel.Channels.Binding binding, System.Configuration.Configuration config);
    parameters:
    - id: name
      type: System.String
      description: "The name of the binding to be added."
    - id: binding
      type: System.ServiceModel.Channels.Binding
      description: "A <xref:System.ServiceModel.Channels.Binding> object that represents the binding to be added."
    - id: config
      type: System.Configuration.Configuration
      description: "The configuration settings of this binding."
    return:
      type: System.Boolean
      description: "To be added."
  overload: System.ServiceModel.Configuration.BindingCollectionElement.TryAdd*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.BindingCollectionElement.#ctor
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  isExternal: false
  name: BindingCollectionElement()
  nameWithType: BindingCollectionElement.BindingCollectionElement()
  fullName: System.ServiceModel.Configuration.BindingCollectionElement.BindingCollectionElement()
- uid: System.ServiceModel.Configuration.BindingCollectionElement.BindingName
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  isExternal: false
  name: BindingName
  nameWithType: BindingCollectionElement.BindingName
  fullName: System.ServiceModel.Configuration.BindingCollectionElement.BindingName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.BindingCollectionElement.BindingType
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  isExternal: false
  name: BindingType
  nameWithType: BindingCollectionElement.BindingType
  fullName: System.ServiceModel.Configuration.BindingCollectionElement.BindingType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.BindingCollectionElement.ConfiguredBindings
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  isExternal: false
  name: ConfiguredBindings
  nameWithType: BindingCollectionElement.ConfiguredBindings
  fullName: System.ServiceModel.Configuration.BindingCollectionElement.ConfiguredBindings
- uid: System.Collections.ObjectModel.ReadOnlyCollection{System.ServiceModel.Configuration.IBindingConfigurationElement}
  parent: System.Collections.ObjectModel
  isExternal: true
  name: ReadOnlyCollection<IBindingConfigurationElement>
  nameWithType: ReadOnlyCollection<IBindingConfigurationElement>
  fullName: System.Collections.ObjectModel.ReadOnlyCollection<System.ServiceModel.Configuration.IBindingConfigurationElement>
  spec.csharp:
  - uid: System.Collections.ObjectModel.ReadOnlyCollection`1
    name: ReadOnlyCollection
    nameWithType: ReadOnlyCollection
    fullName: ReadOnlyCollection<System.ServiceModel.Configuration.IBindingConfigurationElement>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.ServiceModel.Configuration.IBindingConfigurationElement
    name: IBindingConfigurationElement
    nameWithType: IBindingConfigurationElement
    fullName: IBindingConfigurationElement
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.ServiceModel.Configuration.BindingCollectionElement.ContainsKey(System.String)
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  isExternal: false
  name: ContainsKey(String)
  nameWithType: BindingCollectionElement.ContainsKey(String)
  fullName: System.ServiceModel.Configuration.BindingCollectionElement.ContainsKey(String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.BindingCollectionElement.GetDefault
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  isExternal: false
  name: GetDefault()
  nameWithType: BindingCollectionElement.GetDefault()
  fullName: System.ServiceModel.Configuration.BindingCollectionElement.GetDefault()
- uid: System.ServiceModel.Channels.Binding
  parent: System.ServiceModel.Channels
  isExternal: true
  name: Binding
  nameWithType: Binding
  fullName: System.ServiceModel.Channels.Binding
- uid: System.ServiceModel.Configuration.BindingCollectionElement.TryAdd(System.String,System.ServiceModel.Channels.Binding,System.Configuration.Configuration)
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  isExternal: false
  name: TryAdd(String,Binding,Configuration)
  nameWithType: BindingCollectionElement.TryAdd(String,Binding,Configuration)
  fullName: System.ServiceModel.Configuration.BindingCollectionElement.TryAdd(String,Binding,Configuration)
- uid: System.Configuration.Configuration
  parent: System.Configuration
  isExternal: false
  name: Configuration
  nameWithType: Configuration
  fullName: System.Configuration.Configuration
- uid: System.ServiceModel.Configuration.BindingCollectionElement.#ctor*
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  isExternal: false
  name: BindingCollectionElement
  nameWithType: BindingCollectionElement.BindingCollectionElement
- uid: System.ServiceModel.Configuration.BindingCollectionElement.BindingName*
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  isExternal: false
  name: BindingName
  nameWithType: BindingCollectionElement.BindingName
- uid: System.ServiceModel.Configuration.BindingCollectionElement.BindingType*
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  isExternal: false
  name: BindingType
  nameWithType: BindingCollectionElement.BindingType
- uid: System.ServiceModel.Configuration.BindingCollectionElement.ConfiguredBindings*
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  isExternal: false
  name: ConfiguredBindings
  nameWithType: BindingCollectionElement.ConfiguredBindings
- uid: System.ServiceModel.Configuration.BindingCollectionElement.ContainsKey*
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  isExternal: false
  name: ContainsKey
  nameWithType: BindingCollectionElement.ContainsKey
- uid: System.ServiceModel.Configuration.BindingCollectionElement.GetDefault*
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  isExternal: false
  name: GetDefault
  nameWithType: BindingCollectionElement.GetDefault
- uid: System.ServiceModel.Configuration.BindingCollectionElement.TryAdd*
  parent: System.ServiceModel.Configuration.BindingCollectionElement
  isExternal: false
  name: TryAdd
  nameWithType: BindingCollectionElement.TryAdd
