### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Channels.ChannelPoolSettings
  id: ChannelPoolSettings
  children:
  - System.ServiceModel.Channels.ChannelPoolSettings.#ctor
  - System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout
  - System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout
  - System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
  langs:
  - csharp
  name: ChannelPoolSettings
  nameWithType: ChannelPoolSettings
  fullName: System.ServiceModel.Channels.ChannelPoolSettings
  type: Class
  summary: "Specifies quotas for channels that belong to a pool of channels used by a service endpoint."
  remarks: "Quotas are used as a policy mechanism to prevent the consumption of excessive resources. They prevent Denial of Service (DOS) attacks that are either malicious or unintentional. Use this class when setting channel quotas on a custom channel.       ChannelPoolSettings specifies three quotas:      -   <xref:System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout%2A> to specify the maximum interval of time for which the channels in the pool can be idle before being closed.      -   <xref:System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout%2A> to specify the interval of time after which a channel, when returned to the pool, is closed.      -   <xref:System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint%2A> to specify the maximum number of channels that can be stored in the pool for each remote endpoint."
  syntax:
    content: public class ChannelPoolSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Channels.ChannelPoolSettings.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  langs:
  - csharp
  name: ChannelPoolSettings()
  nameWithType: ChannelPoolSettings.ChannelPoolSettings()
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.ChannelPoolSettings()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Channels.ChannelPoolSettings&quot;></see> class."
  remarks: "The default values set are:      -   <xref:System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout%2A>: 2 minutes.      -   <xref:System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout%2A>: 10 minutes.      -   <xref:System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint%2A>: 10 channels.       These default quota values are based on a conservatively modest allocation of resources that are suitable for development environments and small installation scenarios. Service administrators should review channel quotas and tune individual quota values if an installation is running out of resources or if connections are being limited despite the availability of additional resources."
  syntax:
    content: public ChannelPoolSettings ();
    parameters: []
  overload: System.ServiceModel.Channels.ChannelPoolSettings.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout
  id: IdleTimeout
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  langs:
  - csharp
  name: IdleTimeout
  nameWithType: ChannelPoolSettings.IdleTimeout
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Get or sets the maximum interval of time for which the channels in the pool can be idle before being closed."
  remarks: "The IdleTimeout quota is used to mitigate Denial of Service (DOS) attacks on the server that rely on tying up resources for an extended period of time. On the client, setting the correct value can increase the reliability of connecting with the service. The default value is based on a conservatively modest allocation of resources. It is suitable for a development environment and small installation scenarios. Service administrators should review the value if an installation is running out of resources or if connections are being limited despite the availability of additional resources."
  syntax:
    content: public TimeSpan IdleTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "The &lt;xref:System.TimeSpan&gt; that specifies the maximum interval of time for which the channels in the pool can be idle before being closed. The default value is 2 minutes."
  overload: System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "The value is less than zero or greater than T:System.Int32.MaxValue in milliseconds."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout
  id: LeaseTimeout
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  langs:
  - csharp
  name: LeaseTimeout
  nameWithType: ChannelPoolSettings.LeaseTimeout
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Gets or sets the lifetime of a channel, after which it is closed."
  remarks: "The LeaseTimeout quota is used to for integration with load balancers and for improving reliability. The default value is based on a conservative allocation of resources. It is suitable for a development environment and small installation scenarios. Service administrators should review the value if an installation is running out of resources or if connections are being limited despite the availability of additional resources."
  syntax:
    content: public TimeSpan LeaseTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "A &lt;xref:System.TimeSpan&gt; that specifies the lifetime of a channel, after which it is closed. The default value is 10 minutes."
  overload: System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "The value is less than zero."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
  id: MaxOutboundChannelsPerEndpoint
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  langs:
  - csharp
  name: MaxOutboundChannelsPerEndpoint
  nameWithType: ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Gets or sets the maximum number of channels connecting to remote endpoints that can be initiated by the service."
  remarks: "The MaxOutboundChannelsPerEndpoint quota sets cache limits on both the server and the client and is used to improve reliability. The default value is based on a conservatively modest allocation of resources that is suitable for a development environment and small installation scenarios. Service administrators should review the value if an installation is running out of resources or if connections are being limited despite the availability of additional resources."
  syntax:
    content: public int MaxOutboundChannelsPerEndpoint { get; set; }
    return:
      type: System.Int32
      description: "A positive integer that specifies the maximum number of channels to a remote endpoint in the pool that can be initiated by the service. The default value is 10 channels."
  overload: System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "The value is less than zero."
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.Channels.ChannelPoolSettings.#ctor
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: ChannelPoolSettings()
  nameWithType: ChannelPoolSettings.ChannelPoolSettings()
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.ChannelPoolSettings()
- uid: System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: IdleTimeout
  nameWithType: ChannelPoolSettings.IdleTimeout
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: LeaseTimeout
  nameWithType: ChannelPoolSettings.LeaseTimeout
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout
- uid: System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: MaxOutboundChannelsPerEndpoint
  nameWithType: ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
  fullName: System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Channels.ChannelPoolSettings.#ctor*
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: ChannelPoolSettings
  nameWithType: ChannelPoolSettings.ChannelPoolSettings
- uid: System.ServiceModel.Channels.ChannelPoolSettings.IdleTimeout*
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: IdleTimeout
  nameWithType: ChannelPoolSettings.IdleTimeout
- uid: System.ServiceModel.Channels.ChannelPoolSettings.LeaseTimeout*
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: LeaseTimeout
  nameWithType: ChannelPoolSettings.LeaseTimeout
- uid: System.ServiceModel.Channels.ChannelPoolSettings.MaxOutboundChannelsPerEndpoint*
  parent: System.ServiceModel.Channels.ChannelPoolSettings
  isExternal: false
  name: MaxOutboundChannelsPerEndpoint
  nameWithType: ChannelPoolSettings.MaxOutboundChannelsPerEndpoint
