### YamlMime:ManagedReference
items:
- uid: System.Configuration.LongValidatorAttribute
  id: LongValidatorAttribute
  children:
  - System.Configuration.LongValidatorAttribute.#ctor
  - System.Configuration.LongValidatorAttribute.ExcludeRange
  - System.Configuration.LongValidatorAttribute.MaxValue
  - System.Configuration.LongValidatorAttribute.MinValue
  - System.Configuration.LongValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: LongValidatorAttribute
  nameWithType: LongValidatorAttribute
  fullName: System.Configuration.LongValidatorAttribute
  type: Class
  summary: "Declaratively instructs the .NET Framework to perform long-integer validation on a configuration property. This class cannot be inherited."
  remarks: "You use the LongValidatorAttribute attribute to decorate a configuration property. This is to instruct the .NET Framework to validate the property using a <xref:System.Configuration.LongValidator> object and pass to it the value of the decorating parameters.       You can apply the LongValidatorAttribute attribute to property types only."
  example:
  - "The following example shows how to decorate the properties of a custom <xref:System.Configuration.ConfigurationSection> object using the LongValidatorAttribute attribute.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/VisualBasic/t-system.configuration.l_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/CSharp/t-system.configuration.l_0_1.cs)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class LongValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.LongValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.LongValidatorAttribute
  langs:
  - csharp
  name: LongValidatorAttribute()
  nameWithType: LongValidatorAttribute.LongValidatorAttribute()
  fullName: System.Configuration.LongValidatorAttribute.LongValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.LongValidatorAttribute&quot;></see> class."
  remarks: "You use this constructor in the attributed model to ensure that the value assigned to the related property is a long integer."
  syntax:
    content: public LongValidatorAttribute ();
    parameters: []
  overload: System.Configuration.LongValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.LongValidatorAttribute.ExcludeRange
  id: ExcludeRange
  parent: System.Configuration.LongValidatorAttribute
  langs:
  - csharp
  name: ExcludeRange
  nameWithType: LongValidatorAttribute.ExcludeRange
  fullName: System.Configuration.LongValidatorAttribute.ExcludeRange
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets or sets a value that indicates whether to include or exclude the integers in the range defined by the &lt;xref:System.Configuration.LongValidatorAttribute.MinValue%2A&gt; and &lt;xref:System.Configuration.LongValidatorAttribute.MaxValue%2A&gt; property values."
  remarks: "The range is inclusive of the <xref:System.Configuration.LongValidatorAttribute.MinValue%2A> and <xref:System.Configuration.LongValidatorAttribute.MaxValue%2A> property values. When the ExcludeRange property value is `false`, the allowed values are outside the range."
  example:
  - "The following example shows how to use the <xref:System.Configuration.IntegerValidatorAttribute.ExcludeRange%2A> property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/VisualBasic/p-system.configuration.l_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/CSharp/p-system.configuration.l_0_1.cs)]"
  syntax:
    content: public bool ExcludeRange { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if the value must be excluded; otherwise, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>. The default is <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>."
  overload: System.Configuration.LongValidatorAttribute.ExcludeRange*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.LongValidatorAttribute.MaxValue
  id: MaxValue
  parent: System.Configuration.LongValidatorAttribute
  langs:
  - csharp
  name: MaxValue
  nameWithType: LongValidatorAttribute.MaxValue
  fullName: System.Configuration.LongValidatorAttribute.MaxValue
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets or sets the maximum value allowed for the property."
  remarks: "The MaxValue property value is included in the allowed range."
  example:
  - "The following example shows how to use the MaxValue property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/VisualBasic/p-system.configuration.l_1_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/CSharp/p-system.configuration.l_1_1.cs)]"
  syntax:
    content: public long MaxValue { get; set; }
    return:
      type: System.Int64
      description: "A long integer that indicates the allowed maximum value."
  overload: System.Configuration.LongValidatorAttribute.MaxValue*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "The selected value is less than <xref:System.Configuration.LongValidatorAttribute.MinValue%2A>."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.LongValidatorAttribute.MinValue
  id: MinValue
  parent: System.Configuration.LongValidatorAttribute
  langs:
  - csharp
  name: MinValue
  nameWithType: LongValidatorAttribute.MinValue
  fullName: System.Configuration.LongValidatorAttribute.MinValue
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets or sets the minimum value allowed for the property."
  remarks: "The MinValue property value is included in the allowed range."
  example:
  - "The following example shows how to use the MinValue property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/VisualBasic/p-system.configuration.l_2_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#7](~/add/codesnippet/CSharp/p-system.configuration.l_2_1.cs)]"
  syntax:
    content: public long MinValue { get; set; }
    return:
      type: System.Int64
      description: "An integer that indicates the allowed minimum value."
  overload: System.Configuration.LongValidatorAttribute.MinValue*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "The selected value is greater than <xref:System.Configuration.LongValidatorAttribute.MaxValue%2A>."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.LongValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.LongValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: LongValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.LongValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets an instance of the <see cref=&quot;T:System.Configuration.LongValidator&quot;></see> class."
  remarks: "You use the ValidatorInstance property value to perform string validation by calling its <xref:System.Configuration.LongValidator.Validate%2A> method."
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "The <see cref=&quot;T:System.Configuration.ConfigurationValidatorBase&quot;></see> validator instance."
  overload: System.Configuration.LongValidatorAttribute.ValidatorInstance*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.Configuration.LongValidatorAttribute.#ctor
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: LongValidatorAttribute()
  nameWithType: LongValidatorAttribute.LongValidatorAttribute()
  fullName: System.Configuration.LongValidatorAttribute.LongValidatorAttribute()
- uid: System.Configuration.LongValidatorAttribute.ExcludeRange
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: ExcludeRange
  nameWithType: LongValidatorAttribute.ExcludeRange
  fullName: System.Configuration.LongValidatorAttribute.ExcludeRange
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.LongValidatorAttribute.MaxValue
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: MaxValue
  nameWithType: LongValidatorAttribute.MaxValue
  fullName: System.Configuration.LongValidatorAttribute.MaxValue
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Configuration.LongValidatorAttribute.MinValue
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: MinValue
  nameWithType: LongValidatorAttribute.MinValue
  fullName: System.Configuration.LongValidatorAttribute.MinValue
- uid: System.Configuration.LongValidatorAttribute.ValidatorInstance
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: LongValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.LongValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.LongValidatorAttribute.#ctor*
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: LongValidatorAttribute
  nameWithType: LongValidatorAttribute.LongValidatorAttribute
- uid: System.Configuration.LongValidatorAttribute.ExcludeRange*
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: ExcludeRange
  nameWithType: LongValidatorAttribute.ExcludeRange
- uid: System.Configuration.LongValidatorAttribute.MaxValue*
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: MaxValue
  nameWithType: LongValidatorAttribute.MaxValue
- uid: System.Configuration.LongValidatorAttribute.MinValue*
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: MinValue
  nameWithType: LongValidatorAttribute.MinValue
- uid: System.Configuration.LongValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.LongValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: LongValidatorAttribute.ValidatorInstance
