### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElementCollection
  id: AnnotationElementCollection
  children:
  - System.ServiceModel.Activities.Tracking.Configuration.AnnotationElementCollection.#ctor
  - System.ServiceModel.Activities.Tracking.Configuration.AnnotationElementCollection.ElementName
  langs:
  - csharp
  name: AnnotationElementCollection
  nameWithType: AnnotationElementCollection
  fullName: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElementCollection
  type: Class
  summary: "A collection of <see cref=&quot;T:System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement&quot;></see> elements that contains <see cref=&quot;T:System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement&quot;></see> elements."
  syntax:
    content: >-
      [System.Configuration.ConfigurationCollection(typeof(System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement), AddItemName="annotation", CollectionType=System.Configuration.ConfigurationElementCollectionType.BasicMap)]

      public class AnnotationElementCollection : System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection<System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement>
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationElementCollection
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection`1
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.AddElementName
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Configuration.ConfigurationElement,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Int32,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseClear
  - System.Configuration.ConfigurationElementCollection.BaseGet(System.Int32)
  - System.Configuration.ConfigurationElementCollection.BaseGet(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseGetAllKeys
  - System.Configuration.ConfigurationElementCollection.BaseGetKey(System.Int32)
  - System.Configuration.ConfigurationElementCollection.BaseIndexOf(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseIsRemoved(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseRemove(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseRemoveAt(System.Int32)
  - System.Configuration.ConfigurationElementCollection.ClearElementName
  - System.Configuration.ConfigurationElementCollection.CopyTo(System.Configuration.ConfigurationElement[],System.Int32)
  - System.Configuration.ConfigurationElementCollection.Count
  - System.Configuration.ConfigurationElementCollection.CreateNewElement(System.String)
  - System.Configuration.ConfigurationElementCollection.EmitClear
  - System.Configuration.ConfigurationElementCollection.Equals(System.Object)
  - System.Configuration.ConfigurationElementCollection.GetEnumerator
  - System.Configuration.ConfigurationElementCollection.GetHashCode
  - System.Configuration.ConfigurationElementCollection.IsElementName(System.String)
  - System.Configuration.ConfigurationElementCollection.IsElementRemovable(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.IsModified
  - System.Configuration.ConfigurationElementCollection.IsReadOnly
  - System.Configuration.ConfigurationElementCollection.IsSynchronized
  - System.Configuration.ConfigurationElementCollection.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElementCollection.RemoveElementName
  - System.Configuration.ConfigurationElementCollection.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.ResetModified
  - System.Configuration.ConfigurationElementCollection.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.SetReadOnly
  - System.Configuration.ConfigurationElementCollection.SyncRoot
  - System.Configuration.ConfigurationElementCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  - System.Configuration.ConfigurationElementCollection.ThrowOnDuplicate
  - System.Configuration.ConfigurationElementCollection.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection`1.Add(`0)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection`1.Clear
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection`1.CollectionType
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection`1.CreateNewElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection`1.GetElementKey(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection`1.IndexOf(`0)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection`1.Item(System.Int32)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection`1.Remove(`0)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection`1.RemoveAt(System.Int32)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElementCollection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElementCollection
  langs:
  - csharp
  name: AnnotationElementCollection()
  nameWithType: AnnotationElementCollection.AnnotationElementCollection()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElementCollection.AnnotationElementCollection()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Activities.Tracking.Configuration.AnnotationElementCollection&quot;></see> class."
  syntax:
    content: public AnnotationElementCollection ();
    parameters: []
  overload: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElementCollection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElementCollection.ElementName
  id: ElementName
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElementCollection
  langs:
  - csharp
  name: ElementName
  nameWithType: AnnotationElementCollection.ElementName
  fullName: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElementCollection.ElementName
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Gets the configuration element name."
  syntax:
    content: protected override string ElementName { get; }
    return:
      type: System.String
      description: "The configuration element name."
  overload: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElementCollection.ElementName*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection`1
  isExternal: false
  name: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationCollection<System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement>
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElementCollection.#ctor
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElementCollection
  isExternal: false
  name: AnnotationElementCollection()
  nameWithType: AnnotationElementCollection.AnnotationElementCollection()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElementCollection.AnnotationElementCollection()
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElementCollection.ElementName
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElementCollection
  isExternal: false
  name: ElementName
  nameWithType: AnnotationElementCollection.ElementName
  fullName: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElementCollection.ElementName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElementCollection.#ctor*
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElementCollection
  isExternal: false
  name: AnnotationElementCollection
  nameWithType: AnnotationElementCollection.AnnotationElementCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElementCollection.ElementName*
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElementCollection
  isExternal: false
  name: ElementName
  nameWithType: AnnotationElementCollection.ElementName
