### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.WSDualHttpSecurityElement
  id: WSDualHttpSecurityElement
  children:
  - System.ServiceModel.Configuration.WSDualHttpSecurityElement.#ctor
  - System.ServiceModel.Configuration.WSDualHttpSecurityElement.Message
  - System.ServiceModel.Configuration.WSDualHttpSecurityElement.Mode
  - System.ServiceModel.Configuration.WSDualHttpSecurityElement.Properties
  langs:
  - csharp
  name: WSDualHttpSecurityElement
  nameWithType: WSDualHttpSecurityElement
  fullName: System.ServiceModel.Configuration.WSDualHttpSecurityElement
  type: Class
  summary: "Represents an XML element that defines the security settings for a wsDualHttpBinding binding."
  syntax:
    content: 'public sealed class WSDualHttpSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.WSDualHttpSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.WSDualHttpSecurityElement
  langs:
  - csharp
  name: WSDualHttpSecurityElement()
  nameWithType: WSDualHttpSecurityElement.WSDualHttpSecurityElement()
  fullName: System.ServiceModel.Configuration.WSDualHttpSecurityElement.WSDualHttpSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.WSDualHttpSecurityElement&quot;></see> class."
  syntax:
    content: public WSDualHttpSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.WSDualHttpSecurityElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.WSDualHttpSecurityElement.Message
  id: Message
  parent: System.ServiceModel.Configuration.WSDualHttpSecurityElement
  langs:
  - csharp
  name: Message
  nameWithType: WSDualHttpSecurityElement.Message
  fullName: System.ServiceModel.Configuration.WSDualHttpSecurityElement.Message
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets the security settings for the message."
  syntax:
    content: public System.ServiceModel.Configuration.MessageSecurityOverHttpElement Message { get; }
    return:
      type: System.ServiceModel.Configuration.MessageSecurityOverHttpElement
      description: "The security settings for the message."
  overload: System.ServiceModel.Configuration.WSDualHttpSecurityElement.Message*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.WSDualHttpSecurityElement.Mode
  id: Mode
  parent: System.ServiceModel.Configuration.WSDualHttpSecurityElement
  langs:
  - csharp
  name: Mode
  nameWithType: WSDualHttpSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.WSDualHttpSecurityElement.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets the type of security that is applied to this binding."
  syntax:
    content: public System.ServiceModel.WSDualHttpSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.WSDualHttpSecurityMode
      description: "A <see cref=&quot;T:System.ServiceModel.WSDualHttpSecurityMode&quot;></see> that specifies the type of security that is applied to this binding The default value is &lt;xref:System.ServiceModel.Configuration.WSDualHttpSecurityElement.Message%2A&gt;."
  overload: System.ServiceModel.Configuration.WSDualHttpSecurityElement.Mode*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.WSDualHttpSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.WSDualHttpSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: WSDualHttpSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.WSDualHttpSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.WSDualHttpSecurityElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.WSDualHttpSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.WSDualHttpSecurityElement
  isExternal: false
  name: WSDualHttpSecurityElement()
  nameWithType: WSDualHttpSecurityElement.WSDualHttpSecurityElement()
  fullName: System.ServiceModel.Configuration.WSDualHttpSecurityElement.WSDualHttpSecurityElement()
- uid: System.ServiceModel.Configuration.WSDualHttpSecurityElement.Message
  parent: System.ServiceModel.Configuration.WSDualHttpSecurityElement
  isExternal: false
  name: Message
  nameWithType: WSDualHttpSecurityElement.Message
  fullName: System.ServiceModel.Configuration.WSDualHttpSecurityElement.Message
- uid: System.ServiceModel.Configuration.MessageSecurityOverHttpElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: MessageSecurityOverHttpElement
  nameWithType: MessageSecurityOverHttpElement
  fullName: System.ServiceModel.Configuration.MessageSecurityOverHttpElement
- uid: System.ServiceModel.Configuration.WSDualHttpSecurityElement.Mode
  parent: System.ServiceModel.Configuration.WSDualHttpSecurityElement
  isExternal: false
  name: Mode
  nameWithType: WSDualHttpSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.WSDualHttpSecurityElement.Mode
- uid: System.ServiceModel.WSDualHttpSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: WSDualHttpSecurityMode
  nameWithType: WSDualHttpSecurityMode
  fullName: System.ServiceModel.WSDualHttpSecurityMode
- uid: System.ServiceModel.Configuration.WSDualHttpSecurityElement.Properties
  parent: System.ServiceModel.Configuration.WSDualHttpSecurityElement
  isExternal: false
  name: Properties
  nameWithType: WSDualHttpSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.WSDualHttpSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.WSDualHttpSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.WSDualHttpSecurityElement
  isExternal: false
  name: WSDualHttpSecurityElement
  nameWithType: WSDualHttpSecurityElement.WSDualHttpSecurityElement
- uid: System.ServiceModel.Configuration.WSDualHttpSecurityElement.Message*
  parent: System.ServiceModel.Configuration.WSDualHttpSecurityElement
  isExternal: false
  name: Message
  nameWithType: WSDualHttpSecurityElement.Message
- uid: System.ServiceModel.Configuration.WSDualHttpSecurityElement.Mode*
  parent: System.ServiceModel.Configuration.WSDualHttpSecurityElement
  isExternal: false
  name: Mode
  nameWithType: WSDualHttpSecurityElement.Mode
- uid: System.ServiceModel.Configuration.WSDualHttpSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.WSDualHttpSecurityElement
  isExternal: false
  name: Properties
  nameWithType: WSDualHttpSecurityElement.Properties
