### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Configuration.ChannelSettingsElement
  id: ChannelSettingsElement
  children:
  - System.ServiceModel.Activities.Configuration.ChannelSettingsElement.#ctor
  - System.ServiceModel.Activities.Configuration.ChannelSettingsElement.IdleTimeout
  - System.ServiceModel.Activities.Configuration.ChannelSettingsElement.LeaseTimeout
  - System.ServiceModel.Activities.Configuration.ChannelSettingsElement.MaxItemsInCache
  - System.ServiceModel.Activities.Configuration.ChannelSettingsElement.Properties
  langs:
  - csharp
  name: ChannelSettingsElement
  nameWithType: ChannelSettingsElement
  fullName: System.ServiceModel.Activities.Configuration.ChannelSettingsElement
  type: Class
  summary: "Enables assigning values to the settings of a channel listener configuration element in a workflow service application. This is a sealed class."
  syntax:
    content: 'public sealed class ChannelSettingsElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Configuration.ChannelSettingsElement
  langs:
  - csharp
  name: ChannelSettingsElement()
  nameWithType: ChannelSettingsElement.ChannelSettingsElement()
  fullName: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.ChannelSettingsElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "Creates a new instance of the <see cref=&quot;T:System.ServiceModel.Activities.Configuration.ChannelSettingsElement&quot;></see> class."
  syntax:
    content: public ChannelSettingsElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.IdleTimeout
  id: IdleTimeout
  parent: System.ServiceModel.Activities.Configuration.ChannelSettingsElement
  langs:
  - csharp
  name: IdleTimeout
  nameWithType: ChannelSettingsElement.IdleTimeout
  fullName: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.IdleTimeout
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "Gets or sets the maximum interval of time for which the object can remain idle in the cache before being disposed.."
  syntax:
    content: public TimeSpan IdleTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "A timespan object."
  overload: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.IdleTimeout*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.LeaseTimeout
  id: LeaseTimeout
  parent: System.ServiceModel.Activities.Configuration.ChannelSettingsElement
  langs:
  - csharp
  name: LeaseTimeout
  nameWithType: ChannelSettingsElement.LeaseTimeout
  fullName: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.LeaseTimeout
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "Gets or sets the interval of time after which an object will be removed from the cache."
  syntax:
    content: public TimeSpan LeaseTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "A timespan object."
  overload: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.LeaseTimeout*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.MaxItemsInCache
  id: MaxItemsInCache
  parent: System.ServiceModel.Activities.Configuration.ChannelSettingsElement
  langs:
  - csharp
  name: MaxItemsInCache
  nameWithType: ChannelSettingsElement.MaxItemsInCache
  fullName: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.MaxItemsInCache
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "Gets or sets the maximum number of objects that can be in the cache."
  syntax:
    content: public int MaxItemsInCache { get; set; }
    return:
      type: System.Int32
      description: "An integer representing a maximum number."
  overload: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.MaxItemsInCache*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Configuration.ChannelSettingsElement
  langs:
  - csharp
  name: Properties
  nameWithType: ChannelSettingsElement.Properties
  fullName: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.#ctor
  parent: System.ServiceModel.Activities.Configuration.ChannelSettingsElement
  isExternal: false
  name: ChannelSettingsElement()
  nameWithType: ChannelSettingsElement.ChannelSettingsElement()
  fullName: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.ChannelSettingsElement()
- uid: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.IdleTimeout
  parent: System.ServiceModel.Activities.Configuration.ChannelSettingsElement
  isExternal: false
  name: IdleTimeout
  nameWithType: ChannelSettingsElement.IdleTimeout
  fullName: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.IdleTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.LeaseTimeout
  parent: System.ServiceModel.Activities.Configuration.ChannelSettingsElement
  isExternal: false
  name: LeaseTimeout
  nameWithType: ChannelSettingsElement.LeaseTimeout
  fullName: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.LeaseTimeout
- uid: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.MaxItemsInCache
  parent: System.ServiceModel.Activities.Configuration.ChannelSettingsElement
  isExternal: false
  name: MaxItemsInCache
  nameWithType: ChannelSettingsElement.MaxItemsInCache
  fullName: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.MaxItemsInCache
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.Properties
  parent: System.ServiceModel.Activities.Configuration.ChannelSettingsElement
  isExternal: false
  name: Properties
  nameWithType: ChannelSettingsElement.Properties
  fullName: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.#ctor*
  parent: System.ServiceModel.Activities.Configuration.ChannelSettingsElement
  isExternal: false
  name: ChannelSettingsElement
  nameWithType: ChannelSettingsElement.ChannelSettingsElement
- uid: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.IdleTimeout*
  parent: System.ServiceModel.Activities.Configuration.ChannelSettingsElement
  isExternal: false
  name: IdleTimeout
  nameWithType: ChannelSettingsElement.IdleTimeout
- uid: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.LeaseTimeout*
  parent: System.ServiceModel.Activities.Configuration.ChannelSettingsElement
  isExternal: false
  name: LeaseTimeout
  nameWithType: ChannelSettingsElement.LeaseTimeout
- uid: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.MaxItemsInCache*
  parent: System.ServiceModel.Activities.Configuration.ChannelSettingsElement
  isExternal: false
  name: MaxItemsInCache
  nameWithType: ChannelSettingsElement.MaxItemsInCache
- uid: System.ServiceModel.Activities.Configuration.ChannelSettingsElement.Properties*
  parent: System.ServiceModel.Activities.Configuration.ChannelSettingsElement
  isExternal: false
  name: Properties
  nameWithType: ChannelSettingsElement.Properties
