### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.EndToEndTracingElement
  id: EndToEndTracingElement
  children:
  - System.ServiceModel.Configuration.EndToEndTracingElement.#ctor
  - System.ServiceModel.Configuration.EndToEndTracingElement.ActivityTracing
  - System.ServiceModel.Configuration.EndToEndTracingElement.MessageFlowTracing
  - System.ServiceModel.Configuration.EndToEndTracingElement.PropagateActivity
  - System.ServiceModel.Configuration.EndToEndTracingElement.Properties
  langs:
  - csharp
  name: EndToEndTracingElement
  nameWithType: EndToEndTracingElement
  fullName: System.ServiceModel.Configuration.EndToEndTracingElement
  type: Class
  summary: "Handles configuration file element settings that enable and disable different aspects of end-to-end tracing during the running of a service application."
  syntax:
    content: 'public sealed class EndToEndTracingElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  langs:
  - csharp
  name: EndToEndTracingElement()
  nameWithType: EndToEndTracingElement.EndToEndTracingElement()
  fullName: System.ServiceModel.Configuration.EndToEndTracingElement.EndToEndTracingElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Creates a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.EndToEndTracingElement&quot;></see> class."
  syntax:
    content: public EndToEndTracingElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.EndToEndTracingElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.ActivityTracing
  id: ActivityTracing
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  langs:
  - csharp
  name: ActivityTracing
  nameWithType: EndToEndTracingElement.ActivityTracing
  fullName: System.ServiceModel.Configuration.EndToEndTracingElement.ActivityTracing
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets a value that indicates whether activity tracing is enabled."
  syntax:
    content: public bool ActivityTracing { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if activity tracing is enabled; otherwise, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>."
  overload: System.ServiceModel.Configuration.EndToEndTracingElement.ActivityTracing*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.MessageFlowTracing
  id: MessageFlowTracing
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  langs:
  - csharp
  name: MessageFlowTracing
  nameWithType: EndToEndTracingElement.MessageFlowTracing
  fullName: System.ServiceModel.Configuration.EndToEndTracingElement.MessageFlowTracing
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets a value that indicates whether message flow tracing in enabled."
  syntax:
    content: public bool MessageFlowTracing { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> is message flow tracing is enabled; otherwise, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>."
  overload: System.ServiceModel.Configuration.EndToEndTracingElement.MessageFlowTracing*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.PropagateActivity
  id: PropagateActivity
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  langs:
  - csharp
  name: PropagateActivity
  nameWithType: EndToEndTracingElement.PropagateActivity
  fullName: System.ServiceModel.Configuration.EndToEndTracingElement.PropagateActivity
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets a value that indicates whether the propagate attribute is set to <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>."
  syntax:
    content: public bool PropagateActivity { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if the propagate activity attribute is set to <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>; otherwise, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>."
  overload: System.ServiceModel.Configuration.EndToEndTracingElement.PropagateActivity*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  langs:
  - csharp
  name: Properties
  nameWithType: EndToEndTracingElement.Properties
  fullName: System.ServiceModel.Configuration.EndToEndTracingElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.EndToEndTracingElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.#ctor
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  isExternal: false
  name: EndToEndTracingElement()
  nameWithType: EndToEndTracingElement.EndToEndTracingElement()
  fullName: System.ServiceModel.Configuration.EndToEndTracingElement.EndToEndTracingElement()
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.ActivityTracing
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  isExternal: false
  name: ActivityTracing
  nameWithType: EndToEndTracingElement.ActivityTracing
  fullName: System.ServiceModel.Configuration.EndToEndTracingElement.ActivityTracing
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.MessageFlowTracing
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  isExternal: false
  name: MessageFlowTracing
  nameWithType: EndToEndTracingElement.MessageFlowTracing
  fullName: System.ServiceModel.Configuration.EndToEndTracingElement.MessageFlowTracing
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.PropagateActivity
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  isExternal: false
  name: PropagateActivity
  nameWithType: EndToEndTracingElement.PropagateActivity
  fullName: System.ServiceModel.Configuration.EndToEndTracingElement.PropagateActivity
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.Properties
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  isExternal: false
  name: Properties
  nameWithType: EndToEndTracingElement.Properties
  fullName: System.ServiceModel.Configuration.EndToEndTracingElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.#ctor*
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  isExternal: false
  name: EndToEndTracingElement
  nameWithType: EndToEndTracingElement.EndToEndTracingElement
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.ActivityTracing*
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  isExternal: false
  name: ActivityTracing
  nameWithType: EndToEndTracingElement.ActivityTracing
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.MessageFlowTracing*
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  isExternal: false
  name: MessageFlowTracing
  nameWithType: EndToEndTracingElement.MessageFlowTracing
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.PropagateActivity*
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  isExternal: false
  name: PropagateActivity
  nameWithType: EndToEndTracingElement.PropagateActivity
- uid: System.ServiceModel.Configuration.EndToEndTracingElement.Properties*
  parent: System.ServiceModel.Configuration.EndToEndTracingElement
  isExternal: false
  name: Properties
  nameWithType: EndToEndTracingElement.Properties
