### YamlMime:ManagedReference
items:
- uid: System.Xml.Serialization.Configuration.SerializationSectionGroup
  id: SerializationSectionGroup
  children:
  - System.Xml.Serialization.Configuration.SerializationSectionGroup.#ctor
  - System.Xml.Serialization.Configuration.SerializationSectionGroup.DateTimeSerialization
  - System.Xml.Serialization.Configuration.SerializationSectionGroup.SchemaImporterExtensions
  - System.Xml.Serialization.Configuration.SerializationSectionGroup.XmlSerializer
  langs:
  - csharp
  name: SerializationSectionGroup
  nameWithType: SerializationSectionGroup
  fullName: System.Xml.Serialization.Configuration.SerializationSectionGroup
  type: Class
  summary: "Handles the XML elements used to configure XML serialization."
  remarks: "This class is used to handle the [\\<system.xml.serialization> Element](../Topic/%3Csystem.xml.serialization%3E%20Element.md)."
  syntax:
    content: 'public sealed class SerializationSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Xml.Serialization.Configuration.SerializationSectionGroup.#ctor
  id: '#ctor'
  parent: System.Xml.Serialization.Configuration.SerializationSectionGroup
  langs:
  - csharp
  name: SerializationSectionGroup()
  nameWithType: SerializationSectionGroup.SerializationSectionGroup()
  fullName: System.Xml.Serialization.Configuration.SerializationSectionGroup.SerializationSectionGroup()
  type: Constructor
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Xml.Serialization.Configuration.SerializationSectionGroup&quot;></see> class."
  syntax:
    content: public SerializationSectionGroup ();
    parameters: []
  overload: System.Xml.Serialization.Configuration.SerializationSectionGroup.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Xml.Serialization.Configuration.SerializationSectionGroup.DateTimeSerialization
  id: DateTimeSerialization
  parent: System.Xml.Serialization.Configuration.SerializationSectionGroup
  langs:
  - csharp
  name: DateTimeSerialization
  nameWithType: SerializationSectionGroup.DateTimeSerialization
  fullName: System.Xml.Serialization.Configuration.SerializationSectionGroup.DateTimeSerialization
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: "Gets the object that represents the &lt;xref:System.DateTime&gt; serialization configuration element."
  syntax:
    content: public System.Xml.Serialization.Configuration.DateTimeSerializationSection DateTimeSerialization { get; }
    return:
      type: System.Xml.Serialization.Configuration.DateTimeSerializationSection
      description: "The <see cref=&quot;T:System.Xml.Serialization.Configuration.DateTimeSerializationSection&quot;></see> object that represents the configuration element."
  overload: System.Xml.Serialization.Configuration.SerializationSectionGroup.DateTimeSerialization*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Xml.Serialization.Configuration.SerializationSectionGroup.SchemaImporterExtensions
  id: SchemaImporterExtensions
  parent: System.Xml.Serialization.Configuration.SerializationSectionGroup
  langs:
  - csharp
  name: SchemaImporterExtensions
  nameWithType: SerializationSectionGroup.SchemaImporterExtensions
  fullName: System.Xml.Serialization.Configuration.SerializationSectionGroup.SchemaImporterExtensions
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: "Gets the object that represents the section that contains configuration elements for the <see cref=&quot;T:System.Xml.Serialization.XmlSchemaImporter&quot;></see>."
  syntax:
    content: public System.Xml.Serialization.Configuration.SchemaImporterExtensionsSection SchemaImporterExtensions { get; }
    return:
      type: System.Xml.Serialization.Configuration.SchemaImporterExtensionsSection
      description: "The <see cref=&quot;T:System.Xml.Serialization.Configuration.SchemaImporterExtensionsSection&quot;></see> that represents the <xref uid=&quot;langword_csharp_schemaImporterExtenstion&quot; name=&quot;schemaImporterExtenstion&quot; href=&quot;&quot;></xref> element in the configuration file."
  overload: System.Xml.Serialization.Configuration.SerializationSectionGroup.SchemaImporterExtensions*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Xml.Serialization.Configuration.SerializationSectionGroup.XmlSerializer
  id: XmlSerializer
  parent: System.Xml.Serialization.Configuration.SerializationSectionGroup
  langs:
  - csharp
  name: XmlSerializer
  nameWithType: SerializationSectionGroup.XmlSerializer
  fullName: System.Xml.Serialization.Configuration.SerializationSectionGroup.XmlSerializer
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: "Gets the object that represents the configuration group for the &lt;xref:System.Xml.Serialization.XmlSerializer&gt;."
  syntax:
    content: public System.Xml.Serialization.Configuration.XmlSerializerSection XmlSerializer { get; }
    return:
      type: System.Xml.Serialization.Configuration.XmlSerializerSection
      description: "The <see cref=&quot;T:System.Xml.Serialization.Configuration.XmlSerializerSection&quot;></see> that represents the &lt;xref:System.Xml.Serialization.XmlSerializer&gt;."
  overload: System.Xml.Serialization.Configuration.SerializationSectionGroup.XmlSerializer*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: System.Configuration.ConfigurationSectionGroup
- uid: System.Xml.Serialization.Configuration.SerializationSectionGroup.#ctor
  parent: System.Xml.Serialization.Configuration.SerializationSectionGroup
  isExternal: false
  name: SerializationSectionGroup()
  nameWithType: SerializationSectionGroup.SerializationSectionGroup()
  fullName: System.Xml.Serialization.Configuration.SerializationSectionGroup.SerializationSectionGroup()
- uid: System.Xml.Serialization.Configuration.SerializationSectionGroup.DateTimeSerialization
  parent: System.Xml.Serialization.Configuration.SerializationSectionGroup
  isExternal: false
  name: DateTimeSerialization
  nameWithType: SerializationSectionGroup.DateTimeSerialization
  fullName: System.Xml.Serialization.Configuration.SerializationSectionGroup.DateTimeSerialization
- uid: System.Xml.Serialization.Configuration.DateTimeSerializationSection
  parent: System.Xml.Serialization.Configuration
  isExternal: false
  name: DateTimeSerializationSection
  nameWithType: DateTimeSerializationSection
  fullName: System.Xml.Serialization.Configuration.DateTimeSerializationSection
- uid: System.Xml.Serialization.Configuration.SerializationSectionGroup.SchemaImporterExtensions
  parent: System.Xml.Serialization.Configuration.SerializationSectionGroup
  isExternal: false
  name: SchemaImporterExtensions
  nameWithType: SerializationSectionGroup.SchemaImporterExtensions
  fullName: System.Xml.Serialization.Configuration.SerializationSectionGroup.SchemaImporterExtensions
- uid: System.Xml.Serialization.Configuration.SchemaImporterExtensionsSection
  parent: System.Xml.Serialization.Configuration
  isExternal: false
  name: SchemaImporterExtensionsSection
  nameWithType: SchemaImporterExtensionsSection
  fullName: System.Xml.Serialization.Configuration.SchemaImporterExtensionsSection
- uid: System.Xml.Serialization.Configuration.SerializationSectionGroup.XmlSerializer
  parent: System.Xml.Serialization.Configuration.SerializationSectionGroup
  isExternal: false
  name: XmlSerializer
  nameWithType: SerializationSectionGroup.XmlSerializer
  fullName: System.Xml.Serialization.Configuration.SerializationSectionGroup.XmlSerializer
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection
  parent: System.Xml.Serialization.Configuration
  isExternal: false
  name: XmlSerializerSection
  nameWithType: XmlSerializerSection
  fullName: System.Xml.Serialization.Configuration.XmlSerializerSection
- uid: System.Xml.Serialization.Configuration.SerializationSectionGroup.#ctor*
  parent: System.Xml.Serialization.Configuration.SerializationSectionGroup
  isExternal: false
  name: SerializationSectionGroup
  nameWithType: SerializationSectionGroup.SerializationSectionGroup
- uid: System.Xml.Serialization.Configuration.SerializationSectionGroup.DateTimeSerialization*
  parent: System.Xml.Serialization.Configuration.SerializationSectionGroup
  isExternal: false
  name: DateTimeSerialization
  nameWithType: SerializationSectionGroup.DateTimeSerialization
- uid: System.Xml.Serialization.Configuration.SerializationSectionGroup.SchemaImporterExtensions*
  parent: System.Xml.Serialization.Configuration.SerializationSectionGroup
  isExternal: false
  name: SchemaImporterExtensions
  nameWithType: SerializationSectionGroup.SchemaImporterExtensions
- uid: System.Xml.Serialization.Configuration.SerializationSectionGroup.XmlSerializer*
  parent: System.Xml.Serialization.Configuration.SerializationSectionGroup
  isExternal: false
  name: XmlSerializer
  nameWithType: SerializationSectionGroup.XmlSerializer
