### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.AuthenticationModuleElement
  id: AuthenticationModuleElement
  children:
  - System.Net.Configuration.AuthenticationModuleElement.#ctor
  - System.Net.Configuration.AuthenticationModuleElement.#ctor(System.String)
  - System.Net.Configuration.AuthenticationModuleElement.Properties
  - System.Net.Configuration.AuthenticationModuleElement.Type
  langs:
  - csharp
  name: AuthenticationModuleElement
  nameWithType: AuthenticationModuleElement
  fullName: System.Net.Configuration.AuthenticationModuleElement
  type: Class
  summary: "Represents the type information for an authentication module. This class cannot be inherited."
  remarks: "This class corresponds to the `type` attribute of the [\\<add> Element for authenticationModules (Network Settings)](../Topic/%3Cadd%3E%20Element%20for%20authenticationModules%20\\(Network%20Settings\\).md) configuration element.  \n  \n This class is used to specify modules registered to authenticate requests made with the <xref:System.Net.WebRequest> and <xref:System.Net.WebClient> classes.  \n  \n This class provides programmatic access to information that can be stored in configuration files."
  syntax:
    content: 'public sealed class AuthenticationModuleElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.AuthenticationModuleElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.AuthenticationModuleElement
  langs:
  - csharp
  name: AuthenticationModuleElement()
  nameWithType: AuthenticationModuleElement.AuthenticationModuleElement()
  fullName: System.Net.Configuration.AuthenticationModuleElement.AuthenticationModuleElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Net.Configuration.AuthenticationModuleElement&quot;></see> class."
  remarks: "This constructor sets the <xref:System.Net.Configuration.AuthenticationModuleElement.Type%2A> property to `null`."
  syntax:
    content: public AuthenticationModuleElement ();
    parameters: []
  overload: System.Net.Configuration.AuthenticationModuleElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.AuthenticationModuleElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Net.Configuration.AuthenticationModuleElement
  langs:
  - csharp
  name: AuthenticationModuleElement(String)
  nameWithType: AuthenticationModuleElement.AuthenticationModuleElement(String)
  fullName: System.Net.Configuration.AuthenticationModuleElement.AuthenticationModuleElement(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Net.Configuration.AuthenticationModuleElement&quot;></see> class with the specified type information."
  remarks: "The `typeName` parameter contains the fully qualified type name followed by a comma (,) and the assembly information. The elements of the assembly information are separated with commas, for example, `Corp.Net.Authenticator, Corp, Version=1.0.5000.0, Culture=neutral, PublicKeyToken=&quot;00000000000000000&quot;`."
  syntax:
    content: public AuthenticationModuleElement (string typeName);
    parameters:
    - id: typeName
      type: System.String
      description: "A string that identifies the type and the assembly that contains it."
  overload: System.Net.Configuration.AuthenticationModuleElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.AuthenticationModuleElement.Properties
  id: Properties
  parent: System.Net.Configuration.AuthenticationModuleElement
  langs:
  - csharp
  name: Properties
  nameWithType: AuthenticationModuleElement.Properties
  fullName: System.Net.Configuration.AuthenticationModuleElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Net.Configuration.AuthenticationModuleElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.AuthenticationModuleElement.Type
  id: Type
  parent: System.Net.Configuration.AuthenticationModuleElement
  langs:
  - csharp
  name: Type
  nameWithType: AuthenticationModuleElement.Type
  fullName: System.Net.Configuration.AuthenticationModuleElement.Type
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Gets or sets the type and assembly information for the current instance."
  remarks: "This property contains the fully qualified type name followed by a comma (,) and the assembly information. The elements of the assembly information are separated with commas, for example, `Corp.Net.Authenticator, Corp, Version=1.0.5000.0, Culture=neutral, PublicKeyToken=&quot;00000000000000000&quot;`."
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "A string that identifies a type that implements an authentication module or <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref> if no value has been specified."
  overload: System.Net.Configuration.AuthenticationModuleElement.Type*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.AuthenticationModuleElement.#ctor
  parent: System.Net.Configuration.AuthenticationModuleElement
  isExternal: false
  name: AuthenticationModuleElement()
  nameWithType: AuthenticationModuleElement.AuthenticationModuleElement()
  fullName: System.Net.Configuration.AuthenticationModuleElement.AuthenticationModuleElement()
- uid: System.Net.Configuration.AuthenticationModuleElement.#ctor(System.String)
  parent: System.Net.Configuration.AuthenticationModuleElement
  isExternal: false
  name: AuthenticationModuleElement(String)
  nameWithType: AuthenticationModuleElement.AuthenticationModuleElement(String)
  fullName: System.Net.Configuration.AuthenticationModuleElement.AuthenticationModuleElement(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Net.Configuration.AuthenticationModuleElement.Properties
  parent: System.Net.Configuration.AuthenticationModuleElement
  isExternal: false
  name: Properties
  nameWithType: AuthenticationModuleElement.Properties
  fullName: System.Net.Configuration.AuthenticationModuleElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.AuthenticationModuleElement.Type
  parent: System.Net.Configuration.AuthenticationModuleElement
  isExternal: false
  name: Type
  nameWithType: AuthenticationModuleElement.Type
  fullName: System.Net.Configuration.AuthenticationModuleElement.Type
- uid: System.Net.Configuration.AuthenticationModuleElement.#ctor*
  parent: System.Net.Configuration.AuthenticationModuleElement
  isExternal: false
  name: AuthenticationModuleElement
  nameWithType: AuthenticationModuleElement.AuthenticationModuleElement
- uid: System.Net.Configuration.AuthenticationModuleElement.Properties*
  parent: System.Net.Configuration.AuthenticationModuleElement
  isExternal: false
  name: Properties
  nameWithType: AuthenticationModuleElement.Properties
- uid: System.Net.Configuration.AuthenticationModuleElement.Type*
  parent: System.Net.Configuration.AuthenticationModuleElement
  isExternal: false
  name: Type
  nameWithType: AuthenticationModuleElement.Type
