### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.WebProxyScriptElement
  id: WebProxyScriptElement
  children:
  - System.Net.Configuration.WebProxyScriptElement.#ctor
  - System.Net.Configuration.WebProxyScriptElement.DownloadTimeout
  - System.Net.Configuration.WebProxyScriptElement.PostDeserialize
  - System.Net.Configuration.WebProxyScriptElement.Properties
  langs:
  - csharp
  name: WebProxyScriptElement
  nameWithType: WebProxyScriptElement
  fullName: System.Net.Configuration.WebProxyScriptElement
  type: Class
  summary: "Represents information used to configure Web proxy scripts. This class cannot be inherited."
  syntax:
    content: 'public sealed class WebProxyScriptElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.WebProxyScriptElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.WebProxyScriptElement
  langs:
  - csharp
  name: WebProxyScriptElement()
  nameWithType: WebProxyScriptElement.WebProxyScriptElement()
  fullName: System.Net.Configuration.WebProxyScriptElement.WebProxyScriptElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Initializes an instance of the <see cref=&quot;T:System.Net.Configuration.WebProxyScriptElement&quot;></see> class."
  syntax:
    content: public WebProxyScriptElement ();
    parameters: []
  overload: System.Net.Configuration.WebProxyScriptElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.WebProxyScriptElement.DownloadTimeout
  id: DownloadTimeout
  parent: System.Net.Configuration.WebProxyScriptElement
  langs:
  - csharp
  name: DownloadTimeout
  nameWithType: WebProxyScriptElement.DownloadTimeout
  fullName: System.Net.Configuration.WebProxyScriptElement.DownloadTimeout
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Gets or sets the Web proxy script download timeout using the format hours:minutes:seconds."
  syntax:
    content: public TimeSpan DownloadTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "A &lt;xref:System.TimeSpan&gt; object that contains the timeout value. The default download timeout is one minute."
  overload: System.Net.Configuration.WebProxyScriptElement.DownloadTimeout*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.WebProxyScriptElement.PostDeserialize
  id: PostDeserialize
  parent: System.Net.Configuration.WebProxyScriptElement
  langs:
  - csharp
  name: PostDeserialize()
  nameWithType: WebProxyScriptElement.PostDeserialize()
  fullName: System.Net.Configuration.WebProxyScriptElement.PostDeserialize()
  type: Method
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override void PostDeserialize ();
    parameters: []
  overload: System.Net.Configuration.WebProxyScriptElement.PostDeserialize*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.WebProxyScriptElement.Properties
  id: Properties
  parent: System.Net.Configuration.WebProxyScriptElement
  langs:
  - csharp
  name: Properties
  nameWithType: WebProxyScriptElement.Properties
  fullName: System.Net.Configuration.WebProxyScriptElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Net.Configuration.WebProxyScriptElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.WebProxyScriptElement.#ctor
  parent: System.Net.Configuration.WebProxyScriptElement
  isExternal: false
  name: WebProxyScriptElement()
  nameWithType: WebProxyScriptElement.WebProxyScriptElement()
  fullName: System.Net.Configuration.WebProxyScriptElement.WebProxyScriptElement()
- uid: System.Net.Configuration.WebProxyScriptElement.DownloadTimeout
  parent: System.Net.Configuration.WebProxyScriptElement
  isExternal: false
  name: DownloadTimeout
  nameWithType: WebProxyScriptElement.DownloadTimeout
  fullName: System.Net.Configuration.WebProxyScriptElement.DownloadTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Net.Configuration.WebProxyScriptElement.PostDeserialize
  parent: System.Net.Configuration.WebProxyScriptElement
  isExternal: false
  name: PostDeserialize()
  nameWithType: WebProxyScriptElement.PostDeserialize()
  fullName: System.Net.Configuration.WebProxyScriptElement.PostDeserialize()
- uid: System.Net.Configuration.WebProxyScriptElement.Properties
  parent: System.Net.Configuration.WebProxyScriptElement
  isExternal: false
  name: Properties
  nameWithType: WebProxyScriptElement.Properties
  fullName: System.Net.Configuration.WebProxyScriptElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.WebProxyScriptElement.#ctor*
  parent: System.Net.Configuration.WebProxyScriptElement
  isExternal: false
  name: WebProxyScriptElement
  nameWithType: WebProxyScriptElement.WebProxyScriptElement
- uid: System.Net.Configuration.WebProxyScriptElement.DownloadTimeout*
  parent: System.Net.Configuration.WebProxyScriptElement
  isExternal: false
  name: DownloadTimeout
  nameWithType: WebProxyScriptElement.DownloadTimeout
- uid: System.Net.Configuration.WebProxyScriptElement.PostDeserialize*
  parent: System.Net.Configuration.WebProxyScriptElement
  isExternal: false
  name: PostDeserialize
  nameWithType: WebProxyScriptElement.PostDeserialize
- uid: System.Net.Configuration.WebProxyScriptElement.Properties*
  parent: System.Net.Configuration.WebProxyScriptElement
  isExternal: false
  name: Properties
  nameWithType: WebProxyScriptElement.Properties
