### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ProfileGroupSettings
  id: ProfileGroupSettings
  children:
  - System.Web.Configuration.ProfileGroupSettings.#ctor(System.String)
  - System.Web.Configuration.ProfileGroupSettings.Equals(System.Object)
  - System.Web.Configuration.ProfileGroupSettings.GetHashCode
  - System.Web.Configuration.ProfileGroupSettings.Name
  - System.Web.Configuration.ProfileGroupSettings.Properties
  - System.Web.Configuration.ProfileGroupSettings.PropertySettings
  langs:
  - csharp
  name: ProfileGroupSettings
  nameWithType: ProfileGroupSettings
  fullName: System.Web.Configuration.ProfileGroupSettings
  type: Class
  summary: "Provides programmatic access to the <xref uid=&quot;langword_csharp_group&quot; name=&quot;group&quot; href=&quot;&quot;></xref> subsection of the <xref uid=&quot;langword_csharp_profiles&quot; name=&quot;profiles&quot; href=&quot;&quot;></xref> configuration file section."
  remarks: "The ProfileGroupSettings class provides a way to programmatically create, access, and modify groups of properties added to the `group` subsection of the `profile` section of a configuration file.       The `profile` section of the configuration file specifies a schema for user profiles. At run time, the ASP.NET compilation system uses the information specified in the `profile` section to generate a class called `ProfileCommon`, which is derived from <xref:System.Web.Profile.ProfileBase>. The `ProfileCommon` class definition is based on the properties defined in the `properties` subsection of the `profile` section of the configuration file. An instance of this class is created for each user profile, and you can access the individual profile values in your code through the <xref:System.Web.HttpContext.Profile%2A?displayProperty=fullName> property. For more information about the profile features added to [!INCLUDE[vstecasplong](~/add/includes/vstecasplong-md.md)], see [ASP.NET Profile Properties Overview](../Topic/ASP.NET%20Profile%20Properties%20Overview.md)."
  example:
  - "The following code example shows how to use the ProfileGroupSettings type. This code example is part of a larger example provided for the <xref:System.Web.Configuration.ProfileSection> class.  \n  \n [!code-cs[System.Web.Configuration.ProfileSection#13](~/add/codesnippet/CSharp/t-system.web.configurati_94_1.cs)]\n [!code-vb[System.Web.Configuration.ProfileSection#13](~/add/codesnippet/VisualBasic/t-system.web.configurati_94_1.vb)]"
  syntax:
    content: 'public sealed class ProfileGroupSettings : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.ProfileGroupSettings.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Web.Configuration.ProfileGroupSettings
  langs:
  - csharp
  name: ProfileGroupSettings(String)
  nameWithType: ProfileGroupSettings.ProfileGroupSettings(String)
  fullName: System.Web.Configuration.ProfileGroupSettings.ProfileGroupSettings(String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Web.Configuration.ProfileGroupSettings&quot;></see> class using default settings."
  remarks: "The ProfileGroupSettings constructor is not intended to be used directly from your code. It is called by the ASP.NET configuration system. You obtain an instance of the <xref:System.Web.Configuration.ProfileGroupSettings> class by using the <xref:System.Configuration.Configuration.GetSection%2A> method."
  syntax:
    content: public ProfileGroupSettings (string name);
    parameters:
    - id: name
      type: System.String
      description: "The name of the new group."
  overload: System.Web.Configuration.ProfileGroupSettings.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.ProfileGroupSettings.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.Web.Configuration.ProfileGroupSettings
  langs:
  - csharp
  name: Equals(Object)
  nameWithType: ProfileGroupSettings.Equals(Object)
  fullName: System.Web.Configuration.ProfileGroupSettings.Equals(Object)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Determines whether the specified <xref uid=&quot;langword_csharp_Object&quot; name=&quot;Object&quot; href=&quot;&quot;></xref> is equal to the current <xref uid=&quot;langword_csharp_Object&quot; name=&quot;Object&quot; href=&quot;&quot;></xref>."
  syntax:
    content: public override bool Equals (object obj);
    parameters:
    - id: obj
      type: System.Object
      description: "The <xref:System.Object> to compare with the current ."
    return:
      type: System.Boolean
      description: "To be added."
  overload: System.Web.Configuration.ProfileGroupSettings.Equals*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.ProfileGroupSettings.GetHashCode
  id: GetHashCode
  parent: System.Web.Configuration.ProfileGroupSettings
  langs:
  - csharp
  name: GetHashCode()
  nameWithType: ProfileGroupSettings.GetHashCode()
  fullName: System.Web.Configuration.ProfileGroupSettings.GetHashCode()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets a unique value representing the current <see cref=&quot;T:System.Configuration.ConfigurationElement&quot;></see> instance."
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: "To be added."
  overload: System.Web.Configuration.ProfileGroupSettings.GetHashCode*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.ProfileGroupSettings.Name
  id: Name
  parent: System.Web.Configuration.ProfileGroupSettings
  langs:
  - csharp
  name: Name
  nameWithType: ProfileGroupSettings.Name
  fullName: System.Web.Configuration.ProfileGroupSettings.Name
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets or sets name of the group of <see cref=&quot;T:System.Web.Configuration.ProfilePropertySettings&quot;></see> objects this object contains."
  remarks: "The group name must be unique within a <xref:System.Web.Configuration.ProfileGroupSettingsCollection> collection; otherwise, an exception is raised when the configuration file is saved."
  example:
  - "The following code example shows how to use the Name property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.ProfileSection> class.  \n  \n [!code-cs[System.Web.Configuration.ProfileSection#12](~/add/codesnippet/CSharp/p-system.web.configurati_232_1.cs)]\n [!code-vb[System.Web.Configuration.ProfileSection#12](~/add/codesnippet/VisualBasic/p-system.web.configurati_232_1.vb)]"
  syntax:
    content: public string Name { get; }
    return:
      type: System.String
      description: "A string containing the name of the group of <see cref=&quot;T:System.Web.Configuration.ProfilePropertySettings&quot;></see> objects this object contains. The default value is an empty string (&quot;&quot;)."
  overload: System.Web.Configuration.ProfileGroupSettings.Name*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.ProfileGroupSettings.Properties
  id: Properties
  parent: System.Web.Configuration.ProfileGroupSettings
  langs:
  - csharp
  name: Properties
  nameWithType: ProfileGroupSettings.Properties
  fullName: System.Web.Configuration.ProfileGroupSettings.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Web.Configuration.ProfileGroupSettings.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.ProfileGroupSettings.PropertySettings
  id: PropertySettings
  parent: System.Web.Configuration.ProfileGroupSettings
  langs:
  - csharp
  name: PropertySettings
  nameWithType: ProfileGroupSettings.PropertySettings
  fullName: System.Web.Configuration.ProfileGroupSettings.PropertySettings
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets the collection of profile property settings this object contains."
  remarks: ''
  example:
  - "The following code example shows how to use the PropertySettings property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.ProfileSection> class.  \n  \n [!code-cs[System.Web.Configuration.ProfileSection#12](~/add/codesnippet/CSharp/p-system.web.configurati_256_1.cs)]\n [!code-vb[System.Web.Configuration.ProfileSection#12](~/add/codesnippet/VisualBasic/p-system.web.configurati_256_1.vb)]"
  syntax:
    content: public System.Web.Configuration.ProfilePropertySettingsCollection PropertySettings { get; }
    return:
      type: System.Web.Configuration.ProfilePropertySettingsCollection
      description: "A <see cref=&quot;T:System.Web.Configuration.ProfilePropertySettingsCollection&quot;></see> collection that contains all the <see cref=&quot;T:System.Web.Configuration.ProfilePropertySettings&quot;></see> objects contained in this group."
  overload: System.Web.Configuration.ProfileGroupSettings.PropertySettings*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.ProfileGroupSettings.#ctor(System.String)
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: ProfileGroupSettings(String)
  nameWithType: ProfileGroupSettings.ProfileGroupSettings(String)
  fullName: System.Web.Configuration.ProfileGroupSettings.ProfileGroupSettings(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.ProfileGroupSettings.Equals(System.Object)
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: Equals(Object)
  nameWithType: ProfileGroupSettings.Equals(Object)
  fullName: System.Web.Configuration.ProfileGroupSettings.Equals(Object)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.ProfileGroupSettings.GetHashCode
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: GetHashCode()
  nameWithType: ProfileGroupSettings.GetHashCode()
  fullName: System.Web.Configuration.ProfileGroupSettings.GetHashCode()
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.ProfileGroupSettings.Name
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: Name
  nameWithType: ProfileGroupSettings.Name
  fullName: System.Web.Configuration.ProfileGroupSettings.Name
- uid: System.Web.Configuration.ProfileGroupSettings.Properties
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: Properties
  nameWithType: ProfileGroupSettings.Properties
  fullName: System.Web.Configuration.ProfileGroupSettings.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.ProfileGroupSettings.PropertySettings
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: PropertySettings
  nameWithType: ProfileGroupSettings.PropertySettings
  fullName: System.Web.Configuration.ProfileGroupSettings.PropertySettings
- uid: System.Web.Configuration.ProfilePropertySettingsCollection
  parent: System.Web.Configuration
  isExternal: false
  name: ProfilePropertySettingsCollection
  nameWithType: ProfilePropertySettingsCollection
  fullName: System.Web.Configuration.ProfilePropertySettingsCollection
- uid: System.Web.Configuration.ProfileGroupSettings.#ctor*
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: ProfileGroupSettings
  nameWithType: ProfileGroupSettings.ProfileGroupSettings
- uid: System.Web.Configuration.ProfileGroupSettings.Equals*
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: Equals
  nameWithType: ProfileGroupSettings.Equals
- uid: System.Web.Configuration.ProfileGroupSettings.GetHashCode*
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: GetHashCode
  nameWithType: ProfileGroupSettings.GetHashCode
- uid: System.Web.Configuration.ProfileGroupSettings.Name*
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: Name
  nameWithType: ProfileGroupSettings.Name
- uid: System.Web.Configuration.ProfileGroupSettings.Properties*
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: Properties
  nameWithType: ProfileGroupSettings.Properties
- uid: System.Web.Configuration.ProfileGroupSettings.PropertySettings*
  parent: System.Web.Configuration.ProfileGroupSettings
  isExternal: false
  name: PropertySettings
  nameWithType: ProfileGroupSettings.PropertySettings
