### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Routing.Configuration.NamespaceElement
  id: NamespaceElement
  children:
  - System.ServiceModel.Routing.Configuration.NamespaceElement.#ctor
  - System.ServiceModel.Routing.Configuration.NamespaceElement.Namespace
  - System.ServiceModel.Routing.Configuration.NamespaceElement.Prefix
  langs:
  - csharp
  name: NamespaceElement
  nameWithType: NamespaceElement
  fullName: System.ServiceModel.Routing.Configuration.NamespaceElement
  type: Class
  summary: "Represents a configuration element that defines the namespace element. This contains namespaces to namespace prefix mappings that can then be used in XPath filters."
  remarks: "The default namespaces and prefixes that are understood are shown in the following table.      |||   |-|-|   |Prefix|Namespace|   |s11|http://schemas.xmlsoap.org/soap/envelope|   |s12|http://www.w3.org/2003/05/soap-envelope|   |wsaAugust2004|http://schemas.xmlsoap.org/ws/2004/08/addressing|   |wsa10|http://www.w3.org/2005/08/addressing|   |sm|http://schemas.microsoft.com/serviceModel/2004/05/xpathfunctions|   |tempuri|http://tempuri.org|   |ser|http://schemas.microsoft.com/2003/10/Serialization|"
  syntax:
    content: 'public class NamespaceElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.NamespaceElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Routing.Configuration.NamespaceElement
  langs:
  - csharp
  name: NamespaceElement()
  nameWithType: NamespaceElement.NamespaceElement()
  fullName: System.ServiceModel.Routing.Configuration.NamespaceElement.NamespaceElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Routing.Configuration.NamespaceElement&quot;></see>."
  syntax:
    content: public NamespaceElement ();
    parameters: []
  overload: System.ServiceModel.Routing.Configuration.NamespaceElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.NamespaceElement.Namespace
  id: Namespace
  parent: System.ServiceModel.Routing.Configuration.NamespaceElement
  langs:
  - csharp
  name: Namespace
  nameWithType: NamespaceElement.Namespace
  fullName: System.ServiceModel.Routing.Configuration.NamespaceElement.Namespace
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Gets or sets the namespace for this configuration element."
  syntax:
    content: public string Namespace { get; set; }
    return:
      type: System.String
      description: "The namespace of this element."
  overload: System.ServiceModel.Routing.Configuration.NamespaceElement.Namespace*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.NamespaceElement.Prefix
  id: Prefix
  parent: System.ServiceModel.Routing.Configuration.NamespaceElement
  langs:
  - csharp
  name: Prefix
  nameWithType: NamespaceElement.Prefix
  fullName: System.ServiceModel.Routing.Configuration.NamespaceElement.Prefix
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Gets or sets the namespace prefix for this configuration element."
  syntax:
    content: public string Prefix { get; set; }
    return:
      type: System.String
      description: "The namespace prefix of this element."
  overload: System.ServiceModel.Routing.Configuration.NamespaceElement.Prefix*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Routing.Configuration.NamespaceElement.#ctor
  parent: System.ServiceModel.Routing.Configuration.NamespaceElement
  isExternal: false
  name: NamespaceElement()
  nameWithType: NamespaceElement.NamespaceElement()
  fullName: System.ServiceModel.Routing.Configuration.NamespaceElement.NamespaceElement()
- uid: System.ServiceModel.Routing.Configuration.NamespaceElement.Namespace
  parent: System.ServiceModel.Routing.Configuration.NamespaceElement
  isExternal: false
  name: Namespace
  nameWithType: NamespaceElement.Namespace
  fullName: System.ServiceModel.Routing.Configuration.NamespaceElement.Namespace
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Routing.Configuration.NamespaceElement.Prefix
  parent: System.ServiceModel.Routing.Configuration.NamespaceElement
  isExternal: false
  name: Prefix
  nameWithType: NamespaceElement.Prefix
  fullName: System.ServiceModel.Routing.Configuration.NamespaceElement.Prefix
- uid: System.ServiceModel.Routing.Configuration.NamespaceElement.#ctor*
  parent: System.ServiceModel.Routing.Configuration.NamespaceElement
  isExternal: false
  name: NamespaceElement
  nameWithType: NamespaceElement.NamespaceElement
- uid: System.ServiceModel.Routing.Configuration.NamespaceElement.Namespace*
  parent: System.ServiceModel.Routing.Configuration.NamespaceElement
  isExternal: false
  name: Namespace
  nameWithType: NamespaceElement.Namespace
- uid: System.ServiceModel.Routing.Configuration.NamespaceElement.Prefix*
  parent: System.ServiceModel.Routing.Configuration.NamespaceElement
  isExternal: false
  name: Prefix
  nameWithType: NamespaceElement.Prefix
