### YamlMime:ManagedReference
items:
- uid: System.Configuration.ProtectedConfiguration
  id: ProtectedConfiguration
  children:
  - System.Configuration.ProtectedConfiguration.DataProtectionProviderName
  - System.Configuration.ProtectedConfiguration.DefaultProvider
  - System.Configuration.ProtectedConfiguration.ProtectedDataSectionName
  - System.Configuration.ProtectedConfiguration.Providers
  - System.Configuration.ProtectedConfiguration.RsaProviderName
  langs:
  - csharp
  name: ProtectedConfiguration
  nameWithType: ProtectedConfiguration
  fullName: System.Configuration.ProtectedConfiguration
  type: Class
  summary: "Provides access to the protected-configuration providers for the current application&quot;s configuration file."
  remarks: "The ProtectedConfiguration class allows you to obtain information about the providers available to protect sensitive configuration data. You typically use the standard providers, but you can also create custom providers by deriving from the <xref:System.Configuration.ProtectedConfigurationProvider> class.       For more information about protected configuration, see [Encrypting Configuration Information Using Protected Configuration](../Topic/Encrypting%20Configuration%20Information%20Using%20Protected%20Configuration.md)."
  example:
  - "The following example shows how to use the ProtectedConfiguration class to retrieve a collection of protected-configuration providers and discover their provider name, RSA provider name, and section names.  \n  \n [!code-cs[System.Configuration.ProtectedConfiguration#1](~/add/codesnippet/CSharp/t-system.configuration.p_4_1.cs)]\n [!code-vb[System.Configuration.ProtectedConfiguration#1](~/add/codesnippet/VisualBasic/t-system.configuration.p_4_1.vb)]"
  syntax:
    content: public static class ProtectedConfiguration
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProtectedConfiguration.DataProtectionProviderName
  id: DataProtectionProviderName
  parent: System.Configuration.ProtectedConfiguration
  langs:
  - csharp
  name: DataProtectionProviderName
  nameWithType: ProtectedConfiguration.DataProtectionProviderName
  fullName: System.Configuration.ProtectedConfiguration.DataProtectionProviderName
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "The name of the data protection provider."
  remarks: "This a constant string variable that contains the name of the data-protection provider made available by the system to protect a configuration section."
  example:
  - "The following example shows how to use the DataProtectionProviderName property to retrieve the name of the current data-protection provider.  \n  \n [!code-cs[System.Configuration.ProtectedConfiguration#4](~/add/codesnippet/CSharp/f-system.configuration.p_2_1.cs)]\n [!code-vb[System.Configuration.ProtectedConfiguration#4](~/add/codesnippet/VisualBasic/f-system.configuration.p_2_1.vb)]"
  syntax:
    content: public const string DataProtectionProviderName;
    return:
      type: System.String
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProtectedConfiguration.DefaultProvider
  id: DefaultProvider
  parent: System.Configuration.ProtectedConfiguration
  langs:
  - csharp
  name: DefaultProvider
  nameWithType: ProtectedConfiguration.DefaultProvider
  fullName: System.Configuration.ProtectedConfiguration.DefaultProvider
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets the name of the default protected-configuration provider."
  remarks: "The default provider is identified by the `defaultProvider` attribute of the `<configProtectedData>` configuration-file element. The value must correspond to the name of one of the providers added in the `<providers>` subsection of the `<configProtectedData>` section. The `<configProtectedData>` section can also be accessed through an instance of the <xref:System.Configuration.ProtectedConfigurationSection> class."
  syntax:
    content: public static string DefaultProvider { get; }
    return:
      type: System.String
      description: "The name of the default protected-configuration provider."
  overload: System.Configuration.ProtectedConfiguration.DefaultProvider*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProtectedConfiguration.ProtectedDataSectionName
  id: ProtectedDataSectionName
  parent: System.Configuration.ProtectedConfiguration
  langs:
  - csharp
  name: ProtectedDataSectionName
  nameWithType: ProtectedConfiguration.ProtectedDataSectionName
  fullName: System.Configuration.ProtectedConfiguration.ProtectedDataSectionName
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "The name of the protected data section."
  remarks: "This is a constant string variable that contains the name of the protected data section."
  example:
  - "The following example shows how to use the ProtectedDataSectionName property to retrieve the name of a protected data section.  \n  \n [!code-cs[System.Configuration.ProtectedConfiguration#6](~/add/codesnippet/CSharp/f-system.configuration.p_0_1.cs)]\n [!code-vb[System.Configuration.ProtectedConfiguration#6](~/add/codesnippet/VisualBasic/f-system.configuration.p_0_1.vb)]"
  syntax:
    content: public const string ProtectedDataSectionName;
    return:
      type: System.String
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProtectedConfiguration.Providers
  id: Providers
  parent: System.Configuration.ProtectedConfiguration
  langs:
  - csharp
  name: Providers
  nameWithType: ProtectedConfiguration.Providers
  fullName: System.Configuration.ProtectedConfiguration.Providers
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets a collection of the installed protected-configuration providers."
  remarks: ''
  example:
  - "The following example shows how to use the Providers property to retrieve the collection of installed <xref:System.Configuration.ProtectedConfigurationProvider> objects.  \n  \n [!code-cs[System.Configuration.ProtectedConfiguration#3](~/add/codesnippet/CSharp/p-system.configuration.p_16_1.cs)]\n [!code-vb[System.Configuration.ProtectedConfiguration#3](~/add/codesnippet/VisualBasic/p-system.configuration.p_16_1.vb)]"
  syntax:
    content: public static System.Configuration.ProtectedConfigurationProviderCollection Providers { get; }
    return:
      type: System.Configuration.ProtectedConfigurationProviderCollection
      description: "A <see cref=&quot;T:System.Configuration.ProtectedConfigurationProviderCollection&quot;></see> collection of installed <see cref=&quot;T:System.Configuration.ProtectedConfigurationProvider&quot;></see> objects."
  overload: System.Configuration.ProtectedConfiguration.Providers*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProtectedConfiguration.RsaProviderName
  id: RsaProviderName
  parent: System.Configuration.ProtectedConfiguration
  langs:
  - csharp
  name: RsaProviderName
  nameWithType: ProtectedConfiguration.RsaProviderName
  fullName: System.Configuration.ProtectedConfiguration.RsaProviderName
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "The name of the RSA provider."
  remarks: "This a constant string variable that contains the name of the RSA provider made available by the system to protect a configuration section."
  example:
  - "The following example shows how to use the RsaProviderName property to retrieve the name of the current RSA provider.  \n  \n [!code-cs[System.Configuration.ProtectedConfiguration#5](~/add/codesnippet/CSharp/f-system.configuration.p_1_1.cs)]\n [!code-vb[System.Configuration.ProtectedConfiguration#5](~/add/codesnippet/VisualBasic/f-system.configuration.p_1_1.vb)]"
  syntax:
    content: public const string RsaProviderName;
    return:
      type: System.String
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ProtectedConfiguration.DataProtectionProviderName
  parent: System.Configuration.ProtectedConfiguration
  isExternal: false
  name: DataProtectionProviderName
  nameWithType: ProtectedConfiguration.DataProtectionProviderName
  fullName: System.Configuration.ProtectedConfiguration.DataProtectionProviderName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ProtectedConfiguration.DefaultProvider
  parent: System.Configuration.ProtectedConfiguration
  isExternal: false
  name: DefaultProvider
  nameWithType: ProtectedConfiguration.DefaultProvider
  fullName: System.Configuration.ProtectedConfiguration.DefaultProvider
- uid: System.Configuration.ProtectedConfiguration.ProtectedDataSectionName
  parent: System.Configuration.ProtectedConfiguration
  isExternal: false
  name: ProtectedDataSectionName
  nameWithType: ProtectedConfiguration.ProtectedDataSectionName
  fullName: System.Configuration.ProtectedConfiguration.ProtectedDataSectionName
- uid: System.Configuration.ProtectedConfiguration.Providers
  parent: System.Configuration.ProtectedConfiguration
  isExternal: false
  name: Providers
  nameWithType: ProtectedConfiguration.Providers
  fullName: System.Configuration.ProtectedConfiguration.Providers
- uid: System.Configuration.ProtectedConfigurationProviderCollection
  parent: System.Configuration
  isExternal: false
  name: ProtectedConfigurationProviderCollection
  nameWithType: ProtectedConfigurationProviderCollection
  fullName: System.Configuration.ProtectedConfigurationProviderCollection
- uid: System.Configuration.ProtectedConfiguration.RsaProviderName
  parent: System.Configuration.ProtectedConfiguration
  isExternal: false
  name: RsaProviderName
  nameWithType: ProtectedConfiguration.RsaProviderName
  fullName: System.Configuration.ProtectedConfiguration.RsaProviderName
- uid: System.Configuration.ProtectedConfiguration.DefaultProvider*
  parent: System.Configuration.ProtectedConfiguration
  isExternal: false
  name: DefaultProvider
  nameWithType: ProtectedConfiguration.DefaultProvider
- uid: System.Configuration.ProtectedConfiguration.Providers*
  parent: System.Configuration.ProtectedConfiguration
  isExternal: false
  name: Providers
  nameWithType: ProtectedConfiguration.Providers
