### YamlMime:ManagedReference
items:
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata
  id: ProfilePropertyMetadata
  children:
  - System.Web.ApplicationServices.ProfilePropertyMetadata.#ctor
  - System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess
  - System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue
  - System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData
  - System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly
  - System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName
  - System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs
  - System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName
  langs:
  - csharp
  name: ProfilePropertyMetadata
  nameWithType: ProfilePropertyMetadata
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata
  type: Class
  summary: "Provides a collection of values that describe a profile property."
  remarks: "You use the ProfilePropertyMetadata class to retrieve information about a profile property when you access profiles through the <xref:System.Web.ApplicationServices.ProfileService> class. You can retrieve the name and type of the property, whether it is read-only, whether it can be accessed by users who have not been authenticated, and the default value. An application can take the appropriate actions based on these values, such as not trying to set a read-only property.       To access the ProfilePropertyMetadata object from an application that is compatible with the Windows Communication Framework (WCF), use the <xref:System.Web.ApplicationServices.ProfileService.GetPropertiesMetadata%2A> method of the <xref:System.Web.ApplicationServices.ProfileService> class. The user does not have to be logged on to retrieve the ProfilePropertyMetadata object because the metadata for profile properties is not specific to a user&quot;s profile property values.       The values in the ProfilePropertyMetadata class are set in the Web.config file in the  element of the  section when the property is defined."
  syntax:
    content: >-
      [System.Runtime.Serialization.DataContract]

      public class ProfilePropertyMetadata : System.Runtime.Serialization.IExtensibleDataObject
  inheritance:
  - System.Object
  implements:
  - System.Runtime.Serialization.IExtensibleDataObject
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.#ctor
  id: '#ctor'
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: ProfilePropertyMetadata()
  nameWithType: ProfilePropertyMetadata.ProfilePropertyMetadata()
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.ProfilePropertyMetadata()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Web.ApplicationServices.ProfilePropertyMetadata&quot;></see> class."
  syntax:
    content: public ProfilePropertyMetadata ();
    parameters: []
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess
  id: AllowAnonymousAccess
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: AllowAnonymousAccess
  nameWithType: ProfilePropertyMetadata.AllowAnonymousAccess
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Gets or sets a value that indicates whether the property is available to unauthenticated users."
  remarks: "When you enable anonymous identification with settings in the  element, you can set which profile properties are available to anonymous users. You set the AllowAnonymousAccess property in the  element of the  section of the Web.config file when the property is defined. From the client application, use the AllowAnonymousAccess property to determine whether a profile property can be set for an anonymous user."
  syntax:
    content: public bool AllowAnonymousAccess { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if the property is available to unauthenticated users; otherwise, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>."
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue
  id: DefaultValue
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: DefaultValue
  nameWithType: ProfilePropertyMetadata.DefaultValue
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Gets or sets the default value of the property."
  remarks: "The serialized format of the DefaultValue property is determined by the <xref:System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs%2A> property of the <xref:System.Web.ApplicationServices.ProfilePropertyMetadata> class."
  syntax:
    content: public string DefaultValue { get; set; }
    return:
      type: System.String
      description: "A serialized representation of the default value for the property, if a default value is defined in the Web.config file; otherwise the string &quot;(null)&quot;."
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData
  id: ExtensionData
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: ExtensionData
  nameWithType: ProfilePropertyMetadata.ExtensionData
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Gets or sets a reference to an <see cref=&quot;T:System.Runtime.Serialization.ExtensionDataObject&quot;></see> instance."
  syntax:
    content: public System.Runtime.Serialization.ExtensionDataObject ExtensionData { get; set; }
    return:
      type: System.Runtime.Serialization.ExtensionDataObject
      description: "A reference to an object that stores extended data during deserialization operations."
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly
  id: IsReadOnly
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: IsReadOnly
  nameWithType: ProfilePropertyMetadata.IsReadOnly
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Gets or sets a value that indicates whether a profile property is read-only."
  remarks: "You set the IsReadOnly property in the  element of the  section of the Web.config file when the property is defined."
  syntax:
    content: public bool IsReadOnly { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if the profile property is read-only; otherwise, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>."
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName
  id: PropertyName
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: PropertyName
  nameWithType: ProfilePropertyMetadata.PropertyName
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Gets or sets the name of the profile property."
  remarks: "You set the PropertyName property in the  element of the  section of the Web.config file when the property is defined."
  syntax:
    content: public string PropertyName { get; set; }
    return:
      type: System.String
      description: "The name of the profile property as defined in the Web.config file."
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs
  id: SerializeAs
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: SerializeAs
  nameWithType: ProfilePropertyMetadata.SerializeAs
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Gets or sets a value that indicates how to serialize the property value."
  remarks: "You set the SerializeAs property in the  element of the  section of the Web.config file when the property is defined."
  syntax:
    content: public int SerializeAs { get; set; }
    return:
      type: System.Int32
      description: "The enumeration value."
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName
  id: TypeName
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: TypeName
  nameWithType: ProfilePropertyMetadata.TypeName
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Gets or sets the assembly-qualified name of the profile property type."
  remarks: "You set the TypeName property in the  element of the  section of the Web.config file when the property is defined."
  syntax:
    content: public string TypeName { get; set; }
    return:
      type: System.String
      description: "The assembly-qualified name of the profile property type."
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.#ctor
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: ProfilePropertyMetadata()
  nameWithType: ProfilePropertyMetadata.ProfilePropertyMetadata()
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.ProfilePropertyMetadata()
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: AllowAnonymousAccess
  nameWithType: ProfilePropertyMetadata.AllowAnonymousAccess
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: DefaultValue
  nameWithType: ProfilePropertyMetadata.DefaultValue
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: ExtensionData
  nameWithType: ProfilePropertyMetadata.ExtensionData
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData
- uid: System.Runtime.Serialization.ExtensionDataObject
  parent: System.Runtime.Serialization
  isExternal: false
  name: ExtensionDataObject
  nameWithType: ExtensionDataObject
  fullName: System.Runtime.Serialization.ExtensionDataObject
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: IsReadOnly
  nameWithType: ProfilePropertyMetadata.IsReadOnly
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: PropertyName
  nameWithType: ProfilePropertyMetadata.PropertyName
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: SerializeAs
  nameWithType: ProfilePropertyMetadata.SerializeAs
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: TypeName
  nameWithType: ProfilePropertyMetadata.TypeName
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.#ctor*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: ProfilePropertyMetadata
  nameWithType: ProfilePropertyMetadata.ProfilePropertyMetadata
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: AllowAnonymousAccess
  nameWithType: ProfilePropertyMetadata.AllowAnonymousAccess
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: DefaultValue
  nameWithType: ProfilePropertyMetadata.DefaultValue
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: ExtensionData
  nameWithType: ProfilePropertyMetadata.ExtensionData
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: IsReadOnly
  nameWithType: ProfilePropertyMetadata.IsReadOnly
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: PropertyName
  nameWithType: ProfilePropertyMetadata.PropertyName
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: SerializeAs
  nameWithType: ProfilePropertyMetadata.SerializeAs
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: TypeName
  nameWithType: ProfilePropertyMetadata.TypeName
