### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ProtocolsSection
  id: ProtocolsSection
  children:
  - System.Web.Configuration.ProtocolsSection.#ctor
  - System.Web.Configuration.ProtocolsSection.Properties
  - System.Web.Configuration.ProtocolsSection.Protocols
  langs:
  - csharp
  name: ProtocolsSection
  nameWithType: ProtocolsSection
  fullName: System.Web.Configuration.ProtocolsSection
  type: Class
  summary: "Represents the <xref uid=&quot;langword_csharp_protocols&quot; name=&quot;protocols&quot; href=&quot;&quot;></xref> section of the Web configuration file."
  remarks: "The ProtocolsSection class was introduced in the .NET Framework version 3.5. For more information, see [Versions and Dependencies](../Topic/.NET%20Framework%20Versions%20and%20Dependencies.md)."
  syntax:
    content: 'public sealed class ProtocolsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.ProtocolsSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.ProtocolsSection
  langs:
  - csharp
  name: ProtocolsSection()
  nameWithType: ProtocolsSection.ProtocolsSection()
  fullName: System.Web.Configuration.ProtocolsSection.ProtocolsSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Web.Configuration.ProtocolsSection&quot;></see> class."
  syntax:
    content: public ProtocolsSection ();
    parameters: []
  overload: System.Web.Configuration.ProtocolsSection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.ProtocolsSection.Properties
  id: Properties
  parent: System.Web.Configuration.ProtocolsSection
  langs:
  - csharp
  name: Properties
  nameWithType: ProtocolsSection.Properties
  fullName: System.Web.Configuration.ProtocolsSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Web.Configuration.ProtocolsSection.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.ProtocolsSection.Protocols
  id: Protocols
  parent: System.Web.Configuration.ProtocolsSection
  langs:
  - csharp
  name: Protocols
  nameWithType: ProtocolsSection.Protocols
  fullName: System.Web.Configuration.ProtocolsSection.Protocols
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets the <xref uid=&quot;langword_csharp_protocols&quot; name=&quot;protocols&quot; href=&quot;&quot;></xref> collection of the protocols section."
  syntax:
    content: public System.Web.Configuration.ProtocolCollection Protocols { get; }
    return:
      type: System.Web.Configuration.ProtocolCollection
      description: "The protocols collection of the <xref uid=&quot;langword_csharp_protocols&quot; name=&quot;protocols&quot; href=&quot;&quot;></xref> section."
  overload: System.Web.Configuration.ProtocolsSection.Protocols*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.ProtocolsSection.#ctor
  parent: System.Web.Configuration.ProtocolsSection
  isExternal: false
  name: ProtocolsSection()
  nameWithType: ProtocolsSection.ProtocolsSection()
  fullName: System.Web.Configuration.ProtocolsSection.ProtocolsSection()
- uid: System.Web.Configuration.ProtocolsSection.Properties
  parent: System.Web.Configuration.ProtocolsSection
  isExternal: false
  name: Properties
  nameWithType: ProtocolsSection.Properties
  fullName: System.Web.Configuration.ProtocolsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.ProtocolsSection.Protocols
  parent: System.Web.Configuration.ProtocolsSection
  isExternal: false
  name: Protocols
  nameWithType: ProtocolsSection.Protocols
  fullName: System.Web.Configuration.ProtocolsSection.Protocols
- uid: System.Web.Configuration.ProtocolCollection
  parent: System.Web.Configuration
  isExternal: false
  name: ProtocolCollection
  nameWithType: ProtocolCollection
  fullName: System.Web.Configuration.ProtocolCollection
- uid: System.Web.Configuration.ProtocolsSection.#ctor*
  parent: System.Web.Configuration.ProtocolsSection
  isExternal: false
  name: ProtocolsSection
  nameWithType: ProtocolsSection.ProtocolsSection
- uid: System.Web.Configuration.ProtocolsSection.Properties*
  parent: System.Web.Configuration.ProtocolsSection
  isExternal: false
  name: Properties
  nameWithType: ProtocolsSection.Properties
- uid: System.Web.Configuration.ProtocolsSection.Protocols*
  parent: System.Web.Configuration.ProtocolsSection
  isExternal: false
  name: Protocols
  nameWithType: ProtocolsSection.Protocols
