### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.PriorityGroup
  id: PriorityGroup
  children:
  - System.Web.Services.Configuration.PriorityGroup.High
  - System.Web.Services.Configuration.PriorityGroup.Low
  langs:
  - csharp
  name: PriorityGroup
  nameWithType: PriorityGroup
  fullName: System.Web.Services.Configuration.PriorityGroup
  type: Enum
  summary: "Specifies the values that can be used to set the priority and group attributes for a SOAP extension in the Web Services configuration file."
  syntax:
    content: public enum PriorityGroup
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Services.Configuration.PriorityGroup.High
  id: High
  parent: System.Web.Services.Configuration.PriorityGroup
  langs:
  - csharp
  name: High
  nameWithType: PriorityGroup.High
  fullName: System.Web.Services.Configuration.PriorityGroup.High
  type: Field
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Represents the value 1. Indicates that the SOAP extension executes in the group of SOAP extensions with the highest priority."
  syntax:
    content: High
    return:
      type: System.Web.Services.Configuration.PriorityGroup
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Services.Configuration.PriorityGroup.Low
  id: Low
  parent: System.Web.Services.Configuration.PriorityGroup
  langs:
  - csharp
  name: Low
  nameWithType: PriorityGroup.Low
  fullName: System.Web.Services.Configuration.PriorityGroup.Low
  type: Field
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Represents the value 0. Indicates that the SOAP extension executes in the group of SOAP extensions with the lowest priority."
  syntax:
    content: Low
    return:
      type: System.Web.Services.Configuration.PriorityGroup
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Services.Configuration.PriorityGroup.High
  parent: System.Web.Services.Configuration.PriorityGroup
  isExternal: false
  name: High
  nameWithType: PriorityGroup.High
  fullName: System.Web.Services.Configuration.PriorityGroup.High
- uid: System.Web.Services.Configuration.PriorityGroup
  parent: System.Web.Services.Configuration
  isExternal: false
  name: PriorityGroup
  nameWithType: PriorityGroup
  fullName: System.Web.Services.Configuration.PriorityGroup
- uid: System.Web.Services.Configuration.PriorityGroup.Low
  parent: System.Web.Services.Configuration.PriorityGroup
  isExternal: false
  name: Low
  nameWithType: PriorityGroup.Low
  fullName: System.Web.Services.Configuration.PriorityGroup.Low
