### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection
  id: TrackingSection
  children:
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.#ctor
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.Profiles
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.Properties
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.TrackingProfiles
  langs:
  - csharp
  name: TrackingSection
  nameWithType: TrackingSection
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection
  type: Class
  summary: "A configuration section for specifying tracking settings."
  syntax:
    content: 'public class TrackingSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection
  langs:
  - csharp
  name: TrackingSection()
  nameWithType: TrackingSection.TrackingSection()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.TrackingSection()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Activities.Tracking.Configuration.TrackingSection&quot;></see> class."
  syntax:
    content: public TrackingSection ();
    parameters: []
  overload: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.Profiles
  id: Profiles
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection
  langs:
  - csharp
  name: Profiles
  nameWithType: TrackingSection.Profiles
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.Profiles
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Gets a collection of <see cref=&quot;T:System.ServiceModel.Activities.Tracking.Configuration.ProfileElement&quot;></see> elements."
  syntax:
    content: public System.ServiceModel.Activities.Tracking.Configuration.ProfileElementCollection Profiles { get; }
    return:
      type: System.ServiceModel.Activities.Tracking.Configuration.ProfileElementCollection
      description: "A collection of elements."
  overload: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.Profiles*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection
  langs:
  - csharp
  name: Properties
  nameWithType: TrackingSection.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Gets the collection of properties."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "The collection of properties for the element."
  overload: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.TrackingProfiles
  id: TrackingProfiles
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection
  langs:
  - csharp
  name: TrackingProfiles
  nameWithType: TrackingSection.TrackingProfiles
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.TrackingProfiles
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Gets a collection of <see cref=&quot;T:System.Activities.Tracking.TrackingProfile&quot;></see> objects."
  syntax:
    content: public System.Collections.ObjectModel.Collection<System.Activities.Tracking.TrackingProfile> TrackingProfiles { get; }
    return:
      type: System.Collections.ObjectModel.Collection{System.Activities.Tracking.TrackingProfile}
      description: "A collection of <see cref=&quot;T:System.Activities.Tracking.TrackingProfile&quot;></see> objects."
  overload: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.TrackingProfiles*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.#ctor
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection
  isExternal: false
  name: TrackingSection()
  nameWithType: TrackingSection.TrackingSection()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.TrackingSection()
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.Profiles
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection
  isExternal: false
  name: Profiles
  nameWithType: TrackingSection.Profiles
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.Profiles
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElementCollection
  parent: System.ServiceModel.Activities.Tracking.Configuration
  isExternal: false
  name: ProfileElementCollection
  nameWithType: ProfileElementCollection
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElementCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection
  isExternal: false
  name: Properties
  nameWithType: TrackingSection.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.TrackingProfiles
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection
  isExternal: false
  name: TrackingProfiles
  nameWithType: TrackingSection.TrackingProfiles
  fullName: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.TrackingProfiles
- uid: System.Collections.ObjectModel.Collection{System.Activities.Tracking.TrackingProfile}
  parent: System.Collections.ObjectModel
  isExternal: true
  name: Collection<TrackingProfile>
  nameWithType: Collection<TrackingProfile>
  fullName: System.Collections.ObjectModel.Collection<System.Activities.Tracking.TrackingProfile>
  spec.csharp:
  - uid: System.Collections.ObjectModel.Collection`1
    name: Collection
    nameWithType: Collection
    fullName: Collection<System.Activities.Tracking.TrackingProfile>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Activities.Tracking.TrackingProfile
    name: TrackingProfile
    nameWithType: TrackingProfile
    fullName: TrackingProfile
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.#ctor*
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection
  isExternal: false
  name: TrackingSection
  nameWithType: TrackingSection.TrackingSection
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.Profiles*
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection
  isExternal: false
  name: Profiles
  nameWithType: TrackingSection.Profiles
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.Properties*
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection
  isExternal: false
  name: Properties
  nameWithType: TrackingSection.Properties
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection.TrackingProfiles*
  parent: System.ServiceModel.Activities.Tracking.Configuration.TrackingSection
  isExternal: false
  name: TrackingProfiles
  nameWithType: TrackingSection.TrackingProfiles
