### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  id: MessageSecurityOverMsmqElement
  children:
  - System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.#ctor
  - System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite
  - System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType
  - System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties
  langs:
  - csharp
  name: MessageSecurityOverMsmqElement
  nameWithType: MessageSecurityOverMsmqElement
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  type: Class
  summary: "Enables setting message-level security properties on the <see cref=&quot;T:System.ServiceModel.NetMsmqBinding&quot;></see> binding."
  syntax:
    content: 'public sealed class MessageSecurityOverMsmqElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  langs:
  - csharp
  name: MessageSecurityOverMsmqElement()
  nameWithType: MessageSecurityOverMsmqElement.MessageSecurityOverMsmqElement()
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.MessageSecurityOverMsmqElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.MessageSecurityOverMsmqElement&quot;></see> class."
  syntax:
    content: public MessageSecurityOverMsmqElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite
  id: AlgorithmSuite
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  langs:
  - csharp
  name: AlgorithmSuite
  nameWithType: MessageSecurityOverMsmqElement.AlgorithmSuite
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Specifies the algorithm suite used for security messages at the SOAP level."
  remarks: "<xref:System.ServiceModel.Security.SecurityAlgorithmSuite> defines a variety of algorithms, such as Canonicalization, Digest, KeyWrap, Signature, Encryption, and KeyDerivation. This property is most relevant when working with a platform that uses a set of algorithms different than the default. You should be aware of the strengths and weaknesses of the relevant algorithms when making modifications to this property."
  syntax:
    content: public System.ServiceModel.Security.SecurityAlgorithmSuite AlgorithmSuite { get; set; }
    return:
      type: System.ServiceModel.Security.SecurityAlgorithmSuite
      description: "The <see cref=&quot;T:System.ServiceModel.Security.SecurityAlgorithmSuite&quot;></see> setting for messages sent over the <see cref=&quot;T:System.ServiceModel.NetMsmqBinding&quot;></see> binding."
  overload: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType
  id: ClientCredentialType
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  langs:
  - csharp
  name: ClientCredentialType
  nameWithType: MessageSecurityOverMsmqElement.ClientCredentialType
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets the &lt;xref:System.ServiceModel.MessageCredentialType&gt; security setting for messages sent over the MSMQ transport."
  remarks: "This property can be set to one of the following values:      -   None: This allows the service to interact with anonymous clients. Neither the service nor the client requires a credential.      -   Windows: This enables the SOAP exchanges to be under the authenticated context of a Windows credential. This always performs Kerberos-based authentication.      -   UserName: This enables the service to require that the client be authenticated using a UserName credential. This credential needs to be specified using <xref:System.ServiceModel.Description.ClientCredentials> class.          > [!NOTE]     >  [!INCLUDE[indigo2](~/add/includes/indigo2-md.md)] does not support sending a password digest or deriving keys using password and using such keys for message security. As such, [!INCLUDE[indigo2](~/add/includes/indigo2-md.md)] enforces that the exchange is secured when using UserName credentials. This mode requires that the service certificate be specified on the client side using ClientCredential behavior and serviceCertificate.      -   Certificate: This enables the service to require that the client be authenticated using a certificate. The client credential in this case needs to be specified using the <xref:System.ServiceModel.Description.ClientCredentials> class or ClientCredentials behavior. The service credential in this case needs to be specified using the <xref:System.ServiceModel.Description.ClientCredentials> class or ClientCredentials behavior by specifying the serviceCertificate.      -   CardSpace: This allows the service to require that the client be authenticated using a [!INCLUDE[infocard1](~/add/includes/infocard1-md.md)]. The serviceCertiifcate must be provisioned in the ClientCredential behavior.       The Certificate credential for the `MessageSecurityOverMsmq` is relevant only when the security mode is set to `Both` or `Message`."
  syntax:
    content: public System.ServiceModel.MessageCredentialType ClientCredentialType { get; set; }
    return:
      type: System.ServiceModel.MessageCredentialType
      description: "The &lt;xref:System.ServiceModel.MessageCredentialType&gt; security setting for messages sent over the MSMQ transport."
  overload: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  langs:
  - csharp
  name: Properties
  nameWithType: MessageSecurityOverMsmqElement.Properties
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.#ctor
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: MessageSecurityOverMsmqElement()
  nameWithType: MessageSecurityOverMsmqElement.MessageSecurityOverMsmqElement()
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.MessageSecurityOverMsmqElement()
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: AlgorithmSuite
  nameWithType: MessageSecurityOverMsmqElement.AlgorithmSuite
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite
- uid: System.ServiceModel.Security.SecurityAlgorithmSuite
  parent: System.ServiceModel.Security
  isExternal: false
  name: SecurityAlgorithmSuite
  nameWithType: SecurityAlgorithmSuite
  fullName: System.ServiceModel.Security.SecurityAlgorithmSuite
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: ClientCredentialType
  nameWithType: MessageSecurityOverMsmqElement.ClientCredentialType
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType
- uid: System.ServiceModel.MessageCredentialType
  parent: System.ServiceModel
  isExternal: true
  name: MessageCredentialType
  nameWithType: MessageCredentialType
  fullName: System.ServiceModel.MessageCredentialType
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: Properties
  nameWithType: MessageSecurityOverMsmqElement.Properties
  fullName: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.#ctor*
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: MessageSecurityOverMsmqElement
  nameWithType: MessageSecurityOverMsmqElement.MessageSecurityOverMsmqElement
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.AlgorithmSuite*
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: AlgorithmSuite
  nameWithType: MessageSecurityOverMsmqElement.AlgorithmSuite
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.ClientCredentialType*
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: ClientCredentialType
  nameWithType: MessageSecurityOverMsmqElement.ClientCredentialType
- uid: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement.Properties*
  parent: System.ServiceModel.Configuration.MessageSecurityOverMsmqElement
  isExternal: false
  name: Properties
  nameWithType: MessageSecurityOverMsmqElement.Properties
