### YamlMime:ManagedReference
items:
- uid: System.Configuration.TypeNameConverter
  id: TypeNameConverter
  children:
  - System.Configuration.TypeNameConverter.#ctor
  - System.Configuration.TypeNameConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.Configuration.TypeNameConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  name: TypeNameConverter
  nameWithType: TypeNameConverter
  fullName: System.Configuration.TypeNameConverter
  type: Class
  summary: "Converts between type and string values. This class cannot be inherited."
  remarks: "This type, like all the other configuration converter types, converts strings found in the configuration file to and from the related strongly typed properties.       In particular, the TypeNameConverter class converts a <xref:System.String> value, assigned to a configuration type, to a <xref:System.Type> value and vice versa. The type referred to is the class responsible for processing the configuration it is associated with."
  example:
  - "The following example shows how to obtain a type associated with a custom section. For the implementation of the custom section, refer to the code example in the <xref:System.Configuration.ConfigurationConverterBase> class reference.  \n  \n [!code-vb[System.Configuration.TypeNameConverter#1](~/add/codesnippet/VisualBasic/t-system.configuration.t_0_1.vb)]\n [!code-cs[System.Configuration.TypeNameConverter#1](~/add/codesnippet/CSharp/t-system.configuration.t_0_1.cs)]  \n  \n The following example is a configuration excerpt used by the previous example.  \n  \n```  \n<?xml version=\"1.0\" encoding=\"utf-8\"?>  \n<configuration>  \n  \n  <configSections>  \n    <section name=\"CustomSection\"   \n      type=\"Samples.AspNet.CustomSection,   \n      ConfigurationConverters,   \n      Version=1.0.0.0, Culture=neutral,   \n      PublicKeyToken=null\"   \n      allowDefinition=\"Everywhere\"   \n      allowExeDefinition=\"MachineToApplication\"   \n      restartOnExternalChanges=\"true\" />  \n  </configSections>  \n  \n  <CustomSection fileName=\"default.txt\" maxIdleTime=\"90\"   \n    timeDelay=\"infinite\" cdStr=\"str0, str1\" permission=\"Read\"  \n    maxUsers=\"Infinite\"/>  \n  \n</configuration>  \n```"
  syntax:
    content: 'public sealed class TypeNameConverter : System.Configuration.ConfigurationConverterBase'
  inheritance:
  - System.Object
  - System.ComponentModel.TypeConverter
  - System.Configuration.ConfigurationConverterBase
  implements: []
  inheritedMembers:
  - System.ComponentModel.TypeConverter.CanConvertFrom(System.Type)
  - System.ComponentModel.TypeConverter.CanConvertTo(System.Type)
  - System.ComponentModel.TypeConverter.ConvertFrom(System.Object)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.String)
  - System.ComponentModel.TypeConverter.ConvertTo(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.Object)
  - System.ComponentModel.TypeConverter.CreateInstance(System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.CreateInstance(System.ComponentModel.ITypeDescriptorContext,System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.GetConvertFromException(System.Object)
  - System.ComponentModel.TypeConverter.GetConvertToException(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object,System.Attribute[])
  - System.ComponentModel.TypeConverter.GetProperties(System.Object)
  - System.ComponentModel.TypeConverter.GetPropertiesSupported
  - System.ComponentModel.TypeConverter.GetPropertiesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValues
  - System.ComponentModel.TypeConverter.GetStandardValues(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.IsValid(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.IsValid(System.Object)
  - System.ComponentModel.TypeConverter.SortProperties(System.ComponentModel.PropertyDescriptorCollection,System.String[])
  - System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TypeNameConverter.#ctor
  id: '#ctor'
  parent: System.Configuration.TypeNameConverter
  langs:
  - csharp
  name: TypeNameConverter()
  nameWithType: TypeNameConverter.TypeNameConverter()
  fullName: System.Configuration.TypeNameConverter.TypeNameConverter()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.TypeNameConverter&quot;></see> class."
  remarks: "Normally, you use the converter types provided by the system. The only time you need to use the TypeNameConverter constructor is when you create your own conversion type."
  syntax:
    content: public TypeNameConverter ();
    parameters: []
  overload: System.Configuration.TypeNameConverter.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TypeNameConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TypeNameConverter
  langs:
  - csharp
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: TypeNameConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.TypeNameConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Converts a &lt;xref:System.String&gt; object to a &lt;xref:System.Type&gt; object."
  remarks: "The system uses the ConvertFrom method when reading from a configuration file to convert a <xref:System.String> value to a <xref:System.Type> value."
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object data);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "The  object used for type conversions."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "The <xref:System.Globalization.CultureInfo> object used during conversion."
    - id: data
      type: System.Object
      description: "The <xref:System.String> object to convert."
    return:
      type: System.Object
      description: "To be added."
  overload: System.Configuration.TypeNameConverter.ConvertFrom*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "The <xref:System.Type> value cannot be resolved."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TypeNameConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TypeNameConverter
  langs:
  - csharp
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: TypeNameConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.TypeNameConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Converts a &lt;xref:System.Type&gt; object to a &lt;xref:System.String&gt; object."
  remarks: "The system uses the ConvertTo method when writing to a configuration file to convert a <xref:System.Type> value to a <xref:System.String> value."
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object value, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "The  object used for type conversions."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "The <xref:System.Globalization.CultureInfo> object used during conversion."
    - id: value
      type: System.Object
      description: "The value to convert to."
    - id: type
      type: System.Type
      description: "The type to convert to."
    return:
      type: System.Object
      description: "To be added."
  overload: System.Configuration.TypeNameConverter.ConvertTo*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationConverterBase
  isExternal: false
  name: System.Configuration.ConfigurationConverterBase
- uid: System.Configuration.TypeNameConverter.#ctor
  parent: System.Configuration.TypeNameConverter
  isExternal: false
  name: TypeNameConverter()
  nameWithType: TypeNameConverter.TypeNameConverter()
  fullName: System.Configuration.TypeNameConverter.TypeNameConverter()
- uid: System.Configuration.TypeNameConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TypeNameConverter
  isExternal: false
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: TypeNameConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.TypeNameConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: false
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: true
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Configuration.TypeNameConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TypeNameConverter
  isExternal: false
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: TypeNameConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.TypeNameConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.TypeNameConverter.#ctor*
  parent: System.Configuration.TypeNameConverter
  isExternal: false
  name: TypeNameConverter
  nameWithType: TypeNameConverter.TypeNameConverter
- uid: System.Configuration.TypeNameConverter.ConvertFrom*
  parent: System.Configuration.TypeNameConverter
  isExternal: false
  name: ConvertFrom
  nameWithType: TypeNameConverter.ConvertFrom
- uid: System.Configuration.TypeNameConverter.ConvertTo*
  parent: System.Configuration.TypeNameConverter
  isExternal: false
  name: ConvertTo
  nameWithType: TypeNameConverter.ConvertTo
