### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Configuration.WorkflowHostingOptionsSection
  id: WorkflowHostingOptionsSection
  children:
  - System.ServiceModel.Activities.Configuration.WorkflowHostingOptionsSection.#ctor
  - System.ServiceModel.Activities.Configuration.WorkflowHostingOptionsSection.OverrideSiteName
  langs:
  - csharp
  name: WorkflowHostingOptionsSection
  nameWithType: WorkflowHostingOptionsSection
  fullName: System.ServiceModel.Activities.Configuration.WorkflowHostingOptionsSection
  type: Class
  summary: "Represents the configuration section for the workflow hosting options."
  syntax:
    content: 'public sealed class WorkflowHostingOptionsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Configuration.WorkflowHostingOptionsSection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Configuration.WorkflowHostingOptionsSection
  langs:
  - csharp
  name: WorkflowHostingOptionsSection()
  nameWithType: WorkflowHostingOptionsSection.WorkflowHostingOptionsSection()
  fullName: System.ServiceModel.Activities.Configuration.WorkflowHostingOptionsSection.WorkflowHostingOptionsSection()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Activities.Configuration.WorkflowHostingOptionsSection&quot;></see> class."
  syntax:
    content: public WorkflowHostingOptionsSection ();
    parameters: []
  overload: System.ServiceModel.Activities.Configuration.WorkflowHostingOptionsSection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Configuration.WorkflowHostingOptionsSection.OverrideSiteName
  id: OverrideSiteName
  parent: System.ServiceModel.Activities.Configuration.WorkflowHostingOptionsSection
  langs:
  - csharp
  name: OverrideSiteName
  nameWithType: WorkflowHostingOptionsSection.OverrideSiteName
  fullName: System.ServiceModel.Activities.Configuration.WorkflowHostingOptionsSection.OverrideSiteName
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "Gets or sets a value that indicates whether to override site name."
  syntax:
    content: public bool OverrideSiteName { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if to override site name; otherwise, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>."
  overload: System.ServiceModel.Activities.Configuration.WorkflowHostingOptionsSection.OverrideSiteName*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.ServiceModel.Activities.Configuration.WorkflowHostingOptionsSection.#ctor
  parent: System.ServiceModel.Activities.Configuration.WorkflowHostingOptionsSection
  isExternal: false
  name: WorkflowHostingOptionsSection()
  nameWithType: WorkflowHostingOptionsSection.WorkflowHostingOptionsSection()
  fullName: System.ServiceModel.Activities.Configuration.WorkflowHostingOptionsSection.WorkflowHostingOptionsSection()
- uid: System.ServiceModel.Activities.Configuration.WorkflowHostingOptionsSection.OverrideSiteName
  parent: System.ServiceModel.Activities.Configuration.WorkflowHostingOptionsSection
  isExternal: false
  name: OverrideSiteName
  nameWithType: WorkflowHostingOptionsSection.OverrideSiteName
  fullName: System.ServiceModel.Activities.Configuration.WorkflowHostingOptionsSection.OverrideSiteName
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Activities.Configuration.WorkflowHostingOptionsSection.#ctor*
  parent: System.ServiceModel.Activities.Configuration.WorkflowHostingOptionsSection
  isExternal: false
  name: WorkflowHostingOptionsSection
  nameWithType: WorkflowHostingOptionsSection.WorkflowHostingOptionsSection
- uid: System.ServiceModel.Activities.Configuration.WorkflowHostingOptionsSection.OverrideSiteName*
  parent: System.ServiceModel.Activities.Configuration.WorkflowHostingOptionsSection
  isExternal: false
  name: OverrideSiteName
  nameWithType: WorkflowHostingOptionsSection.OverrideSiteName
