### YamlMime:ManagedReference
items:
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute
  id: PositiveTimeSpanValidatorAttribute
  children:
  - System.Configuration.PositiveTimeSpanValidatorAttribute.#ctor
  - System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: PositiveTimeSpanValidatorAttribute
  nameWithType: PositiveTimeSpanValidatorAttribute
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute
  type: Class
  summary: "Declaratively instructs the .NET Framework to perform time validation on a configuration property. This class cannot be inherited."
  remarks: "You use the PositiveTimeSpanValidatorAttribute attribute to decorate a configuration property. This instructs the .NET Framework to validate the property using a <xref:System.Configuration.PositiveTimeSpanValidator> object and pass the value of the decorating parameters.       You can apply PositiveTimeSpanValidatorAttribute objects only to property types."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class PositiveTimeSpanValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  langs:
  - csharp
  name: PositiveTimeSpanValidatorAttribute()
  nameWithType: PositiveTimeSpanValidatorAttribute.PositiveTimeSpanValidatorAttribute()
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute.PositiveTimeSpanValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.PositiveTimeSpanValidatorAttribute&quot;></see> class."
  remarks: "You use this constructor in the attributed model to ensure that the type of the value assigned to the related property is a positive <xref:System.TimeSpan> object."
  syntax:
    content: public PositiveTimeSpanValidatorAttribute ();
    parameters: []
  overload: System.Configuration.PositiveTimeSpanValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: PositiveTimeSpanValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets an instance of the <see cref=&quot;T:System.Configuration.PositiveTimeSpanValidator&quot;></see> class."
  remarks: "You use the ValidatorInstance property to perform positive <xref:System.TimeSpan> object validation by calling the <xref:System.Configuration.PositiveTimeSpanValidator.Validate%2A?displayProperty=fullName> method."
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "The <see cref=&quot;T:System.Configuration.ConfigurationValidatorBase&quot;></see> validator instance."
  overload: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.#ctor
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  isExternal: false
  name: PositiveTimeSpanValidatorAttribute()
  nameWithType: PositiveTimeSpanValidatorAttribute.PositiveTimeSpanValidatorAttribute()
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute.PositiveTimeSpanValidatorAttribute()
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: PositiveTimeSpanValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.#ctor*
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  isExternal: false
  name: PositiveTimeSpanValidatorAttribute
  nameWithType: PositiveTimeSpanValidatorAttribute.PositiveTimeSpanValidatorAttribute
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: PositiveTimeSpanValidatorAttribute.ValidatorInstance
