### YamlMime:ManagedReference
items:
- uid: System.Web.PreApplicationStartMethodAttribute
  id: PreApplicationStartMethodAttribute
  children:
  - System.Web.PreApplicationStartMethodAttribute.#ctor(System.Type,System.String)
  - System.Web.PreApplicationStartMethodAttribute.MethodName
  - System.Web.PreApplicationStartMethodAttribute.Type
  langs:
  - csharp
  name: PreApplicationStartMethodAttribute
  nameWithType: PreApplicationStartMethodAttribute
  fullName: System.Web.PreApplicationStartMethodAttribute
  type: Class
  summary: "Provides expanded support for application startup."
  remarks: "-   There is no guarantee of the order in which the assembly-defined application start methods are called. As a result, each registered start method should be coded to run in isolation and should not depend on side effects from other registered start methods.       For more information about using attributes, see [Attributes](../Topic/Extending%20Metadata%20Using%20Attributes.md)."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Assembly, AllowMultiple=true)]

      public sealed class PreApplicationStartMethodAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.PreApplicationStartMethodAttribute.#ctor(System.Type,System.String)
  id: '#ctor(System.Type,System.String)'
  parent: System.Web.PreApplicationStartMethodAttribute
  langs:
  - csharp
  name: PreApplicationStartMethodAttribute(Type,String)
  nameWithType: PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute(Type,String)
  fullName: System.Web.PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute(Type,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Web.PreApplicationStartMethodAttribute&quot;></see> class."
  remarks: "The method referenced by the `methodName` parameter must be public and can be either an instance method or static method."
  syntax:
    content: public PreApplicationStartMethodAttribute (Type type, string methodName);
    parameters:
    - id: type
      type: System.Type
      description: "An object that describes the type of the startup method.."
    - id: methodName
      type: System.String
      description: "An empty parameter signature that has no return value."
  overload: System.Web.PreApplicationStartMethodAttribute.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.PreApplicationStartMethodAttribute.MethodName
  id: MethodName
  parent: System.Web.PreApplicationStartMethodAttribute
  langs:
  - csharp
  name: MethodName
  nameWithType: PreApplicationStartMethodAttribute.MethodName
  fullName: System.Web.PreApplicationStartMethodAttribute.MethodName
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Gets the associated startup method."
  syntax:
    content: public string MethodName { get; }
    return:
      type: System.String
      description: "A string that contains the name of the associated startup method."
  overload: System.Web.PreApplicationStartMethodAttribute.MethodName*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.PreApplicationStartMethodAttribute.Type
  id: Type
  parent: System.Web.PreApplicationStartMethodAttribute
  langs:
  - csharp
  name: Type
  nameWithType: PreApplicationStartMethodAttribute.Type
  fullName: System.Web.PreApplicationStartMethodAttribute.Type
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Gets the type that is returned by the associated startup method."
  syntax:
    content: public Type Type { get; }
    return:
      type: System.Type
      description: "An object that describes the type of the startup method."
  overload: System.Web.PreApplicationStartMethodAttribute.Type*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Web.PreApplicationStartMethodAttribute.#ctor(System.Type,System.String)
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: PreApplicationStartMethodAttribute(Type,String)
  nameWithType: PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute(Type,String)
  fullName: System.Web.PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute(Type,String)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.PreApplicationStartMethodAttribute.MethodName
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: MethodName
  nameWithType: PreApplicationStartMethodAttribute.MethodName
  fullName: System.Web.PreApplicationStartMethodAttribute.MethodName
- uid: System.Web.PreApplicationStartMethodAttribute.Type
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: Type
  nameWithType: PreApplicationStartMethodAttribute.Type
  fullName: System.Web.PreApplicationStartMethodAttribute.Type
- uid: System.Web.PreApplicationStartMethodAttribute.#ctor*
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: PreApplicationStartMethodAttribute
  nameWithType: PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute
- uid: System.Web.PreApplicationStartMethodAttribute.MethodName*
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: MethodName
  nameWithType: PreApplicationStartMethodAttribute.MethodName
- uid: System.Web.PreApplicationStartMethodAttribute.Type*
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: Type
  nameWithType: PreApplicationStartMethodAttribute.Type
