### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.XhtmlConformanceMode
  id: XhtmlConformanceMode
  children:
  - System.Web.Configuration.XhtmlConformanceMode.Legacy
  - System.Web.Configuration.XhtmlConformanceMode.Strict
  - System.Web.Configuration.XhtmlConformanceMode.Transitional
  langs:
  - csharp
  name: XhtmlConformanceMode
  nameWithType: XhtmlConformanceMode
  fullName: System.Web.Configuration.XhtmlConformanceMode
  type: Enum
  summary: "Specifies the authentication mode to use in a Web application."
  remarks: "The XhtmlConformanceMode enumeration applies to the `mode` attribute in the `xhtmlConformance` tag. It specifies the XHTML rendering modalities for an ASP.NET application. The mode can assume one of the values listed next. The default is `Transitional` (XHTML 1.0 Transitional)."
  syntax:
    content: public enum XhtmlConformanceMode
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.XhtmlConformanceMode.Legacy
  id: Legacy
  parent: System.Web.Configuration.XhtmlConformanceMode
  langs:
  - csharp
  name: Legacy
  nameWithType: XhtmlConformanceMode.Legacy
  fullName: System.Web.Configuration.XhtmlConformanceMode.Legacy
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "XHTML 1.0 Transitional"
  syntax:
    content: Legacy
    return:
      type: System.Web.Configuration.XhtmlConformanceMode
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.XhtmlConformanceMode.Strict
  id: Strict
  parent: System.Web.Configuration.XhtmlConformanceMode
  langs:
  - csharp
  name: Strict
  nameWithType: XhtmlConformanceMode.Strict
  fullName: System.Web.Configuration.XhtmlConformanceMode.Strict
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "XHTML 1.0 Strict conformance"
  syntax:
    content: Strict
    return:
      type: System.Web.Configuration.XhtmlConformanceMode
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.XhtmlConformanceMode.Transitional
  id: Transitional
  parent: System.Web.Configuration.XhtmlConformanceMode
  langs:
  - csharp
  name: Transitional
  nameWithType: XhtmlConformanceMode.Transitional
  fullName: System.Web.Configuration.XhtmlConformanceMode.Transitional
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Reverts a number of rendering changes made for conformance to the v1.1 rendering behavior."
  syntax:
    content: Transitional
    return:
      type: System.Web.Configuration.XhtmlConformanceMode
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.XhtmlConformanceMode.Legacy
  parent: System.Web.Configuration.XhtmlConformanceMode
  isExternal: false
  name: Legacy
  nameWithType: XhtmlConformanceMode.Legacy
  fullName: System.Web.Configuration.XhtmlConformanceMode.Legacy
- uid: System.Web.Configuration.XhtmlConformanceMode
  parent: System.Web.Configuration
  isExternal: false
  name: XhtmlConformanceMode
  nameWithType: XhtmlConformanceMode
  fullName: System.Web.Configuration.XhtmlConformanceMode
- uid: System.Web.Configuration.XhtmlConformanceMode.Strict
  parent: System.Web.Configuration.XhtmlConformanceMode
  isExternal: false
  name: Strict
  nameWithType: XhtmlConformanceMode.Strict
  fullName: System.Web.Configuration.XhtmlConformanceMode.Strict
- uid: System.Web.Configuration.XhtmlConformanceMode.Transitional
  parent: System.Web.Configuration.XhtmlConformanceMode
  isExternal: false
  name: Transitional
  nameWithType: XhtmlConformanceMode.Transitional
  fullName: System.Web.Configuration.XhtmlConformanceMode.Transitional
