### YamlMime:ManagedReference
items:
- uid: System.Configuration.IgnoreSectionHandler
  id: IgnoreSectionHandler
  children:
  - System.Configuration.IgnoreSectionHandler.#ctor
  - System.Configuration.IgnoreSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: IgnoreSectionHandler
  nameWithType: IgnoreSectionHandler
  fullName: System.Configuration.IgnoreSectionHandler
  type: Class
  summary: "Provides a legacy section-handler definition for configuration sections that are not handled by the <see cref=&quot;N:System.Configuration&quot;></see> types."
  remarks: "The configuration system completely parses configuration files to collect configuration information and throws exceptions when it encounters configuration sections that do not have a corresponding entry in the `configSections` section.       For those sections not handled by the <xref:System.Configuration> types, the new wrapper type <xref:System.Configuration.IgnoreSection> is provided. This is to prevent configuration-file parsing exceptions.       For legacy purposes the IgnoreSectionHandler is also provided."
  syntax:
    content: 'public class IgnoreSectionHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.IgnoreSectionHandler.#ctor
  id: '#ctor'
  parent: System.Configuration.IgnoreSectionHandler
  langs:
  - csharp
  name: IgnoreSectionHandler()
  nameWithType: IgnoreSectionHandler.IgnoreSectionHandler()
  fullName: System.Configuration.IgnoreSectionHandler.IgnoreSectionHandler()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.IgnoreSectionHandler&quot;></see> class."
  syntax:
    content: public IgnoreSectionHandler ();
    parameters: []
  overload: System.Configuration.IgnoreSectionHandler.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.IgnoreSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.IgnoreSectionHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: IgnoreSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.IgnoreSectionHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Creates a new configuration handler and adds the specified configuration object to the section-handler collection."
  syntax:
    content: public virtual object Create (object parent, object configContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "The configuration settings in a corresponding parent configuration section."
    - id: configContext
      type: System.Object
      description: "The virtual path for which the configuration section handler computes configuration values. Normally this parameter is reserved and is ."
    - id: section
      type: System.Xml.XmlNode
      description: "An  that contains the configuration information to be handled. Provides direct access to the XML contents of the configuration section."
    return:
      type: System.Object
      description: "To be added."
  overload: System.Configuration.IgnoreSectionHandler.Create*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.IgnoreSectionHandler.#ctor
  parent: System.Configuration.IgnoreSectionHandler
  isExternal: false
  name: IgnoreSectionHandler()
  nameWithType: IgnoreSectionHandler.IgnoreSectionHandler()
  fullName: System.Configuration.IgnoreSectionHandler.IgnoreSectionHandler()
- uid: System.Configuration.IgnoreSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.IgnoreSectionHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: IgnoreSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.IgnoreSectionHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.IgnoreSectionHandler.#ctor*
  parent: System.Configuration.IgnoreSectionHandler
  isExternal: false
  name: IgnoreSectionHandler
  nameWithType: IgnoreSectionHandler.IgnoreSectionHandler
- uid: System.Configuration.IgnoreSectionHandler.Create*
  parent: System.Configuration.IgnoreSectionHandler
  isExternal: false
  name: Create
  nameWithType: IgnoreSectionHandler.Create
