### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.SqlCacheDependencyDatabase
  id: SqlCacheDependencyDatabase
  children:
  - System.Web.Configuration.SqlCacheDependencyDatabase.#ctor(System.String,System.String)
  - System.Web.Configuration.SqlCacheDependencyDatabase.#ctor(System.String,System.String,System.Int32)
  - System.Web.Configuration.SqlCacheDependencyDatabase.ConnectionStringName
  - System.Web.Configuration.SqlCacheDependencyDatabase.ElementProperty
  - System.Web.Configuration.SqlCacheDependencyDatabase.Name
  - System.Web.Configuration.SqlCacheDependencyDatabase.PollTime
  - System.Web.Configuration.SqlCacheDependencyDatabase.Properties
  langs:
  - csharp
  name: SqlCacheDependencyDatabase
  nameWithType: SqlCacheDependencyDatabase
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase
  type: Class
  summary: "Configures the SQL cache dependencies databases for an ASP.NET application. This class cannot be inherited."
  remarks: "The SqlCacheDependencyDatabase allows you to programmatically access and modify the `databases` element of the `sqlCacheDependency` node within the `caching` configuration section.       The SQL cache dependency allows the cached data to be synchronized with the original source. After you configure the relationship between an item stored in an ASP.NET application&quot;s cache and a specific SQL Server database table, an instance of the <xref:System.Web.Caching.SqlCacheDependency> class monitors the table for possible changes."
  example:
  - "The following code example shows how to obtain the SqlCacheDependencyDatabase object from the configuration file of an existing Web application.  \n  \n [!code-vb[System.Web.Configuration.SqlCacheDependencyDatabase#1](~/add/codesnippet/VisualBasic/t-system.web.configurati_17_1.vb)]\n [!code-cs[System.Web.Configuration.SqlCacheDependencyDatabase#1](~/add/codesnippet/CSharp/t-system.web.configurati_17_1.cs)]"
  syntax:
    content: 'public sealed class SqlCacheDependencyDatabase : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  langs:
  - csharp
  name: SqlCacheDependencyDatabase(String,String)
  nameWithType: SqlCacheDependencyDatabase.SqlCacheDependencyDatabase(String,String)
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase.SqlCacheDependencyDatabase(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Web.Configuration.SqlCacheDependencyDatabase&quot;></see> class with the passed parameters."
  remarks: ''
  example:
  - "The following example shows how to use this constructor.  \n  \n [!code-vb[System.Web.Configuration.SqlCacheDependencyDatabase#6](~/add/codesnippet/VisualBasic/5e38fe68-b87d-487a-9066-_1.vb)]\n [!code-cs[System.Web.Configuration.SqlCacheDependencyDatabase#6](~/add/codesnippet/CSharp/5e38fe68-b87d-487a-9066-_1.cs)]"
  syntax:
    content: public SqlCacheDependencyDatabase (string name, string connectionStringName);
    parameters:
    - id: name
      type: System.String
      description: "A string that specifies the name used by  to identify the database."
    - id: connectionStringName
      type: System.String
      description: "A string that specifies the name of the connection string in the  section to use to connect to this database."
  overload: System.Web.Configuration.SqlCacheDependencyDatabase.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.#ctor(System.String,System.String,System.Int32)
  id: '#ctor(System.String,System.String,System.Int32)'
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  langs:
  - csharp
  name: SqlCacheDependencyDatabase(String,String,Int32)
  nameWithType: SqlCacheDependencyDatabase.SqlCacheDependencyDatabase(String,String,Int32)
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase.SqlCacheDependencyDatabase(String,String,Int32)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Web.Configuration.SqlCacheDependencyDatabase&quot;></see> class."
  remarks: ''
  example:
  - "The following example shows how to use this constructor.  \n  \n [!code-vb[System.Web.Configuration.SqlCacheDependencyDatabase#5](~/add/codesnippet/VisualBasic/de5448cc-1e38-425a-ac5d-_1.vb)]\n [!code-cs[System.Web.Configuration.SqlCacheDependencyDatabase#5](~/add/codesnippet/CSharp/de5448cc-1e38-425a-ac5d-_1.cs)]"
  syntax:
    content: public SqlCacheDependencyDatabase (string name, string connectionStringName, int pollTime);
    parameters:
    - id: name
      type: System.String
      description: "A string that specifies the name used by  to identify the database."
    - id: connectionStringName
      type: System.String
      description: "A string that specifies the name of the connection string in the  section to use to connect to this database."
    - id: pollTime
      type: System.Int32
      description: "The database polling time, in milliseconds."
  overload: System.Web.Configuration.SqlCacheDependencyDatabase.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.ConnectionStringName
  id: ConnectionStringName
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  langs:
  - csharp
  name: ConnectionStringName
  nameWithType: SqlCacheDependencyDatabase.ConnectionStringName
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase.ConnectionStringName
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets or sets the connection name for the database."
  remarks: "The ConnectionStringName property allows you to programmatically access and modify the `connectionName` attribute of an `add` element of the `databases` node in a configuration file. The connection name identifies an element in the `connectionStrings` section which contains the database connection string."
  example:
  - "The following code example shows how to use the ConnectionStringName property.  \n  \n [!code-vb[System.Web.Configuration.SqlCacheDependencyDatabase#4](~/add/codesnippet/VisualBasic/p-system.web.configurati_380_1.vb)]\n [!code-cs[System.Web.Configuration.SqlCacheDependencyDatabase#4](~/add/codesnippet/CSharp/p-system.web.configurati_380_1.cs)]"
  syntax:
    content: public string ConnectionStringName { get; set; }
    return:
      type: System.String
      description: "A string that specifies the name of a database connection string within the <xref uid=&quot;langword_csharp_connectionStrings&quot; name=&quot;connectionStrings&quot; href=&quot;&quot;></xref> configuration section."
  overload: System.Web.Configuration.SqlCacheDependencyDatabase.ConnectionStringName*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.ElementProperty
  id: ElementProperty
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  langs:
  - csharp
  name: ElementProperty
  nameWithType: SqlCacheDependencyDatabase.ElementProperty
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase.ElementProperty
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationElementProperty ElementProperty { get; }
    return:
      type: System.Configuration.ConfigurationElementProperty
      description: "To be added."
  overload: System.Web.Configuration.SqlCacheDependencyDatabase.ElementProperty*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.Name
  id: Name
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  langs:
  - csharp
  name: Name
  nameWithType: SqlCacheDependencyDatabase.Name
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase.Name
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets or sets the name of the database."
  remarks: "The Name property allows you to programmatically access and modify the `name` attribute of an `add` element of the `databases` node in a configuration file.       The `name` attribute identifies the database whose table is used for the <xref:System.Web.Caching.SqlCacheDependency>."
  example:
  - "The following code example shows how to use the Name property.  \n  \n [!code-vb[System.Web.Configuration.SqlCacheDependencyDatabase#3](~/add/codesnippet/VisualBasic/p-system.web.configurati_277_1.vb)]\n [!code-cs[System.Web.Configuration.SqlCacheDependencyDatabase#3](~/add/codesnippet/CSharp/p-system.web.configurati_277_1.cs)]"
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "A string that specifies the name used by <see cref=&quot;T:System.Web.Configuration.SqlCacheDependencyDatabase&quot;></see> to identify the database."
  overload: System.Web.Configuration.SqlCacheDependencyDatabase.Name*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.PollTime
  id: PollTime
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  langs:
  - csharp
  name: PollTime
  nameWithType: SqlCacheDependencyDatabase.PollTime
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase.PollTime
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets or sets the frequency with which the <see cref=&quot;T:System.Web.Caching.SqlCacheDependency&quot;></see> polls the database table for changes."
  remarks: "The PollTime property allows you to programmatically access and modify the `pollTime` attribute of an `add` element of the `databases` node in a configuration file.       After you configure the relationship between an item stored in an ASP.NET application&quot;s cache and a specific SQL Server database table, an instance of the <xref:System.Web.Caching.SqlCacheDependency> class monitors the table so that when an item in the table changes, the item is automatically updated in or removed from the cache. The monitoring happens at the frequency specified by the PollTime."
  example:
  - "The following code example shows how to use the PollTime property.  \n  \n [!code-vb[System.Web.Configuration.SqlCacheDependencyDatabase#2](~/add/codesnippet/VisualBasic/p-system.web.configurati_251_1.vb)]\n [!code-cs[System.Web.Configuration.SqlCacheDependencyDatabase#2](~/add/codesnippet/CSharp/p-system.web.configurati_251_1.cs)]"
  syntax:
    content: public int PollTime { get; set; }
    return:
      type: System.Int32
      description: "The database polling time, in milliseconds."
  overload: System.Web.Configuration.SqlCacheDependencyDatabase.PollTime*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.Properties
  id: Properties
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  langs:
  - csharp
  name: Properties
  nameWithType: SqlCacheDependencyDatabase.Properties
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Web.Configuration.SqlCacheDependencyDatabase.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.#ctor(System.String,System.String)
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  isExternal: false
  name: SqlCacheDependencyDatabase(String,String)
  nameWithType: SqlCacheDependencyDatabase.SqlCacheDependencyDatabase(String,String)
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase.SqlCacheDependencyDatabase(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.#ctor(System.String,System.String,System.Int32)
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  isExternal: false
  name: SqlCacheDependencyDatabase(String,String,Int32)
  nameWithType: SqlCacheDependencyDatabase.SqlCacheDependencyDatabase(String,String,Int32)
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase.SqlCacheDependencyDatabase(String,String,Int32)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.ConnectionStringName
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  isExternal: false
  name: ConnectionStringName
  nameWithType: SqlCacheDependencyDatabase.ConnectionStringName
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase.ConnectionStringName
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.ElementProperty
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  isExternal: false
  name: ElementProperty
  nameWithType: SqlCacheDependencyDatabase.ElementProperty
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase.ElementProperty
- uid: System.Configuration.ConfigurationElementProperty
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElementProperty
  nameWithType: ConfigurationElementProperty
  fullName: System.Configuration.ConfigurationElementProperty
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.Name
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  isExternal: false
  name: Name
  nameWithType: SqlCacheDependencyDatabase.Name
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase.Name
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.PollTime
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  isExternal: false
  name: PollTime
  nameWithType: SqlCacheDependencyDatabase.PollTime
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase.PollTime
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.Properties
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  isExternal: false
  name: Properties
  nameWithType: SqlCacheDependencyDatabase.Properties
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.#ctor*
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  isExternal: false
  name: SqlCacheDependencyDatabase
  nameWithType: SqlCacheDependencyDatabase.SqlCacheDependencyDatabase
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.ConnectionStringName*
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  isExternal: false
  name: ConnectionStringName
  nameWithType: SqlCacheDependencyDatabase.ConnectionStringName
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.ElementProperty*
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  isExternal: false
  name: ElementProperty
  nameWithType: SqlCacheDependencyDatabase.ElementProperty
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.Name*
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  isExternal: false
  name: Name
  nameWithType: SqlCacheDependencyDatabase.Name
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.PollTime*
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  isExternal: false
  name: PollTime
  nameWithType: SqlCacheDependencyDatabase.PollTime
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.Properties*
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  isExternal: false
  name: Properties
  nameWithType: SqlCacheDependencyDatabase.Properties
