### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.SessionPageStateSection
  id: SessionPageStateSection
  children:
  - System.Web.Configuration.SessionPageStateSection.#ctor
  - System.Web.Configuration.SessionPageStateSection.DefaultHistorySize
  - System.Web.Configuration.SessionPageStateSection.HistorySize
  - System.Web.Configuration.SessionPageStateSection.Properties
  langs:
  - csharp
  name: SessionPageStateSection
  nameWithType: SessionPageStateSection
  fullName: System.Web.Configuration.SessionPageStateSection
  type: Class
  summary: "Configures the <xref uid=&quot;langword_csharp_sessionPageState&quot; name=&quot;sessionPageState&quot; href=&quot;&quot;></xref> section. This class cannot be inherited."
  remarks: "The SessionPageStateSection refers to the `sessionPageState` section of the configuration file.      > [!NOTE] >  The SessionPageStateSection can read and write information from and to the related section of the configuration file according to the section property <xref:System.Configuration.SectionInformation.AllowDefinition%2A> whose value is <xref:System.Configuration.ConfigurationAllowDefinition>."
  example:
  - "The following code example shows how to obtain the SessionPageStateSection object from the configuration file associated with an existing Web application.  \n  \n [!code-cs[System.Web.Configuration.SessionPageStateSection#1](~/add/codesnippet/CSharp/t-system.web.configurati_84_1.cs)]\n [!code-vb[System.Web.Configuration.SessionPageStateSection#1](~/add/codesnippet/VisualBasic/t-system.web.configurati_84_1.vb)]"
  syntax:
    content: 'public sealed class SessionPageStateSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.SessionPageStateSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.SessionPageStateSection
  langs:
  - csharp
  name: SessionPageStateSection()
  nameWithType: SessionPageStateSection.SessionPageStateSection()
  fullName: System.Web.Configuration.SessionPageStateSection.SessionPageStateSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Creates a new instance of <see cref=&quot;T:System.Web.Configuration.SessionPageStateSection&quot;></see>."
  remarks: "The SessionPageStateSection constructor is not intended to be used directly from your code. It is called by the ASP.NET configuration system. You obtain an instance of the <xref:System.Web.Configuration.SessionPageStateSection> class by using the <xref:System.Configuration.Configuration.GetSection%2A> method."
  syntax:
    content: public SessionPageStateSection ();
    parameters: []
  overload: System.Web.Configuration.SessionPageStateSection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.SessionPageStateSection.DefaultHistorySize
  id: DefaultHistorySize
  parent: System.Web.Configuration.SessionPageStateSection
  langs:
  - csharp
  name: DefaultHistorySize
  nameWithType: SessionPageStateSection.DefaultHistorySize
  fullName: System.Web.Configuration.SessionPageStateSection.DefaultHistorySize
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Defines the size of the page history."
  remarks: ''
  example:
  - "The following code example shows how to obtain the DefaultHistorySize property from the configuration file associated with an existing Web application.  \n  \n [!code-cs[System.Web.Configuration.SessionPageStateSection#2](~/add/codesnippet/CSharp/f-system.web.configurati_1.cs)]\n [!code-vb[System.Web.Configuration.SessionPageStateSection#2](~/add/codesnippet/VisualBasic/f-system.web.configurati_1.vb)]"
  syntax:
    content: public const int DefaultHistorySize = 9;
    return:
      type: System.Int32
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.SessionPageStateSection.HistorySize
  id: HistorySize
  parent: System.Web.Configuration.SessionPageStateSection
  langs:
  - csharp
  name: HistorySize
  nameWithType: SessionPageStateSection.HistorySize
  fullName: System.Web.Configuration.SessionPageStateSection.HistorySize
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets or sets the size of the page history."
  syntax:
    content: public int HistorySize { get; set; }
    return:
      type: System.Int32
      description: "The size of the page history."
  overload: System.Web.Configuration.SessionPageStateSection.HistorySize*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.SessionPageStateSection.Properties
  id: Properties
  parent: System.Web.Configuration.SessionPageStateSection
  langs:
  - csharp
  name: Properties
  nameWithType: SessionPageStateSection.Properties
  fullName: System.Web.Configuration.SessionPageStateSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Web.Configuration.SessionPageStateSection.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.SessionPageStateSection.#ctor
  parent: System.Web.Configuration.SessionPageStateSection
  isExternal: false
  name: SessionPageStateSection()
  nameWithType: SessionPageStateSection.SessionPageStateSection()
  fullName: System.Web.Configuration.SessionPageStateSection.SessionPageStateSection()
- uid: System.Web.Configuration.SessionPageStateSection.DefaultHistorySize
  parent: System.Web.Configuration.SessionPageStateSection
  isExternal: false
  name: DefaultHistorySize
  nameWithType: SessionPageStateSection.DefaultHistorySize
  fullName: System.Web.Configuration.SessionPageStateSection.DefaultHistorySize
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.SessionPageStateSection.HistorySize
  parent: System.Web.Configuration.SessionPageStateSection
  isExternal: false
  name: HistorySize
  nameWithType: SessionPageStateSection.HistorySize
  fullName: System.Web.Configuration.SessionPageStateSection.HistorySize
- uid: System.Web.Configuration.SessionPageStateSection.Properties
  parent: System.Web.Configuration.SessionPageStateSection
  isExternal: false
  name: Properties
  nameWithType: SessionPageStateSection.Properties
  fullName: System.Web.Configuration.SessionPageStateSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.SessionPageStateSection.#ctor*
  parent: System.Web.Configuration.SessionPageStateSection
  isExternal: false
  name: SessionPageStateSection
  nameWithType: SessionPageStateSection.SessionPageStateSection
- uid: System.Web.Configuration.SessionPageStateSection.HistorySize*
  parent: System.Web.Configuration.SessionPageStateSection
  isExternal: false
  name: HistorySize
  nameWithType: SessionPageStateSection.HistorySize
- uid: System.Web.Configuration.SessionPageStateSection.Properties*
  parent: System.Web.Configuration.SessionPageStateSection
  isExternal: false
  name: Properties
  nameWithType: SessionPageStateSection.Properties
