### YamlMime:ManagedReference
items:
- uid: System.Runtime.Caching.Hosting.IApplicationIdentifier
  id: IApplicationIdentifier
  children:
  - System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId
  langs:
  - csharp
  name: IApplicationIdentifier
  nameWithType: IApplicationIdentifier
  fullName: System.Runtime.Caching.Hosting.IApplicationIdentifier
  type: Interface
  summary: "Defines an identifier for application domains that a cache implementation can use to interact with a host environment."
  remarks: "A [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] host environment such as ASP.NET can use the IApplicationIdentifier interface to define strings that identify individual application domains. The host environment implements the IApplicationIdentifier interface. This interface is then available to <xref:System.Runtime.Caching.ObjectCache> implementations through the <xref:System.Runtime.Caching.ObjectCache.Host%2A> property.       A cache implementation uses this reference to obtain an identifier for the application domain. In ASP.NET, cache implementations use the application identifier to construct identifiers for cache performance counters. This provides names for performance counter instances that can be distinguished between application domains when multiple application domains are running."
  syntax:
    content: public interface IApplicationIdentifier
  implements: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId
  id: GetApplicationId
  parent: System.Runtime.Caching.Hosting.IApplicationIdentifier
  langs:
  - csharp
  name: GetApplicationId()
  nameWithType: IApplicationIdentifier.GetApplicationId()
  fullName: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId()
  type: Method
  assemblies:
  - System.Runtime.Caching
  namespace: System.Runtime.Caching.Hosting
  summary: "Gets an identifier for an application domain."
  remarks: "The GetApplicationId method is typically implemented by a [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] host environment in order to construct an application identifier for an <xref:System.Runtime.Caching.ObjectCache> implementation. A <xref:System.Runtime.Caching.ObjectCache> implementation uses this information to identify the application domain that is currently running.       For example, in ASP.NET, the cache uses an application identifier to construct identifiers for cache performance counters. The cache calls the GetApplicationId method that is implemented by the host environment and the host returns the identifier. This provides names for performance counter instances that can be distinguished between application domains when multiple application domains are running."
  syntax:
    content: public string GetApplicationId ();
    parameters: []
    return:
      type: System.String
      description: "To be added."
  overload: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId
  parent: System.Runtime.Caching.Hosting.IApplicationIdentifier
  isExternal: false
  name: GetApplicationId()
  nameWithType: IApplicationIdentifier.GetApplicationId()
  fullName: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId()
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId*
  parent: System.Runtime.Caching.Hosting.IApplicationIdentifier
  isExternal: false
  name: GetApplicationId
  nameWithType: IApplicationIdentifier.GetApplicationId
