### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlXmlReaderSettings
  id: XamlXmlReaderSettings
  children:
  - System.Xaml.XamlXmlReaderSettings.#ctor
  - System.Xaml.XamlXmlReaderSettings.#ctor(System.Xaml.XamlXmlReaderSettings)
  - System.Xaml.XamlXmlReaderSettings.CloseInput
  - System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  - System.Xaml.XamlXmlReaderSettings.XmlLang
  - System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve
  langs:
  - csharp
  name: XamlXmlReaderSettings
  nameWithType: XamlXmlReaderSettings
  fullName: System.Xaml.XamlXmlReaderSettings
  type: Class
  summary: "Specifies processing rules or option settings for the <see cref=&quot;T:System.Xaml.XamlXmlReader&quot;></see> XAML reader implementation."
  syntax:
    content: 'public class XamlXmlReaderSettings : System.Xaml.XamlReaderSettings'
  inheritance:
  - System.Object
  - System.Xaml.XamlReaderSettings
  implements: []
  inheritedMembers:
  - System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  - System.Xaml.XamlReaderSettings.BaseUri
  - System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  - System.Xaml.XamlReaderSettings.LocalAssembly
  - System.Xaml.XamlReaderSettings.ProvideLineInfo
  - System.Xaml.XamlReaderSettings.ValuesMustBeString
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Xaml.XamlXmlReaderSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: XamlXmlReaderSettings()
  nameWithType: XamlXmlReaderSettings.XamlXmlReaderSettings()
  fullName: System.Xaml.XamlXmlReaderSettings.XamlXmlReaderSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Xaml.XamlXmlReaderSettings&quot;></see> class."
  syntax:
    content: public XamlXmlReaderSettings ();
    parameters: []
  overload: System.Xaml.XamlXmlReaderSettings.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Xaml.XamlXmlReaderSettings.#ctor(System.Xaml.XamlXmlReaderSettings)
  id: '#ctor(System.Xaml.XamlXmlReaderSettings)'
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: XamlXmlReaderSettings(XamlXmlReaderSettings)
  nameWithType: XamlXmlReaderSettings.XamlXmlReaderSettings(XamlXmlReaderSettings)
  fullName: System.Xaml.XamlXmlReaderSettings.XamlXmlReaderSettings(XamlXmlReaderSettings)
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Xaml.XamlXmlReaderSettings&quot;></see> class by copying settings from an existing <see cref=&quot;T:System.Xaml.XamlXmlReaderSettings&quot;></see> object."
  syntax:
    content: public XamlXmlReaderSettings (System.Xaml.XamlXmlReaderSettings settings);
    parameters:
    - id: settings
      type: System.Xaml.XamlXmlReaderSettings
      description: "The existing  object to copy."
  overload: System.Xaml.XamlXmlReaderSettings.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Xaml.XamlXmlReaderSettings.CloseInput
  id: CloseInput
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: CloseInput
  nameWithType: XamlXmlReaderSettings.CloseInput
  fullName: System.Xaml.XamlXmlReaderSettings.CloseInput
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Gets or sets a value that indicates whether the underlying stream or text reader should be closed when the <see cref=&quot;T:System.Xaml.XamlXmlReader&quot;></see> is closed."
  syntax:
    content: public bool CloseInput { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if the underlying stream or reader should be closed when the <see cref=&quot;T:System.Xaml.XamlXmlReader&quot;></see> is closed; otherwise, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>. The default is <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>."
  overload: System.Xaml.XamlXmlReaderSettings.CloseInput*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  id: SkipXmlCompatibilityProcessing
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: SkipXmlCompatibilityProcessing
  nameWithType: XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  fullName: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Gets or sets a value that determines whether the reader should differ from the default <see cref=&quot;T:System.Xaml.XamlXmlReader&quot;></see> behavior of how markup compatibility content is processed."
  remarks: "The default handling behavior for XML markup compatibility in <xref:System.Xaml.XamlXmlReader> is that the <xref:System.Xaml.XamlXmlReader>, as provided for initialization, is wrapped in a created internal helper class. This helper class reads the markup compatibility nodes separately and enters into the nodes based on markup compatibility of the schema context.       Suggested scenarios for setting SkipXmlCompatibilityProcessing to `true` are:      -   You want to keep any markup compatibility content in the primary XAML stream.      -   You have already processed the markup compatibility because you are using a reader that can process markup compatibility content inline.      -   You choose to ignore XML compatibility conventions in your XAML reader implementation for reasons of performance."
  syntax:
    content: public bool SkipXmlCompatibilityProcessing { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if the initiating reader is directly used, which means that XML compatibility markup is processed as part of the main stream and compatibility is not considered. <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref> if the default behavior is used, which processes XML compatibility separately. The default is <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>."
  overload: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Xaml.XamlXmlReaderSettings.XmlLang
  id: XmlLang
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: XmlLang
  nameWithType: XamlXmlReaderSettings.XmlLang
  fullName: System.Xaml.XamlXmlReaderSettings.XmlLang
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Gets or sets the language setting value that the reader may promote to writers that write <xref uid=&quot;langword_csharp_xml:lang&quot; name=&quot;xml:lang&quot; href=&quot;&quot;></xref> attributes in nodes."
  remarks: "The caller is responsible for making sure that the string you provide is appropriate for `xml:lang` usage."
  syntax:
    content: public string XmlLang { get; set; }
    return:
      type: System.String
      description: "The string to use for possible <xref uid=&quot;langword_csharp_xml:lang&quot; name=&quot;xml:lang&quot; href=&quot;&quot;></xref> output that is based on the reader."
  overload: System.Xaml.XamlXmlReaderSettings.XmlLang*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve
  id: XmlSpacePreserve
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: XmlSpacePreserve
  nameWithType: XamlXmlReaderSettings.XmlSpacePreserve
  fullName: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Gets or sets a value that determines whether the XAML reader instructs any XAML writers to write <xref uid=&quot;langword_csharp_xml:space&quot; name=&quot;xml:space&quot; href=&quot;&quot;></xref> attributes in nodes. If that behavior is desired, this information is passed through shared XAML schema context."
  remarks: "The XML whitespace concepts are not robust enough to apply to XAML, and are typically ignored by XAML readers."
  syntax:
    content: public bool XmlSpacePreserve { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if writers that are processing the XAML node stream can write `xml:space=&quot;preserve&quot;` in output; <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref> if <xref uid=&quot;langword_csharp_xml:space&quot; name=&quot;xml:space&quot; href=&quot;&quot;></xref> attributes cannot be written in nodes."
  overload: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Xaml.XamlReaderSettings
  isExternal: false
  name: System.Xaml.XamlReaderSettings
- uid: System.Xaml.XamlXmlReaderSettings.#ctor
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XamlXmlReaderSettings()
  nameWithType: XamlXmlReaderSettings.XamlXmlReaderSettings()
  fullName: System.Xaml.XamlXmlReaderSettings.XamlXmlReaderSettings()
- uid: System.Xaml.XamlXmlReaderSettings.#ctor(System.Xaml.XamlXmlReaderSettings)
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XamlXmlReaderSettings(XamlXmlReaderSettings)
  nameWithType: XamlXmlReaderSettings.XamlXmlReaderSettings(XamlXmlReaderSettings)
  fullName: System.Xaml.XamlXmlReaderSettings.XamlXmlReaderSettings(XamlXmlReaderSettings)
- uid: System.Xaml.XamlXmlReaderSettings
  parent: System.Xaml
  isExternal: false
  name: XamlXmlReaderSettings
  nameWithType: XamlXmlReaderSettings
  fullName: System.Xaml.XamlXmlReaderSettings
- uid: System.Xaml.XamlXmlReaderSettings.CloseInput
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: CloseInput
  nameWithType: XamlXmlReaderSettings.CloseInput
  fullName: System.Xaml.XamlXmlReaderSettings.CloseInput
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: SkipXmlCompatibilityProcessing
  nameWithType: XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  fullName: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
- uid: System.Xaml.XamlXmlReaderSettings.XmlLang
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XmlLang
  nameWithType: XamlXmlReaderSettings.XmlLang
  fullName: System.Xaml.XamlXmlReaderSettings.XmlLang
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XmlSpacePreserve
  nameWithType: XamlXmlReaderSettings.XmlSpacePreserve
  fullName: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve
- uid: System.Xaml.XamlXmlReaderSettings.#ctor*
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XamlXmlReaderSettings
  nameWithType: XamlXmlReaderSettings.XamlXmlReaderSettings
- uid: System.Xaml.XamlXmlReaderSettings.CloseInput*
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: CloseInput
  nameWithType: XamlXmlReaderSettings.CloseInput
- uid: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing*
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: SkipXmlCompatibilityProcessing
  nameWithType: XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
- uid: System.Xaml.XamlXmlReaderSettings.XmlLang*
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XmlLang
  nameWithType: XamlXmlReaderSettings.XmlLang
- uid: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve*
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XmlSpacePreserve
  nameWithType: XamlXmlReaderSettings.XmlSpacePreserve
