### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement
  id: MexNamedPipeBindingCollectionElement
  children:
  - System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.#ctor
  - System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.GetDefault
  langs:
  - csharp
  name: MexNamedPipeBindingCollectionElement
  nameWithType: MexNamedPipeBindingCollectionElement
  fullName: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement
  type: Class
  summary: "Represents a collection of <see cref=&quot;T:System.ServiceModel.Configuration.MexNamedPipeBindingElement&quot;></see> instances."
  syntax:
    content: 'public class MexNamedPipeBindingCollectionElement : System.ServiceModel.Configuration.MexBindingBindingCollectionElement<System.ServiceModel.Channels.CustomBinding,System.ServiceModel.Configuration.MexNamedPipeBindingElement>'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.BindingCollectionElement
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2
  - System.ServiceModel.Configuration.MexBindingBindingCollectionElement`2
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.BindingCollectionElement.BindingName
  - System.ServiceModel.Configuration.MexBindingBindingCollectionElement`2.TryAdd(System.String,System.ServiceModel.Channels.Binding,System.Configuration.Configuration)
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.Bindings
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.BindingType
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.ConfiguredBindings
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.ContainsKey(System.String)
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.Properties
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement
  langs:
  - csharp
  name: MexNamedPipeBindingCollectionElement()
  nameWithType: MexNamedPipeBindingCollectionElement.MexNamedPipeBindingCollectionElement()
  fullName: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.MexNamedPipeBindingCollectionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement&quot;></see> class."
  syntax:
    content: public MexNamedPipeBindingCollectionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.GetDefault
  id: GetDefault
  parent: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement
  langs:
  - csharp
  name: GetDefault()
  nameWithType: MexNamedPipeBindingCollectionElement.GetDefault()
  fullName: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.GetDefault()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Retrieves the default values of a configuration element."
  syntax:
    content: protected override System.ServiceModel.Channels.Binding GetDefault ();
    parameters: []
    return:
      type: System.ServiceModel.Channels.Binding
      description: "To be added."
  overload: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.GetDefault*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.MexBindingBindingCollectionElement`2
  isExternal: false
  name: System.ServiceModel.Configuration.MexBindingBindingCollectionElement<System.ServiceModel.Channels.CustomBinding,System.ServiceModel.Configuration.MexNamedPipeBindingElement>
- uid: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.#ctor
  parent: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement
  isExternal: false
  name: MexNamedPipeBindingCollectionElement()
  nameWithType: MexNamedPipeBindingCollectionElement.MexNamedPipeBindingCollectionElement()
  fullName: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.MexNamedPipeBindingCollectionElement()
- uid: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.GetDefault
  parent: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement
  isExternal: false
  name: GetDefault()
  nameWithType: MexNamedPipeBindingCollectionElement.GetDefault()
  fullName: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.GetDefault()
- uid: System.ServiceModel.Channels.Binding
  parent: System.ServiceModel.Channels
  isExternal: true
  name: Binding
  nameWithType: Binding
  fullName: System.ServiceModel.Channels.Binding
- uid: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.#ctor*
  parent: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement
  isExternal: false
  name: MexNamedPipeBindingCollectionElement
  nameWithType: MexNamedPipeBindingCollectionElement.MexNamedPipeBindingCollectionElement
- uid: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement.GetDefault*
  parent: System.ServiceModel.Configuration.MexNamedPipeBindingCollectionElement
  isExternal: false
  name: GetDefault
  nameWithType: MexNamedPipeBindingCollectionElement.GetDefault
