### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.DeploymentSection
  id: DeploymentSection
  children:
  - System.Web.Configuration.DeploymentSection.#ctor
  - System.Web.Configuration.DeploymentSection.Properties
  - System.Web.Configuration.DeploymentSection.Retail
  langs:
  - csharp
  name: DeploymentSection
  nameWithType: DeploymentSection
  fullName: System.Web.Configuration.DeploymentSection
  type: Class
  summary: "Defines a configuration setting that is typically used on a production server to override application-level settings that are appropriate only on development computers."
  syntax:
    content: 'public sealed class DeploymentSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.DeploymentSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.DeploymentSection
  langs:
  - csharp
  name: DeploymentSection()
  nameWithType: DeploymentSection.DeploymentSection()
  fullName: System.Web.Configuration.DeploymentSection.DeploymentSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Web.Configuration.DeploymentSection&quot;></see> class."
  remarks: "This constructor is called by the ASP.NET configuration system. You obtain an instance of the <xref:System.Web.Configuration.DeploymentSection> class by using the <xref:System.Configuration.Configuration.GetSection%2A> method."
  syntax:
    content: public DeploymentSection ();
    parameters: []
  overload: System.Web.Configuration.DeploymentSection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.DeploymentSection.Properties
  id: Properties
  parent: System.Web.Configuration.DeploymentSection
  langs:
  - csharp
  name: Properties
  nameWithType: DeploymentSection.Properties
  fullName: System.Web.Configuration.DeploymentSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Web.Configuration.DeploymentSection.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.DeploymentSection.Retail
  id: Retail
  parent: System.Web.Configuration.DeploymentSection
  langs:
  - csharp
  name: Retail
  nameWithType: DeploymentSection.Retail
  fullName: System.Web.Configuration.DeploymentSection.Retail
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets or sets a value that specifies whether Web applications on the computer are deployed in <xref uid=&quot;langword_csharp_retail&quot; name=&quot;retail&quot; href=&quot;&quot;></xref> mode."
  remarks: "When Retail is `true`, ASP.NET disables trace output, disables debug capabilities, and disables detailed system-generated error messages for remote users. For applications that have a `customErrors` element in the application Web.config file, the `mode` attribute is forced to `On`. These settings override any settings that are made in application Web.config files.      > [!NOTE] >  When you use the `retail` setting, you should continue to set the `debug` attribute to `false` in application Web.config files that are deployed to the server. The `debug` setting disables request execution timeout, and this is not overridden by the `retail` setting. For more information, see. [Most Common ASP.NET Support issues - Reporting from deep inside Microsoft Developer Support](http://www.hanselman.com/blog/MostCommonASPNETSupportIssuesReportingFromDeepInsideMicrosoftDeveloperSupport.aspx) on Scott Hanselman&quot;s blog."
  example:
  - "The following configuration file example shows how to set this property to `true` in the machine.config file. The machine.config file is located in this folder:  \n  \n `%windir%\\Microsoft.NET\\Framework\\<frameworkversion>\\Config`  \n  \n```  \n<system.web>  \n  <deployment   \n    retail=\"true\" />  \n</system.web>  \n```"
  syntax:
    content: public bool Retail { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if Web applications are deployed in <xref uid=&quot;langword_csharp_retail&quot; name=&quot;retail&quot; href=&quot;&quot;></xref> mode; otherwise, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>. The default is <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>."
  overload: System.Web.Configuration.DeploymentSection.Retail*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.DeploymentSection.#ctor
  parent: System.Web.Configuration.DeploymentSection
  isExternal: false
  name: DeploymentSection()
  nameWithType: DeploymentSection.DeploymentSection()
  fullName: System.Web.Configuration.DeploymentSection.DeploymentSection()
- uid: System.Web.Configuration.DeploymentSection.Properties
  parent: System.Web.Configuration.DeploymentSection
  isExternal: false
  name: Properties
  nameWithType: DeploymentSection.Properties
  fullName: System.Web.Configuration.DeploymentSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.DeploymentSection.Retail
  parent: System.Web.Configuration.DeploymentSection
  isExternal: false
  name: Retail
  nameWithType: DeploymentSection.Retail
  fullName: System.Web.Configuration.DeploymentSection.Retail
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.DeploymentSection.#ctor*
  parent: System.Web.Configuration.DeploymentSection
  isExternal: false
  name: DeploymentSection
  nameWithType: DeploymentSection.DeploymentSection
- uid: System.Web.Configuration.DeploymentSection.Properties*
  parent: System.Web.Configuration.DeploymentSection
  isExternal: false
  name: Properties
  nameWithType: DeploymentSection.Properties
- uid: System.Web.Configuration.DeploymentSection.Retail*
  parent: System.Web.Configuration.DeploymentSection
  isExternal: false
  name: Retail
  nameWithType: DeploymentSection.Retail
