### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement
  id: WorkflowInstanceManagementElement
  children:
  - System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.#ctor
  - System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.AuthorizedWindowsGroup
  - System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.BehaviorType
  - System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.CreateBehavior
  - System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.Properties
  langs:
  - csharp
  name: WorkflowInstanceManagementElement
  nameWithType: WorkflowInstanceManagementElement
  fullName: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement
  type: Class
  summary: "Adds the <see cref=&quot;T:System.ServiceModel.Activities.Description.WorkflowInstanceManagementBehavior&quot;></see> to the service host."
  syntax:
    content: 'public class WorkflowInstanceManagementElement : System.ServiceModel.Configuration.BehaviorExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  - System.ServiceModel.Configuration.BehaviorExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement
  langs:
  - csharp
  name: WorkflowInstanceManagementElement()
  nameWithType: WorkflowInstanceManagementElement.WorkflowInstanceManagementElement()
  fullName: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.WorkflowInstanceManagementElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement&quot;></see> class."
  syntax:
    content: public WorkflowInstanceManagementElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.AuthorizedWindowsGroup
  id: AuthorizedWindowsGroup
  parent: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement
  langs:
  - csharp
  name: AuthorizedWindowsGroup
  nameWithType: WorkflowInstanceManagementElement.AuthorizedWindowsGroup
  fullName: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.AuthorizedWindowsGroup
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "Gets or sets the Windows group of users authorized to use the workflow instance control endpoint."
  remarks: 'Defaults to “BUILTIN\Administrators”. Valid settings are: a local Windows group or a Windows domain.'
  syntax:
    content: public string AuthorizedWindowsGroup { get; set; }
    return:
      type: System.String
      description: "The Windows group of users authorized to use the workflow instance control endpoint."
  overload: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.AuthorizedWindowsGroup*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.BehaviorType
  id: BehaviorType
  parent: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement
  langs:
  - csharp
  name: BehaviorType
  nameWithType: WorkflowInstanceManagementElement.BehaviorType
  fullName: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.BehaviorType
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "Gets the type of the behavior associated with this configuration element."
  syntax:
    content: public override Type BehaviorType { get; }
    return:
      type: System.Type
      description: "The type of behavior associated with this configuration element."
  overload: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.BehaviorType*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.CreateBehavior
  id: CreateBehavior
  parent: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement
  langs:
  - csharp
  name: CreateBehavior()
  nameWithType: WorkflowInstanceManagementElement.CreateBehavior()
  fullName: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.CreateBehavior()
  type: Method
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "Creates the <see cref=&quot;T:System.ServiceModel.Activities.Description.WorkflowInstanceManagementBehavior&quot;></see> behavior."
  syntax:
    content: protected override object CreateBehavior ();
    parameters: []
    return:
      type: System.Object
      description: "To be added."
  overload: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.CreateBehavior*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement
  langs:
  - csharp
  name: Properties
  nameWithType: WorkflowInstanceManagementElement.Properties
  fullName: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "Gets the collection of properties associated with this configuration element."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "The properties associated with this configuration element."
  overload: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.BehaviorExtensionElement
  isExternal: false
  name: System.ServiceModel.Configuration.BehaviorExtensionElement
- uid: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.#ctor
  parent: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement
  isExternal: false
  name: WorkflowInstanceManagementElement()
  nameWithType: WorkflowInstanceManagementElement.WorkflowInstanceManagementElement()
  fullName: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.WorkflowInstanceManagementElement()
- uid: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.AuthorizedWindowsGroup
  parent: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement
  isExternal: false
  name: AuthorizedWindowsGroup
  nameWithType: WorkflowInstanceManagementElement.AuthorizedWindowsGroup
  fullName: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.AuthorizedWindowsGroup
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.BehaviorType
  parent: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement
  isExternal: false
  name: BehaviorType
  nameWithType: WorkflowInstanceManagementElement.BehaviorType
  fullName: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.BehaviorType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.CreateBehavior
  parent: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement
  isExternal: false
  name: CreateBehavior()
  nameWithType: WorkflowInstanceManagementElement.CreateBehavior()
  fullName: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.CreateBehavior()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.Properties
  parent: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement
  isExternal: false
  name: Properties
  nameWithType: WorkflowInstanceManagementElement.Properties
  fullName: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.#ctor*
  parent: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement
  isExternal: false
  name: WorkflowInstanceManagementElement
  nameWithType: WorkflowInstanceManagementElement.WorkflowInstanceManagementElement
- uid: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.AuthorizedWindowsGroup*
  parent: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement
  isExternal: false
  name: AuthorizedWindowsGroup
  nameWithType: WorkflowInstanceManagementElement.AuthorizedWindowsGroup
- uid: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.BehaviorType*
  parent: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement
  isExternal: false
  name: BehaviorType
  nameWithType: WorkflowInstanceManagementElement.BehaviorType
- uid: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.CreateBehavior*
  parent: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement
  isExternal: false
  name: CreateBehavior
  nameWithType: WorkflowInstanceManagementElement.CreateBehavior
- uid: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement.Properties*
  parent: System.ServiceModel.Activities.Configuration.WorkflowInstanceManagementElement
  isExternal: false
  name: Properties
  nameWithType: WorkflowInstanceManagementElement.Properties
