### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.SystemWebExtensionsSectionGroup
  id: SystemWebExtensionsSectionGroup
  children:
  - System.Web.Configuration.SystemWebExtensionsSectionGroup.#ctor
  - System.Web.Configuration.SystemWebExtensionsSectionGroup.Scripting
  langs:
  - csharp
  name: SystemWebExtensionsSectionGroup
  nameWithType: SystemWebExtensionsSectionGroup
  fullName: System.Web.Configuration.SystemWebExtensionsSectionGroup
  type: Class
  summary: "Represents a group of related sections in a configuration file. This class cannot be inherited."
  syntax:
    content: 'public sealed class SystemWebExtensionsSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.SystemWebExtensionsSectionGroup.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.SystemWebExtensionsSectionGroup
  langs:
  - csharp
  name: SystemWebExtensionsSectionGroup()
  nameWithType: SystemWebExtensionsSectionGroup.SystemWebExtensionsSectionGroup()
  fullName: System.Web.Configuration.SystemWebExtensionsSectionGroup.SystemWebExtensionsSectionGroup()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Web.Configuration.SystemWebExtensionsSectionGroup&quot;></see> class."
  syntax:
    content: public SystemWebExtensionsSectionGroup ();
    parameters: []
  overload: System.Web.Configuration.SystemWebExtensionsSectionGroup.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.SystemWebExtensionsSectionGroup.Scripting
  id: Scripting
  parent: System.Web.Configuration.SystemWebExtensionsSectionGroup
  langs:
  - csharp
  name: Scripting
  nameWithType: SystemWebExtensionsSectionGroup.Scripting
  fullName: System.Web.Configuration.SystemWebExtensionsSectionGroup.Scripting
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Gets a <see cref=&quot;T:System.Web.Configuration.ScriptingSectionGroup&quot;></see> object that is derived from the current system configuration."
  syntax:
    content: public System.Web.Configuration.ScriptingSectionGroup Scripting { get; }
    return:
      type: System.Web.Configuration.ScriptingSectionGroup
      description: "A <see cref=&quot;T:System.Web.Configuration.ScriptingSectionGroup&quot;></see> object."
  overload: System.Web.Configuration.SystemWebExtensionsSectionGroup.Scripting*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: System.Configuration.ConfigurationSectionGroup
- uid: System.Web.Configuration.SystemWebExtensionsSectionGroup.#ctor
  parent: System.Web.Configuration.SystemWebExtensionsSectionGroup
  isExternal: false
  name: SystemWebExtensionsSectionGroup()
  nameWithType: SystemWebExtensionsSectionGroup.SystemWebExtensionsSectionGroup()
  fullName: System.Web.Configuration.SystemWebExtensionsSectionGroup.SystemWebExtensionsSectionGroup()
- uid: System.Web.Configuration.SystemWebExtensionsSectionGroup.Scripting
  parent: System.Web.Configuration.SystemWebExtensionsSectionGroup
  isExternal: false
  name: Scripting
  nameWithType: SystemWebExtensionsSectionGroup.Scripting
  fullName: System.Web.Configuration.SystemWebExtensionsSectionGroup.Scripting
- uid: System.Web.Configuration.ScriptingSectionGroup
  parent: System.Web.Configuration
  isExternal: false
  name: ScriptingSectionGroup
  nameWithType: ScriptingSectionGroup
  fullName: System.Web.Configuration.ScriptingSectionGroup
- uid: System.Web.Configuration.SystemWebExtensionsSectionGroup.#ctor*
  parent: System.Web.Configuration.SystemWebExtensionsSectionGroup
  isExternal: false
  name: SystemWebExtensionsSectionGroup
  nameWithType: SystemWebExtensionsSectionGroup.SystemWebExtensionsSectionGroup
- uid: System.Web.Configuration.SystemWebExtensionsSectionGroup.Scripting*
  parent: System.Web.Configuration.SystemWebExtensionsSectionGroup
  isExternal: false
  name: Scripting
  nameWithType: SystemWebExtensionsSectionGroup.Scripting
