### YamlMime:ManagedReference
items:
- uid: System.Configuration.ApplicationSettingsGroup
  id: ApplicationSettingsGroup
  children:
  - System.Configuration.ApplicationSettingsGroup.#ctor
  langs:
  - csharp
  name: ApplicationSettingsGroup
  nameWithType: ApplicationSettingsGroup
  fullName: System.Configuration.ApplicationSettingsGroup
  type: Class
  summary: "Represents a grouping of related application settings sections within a configuration file. This class cannot be inherited."
  syntax:
    content: 'public sealed class ApplicationSettingsGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ApplicationSettingsGroup.#ctor
  id: '#ctor'
  parent: System.Configuration.ApplicationSettingsGroup
  langs:
  - csharp
  name: ApplicationSettingsGroup()
  nameWithType: ApplicationSettingsGroup.ApplicationSettingsGroup()
  fullName: System.Configuration.ApplicationSettingsGroup.ApplicationSettingsGroup()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.ApplicationSettingsGroup&quot;></see> class."
  syntax:
    content: public ApplicationSettingsGroup ();
    parameters: []
  overload: System.Configuration.ApplicationSettingsGroup.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: System.Configuration.ConfigurationSectionGroup
- uid: System.Configuration.ApplicationSettingsGroup.#ctor
  parent: System.Configuration.ApplicationSettingsGroup
  isExternal: false
  name: ApplicationSettingsGroup()
  nameWithType: ApplicationSettingsGroup.ApplicationSettingsGroup()
  fullName: System.Configuration.ApplicationSettingsGroup.ApplicationSettingsGroup()
- uid: System.Configuration.ApplicationSettingsGroup.#ctor*
  parent: System.Configuration.ApplicationSettingsGroup
  isExternal: false
  name: ApplicationSettingsGroup
  nameWithType: ApplicationSettingsGroup.ApplicationSettingsGroup
