### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.PartialTrustVisibleAssembly
  id: PartialTrustVisibleAssembly
  children:
  - System.Web.Configuration.PartialTrustVisibleAssembly.#ctor(System.String,System.String)
  - System.Web.Configuration.PartialTrustVisibleAssembly.AssemblyName
  - System.Web.Configuration.PartialTrustVisibleAssembly.Properties
  - System.Web.Configuration.PartialTrustVisibleAssembly.PublicKey
  langs:
  - csharp
  name: PartialTrustVisibleAssembly
  nameWithType: PartialTrustVisibleAssembly
  fullName: System.Web.Configuration.PartialTrustVisibleAssembly
  type: Class
  summary: "Configures a partial-trust assembly. This class cannot be inherited."
  remarks: "The PartialTrustVisibleAssembly configures an assembly that is marked with the Partially Trusted Callers Attribute (APTCA) for use in a partial-trust ASP.NET application. For more information, see <xref:System.Security.AllowPartiallyTrustedCallersAttribute>."
  syntax:
    content: 'public sealed class PartialTrustVisibleAssembly : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.PartialTrustVisibleAssembly.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.PartialTrustVisibleAssembly
  langs:
  - csharp
  name: PartialTrustVisibleAssembly(String,String)
  nameWithType: PartialTrustVisibleAssembly.PartialTrustVisibleAssembly(String,String)
  fullName: System.Web.Configuration.PartialTrustVisibleAssembly.PartialTrustVisibleAssembly(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Web.Configuration.PartialTrustVisibleAssembly&quot;></see> class."
  syntax:
    content: public PartialTrustVisibleAssembly (string assemblyName, string publicKey);
    parameters:
    - id: assemblyName
      type: System.String
      description: "The assembly name."
    - id: publicKey
      type: System.String
      description: "The hexadecimal string representation of the public key that is associated with the assembly."
  overload: System.Web.Configuration.PartialTrustVisibleAssembly.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.PartialTrustVisibleAssembly.AssemblyName
  id: AssemblyName
  parent: System.Web.Configuration.PartialTrustVisibleAssembly
  langs:
  - csharp
  name: AssemblyName
  nameWithType: PartialTrustVisibleAssembly.AssemblyName
  fullName: System.Web.Configuration.PartialTrustVisibleAssembly.AssemblyName
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets or sets the assembly name."
  syntax:
    content: public string AssemblyName { get; set; }
    return:
      type: System.String
      description: "The assembly name."
  overload: System.Web.Configuration.PartialTrustVisibleAssembly.AssemblyName*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.PartialTrustVisibleAssembly.Properties
  id: Properties
  parent: System.Web.Configuration.PartialTrustVisibleAssembly
  langs:
  - csharp
  name: Properties
  nameWithType: PartialTrustVisibleAssembly.Properties
  fullName: System.Web.Configuration.PartialTrustVisibleAssembly.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Web.Configuration.PartialTrustVisibleAssembly.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.PartialTrustVisibleAssembly.PublicKey
  id: PublicKey
  parent: System.Web.Configuration.PartialTrustVisibleAssembly
  langs:
  - csharp
  name: PublicKey
  nameWithType: PartialTrustVisibleAssembly.PublicKey
  fullName: System.Web.Configuration.PartialTrustVisibleAssembly.PublicKey
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets or sets the assembly public key."
  syntax:
    content: public string PublicKey { get; set; }
    return:
      type: System.String
      description: "The hexadecimal string representation of the public key that is associated with the assembly."
  overload: System.Web.Configuration.PartialTrustVisibleAssembly.PublicKey*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.PartialTrustVisibleAssembly.#ctor(System.String,System.String)
  parent: System.Web.Configuration.PartialTrustVisibleAssembly
  isExternal: false
  name: PartialTrustVisibleAssembly(String,String)
  nameWithType: PartialTrustVisibleAssembly.PartialTrustVisibleAssembly(String,String)
  fullName: System.Web.Configuration.PartialTrustVisibleAssembly.PartialTrustVisibleAssembly(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.PartialTrustVisibleAssembly.AssemblyName
  parent: System.Web.Configuration.PartialTrustVisibleAssembly
  isExternal: false
  name: AssemblyName
  nameWithType: PartialTrustVisibleAssembly.AssemblyName
  fullName: System.Web.Configuration.PartialTrustVisibleAssembly.AssemblyName
- uid: System.Web.Configuration.PartialTrustVisibleAssembly.Properties
  parent: System.Web.Configuration.PartialTrustVisibleAssembly
  isExternal: false
  name: Properties
  nameWithType: PartialTrustVisibleAssembly.Properties
  fullName: System.Web.Configuration.PartialTrustVisibleAssembly.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.PartialTrustVisibleAssembly.PublicKey
  parent: System.Web.Configuration.PartialTrustVisibleAssembly
  isExternal: false
  name: PublicKey
  nameWithType: PartialTrustVisibleAssembly.PublicKey
  fullName: System.Web.Configuration.PartialTrustVisibleAssembly.PublicKey
- uid: System.Web.Configuration.PartialTrustVisibleAssembly.#ctor*
  parent: System.Web.Configuration.PartialTrustVisibleAssembly
  isExternal: false
  name: PartialTrustVisibleAssembly
  nameWithType: PartialTrustVisibleAssembly.PartialTrustVisibleAssembly
- uid: System.Web.Configuration.PartialTrustVisibleAssembly.AssemblyName*
  parent: System.Web.Configuration.PartialTrustVisibleAssembly
  isExternal: false
  name: AssemblyName
  nameWithType: PartialTrustVisibleAssembly.AssemblyName
- uid: System.Web.Configuration.PartialTrustVisibleAssembly.Properties*
  parent: System.Web.Configuration.PartialTrustVisibleAssembly
  isExternal: false
  name: Properties
  nameWithType: PartialTrustVisibleAssembly.Properties
- uid: System.Web.Configuration.PartialTrustVisibleAssembly.PublicKey*
  parent: System.Web.Configuration.PartialTrustVisibleAssembly
  isExternal: false
  name: PublicKey
  nameWithType: PartialTrustVisibleAssembly.PublicKey
