### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement
  id: StandardBindingOptionalReliableSessionElement
  children:
  - System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.#ctor
  - System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.ApplyConfiguration(System.ServiceModel.OptionalReliableSession)
  - System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.Enabled
  - System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.InitializeFrom(System.ServiceModel.OptionalReliableSession)
  - System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.Properties
  langs:
  - csharp
  name: StandardBindingOptionalReliableSessionElement
  nameWithType: StandardBindingOptionalReliableSessionElement
  fullName: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement
  type: Class
  summary: "Represents the optional configuration setting for WS-Reliable Messaging defined in a standard binding. This class cannot be inherited."
  syntax:
    content: 'public sealed class StandardBindingOptionalReliableSessionElement : System.ServiceModel.Configuration.StandardBindingReliableSessionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.StandardBindingReliableSessionElement.ApplyConfiguration(System.ServiceModel.ReliableSession)
  - System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InactivityTimeout
  - System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InitializeFrom(System.ServiceModel.ReliableSession)
  - System.ServiceModel.Configuration.StandardBindingReliableSessionElement.Ordered
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement
  langs:
  - csharp
  name: StandardBindingOptionalReliableSessionElement()
  nameWithType: StandardBindingOptionalReliableSessionElement.StandardBindingOptionalReliableSessionElement()
  fullName: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.StandardBindingOptionalReliableSessionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement&quot;></see> class."
  syntax:
    content: public StandardBindingOptionalReliableSessionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.ApplyConfiguration(System.ServiceModel.OptionalReliableSession)
  id: ApplyConfiguration(System.ServiceModel.OptionalReliableSession)
  parent: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement
  langs:
  - csharp
  name: ApplyConfiguration(OptionalReliableSession)
  nameWithType: StandardBindingOptionalReliableSessionElement.ApplyConfiguration(OptionalReliableSession)
  fullName: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.ApplyConfiguration(OptionalReliableSession)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Applies the content of a specified binding element to this configuration section."
  syntax:
    content: public void ApplyConfiguration (System.ServiceModel.OptionalReliableSession optionalReliableSession);
    parameters:
    - id: optionalReliableSession
      type: System.ServiceModel.OptionalReliableSession
      description: "The configuration element to apply."
  overload: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.ApplyConfiguration*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "\n    optionalReliableSession is ."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.Enabled
  id: Enabled
  parent: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement
  langs:
  - csharp
  name: Enabled
  nameWithType: StandardBindingOptionalReliableSessionElement.Enabled
  fullName: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.Enabled
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets a Boolean value that specifies whether reliable session is enabled for this binding."
  syntax:
    content: public bool Enabled { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if reliable session is enabled for this binding; otherwise, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>."
  overload: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.Enabled*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.InitializeFrom(System.ServiceModel.OptionalReliableSession)
  id: InitializeFrom(System.ServiceModel.OptionalReliableSession)
  parent: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement
  langs:
  - csharp
  name: InitializeFrom(OptionalReliableSession)
  nameWithType: StandardBindingOptionalReliableSessionElement.InitializeFrom(OptionalReliableSession)
  fullName: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.InitializeFrom(OptionalReliableSession)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes the settings of this configuration element from the content of a specified configuration element."
  syntax:
    content: public void InitializeFrom (System.ServiceModel.OptionalReliableSession optionalReliableSession);
    parameters:
    - id: optionalReliableSession
      type: System.ServiceModel.OptionalReliableSession
      description: "The configuration element whose settings are to be copied."
  overload: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.InitializeFrom*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "\n    optionalReliableSession is ."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement
  langs:
  - csharp
  name: Properties
  nameWithType: StandardBindingOptionalReliableSessionElement.Properties
  fullName: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  isExternal: false
  name: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
- uid: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.#ctor
  parent: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement
  isExternal: false
  name: StandardBindingOptionalReliableSessionElement()
  nameWithType: StandardBindingOptionalReliableSessionElement.StandardBindingOptionalReliableSessionElement()
  fullName: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.StandardBindingOptionalReliableSessionElement()
- uid: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.ApplyConfiguration(System.ServiceModel.OptionalReliableSession)
  parent: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement
  isExternal: false
  name: ApplyConfiguration(OptionalReliableSession)
  nameWithType: StandardBindingOptionalReliableSessionElement.ApplyConfiguration(OptionalReliableSession)
  fullName: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.ApplyConfiguration(OptionalReliableSession)
- uid: System.ServiceModel.OptionalReliableSession
  parent: System.ServiceModel
  isExternal: false
  name: OptionalReliableSession
  nameWithType: OptionalReliableSession
  fullName: System.ServiceModel.OptionalReliableSession
- uid: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.Enabled
  parent: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement
  isExternal: false
  name: Enabled
  nameWithType: StandardBindingOptionalReliableSessionElement.Enabled
  fullName: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.Enabled
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.InitializeFrom(System.ServiceModel.OptionalReliableSession)
  parent: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement
  isExternal: false
  name: InitializeFrom(OptionalReliableSession)
  nameWithType: StandardBindingOptionalReliableSessionElement.InitializeFrom(OptionalReliableSession)
  fullName: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.InitializeFrom(OptionalReliableSession)
- uid: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.Properties
  parent: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement
  isExternal: false
  name: Properties
  nameWithType: StandardBindingOptionalReliableSessionElement.Properties
  fullName: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.#ctor*
  parent: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement
  isExternal: false
  name: StandardBindingOptionalReliableSessionElement
  nameWithType: StandardBindingOptionalReliableSessionElement.StandardBindingOptionalReliableSessionElement
- uid: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.ApplyConfiguration*
  parent: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement
  isExternal: false
  name: ApplyConfiguration
  nameWithType: StandardBindingOptionalReliableSessionElement.ApplyConfiguration
- uid: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.Enabled*
  parent: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement
  isExternal: false
  name: Enabled
  nameWithType: StandardBindingOptionalReliableSessionElement.Enabled
- uid: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.InitializeFrom*
  parent: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement
  isExternal: false
  name: InitializeFrom
  nameWithType: StandardBindingOptionalReliableSessionElement.InitializeFrom
- uid: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement.Properties*
  parent: System.ServiceModel.Configuration.StandardBindingOptionalReliableSessionElement
  isExternal: false
  name: Properties
  nameWithType: StandardBindingOptionalReliableSessionElement.Properties
