### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement
  id: PeerCustomResolverElement
  children:
  - System.ServiceModel.Configuration.PeerCustomResolverElement.#ctor
  - System.ServiceModel.Configuration.PeerCustomResolverElement.Address
  - System.ServiceModel.Configuration.PeerCustomResolverElement.Binding
  - System.ServiceModel.Configuration.PeerCustomResolverElement.BindingConfiguration
  - System.ServiceModel.Configuration.PeerCustomResolverElement.Headers
  - System.ServiceModel.Configuration.PeerCustomResolverElement.Identity
  - System.ServiceModel.Configuration.PeerCustomResolverElement.Properties
  - System.ServiceModel.Configuration.PeerCustomResolverElement.ResolverType
  langs:
  - csharp
  name: PeerCustomResolverElement
  nameWithType: PeerCustomResolverElement
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement
  type: Class
  summary: "Represents a configuration element for a custom peer resolver."
  syntax:
    content: 'public sealed class PeerCustomResolverElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  langs:
  - csharp
  name: PeerCustomResolverElement()
  nameWithType: PeerCustomResolverElement.PeerCustomResolverElement()
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.PeerCustomResolverElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new default instance of the <see cref=&quot;T:System.ServiceModel.Configuration.PeerCustomResolverElement&quot;></see> class."
  syntax:
    content: public PeerCustomResolverElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.PeerCustomResolverElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Address
  id: Address
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  langs:
  - csharp
  name: Address
  nameWithType: PeerCustomResolverElement.Address
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.Address
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Contains the URI of the schema used for the custom peer resolver configuration XML."
  syntax:
    content: public Uri Address { get; set; }
    return:
      type: System.Uri
      description: "The URI the schema used for the custom peer resolver configuration XML."
  overload: System.ServiceModel.Configuration.PeerCustomResolverElement.Address*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Binding
  id: Binding
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  langs:
  - csharp
  name: Binding
  nameWithType: PeerCustomResolverElement.Binding
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.Binding
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets and sets the name of the string binding used for the custom peer resolver."
  syntax:
    content: public string Binding { get; set; }
    return:
      type: System.String
      description: "The name of the string binding used for the custom peer resolver."
  overload: System.ServiceModel.Configuration.PeerCustomResolverElement.Binding*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.BindingConfiguration
  id: BindingConfiguration
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  langs:
  - csharp
  name: BindingConfiguration
  nameWithType: PeerCustomResolverElement.BindingConfiguration
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.BindingConfiguration
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets and sets the binding configuration string for the custom peer resolver."
  syntax:
    content: public string BindingConfiguration { get; set; }
    return:
      type: System.String
      description: "The binding configuration string for the custom peer resolver."
  overload: System.ServiceModel.Configuration.PeerCustomResolverElement.BindingConfiguration*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Headers
  id: Headers
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  langs:
  - csharp
  name: Headers
  nameWithType: PeerCustomResolverElement.Headers
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.Headers
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets a configuration element that defines the collection that contains the headers used for SOAP messages handled by the custom peer resolver."
  syntax:
    content: public System.ServiceModel.Configuration.AddressHeaderCollectionElement Headers { get; }
    return:
      type: System.ServiceModel.Configuration.AddressHeaderCollectionElement
      description: "<see cref=&quot;T:System.ServiceModel.Configuration.AddressHeaderCollectionElement&quot;></see> that defines the collection that contains the headers used for SOAP messages handled by the custom peer resolver."
  overload: System.ServiceModel.Configuration.PeerCustomResolverElement.Headers*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Identity
  id: Identity
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  langs:
  - csharp
  name: Identity
  nameWithType: PeerCustomResolverElement.Identity
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.Identity
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets the identity for custom peer resolvers configured with this element."
  syntax:
    content: public System.ServiceModel.Configuration.IdentityElement Identity { get; }
    return:
      type: System.ServiceModel.Configuration.IdentityElement
      description: "<see cref=&quot;T:System.ServiceModel.Configuration.IdentityElement&quot;></see> that contains the identity for custom peer resolvers configured with this element."
  overload: System.ServiceModel.Configuration.PeerCustomResolverElement.Identity*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  langs:
  - csharp
  name: Properties
  nameWithType: PeerCustomResolverElement.Properties
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.PeerCustomResolverElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.ResolverType
  id: ResolverType
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  langs:
  - csharp
  name: ResolverType
  nameWithType: PeerCustomResolverElement.ResolverType
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.ResolverType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets and sets a string value that contains the &quot;type&quot; of the custom peer resolver."
  syntax:
    content: public string ResolverType { get; set; }
    return:
      type: System.String
      description: "A string value that contains the &quot;type&quot; of the custom peer resolver."
  overload: System.ServiceModel.Configuration.PeerCustomResolverElement.ResolverType*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.#ctor
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: PeerCustomResolverElement()
  nameWithType: PeerCustomResolverElement.PeerCustomResolverElement()
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.PeerCustomResolverElement()
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Address
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: Address
  nameWithType: PeerCustomResolverElement.Address
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.Address
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Binding
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: Binding
  nameWithType: PeerCustomResolverElement.Binding
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.Binding
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.BindingConfiguration
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: BindingConfiguration
  nameWithType: PeerCustomResolverElement.BindingConfiguration
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.BindingConfiguration
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Headers
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: Headers
  nameWithType: PeerCustomResolverElement.Headers
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.Headers
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: AddressHeaderCollectionElement
  nameWithType: AddressHeaderCollectionElement
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Identity
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: Identity
  nameWithType: PeerCustomResolverElement.Identity
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.Identity
- uid: System.ServiceModel.Configuration.IdentityElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: IdentityElement
  nameWithType: IdentityElement
  fullName: System.ServiceModel.Configuration.IdentityElement
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Properties
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: Properties
  nameWithType: PeerCustomResolverElement.Properties
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.ResolverType
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: ResolverType
  nameWithType: PeerCustomResolverElement.ResolverType
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement.ResolverType
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.#ctor*
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: PeerCustomResolverElement
  nameWithType: PeerCustomResolverElement.PeerCustomResolverElement
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Address*
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: Address
  nameWithType: PeerCustomResolverElement.Address
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Binding*
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: Binding
  nameWithType: PeerCustomResolverElement.Binding
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.BindingConfiguration*
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: BindingConfiguration
  nameWithType: PeerCustomResolverElement.BindingConfiguration
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Headers*
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: Headers
  nameWithType: PeerCustomResolverElement.Headers
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Identity*
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: Identity
  nameWithType: PeerCustomResolverElement.Identity
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.Properties*
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: Properties
  nameWithType: PeerCustomResolverElement.Properties
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement.ResolverType*
  parent: System.ServiceModel.Configuration.PeerCustomResolverElement
  isExternal: false
  name: ResolverType
  nameWithType: PeerCustomResolverElement.ResolverType
