### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.SecureConversationServiceElement
  id: SecureConversationServiceElement
  children:
  - System.ServiceModel.Configuration.SecureConversationServiceElement.#ctor
  - System.ServiceModel.Configuration.SecureConversationServiceElement.Copy(System.ServiceModel.Configuration.SecureConversationServiceElement)
  - System.ServiceModel.Configuration.SecureConversationServiceElement.Properties
  - System.ServiceModel.Configuration.SecureConversationServiceElement.SecurityStateEncoderType
  langs:
  - csharp
  name: SecureConversationServiceElement
  nameWithType: SecureConversationServiceElement
  fullName: System.ServiceModel.Configuration.SecureConversationServiceElement
  type: Class
  summary: "Represents a configuration element that specifies the settings for a secure conversation service. This class cannot be inherited."
  syntax:
    content: 'public sealed class SecureConversationServiceElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.SecureConversationServiceElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.SecureConversationServiceElement
  langs:
  - csharp
  name: SecureConversationServiceElement()
  nameWithType: SecureConversationServiceElement.SecureConversationServiceElement()
  fullName: System.ServiceModel.Configuration.SecureConversationServiceElement.SecureConversationServiceElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.SecureConversationServiceElement&quot;></see> class."
  syntax:
    content: public SecureConversationServiceElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.SecureConversationServiceElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.SecureConversationServiceElement.Copy(System.ServiceModel.Configuration.SecureConversationServiceElement)
  id: Copy(System.ServiceModel.Configuration.SecureConversationServiceElement)
  parent: System.ServiceModel.Configuration.SecureConversationServiceElement
  langs:
  - csharp
  name: Copy(SecureConversationServiceElement)
  nameWithType: SecureConversationServiceElement.Copy(SecureConversationServiceElement)
  fullName: System.ServiceModel.Configuration.SecureConversationServiceElement.Copy(SecureConversationServiceElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Copies the content of the specified configuration element to this configuration element."
  syntax:
    content: public void Copy (System.ServiceModel.Configuration.SecureConversationServiceElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.SecureConversationServiceElement
      description: "The configuration element to be copied."
  overload: System.ServiceModel.Configuration.SecureConversationServiceElement.Copy*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "\n    from is  or empty."
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "The configuration file is read-only."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.SecureConversationServiceElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.SecureConversationServiceElement
  langs:
  - csharp
  name: Properties
  nameWithType: SecureConversationServiceElement.Properties
  fullName: System.ServiceModel.Configuration.SecureConversationServiceElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.SecureConversationServiceElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.SecureConversationServiceElement.SecurityStateEncoderType
  id: SecurityStateEncoderType
  parent: System.ServiceModel.Configuration.SecureConversationServiceElement
  langs:
  - csharp
  name: SecurityStateEncoderType
  nameWithType: SecureConversationServiceElement.SecurityStateEncoderType
  fullName: System.ServiceModel.Configuration.SecureConversationServiceElement.SecurityStateEncoderType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets the type of <see cref=&quot;T:System.ServiceModel.Security.SecurityStateEncoder&quot;></see> to be used."
  syntax:
    content: public string SecurityStateEncoderType { get; set; }
    return:
      type: System.String
      description: "The type of <see cref=&quot;T:System.ServiceModel.Security.SecurityStateEncoder&quot;></see> to be used."
  overload: System.ServiceModel.Configuration.SecureConversationServiceElement.SecurityStateEncoderType*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.SecureConversationServiceElement.#ctor
  parent: System.ServiceModel.Configuration.SecureConversationServiceElement
  isExternal: false
  name: SecureConversationServiceElement()
  nameWithType: SecureConversationServiceElement.SecureConversationServiceElement()
  fullName: System.ServiceModel.Configuration.SecureConversationServiceElement.SecureConversationServiceElement()
- uid: System.ServiceModel.Configuration.SecureConversationServiceElement.Copy(System.ServiceModel.Configuration.SecureConversationServiceElement)
  parent: System.ServiceModel.Configuration.SecureConversationServiceElement
  isExternal: false
  name: Copy(SecureConversationServiceElement)
  nameWithType: SecureConversationServiceElement.Copy(SecureConversationServiceElement)
  fullName: System.ServiceModel.Configuration.SecureConversationServiceElement.Copy(SecureConversationServiceElement)
- uid: System.ServiceModel.Configuration.SecureConversationServiceElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: SecureConversationServiceElement
  nameWithType: SecureConversationServiceElement
  fullName: System.ServiceModel.Configuration.SecureConversationServiceElement
- uid: System.ServiceModel.Configuration.SecureConversationServiceElement.Properties
  parent: System.ServiceModel.Configuration.SecureConversationServiceElement
  isExternal: false
  name: Properties
  nameWithType: SecureConversationServiceElement.Properties
  fullName: System.ServiceModel.Configuration.SecureConversationServiceElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.SecureConversationServiceElement.SecurityStateEncoderType
  parent: System.ServiceModel.Configuration.SecureConversationServiceElement
  isExternal: false
  name: SecurityStateEncoderType
  nameWithType: SecureConversationServiceElement.SecurityStateEncoderType
  fullName: System.ServiceModel.Configuration.SecureConversationServiceElement.SecurityStateEncoderType
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.SecureConversationServiceElement.#ctor*
  parent: System.ServiceModel.Configuration.SecureConversationServiceElement
  isExternal: false
  name: SecureConversationServiceElement
  nameWithType: SecureConversationServiceElement.SecureConversationServiceElement
- uid: System.ServiceModel.Configuration.SecureConversationServiceElement.Copy*
  parent: System.ServiceModel.Configuration.SecureConversationServiceElement
  isExternal: false
  name: Copy
  nameWithType: SecureConversationServiceElement.Copy
- uid: System.ServiceModel.Configuration.SecureConversationServiceElement.Properties*
  parent: System.ServiceModel.Configuration.SecureConversationServiceElement
  isExternal: false
  name: Properties
  nameWithType: SecureConversationServiceElement.Properties
- uid: System.ServiceModel.Configuration.SecureConversationServiceElement.SecurityStateEncoderType*
  parent: System.ServiceModel.Configuration.SecureConversationServiceElement
  isExternal: false
  name: SecurityStateEncoderType
  nameWithType: SecureConversationServiceElement.SecurityStateEncoderType
