### YamlMime:ManagedReference
items:
- uid: System.Activities.WorkflowApplicationCompletedEventArgs
  id: WorkflowApplicationCompletedEventArgs
  children:
  - System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState
  - System.Activities.WorkflowApplicationCompletedEventArgs.Outputs
  - System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException
  langs:
  - csharp
  name: WorkflowApplicationCompletedEventArgs
  nameWithType: WorkflowApplicationCompletedEventArgs
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs
  type: Class
  summary: "Provides information about a workflow instance that has completed its execution."
  remarks: ''
  example:
  - "The following code example inspects the WorkflowApplicationCompletedEventArgs passed into the <xref:System.Activities.WorkflowApplication.Completed%2A> handler of a <xref:System.Activities.WorkflowApplication> instance and displays information about how the workflow completed.  \n  \n [!code-cs[CFX_WorkflowApplicationExample#4](~/add/codesnippet/CSharp/t-system.activities.work_5_1.cs)]"
  syntax:
    content: 'public class WorkflowApplicationCompletedEventArgs : System.Activities.WorkflowApplicationEventArgs'
  inheritance:
  - System.EventArgs
  - System.Activities.WorkflowApplicationEventArgs
  implements: []
  inheritedMembers:
  - System.Activities.WorkflowApplicationEventArgs.GetInstanceExtensions``1
  - System.Activities.WorkflowApplicationEventArgs.InstanceId
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState
  id: CompletionState
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  langs:
  - csharp
  name: CompletionState
  nameWithType: WorkflowApplicationCompletedEventArgs.CompletionState
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Gets the completion state of the workflow instance, which indicates whether the workflow instance completed successfully, was canceled, or faulted."
  remarks: ''
  example:
  - "The following code example inspects the <xref:System.Activities.WorkflowApplicationCompletedEventArgs> passed into the <xref:System.Activities.WorkflowApplication.Completed%2A> handler of a <xref:System.Activities.WorkflowApplication> instance and displays information about how the workflow completed.  \n  \n [!code-cs[CFX_WorkflowApplicationExample#4](~/add/codesnippet/CSharp/p-system.activities.work_8_1.cs)]"
  syntax:
    content: public System.Activities.ActivityInstanceState CompletionState { get; }
    return:
      type: System.Activities.ActivityInstanceState
      description: "The completion state of the workflow instance, which indicates whether the workflow instance completed successfully, was canceled, or faulted."
  overload: System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.Outputs
  id: Outputs
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  langs:
  - csharp
  name: Outputs
  nameWithType: WorkflowApplicationCompletedEventArgs.Outputs
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs.Outputs
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Gets a dictionary that contains the values of <see cref=&quot;T:System.Activities.OutArgument&quot;></see>s of the workflow instance’s root activity, keyed by argument name."
  remarks: ''
  example:
  - "The following code example inspects the <xref:System.Activities.WorkflowApplicationCompletedEventArgs> passed into the <xref:System.Activities.WorkflowApplication.Completed%2A> handler of a <xref:System.Activities.WorkflowApplication> instance and displays information about how the workflow completed.  \n  \n [!code-cs[CFX_WorkflowApplicationExample#4](~/add/codesnippet/CSharp/p-system.activities.work_5_1.cs)]"
  syntax:
    content: public System.Collections.Generic.IDictionary<string,object> Outputs { get; }
    return:
      type: System.Collections.Generic.IDictionary{System.String,System.Object}
      description: "A dictionary that contains the values of <see cref=&quot;T:System.Activities.OutArgument&quot;></see>s of the workflow instance’s root activity, keyed by argument name."
  overload: System.Activities.WorkflowApplicationCompletedEventArgs.Outputs*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException
  id: TerminationException
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  langs:
  - csharp
  name: TerminationException
  nameWithType: WorkflowApplicationCompletedEventArgs.TerminationException
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Gets the exception associated with the termination of the workflow instance."
  remarks: ''
  example:
  - "The following code example inspects the <xref:System.Activities.WorkflowApplicationCompletedEventArgs> passed into the <xref:System.Activities.WorkflowApplication.Completed%2A> handler of a <xref:System.Activities.WorkflowApplication> instance and displays information about how the workflow completed.  \n  \n [!code-cs[CFX_WorkflowApplicationExample#4](~/add/codesnippet/CSharp/p-system.activities.work_9_1.cs)]"
  syntax:
    content: public Exception TerminationException { get; }
    return:
      type: System.Exception
      description: "The exception associated with the termination of the workflow instance."
  overload: System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Activities.WorkflowApplicationEventArgs
  isExternal: false
  name: System.Activities.WorkflowApplicationEventArgs
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  isExternal: false
  name: CompletionState
  nameWithType: WorkflowApplicationCompletedEventArgs.CompletionState
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState
- uid: System.Activities.ActivityInstanceState
  parent: System.Activities
  isExternal: false
  name: ActivityInstanceState
  nameWithType: ActivityInstanceState
  fullName: System.Activities.ActivityInstanceState
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.Outputs
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  isExternal: false
  name: Outputs
  nameWithType: WorkflowApplicationCompletedEventArgs.Outputs
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs.Outputs
- uid: System.Collections.Generic.IDictionary{System.String,System.Object}
  parent: System.Collections.Generic
  isExternal: true
  name: IDictionary<String,Object>
  nameWithType: IDictionary<String,Object>
  fullName: System.Collections.Generic.IDictionary<System.String,System.Object>
  spec.csharp:
  - uid: System.Collections.Generic.IDictionary`2
    name: IDictionary
    nameWithType: IDictionary
    fullName: IDictionary<System.String,System.Object>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String
  - name: ','
    nameWithType: ','
    fullName: ','
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: Object
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  isExternal: false
  name: TerminationException
  nameWithType: WorkflowApplicationCompletedEventArgs.TerminationException
  fullName: System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.CompletionState*
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  isExternal: false
  name: CompletionState
  nameWithType: WorkflowApplicationCompletedEventArgs.CompletionState
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.Outputs*
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  isExternal: false
  name: Outputs
  nameWithType: WorkflowApplicationCompletedEventArgs.Outputs
- uid: System.Activities.WorkflowApplicationCompletedEventArgs.TerminationException*
  parent: System.Activities.WorkflowApplicationCompletedEventArgs
  isExternal: false
  name: TerminationException
  nameWithType: WorkflowApplicationCompletedEventArgs.TerminationException
