### YamlMime:ManagedReference
items:
- uid: System.Configuration.TimeSpanValidator
  id: TimeSpanValidator
  children:
  - System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan)
  - System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean)
  - System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean,System.Int64)
  - System.Configuration.TimeSpanValidator.CanValidate(System.Type)
  - System.Configuration.TimeSpanValidator.Validate(System.Object)
  langs:
  - csharp
  name: TimeSpanValidator
  nameWithType: TimeSpanValidator
  fullName: System.Configuration.TimeSpanValidator
  type: Class
  summary: "Provides validation of a &lt;xref:System.TimeSpan&gt; object."
  remarks: "The TimeSpanValidator class is used to ensure that a <xref:System.TimeSpan> object meets specific criteria. The <xref:System.Configuration.TimeSpanValidator.%23ctor%2A> constructor with two parameters ensures that both a minimum and a maximum <xref:System.TimeSpan> value are adhered to. The <xref:System.Configuration.TimeSpanValidator.%23ctor%2A> constructor with three parameters checks both the minimum and maximum <xref:System.TimeSpan> values, as well as whether the validation range is exclusive. The <xref:System.Configuration.TimeSpanValidator.%23ctor%2A> constructor with four parameters checks the previous three parameters and also checks whether the <xref:System.TimeSpan> value is equal to a specific number of seconds.       The <xref:System.Configuration.TimeSpanValidator.CanValidate%2A> method determines whether the object type being validated matches the expected type. The object being validated is passed as a parameter of the <xref:System.Configuration.TimeSpanValidator.Validate%2A> method."
  example:
  - "The following code example demonstrates how to use the TimeSpanValidator type.  \n  \n [!code-cs[System.Configuration.TimeSpanValidator#1](~/add/codesnippet/CSharp/t-system.configuration.t_2_1.cs)]\n [!code-vb[System.Configuration.TimeSpanValidator#1](~/add/codesnippet/VisualBasic/t-system.configuration.t_2_1.vb)]"
  syntax:
    content: 'public class TimeSpanValidator : System.Configuration.ConfigurationValidatorBase'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationValidatorBase
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan)
  id: '#ctor(System.TimeSpan,System.TimeSpan)'
  parent: System.Configuration.TimeSpanValidator
  langs:
  - csharp
  name: TimeSpanValidator(TimeSpan,TimeSpan)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.TimeSpanValidator&quot;></see> class, based on supplied parameters."
  remarks: "When the TimeSpanValidator constructor with two parameters is used, the <xref:System.Configuration.TimeSpanValidator> object validates that a <xref:System.TimeSpan> value adheres to a specific range."
  syntax:
    content: public TimeSpanValidator (TimeSpan minValue, TimeSpan maxValue);
    parameters:
    - id: minValue
      type: System.TimeSpan
      description: "A <xref:System.TimeSpan> object that specifies the minimum time allowed to pass validation."
    - id: maxValue
      type: System.TimeSpan
      description: "A <xref:System.TimeSpan> object that specifies the maximum time allowed to pass validation."
  overload: System.Configuration.TimeSpanValidator.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean)
  id: '#ctor(System.TimeSpan,System.TimeSpan,System.Boolean)'
  parent: System.Configuration.TimeSpanValidator
  langs:
  - csharp
  name: TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.TimeSpanValidator&quot;></see> class, based on supplied parameters."
  remarks: "The TimeSpanValidator constructor checks both the minimum and maximum <xref:System.TimeSpan> values, as well as whether the validation range is exclusive. When the `rangeIsExclusive` parameter is set to `true`, the <xref:System.TimeSpan> value must not be between the `minValue` and `maxValue` values."
  syntax:
    content: public TimeSpanValidator (TimeSpan minValue, TimeSpan maxValue, bool rangeIsExclusive);
    parameters:
    - id: minValue
      type: System.TimeSpan
      description: "A <xref:System.TimeSpan> object that specifies the minimum time allowed to pass validation."
    - id: maxValue
      type: System.TimeSpan
      description: "A <xref:System.TimeSpan> object that specifies the maximum time allowed to pass validation."
    - id: rangeIsExclusive
      type: System.Boolean
      description: "A <xref:System.Boolean> value that specifies whether the validation range is exclusive."
  overload: System.Configuration.TimeSpanValidator.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean,System.Int64)
  id: '#ctor(System.TimeSpan,System.TimeSpan,System.Boolean,System.Int64)'
  parent: System.Configuration.TimeSpanValidator
  langs:
  - csharp
  name: TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.TimeSpanValidator&quot;></see> class, based on supplied parameters."
  remarks: "When the `resolutionInSeconds` parameter is specified, the <xref:System.TimeSpan> object being validated must be equal to this value in order to pass validation."
  example:
  - "The following code example demonstrates how to use the TimeSpanValidator constructor. This code example is part of a larger example provided for the <xref:System.Configuration.TimeSpanValidator> class.  \n  \n [!code-cs[System.Configuration.TimeSpanValidator#2](~/add/codesnippet/CSharp/5fd5fd48-b5cd-41a3-9e7a-_1.cs)]\n [!code-vb[System.Configuration.TimeSpanValidator#2](~/add/codesnippet/VisualBasic/5fd5fd48-b5cd-41a3-9e7a-_1.vb)]"
  syntax:
    content: public TimeSpanValidator (TimeSpan minValue, TimeSpan maxValue, bool rangeIsExclusive, long resolutionInSeconds);
    parameters:
    - id: minValue
      type: System.TimeSpan
      description: "A <xref:System.TimeSpan> object that specifies the minimum time allowed to pass validation."
    - id: maxValue
      type: System.TimeSpan
      description: "A <xref:System.TimeSpan> object that specifies the maximum time allowed to pass validation."
    - id: rangeIsExclusive
      type: System.Boolean
      description: "A <xref:System.Boolean> value that specifies whether the validation range is exclusive."
    - id: resolutionInSeconds
      type: System.Int64
      description: "An <xref:System.Int64> value that specifies a number of seconds."
  overload: System.Configuration.TimeSpanValidator.#ctor*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "\n    resolutionInSeconds is less than .  \n  \n \\- or -  \n  \n minValue is greater than maxValue."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanValidator.CanValidate(System.Type)
  id: CanValidate(System.Type)
  parent: System.Configuration.TimeSpanValidator
  langs:
  - csharp
  name: CanValidate(Type)
  nameWithType: TimeSpanValidator.CanValidate(Type)
  fullName: System.Configuration.TimeSpanValidator.CanValidate(Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Determines whether the type of the object can be validated."
  remarks: ''
  example:
  - "The following code example demonstrates how to use the CanValidate method. This code example is part of a larger example provided for the <xref:System.Configuration.TimeSpanValidator> class.  \n  \n [!code-cs[System.Configuration.TimeSpanValidator#3](~/add/codesnippet/CSharp/m-system.configuration.t_1_1.cs)]\n [!code-vb[System.Configuration.TimeSpanValidator#3](~/add/codesnippet/VisualBasic/m-system.configuration.t_1_1.vb)]"
  syntax:
    content: public override bool CanValidate (Type type);
    parameters:
    - id: type
      type: System.Type
      description: "The type of the object."
    return:
      type: System.Boolean
      description: "To be added."
  overload: System.Configuration.TimeSpanValidator.CanValidate*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.TimeSpanValidator.Validate(System.Object)
  id: Validate(System.Object)
  parent: System.Configuration.TimeSpanValidator
  langs:
  - csharp
  name: Validate(Object)
  nameWithType: TimeSpanValidator.Validate(Object)
  fullName: System.Configuration.TimeSpanValidator.Validate(Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Determines whether the value of an object is valid."
  remarks: "The <xref:System.Configuration.TimeSpanValidator> object contains the rules necessary to validate a <xref:System.TimeSpan> object. The rules are established when an instance of the <xref:System.Configuration.TimeSpanValidator> class is created. The object to validate is passed as a parameter of the Validate method."
  example:
  - "The following code example demonstrates how to use the Validate method. This code example is part of a larger example provided for the <xref:System.Configuration.TimeSpanValidator> class.  \n  \n [!code-cs[System.Configuration.TimeSpanValidator#4](~/add/codesnippet/CSharp/m-system.configuration.t_2_1.cs)]\n [!code-vb[System.Configuration.TimeSpanValidator#4](~/add/codesnippet/VisualBasic/m-system.configuration.t_2_1.vb)]"
  syntax:
    content: public override void Validate (object value);
    parameters:
    - id: value
      type: System.Object
      description: "The value of an object."
  overload: System.Configuration.TimeSpanValidator.Validate*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan)
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: TimeSpanValidator(TimeSpan,TimeSpan)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan)
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean)
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean,System.Int64)
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Configuration.TimeSpanValidator.CanValidate(System.Type)
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: CanValidate(Type)
  nameWithType: TimeSpanValidator.CanValidate(Type)
  fullName: System.Configuration.TimeSpanValidator.CanValidate(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.TimeSpanValidator.Validate(System.Object)
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: Validate(Object)
  nameWithType: TimeSpanValidator.Validate(Object)
  fullName: System.Configuration.TimeSpanValidator.Validate(Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.TimeSpanValidator.#ctor*
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: TimeSpanValidator
  nameWithType: TimeSpanValidator.TimeSpanValidator
- uid: System.Configuration.TimeSpanValidator.CanValidate*
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: CanValidate
  nameWithType: TimeSpanValidator.CanValidate
- uid: System.Configuration.TimeSpanValidator.Validate*
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: Validate
  nameWithType: TimeSpanValidator.Validate
