### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  id: WindowsStreamSecurityElement
  children:
  - System.ServiceModel.Configuration.WindowsStreamSecurityElement.#ctor
  - System.ServiceModel.Configuration.WindowsStreamSecurityElement.ApplyConfiguration(System.ServiceModel.Channels.BindingElement)
  - System.ServiceModel.Configuration.WindowsStreamSecurityElement.BindingElementType
  - System.ServiceModel.Configuration.WindowsStreamSecurityElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.WindowsStreamSecurityElement.CreateBindingElement
  - System.ServiceModel.Configuration.WindowsStreamSecurityElement.InitializeFrom(System.ServiceModel.Channels.BindingElement)
  - System.ServiceModel.Configuration.WindowsStreamSecurityElement.Properties
  - System.ServiceModel.Configuration.WindowsStreamSecurityElement.ProtectionLevel
  langs:
  - csharp
  name: WindowsStreamSecurityElement
  nameWithType: WindowsStreamSecurityElement
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  type: Class
  summary: "Represents a configuration element that is used to specify settings for Windows stream security for a binding. This class cannot be inherited."
  syntax:
    content: 'public sealed class WindowsStreamSecurityElement : System.ServiceModel.Configuration.BindingElementExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  - System.ServiceModel.Configuration.BindingElementExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  langs:
  - csharp
  name: WindowsStreamSecurityElement()
  nameWithType: WindowsStreamSecurityElement.WindowsStreamSecurityElement()
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.WindowsStreamSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.WindowsStreamSecurityElement&quot;></see> class."
  syntax:
    content: public WindowsStreamSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.WindowsStreamSecurityElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.ApplyConfiguration(System.ServiceModel.Channels.BindingElement)
  id: ApplyConfiguration(System.ServiceModel.Channels.BindingElement)
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  langs:
  - csharp
  name: ApplyConfiguration(BindingElement)
  nameWithType: WindowsStreamSecurityElement.ApplyConfiguration(BindingElement)
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.ApplyConfiguration(BindingElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Applies the content of a specified binding element to this binding configuration element."
  syntax:
    content: public override void ApplyConfiguration (System.ServiceModel.Channels.BindingElement bindingElement);
    parameters:
    - id: bindingElement
      type: System.ServiceModel.Channels.BindingElement
      description: "A binding element."
  overload: System.ServiceModel.Configuration.WindowsStreamSecurityElement.ApplyConfiguration*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.BindingElementType
  id: BindingElementType
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  langs:
  - csharp
  name: BindingElementType
  nameWithType: WindowsStreamSecurityElement.BindingElementType
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.BindingElementType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets the &lt;xref:System.Type&gt; object that represents the binding element."
  syntax:
    content: public override Type BindingElementType { get; }
    return:
      type: System.Type
      description: "A &lt;xref:System.Type&gt; object that represents the binding type."
  overload: System.ServiceModel.Configuration.WindowsStreamSecurityElement.BindingElementType*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  id: CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  langs:
  - csharp
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: WindowsStreamSecurityElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.CopyFrom(ServiceModelExtensionElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Copies the content of a specified configuration element to this configuration element."
  syntax:
    content: public override void CopyFrom (System.ServiceModel.Configuration.ServiceModelExtensionElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.ServiceModelExtensionElement
      description: "The configuration element to be copied."
  overload: System.ServiceModel.Configuration.WindowsStreamSecurityElement.CopyFrom*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.CreateBindingElement
  id: CreateBindingElement
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  langs:
  - csharp
  name: CreateBindingElement()
  nameWithType: WindowsStreamSecurityElement.CreateBindingElement()
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.CreateBindingElement()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.ServiceModel.Channels.BindingElement CreateBindingElement ();
    parameters: []
    return:
      type: System.ServiceModel.Channels.BindingElement
      description: "To be added."
  overload: System.ServiceModel.Configuration.WindowsStreamSecurityElement.CreateBindingElement*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.InitializeFrom(System.ServiceModel.Channels.BindingElement)
  id: InitializeFrom(System.ServiceModel.Channels.BindingElement)
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  langs:
  - csharp
  name: InitializeFrom(BindingElement)
  nameWithType: WindowsStreamSecurityElement.InitializeFrom(BindingElement)
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.InitializeFrom(BindingElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override void InitializeFrom (System.ServiceModel.Channels.BindingElement bindingElement);
    parameters:
    - id: bindingElement
      type: System.ServiceModel.Channels.BindingElement
      description: "To be added."
  overload: System.ServiceModel.Configuration.WindowsStreamSecurityElement.InitializeFrom*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: WindowsStreamSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.WindowsStreamSecurityElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.ProtectionLevel
  id: ProtectionLevel
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  langs:
  - csharp
  name: ProtectionLevel
  nameWithType: WindowsStreamSecurityElement.ProtectionLevel
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.ProtectionLevel
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets the message-level security used."
  remarks: "This property specifies the message-level security used for signing and encryption. Signing messages mitigates the risk of a third party tampering with the message while it is being transferred. Encryption provides data-level privacy during transport."
  syntax:
    content: public System.Net.Security.ProtectionLevel ProtectionLevel { get; set; }
    return:
      type: System.Net.Security.ProtectionLevel
      description: "A <see cref=&quot;T:System.Net.Security.ProtectionLevel&quot;></see> that specifies the message-level security used. The default value is <see cref=&quot;T:System.Net.Security.ProtectionLevel&quot;></see> ."
  overload: System.ServiceModel.Configuration.WindowsStreamSecurityElement.ProtectionLevel*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement
  isExternal: false
  name: System.ServiceModel.Configuration.BindingElementExtensionElement
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: WindowsStreamSecurityElement()
  nameWithType: WindowsStreamSecurityElement.WindowsStreamSecurityElement()
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.WindowsStreamSecurityElement()
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.ApplyConfiguration(System.ServiceModel.Channels.BindingElement)
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: ApplyConfiguration(BindingElement)
  nameWithType: WindowsStreamSecurityElement.ApplyConfiguration(BindingElement)
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.ApplyConfiguration(BindingElement)
- uid: System.ServiceModel.Channels.BindingElement
  parent: System.ServiceModel.Channels
  isExternal: true
  name: BindingElement
  nameWithType: BindingElement
  fullName: System.ServiceModel.Channels.BindingElement
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.BindingElementType
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: BindingElementType
  nameWithType: WindowsStreamSecurityElement.BindingElementType
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.BindingElementType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: WindowsStreamSecurityElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.CopyFrom(ServiceModelExtensionElement)
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelExtensionElement
  nameWithType: ServiceModelExtensionElement
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.CreateBindingElement
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: CreateBindingElement()
  nameWithType: WindowsStreamSecurityElement.CreateBindingElement()
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.CreateBindingElement()
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.InitializeFrom(System.ServiceModel.Channels.BindingElement)
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: InitializeFrom(BindingElement)
  nameWithType: WindowsStreamSecurityElement.InitializeFrom(BindingElement)
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.InitializeFrom(BindingElement)
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.Properties
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: Properties
  nameWithType: WindowsStreamSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.ProtectionLevel
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: ProtectionLevel
  nameWithType: WindowsStreamSecurityElement.ProtectionLevel
  fullName: System.ServiceModel.Configuration.WindowsStreamSecurityElement.ProtectionLevel
- uid: System.Net.Security.ProtectionLevel
  parent: System.Net.Security
  isExternal: false
  name: ProtectionLevel
  nameWithType: ProtectionLevel
  fullName: System.Net.Security.ProtectionLevel
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: WindowsStreamSecurityElement
  nameWithType: WindowsStreamSecurityElement.WindowsStreamSecurityElement
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.ApplyConfiguration*
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: ApplyConfiguration
  nameWithType: WindowsStreamSecurityElement.ApplyConfiguration
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.BindingElementType*
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: BindingElementType
  nameWithType: WindowsStreamSecurityElement.BindingElementType
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.CopyFrom*
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: CopyFrom
  nameWithType: WindowsStreamSecurityElement.CopyFrom
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.CreateBindingElement*
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: CreateBindingElement
  nameWithType: WindowsStreamSecurityElement.CreateBindingElement
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.InitializeFrom*
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: InitializeFrom
  nameWithType: WindowsStreamSecurityElement.InitializeFrom
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: Properties
  nameWithType: WindowsStreamSecurityElement.Properties
- uid: System.ServiceModel.Configuration.WindowsStreamSecurityElement.ProtectionLevel*
  parent: System.ServiceModel.Configuration.WindowsStreamSecurityElement
  isExternal: false
  name: ProtectionLevel
  nameWithType: WindowsStreamSecurityElement.ProtectionLevel
