### YamlMime:ManagedReference
items:
- uid: System.Configuration.NameValueConfigurationElement
  id: NameValueConfigurationElement
  children:
  - System.Configuration.NameValueConfigurationElement.#ctor(System.String,System.String)
  - System.Configuration.NameValueConfigurationElement.Name
  - System.Configuration.NameValueConfigurationElement.Properties
  - System.Configuration.NameValueConfigurationElement.Value
  langs:
  - csharp
  name: NameValueConfigurationElement
  nameWithType: NameValueConfigurationElement
  fullName: System.Configuration.NameValueConfigurationElement
  type: Class
  summary: "A configuration element that contains a &lt;xref:System.String&gt; name and &lt;xref:System.String&gt; value. This class cannot be inherited."
  remarks: "The NameValueConfigurationElement inherits from the <xref:System.Configuration.ConfigurationElement> base class. The <xref:System.Configuration.ConfigurationElement> represents an element within a configuration file.       There is a difference between the NameValueConfigurationElement class and <xref:System.Configuration.KeyValueConfigurationElement> class. The NameValueConfigurationElement class does not require the first string to be unique, whereas <xref:System.Configuration.KeyValueConfigurationElement> class requires the first string to be a key, and therefore unique in the collection."
  syntax:
    content: 'public sealed class NameValueConfigurationElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.NameValueConfigurationElement.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Configuration.NameValueConfigurationElement
  langs:
  - csharp
  name: NameValueConfigurationElement(String,String)
  nameWithType: NameValueConfigurationElement.NameValueConfigurationElement(String,String)
  fullName: System.Configuration.NameValueConfigurationElement.NameValueConfigurationElement(String,String)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.NameValueConfigurationElement&quot;></see> class based on supplied parameters."
  syntax:
    content: public NameValueConfigurationElement (string name, string value);
    parameters:
    - id: name
      type: System.String
      description: "The name of the  object."
    - id: value
      type: System.String
      description: "The value of the  object."
  overload: System.Configuration.NameValueConfigurationElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.NameValueConfigurationElement.Name
  id: Name
  parent: System.Configuration.NameValueConfigurationElement
  langs:
  - csharp
  name: Name
  nameWithType: NameValueConfigurationElement.Name
  fullName: System.Configuration.NameValueConfigurationElement.Name
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets the name of the <see cref=&quot;T:System.Configuration.NameValueConfigurationElement&quot;></see> object."
  syntax:
    content: public string Name { get; }
    return:
      type: System.String
      description: "The name of the <see cref=&quot;T:System.Configuration.NameValueConfigurationElement&quot;></see> object."
  overload: System.Configuration.NameValueConfigurationElement.Name*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.NameValueConfigurationElement.Properties
  id: Properties
  parent: System.Configuration.NameValueConfigurationElement
  langs:
  - csharp
  name: Properties
  nameWithType: NameValueConfigurationElement.Properties
  fullName: System.Configuration.NameValueConfigurationElement.Properties
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Configuration.NameValueConfigurationElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.NameValueConfigurationElement.Value
  id: Value
  parent: System.Configuration.NameValueConfigurationElement
  langs:
  - csharp
  name: Value
  nameWithType: NameValueConfigurationElement.Value
  fullName: System.Configuration.NameValueConfigurationElement.Value
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets or sets the value of the <see cref=&quot;T:System.Configuration.NameValueConfigurationElement&quot;></see> object."
  syntax:
    content: public string Value { get; set; }
    return:
      type: System.String
      description: "The value of the <see cref=&quot;T:System.Configuration.NameValueConfigurationElement&quot;></see> object."
  overload: System.Configuration.NameValueConfigurationElement.Value*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Configuration.NameValueConfigurationElement.#ctor(System.String,System.String)
  parent: System.Configuration.NameValueConfigurationElement
  isExternal: false
  name: NameValueConfigurationElement(String,String)
  nameWithType: NameValueConfigurationElement.NameValueConfigurationElement(String,String)
  fullName: System.Configuration.NameValueConfigurationElement.NameValueConfigurationElement(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.NameValueConfigurationElement.Name
  parent: System.Configuration.NameValueConfigurationElement
  isExternal: false
  name: Name
  nameWithType: NameValueConfigurationElement.Name
  fullName: System.Configuration.NameValueConfigurationElement.Name
- uid: System.Configuration.NameValueConfigurationElement.Properties
  parent: System.Configuration.NameValueConfigurationElement
  isExternal: false
  name: Properties
  nameWithType: NameValueConfigurationElement.Properties
  fullName: System.Configuration.NameValueConfigurationElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Configuration.NameValueConfigurationElement.Value
  parent: System.Configuration.NameValueConfigurationElement
  isExternal: false
  name: Value
  nameWithType: NameValueConfigurationElement.Value
  fullName: System.Configuration.NameValueConfigurationElement.Value
- uid: System.Configuration.NameValueConfigurationElement.#ctor*
  parent: System.Configuration.NameValueConfigurationElement
  isExternal: false
  name: NameValueConfigurationElement
  nameWithType: NameValueConfigurationElement.NameValueConfigurationElement
- uid: System.Configuration.NameValueConfigurationElement.Name*
  parent: System.Configuration.NameValueConfigurationElement
  isExternal: false
  name: Name
  nameWithType: NameValueConfigurationElement.Name
- uid: System.Configuration.NameValueConfigurationElement.Properties*
  parent: System.Configuration.NameValueConfigurationElement
  isExternal: false
  name: Properties
  nameWithType: NameValueConfigurationElement.Properties
- uid: System.Configuration.NameValueConfigurationElement.Value*
  parent: System.Configuration.NameValueConfigurationElement
  isExternal: false
  name: Value
  nameWithType: NameValueConfigurationElement.Value
