### YamlMime:ManagedReference
items:
- uid: System.Configuration.ISettingsProviderService
  id: ISettingsProviderService
  children:
  - System.Configuration.ISettingsProviderService.GetSettingsProvider(System.Configuration.SettingsProperty)
  langs:
  - csharp
  name: ISettingsProviderService
  nameWithType: ISettingsProviderService
  fullName: System.Configuration.ISettingsProviderService
  type: Interface
  summary: "Provides an interface for defining an alternate application settings provider."
  remarks: "The <xref:System.Configuration.IPersistComponentSettings> interface enables controls and components hosted in an application to persist their application settings in a manner largely transparent to the application. However, in some cases, the application or environment may need to override the settings provider natively used by a component with one of its own choosing. The ISettingsProviderService interface enables the creation of a lightweight service that communicates such an alternate settings provider, typically offered through the owning <xref:System.ComponentModel.Container>.       ISettingsProviderService is commonly used by design-time tools and debuggers that provide special support for application settings. To make such an arrangement function seamlessly, the <xref:System.Configuration.ApplicationSettingsBase> class contains constructors that take a reference to the owning component. These constructors automatically query for compatible settings providers."
  syntax:
    content: public interface ISettingsProviderService
  implements: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ISettingsProviderService.GetSettingsProvider(System.Configuration.SettingsProperty)
  id: GetSettingsProvider(System.Configuration.SettingsProperty)
  parent: System.Configuration.ISettingsProviderService
  langs:
  - csharp
  name: GetSettingsProvider(SettingsProperty)
  nameWithType: ISettingsProviderService.GetSettingsProvider(SettingsProperty)
  fullName: System.Configuration.ISettingsProviderService.GetSettingsProvider(SettingsProperty)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Returns the settings provider compatible with the specified settings property."
  remarks: "The GetSettingsProvider method enables an <xref:System.Configuration.ISettingsProviderService> to offer its serialization services to any sited component. This method determines if the associated settings provider can persist the specified application settings property type. If it can, this method returns a reference to that settings provider; otherwise it returns `null`."
  syntax:
    content: public System.Configuration.SettingsProvider GetSettingsProvider (System.Configuration.SettingsProperty property);
    parameters:
    - id: property
      type: System.Configuration.SettingsProperty
      description: "The  that requires serialization."
    return:
      type: System.Configuration.SettingsProvider
      description: "To be added."
  overload: System.Configuration.ISettingsProviderService.GetSettingsProvider*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ISettingsProviderService.GetSettingsProvider(System.Configuration.SettingsProperty)
  parent: System.Configuration.ISettingsProviderService
  isExternal: false
  name: GetSettingsProvider(SettingsProperty)
  nameWithType: ISettingsProviderService.GetSettingsProvider(SettingsProperty)
  fullName: System.Configuration.ISettingsProviderService.GetSettingsProvider(SettingsProperty)
- uid: System.Configuration.SettingsProvider
  parent: System.Configuration
  isExternal: false
  name: SettingsProvider
  nameWithType: SettingsProvider
  fullName: System.Configuration.SettingsProvider
- uid: System.Configuration.SettingsProperty
  parent: System.Configuration
  isExternal: false
  name: SettingsProperty
  nameWithType: SettingsProperty
  fullName: System.Configuration.SettingsProperty
- uid: System.Configuration.ISettingsProviderService.GetSettingsProvider*
  parent: System.Configuration.ISettingsProviderService
  isExternal: false
  name: GetSettingsProvider
  nameWithType: ISettingsProviderService.GetSettingsProvider
