### YamlMime:ManagedReference
items:
- uid: System.Web.Management.WebApplicationLifetimeEvent
  id: WebApplicationLifetimeEvent
  children:
  - System.Web.Management.WebApplicationLifetimeEvent.#ctor(System.String,System.Object,System.Int32)
  - System.Web.Management.WebApplicationLifetimeEvent.#ctor(System.String,System.Object,System.Int32,System.Int32)
  - System.Web.Management.WebApplicationLifetimeEvent.IncrementPerfCounters
  langs:
  - csharp
  name: WebApplicationLifetimeEvent
  nameWithType: WebApplicationLifetimeEvent
  fullName: System.Web.Management.WebApplicationLifetimeEvent
  type: Class
  summary: "Represents a significant event in the lifetime of an application."
  remarks: "ASP.NET health monitoring allows production and operations staff to manage deployed Web applications. The <xref:System.Web.Management> namespace contains the health-event types responsible for packaging application health-status data and the provider types responsible for processing this data. It also contains supporting types that help during the management of health events.       Application lifetime events include events such as application startup and shutdown events. If an application is terminated, you can determine why by viewing the related event message field.       When a WebApplicationLifetimeEvent instance occurs, ASP.NET health monitoring updates the Application Lifetime Events performance counter. You can log these events by adding the WebApplicationLifetimeEvent object to the `rules` subsection of the `healthMonitoring` section of the configuration file, as shown in the following example.      ```   <rules>     <add name=&quot;Application Events&quot;       eventName=&quot;Application Lifetime Events&quot;       provider=&quot;EventLogProvider&quot;       profile=&quot;Default&quot;       minInterval=&quot;00:01:00&quot; />   </rules>      ```       The Application Lifetime Events performance counter contains the sum total of all ASP.NET lifetime events. To view this performance counter in System Monitor (PerfMon), in the **Add Counters** window select **ASP.NET** from the **Performance object** drop-down list. Select the **Application Lifetime Events** performance counter, and click the **Add** button. For more information, see &quot;Using the System Monitor (PerfMon) with ASP.NET Applications&quot; on [MSDN](http://go.microsoft.com/fwlink/?linkid=37118). If you allow events to be logged by the standard <xref:System.Web.Management.EventLogWebEventProvider>, you can view them in Event Viewer by selecting the **Application** log. For more information, see [Event Viewer](http://go.microsoft.com/fwlink/?linkid=24845&clcid=0x409) in the Windows Server 2003 documentation on TechNet.      > [!CAUTION] >  Because the WebApplicationLifetimeEvent object is a high-volume event, logging it is resource-intensive and might slow down your system. It can also cause other events to be overwritten in the case of the <xref:System.Web.Management.EventLogWebEventProvider> class due to the high volume of events and the way the event logging works.      > [!NOTE] >  In most cases you will be able to use the ASP.NET health-monitoring types as implemented, and you will control the health-monitoring system by specifying values in the `healthMonitoring` configuration section. You can also derive from the health-monitoring types to create your own custom events and providers. For an example of deriving from the WebApplicationLifetimeEvent class, see the example provided in this topic."
  example:
  - "The following code example shows how to derive from the WebApplicationLifetimeEvent class to create a custom event.  \n  \n [!code-vb[System.Web.Management.WebApplicationLifetimeEvent#1](~/add/codesnippet/VisualBasic/t-system.web.management._24_1.vb)]\n [!code-cs[System.Web.Management.WebApplicationLifetimeEvent#1](~/add/codesnippet/CSharp/t-system.web.management._24_1.cs)]  \n  \n The following configuration-file excerpt shows how to configure the `healthMonitoring` section of a configuration file to add the `SampleWebApplicationLifetimeEvent` code defined above to the ASP.NET health-monitoring system. To add the event to the system, you must define the event by adding a new entry to the `eventMappings` section and map the event to a provider by adding a new entry to the `rules` section.  \n  \n```  \n<healthMonitoring  \n  enabled=\"true\"  \n  heartBeatInterval=\"0\">  \n  \n    <eventMappings>  \n       <clear />  \n       <!-- Configure the application lifetime event -->  \n       <!-- object to handle the Web application events. -->  \n       <add name=\"SampleApplicationLifetimeEvents\"  \n         type=\"System.Web.Management.SampleWebApplicationLifetimeEvent,  \n         System.Web,Version=2.0.3600.0,  \n         Culture=neutral,PublicKeyToken=b03f5f7f11d50a3a\" />  \n     </eventMappings>  \n  \n    <rules>  \n      <clear/>  \n       // Configure the connection between the   \n       // application lifetime event object   \n       // and the provider that must process it.  \n       <add name=\"Custom Application Events\"  \n         eventName=\"SampleApplicationLifetimeEvents\"  \n         provider=\"EventLogProvider\"  \n         profile=\"Default\"  \n         minInterval=\"00:01:00\" />  \n    </rules>  \n  \n</healthMonitoring>  \n```"
  syntax:
    content: 'public class WebApplicationLifetimeEvent : System.Web.Management.WebManagementEvent'
  inheritance:
  - System.Object
  - System.Web.Management.WebBaseEvent
  - System.Web.Management.WebManagementEvent
  implements: []
  inheritedMembers:
  - System.Web.Management.WebBaseEvent.ApplicationInformation
  - System.Web.Management.WebBaseEvent.EventCode
  - System.Web.Management.WebBaseEvent.EventDetailCode
  - System.Web.Management.WebBaseEvent.EventID
  - System.Web.Management.WebBaseEvent.EventOccurrence
  - System.Web.Management.WebBaseEvent.EventSequence
  - System.Web.Management.WebBaseEvent.EventSource
  - System.Web.Management.WebBaseEvent.EventTime
  - System.Web.Management.WebBaseEvent.EventTimeUtc
  - System.Web.Management.WebBaseEvent.FormatCustomEventDetails(System.Web.Management.WebEventFormatter)
  - System.Web.Management.WebBaseEvent.Message
  - System.Web.Management.WebBaseEvent.Raise
  - System.Web.Management.WebBaseEvent.Raise(System.Web.Management.WebBaseEvent)
  - System.Web.Management.WebBaseEvent.ToString
  - System.Web.Management.WebBaseEvent.ToString(System.Boolean,System.Boolean)
  - System.Web.Management.WebManagementEvent.ProcessInformation
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Management.WebApplicationLifetimeEvent.#ctor(System.String,System.Object,System.Int32)
  id: '#ctor(System.String,System.Object,System.Int32)'
  parent: System.Web.Management.WebApplicationLifetimeEvent
  langs:
  - csharp
  name: WebApplicationLifetimeEvent(String,Object,Int32)
  nameWithType: WebApplicationLifetimeEvent.WebApplicationLifetimeEvent(String,Object,Int32)
  fullName: System.Web.Management.WebApplicationLifetimeEvent.WebApplicationLifetimeEvent(String,Object,Int32)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Management
  summary: "Initializes the <see cref=&quot;T:System.Web.Management.WebApplicationLifetimeEvent&quot;></see> class using the supplied parameters."
  remarks: "This constructor is used internally by the ASP.NET health-monitoring system. You will never use it to create an instance of the <xref:System.Web.Management.WebApplicationLifetimeEvent> class, but you can call this constructor when implementing your own event type that inherits from this class.      > [!NOTE] >  The WebApplicationLifetimeEvent constructor is not intended to be used directly from your code. It is called by ASP.NET. You can call the WebApplicationLifetimeEvent constructor when deriving from the <xref:System.Web.Management.WebApplicationLifetimeEvent> class."
  example:
  - "The following code example shows how to use the WebApplicationLifetimeEvent in an ASP.NET custom health event. This code example is mainly intended to show the correct syntax to use.  \n  \n [!code-vb[System.Web.Management.WebApplicationLifetimeEvent#2](~/add/codesnippet/VisualBasic/f6897152-ffc5-4ce1-a4ea-_1.vb)]\n [!code-cs[System.Web.Management.WebApplicationLifetimeEvent#2](~/add/codesnippet/CSharp/f6897152-ffc5-4ce1-a4ea-_1.cs)]"
  syntax:
    content: protected WebApplicationLifetimeEvent (string message, object eventSource, int eventCode);
    parameters:
    - id: message
      type: System.String
      description: "The message associated with the event."
    - id: eventSource
      type: System.Object
      description: "The object that is the source of the event."
    - id: eventCode
      type: System.Int32
      description: "The code associated with the event. When you implement a custom event, the event code must be greater than ."
  overload: System.Web.Management.WebApplicationLifetimeEvent.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Management.WebApplicationLifetimeEvent.#ctor(System.String,System.Object,System.Int32,System.Int32)
  id: '#ctor(System.String,System.Object,System.Int32,System.Int32)'
  parent: System.Web.Management.WebApplicationLifetimeEvent
  langs:
  - csharp
  name: WebApplicationLifetimeEvent(String,Object,Int32,Int32)
  nameWithType: WebApplicationLifetimeEvent.WebApplicationLifetimeEvent(String,Object,Int32,Int32)
  fullName: System.Web.Management.WebApplicationLifetimeEvent.WebApplicationLifetimeEvent(String,Object,Int32,Int32)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Management
  summary: "Initializes the <see cref=&quot;T:System.Web.Management.WebApplicationLifetimeEvent&quot;></see> class using the supplied parameters."
  remarks: "This constructor is used internally by the ASP.NET health-monitoring system. You will never use it to create an instance of the <xref:System.Web.Management.WebApplicationLifetimeEvent> class, but you can call this constructor when implementing your own event type that inherits from this class.      > [!NOTE] >  The WebApplicationLifetimeEvent constructor is not intended to be used directly from your code. It is called by ASP.NET. You can call the WebApplicationLifetimeEvent constructor when deriving from the <xref:System.Web.Management.WebApplicationLifetimeEvent> class."
  example:
  - "The following code example shows how to use the WebApplicationLifetimeEvent in an ASP.NET custom health event. This code example is mainly intended to show the correct syntax to use.  \n  \n [!code-vb[System.Web.Management.WebApplicationLifetimeEvent#3](~/add/codesnippet/VisualBasic/d658829b-c5f1-4bb1-9080-_1.vb)]\n [!code-cs[System.Web.Management.WebApplicationLifetimeEvent#3](~/add/codesnippet/CSharp/d658829b-c5f1-4bb1-9080-_1.cs)]"
  syntax:
    content: protected WebApplicationLifetimeEvent (string message, object eventSource, int eventCode, int eventDetailCode);
    parameters:
    - id: message
      type: System.String
      description: "The message associated with the event."
    - id: eventSource
      type: System.Object
      description: "The object that is the source of the event."
    - id: eventCode
      type: System.Int32
      description: "The code associated with the event. When you implement a custom event, the event code must be greater than ."
    - id: eventDetailCode
      type: System.Int32
      description: "The  value that specifies the detailed identifier for the event."
  overload: System.Web.Management.WebApplicationLifetimeEvent.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Management.WebApplicationLifetimeEvent.IncrementPerfCounters
  id: IncrementPerfCounters
  parent: System.Web.Management.WebApplicationLifetimeEvent
  langs:
  - csharp
  name: IncrementPerfCounters()
  nameWithType: WebApplicationLifetimeEvent.IncrementPerfCounters()
  fullName: System.Web.Management.WebApplicationLifetimeEvent.IncrementPerfCounters()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Management
  summary: "Used internally to increment performance counters."
  syntax:
    content: protected override void IncrementPerfCounters ();
    parameters: []
  overload: System.Web.Management.WebApplicationLifetimeEvent.IncrementPerfCounters*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Web.Management.WebManagementEvent
  isExternal: false
  name: System.Web.Management.WebManagementEvent
- uid: System.Web.Management.WebApplicationLifetimeEvent.#ctor(System.String,System.Object,System.Int32)
  parent: System.Web.Management.WebApplicationLifetimeEvent
  isExternal: false
  name: WebApplicationLifetimeEvent(String,Object,Int32)
  nameWithType: WebApplicationLifetimeEvent.WebApplicationLifetimeEvent(String,Object,Int32)
  fullName: System.Web.Management.WebApplicationLifetimeEvent.WebApplicationLifetimeEvent(String,Object,Int32)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Management.WebApplicationLifetimeEvent.#ctor(System.String,System.Object,System.Int32,System.Int32)
  parent: System.Web.Management.WebApplicationLifetimeEvent
  isExternal: false
  name: WebApplicationLifetimeEvent(String,Object,Int32,Int32)
  nameWithType: WebApplicationLifetimeEvent.WebApplicationLifetimeEvent(String,Object,Int32,Int32)
  fullName: System.Web.Management.WebApplicationLifetimeEvent.WebApplicationLifetimeEvent(String,Object,Int32,Int32)
- uid: System.Web.Management.WebApplicationLifetimeEvent.IncrementPerfCounters
  parent: System.Web.Management.WebApplicationLifetimeEvent
  isExternal: false
  name: IncrementPerfCounters()
  nameWithType: WebApplicationLifetimeEvent.IncrementPerfCounters()
  fullName: System.Web.Management.WebApplicationLifetimeEvent.IncrementPerfCounters()
- uid: System.Web.Management.WebApplicationLifetimeEvent.#ctor*
  parent: System.Web.Management.WebApplicationLifetimeEvent
  isExternal: false
  name: WebApplicationLifetimeEvent
  nameWithType: WebApplicationLifetimeEvent.WebApplicationLifetimeEvent
- uid: System.Web.Management.WebApplicationLifetimeEvent.IncrementPerfCounters*
  parent: System.Web.Management.WebApplicationLifetimeEvent
  isExternal: false
  name: IncrementPerfCounters
  nameWithType: WebApplicationLifetimeEvent.IncrementPerfCounters
