### YamlMime:ManagedReference
items:
- uid: System.Web.Hosting.IApplicationPreloadUtil
  id: IApplicationPreloadUtil
  children:
  - System.Web.Hosting.IApplicationPreloadUtil.GetApplicationPreloadInfo(System.String,System.Boolean@,System.String@,System.String[]@)
  - System.Web.Hosting.IApplicationPreloadUtil.ReportApplicationPreloadFailure(System.String,System.Int32,System.String)
  langs:
  - csharp
  name: IApplicationPreloadUtil
  nameWithType: IApplicationPreloadUtil
  fullName: System.Web.Hosting.IApplicationPreloadUtil
  type: Interface
  summary: "Provides methods that ASP.NET uses to communicate with [!INCLUDE[iisver](~/add/includes/iisver-md.md)] while the server preloads an application."
  syntax:
    content: >-
      [System.Runtime.InteropServices.Guid("940D8ADD-9E40-4475-9A67-2CDCDF57995C")]

      [System.Runtime.InteropServices.InterfaceType(System.Runtime.InteropServices.ComInterfaceType.InterfaceIsIUnknown)]

      public interface IApplicationPreloadUtil
  implements: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Hosting.IApplicationPreloadUtil.GetApplicationPreloadInfo(System.String,System.Boolean@,System.String@,System.String[]@)
  id: GetApplicationPreloadInfo(System.String,System.Boolean@,System.String@,System.String[]@)
  parent: System.Web.Hosting.IApplicationPreloadUtil
  langs:
  - csharp
  name: GetApplicationPreloadInfo(String,Boolean,String,String[])
  nameWithType: IApplicationPreloadUtil.GetApplicationPreloadInfo(String,Boolean,String,String[])
  fullName: System.Web.Hosting.IApplicationPreloadUtil.GetApplicationPreloadInfo(String,Boolean,String,String[])
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Gets initialization data that is required in order to preload an application. This method is called by ASP.NET."
  syntax:
    content: public void GetApplicationPreloadInfo (string context, out bool enabled, out string startupObjType, out string[] parametersForStartupObj);
    parameters:
    - id: context
      type: System.String
      description: "The application context."
    - id: enabled
      type: System.Boolean
      description: "When this method returns, contains  to indicate that the application has to be preloaded; otherwise, . This parameter is passed uninitialized."
    - id: startupObjType
      type: System.String
      description: "When this method returns, contains a string that identifies the managed type that is part of the preload process. This parameter is passed uninitialized."
    - id: parametersForStartupObj
      type: System.String[]
      description: "When this method returns, contains the data that will be passed to the preloaded type. This parameter is passed uninitialized."
  overload: System.Web.Hosting.IApplicationPreloadUtil.GetApplicationPreloadInfo*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Hosting.IApplicationPreloadUtil.ReportApplicationPreloadFailure(System.String,System.Int32,System.String)
  id: ReportApplicationPreloadFailure(System.String,System.Int32,System.String)
  parent: System.Web.Hosting.IApplicationPreloadUtil
  langs:
  - csharp
  name: ReportApplicationPreloadFailure(String,Int32,String)
  nameWithType: IApplicationPreloadUtil.ReportApplicationPreloadFailure(String,Int32,String)
  fullName: System.Web.Hosting.IApplicationPreloadUtil.ReportApplicationPreloadFailure(String,Int32,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Reports that an error occurred in [!INCLUDE[iisver](~/add/includes/iisver-md.md)] while the server was preloading the ASP.NET application."
  syntax:
    content: public void ReportApplicationPreloadFailure (string context, int errorCode, string errorMessage);
    parameters:
    - id: context
      type: System.String
      description: "The application context."
    - id: errorCode
      type: System.Int32
      description: "The numeric error code."
    - id: errorMessage
      type: System.String
      description: "The error text."
  overload: System.Web.Hosting.IApplicationPreloadUtil.ReportApplicationPreloadFailure*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Web.Hosting.IApplicationPreloadUtil.GetApplicationPreloadInfo(System.String,System.Boolean@,System.String@,System.String[]@)
  parent: System.Web.Hosting.IApplicationPreloadUtil
  isExternal: false
  name: GetApplicationPreloadInfo(String,Boolean,String,String[])
  nameWithType: IApplicationPreloadUtil.GetApplicationPreloadInfo(String,Boolean,String,String[])
  fullName: System.Web.Hosting.IApplicationPreloadUtil.GetApplicationPreloadInfo(String,Boolean,String,String[])
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String[]
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String[]
  spec.csharp:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Web.Hosting.IApplicationPreloadUtil.ReportApplicationPreloadFailure(System.String,System.Int32,System.String)
  parent: System.Web.Hosting.IApplicationPreloadUtil
  isExternal: false
  name: ReportApplicationPreloadFailure(String,Int32,String)
  nameWithType: IApplicationPreloadUtil.ReportApplicationPreloadFailure(String,Int32,String)
  fullName: System.Web.Hosting.IApplicationPreloadUtil.ReportApplicationPreloadFailure(String,Int32,String)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Hosting.IApplicationPreloadUtil.GetApplicationPreloadInfo*
  parent: System.Web.Hosting.IApplicationPreloadUtil
  isExternal: false
  name: GetApplicationPreloadInfo
  nameWithType: IApplicationPreloadUtil.GetApplicationPreloadInfo
- uid: System.Web.Hosting.IApplicationPreloadUtil.ReportApplicationPreloadFailure*
  parent: System.Web.Hosting.IApplicationPreloadUtil
  isExternal: false
  name: ReportApplicationPreloadFailure
  nameWithType: IApplicationPreloadUtil.ReportApplicationPreloadFailure
