### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsManageabilityAttribute
  id: SettingsManageabilityAttribute
  children:
  - System.Configuration.SettingsManageabilityAttribute.#ctor(System.Configuration.SettingsManageability)
  - System.Configuration.SettingsManageabilityAttribute.Manageability
  langs:
  - csharp
  name: SettingsManageabilityAttribute
  nameWithType: SettingsManageabilityAttribute
  fullName: System.Configuration.SettingsManageabilityAttribute
  type: Class
  summary: "Specifies special services for application settings properties. This class cannot be inherited."
  remarks: "The SettingsManageabilityAttribute indicates that special, predefined services are to be provided to individual application settings properties and property groups. Most of these services will be provided by the Windows operating system.       For more information about application settings properties and their use, see [Application Settings for Windows Forms](../Topic/Application%20Settings%20for%20Windows%20Forms.md)."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Property)]

      public sealed class SettingsManageabilityAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SettingsManageabilityAttribute.#ctor(System.Configuration.SettingsManageability)
  id: '#ctor(System.Configuration.SettingsManageability)'
  parent: System.Configuration.SettingsManageabilityAttribute
  langs:
  - csharp
  name: SettingsManageabilityAttribute(SettingsManageability)
  nameWithType: SettingsManageabilityAttribute.SettingsManageabilityAttribute(SettingsManageability)
  fullName: System.Configuration.SettingsManageabilityAttribute.SettingsManageabilityAttribute(SettingsManageability)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.SettingsManageabilityAttribute&quot;></see> class."
  remarks: "Multiple services can be requested by combining together values defined by the <xref:System.Configuration.SettingsManageability> enumeration with the logical `OR` operator."
  syntax:
    content: public SettingsManageabilityAttribute (System.Configuration.SettingsManageability manageability);
    parameters:
    - id: manageability
      type: System.Configuration.SettingsManageability
      description: "A  value that enumerates the services being requested."
  overload: System.Configuration.SettingsManageabilityAttribute.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SettingsManageabilityAttribute.Manageability
  id: Manageability
  parent: System.Configuration.SettingsManageabilityAttribute
  langs:
  - csharp
  name: Manageability
  nameWithType: SettingsManageabilityAttribute.Manageability
  fullName: System.Configuration.SettingsManageabilityAttribute.Manageability
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Gets the set of special services that have been requested."
  remarks: "This property is set in the <xref:System.Configuration.SettingsManageabilityAttribute.%23ctor%2A> constructor."
  syntax:
    content: public System.Configuration.SettingsManageability Manageability { get; }
    return:
      type: System.Configuration.SettingsManageability
      description: "A value that results from using the logical <xref uid=&quot;langword_csharp_OR&quot; name=&quot;OR&quot; href=&quot;&quot;></xref> operator to combine all the <see cref=&quot;T:System.Configuration.SettingsManageability&quot;></see> enumeration values corresponding to the requested services."
  overload: System.Configuration.SettingsManageabilityAttribute.Manageability*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsManageabilityAttribute.#ctor(System.Configuration.SettingsManageability)
  parent: System.Configuration.SettingsManageabilityAttribute
  isExternal: false
  name: SettingsManageabilityAttribute(SettingsManageability)
  nameWithType: SettingsManageabilityAttribute.SettingsManageabilityAttribute(SettingsManageability)
  fullName: System.Configuration.SettingsManageabilityAttribute.SettingsManageabilityAttribute(SettingsManageability)
- uid: System.Configuration.SettingsManageability
  parent: System.Configuration
  isExternal: false
  name: SettingsManageability
  nameWithType: SettingsManageability
  fullName: System.Configuration.SettingsManageability
- uid: System.Configuration.SettingsManageabilityAttribute.Manageability
  parent: System.Configuration.SettingsManageabilityAttribute
  isExternal: false
  name: Manageability
  nameWithType: SettingsManageabilityAttribute.Manageability
  fullName: System.Configuration.SettingsManageabilityAttribute.Manageability
- uid: System.Configuration.SettingsManageabilityAttribute.#ctor*
  parent: System.Configuration.SettingsManageabilityAttribute
  isExternal: false
  name: SettingsManageabilityAttribute
  nameWithType: SettingsManageabilityAttribute.SettingsManageabilityAttribute
- uid: System.Configuration.SettingsManageabilityAttribute.Manageability*
  parent: System.Configuration.SettingsManageabilityAttribute
  isExternal: false
  name: Manageability
  nameWithType: SettingsManageabilityAttribute.Manageability
