### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.AsyncPreloadModeFlags
  id: AsyncPreloadModeFlags
  children:
  - System.Web.Configuration.AsyncPreloadModeFlags.All
  - System.Web.Configuration.AsyncPreloadModeFlags.AllFormTypes
  - System.Web.Configuration.AsyncPreloadModeFlags.Form
  - System.Web.Configuration.AsyncPreloadModeFlags.FormMultiPart
  - System.Web.Configuration.AsyncPreloadModeFlags.None
  - System.Web.Configuration.AsyncPreloadModeFlags.NonForm
  langs:
  - csharp
  name: AsyncPreloadModeFlags
  nameWithType: AsyncPreloadModeFlags
  fullName: System.Web.Configuration.AsyncPreloadModeFlags
  type: Enum
  summary: "Specifies the mode for asynchronous requests."
  syntax:
    content: >-
      [System.Flags]

      public enum AsyncPreloadModeFlags
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.AsyncPreloadModeFlags.All
  id: All
  parent: System.Web.Configuration.AsyncPreloadModeFlags
  langs:
  - csharp
  name: All
  nameWithType: AsyncPreloadModeFlags.All
  fullName: System.Web.Configuration.AsyncPreloadModeFlags.All
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Asynchronous uploads of the request entity body will occur for all posts."
  syntax:
    content: All
    return:
      type: System.Web.Configuration.AsyncPreloadModeFlags
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.AsyncPreloadModeFlags.AllFormTypes
  id: AllFormTypes
  parent: System.Web.Configuration.AsyncPreloadModeFlags
  langs:
  - csharp
  name: AllFormTypes
  nameWithType: AsyncPreloadModeFlags.AllFormTypes
  fullName: System.Web.Configuration.AsyncPreloadModeFlags.AllFormTypes
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Asynchronous uploads of the request entity body will occur only for form posts."
  syntax:
    content: AllFormTypes
    return:
      type: System.Web.Configuration.AsyncPreloadModeFlags
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.AsyncPreloadModeFlags.Form
  id: Form
  parent: System.Web.Configuration.AsyncPreloadModeFlags
  langs:
  - csharp
  name: Form
  nameWithType: AsyncPreloadModeFlags.Form
  fullName: System.Web.Configuration.AsyncPreloadModeFlags.Form
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Asynchronous uploads of the request entity body will occur only for form posts. This flag enables asynchronous preloading for MIME types that are specifically set to `application/x-www-form-urlencoded`."
  syntax:
    content: Form
    return:
      type: System.Web.Configuration.AsyncPreloadModeFlags
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.AsyncPreloadModeFlags.FormMultiPart
  id: FormMultiPart
  parent: System.Web.Configuration.AsyncPreloadModeFlags
  langs:
  - csharp
  name: FormMultiPart
  nameWithType: AsyncPreloadModeFlags.FormMultiPart
  fullName: System.Web.Configuration.AsyncPreloadModeFlags.FormMultiPart
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Asynchronous uploads of the request entity body will occur only for multi-part form data. This flag enables asynchronous preloading for MIME types that are specifically set to `multipart/form-data`."
  syntax:
    content: FormMultiPart
    return:
      type: System.Web.Configuration.AsyncPreloadModeFlags
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.AsyncPreloadModeFlags.None
  id: None
  parent: System.Web.Configuration.AsyncPreloadModeFlags
  langs:
  - csharp
  name: None
  nameWithType: AsyncPreloadModeFlags.None
  fullName: System.Web.Configuration.AsyncPreloadModeFlags.None
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "No asynchronous upload of the request entity body will occur."
  syntax:
    content: None
    return:
      type: System.Web.Configuration.AsyncPreloadModeFlags
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.AsyncPreloadModeFlags.NonForm
  id: NonForm
  parent: System.Web.Configuration.AsyncPreloadModeFlags
  langs:
  - csharp
  name: NonForm
  nameWithType: AsyncPreloadModeFlags.NonForm
  fullName: System.Web.Configuration.AsyncPreloadModeFlags.NonForm
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Asynchronous uploads of the request entity body will occur only for non-form posts."
  syntax:
    content: NonForm
    return:
      type: System.Web.Configuration.AsyncPreloadModeFlags
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.AsyncPreloadModeFlags.All
  parent: System.Web.Configuration.AsyncPreloadModeFlags
  isExternal: false
  name: All
  nameWithType: AsyncPreloadModeFlags.All
  fullName: System.Web.Configuration.AsyncPreloadModeFlags.All
- uid: System.Web.Configuration.AsyncPreloadModeFlags
  parent: System.Web.Configuration
  isExternal: false
  name: AsyncPreloadModeFlags
  nameWithType: AsyncPreloadModeFlags
  fullName: System.Web.Configuration.AsyncPreloadModeFlags
- uid: System.Web.Configuration.AsyncPreloadModeFlags.AllFormTypes
  parent: System.Web.Configuration.AsyncPreloadModeFlags
  isExternal: false
  name: AllFormTypes
  nameWithType: AsyncPreloadModeFlags.AllFormTypes
  fullName: System.Web.Configuration.AsyncPreloadModeFlags.AllFormTypes
- uid: System.Web.Configuration.AsyncPreloadModeFlags.Form
  parent: System.Web.Configuration.AsyncPreloadModeFlags
  isExternal: false
  name: Form
  nameWithType: AsyncPreloadModeFlags.Form
  fullName: System.Web.Configuration.AsyncPreloadModeFlags.Form
- uid: System.Web.Configuration.AsyncPreloadModeFlags.FormMultiPart
  parent: System.Web.Configuration.AsyncPreloadModeFlags
  isExternal: false
  name: FormMultiPart
  nameWithType: AsyncPreloadModeFlags.FormMultiPart
  fullName: System.Web.Configuration.AsyncPreloadModeFlags.FormMultiPart
- uid: System.Web.Configuration.AsyncPreloadModeFlags.None
  parent: System.Web.Configuration.AsyncPreloadModeFlags
  isExternal: false
  name: None
  nameWithType: AsyncPreloadModeFlags.None
  fullName: System.Web.Configuration.AsyncPreloadModeFlags.None
- uid: System.Web.Configuration.AsyncPreloadModeFlags.NonForm
  parent: System.Web.Configuration.AsyncPreloadModeFlags
  isExternal: false
  name: NonForm
  nameWithType: AsyncPreloadModeFlags.NonForm
  fullName: System.Web.Configuration.AsyncPreloadModeFlags.NonForm
