### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ClientSection
  id: ClientSection
  children:
  - System.ServiceModel.Configuration.ClientSection.#ctor
  - System.ServiceModel.Configuration.ClientSection.Endpoints
  - System.ServiceModel.Configuration.ClientSection.InitializeDefault
  - System.ServiceModel.Configuration.ClientSection.Metadata
  - System.ServiceModel.Configuration.ClientSection.PostDeserialize
  - System.ServiceModel.Configuration.ClientSection.Properties
  langs:
  - csharp
  name: ClientSection
  nameWithType: ClientSection
  fullName: System.ServiceModel.Configuration.ClientSection
  type: Class
  summary: "Represents the client section of a configuration file, which defines a list of endpoints that a client can connect to. This class cannot be inherited."
  syntax:
    content: 'public sealed class ClientSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ClientSection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ClientSection
  langs:
  - csharp
  name: ClientSection()
  nameWithType: ClientSection.ClientSection()
  fullName: System.ServiceModel.Configuration.ClientSection.ClientSection()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.ClientSection&quot;></see> class."
  syntax:
    content: public ClientSection ();
    parameters: []
  overload: System.ServiceModel.Configuration.ClientSection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ClientSection.Endpoints
  id: Endpoints
  parent: System.ServiceModel.Configuration.ClientSection
  langs:
  - csharp
  name: Endpoints
  nameWithType: ClientSection.Endpoints
  fullName: System.ServiceModel.Configuration.ClientSection.Endpoints
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets a list of endpoints that a client can connect to."
  syntax:
    content: public System.ServiceModel.Configuration.ChannelEndpointElementCollection Endpoints { get; }
    return:
      type: System.ServiceModel.Configuration.ChannelEndpointElementCollection
      description: "A <see cref=&quot;T:System.ServiceModel.Configuration.ChannelEndpointElementCollection&quot;></see> that contains a list of endpoints that a client can connect to."
  overload: System.ServiceModel.Configuration.ClientSection.Endpoints*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ClientSection.InitializeDefault
  id: InitializeDefault
  parent: System.ServiceModel.Configuration.ClientSection
  langs:
  - csharp
  name: InitializeDefault()
  nameWithType: ClientSection.InitializeDefault()
  fullName: System.ServiceModel.Configuration.ClientSection.InitializeDefault()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override void InitializeDefault ();
    parameters: []
  overload: System.ServiceModel.Configuration.ClientSection.InitializeDefault*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ClientSection.Metadata
  id: Metadata
  parent: System.ServiceModel.Configuration.ClientSection
  langs:
  - csharp
  name: Metadata
  nameWithType: ClientSection.Metadata
  fullName: System.ServiceModel.Configuration.ClientSection.Metadata
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets the configuration settings for processing metadata."
  syntax:
    content: public System.ServiceModel.Configuration.MetadataElement Metadata { get; }
    return:
      type: System.ServiceModel.Configuration.MetadataElement
      description: "A <see cref=&quot;T:System.ServiceModel.Configuration.MetadataElement&quot;></see>that represents the configuration settings for processing metadata."
  overload: System.ServiceModel.Configuration.ClientSection.Metadata*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ClientSection.PostDeserialize
  id: PostDeserialize
  parent: System.ServiceModel.Configuration.ClientSection
  langs:
  - csharp
  name: PostDeserialize()
  nameWithType: ClientSection.PostDeserialize()
  fullName: System.ServiceModel.Configuration.ClientSection.PostDeserialize()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override void PostDeserialize ();
    parameters: []
  overload: System.ServiceModel.Configuration.ClientSection.PostDeserialize*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ClientSection.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ClientSection
  langs:
  - csharp
  name: Properties
  nameWithType: ClientSection.Properties
  fullName: System.ServiceModel.Configuration.ClientSection.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.ClientSection.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.ServiceModel.Configuration.ClientSection.#ctor
  parent: System.ServiceModel.Configuration.ClientSection
  isExternal: false
  name: ClientSection()
  nameWithType: ClientSection.ClientSection()
  fullName: System.ServiceModel.Configuration.ClientSection.ClientSection()
- uid: System.ServiceModel.Configuration.ClientSection.Endpoints
  parent: System.ServiceModel.Configuration.ClientSection
  isExternal: false
  name: Endpoints
  nameWithType: ClientSection.Endpoints
  fullName: System.ServiceModel.Configuration.ClientSection.Endpoints
- uid: System.ServiceModel.Configuration.ChannelEndpointElementCollection
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ChannelEndpointElementCollection
  nameWithType: ChannelEndpointElementCollection
  fullName: System.ServiceModel.Configuration.ChannelEndpointElementCollection
- uid: System.ServiceModel.Configuration.ClientSection.InitializeDefault
  parent: System.ServiceModel.Configuration.ClientSection
  isExternal: false
  name: InitializeDefault()
  nameWithType: ClientSection.InitializeDefault()
  fullName: System.ServiceModel.Configuration.ClientSection.InitializeDefault()
- uid: System.ServiceModel.Configuration.ClientSection.Metadata
  parent: System.ServiceModel.Configuration.ClientSection
  isExternal: false
  name: Metadata
  nameWithType: ClientSection.Metadata
  fullName: System.ServiceModel.Configuration.ClientSection.Metadata
- uid: System.ServiceModel.Configuration.MetadataElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: MetadataElement
  nameWithType: MetadataElement
  fullName: System.ServiceModel.Configuration.MetadataElement
- uid: System.ServiceModel.Configuration.ClientSection.PostDeserialize
  parent: System.ServiceModel.Configuration.ClientSection
  isExternal: false
  name: PostDeserialize()
  nameWithType: ClientSection.PostDeserialize()
  fullName: System.ServiceModel.Configuration.ClientSection.PostDeserialize()
- uid: System.ServiceModel.Configuration.ClientSection.Properties
  parent: System.ServiceModel.Configuration.ClientSection
  isExternal: false
  name: Properties
  nameWithType: ClientSection.Properties
  fullName: System.ServiceModel.Configuration.ClientSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ClientSection.#ctor*
  parent: System.ServiceModel.Configuration.ClientSection
  isExternal: false
  name: ClientSection
  nameWithType: ClientSection.ClientSection
- uid: System.ServiceModel.Configuration.ClientSection.Endpoints*
  parent: System.ServiceModel.Configuration.ClientSection
  isExternal: false
  name: Endpoints
  nameWithType: ClientSection.Endpoints
- uid: System.ServiceModel.Configuration.ClientSection.InitializeDefault*
  parent: System.ServiceModel.Configuration.ClientSection
  isExternal: false
  name: InitializeDefault
  nameWithType: ClientSection.InitializeDefault
- uid: System.ServiceModel.Configuration.ClientSection.Metadata*
  parent: System.ServiceModel.Configuration.ClientSection
  isExternal: false
  name: Metadata
  nameWithType: ClientSection.Metadata
- uid: System.ServiceModel.Configuration.ClientSection.PostDeserialize*
  parent: System.ServiceModel.Configuration.ClientSection
  isExternal: false
  name: PostDeserialize
  nameWithType: ClientSection.PostDeserialize
- uid: System.ServiceModel.Configuration.ClientSection.Properties*
  parent: System.ServiceModel.Configuration.ClientSection
  isExternal: false
  name: Properties
  nameWithType: ClientSection.Properties
