### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  id: SystemIdentityModelServicesSection
  children:
  - System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.#ctor
  - System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.Current
  - System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.DefaultFederationConfigurationElement
  - System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.FederationConfigurationElements
  - System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.SectionName
  langs:
  - csharp
  name: SystemIdentityModelServicesSection
  nameWithType: SystemIdentityModelServicesSection
  fullName: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  type: Class
  summary: "Represents the <xref uid=&quot;langword_csharp_&lt;system.identityModel.services&gt;&quot; name=&quot;&lt;system.identityModel.services&gt;&quot; href=&quot;&quot;></xref> section in a configuration file. This class cannot be inherited."
  remarks: "The `<system.identityModel.services>` section configures authentication using WS-Federation protocol. It contains elements that configure the <xref:System.IdentityModel.Services.WSFederationAuthenticationModule> (WSFAM) and the <xref:System.IdentityModel.Services.SessionAuthenticationModule> (SAM)."
  syntax:
    content: 'public sealed class SystemIdentityModelServicesSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  langs:
  - csharp
  name: SystemIdentityModelServicesSection()
  nameWithType: SystemIdentityModelServicesSection.SystemIdentityModelServicesSection()
  fullName: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.SystemIdentityModelServicesSection()
  type: Constructor
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection&quot;></see> class."
  syntax:
    content: public SystemIdentityModelServicesSection ();
    parameters: []
  overload: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.Current
  id: Current
  parent: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  langs:
  - csharp
  name: Current
  nameWithType: SystemIdentityModelServicesSection.Current
  fullName: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.Current
  type: Property
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services.Configuration
  summary: "Gets a reference to the <xref uid=&quot;langword_csharp_&lt;system.identityModel.services&gt;&quot; name=&quot;&lt;system.identityModel.services&gt;&quot; href=&quot;&quot;></xref> section from the configuration file."
  syntax:
    content: public static System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection Current { get; }
    return:
      type: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
      description: "The <xref uid=&quot;langword_csharp_&lt;system.identityModel.services&gt;&quot; name=&quot;&lt;system.identityModel.services&gt;&quot; href=&quot;&quot;></xref> section from the configuration file. <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref> if the configuration file does not contain a <xref uid=&quot;langword_csharp_&lt;system.identityModel.services&gt;&quot; name=&quot;&lt;system.identityModel.services&gt;&quot; href=&quot;&quot;></xref> section."
  overload: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.Current*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.DefaultFederationConfigurationElement
  id: DefaultFederationConfigurationElement
  parent: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  langs:
  - csharp
  name: DefaultFederationConfigurationElement
  nameWithType: SystemIdentityModelServicesSection.DefaultFederationConfigurationElement
  fullName: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.DefaultFederationConfigurationElement
  type: Property
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services.Configuration
  summary: "Gets the unnamed <xref uid=&quot;langword_csharp_&lt;federationConfiguration&gt;&quot; name=&quot;&lt;federationConfiguration&gt;&quot; href=&quot;&quot;></xref> element from the configuration file."
  remarks: "The unnamed `<federationConfiguration>` element does not have its `name` attribute set (<xref:System.IdentityModel.Services.Configuration.FederationConfigurationElement.Name%2A?displayProperty=fullName> property is `null`)."
  syntax:
    content: public static System.IdentityModel.Services.Configuration.FederationConfigurationElement DefaultFederationConfigurationElement { get; }
    return:
      type: System.IdentityModel.Services.Configuration.FederationConfigurationElement
      description: "The unnamed <xref uid=&quot;langword_csharp_&lt;federationConfiguration&gt;&quot; name=&quot;&lt;federationConfiguration&gt;&quot; href=&quot;&quot;></xref> element from the configuration file. <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref> if the configuration file does not contain a <xref uid=&quot;langword_csharp_&lt;system.identityModel.services&gt;&quot; name=&quot;&lt;system.identityModel.services&gt;&quot; href=&quot;&quot;></xref> section."
  overload: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.DefaultFederationConfigurationElement*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.FederationConfigurationElements
  id: FederationConfigurationElements
  parent: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  langs:
  - csharp
  name: FederationConfigurationElements
  nameWithType: SystemIdentityModelServicesSection.FederationConfigurationElements
  fullName: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.FederationConfigurationElements
  type: Property
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services.Configuration
  summary: "Gets the collection of <xref uid=&quot;langword_csharp_&lt;federationConfiguration&gt;&quot; name=&quot;&lt;federationConfiguration&gt;&quot; href=&quot;&quot;></xref> elements configured in this <xref uid=&quot;langword_csharp_&lt;system.identityModel.services&gt;&quot; name=&quot;&lt;system.identityModel.services&gt;&quot; href=&quot;&quot;></xref> section."
  syntax:
    content: public System.IdentityModel.Services.Configuration.FederationConfigurationElementCollection FederationConfigurationElements { get; }
    return:
      type: System.IdentityModel.Services.Configuration.FederationConfigurationElementCollection
      description: "A collection that contains all of the <xref uid=&quot;langword_csharp_&lt;federationConfiguration&gt;&quot; name=&quot;&lt;federationConfiguration&gt;&quot; href=&quot;&quot;></xref> elements configured in this <xref uid=&quot;langword_csharp_&lt;system.identityModel.services&gt;&quot; name=&quot;&lt;system.identityModel.services&gt;&quot; href=&quot;&quot;></xref> section."
  overload: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.FederationConfigurationElements*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.SectionName
  id: SectionName
  parent: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  langs:
  - csharp
  name: SectionName
  nameWithType: SystemIdentityModelServicesSection.SectionName
  fullName: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.SectionName
  type: Field
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services.Configuration
  summary: "A constant that defines the name of the configuration section; “system.identityModel.services”."
  syntax:
    content: public const string SectionName;
    return:
      type: System.String
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.#ctor
  parent: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  isExternal: false
  name: SystemIdentityModelServicesSection()
  nameWithType: SystemIdentityModelServicesSection.SystemIdentityModelServicesSection()
  fullName: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.SystemIdentityModelServicesSection()
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.Current
  parent: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  isExternal: false
  name: Current
  nameWithType: SystemIdentityModelServicesSection.Current
  fullName: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.Current
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  parent: System.IdentityModel.Services.Configuration
  isExternal: false
  name: SystemIdentityModelServicesSection
  nameWithType: SystemIdentityModelServicesSection
  fullName: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.DefaultFederationConfigurationElement
  parent: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  isExternal: false
  name: DefaultFederationConfigurationElement
  nameWithType: SystemIdentityModelServicesSection.DefaultFederationConfigurationElement
  fullName: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.DefaultFederationConfigurationElement
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationElement
  parent: System.IdentityModel.Services.Configuration
  isExternal: false
  name: FederationConfigurationElement
  nameWithType: FederationConfigurationElement
  fullName: System.IdentityModel.Services.Configuration.FederationConfigurationElement
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.FederationConfigurationElements
  parent: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  isExternal: false
  name: FederationConfigurationElements
  nameWithType: SystemIdentityModelServicesSection.FederationConfigurationElements
  fullName: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.FederationConfigurationElements
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationElementCollection
  parent: System.IdentityModel.Services.Configuration
  isExternal: false
  name: FederationConfigurationElementCollection
  nameWithType: FederationConfigurationElementCollection
  fullName: System.IdentityModel.Services.Configuration.FederationConfigurationElementCollection
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.SectionName
  parent: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  isExternal: false
  name: SectionName
  nameWithType: SystemIdentityModelServicesSection.SectionName
  fullName: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.SectionName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.#ctor*
  parent: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  isExternal: false
  name: SystemIdentityModelServicesSection
  nameWithType: SystemIdentityModelServicesSection.SystemIdentityModelServicesSection
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.Current*
  parent: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  isExternal: false
  name: Current
  nameWithType: SystemIdentityModelServicesSection.Current
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.DefaultFederationConfigurationElement*
  parent: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  isExternal: false
  name: DefaultFederationConfigurationElement
  nameWithType: SystemIdentityModelServicesSection.DefaultFederationConfigurationElement
- uid: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection.FederationConfigurationElements*
  parent: System.IdentityModel.Services.Configuration.SystemIdentityModelServicesSection
  isExternal: false
  name: FederationConfigurationElements
  nameWithType: SystemIdentityModelServicesSection.FederationConfigurationElements
