### YamlMime:ManagedReference
items:
- uid: System.Activities.XamlIntegration.ActivityXamlServicesSettings
  id: ActivityXamlServicesSettings
  children:
  - System.Activities.XamlIntegration.ActivityXamlServicesSettings.#ctor
  - System.Activities.XamlIntegration.ActivityXamlServicesSettings.CompileExpressions
  - System.Activities.XamlIntegration.ActivityXamlServicesSettings.LocationReferenceEnvironment
  langs:
  - csharp
  name: ActivityXamlServicesSettings
  nameWithType: ActivityXamlServicesSettings
  fullName: System.Activities.XamlIntegration.ActivityXamlServicesSettings
  type: Class
  summary: "Specifies XAML Service settings."
  syntax:
    content: public class ActivityXamlServicesSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.XamlIntegration.ActivityXamlServicesSettings.#ctor
  id: '#ctor'
  parent: System.Activities.XamlIntegration.ActivityXamlServicesSettings
  langs:
  - csharp
  name: ActivityXamlServicesSettings()
  nameWithType: ActivityXamlServicesSettings.ActivityXamlServicesSettings()
  fullName: System.Activities.XamlIntegration.ActivityXamlServicesSettings.ActivityXamlServicesSettings()
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Activities.XamlIntegration.ActivityXamlServicesSettings&quot;></see> class."
  syntax:
    content: public ActivityXamlServicesSettings ();
    parameters: []
  overload: System.Activities.XamlIntegration.ActivityXamlServicesSettings.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.XamlIntegration.ActivityXamlServicesSettings.CompileExpressions
  id: CompileExpressions
  parent: System.Activities.XamlIntegration.ActivityXamlServicesSettings
  langs:
  - csharp
  name: CompileExpressions
  nameWithType: ActivityXamlServicesSettings.CompileExpressions
  fullName: System.Activities.XamlIntegration.ActivityXamlServicesSettings.CompileExpressions
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: "Gets or sets a value that indicates whether the expressions are compiled."
  syntax:
    content: public bool CompileExpressions { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_True&quot; name=&quot;True&quot; href=&quot;&quot;></xref> if the expressions are compiled; otherwise, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>."
  overload: System.Activities.XamlIntegration.ActivityXamlServicesSettings.CompileExpressions*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Activities.XamlIntegration.ActivityXamlServicesSettings.LocationReferenceEnvironment
  id: LocationReferenceEnvironment
  parent: System.Activities.XamlIntegration.ActivityXamlServicesSettings
  langs:
  - csharp
  name: LocationReferenceEnvironment
  nameWithType: ActivityXamlServicesSettings.LocationReferenceEnvironment
  fullName: System.Activities.XamlIntegration.ActivityXamlServicesSettings.LocationReferenceEnvironment
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.XamlIntegration
  summary: "Gets or sets the activity’s location reference environment."
  syntax:
    content: public System.Activities.LocationReferenceEnvironment LocationReferenceEnvironment { get; set; }
    return:
      type: System.Activities.LocationReferenceEnvironment
      description: "The activity’s location reference environment."
  overload: System.Activities.XamlIntegration.ActivityXamlServicesSettings.LocationReferenceEnvironment*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Activities.XamlIntegration.ActivityXamlServicesSettings.#ctor
  parent: System.Activities.XamlIntegration.ActivityXamlServicesSettings
  isExternal: false
  name: ActivityXamlServicesSettings()
  nameWithType: ActivityXamlServicesSettings.ActivityXamlServicesSettings()
  fullName: System.Activities.XamlIntegration.ActivityXamlServicesSettings.ActivityXamlServicesSettings()
- uid: System.Activities.XamlIntegration.ActivityXamlServicesSettings.CompileExpressions
  parent: System.Activities.XamlIntegration.ActivityXamlServicesSettings
  isExternal: false
  name: CompileExpressions
  nameWithType: ActivityXamlServicesSettings.CompileExpressions
  fullName: System.Activities.XamlIntegration.ActivityXamlServicesSettings.CompileExpressions
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Activities.XamlIntegration.ActivityXamlServicesSettings.LocationReferenceEnvironment
  parent: System.Activities.XamlIntegration.ActivityXamlServicesSettings
  isExternal: false
  name: LocationReferenceEnvironment
  nameWithType: ActivityXamlServicesSettings.LocationReferenceEnvironment
  fullName: System.Activities.XamlIntegration.ActivityXamlServicesSettings.LocationReferenceEnvironment
- uid: System.Activities.LocationReferenceEnvironment
  parent: System.Activities
  isExternal: false
  name: LocationReferenceEnvironment
  nameWithType: LocationReferenceEnvironment
  fullName: System.Activities.LocationReferenceEnvironment
- uid: System.Activities.XamlIntegration.ActivityXamlServicesSettings.#ctor*
  parent: System.Activities.XamlIntegration.ActivityXamlServicesSettings
  isExternal: false
  name: ActivityXamlServicesSettings
  nameWithType: ActivityXamlServicesSettings.ActivityXamlServicesSettings
- uid: System.Activities.XamlIntegration.ActivityXamlServicesSettings.CompileExpressions*
  parent: System.Activities.XamlIntegration.ActivityXamlServicesSettings
  isExternal: false
  name: CompileExpressions
  nameWithType: ActivityXamlServicesSettings.CompileExpressions
- uid: System.Activities.XamlIntegration.ActivityXamlServicesSettings.LocationReferenceEnvironment*
  parent: System.Activities.XamlIntegration.ActivityXamlServicesSettings
  isExternal: false
  name: LocationReferenceEnvironment
  nameWithType: ActivityXamlServicesSettings.LocationReferenceEnvironment
