### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.MexBindingElement`1
  id: MexBindingElement`1
  children:
  - System.ServiceModel.Configuration.MexBindingElement`1.#ctor(System.String)
  - System.ServiceModel.Configuration.MexBindingElement`1.BindingElementType
  - System.ServiceModel.Configuration.MexBindingElement`1.OnApplyConfiguration(System.ServiceModel.Channels.Binding)
  langs:
  - csharp
  name: MexBindingElement<TStandardBinding>
  nameWithType: MexBindingElement<TStandardBinding>
  fullName: System.ServiceModel.Configuration.MexBindingElement<TStandardBinding>
  type: Class
  syntax:
    content: 'public abstract class MexBindingElement<TStandardBinding> : System.ServiceModel.Configuration.StandardBindingElement where TStandardBinding : Binding'
    typeParameters:
    - id: TStandardBinding
      description: "To be added."
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.StandardBindingElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.StandardBindingElement.ApplyConfiguration(System.ServiceModel.Channels.Binding)
  - System.ServiceModel.Configuration.StandardBindingElement.CloseTimeout
  - System.ServiceModel.Configuration.StandardBindingElement.InitializeFrom(System.ServiceModel.Channels.Binding)
  - System.ServiceModel.Configuration.StandardBindingElement.Name
  - System.ServiceModel.Configuration.StandardBindingElement.OpenTimeout
  - System.ServiceModel.Configuration.StandardBindingElement.Properties
  - System.ServiceModel.Configuration.StandardBindingElement.ReceiveTimeout
  - System.ServiceModel.Configuration.StandardBindingElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.StandardBindingElement.SendTimeout
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.MexBindingElement`1.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.Configuration.MexBindingElement`1
  langs:
  - csharp
  name: MexBindingElement(String)
  nameWithType: MexBindingElement<TStandardBinding>.MexBindingElement(String)
  fullName: System.ServiceModel.Configuration.MexBindingElement<TStandardBinding>.MexBindingElement(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected MexBindingElement (string name);
    parameters:
    - id: name
      type: System.String
      description: "To be added."
  overload: System.ServiceModel.Configuration.MexBindingElement`1.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.MexBindingElement`1.BindingElementType
  id: BindingElementType
  parent: System.ServiceModel.Configuration.MexBindingElement`1
  langs:
  - csharp
  name: BindingElementType
  nameWithType: MexBindingElement<TStandardBinding>.BindingElementType
  fullName: System.ServiceModel.Configuration.MexBindingElement<TStandardBinding>.BindingElementType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override Type BindingElementType { get; }
    return:
      type: System.Type
      description: "To be added."
  overload: System.ServiceModel.Configuration.MexBindingElement`1.BindingElementType*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.MexBindingElement`1.OnApplyConfiguration(System.ServiceModel.Channels.Binding)
  id: OnApplyConfiguration(System.ServiceModel.Channels.Binding)
  parent: System.ServiceModel.Configuration.MexBindingElement`1
  langs:
  - csharp
  name: OnApplyConfiguration(Binding)
  nameWithType: MexBindingElement<TStandardBinding>.OnApplyConfiguration(Binding)
  fullName: System.ServiceModel.Configuration.MexBindingElement<TStandardBinding>.OnApplyConfiguration(Binding)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override void OnApplyConfiguration (System.ServiceModel.Channels.Binding binding);
    parameters:
    - id: binding
      type: System.ServiceModel.Channels.Binding
      description: "To be added."
  overload: System.ServiceModel.Configuration.MexBindingElement`1.OnApplyConfiguration*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.StandardBindingElement
  isExternal: false
  name: System.ServiceModel.Configuration.StandardBindingElement
- uid: System.ServiceModel.Configuration.MexBindingElement`1.#ctor(System.String)
  parent: System.ServiceModel.Configuration.MexBindingElement`1
  isExternal: false
  name: MexBindingElement(String)
  nameWithType: MexBindingElement<TStandardBinding>.MexBindingElement(String)
  fullName: System.ServiceModel.Configuration.MexBindingElement<TStandardBinding>.MexBindingElement(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.MexBindingElement`1.BindingElementType
  parent: System.ServiceModel.Configuration.MexBindingElement`1
  isExternal: false
  name: BindingElementType
  nameWithType: MexBindingElement<TStandardBinding>.BindingElementType
  fullName: System.ServiceModel.Configuration.MexBindingElement<TStandardBinding>.BindingElementType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.MexBindingElement`1.OnApplyConfiguration(System.ServiceModel.Channels.Binding)
  parent: System.ServiceModel.Configuration.MexBindingElement`1
  isExternal: false
  name: OnApplyConfiguration(Binding)
  nameWithType: MexBindingElement<TStandardBinding>.OnApplyConfiguration(Binding)
  fullName: System.ServiceModel.Configuration.MexBindingElement<TStandardBinding>.OnApplyConfiguration(Binding)
- uid: System.ServiceModel.Channels.Binding
  parent: System.ServiceModel.Channels
  isExternal: true
  name: Binding
  nameWithType: Binding
  fullName: System.ServiceModel.Channels.Binding
- uid: System.ServiceModel.Configuration.MexBindingElement`1.#ctor*
  parent: System.ServiceModel.Configuration.MexBindingElement`1
  isExternal: false
  name: MexBindingElement<TStandardBinding>
  nameWithType: MexBindingElement<TStandardBinding>.MexBindingElement<TStandardBinding>
- uid: System.ServiceModel.Configuration.MexBindingElement`1.BindingElementType*
  parent: System.ServiceModel.Configuration.MexBindingElement`1
  isExternal: false
  name: BindingElementType
  nameWithType: MexBindingElement<TStandardBinding>.BindingElementType
- uid: System.ServiceModel.Configuration.MexBindingElement`1.OnApplyConfiguration*
  parent: System.ServiceModel.Configuration.MexBindingElement`1
  isExternal: false
  name: OnApplyConfiguration
  nameWithType: MexBindingElement<TStandardBinding>.OnApplyConfiguration
