### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.HttpCachePolicyElement
  id: HttpCachePolicyElement
  children:
  - System.Net.Configuration.HttpCachePolicyElement.#ctor
  - System.Net.Configuration.HttpCachePolicyElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Net.Configuration.HttpCachePolicyElement.MaximumAge
  - System.Net.Configuration.HttpCachePolicyElement.MaximumStale
  - System.Net.Configuration.HttpCachePolicyElement.MinimumFresh
  - System.Net.Configuration.HttpCachePolicyElement.PolicyLevel
  - System.Net.Configuration.HttpCachePolicyElement.Properties
  - System.Net.Configuration.HttpCachePolicyElement.Reset(System.Configuration.ConfigurationElement)
  langs:
  - csharp
  name: HttpCachePolicyElement
  nameWithType: HttpCachePolicyElement
  fullName: System.Net.Configuration.HttpCachePolicyElement
  type: Class
  summary: "Represents the default HTTP cache policy for network resources. This class cannot be inherited."
  remarks: "This class corresponds to the [\\<defaultHttpCachePolicy> Element (Network Settings)](../Topic/%3CdefaultHttpCachePolicy%3E%20Element%20\\(Network%20Settings\\).md) configuration element.  \n  \n This class is used to specify the HTTP caching configuration that applies to network resources obtained by using the <xref:System.Net.WebRequest> and <xref:System.Net.WebClient> classes.  \n  \n This class provides programmatic access to information that can be stored in configuration files."
  syntax:
    content: 'public sealed class HttpCachePolicyElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.HttpCachePolicyElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.HttpCachePolicyElement
  langs:
  - csharp
  name: HttpCachePolicyElement()
  nameWithType: HttpCachePolicyElement.HttpCachePolicyElement()
  fullName: System.Net.Configuration.HttpCachePolicyElement.HttpCachePolicyElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Net.Configuration.HttpCachePolicyElement&quot;></see> class."
  remarks: "This constructor adds the <xref:System.Net.Configuration.HttpCachePolicyElement.MaximumAge%2A>, <xref:System.Net.Configuration.HttpCachePolicyElement.MaximumStale%2A>, <xref:System.Net.Configuration.HttpCachePolicyElement.MinimumFresh%2A>, and <xref:System.Net.Configuration.HttpCachePolicyElement.PolicyLevel%2A> properties to the collection."
  syntax:
    content: public HttpCachePolicyElement ();
    parameters: []
  overload: System.Net.Configuration.HttpCachePolicyElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.HttpCachePolicyElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  id: DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.Net.Configuration.HttpCachePolicyElement
  langs:
  - csharp
  name: DeserializeElement(XmlReader,Boolean)
  nameWithType: HttpCachePolicyElement.DeserializeElement(XmlReader,Boolean)
  fullName: System.Net.Configuration.HttpCachePolicyElement.DeserializeElement(XmlReader,Boolean)
  type: Method
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override void DeserializeElement (System.Xml.XmlReader reader, bool serializeCollectionKey);
    parameters:
    - id: reader
      type: System.Xml.XmlReader
      description: "To be added."
    - id: serializeCollectionKey
      type: System.Boolean
      description: "To be added."
  overload: System.Net.Configuration.HttpCachePolicyElement.DeserializeElement*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.HttpCachePolicyElement.MaximumAge
  id: MaximumAge
  parent: System.Net.Configuration.HttpCachePolicyElement
  langs:
  - csharp
  name: MaximumAge
  nameWithType: HttpCachePolicyElement.MaximumAge
  fullName: System.Net.Configuration.HttpCachePolicyElement.MaximumAge
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Gets or sets the maximum age permitted for a resource returned from the cache."
  remarks: "If the cached copy of the resource is older than the specified time value, the resource must be revalidated by comparing the cached resource to the resource on the server."
  syntax:
    content: public TimeSpan MaximumAge { get; set; }
    return:
      type: System.TimeSpan
      description: "A &lt;xref:System.TimeSpan&gt; value that specifies the maximum age for cached resources specified in the configuration file."
  overload: System.Net.Configuration.HttpCachePolicyElement.MaximumAge*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.HttpCachePolicyElement.MaximumStale
  id: MaximumStale
  parent: System.Net.Configuration.HttpCachePolicyElement
  langs:
  - csharp
  name: MaximumStale
  nameWithType: HttpCachePolicyElement.MaximumStale
  fullName: System.Net.Configuration.HttpCachePolicyElement.MaximumStale
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Gets or sets the maximum staleness value permitted for a resource returned from the cache."
  remarks: "This property specifies the amount of time after content expiration during which the cached copy of the resource is acceptable."
  syntax:
    content: public TimeSpan MaximumStale { get; set; }
    return:
      type: System.TimeSpan
      description: "A &lt;xref:System.TimeSpan&gt; value that is set to the maximum staleness value specified in the configuration file."
  overload: System.Net.Configuration.HttpCachePolicyElement.MaximumStale*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.HttpCachePolicyElement.MinimumFresh
  id: MinimumFresh
  parent: System.Net.Configuration.HttpCachePolicyElement
  langs:
  - csharp
  name: MinimumFresh
  nameWithType: HttpCachePolicyElement.MinimumFresh
  fullName: System.Net.Configuration.HttpCachePolicyElement.MinimumFresh
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Gets or sets the minimum freshness permitted for a resource returned from the cache."
  remarks: "This value specifies the amount of time before content expiration, during which the cached copy of the resource is acceptable."
  syntax:
    content: public TimeSpan MinimumFresh { get; set; }
    return:
      type: System.TimeSpan
      description: "A &lt;xref:System.TimeSpan&gt; value that specifies the minimum freshness specified in the configuration file."
  overload: System.Net.Configuration.HttpCachePolicyElement.MinimumFresh*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.HttpCachePolicyElement.PolicyLevel
  id: PolicyLevel
  parent: System.Net.Configuration.HttpCachePolicyElement
  langs:
  - csharp
  name: PolicyLevel
  nameWithType: HttpCachePolicyElement.PolicyLevel
  fullName: System.Net.Configuration.HttpCachePolicyElement.PolicyLevel
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Gets or sets HTTP caching behavior for the local machine."
  remarks: "Applications typically use <xref:System.Net.Cache.HttpRequestCacheLevel> as their cache policy level. The <xref:System.Net.WebRequest.CachePolicy%2A> property, if not `null`, determines the cache policy in effect for a request."
  syntax:
    content: public System.Net.Cache.HttpRequestCacheLevel PolicyLevel { get; set; }
    return:
      type: System.Net.Cache.HttpRequestCacheLevel
      description: "A <see cref=&quot;T:System.Net.Cache.HttpRequestCacheLevel&quot;></see> value that specifies the cache behavior."
  overload: System.Net.Configuration.HttpCachePolicyElement.PolicyLevel*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.HttpCachePolicyElement.Properties
  id: Properties
  parent: System.Net.Configuration.HttpCachePolicyElement
  langs:
  - csharp
  name: Properties
  nameWithType: HttpCachePolicyElement.Properties
  fullName: System.Net.Configuration.HttpCachePolicyElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Net.Configuration.HttpCachePolicyElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.HttpCachePolicyElement.Reset(System.Configuration.ConfigurationElement)
  id: Reset(System.Configuration.ConfigurationElement)
  parent: System.Net.Configuration.HttpCachePolicyElement
  langs:
  - csharp
  name: Reset(ConfigurationElement)
  nameWithType: HttpCachePolicyElement.Reset(ConfigurationElement)
  fullName: System.Net.Configuration.HttpCachePolicyElement.Reset(ConfigurationElement)
  type: Method
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override void Reset (System.Configuration.ConfigurationElement parentElement);
    parameters:
    - id: parentElement
      type: System.Configuration.ConfigurationElement
      description: "To be added."
  overload: System.Net.Configuration.HttpCachePolicyElement.Reset*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.HttpCachePolicyElement.#ctor
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: HttpCachePolicyElement()
  nameWithType: HttpCachePolicyElement.HttpCachePolicyElement()
  fullName: System.Net.Configuration.HttpCachePolicyElement.HttpCachePolicyElement()
- uid: System.Net.Configuration.HttpCachePolicyElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: DeserializeElement(XmlReader,Boolean)
  nameWithType: HttpCachePolicyElement.DeserializeElement(XmlReader,Boolean)
  fullName: System.Net.Configuration.HttpCachePolicyElement.DeserializeElement(XmlReader,Boolean)
- uid: System.Xml.XmlReader
  parent: System.Xml
  isExternal: true
  name: XmlReader
  nameWithType: XmlReader
  fullName: System.Xml.XmlReader
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Net.Configuration.HttpCachePolicyElement.MaximumAge
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: MaximumAge
  nameWithType: HttpCachePolicyElement.MaximumAge
  fullName: System.Net.Configuration.HttpCachePolicyElement.MaximumAge
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Net.Configuration.HttpCachePolicyElement.MaximumStale
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: MaximumStale
  nameWithType: HttpCachePolicyElement.MaximumStale
  fullName: System.Net.Configuration.HttpCachePolicyElement.MaximumStale
- uid: System.Net.Configuration.HttpCachePolicyElement.MinimumFresh
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: MinimumFresh
  nameWithType: HttpCachePolicyElement.MinimumFresh
  fullName: System.Net.Configuration.HttpCachePolicyElement.MinimumFresh
- uid: System.Net.Configuration.HttpCachePolicyElement.PolicyLevel
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: PolicyLevel
  nameWithType: HttpCachePolicyElement.PolicyLevel
  fullName: System.Net.Configuration.HttpCachePolicyElement.PolicyLevel
- uid: System.Net.Cache.HttpRequestCacheLevel
  parent: System.Net.Cache
  isExternal: false
  name: HttpRequestCacheLevel
  nameWithType: HttpRequestCacheLevel
  fullName: System.Net.Cache.HttpRequestCacheLevel
- uid: System.Net.Configuration.HttpCachePolicyElement.Properties
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: Properties
  nameWithType: HttpCachePolicyElement.Properties
  fullName: System.Net.Configuration.HttpCachePolicyElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.HttpCachePolicyElement.Reset(System.Configuration.ConfigurationElement)
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: Reset(ConfigurationElement)
  nameWithType: HttpCachePolicyElement.Reset(ConfigurationElement)
  fullName: System.Net.Configuration.HttpCachePolicyElement.Reset(ConfigurationElement)
- uid: System.Net.Configuration.HttpCachePolicyElement.#ctor*
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: HttpCachePolicyElement
  nameWithType: HttpCachePolicyElement.HttpCachePolicyElement
- uid: System.Net.Configuration.HttpCachePolicyElement.DeserializeElement*
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: DeserializeElement
  nameWithType: HttpCachePolicyElement.DeserializeElement
- uid: System.Net.Configuration.HttpCachePolicyElement.MaximumAge*
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: MaximumAge
  nameWithType: HttpCachePolicyElement.MaximumAge
- uid: System.Net.Configuration.HttpCachePolicyElement.MaximumStale*
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: MaximumStale
  nameWithType: HttpCachePolicyElement.MaximumStale
- uid: System.Net.Configuration.HttpCachePolicyElement.MinimumFresh*
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: MinimumFresh
  nameWithType: HttpCachePolicyElement.MinimumFresh
- uid: System.Net.Configuration.HttpCachePolicyElement.PolicyLevel*
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: PolicyLevel
  nameWithType: HttpCachePolicyElement.PolicyLevel
- uid: System.Net.Configuration.HttpCachePolicyElement.Properties*
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: Properties
  nameWithType: HttpCachePolicyElement.Properties
- uid: System.Net.Configuration.HttpCachePolicyElement.Reset*
  parent: System.Net.Configuration.HttpCachePolicyElement
  isExternal: false
  name: Reset
  nameWithType: HttpCachePolicyElement.Reset
