### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.MsmqTransportSecurity
  id: MsmqTransportSecurity
  children:
  - System.ServiceModel.MsmqTransportSecurity.#ctor
  - System.ServiceModel.MsmqTransportSecurity.#ctor(System.ServiceModel.MsmqTransportSecurity)
  - System.ServiceModel.MsmqTransportSecurity.MsmqAuthenticationMode
  - System.ServiceModel.MsmqTransportSecurity.MsmqEncryptionAlgorithm
  - System.ServiceModel.MsmqTransportSecurity.MsmqProtectionLevel
  - System.ServiceModel.MsmqTransportSecurity.MsmqSecureHashAlgorithm
  langs:
  - csharp
  name: MsmqTransportSecurity
  nameWithType: MsmqTransportSecurity
  fullName: System.ServiceModel.MsmqTransportSecurity
  type: Class
  summary: "The MsmqTransportSecurity class encapsulates the transport security settings for queued transports."
  syntax:
    content: public sealed class MsmqTransportSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.MsmqTransportSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.MsmqTransportSecurity
  langs:
  - csharp
  name: MsmqTransportSecurity()
  nameWithType: MsmqTransportSecurity.MsmqTransportSecurity()
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqTransportSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.MsmqTransportSecurity&quot;></see> class."
  syntax:
    content: public MsmqTransportSecurity ();
    parameters: []
  overload: System.ServiceModel.MsmqTransportSecurity.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.MsmqTransportSecurity.#ctor(System.ServiceModel.MsmqTransportSecurity)
  id: '#ctor(System.ServiceModel.MsmqTransportSecurity)'
  parent: System.ServiceModel.MsmqTransportSecurity
  langs:
  - csharp
  name: MsmqTransportSecurity(MsmqTransportSecurity)
  nameWithType: MsmqTransportSecurity.MsmqTransportSecurity(MsmqTransportSecurity)
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqTransportSecurity(MsmqTransportSecurity)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.MsmqTransportSecurity&quot;></see> class, using an existing instance."
  syntax:
    content: public MsmqTransportSecurity (System.ServiceModel.MsmqTransportSecurity other);
    parameters:
    - id: other
      type: System.ServiceModel.MsmqTransportSecurity
      description: "The existing instance of the  class, to be used in initializing the new instance."
  overload: System.ServiceModel.MsmqTransportSecurity.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "\n    other is ."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqAuthenticationMode
  id: MsmqAuthenticationMode
  parent: System.ServiceModel.MsmqTransportSecurity
  langs:
  - csharp
  name: MsmqAuthenticationMode
  nameWithType: MsmqTransportSecurity.MsmqAuthenticationMode
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqAuthenticationMode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Gets or sets the <see cref=&quot;T:System.ServiceModel.MsmqAuthenticationMode&quot;></see> that is associated with this instance of the <see cref=&quot;T:System.ServiceModel.MsmqTransportSecurity&quot;></see> class."
  remarks: "MSMQ can authenticate messages that are sent to message queues that require authentication, or messages can explicitly request authentication. The default authentication mode is <xref:System.ServiceModel.MsmqAuthenticationMode>."
  syntax:
    content: public System.ServiceModel.MsmqAuthenticationMode MsmqAuthenticationMode { get; set; }
    return:
      type: System.ServiceModel.MsmqAuthenticationMode
      description: "The <see cref=&quot;T:System.ServiceModel.MsmqAuthenticationMode&quot;></see> that is associated with this instance of the <see cref=&quot;T:System.ServiceModel.MsmqTransportSecurity&quot;></see> class."
  overload: System.ServiceModel.MsmqTransportSecurity.MsmqAuthenticationMode*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "The value is not one of  values."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqEncryptionAlgorithm
  id: MsmqEncryptionAlgorithm
  parent: System.ServiceModel.MsmqTransportSecurity
  langs:
  - csharp
  name: MsmqEncryptionAlgorithm
  nameWithType: MsmqTransportSecurity.MsmqEncryptionAlgorithm
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqEncryptionAlgorithm
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Gets or sets the <see cref=&quot;T:System.ServiceModel.MsmqEncryptionAlgorithm&quot;></see> that is associated with this instance of the <see cref=&quot;T:System.ServiceModel.MsmqTransportSecurity&quot;></see> class."
  remarks: "MSMQ can encrypt messages on the wire when transferring messages between message queue managers. The default encryption algorithm is <xref:System.ServiceModel.MsmqEncryptionAlgorithm>."
  syntax:
    content: public System.ServiceModel.MsmqEncryptionAlgorithm MsmqEncryptionAlgorithm { get; set; }
    return:
      type: System.ServiceModel.MsmqEncryptionAlgorithm
      description: "The <see cref=&quot;T:System.ServiceModel.MsmqEncryptionAlgorithm&quot;></see> that is associated with this instance of the <see cref=&quot;T:System.ServiceModel.MsmqTransportSecurity&quot;></see> class."
  overload: System.ServiceModel.MsmqTransportSecurity.MsmqEncryptionAlgorithm*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "The value is not one of  values."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqProtectionLevel
  id: MsmqProtectionLevel
  parent: System.ServiceModel.MsmqTransportSecurity
  langs:
  - csharp
  name: MsmqProtectionLevel
  nameWithType: MsmqTransportSecurity.MsmqProtectionLevel
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqProtectionLevel
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Gets or sets the <see cref=&quot;T:System.Net.Security.ProtectionLevel&quot;></see> that is associated with this instance of the <see cref=&quot;T:System.ServiceModel.MsmqTransportSecurity&quot;></see> class."
  remarks: "The default protection level is <xref:System.Net.Security.ProtectionLevel>."
  syntax:
    content: public System.Net.Security.ProtectionLevel MsmqProtectionLevel { get; set; }
    return:
      type: System.Net.Security.ProtectionLevel
      description: "The <see cref=&quot;T:System.Net.Security.ProtectionLevel&quot;></see> that is associated with this instance of the <see cref=&quot;T:System.ServiceModel.MsmqTransportSecurity&quot;></see> class."
  overload: System.ServiceModel.MsmqTransportSecurity.MsmqProtectionLevel*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "The value is not one of the  values."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqSecureHashAlgorithm
  id: MsmqSecureHashAlgorithm
  parent: System.ServiceModel.MsmqTransportSecurity
  langs:
  - csharp
  name: MsmqSecureHashAlgorithm
  nameWithType: MsmqTransportSecurity.MsmqSecureHashAlgorithm
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqSecureHashAlgorithm
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Gets or sets the <see cref=&quot;T:System.ServiceModel.MsmqSecureHashAlgorithm&quot;></see> that is associated with this instance of the <see cref=&quot;T:System.ServiceModel.MsmqTransportSecurity&quot;></see> class."
  remarks: "The default hash algorithm is <xref:System.ServiceModel.MsmqSecureHashAlgorithm.SHA1>."
  syntax:
    content: public System.ServiceModel.MsmqSecureHashAlgorithm MsmqSecureHashAlgorithm { get; set; }
    return:
      type: System.ServiceModel.MsmqSecureHashAlgorithm
      description: "The <see cref=&quot;T:System.ServiceModel.MsmqSecureHashAlgorithm&quot;></see> that is associated with this instance of the <see cref=&quot;T:System.ServiceModel.MsmqTransportSecurity&quot;></see> class."
  overload: System.ServiceModel.MsmqTransportSecurity.MsmqSecureHashAlgorithm*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "The value is not one of  values."
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.MsmqTransportSecurity.#ctor
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqTransportSecurity()
  nameWithType: MsmqTransportSecurity.MsmqTransportSecurity()
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqTransportSecurity()
- uid: System.ServiceModel.MsmqTransportSecurity.#ctor(System.ServiceModel.MsmqTransportSecurity)
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqTransportSecurity(MsmqTransportSecurity)
  nameWithType: MsmqTransportSecurity.MsmqTransportSecurity(MsmqTransportSecurity)
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqTransportSecurity(MsmqTransportSecurity)
- uid: System.ServiceModel.MsmqTransportSecurity
  parent: System.ServiceModel
  isExternal: false
  name: MsmqTransportSecurity
  nameWithType: MsmqTransportSecurity
  fullName: System.ServiceModel.MsmqTransportSecurity
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqAuthenticationMode
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqAuthenticationMode
  nameWithType: MsmqTransportSecurity.MsmqAuthenticationMode
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqAuthenticationMode
- uid: System.ServiceModel.MsmqAuthenticationMode
  parent: System.ServiceModel
  isExternal: false
  name: MsmqAuthenticationMode
  nameWithType: MsmqAuthenticationMode
  fullName: System.ServiceModel.MsmqAuthenticationMode
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqEncryptionAlgorithm
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqEncryptionAlgorithm
  nameWithType: MsmqTransportSecurity.MsmqEncryptionAlgorithm
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqEncryptionAlgorithm
- uid: System.ServiceModel.MsmqEncryptionAlgorithm
  parent: System.ServiceModel
  isExternal: false
  name: MsmqEncryptionAlgorithm
  nameWithType: MsmqEncryptionAlgorithm
  fullName: System.ServiceModel.MsmqEncryptionAlgorithm
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqProtectionLevel
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqProtectionLevel
  nameWithType: MsmqTransportSecurity.MsmqProtectionLevel
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqProtectionLevel
- uid: System.Net.Security.ProtectionLevel
  parent: System.Net.Security
  isExternal: false
  name: ProtectionLevel
  nameWithType: ProtectionLevel
  fullName: System.Net.Security.ProtectionLevel
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqSecureHashAlgorithm
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqSecureHashAlgorithm
  nameWithType: MsmqTransportSecurity.MsmqSecureHashAlgorithm
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqSecureHashAlgorithm
- uid: System.ServiceModel.MsmqSecureHashAlgorithm
  parent: System.ServiceModel
  isExternal: false
  name: MsmqSecureHashAlgorithm
  nameWithType: MsmqSecureHashAlgorithm
  fullName: System.ServiceModel.MsmqSecureHashAlgorithm
- uid: System.ServiceModel.MsmqTransportSecurity.#ctor*
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqTransportSecurity
  nameWithType: MsmqTransportSecurity.MsmqTransportSecurity
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqAuthenticationMode*
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqAuthenticationMode
  nameWithType: MsmqTransportSecurity.MsmqAuthenticationMode
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqEncryptionAlgorithm*
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqEncryptionAlgorithm
  nameWithType: MsmqTransportSecurity.MsmqEncryptionAlgorithm
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqProtectionLevel*
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqProtectionLevel
  nameWithType: MsmqTransportSecurity.MsmqProtectionLevel
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqSecureHashAlgorithm*
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqSecureHashAlgorithm
  nameWithType: MsmqTransportSecurity.MsmqSecureHashAlgorithm
