### YamlMime:ManagedReference
items:
- uid: System.Configuration.DpapiProtectedConfigurationProvider
  id: DpapiProtectedConfigurationProvider
  children:
  - System.Configuration.DpapiProtectedConfigurationProvider.#ctor
  - System.Configuration.DpapiProtectedConfigurationProvider.Decrypt(System.Xml.XmlNode)
  - System.Configuration.DpapiProtectedConfigurationProvider.Encrypt(System.Xml.XmlNode)
  - System.Configuration.DpapiProtectedConfigurationProvider.Initialize(System.String,System.Collections.Specialized.NameValueCollection)
  - System.Configuration.DpapiProtectedConfigurationProvider.UseMachineProtection
  langs:
  - csharp
  name: DpapiProtectedConfigurationProvider
  nameWithType: DpapiProtectedConfigurationProvider
  fullName: System.Configuration.DpapiProtectedConfigurationProvider
  type: Class
  summary: "Provides a <see cref=&quot;T:System.Configuration.ProtectedConfigurationProvider&quot;></see> object that uses the Windows data protection API (DPAPI) to encrypt and decrypt configuration data."
  remarks: "The DpapiProtectedConfigurationProvider allows you to protect sensitive information stored in a configuration file from unauthorized access.       You use the standard DpapiProtectedConfigurationProvider by declaring the provider and appropriate settings in the configuration file rather than creating an instance of this class. Refer to the next example.       For more information about Protected Configuration, see [Encrypting Configuration Information Using Protected Configuration](../Topic/Encrypting%20Configuration%20Information%20Using%20Protected%20Configuration.md).       The DpapiProtectedConfigurationProvider uses the Windows built-in cryptographic services and can be configured for either machine-specific or user-account-specific protection. Machine-specific protection is useful for anonymous services but provides less security. User-account-specific protection can be used with services that run with a specific user identity."
  example:
  - "The following example shows how to use the standard DpapiProtectedConfigurationProvider to protect or unprotect a configuration section.  \n  \n [!CODE [System.Configuration.DpapiProtectedConfigurationProvider#1](System.Configuration.DpapiProtectedConfigurationProvider#1)]  \n  \n The following configuration excerpts show the configuration section before and after the protection has been applied.  \n  \n```  \n<?xml version=\"1.0\" encoding=\"utf-8\" ?>  \n<configuration>  \n  <connectionStrings>  \n    <add name=\"NorthwindConnectionString\"   \n      connectionString=\"Data Source=webnetue2;Initial Catalog=Northwind;User ID=aspnet_test;Password=test\"  \n      providerName=\"System.Data.SqlClient\" />  \n  </connectionStrings>  \n</configuration>  \n```  \n  \n```  \n<?xml version=\"1.0\" encoding=\"utf-8\"?>  \n<configuration>  \n  <connectionStrings>  \n    <EncryptedData>  \n      <CipherData>                <CipherValue>AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAcAMh0jIC1kigyFfd9AUZfQQAAAACAAAAAAADZgAAqAAAABAAAADQwbQ2DgIgIlqskE1RI9UpAAAAAASAAACgAAAAEAAAAAXlYBxi3jhM6wv4sxLhugsQAgAAgoReHZS2406dc/AyRDd6WuNr4ihHn6fbipd4tzHEmeuyS4o4fS4CmT3jMt/WjsP/kR7TF4ygwr2GG47podK79ECpVCZHAgctCauCYjE2Ls3iphKXy/pHic2o6aaClt/xPm+fb4OfODv6XjrJhJzGK2lqUPXkyJN1w2zwh6OVpDQF9N8vTyxL4eitp35/M5zYbW7e6VVAgYUOxlNxgCV5+jXpUKh/rPovopTD392u8KavqQFW1iu+gBPSPq/xeZNz+qYMKbUl+r4VTzBQg3fPlRxp1lNZmM2yRgUbkYPNaFb9ihS7GAg5/wZn8lLmThvq39eA0Vlp6hDE92iop885umELt0/NBKf5umQCqqz9EXXLbmmGc7qoLqTaYVuOmqx0LsvrJL0wSL1dSySCjmB/dNAtVUYgg02eWQNKyaLqnpMdCbTLLQ/oCKuNkL5OQ7t1yl5wQGjQhieIRzLtrMgpTSyaHbqDsRurp9Bc5mM078IAg1hXquQNKlJC/wiJ9kbHerFCbtuLGy/7nXVrFH91ud4U4ExCJEuhoTdmuql5kbqYd6Ye/bu2CftPni19nDkSJ8w4NoqMNKbK3Mi/Cd0o113HsVYlETMv1vlJWZWYP91PK9trixiY4E0G81c6IKITjHDrOJ9evdw2T1/TrvY6pzre3UXSJbFMDQVX6JoAxFk02SRZDKOZdRojeoX19lgrFAAAABzjlz3Qg2as3vn7MRQVxDfZucgE</CipherValue>  \n      </CipherData>  \n    </EncryptedData>  \n  </connectionStrings>  \n  <configProtectedData defaultProvider=\"RsaProtectedConfigurationProvider\">  \n    <providers>  \n      <clear />  \n      <add keyContainerName=\"NetFrameworkConfigurationKey\" cspProviderName=\"\"  \n        useMachineContainer=\"true\" useOAEP=\"false\" description=\"Uses RsaCryptoServiceProvider to encrypt and decrypt\"  \n        name=\"RsaProtectedConfigurationProvider\" type=\"System.Configuration.RsaProtectedConfigurationProvider,System.Configuration, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" />  \n      <add useMachineProtection=\"true\" description=\"Uses CryptProtectData and CryptUnProtectData Windows APIs to encrypt and decrypt\"  \n        keyEntropy=\"\" name=\"DataProtectionConfigurationProvider\" type=\"System.Configuration.DpapiProtectedConfigurationProvider,System.Configuration, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" />  \n    </providers>  \n  </configProtectedData>  \n</configuration>  \n```"
  syntax:
    content: 'public sealed class DpapiProtectedConfigurationProvider : System.Configuration.ProtectedConfigurationProvider'
  inheritance:
  - System.Object
  - System.Configuration.Provider.ProviderBase
  - System.Configuration.ProtectedConfigurationProvider
  implements: []
  inheritedMembers:
  - System.Configuration.Provider.ProviderBase.Description
  - System.Configuration.Provider.ProviderBase.Name
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.DpapiProtectedConfigurationProvider.#ctor
  id: '#ctor'
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  langs:
  - csharp
  name: DpapiProtectedConfigurationProvider()
  nameWithType: DpapiProtectedConfigurationProvider.DpapiProtectedConfigurationProvider()
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.DpapiProtectedConfigurationProvider()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.DpapiProtectedConfigurationProvider&quot;></see> class using default settings."
  remarks: "The DpapiProtectedConfigurationProvider constructor is not intended to be used directly from your code. It is called by the ASP.NET configuration system."
  syntax:
    content: public DpapiProtectedConfigurationProvider ();
    parameters: []
  overload: System.Configuration.DpapiProtectedConfigurationProvider.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Decrypt(System.Xml.XmlNode)
  id: Decrypt(System.Xml.XmlNode)
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  langs:
  - csharp
  name: Decrypt(XmlNode)
  nameWithType: DpapiProtectedConfigurationProvider.Decrypt(XmlNode)
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.Decrypt(XmlNode)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Decrypts the passed <see cref=&quot;T:System.Xml.XmlNode&quot;></see> object."
  syntax:
    content: public override System.Xml.XmlNode Decrypt (System.Xml.XmlNode encryptedNode);
    parameters:
    - id: encryptedNode
      type: System.Xml.XmlNode
      description: "The  object to decrypt."
    return:
      type: System.Xml.XmlNode
      description: "To be added."
  overload: System.Configuration.DpapiProtectedConfigurationProvider.Decrypt*
  exceptions:
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "\n    encryptedNode does not have <xref:System.Xml.XmlNode.Name%2A> set to \"EncryptedData\" and <xref:System.Xml.XmlNodeType> set to <xref:System.Xml.XmlNodeType>.  \n  \n \\- or -  \n  \n encryptedNode does not have a child node named \"CipherData\" with a child node named \"CipherValue\".  \n  \n \\- or -  \n  \n The child node named \"CipherData\" is an empty node."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Encrypt(System.Xml.XmlNode)
  id: Encrypt(System.Xml.XmlNode)
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  langs:
  - csharp
  name: Encrypt(XmlNode)
  nameWithType: DpapiProtectedConfigurationProvider.Encrypt(XmlNode)
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.Encrypt(XmlNode)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Encrypts the passed <see cref=&quot;T:System.Xml.XmlNode&quot;></see> object."
  syntax:
    content: public override System.Xml.XmlNode Encrypt (System.Xml.XmlNode node);
    parameters:
    - id: node
      type: System.Xml.XmlNode
      description: "The  object to encrypt."
    return:
      type: System.Xml.XmlNode
      description: "To be added."
  overload: System.Configuration.DpapiProtectedConfigurationProvider.Encrypt*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Initialize(System.String,System.Collections.Specialized.NameValueCollection)
  id: Initialize(System.String,System.Collections.Specialized.NameValueCollection)
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  langs:
  - csharp
  name: Initialize(String,NameValueCollection)
  nameWithType: DpapiProtectedConfigurationProvider.Initialize(String,NameValueCollection)
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.Initialize(String,NameValueCollection)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initializes the provider with default settings."
  syntax:
    content: public override void Initialize (string name, System.Collections.Specialized.NameValueCollection configurationValues);
    parameters:
    - id: name
      type: System.String
      description: "The provider name to use for the object."
    - id: configurationValues
      type: System.Collections.Specialized.NameValueCollection
      description: "A  collection of values to use when initializing the object."
  overload: System.Configuration.DpapiProtectedConfigurationProvider.Initialize*
  exceptions:
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "\n    configurationValues contains an unrecognized configuration setting."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.DpapiProtectedConfigurationProvider.UseMachineProtection
  id: UseMachineProtection
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  langs:
  - csharp
  name: UseMachineProtection
  nameWithType: DpapiProtectedConfigurationProvider.UseMachineProtection
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.UseMachineProtection
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets a value that indicates whether the <see cref=&quot;T:System.Configuration.DpapiProtectedConfigurationProvider&quot;></see> object is using machine-specific or user-account-specific protection."
  remarks: "Machine-specific protection is useful for anonymous services but provides less security. User-account-specific protection can be used with services that run with a specific user identity."
  syntax:
    content: public bool UseMachineProtection { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if the <see cref=&quot;T:System.Configuration.DpapiProtectedConfigurationProvider&quot;></see> is using machine-specific protection; <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref> if it is using user-account-specific protection."
  overload: System.Configuration.DpapiProtectedConfigurationProvider.UseMachineProtection*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ProtectedConfigurationProvider
  isExternal: false
  name: System.Configuration.ProtectedConfigurationProvider
- uid: System.Configuration.DpapiProtectedConfigurationProvider.#ctor
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: DpapiProtectedConfigurationProvider()
  nameWithType: DpapiProtectedConfigurationProvider.DpapiProtectedConfigurationProvider()
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.DpapiProtectedConfigurationProvider()
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Decrypt(System.Xml.XmlNode)
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: Decrypt(XmlNode)
  nameWithType: DpapiProtectedConfigurationProvider.Decrypt(XmlNode)
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.Decrypt(XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Encrypt(System.Xml.XmlNode)
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: Encrypt(XmlNode)
  nameWithType: DpapiProtectedConfigurationProvider.Encrypt(XmlNode)
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.Encrypt(XmlNode)
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Initialize(System.String,System.Collections.Specialized.NameValueCollection)
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: Initialize(String,NameValueCollection)
  nameWithType: DpapiProtectedConfigurationProvider.Initialize(String,NameValueCollection)
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.Initialize(String,NameValueCollection)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Collections.Specialized.NameValueCollection
  parent: System.Collections.Specialized
  isExternal: false
  name: NameValueCollection
  nameWithType: NameValueCollection
  fullName: System.Collections.Specialized.NameValueCollection
- uid: System.Configuration.DpapiProtectedConfigurationProvider.UseMachineProtection
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: UseMachineProtection
  nameWithType: DpapiProtectedConfigurationProvider.UseMachineProtection
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.UseMachineProtection
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.DpapiProtectedConfigurationProvider.#ctor*
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: DpapiProtectedConfigurationProvider
  nameWithType: DpapiProtectedConfigurationProvider.DpapiProtectedConfigurationProvider
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Decrypt*
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: Decrypt
  nameWithType: DpapiProtectedConfigurationProvider.Decrypt
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Encrypt*
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: Encrypt
  nameWithType: DpapiProtectedConfigurationProvider.Encrypt
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Initialize*
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: Initialize
  nameWithType: DpapiProtectedConfigurationProvider.Initialize
- uid: System.Configuration.DpapiProtectedConfigurationProvider.UseMachineProtection*
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: UseMachineProtection
  nameWithType: DpapiProtectedConfigurationProvider.UseMachineProtection
