### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ComMethodElement
  id: ComMethodElement
  children:
  - System.ServiceModel.Configuration.ComMethodElement.#ctor
  - System.ServiceModel.Configuration.ComMethodElement.#ctor(System.String)
  - System.ServiceModel.Configuration.ComMethodElement.ExposedMethod
  - System.ServiceModel.Configuration.ComMethodElement.Properties
  langs:
  - csharp
  name: ComMethodElement
  nameWithType: ComMethodElement
  fullName: System.ServiceModel.Configuration.ComMethodElement
  type: Class
  summary: "Represents a COM+ method that is exposed when the interface on a COM+ component is exposed as a Web service. This class cannot be inherited."
  remarks: "The COM+ integration configuration tool (ComSvcConfig.exe) can be used to add specific methods from a COM interface to appear on the generated service contract.       For example, you can use the following command to add the three named methods from the `IFinances` COM interface on the `ItemOrders.Financial` component, to the generated service contract.      ```   ComSvcConfig.exe /i /application:OnlineStore /contract:ItemOrders.Financial,IFinances.{TransferFunds,AddFunds,RemoveFunds} /hosting:complus   ```       When you run the ComSvcConfig.exe too, it then generates the following service contract listing the previously mentioned methods as `exposedMethod` elements.      ```      <comContract contractType=&quot;{C551FBA9-E3AA-4272-8C2A-84BD8D290AC7}&quot; name=&quot;IFinances&quot; namespace=&quot;http://contoso.com/services/financial&quot;>       <exposedMethod name=&quot;TransferFunds&quot;/>       <exposedMethod name=&quot;AddFunds&quot;/>       <exposedMethod name=&quot;RemoveFunds&quot;/>   </comContract>      ```       At service initialization time, the runtime attempts to generate a service contract by reflecting over and adding only the methods included in the list of `exposedMethod` elements. A trace is produced for every interface method that is not included on the service contract."
  syntax:
    content: 'public sealed class ComMethodElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ComMethodElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ComMethodElement
  langs:
  - csharp
  name: ComMethodElement()
  nameWithType: ComMethodElement.ComMethodElement()
  fullName: System.ServiceModel.Configuration.ComMethodElement.ComMethodElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.ComMethodElement&quot;></see> class."
  syntax:
    content: public ComMethodElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.ComMethodElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ComMethodElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.Configuration.ComMethodElement
  langs:
  - csharp
  name: ComMethodElement(String)
  nameWithType: ComMethodElement.ComMethodElement(String)
  fullName: System.ServiceModel.Configuration.ComMethodElement.ComMethodElement(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.ComMethodElement&quot;></see> class with the specified method."
  syntax:
    content: public ComMethodElement (string method);
    parameters:
    - id: method
      type: System.String
      description: "A COM+ method exposed."
  overload: System.ServiceModel.Configuration.ComMethodElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ComMethodElement.ExposedMethod
  id: ExposedMethod
  parent: System.ServiceModel.Configuration.ComMethodElement
  langs:
  - csharp
  name: ExposedMethod
  nameWithType: ComMethodElement.ExposedMethod
  fullName: System.ServiceModel.Configuration.ComMethodElement.ExposedMethod
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets the COM+ method that is exposed when the interface on a COM+ component is exposed as a Web service."
  syntax:
    content: public string ExposedMethod { get; set; }
    return:
      type: System.String
      description: "The name of the COM+ method that is exposed when the interface on a COM+ component is exposed as a Web service."
  overload: System.ServiceModel.Configuration.ComMethodElement.ExposedMethod*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ComMethodElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ComMethodElement
  langs:
  - csharp
  name: Properties
  nameWithType: ComMethodElement.Properties
  fullName: System.ServiceModel.Configuration.ComMethodElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.ComMethodElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.ComMethodElement.#ctor
  parent: System.ServiceModel.Configuration.ComMethodElement
  isExternal: false
  name: ComMethodElement()
  nameWithType: ComMethodElement.ComMethodElement()
  fullName: System.ServiceModel.Configuration.ComMethodElement.ComMethodElement()
- uid: System.ServiceModel.Configuration.ComMethodElement.#ctor(System.String)
  parent: System.ServiceModel.Configuration.ComMethodElement
  isExternal: false
  name: ComMethodElement(String)
  nameWithType: ComMethodElement.ComMethodElement(String)
  fullName: System.ServiceModel.Configuration.ComMethodElement.ComMethodElement(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.ComMethodElement.ExposedMethod
  parent: System.ServiceModel.Configuration.ComMethodElement
  isExternal: false
  name: ExposedMethod
  nameWithType: ComMethodElement.ExposedMethod
  fullName: System.ServiceModel.Configuration.ComMethodElement.ExposedMethod
- uid: System.ServiceModel.Configuration.ComMethodElement.Properties
  parent: System.ServiceModel.Configuration.ComMethodElement
  isExternal: false
  name: Properties
  nameWithType: ComMethodElement.Properties
  fullName: System.ServiceModel.Configuration.ComMethodElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ComMethodElement.#ctor*
  parent: System.ServiceModel.Configuration.ComMethodElement
  isExternal: false
  name: ComMethodElement
  nameWithType: ComMethodElement.ComMethodElement
- uid: System.ServiceModel.Configuration.ComMethodElement.ExposedMethod*
  parent: System.ServiceModel.Configuration.ComMethodElement
  isExternal: false
  name: ExposedMethod
  nameWithType: ComMethodElement.ExposedMethod
- uid: System.ServiceModel.Configuration.ComMethodElement.Properties*
  parent: System.ServiceModel.Configuration.ComMethodElement
  isExternal: false
  name: Properties
  nameWithType: ComMethodElement.Properties
