### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  id: BrowserCapabilitiesFactoryBase
  children:
  - System.Web.Configuration.BrowserCapabilitiesFactoryBase.#ctor
  - System.Web.Configuration.BrowserCapabilitiesFactoryBase.BrowserElements
  - System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities(System.Collections.Specialized.NameValueCollection,System.Web.HttpBrowserCapabilities)
  - System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities(System.Collections.Specialized.NameValueCollection,System.Web.HttpBrowserCapabilities)
  - System.Web.Configuration.BrowserCapabilitiesFactoryBase.IsBrowserUnknown(System.Web.Configuration.HttpCapabilitiesBase)
  - System.Web.Configuration.BrowserCapabilitiesFactoryBase.MatchedHeaders
  - System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateBrowserElements(System.Collections.IDictionary)
  - System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders(System.Collections.IDictionary)
  langs:
  - csharp
  name: BrowserCapabilitiesFactoryBase
  nameWithType: BrowserCapabilitiesFactoryBase
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  type: Class
  summary: "The BrowserCapabilitiesFactoryBase class is the base class from which <see cref=&quot;T:System.Web.Configuration.BrowserCapabilitiesFactory&quot;></see> is derived. It is used internally at run time by the configuration system to create request-specific instances of the <see cref=&quot;T:System.Web.Configuration.HttpCapabilitiesBase&quot;></see> class, publicly accessed through the ASP.NET intrinsic <xref uid=&quot;langword_csharp_Request.Browser&quot; name=&quot;Request.Browser&quot; href=&quot;&quot;></xref> property."
  remarks: "You define browser capabilities in a .browser file. You can use the default hierarchy in the .browser file or create a custom hierarchy to define the browser capabilities."
  syntax:
    content: public class BrowserCapabilitiesFactoryBase
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  langs:
  - csharp
  name: BrowserCapabilitiesFactoryBase()
  nameWithType: BrowserCapabilitiesFactoryBase.BrowserCapabilitiesFactoryBase()
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.BrowserCapabilitiesFactoryBase()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Used internally by the configuration system to create a new instance of this class."
  syntax:
    content: public BrowserCapabilitiesFactoryBase ();
    parameters: []
  overload: System.Web.Configuration.BrowserCapabilitiesFactoryBase.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.BrowserElements
  id: BrowserElements
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  langs:
  - csharp
  name: BrowserElements
  nameWithType: BrowserCapabilitiesFactoryBase.BrowserElements
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.BrowserElements
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Used internally by the configuration system to represent a collection of information relating to various browser capabilities."
  syntax:
    content: protected System.Collections.IDictionary BrowserElements { get; }
    return:
      type: System.Collections.IDictionary
      description: "A dictionary of browser capabilities."
  overload: System.Web.Configuration.BrowserCapabilitiesFactoryBase.BrowserElements*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities(System.Collections.Specialized.NameValueCollection,System.Web.HttpBrowserCapabilities)
  id: ConfigureBrowserCapabilities(System.Collections.Specialized.NameValueCollection,System.Web.HttpBrowserCapabilities)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  langs:
  - csharp
  name: ConfigureBrowserCapabilities(NameValueCollection,HttpBrowserCapabilities)
  nameWithType: BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities(NameValueCollection,HttpBrowserCapabilities)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities(NameValueCollection,HttpBrowserCapabilities)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Used internally at run time to configure an <see cref=&quot;T:System.Web.HttpBrowserCapabilities&quot;></see> object."
  syntax:
    content: public virtual void ConfigureBrowserCapabilities (System.Collections.Specialized.NameValueCollection headers, System.Web.HttpBrowserCapabilities browserCaps);
    parameters:
    - id: headers
      type: System.Collections.Specialized.NameValueCollection
      description: "A collection of request headers."
    - id: browserCaps
      type: System.Web.HttpBrowserCapabilities
      description: "An  object."
  overload: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities(System.Collections.Specialized.NameValueCollection,System.Web.HttpBrowserCapabilities)
  id: ConfigureCustomCapabilities(System.Collections.Specialized.NameValueCollection,System.Web.HttpBrowserCapabilities)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  langs:
  - csharp
  name: ConfigureCustomCapabilities(NameValueCollection,HttpBrowserCapabilities)
  nameWithType: BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities(NameValueCollection,HttpBrowserCapabilities)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities(NameValueCollection,HttpBrowserCapabilities)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Used internally at run time to configure custom hierarchies of browser capabilities."
  remarks: "You define browser capabilities in a .browser file. You can use the default hierarchy in the .browser file or create a custom hierarchy to define the browser capabilities. The ConfigureCustomCapabilities method processes a custom hierarchy. The custom hierarchy must contain a `parentID` value in the `browser` element."
  syntax:
    content: public virtual void ConfigureCustomCapabilities (System.Collections.Specialized.NameValueCollection headers, System.Web.HttpBrowserCapabilities browserCaps);
    parameters:
    - id: headers
      type: System.Collections.Specialized.NameValueCollection
      description: "A collection of request headers."
    - id: browserCaps
      type: System.Web.HttpBrowserCapabilities
      description: "An object that specifies the capabilities of the browser."
  overload: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.IsBrowserUnknown(System.Web.Configuration.HttpCapabilitiesBase)
  id: IsBrowserUnknown(System.Web.Configuration.HttpCapabilitiesBase)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  langs:
  - csharp
  name: IsBrowserUnknown(HttpCapabilitiesBase)
  nameWithType: BrowserCapabilitiesFactoryBase.IsBrowserUnknown(HttpCapabilitiesBase)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.IsBrowserUnknown(HttpCapabilitiesBase)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Used internally by the configuration system to determine whether the browser represented by the specified <see cref=&quot;T:System.Web.HttpBrowserCapabilities&quot;></see> object does not have an available adapter."
  syntax:
    content: protected bool IsBrowserUnknown (System.Web.Configuration.HttpCapabilitiesBase browserCaps);
    parameters:
    - id: browserCaps
      type: System.Web.Configuration.HttpCapabilitiesBase
      description: "An  object."
    return:
      type: System.Boolean
      description: "To be added."
  overload: System.Web.Configuration.BrowserCapabilitiesFactoryBase.IsBrowserUnknown*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.MatchedHeaders
  id: MatchedHeaders
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  langs:
  - csharp
  name: MatchedHeaders
  nameWithType: BrowserCapabilitiesFactoryBase.MatchedHeaders
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.MatchedHeaders
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Used internally by the configuration system to represent a collection of request-header values."
  syntax:
    content: protected System.Collections.IDictionary MatchedHeaders { get; }
    return:
      type: System.Collections.IDictionary
      description: "A collection of request headers."
  overload: System.Web.Configuration.BrowserCapabilitiesFactoryBase.MatchedHeaders*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateBrowserElements(System.Collections.IDictionary)
  id: PopulateBrowserElements(System.Collections.IDictionary)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  langs:
  - csharp
  name: PopulateBrowserElements(IDictionary)
  nameWithType: BrowserCapabilitiesFactoryBase.PopulateBrowserElements(IDictionary)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateBrowserElements(IDictionary)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Used internally by the configuration system to populate a collection of browser capabilities based on the supported browser."
  syntax:
    content: protected virtual void PopulateBrowserElements (System.Collections.IDictionary dictionary);
    parameters:
    - id: dictionary
      type: System.Collections.IDictionary
      description: "A collection of key/value pairs representing the browser capabilities."
  overload: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateBrowserElements*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders(System.Collections.IDictionary)
  id: PopulateMatchedHeaders(System.Collections.IDictionary)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  langs:
  - csharp
  name: PopulateMatchedHeaders(IDictionary)
  nameWithType: BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders(IDictionary)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders(IDictionary)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Used internally by the configuration system to populate a collection of request headers based on the supported browser."
  syntax:
    content: protected virtual void PopulateMatchedHeaders (System.Collections.IDictionary dictionary);
    parameters:
    - id: dictionary
      type: System.Collections.IDictionary
      description: "A collection of key/value pairs representing the browser capabilities."
  overload: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.#ctor
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: BrowserCapabilitiesFactoryBase()
  nameWithType: BrowserCapabilitiesFactoryBase.BrowserCapabilitiesFactoryBase()
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.BrowserCapabilitiesFactoryBase()
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.BrowserElements
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: BrowserElements
  nameWithType: BrowserCapabilitiesFactoryBase.BrowserElements
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.BrowserElements
- uid: System.Collections.IDictionary
  parent: System.Collections
  isExternal: true
  name: IDictionary
  nameWithType: IDictionary
  fullName: System.Collections.IDictionary
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities(System.Collections.Specialized.NameValueCollection,System.Web.HttpBrowserCapabilities)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: ConfigureBrowserCapabilities(NameValueCollection,HttpBrowserCapabilities)
  nameWithType: BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities(NameValueCollection,HttpBrowserCapabilities)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities(NameValueCollection,HttpBrowserCapabilities)
- uid: System.Collections.Specialized.NameValueCollection
  parent: System.Collections.Specialized
  isExternal: false
  name: NameValueCollection
  nameWithType: NameValueCollection
  fullName: System.Collections.Specialized.NameValueCollection
- uid: System.Web.HttpBrowserCapabilities
  parent: System.Web
  isExternal: false
  name: HttpBrowserCapabilities
  nameWithType: HttpBrowserCapabilities
  fullName: System.Web.HttpBrowserCapabilities
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities(System.Collections.Specialized.NameValueCollection,System.Web.HttpBrowserCapabilities)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: ConfigureCustomCapabilities(NameValueCollection,HttpBrowserCapabilities)
  nameWithType: BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities(NameValueCollection,HttpBrowserCapabilities)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities(NameValueCollection,HttpBrowserCapabilities)
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.IsBrowserUnknown(System.Web.Configuration.HttpCapabilitiesBase)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: IsBrowserUnknown(HttpCapabilitiesBase)
  nameWithType: BrowserCapabilitiesFactoryBase.IsBrowserUnknown(HttpCapabilitiesBase)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.IsBrowserUnknown(HttpCapabilitiesBase)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.HttpCapabilitiesBase
  parent: System.Web.Configuration
  isExternal: false
  name: HttpCapabilitiesBase
  nameWithType: HttpCapabilitiesBase
  fullName: System.Web.Configuration.HttpCapabilitiesBase
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.MatchedHeaders
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: MatchedHeaders
  nameWithType: BrowserCapabilitiesFactoryBase.MatchedHeaders
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.MatchedHeaders
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateBrowserElements(System.Collections.IDictionary)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: PopulateBrowserElements(IDictionary)
  nameWithType: BrowserCapabilitiesFactoryBase.PopulateBrowserElements(IDictionary)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateBrowserElements(IDictionary)
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders(System.Collections.IDictionary)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: PopulateMatchedHeaders(IDictionary)
  nameWithType: BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders(IDictionary)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders(IDictionary)
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.#ctor*
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: BrowserCapabilitiesFactoryBase
  nameWithType: BrowserCapabilitiesFactoryBase.BrowserCapabilitiesFactoryBase
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.BrowserElements*
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: BrowserElements
  nameWithType: BrowserCapabilitiesFactoryBase.BrowserElements
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities*
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: ConfigureBrowserCapabilities
  nameWithType: BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities*
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: ConfigureCustomCapabilities
  nameWithType: BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.IsBrowserUnknown*
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: IsBrowserUnknown
  nameWithType: BrowserCapabilitiesFactoryBase.IsBrowserUnknown
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.MatchedHeaders*
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: MatchedHeaders
  nameWithType: BrowserCapabilitiesFactoryBase.MatchedHeaders
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateBrowserElements*
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: PopulateBrowserElements
  nameWithType: BrowserCapabilitiesFactoryBase.PopulateBrowserElements
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders*
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: PopulateMatchedHeaders
  nameWithType: BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders
