### YamlMime:ManagedReference
items:
- uid: System.Configuration.NoSettingsVersionUpgradeAttribute
  id: NoSettingsVersionUpgradeAttribute
  children:
  - System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor
  langs:
  - csharp
  name: NoSettingsVersionUpgradeAttribute
  nameWithType: NoSettingsVersionUpgradeAttribute
  fullName: System.Configuration.NoSettingsVersionUpgradeAttribute
  type: Class
  summary: "Specifies that a settings provider should disable any logic that gets invoked when an application upgrade is detected. This class cannot be inherited."
  remarks: "To create a fully featured application settings provider that supports application versioning, the provider must implement the <xref:System.Configuration.IApplicationSettingsProvider> interface. One of the members in this interface, the <xref:System.Configuration.IApplicationSettingsProvider.Upgrade%2A> method, is called to notify the provider that a new version of the application has been installed. In response, the provider is expected to perform an appropriate action, typically migrating past application settings.       The NoSettingsVersionUpgradeAttribute informs the provider to suppress the upgrade logic associated with the current settings class. Therefore, the value of the previous version of this property group should not be migrated to the new installation.      > [!NOTE] >  This attribute can only be applied to individual application settings properties."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class NoSettingsVersionUpgradeAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.NoSettingsVersionUpgradeAttribute
  langs:
  - csharp
  name: NoSettingsVersionUpgradeAttribute()
  nameWithType: NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute()
  fullName: System.Configuration.NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.NoSettingsVersionUpgradeAttribute&quot;></see> class."
  remarks: "This is the compiler-supplied default constructor for the <xref:System.Configuration.NoSettingsVersionUpgradeAttribute> class."
  syntax:
    content: public NoSettingsVersionUpgradeAttribute ();
    parameters: []
  overload: System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor
  parent: System.Configuration.NoSettingsVersionUpgradeAttribute
  isExternal: false
  name: NoSettingsVersionUpgradeAttribute()
  nameWithType: NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute()
  fullName: System.Configuration.NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute()
- uid: System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor*
  parent: System.Configuration.NoSettingsVersionUpgradeAttribute
  isExternal: false
  name: NoSettingsVersionUpgradeAttribute
  nameWithType: NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute
