### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.IdentityModelCaches
  id: IdentityModelCaches
  children:
  - System.IdentityModel.Configuration.IdentityModelCaches.#ctor
  - System.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache
  - System.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache
  langs:
  - csharp
  name: IdentityModelCaches
  nameWithType: IdentityModelCaches
  fullName: System.IdentityModel.Configuration.IdentityModelCaches
  type: Class
  summary: "Defines the caches that are configured to detect replayed tokens and to cache session tokens. This class cannot be inherited."
  remarks: "Gets and sets the configured <xref:System.IdentityModel.Tokens.TokenReplayCache> and <xref:System.IdentityModel.Tokens.SessionSecurityTokenCache>. The `Caches` property of the <xref:System.IdentityModel.Configuration.IdentityConfiguration> class and of the <xref:System.IdentityModel.Configuration.SecurityTokenHandlerConfiguration> class is an instance of IdentityModelCaches."
  syntax:
    content: public sealed class IdentityModelCaches
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Configuration.IdentityModelCaches.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  langs:
  - csharp
  name: IdentityModelCaches()
  nameWithType: IdentityModelCaches.IdentityModelCaches()
  fullName: System.IdentityModel.Configuration.IdentityModelCaches.IdentityModelCaches()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.IdentityModel.Configuration.IdentityModelCaches&quot;></see> class."
  syntax:
    content: public IdentityModelCaches ();
    parameters: []
  overload: System.IdentityModel.Configuration.IdentityModelCaches.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache
  id: SessionSecurityTokenCache
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  langs:
  - csharp
  name: SessionSecurityTokenCache
  nameWithType: IdentityModelCaches.SessionSecurityTokenCache
  fullName: System.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Gets or sets the <see cref=&quot;T:System.IdentityModel.Tokens.SessionSecurityTokenCache&quot;></see> that is used to cache the <see cref=&quot;T:System.IdentityModel.Tokens.SessionSecurityToken&quot;></see>."
  syntax:
    content: public System.IdentityModel.Tokens.SessionSecurityTokenCache SessionSecurityTokenCache { get; set; }
    return:
      type: System.IdentityModel.Tokens.SessionSecurityTokenCache
      description: "The configured session token cache."
  overload: System.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "An attempt to set the property to  occurs."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache
  id: TokenReplayCache
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  langs:
  - csharp
  name: TokenReplayCache
  nameWithType: IdentityModelCaches.TokenReplayCache
  fullName: System.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Gets or sets the <see cref=&quot;T:System.IdentityModel.Tokens.TokenReplayCache&quot;></see> that is used to determine whether tokens are replayed."
  syntax:
    content: public System.IdentityModel.Tokens.TokenReplayCache TokenReplayCache { get; set; }
    return:
      type: System.IdentityModel.Tokens.TokenReplayCache
      description: "The configured token replay cache."
  overload: System.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "An attempt to set the property to  occurs."
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.IdentityModel.Configuration.IdentityModelCaches.#ctor
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  isExternal: false
  name: IdentityModelCaches()
  nameWithType: IdentityModelCaches.IdentityModelCaches()
  fullName: System.IdentityModel.Configuration.IdentityModelCaches.IdentityModelCaches()
- uid: System.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  isExternal: false
  name: SessionSecurityTokenCache
  nameWithType: IdentityModelCaches.SessionSecurityTokenCache
  fullName: System.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache
- uid: System.IdentityModel.Tokens.SessionSecurityTokenCache
  parent: System.IdentityModel.Tokens
  isExternal: false
  name: SessionSecurityTokenCache
  nameWithType: SessionSecurityTokenCache
  fullName: System.IdentityModel.Tokens.SessionSecurityTokenCache
- uid: System.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  isExternal: false
  name: TokenReplayCache
  nameWithType: IdentityModelCaches.TokenReplayCache
  fullName: System.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache
- uid: System.IdentityModel.Tokens.TokenReplayCache
  parent: System.IdentityModel.Tokens
  isExternal: false
  name: TokenReplayCache
  nameWithType: TokenReplayCache
  fullName: System.IdentityModel.Tokens.TokenReplayCache
- uid: System.IdentityModel.Configuration.IdentityModelCaches.#ctor*
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  isExternal: false
  name: IdentityModelCaches
  nameWithType: IdentityModelCaches.IdentityModelCaches
- uid: System.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache*
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  isExternal: false
  name: SessionSecurityTokenCache
  nameWithType: IdentityModelCaches.SessionSecurityTokenCache
- uid: System.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache*
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  isExternal: false
  name: TokenReplayCache
  nameWithType: IdentityModelCaches.TokenReplayCache
