### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.ConnectionManagementSection
  id: ConnectionManagementSection
  children:
  - System.Net.Configuration.ConnectionManagementSection.#ctor
  - System.Net.Configuration.ConnectionManagementSection.ConnectionManagement
  - System.Net.Configuration.ConnectionManagementSection.Properties
  langs:
  - csharp
  name: ConnectionManagementSection
  nameWithType: ConnectionManagementSection
  fullName: System.Net.Configuration.ConnectionManagementSection
  type: Class
  summary: "Represents the configuration section for connection management. This class cannot be inherited."
  remarks: "This class corresponds to the [\\<connectionManagement> Element (Network Settings)](../Topic/%3CconnectionManagement%3E%20Element%20\\(Network%20Settings\\).md) configuration element.  \n  \n This class is used to access information about the number of simultaneous connections allowed between the local computer and a remote computer.  \n  \n This class provides programmatic access to information that can be stored in configuration files."
  syntax:
    content: 'public sealed class ConnectionManagementSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.ConnectionManagementSection.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.ConnectionManagementSection
  langs:
  - csharp
  name: ConnectionManagementSection()
  nameWithType: ConnectionManagementSection.ConnectionManagementSection()
  fullName: System.Net.Configuration.ConnectionManagementSection.ConnectionManagementSection()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Net.Configuration.ConnectionManagementSection&quot;></see> class."
  syntax:
    content: public ConnectionManagementSection ();
    parameters: []
  overload: System.Net.Configuration.ConnectionManagementSection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.ConnectionManagementSection.ConnectionManagement
  id: ConnectionManagement
  parent: System.Net.Configuration.ConnectionManagementSection
  langs:
  - csharp
  name: ConnectionManagement
  nameWithType: ConnectionManagementSection.ConnectionManagement
  fullName: System.Net.Configuration.ConnectionManagementSection.ConnectionManagement
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Gets the collection of connection management objects in the section."
  remarks: "The <xref:System.Net.Configuration.ConnectionManagementElementCollection> returned by this property contains one <xref:System.Net.Configuration.ConnectionManagementElement> for each `connectionManagement` element in the configuration file."
  syntax:
    content: public System.Net.Configuration.ConnectionManagementElementCollection ConnectionManagement { get; }
    return:
      type: System.Net.Configuration.ConnectionManagementElementCollection
      description: "A <see cref=&quot;T:System.Net.Configuration.ConnectionManagementElementCollection&quot;></see> that contains the connection management information for the local computer."
  overload: System.Net.Configuration.ConnectionManagementSection.ConnectionManagement*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.ConnectionManagementSection.Properties
  id: Properties
  parent: System.Net.Configuration.ConnectionManagementSection
  langs:
  - csharp
  name: Properties
  nameWithType: ConnectionManagementSection.Properties
  fullName: System.Net.Configuration.ConnectionManagementSection.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Net.Configuration.ConnectionManagementSection.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Net.Configuration.ConnectionManagementSection.#ctor
  parent: System.Net.Configuration.ConnectionManagementSection
  isExternal: false
  name: ConnectionManagementSection()
  nameWithType: ConnectionManagementSection.ConnectionManagementSection()
  fullName: System.Net.Configuration.ConnectionManagementSection.ConnectionManagementSection()
- uid: System.Net.Configuration.ConnectionManagementSection.ConnectionManagement
  parent: System.Net.Configuration.ConnectionManagementSection
  isExternal: false
  name: ConnectionManagement
  nameWithType: ConnectionManagementSection.ConnectionManagement
  fullName: System.Net.Configuration.ConnectionManagementSection.ConnectionManagement
- uid: System.Net.Configuration.ConnectionManagementElementCollection
  parent: System.Net.Configuration
  isExternal: false
  name: ConnectionManagementElementCollection
  nameWithType: ConnectionManagementElementCollection
  fullName: System.Net.Configuration.ConnectionManagementElementCollection
- uid: System.Net.Configuration.ConnectionManagementSection.Properties
  parent: System.Net.Configuration.ConnectionManagementSection
  isExternal: false
  name: Properties
  nameWithType: ConnectionManagementSection.Properties
  fullName: System.Net.Configuration.ConnectionManagementSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.ConnectionManagementSection.#ctor*
  parent: System.Net.Configuration.ConnectionManagementSection
  isExternal: false
  name: ConnectionManagementSection
  nameWithType: ConnectionManagementSection.ConnectionManagementSection
- uid: System.Net.Configuration.ConnectionManagementSection.ConnectionManagement*
  parent: System.Net.Configuration.ConnectionManagementSection
  isExternal: false
  name: ConnectionManagement
  nameWithType: ConnectionManagementSection.ConnectionManagement
- uid: System.Net.Configuration.ConnectionManagementSection.Properties*
  parent: System.Net.Configuration.ConnectionManagementSection
  isExternal: false
  name: Properties
  nameWithType: ConnectionManagementSection.Properties
