### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Routing.Configuration.FilterType
  id: FilterType
  children:
  - System.ServiceModel.Routing.Configuration.FilterType.Action
  - System.ServiceModel.Routing.Configuration.FilterType.And
  - System.ServiceModel.Routing.Configuration.FilterType.Custom
  - System.ServiceModel.Routing.Configuration.FilterType.EndpointAddress
  - System.ServiceModel.Routing.Configuration.FilterType.EndpointName
  - System.ServiceModel.Routing.Configuration.FilterType.MatchAll
  - System.ServiceModel.Routing.Configuration.FilterType.PrefixEndpointAddress
  - System.ServiceModel.Routing.Configuration.FilterType.XPath
  langs:
  - csharp
  name: FilterType
  nameWithType: FilterType
  fullName: System.ServiceModel.Routing.Configuration.FilterType
  type: Enum
  summary: "Specifies the type of filter to use when routing messages."
  remarks: '[!INCLUDE[crabout](~/add/includes/crabout-md.md)] using FilterType, see <xref:System.ServiceModel.Routing.Configuration.FilterElement.FilterData%2A>.'
  syntax:
    content: public enum FilterType
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.FilterType.Action
  id: Action
  parent: System.ServiceModel.Routing.Configuration.FilterType
  langs:
  - csharp
  name: Action
  nameWithType: FilterType.Action
  fullName: System.ServiceModel.Routing.Configuration.FilterType.Action
  type: Field
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Use <see cref=&quot;T:System.ServiceModel.Dispatcher.ActionMessageFilter&quot;></see> to filter on an action."
  syntax:
    content: Action
    return:
      type: System.ServiceModel.Routing.Configuration.FilterType
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.FilterType.And
  id: And
  parent: System.ServiceModel.Routing.Configuration.FilterType
  langs:
  - csharp
  name: And
  nameWithType: FilterType.And
  fullName: System.ServiceModel.Routing.Configuration.FilterType.And
  type: Field
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Use <see cref=&quot;T:System.ServiceModel.Dispatcher.StrictAndMessageFilter&quot;></see> to filter on two message filters, ANDed together."
  syntax:
    content: And
    return:
      type: System.ServiceModel.Routing.Configuration.FilterType
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.FilterType.Custom
  id: Custom
  parent: System.ServiceModel.Routing.Configuration.FilterType
  langs:
  - csharp
  name: Custom
  nameWithType: FilterType.Custom
  fullName: System.ServiceModel.Routing.Configuration.FilterType.Custom
  type: Field
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Use a user-defined filter."
  syntax:
    content: Custom
    return:
      type: System.ServiceModel.Routing.Configuration.FilterType
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.FilterType.EndpointAddress
  id: EndpointAddress
  parent: System.ServiceModel.Routing.Configuration.FilterType
  langs:
  - csharp
  name: EndpointAddress
  nameWithType: FilterType.EndpointAddress
  fullName: System.ServiceModel.Routing.Configuration.FilterType.EndpointAddress
  type: Field
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Use <see cref=&quot;T:System.ServiceModel.Dispatcher.EndpointAddressMessageFilter&quot;></see> with &lt;xref:System.ServiceModel.Dispatcher.EndpointAddressMessageFilter.IncludeHostNameInComparison%2A&gt; set to **false** to filter on the address."
  syntax:
    content: EndpointAddress
    return:
      type: System.ServiceModel.Routing.Configuration.FilterType
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.FilterType.EndpointName
  id: EndpointName
  parent: System.ServiceModel.Routing.Configuration.FilterType
  langs:
  - csharp
  name: EndpointName
  nameWithType: FilterType.EndpointName
  fullName: System.ServiceModel.Routing.Configuration.FilterType.EndpointName
  type: Field
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Use the <see cref=&quot;T:System.ServiceModel.Dispatcher.EndpointNameMessageFilter&quot;></see> to filter on the name of the service endpoint."
  syntax:
    content: EndpointName
    return:
      type: System.ServiceModel.Routing.Configuration.FilterType
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.FilterType.MatchAll
  id: MatchAll
  parent: System.ServiceModel.Routing.Configuration.FilterType
  langs:
  - csharp
  name: MatchAll
  nameWithType: FilterType.MatchAll
  fullName: System.ServiceModel.Routing.Configuration.FilterType.MatchAll
  type: Field
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Use the <see cref=&quot;T:System.ServiceModel.Dispatcher.MatchAllMessageFilter&quot;></see> to match all messages."
  syntax:
    content: MatchAll
    return:
      type: System.ServiceModel.Routing.Configuration.FilterType
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.FilterType.PrefixEndpointAddress
  id: PrefixEndpointAddress
  parent: System.ServiceModel.Routing.Configuration.FilterType
  langs:
  - csharp
  name: PrefixEndpointAddress
  nameWithType: FilterType.PrefixEndpointAddress
  fullName: System.ServiceModel.Routing.Configuration.FilterType.PrefixEndpointAddress
  type: Field
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Use <see cref=&quot;T:System.ServiceModel.Dispatcher.PrefixEndpointAddressMessageFilter&quot;></see> with &lt;xref:System.ServiceModel.Dispatcher.PrefixEndpointAddressMessageFilter.IncludeHostNameInComparison%2A&gt; set to **false** to filter on the address using longest prefix matching."
  syntax:
    content: PrefixEndpointAddress
    return:
      type: System.ServiceModel.Routing.Configuration.FilterType
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.FilterType.XPath
  id: XPath
  parent: System.ServiceModel.Routing.Configuration.FilterType
  langs:
  - csharp
  name: XPath
  nameWithType: FilterType.XPath
  fullName: System.ServiceModel.Routing.Configuration.FilterType.XPath
  type: Field
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Use the <see cref=&quot;T:System.ServiceModel.Dispatcher.XPathMessageFilter&quot;></see> to filter on an XPath expression."
  syntax:
    content: XPath
    return:
      type: System.ServiceModel.Routing.Configuration.FilterType
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.ServiceModel.Routing.Configuration.FilterType.Action
  parent: System.ServiceModel.Routing.Configuration.FilterType
  isExternal: false
  name: Action
  nameWithType: FilterType.Action
  fullName: System.ServiceModel.Routing.Configuration.FilterType.Action
- uid: System.ServiceModel.Routing.Configuration.FilterType
  parent: System.ServiceModel.Routing.Configuration
  isExternal: false
  name: FilterType
  nameWithType: FilterType
  fullName: System.ServiceModel.Routing.Configuration.FilterType
- uid: System.ServiceModel.Routing.Configuration.FilterType.And
  parent: System.ServiceModel.Routing.Configuration.FilterType
  isExternal: false
  name: And
  nameWithType: FilterType.And
  fullName: System.ServiceModel.Routing.Configuration.FilterType.And
- uid: System.ServiceModel.Routing.Configuration.FilterType.Custom
  parent: System.ServiceModel.Routing.Configuration.FilterType
  isExternal: false
  name: Custom
  nameWithType: FilterType.Custom
  fullName: System.ServiceModel.Routing.Configuration.FilterType.Custom
- uid: System.ServiceModel.Routing.Configuration.FilterType.EndpointAddress
  parent: System.ServiceModel.Routing.Configuration.FilterType
  isExternal: false
  name: EndpointAddress
  nameWithType: FilterType.EndpointAddress
  fullName: System.ServiceModel.Routing.Configuration.FilterType.EndpointAddress
- uid: System.ServiceModel.Routing.Configuration.FilterType.EndpointName
  parent: System.ServiceModel.Routing.Configuration.FilterType
  isExternal: false
  name: EndpointName
  nameWithType: FilterType.EndpointName
  fullName: System.ServiceModel.Routing.Configuration.FilterType.EndpointName
- uid: System.ServiceModel.Routing.Configuration.FilterType.MatchAll
  parent: System.ServiceModel.Routing.Configuration.FilterType
  isExternal: false
  name: MatchAll
  nameWithType: FilterType.MatchAll
  fullName: System.ServiceModel.Routing.Configuration.FilterType.MatchAll
- uid: System.ServiceModel.Routing.Configuration.FilterType.PrefixEndpointAddress
  parent: System.ServiceModel.Routing.Configuration.FilterType
  isExternal: false
  name: PrefixEndpointAddress
  nameWithType: FilterType.PrefixEndpointAddress
  fullName: System.ServiceModel.Routing.Configuration.FilterType.PrefixEndpointAddress
- uid: System.ServiceModel.Routing.Configuration.FilterType.XPath
  parent: System.ServiceModel.Routing.Configuration.FilterType
  isExternal: false
  name: XPath
  nameWithType: FilterType.XPath
  fullName: System.ServiceModel.Routing.Configuration.FilterType.XPath
