### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ComPersistableTypeElement
  id: ComPersistableTypeElement
  children:
  - System.ServiceModel.Configuration.ComPersistableTypeElement.#ctor
  - System.ServiceModel.Configuration.ComPersistableTypeElement.#ctor(System.String)
  - System.ServiceModel.Configuration.ComPersistableTypeElement.ID
  - System.ServiceModel.Configuration.ComPersistableTypeElement.Name
  - System.ServiceModel.Configuration.ComPersistableTypeElement.Properties
  langs:
  - csharp
  name: ComPersistableTypeElement
  nameWithType: ComPersistableTypeElement
  fullName: System.ServiceModel.Configuration.ComPersistableTypeElement
  type: Class
  summary: "Specifies all the persistable types.This class cannot be inherited."
  syntax:
    content: 'public sealed class ComPersistableTypeElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ComPersistableTypeElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ComPersistableTypeElement
  langs:
  - csharp
  name: ComPersistableTypeElement()
  nameWithType: ComPersistableTypeElement.ComPersistableTypeElement()
  fullName: System.ServiceModel.Configuration.ComPersistableTypeElement.ComPersistableTypeElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.ComPersistableTypeElement&quot;></see> class."
  syntax:
    content: public ComPersistableTypeElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.ComPersistableTypeElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ComPersistableTypeElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.Configuration.ComPersistableTypeElement
  langs:
  - csharp
  name: ComPersistableTypeElement(String)
  nameWithType: ComPersistableTypeElement.ComPersistableTypeElement(String)
  fullName: System.ServiceModel.Configuration.ComPersistableTypeElement.ComPersistableTypeElement(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.ComPersistableTypeElement&quot;></see> class."
  syntax:
    content: public ComPersistableTypeElement (string ID);
    parameters:
    - id: ID
      type: System.String
      description: "A unique identifier for a persistable type."
  overload: System.ServiceModel.Configuration.ComPersistableTypeElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ComPersistableTypeElement.ID
  id: ID
  parent: System.ServiceModel.Configuration.ComPersistableTypeElement
  langs:
  - csharp
  name: ID
  nameWithType: ComPersistableTypeElement.ID
  fullName: System.ServiceModel.Configuration.ComPersistableTypeElement.ID
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets a unique identifier for a persistable type."
  syntax:
    content: public string ID { get; set; }
    return:
      type: System.String
      description: "A unique identifier for a persistable type."
  overload: System.ServiceModel.Configuration.ComPersistableTypeElement.ID*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ComPersistableTypeElement.Name
  id: Name
  parent: System.ServiceModel.Configuration.ComPersistableTypeElement
  langs:
  - csharp
  name: Name
  nameWithType: ComPersistableTypeElement.Name
  fullName: System.ServiceModel.Configuration.ComPersistableTypeElement.Name
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets the name of the persistable type."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "A name of the persistable type."
  overload: System.ServiceModel.Configuration.ComPersistableTypeElement.Name*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ComPersistableTypeElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ComPersistableTypeElement
  langs:
  - csharp
  name: Properties
  nameWithType: ComPersistableTypeElement.Properties
  fullName: System.ServiceModel.Configuration.ComPersistableTypeElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.ComPersistableTypeElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.ComPersistableTypeElement.#ctor
  parent: System.ServiceModel.Configuration.ComPersistableTypeElement
  isExternal: false
  name: ComPersistableTypeElement()
  nameWithType: ComPersistableTypeElement.ComPersistableTypeElement()
  fullName: System.ServiceModel.Configuration.ComPersistableTypeElement.ComPersistableTypeElement()
- uid: System.ServiceModel.Configuration.ComPersistableTypeElement.#ctor(System.String)
  parent: System.ServiceModel.Configuration.ComPersistableTypeElement
  isExternal: false
  name: ComPersistableTypeElement(String)
  nameWithType: ComPersistableTypeElement.ComPersistableTypeElement(String)
  fullName: System.ServiceModel.Configuration.ComPersistableTypeElement.ComPersistableTypeElement(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.ComPersistableTypeElement.ID
  parent: System.ServiceModel.Configuration.ComPersistableTypeElement
  isExternal: false
  name: ID
  nameWithType: ComPersistableTypeElement.ID
  fullName: System.ServiceModel.Configuration.ComPersistableTypeElement.ID
- uid: System.ServiceModel.Configuration.ComPersistableTypeElement.Name
  parent: System.ServiceModel.Configuration.ComPersistableTypeElement
  isExternal: false
  name: Name
  nameWithType: ComPersistableTypeElement.Name
  fullName: System.ServiceModel.Configuration.ComPersistableTypeElement.Name
- uid: System.ServiceModel.Configuration.ComPersistableTypeElement.Properties
  parent: System.ServiceModel.Configuration.ComPersistableTypeElement
  isExternal: false
  name: Properties
  nameWithType: ComPersistableTypeElement.Properties
  fullName: System.ServiceModel.Configuration.ComPersistableTypeElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ComPersistableTypeElement.#ctor*
  parent: System.ServiceModel.Configuration.ComPersistableTypeElement
  isExternal: false
  name: ComPersistableTypeElement
  nameWithType: ComPersistableTypeElement.ComPersistableTypeElement
- uid: System.ServiceModel.Configuration.ComPersistableTypeElement.ID*
  parent: System.ServiceModel.Configuration.ComPersistableTypeElement
  isExternal: false
  name: ID
  nameWithType: ComPersistableTypeElement.ID
- uid: System.ServiceModel.Configuration.ComPersistableTypeElement.Name*
  parent: System.ServiceModel.Configuration.ComPersistableTypeElement
  isExternal: false
  name: Name
  nameWithType: ComPersistableTypeElement.Name
- uid: System.ServiceModel.Configuration.ComPersistableTypeElement.Properties*
  parent: System.ServiceModel.Configuration.ComPersistableTypeElement
  isExternal: false
  name: Properties
  nameWithType: ComPersistableTypeElement.Properties
