### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.CompatibleFrameworkMissingException
  id: CompatibleFrameworkMissingException
  children:
  - System.Deployment.Application.CompatibleFrameworkMissingException.#ctor
  - System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String)
  - System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String,System.Exception)
  - System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks
  - System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  langs:
  - csharp
  name: CompatibleFrameworkMissingException
  nameWithType: CompatibleFrameworkMissingException
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException
  type: Class
  summary: "This exception is thrown when a version of the .NET Framework that is compatible with this application cannot be found."
  syntax:
    content: 'public class CompatibleFrameworkMissingException : System.Deployment.Application.DependentPlatformMissingException'
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Deployment.Application.DeploymentException
  - System.Deployment.Application.DependentPlatformMissingException
  implements: []
  inheritedMembers:
  - System.Deployment.Application.DependentPlatformMissingException.SupportUrl
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: CompatibleFrameworkMissingException()
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException()
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Deployment.Application.CompatibleFrameworkMissingException&quot;></see> class with a system-supplied message that describes the error."
  remarks: "This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as &quot;No compatible framework found.&quot; This message takes into account the current system culture.       The following table shows the initial property values for an instance of <xref:System.Deployment.Application.CompatibleFrameworkMissingException>.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|`null`.|   |<xref:System.Exception.Message%2A>|The localized error message string.|"
  syntax:
    content: public CompatibleFrameworkMissingException ();
    parameters: []
  overload: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: CompatibleFrameworkMissingException(String)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Deployment.Application.CompatibleFrameworkMissingException&quot;></see> class with a specified message that describes the error."
  remarks: "The following table shows the initial property values for an instance of <xref:System.Deployment.Application.CompatibleFrameworkMissingException>.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|`null`.|   |<xref:System.Exception.Message%2A>|The error message string specified in `message`.|"
  syntax:
    content: public CompatibleFrameworkMissingException (string message);
    parameters:
    - id: message
      type: System.String
      description: "The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture."
  overload: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Deployment.Application.CompatibleFrameworkMissingException&quot;></see> class with serialized data."
  remarks: "This constructor is called during deserialization to reconstitute the exception object transmitted over a stream."
  syntax:
    content: protected CompatibleFrameworkMissingException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: "The object that holds the serialized object data."
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: "The contextual information about the source or destination."
  overload: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: CompatibleFrameworkMissingException(String,Exception)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String,Exception)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String,Exception)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Deployment.Application.CompatibleFrameworkMissingException&quot;></see> class with a specified error message and a reference to the inner exception that is the cause of this exception."
  remarks: "An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.       The following table shows the initial property values for an instance of <xref:System.Deployment.Application.CompatibleFrameworkMissingException>.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|`null`.|   |<xref:System.Exception.Message%2A>|The error message string specified in `message`.|"
  syntax:
    content: public CompatibleFrameworkMissingException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture."
    - id: innerException
      type: System.Exception
      description: "The exception that is the cause of the current exception. If the `innerException` parameter is not , the current exception is raised in a  block that handles the inner exception."
  overload: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks
  id: CompatibleFrameworks
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: CompatibleFrameworks
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworks
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Gets a list of .NET Framework versions where this application can install and run."
  syntax:
    content: public System.Deployment.Application.CompatibleFrameworks CompatibleFrameworks { get; }
    return:
      type: System.Deployment.Application.CompatibleFrameworks
      description: "A list of .NET Framework versions where this application can install and run."
  overload: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: CompatibleFrameworkMissingException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData(SerializationInfo,StreamingContext)
  type: Method
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Deployment.Application.CompatibleFrameworkMissingException&quot;></see> class with serialized data."
  remarks: "This constructor is called during deserialization to reconstitute the exception object transmitted over a stream."
  syntax:
    content: public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "The object that holds the serialized object data."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "The contextual information about the source or destination."
  overload: System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: System.Deployment.Application.DependentPlatformMissingException
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworkMissingException()
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException()
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException()
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String)
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworkMissingException(String)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworkMissingException(String,Exception)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String,Exception)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworks
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworks
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks
- uid: System.Deployment.Application.CompatibleFrameworks
  parent: System.Deployment.Application
  isExternal: false
  name: CompatibleFrameworks
  nameWithType: CompatibleFrameworks
  fullName: System.Deployment.Application.CompatibleFrameworks
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: CompatibleFrameworkMissingException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData(SerializationInfo,StreamingContext)
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor*
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworkMissingException
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks*
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworks
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworks
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData*
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: GetObjectData
  nameWithType: CompatibleFrameworkMissingException.GetObjectData
