### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ExtensionElementCollection
  id: ExtensionElementCollection
  children:
  - System.ServiceModel.Configuration.ExtensionElementCollection.#ctor
  - System.ServiceModel.Configuration.ExtensionElementCollection.BaseAdd(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ExtensionElementCollection.BaseAdd(System.Int32,System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ExtensionElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ExtensionElementCollection.ThrowOnDuplicate
  langs:
  - csharp
  name: ExtensionElementCollection
  nameWithType: ExtensionElementCollection
  fullName: System.ServiceModel.Configuration.ExtensionElementCollection
  type: Class
  summary: "Represents a collection of <see cref=&quot;T:System.ServiceModel.Configuration.ExtensionElement&quot;></see> instances."
  syntax:
    content: >-
      [System.Configuration.ConfigurationCollection(typeof(System.ServiceModel.Configuration.ExtensionElement), CollectionType=System.Configuration.ConfigurationElementCollectionType.BasicMap)]

      public class ExtensionElementCollection : System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection<System.ServiceModel.Configuration.ExtensionElement>
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationElementCollection
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.AddElementName
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Configuration.ConfigurationElement,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.BaseClear
  - System.Configuration.ConfigurationElementCollection.BaseGet(System.Int32)
  - System.Configuration.ConfigurationElementCollection.BaseGet(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseGetAllKeys
  - System.Configuration.ConfigurationElementCollection.BaseGetKey(System.Int32)
  - System.Configuration.ConfigurationElementCollection.BaseIndexOf(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseIsRemoved(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseRemove(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseRemoveAt(System.Int32)
  - System.Configuration.ConfigurationElementCollection.ClearElementName
  - System.Configuration.ConfigurationElementCollection.CopyTo(System.Configuration.ConfigurationElement[],System.Int32)
  - System.Configuration.ConfigurationElementCollection.Count
  - System.Configuration.ConfigurationElementCollection.CreateNewElement(System.String)
  - System.Configuration.ConfigurationElementCollection.EmitClear
  - System.Configuration.ConfigurationElementCollection.Equals(System.Object)
  - System.Configuration.ConfigurationElementCollection.GetEnumerator
  - System.Configuration.ConfigurationElementCollection.GetHashCode
  - System.Configuration.ConfigurationElementCollection.IsElementName(System.String)
  - System.Configuration.ConfigurationElementCollection.IsElementRemovable(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.IsModified
  - System.Configuration.ConfigurationElementCollection.IsReadOnly
  - System.Configuration.ConfigurationElementCollection.IsSynchronized
  - System.Configuration.ConfigurationElementCollection.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElementCollection.RemoveElementName
  - System.Configuration.ConfigurationElementCollection.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.ResetModified
  - System.Configuration.ConfigurationElementCollection.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.SetReadOnly
  - System.Configuration.ConfigurationElementCollection.SyncRoot
  - System.Configuration.ConfigurationElementCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  - System.Configuration.ConfigurationElementCollection.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Add(`0)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Clear
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.CollectionType
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.ContainsKey(System.Object)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.CopyTo(`0[],System.Int32)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.ElementName
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.IndexOf(`0)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Item(System.Int32)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Item(System.Object)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Remove(`0)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.RemoveAt(System.Int32)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.RemoveAt(System.Object)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ExtensionElementCollection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ExtensionElementCollection
  langs:
  - csharp
  name: ExtensionElementCollection()
  nameWithType: ExtensionElementCollection.ExtensionElementCollection()
  fullName: System.ServiceModel.Configuration.ExtensionElementCollection.ExtensionElementCollection()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.ExtensionElementCollection&quot;></see> class."
  syntax:
    content: public ExtensionElementCollection ();
    parameters: []
  overload: System.ServiceModel.Configuration.ExtensionElementCollection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ExtensionElementCollection.BaseAdd(System.Configuration.ConfigurationElement)
  id: BaseAdd(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Configuration.ExtensionElementCollection
  langs:
  - csharp
  name: BaseAdd(ConfigurationElement)
  nameWithType: ExtensionElementCollection.BaseAdd(ConfigurationElement)
  fullName: System.ServiceModel.Configuration.ExtensionElementCollection.BaseAdd(ConfigurationElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Adds a configuration element to the <see cref=&quot;T:System.ServiceModel.Configuration.ExtensionElementCollection&quot;></see>."
  remarks: "When adding, an element is considered a duplicate only if the keys are identical but the values are different. Elements with identical keys and values are accepted silently because the elements do not compete. However, an element with an identical key but a different value cannot be added because there is no logic to determine which of the competing values should be honored."
  syntax:
    content: protected override void BaseAdd (System.Configuration.ConfigurationElement element);
    parameters:
    - id: element
      type: System.Configuration.ConfigurationElement
      description: "The  to add."
  overload: System.ServiceModel.Configuration.ExtensionElementCollection.BaseAdd*
  exceptions:
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "An extension with the same name or type as element already exists in the collection."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ExtensionElementCollection.BaseAdd(System.Int32,System.Configuration.ConfigurationElement)
  id: BaseAdd(System.Int32,System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Configuration.ExtensionElementCollection
  langs:
  - csharp
  name: BaseAdd(Int32,ConfigurationElement)
  nameWithType: ExtensionElementCollection.BaseAdd(Int32,ConfigurationElement)
  fullName: System.ServiceModel.Configuration.ExtensionElementCollection.BaseAdd(Int32,ConfigurationElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Adds a configuration element to the <see cref=&quot;T:System.ServiceModel.Configuration.ExtensionElementCollection&quot;></see>, at the specified location."
  remarks: "When adding, an element is considered a duplicate only if the keys are identical but the values are different. Elements with identical keys and values are accepted silently because the elements do not compete. However, an element with an identical key but a different value cannot be added because there is no logic to determine which of the competing values should be honored."
  syntax:
    content: protected override void BaseAdd (int index, System.Configuration.ConfigurationElement element);
    parameters:
    - id: index
      type: System.Int32
      description: "The index location at which to add `element`."
    - id: element
      type: System.Configuration.ConfigurationElement
      description: "The  to add."
  overload: System.ServiceModel.Configuration.ExtensionElementCollection.BaseAdd*
  exceptions:
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "An extension with the same name or type as element already exists in the collection."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ExtensionElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  id: GetElementKey(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Configuration.ExtensionElementCollection
  langs:
  - csharp
  name: GetElementKey(ConfigurationElement)
  nameWithType: ExtensionElementCollection.GetElementKey(ConfigurationElement)
  fullName: System.ServiceModel.Configuration.ExtensionElementCollection.GetElementKey(ConfigurationElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets the element key for the specified configuration element."
  syntax:
    content: protected override object GetElementKey (System.Configuration.ConfigurationElement element);
    parameters:
    - id: element
      type: System.Configuration.ConfigurationElement
      description: "The  to return the key for."
    return:
      type: System.Object
      description: "To be added."
  overload: System.ServiceModel.Configuration.ExtensionElementCollection.GetElementKey*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "\n    element is  or empty."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ExtensionElementCollection.ThrowOnDuplicate
  id: ThrowOnDuplicate
  parent: System.ServiceModel.Configuration.ExtensionElementCollection
  langs:
  - csharp
  name: ThrowOnDuplicate
  nameWithType: ExtensionElementCollection.ThrowOnDuplicate
  fullName: System.ServiceModel.Configuration.ExtensionElementCollection.ThrowOnDuplicate
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets a value indicating whether an attempt to add a duplicate <see cref=&quot;T:System.Configuration.ConfigurationElement&quot;></see> to the <see cref=&quot;T:System.ServiceModel.Configuration.ExtensionElementCollection&quot;></see> will cause an exception to be thrown."
  syntax:
    content: protected override bool ThrowOnDuplicate { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if an attempt to add a duplicate <see cref=&quot;T:System.Configuration.ConfigurationElement&quot;></see> to the <see cref=&quot;T:System.ServiceModel.Configuration.ExtensionElementCollection&quot;></see> will cause an exception to be thrown; otherwise, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>."
  overload: System.ServiceModel.Configuration.ExtensionElementCollection.ThrowOnDuplicate*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection<System.ServiceModel.Configuration.ExtensionElement>
- uid: System.ServiceModel.Configuration.ExtensionElementCollection.#ctor
  parent: System.ServiceModel.Configuration.ExtensionElementCollection
  isExternal: false
  name: ExtensionElementCollection()
  nameWithType: ExtensionElementCollection.ExtensionElementCollection()
  fullName: System.ServiceModel.Configuration.ExtensionElementCollection.ExtensionElementCollection()
- uid: System.ServiceModel.Configuration.ExtensionElementCollection.BaseAdd(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Configuration.ExtensionElementCollection
  isExternal: false
  name: BaseAdd(ConfigurationElement)
  nameWithType: ExtensionElementCollection.BaseAdd(ConfigurationElement)
  fullName: System.ServiceModel.Configuration.ExtensionElementCollection.BaseAdd(ConfigurationElement)
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.ExtensionElementCollection.BaseAdd(System.Int32,System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Configuration.ExtensionElementCollection
  isExternal: false
  name: BaseAdd(Int32,ConfigurationElement)
  nameWithType: ExtensionElementCollection.BaseAdd(Int32,ConfigurationElement)
  fullName: System.ServiceModel.Configuration.ExtensionElementCollection.BaseAdd(Int32,ConfigurationElement)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Configuration.ExtensionElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Configuration.ExtensionElementCollection
  isExternal: false
  name: GetElementKey(ConfigurationElement)
  nameWithType: ExtensionElementCollection.GetElementKey(ConfigurationElement)
  fullName: System.ServiceModel.Configuration.ExtensionElementCollection.GetElementKey(ConfigurationElement)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Configuration.ExtensionElementCollection.ThrowOnDuplicate
  parent: System.ServiceModel.Configuration.ExtensionElementCollection
  isExternal: false
  name: ThrowOnDuplicate
  nameWithType: ExtensionElementCollection.ThrowOnDuplicate
  fullName: System.ServiceModel.Configuration.ExtensionElementCollection.ThrowOnDuplicate
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.ExtensionElementCollection.#ctor*
  parent: System.ServiceModel.Configuration.ExtensionElementCollection
  isExternal: false
  name: ExtensionElementCollection
  nameWithType: ExtensionElementCollection.ExtensionElementCollection
- uid: System.ServiceModel.Configuration.ExtensionElementCollection.BaseAdd*
  parent: System.ServiceModel.Configuration.ExtensionElementCollection
  isExternal: false
  name: BaseAdd
  nameWithType: ExtensionElementCollection.BaseAdd
- uid: System.ServiceModel.Configuration.ExtensionElementCollection.GetElementKey*
  parent: System.ServiceModel.Configuration.ExtensionElementCollection
  isExternal: false
  name: GetElementKey
  nameWithType: ExtensionElementCollection.GetElementKey
- uid: System.ServiceModel.Configuration.ExtensionElementCollection.ThrowOnDuplicate*
  parent: System.ServiceModel.Configuration.ExtensionElementCollection
  isExternal: false
  name: ThrowOnDuplicate
  nameWithType: ExtensionElementCollection.ThrowOnDuplicate
