### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsPropertyIsReadOnlyException
  id: SettingsPropertyIsReadOnlyException
  children:
  - System.Configuration.SettingsPropertyIsReadOnlyException.#ctor
  - System.Configuration.SettingsPropertyIsReadOnlyException.#ctor(System.String)
  - System.Configuration.SettingsPropertyIsReadOnlyException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Configuration.SettingsPropertyIsReadOnlyException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: SettingsPropertyIsReadOnlyException
  nameWithType: SettingsPropertyIsReadOnlyException
  fullName: System.Configuration.SettingsPropertyIsReadOnlyException
  type: Class
  summary: "Provides an exception for read-only <see cref=&quot;T:System.Configuration.SettingsProperty&quot;></see> objects."
  remarks: "This exception is thrown by the <xref:System.Configuration.SettingsBase> class when attempting to change the value of a <xref:System.Configuration.SettingsPropertyValue> that was marked as being read-only."
  syntax:
    content: 'public class SettingsPropertyIsReadOnlyException : Exception'
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor
  id: '#ctor'
  parent: System.Configuration.SettingsPropertyIsReadOnlyException
  langs:
  - csharp
  name: SettingsPropertyIsReadOnlyException()
  nameWithType: SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException()
  fullName: System.Configuration.SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.SettingsPropertyIsReadOnlyException&quot;></see> class."
  syntax:
    content: public SettingsPropertyIsReadOnlyException ();
    parameters: []
  overload: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsPropertyIsReadOnlyException
  langs:
  - csharp
  name: SettingsPropertyIsReadOnlyException(String)
  nameWithType: SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(String)
  fullName: System.Configuration.SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.SettingsPropertyIsReadOnlyException&quot;></see> class based on a supplied parameter."
  syntax:
    content: public SettingsPropertyIsReadOnlyException (string message);
    parameters:
    - id: message
      type: System.String
      description: "A string containing an exception message."
  overload: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Configuration.SettingsPropertyIsReadOnlyException
  langs:
  - csharp
  name: SettingsPropertyIsReadOnlyException(SerializationInfo,StreamingContext)
  nameWithType: SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(SerializationInfo,StreamingContext)
  fullName: System.Configuration.SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.SettingsPropertyIsReadOnlyException&quot;></see> class based on the supplied parameters."
  syntax:
    content: protected SettingsPropertyIsReadOnlyException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "The  object that holds the serialized object data about the exception being thrown."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "The <xref:System.Runtime.Serialization.StreamingContext> object that contains contextual information about the source or destination of the serialized stream."
  overload: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Configuration.SettingsPropertyIsReadOnlyException
  langs:
  - csharp
  name: SettingsPropertyIsReadOnlyException(String,Exception)
  nameWithType: SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(String,Exception)
  fullName: System.Configuration.SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(String,Exception)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.SettingsPropertyIsReadOnlyException&quot;></see> class based on supplied parameters."
  syntax:
    content: public SettingsPropertyIsReadOnlyException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "A string containing an exception message."
    - id: innerException
      type: System.Exception
      description: "The exception that is the cause of the current exception."
  overload: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor
  parent: System.Configuration.SettingsPropertyIsReadOnlyException
  isExternal: false
  name: SettingsPropertyIsReadOnlyException()
  nameWithType: SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException()
  fullName: System.Configuration.SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException()
- uid: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor(System.String)
  parent: System.Configuration.SettingsPropertyIsReadOnlyException
  isExternal: false
  name: SettingsPropertyIsReadOnlyException(String)
  nameWithType: SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(String)
  fullName: System.Configuration.SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Configuration.SettingsPropertyIsReadOnlyException
  isExternal: false
  name: SettingsPropertyIsReadOnlyException(SerializationInfo,StreamingContext)
  nameWithType: SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(SerializationInfo,StreamingContext)
  fullName: System.Configuration.SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor(System.String,System.Exception)
  parent: System.Configuration.SettingsPropertyIsReadOnlyException
  isExternal: false
  name: SettingsPropertyIsReadOnlyException(String,Exception)
  nameWithType: SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(String,Exception)
  fullName: System.Configuration.SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException(String,Exception)
- uid: System.Configuration.SettingsPropertyIsReadOnlyException.#ctor*
  parent: System.Configuration.SettingsPropertyIsReadOnlyException
  isExternal: false
  name: SettingsPropertyIsReadOnlyException
  nameWithType: SettingsPropertyIsReadOnlyException.SettingsPropertyIsReadOnlyException
