### YamlMime:ManagedReference
items:
- uid: System.Drawing.Printing.QueryPageSettingsEventArgs
  id: QueryPageSettingsEventArgs
  children:
  - System.Drawing.Printing.QueryPageSettingsEventArgs.#ctor(System.Drawing.Printing.PageSettings)
  - System.Drawing.Printing.QueryPageSettingsEventArgs.PageSettings
  langs:
  - csharp
  name: QueryPageSettingsEventArgs
  nameWithType: QueryPageSettingsEventArgs
  fullName: System.Drawing.Printing.QueryPageSettingsEventArgs
  type: Class
  summary: "Provides data for the <see cref=&quot;E:System.Drawing.Printing.PrintDocument.QueryPageSettings&quot;></see> event."
  remarks: "It is possible to print each page of a document using different page settings. You set page settings by modifying individual properties of the <xref:System.Drawing.Printing.QueryPageSettingsEventArgs.PageSettings%2A> property or by setting the property to a <xref:System.Drawing.Printing.PageSettings>. The print job can also be canceled by setting the <xref:System.ComponentModel.CancelEventArgs.Cancel%2A> property to `true`."
  example:
  - "The following code example prints a document with the first page in color, if the printer supports it. The example assumes that a <xref:System.Drawing.Printing.PrintDocument> variable named `printDoc` has been created, and the <xref:System.Drawing.Printing.PrintDocument.PrintPage> and <xref:System.Drawing.Printing.PrintDocument.QueryPageSettings> events are handled.  \n  \n Use the <xref:System.Drawing> and <xref:System.Drawing.Printing> namespaces for this example.  \n  \n [!code-cs[PaperSource and PaperSize Example with Resolution#6](~/add/codesnippet/CSharp/t-system.drawing.printin_1_1.cs)]\n [!code-cpp[PaperSource and PaperSize Example with Resolution#6](~/add/codesnippet/CPP/t-system.drawing.printin_1_1.cpp)]\n [!code-vb[PaperSource and PaperSize Example with Resolution#6](~/add/codesnippet/VisualBasic/t-system.drawing.printin_1_1.vb)]"
  syntax:
    content: 'public class QueryPageSettingsEventArgs : System.Drawing.Printing.PrintEventArgs'
  inheritance:
  - System.ComponentModel.CancelEventArgs
  - System.Drawing.Printing.PrintEventArgs
  implements: []
  inheritedMembers:
  - System.Drawing.Printing.PrintEventArgs.PrintAction
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Drawing.Printing.QueryPageSettingsEventArgs.#ctor(System.Drawing.Printing.PageSettings)
  id: '#ctor(System.Drawing.Printing.PageSettings)'
  parent: System.Drawing.Printing.QueryPageSettingsEventArgs
  langs:
  - csharp
  name: QueryPageSettingsEventArgs(PageSettings)
  nameWithType: QueryPageSettingsEventArgs.QueryPageSettingsEventArgs(PageSettings)
  fullName: System.Drawing.Printing.QueryPageSettingsEventArgs.QueryPageSettingsEventArgs(PageSettings)
  type: Constructor
  assemblies:
  - System.Drawing
  namespace: System.Drawing.Printing
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Drawing.Printing.QueryPageSettingsEventArgs&quot;></see> class."
  syntax:
    content: public QueryPageSettingsEventArgs (System.Drawing.Printing.PageSettings pageSettings);
    parameters:
    - id: pageSettings
      type: System.Drawing.Printing.PageSettings
      description: "The page settings for the page to be printed."
  overload: System.Drawing.Printing.QueryPageSettingsEventArgs.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Drawing.Printing.QueryPageSettingsEventArgs.PageSettings
  id: PageSettings
  parent: System.Drawing.Printing.QueryPageSettingsEventArgs
  langs:
  - csharp
  name: PageSettings
  nameWithType: QueryPageSettingsEventArgs.PageSettings
  fullName: System.Drawing.Printing.QueryPageSettingsEventArgs.PageSettings
  type: Property
  assemblies:
  - System.Drawing
  namespace: System.Drawing.Printing
  summary: "Gets or sets the page settings for the page to be printed."
  remarks: "It is possible to print each page of a document using different page settings. You set page settings by modifying individual properties of the PageSettings property or by setting the property to a <xref:System.Drawing.Printing.PageSettings>. The print job can also be canceled by setting the <xref:System.ComponentModel.CancelEventArgs.Cancel%2A> property to `true`."
  example:
  - "The following code example prints a document with the first page in color, if the printer supports it. The example assumes that a <xref:System.Drawing.Printing.PrintDocument> variable named `printDoc` has been created, and the <xref:System.Drawing.Printing.PrintDocument.PrintPage> and <xref:System.Drawing.Printing.PrintDocument.QueryPageSettings> events are handled.  \n  \n Use the <xref:System.Drawing> and <xref:System.Drawing.Printing> namespaces for this example.  \n  \n [!code-cs[PaperSource and PaperSize Example with Resolution#6](~/add/codesnippet/CSharp/p-system.drawing.printin_18_1.cs)]\n [!code-cpp[PaperSource and PaperSize Example with Resolution#6](~/add/codesnippet/CPP/p-system.drawing.printin_18_1.cpp)]\n [!code-vb[PaperSource and PaperSize Example with Resolution#6](~/add/codesnippet/VisualBasic/p-system.drawing.printin_18_1.vb)]"
  syntax:
    content: public System.Drawing.Printing.PageSettings PageSettings { get; set; }
    return:
      type: System.Drawing.Printing.PageSettings
      description: "The page settings for the page to be printed."
  overload: System.Drawing.Printing.QueryPageSettingsEventArgs.PageSettings*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Drawing.Printing.PrintEventArgs
  isExternal: false
  name: System.Drawing.Printing.PrintEventArgs
- uid: System.Drawing.Printing.QueryPageSettingsEventArgs.#ctor(System.Drawing.Printing.PageSettings)
  parent: System.Drawing.Printing.QueryPageSettingsEventArgs
  isExternal: false
  name: QueryPageSettingsEventArgs(PageSettings)
  nameWithType: QueryPageSettingsEventArgs.QueryPageSettingsEventArgs(PageSettings)
  fullName: System.Drawing.Printing.QueryPageSettingsEventArgs.QueryPageSettingsEventArgs(PageSettings)
- uid: System.Drawing.Printing.PageSettings
  parent: System.Drawing.Printing
  isExternal: false
  name: PageSettings
  nameWithType: PageSettings
  fullName: System.Drawing.Printing.PageSettings
- uid: System.Drawing.Printing.QueryPageSettingsEventArgs.PageSettings
  parent: System.Drawing.Printing.QueryPageSettingsEventArgs
  isExternal: false
  name: PageSettings
  nameWithType: QueryPageSettingsEventArgs.PageSettings
  fullName: System.Drawing.Printing.QueryPageSettingsEventArgs.PageSettings
- uid: System.Drawing.Printing.QueryPageSettingsEventArgs.#ctor*
  parent: System.Drawing.Printing.QueryPageSettingsEventArgs
  isExternal: false
  name: QueryPageSettingsEventArgs
  nameWithType: QueryPageSettingsEventArgs.QueryPageSettingsEventArgs
- uid: System.Drawing.Printing.QueryPageSettingsEventArgs.PageSettings*
  parent: System.Drawing.Printing.QueryPageSettingsEventArgs
  isExternal: false
  name: PageSettings
  nameWithType: QueryPageSettingsEventArgs.PageSettings
