### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.HostTimeoutsElement
  id: HostTimeoutsElement
  children:
  - System.ServiceModel.Configuration.HostTimeoutsElement.#ctor
  - System.ServiceModel.Configuration.HostTimeoutsElement.CloseTimeout
  - System.ServiceModel.Configuration.HostTimeoutsElement.OpenTimeout
  - System.ServiceModel.Configuration.HostTimeoutsElement.Properties
  langs:
  - csharp
  name: HostTimeoutsElement
  nameWithType: HostTimeoutsElement
  fullName: System.ServiceModel.Configuration.HostTimeoutsElement
  type: Class
  summary: "Represents a configuration element that specifies the interval of time allowed for the service host to open or close. This class cannot be inherited."
  syntax:
    content: 'public sealed class HostTimeoutsElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.HostTimeoutsElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.HostTimeoutsElement
  langs:
  - csharp
  name: HostTimeoutsElement()
  nameWithType: HostTimeoutsElement.HostTimeoutsElement()
  fullName: System.ServiceModel.Configuration.HostTimeoutsElement.HostTimeoutsElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.HostTimeoutsElement&quot;></see> class."
  syntax:
    content: public HostTimeoutsElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.HostTimeoutsElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.HostTimeoutsElement.CloseTimeout
  id: CloseTimeout
  parent: System.ServiceModel.Configuration.HostTimeoutsElement
  langs:
  - csharp
  name: CloseTimeout
  nameWithType: HostTimeoutsElement.CloseTimeout
  fullName: System.ServiceModel.Configuration.HostTimeoutsElement.CloseTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets the interval of time allowed for the service host to close."
  syntax:
    content: public TimeSpan CloseTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "The &lt;xref:System.TimeSpan&gt; that specifies the interval of time allowed for the service host to close"
  overload: System.ServiceModel.Configuration.HostTimeoutsElement.CloseTimeout*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.HostTimeoutsElement.OpenTimeout
  id: OpenTimeout
  parent: System.ServiceModel.Configuration.HostTimeoutsElement
  langs:
  - csharp
  name: OpenTimeout
  nameWithType: HostTimeoutsElement.OpenTimeout
  fullName: System.ServiceModel.Configuration.HostTimeoutsElement.OpenTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets the interval of time allowed for the service host to open."
  syntax:
    content: public TimeSpan OpenTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "The &lt;xref:System.TimeSpan&gt; that specifies the interval of time allowed for the service host to open."
  overload: System.ServiceModel.Configuration.HostTimeoutsElement.OpenTimeout*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.HostTimeoutsElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.HostTimeoutsElement
  langs:
  - csharp
  name: Properties
  nameWithType: HostTimeoutsElement.Properties
  fullName: System.ServiceModel.Configuration.HostTimeoutsElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.HostTimeoutsElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.HostTimeoutsElement.#ctor
  parent: System.ServiceModel.Configuration.HostTimeoutsElement
  isExternal: false
  name: HostTimeoutsElement()
  nameWithType: HostTimeoutsElement.HostTimeoutsElement()
  fullName: System.ServiceModel.Configuration.HostTimeoutsElement.HostTimeoutsElement()
- uid: System.ServiceModel.Configuration.HostTimeoutsElement.CloseTimeout
  parent: System.ServiceModel.Configuration.HostTimeoutsElement
  isExternal: false
  name: CloseTimeout
  nameWithType: HostTimeoutsElement.CloseTimeout
  fullName: System.ServiceModel.Configuration.HostTimeoutsElement.CloseTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Configuration.HostTimeoutsElement.OpenTimeout
  parent: System.ServiceModel.Configuration.HostTimeoutsElement
  isExternal: false
  name: OpenTimeout
  nameWithType: HostTimeoutsElement.OpenTimeout
  fullName: System.ServiceModel.Configuration.HostTimeoutsElement.OpenTimeout
- uid: System.ServiceModel.Configuration.HostTimeoutsElement.Properties
  parent: System.ServiceModel.Configuration.HostTimeoutsElement
  isExternal: false
  name: Properties
  nameWithType: HostTimeoutsElement.Properties
  fullName: System.ServiceModel.Configuration.HostTimeoutsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.HostTimeoutsElement.#ctor*
  parent: System.ServiceModel.Configuration.HostTimeoutsElement
  isExternal: false
  name: HostTimeoutsElement
  nameWithType: HostTimeoutsElement.HostTimeoutsElement
- uid: System.ServiceModel.Configuration.HostTimeoutsElement.CloseTimeout*
  parent: System.ServiceModel.Configuration.HostTimeoutsElement
  isExternal: false
  name: CloseTimeout
  nameWithType: HostTimeoutsElement.CloseTimeout
- uid: System.ServiceModel.Configuration.HostTimeoutsElement.OpenTimeout*
  parent: System.ServiceModel.Configuration.HostTimeoutsElement
  isExternal: false
  name: OpenTimeout
  nameWithType: HostTimeoutsElement.OpenTimeout
- uid: System.ServiceModel.Configuration.HostTimeoutsElement.Properties*
  parent: System.ServiceModel.Configuration.HostTimeoutsElement
  isExternal: false
  name: Properties
  nameWithType: HostTimeoutsElement.Properties
