### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement
  id: SoapProcessingExtensionElement
  children:
  - System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement.#ctor
  - System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement.BehaviorType
  - System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement.CreateBehavior
  - System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement.ProcessMessages
  langs:
  - csharp
  name: SoapProcessingExtensionElement
  nameWithType: SoapProcessingExtensionElement
  fullName: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement
  type: Class
  summary: "Represents a configuration element that defines the SOAP processing endpoint behavior."
  syntax:
    content: 'public class SoapProcessingExtensionElement : System.ServiceModel.Configuration.BehaviorExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  - System.ServiceModel.Configuration.BehaviorExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement
  langs:
  - csharp
  name: SoapProcessingExtensionElement()
  nameWithType: SoapProcessingExtensionElement.SoapProcessingExtensionElement()
  fullName: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement.SoapProcessingExtensionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Creates a new instance of the <see cref=&quot;T:System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement&quot;></see> class."
  syntax:
    content: public SoapProcessingExtensionElement ();
    parameters: []
  overload: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement.BehaviorType
  id: BehaviorType
  parent: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement
  langs:
  - csharp
  name: BehaviorType
  nameWithType: SoapProcessingExtensionElement.BehaviorType
  fullName: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement.BehaviorType
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Gets the type of the behavior."
  remarks: "This property always returns a type of <xref:System.ServiceModel.Routing.SoapProcessingBehavior>."
  syntax:
    content: public override Type BehaviorType { get; }
    return:
      type: System.Type
      description: "The type of the behavior."
  overload: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement.BehaviorType*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement.CreateBehavior
  id: CreateBehavior
  parent: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement
  langs:
  - csharp
  name: CreateBehavior()
  nameWithType: SoapProcessingExtensionElement.CreateBehavior()
  fullName: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement.CreateBehavior()
  type: Method
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Creates a new SOAP processing behavior element based on the current configuration settings."
  syntax:
    content: protected override object CreateBehavior ();
    parameters: []
    return:
      type: System.Object
      description: "To be added."
  overload: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement.CreateBehavior*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement.ProcessMessages
  id: ProcessMessages
  parent: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement
  langs:
  - csharp
  name: ProcessMessages
  nameWithType: SoapProcessingExtensionElement.ProcessMessages
  fullName: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement.ProcessMessages
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Gets or sets a value that indicates whether messages should be marshaled between SOAP message versions."
  syntax:
    content: public bool ProcessMessages { get; set; }
    return:
      type: System.Boolean
      description: '**true** if messages should be marshaled; otherwise, **false**. The default is **true**.'
  overload: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement.ProcessMessages*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.BehaviorExtensionElement
  isExternal: false
  name: System.ServiceModel.Configuration.BehaviorExtensionElement
- uid: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement.#ctor
  parent: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement
  isExternal: false
  name: SoapProcessingExtensionElement()
  nameWithType: SoapProcessingExtensionElement.SoapProcessingExtensionElement()
  fullName: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement.SoapProcessingExtensionElement()
- uid: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement.BehaviorType
  parent: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement
  isExternal: false
  name: BehaviorType
  nameWithType: SoapProcessingExtensionElement.BehaviorType
  fullName: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement.BehaviorType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement.CreateBehavior
  parent: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement
  isExternal: false
  name: CreateBehavior()
  nameWithType: SoapProcessingExtensionElement.CreateBehavior()
  fullName: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement.CreateBehavior()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement.ProcessMessages
  parent: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement
  isExternal: false
  name: ProcessMessages
  nameWithType: SoapProcessingExtensionElement.ProcessMessages
  fullName: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement.ProcessMessages
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement.#ctor*
  parent: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement
  isExternal: false
  name: SoapProcessingExtensionElement
  nameWithType: SoapProcessingExtensionElement.SoapProcessingExtensionElement
- uid: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement.BehaviorType*
  parent: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement
  isExternal: false
  name: BehaviorType
  nameWithType: SoapProcessingExtensionElement.BehaviorType
- uid: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement.CreateBehavior*
  parent: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement
  isExternal: false
  name: CreateBehavior
  nameWithType: SoapProcessingExtensionElement.CreateBehavior
- uid: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement.ProcessMessages*
  parent: System.ServiceModel.Routing.Configuration.SoapProcessingExtensionElement
  isExternal: false
  name: ProcessMessages
  nameWithType: SoapProcessingExtensionElement.ProcessMessages
