### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  id: AddressHeaderCollectionElement
  children:
  - System.ServiceModel.Configuration.AddressHeaderCollectionElement.#ctor
  - System.ServiceModel.Configuration.AddressHeaderCollectionElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.ServiceModel.Configuration.AddressHeaderCollectionElement.Headers
  - System.ServiceModel.Configuration.AddressHeaderCollectionElement.Properties
  - System.ServiceModel.Configuration.AddressHeaderCollectionElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  langs:
  - csharp
  name: AddressHeaderCollectionElement
  nameWithType: AddressHeaderCollectionElement
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  type: Class
  summary: "Represents the configuration element that contains a collection of address headers. This class cannot be inherited."
  syntax:
    content: 'public sealed class AddressHeaderCollectionElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  langs:
  - csharp
  name: AddressHeaderCollectionElement()
  nameWithType: AddressHeaderCollectionElement.AddressHeaderCollectionElement()
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement.AddressHeaderCollectionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.AddressHeaderCollectionElement&quot;></see> class."
  syntax:
    content: public AddressHeaderCollectionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.AddressHeaderCollectionElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  id: DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  langs:
  - csharp
  name: DeserializeElement(XmlReader,Boolean)
  nameWithType: AddressHeaderCollectionElement.DeserializeElement(XmlReader,Boolean)
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement.DeserializeElement(XmlReader,Boolean)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override void DeserializeElement (System.Xml.XmlReader reader, bool serializeCollectionKey);
    parameters:
    - id: reader
      type: System.Xml.XmlReader
      description: "To be added."
    - id: serializeCollectionKey
      type: System.Boolean
      description: "To be added."
  overload: System.ServiceModel.Configuration.AddressHeaderCollectionElement.DeserializeElement*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.Headers
  id: Headers
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  langs:
  - csharp
  name: Headers
  nameWithType: AddressHeaderCollectionElement.Headers
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement.Headers
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets a collection of address headers."
  syntax:
    content: public System.ServiceModel.Channels.AddressHeaderCollection Headers { get; set; }
    return:
      type: System.ServiceModel.Channels.AddressHeaderCollection
      description: "A collection of address headers."
  overload: System.ServiceModel.Configuration.AddressHeaderCollectionElement.Headers*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  langs:
  - csharp
  name: Properties
  nameWithType: AddressHeaderCollectionElement.Properties
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.AddressHeaderCollectionElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  id: SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  langs:
  - csharp
  name: SerializeToXmlElement(XmlWriter,String)
  nameWithType: AddressHeaderCollectionElement.SerializeToXmlElement(XmlWriter,String)
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement.SerializeToXmlElement(XmlWriter,String)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override bool SerializeToXmlElement (System.Xml.XmlWriter writer, string elementName);
    parameters:
    - id: writer
      type: System.Xml.XmlWriter
      description: "To be added."
    - id: elementName
      type: System.String
      description: "To be added."
    return:
      type: System.Boolean
      description: "To be added."
  overload: System.ServiceModel.Configuration.AddressHeaderCollectionElement.SerializeToXmlElement*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.#ctor
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  isExternal: false
  name: AddressHeaderCollectionElement()
  nameWithType: AddressHeaderCollectionElement.AddressHeaderCollectionElement()
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement.AddressHeaderCollectionElement()
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  isExternal: false
  name: DeserializeElement(XmlReader,Boolean)
  nameWithType: AddressHeaderCollectionElement.DeserializeElement(XmlReader,Boolean)
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement.DeserializeElement(XmlReader,Boolean)
- uid: System.Xml.XmlReader
  parent: System.Xml
  isExternal: true
  name: XmlReader
  nameWithType: XmlReader
  fullName: System.Xml.XmlReader
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.Headers
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  isExternal: false
  name: Headers
  nameWithType: AddressHeaderCollectionElement.Headers
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement.Headers
- uid: System.ServiceModel.Channels.AddressHeaderCollection
  parent: System.ServiceModel.Channels
  isExternal: true
  name: AddressHeaderCollection
  nameWithType: AddressHeaderCollection
  fullName: System.ServiceModel.Channels.AddressHeaderCollection
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.Properties
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  isExternal: false
  name: Properties
  nameWithType: AddressHeaderCollectionElement.Properties
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  isExternal: false
  name: SerializeToXmlElement(XmlWriter,String)
  nameWithType: AddressHeaderCollectionElement.SerializeToXmlElement(XmlWriter,String)
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement.SerializeToXmlElement(XmlWriter,String)
- uid: System.Xml.XmlWriter
  parent: System.Xml
  isExternal: true
  name: XmlWriter
  nameWithType: XmlWriter
  fullName: System.Xml.XmlWriter
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.#ctor*
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  isExternal: false
  name: AddressHeaderCollectionElement
  nameWithType: AddressHeaderCollectionElement.AddressHeaderCollectionElement
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.DeserializeElement*
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  isExternal: false
  name: DeserializeElement
  nameWithType: AddressHeaderCollectionElement.DeserializeElement
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.Headers*
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  isExternal: false
  name: Headers
  nameWithType: AddressHeaderCollectionElement.Headers
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.Properties*
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  isExternal: false
  name: Properties
  nameWithType: AddressHeaderCollectionElement.Properties
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement.SerializeToXmlElement*
  parent: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  isExternal: false
  name: SerializeToXmlElement
  nameWithType: AddressHeaderCollectionElement.SerializeToXmlElement
