### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Channels.IReceiveContextSettings
  id: IReceiveContextSettings
  children:
  - System.ServiceModel.Channels.IReceiveContextSettings.Enabled
  - System.ServiceModel.Channels.IReceiveContextSettings.ValidityDuration
  langs:
  - csharp
  name: IReceiveContextSettings
  nameWithType: IReceiveContextSettings
  fullName: System.ServiceModel.Channels.IReceiveContextSettings
  type: Interface
  summary: "An interface that enables you to set receive context settings."
  remarks: "Receive context allows for controlled acknowledgement when using a one-way message channel and non-destructive reads when using a queued channel."
  syntax:
    content: public interface IReceiveContextSettings
  implements: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Channels.IReceiveContextSettings.Enabled
  id: Enabled
  parent: System.ServiceModel.Channels.IReceiveContextSettings
  langs:
  - csharp
  name: Enabled
  nameWithType: IReceiveContextSettings.Enabled
  fullName: System.ServiceModel.Channels.IReceiveContextSettings.Enabled
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Gets or sets a value that specifies if receive context is enabled."
  syntax:
    content: public bool Enabled { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if receive context is enabled; otherwise <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>."
  overload: System.ServiceModel.Channels.IReceiveContextSettings.Enabled*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Channels.IReceiveContextSettings.ValidityDuration
  id: ValidityDuration
  parent: System.ServiceModel.Channels.IReceiveContextSettings
  langs:
  - csharp
  name: ValidityDuration
  nameWithType: IReceiveContextSettings.ValidityDuration
  fullName: System.ServiceModel.Channels.IReceiveContextSettings.ValidityDuration
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Gets a value that specifies a connection timeout when used with direct channels and message lock duration when used with queued channels."
  remarks: >-
    > [!IMPORTANT]

    >  If ValidityDurationexpires for a message, any transaction that may be used for its processing, will be aborted along with the workflow instance if the expiration occurs during the transaction.
  syntax:
    content: public TimeSpan ValidityDuration { get; }
    return:
      type: System.TimeSpan
      description: "A timeout value."
  overload: System.ServiceModel.Channels.IReceiveContextSettings.ValidityDuration*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Channels.IReceiveContextSettings.Enabled
  parent: System.ServiceModel.Channels.IReceiveContextSettings
  isExternal: false
  name: Enabled
  nameWithType: IReceiveContextSettings.Enabled
  fullName: System.ServiceModel.Channels.IReceiveContextSettings.Enabled
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Channels.IReceiveContextSettings.ValidityDuration
  parent: System.ServiceModel.Channels.IReceiveContextSettings
  isExternal: false
  name: ValidityDuration
  nameWithType: IReceiveContextSettings.ValidityDuration
  fullName: System.ServiceModel.Channels.IReceiveContextSettings.ValidityDuration
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Channels.IReceiveContextSettings.Enabled*
  parent: System.ServiceModel.Channels.IReceiveContextSettings
  isExternal: false
  name: Enabled
  nameWithType: IReceiveContextSettings.Enabled
- uid: System.ServiceModel.Channels.IReceiveContextSettings.ValidityDuration*
  parent: System.ServiceModel.Channels.IReceiveContextSettings
  isExternal: false
  name: ValidityDuration
  nameWithType: IReceiveContextSettings.ValidityDuration
