### YamlMime:ManagedReference
items:
- uid: System.Security.Policy.ApplicationVersionMatch
  id: ApplicationVersionMatch
  children:
  - System.Security.Policy.ApplicationVersionMatch.MatchAllVersions
  - System.Security.Policy.ApplicationVersionMatch.MatchExactVersion
  langs:
  - csharp
  name: ApplicationVersionMatch
  nameWithType: ApplicationVersionMatch
  fullName: System.Security.Policy.ApplicationVersionMatch
  type: Enum
  summary: "Specifies how to match versions when locating application trusts in a collection."
  remarks: "The <xref:System.Security.Policy.ApplicationTrustCollection.Remove%2A> and <xref:System.Security.Policy.ApplicationTrustCollection.Find%2A> methods of an <xref:System.Security.Policy.ApplicationTrustCollection> can act either on all versions of an application or on the exact version. The ApplicationVersionMatch enumeration allows the caller to specify the desired behavior."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public enum ApplicationVersionMatch
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationVersionMatch.MatchAllVersions
  id: MatchAllVersions
  parent: System.Security.Policy.ApplicationVersionMatch
  langs:
  - csharp
  name: MatchAllVersions
  nameWithType: ApplicationVersionMatch.MatchAllVersions
  fullName: System.Security.Policy.ApplicationVersionMatch.MatchAllVersions
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: "Match on all versions."
  syntax:
    content: MatchAllVersions
    return:
      type: System.Security.Policy.ApplicationVersionMatch
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Policy.ApplicationVersionMatch.MatchExactVersion
  id: MatchExactVersion
  parent: System.Security.Policy.ApplicationVersionMatch
  langs:
  - csharp
  name: MatchExactVersion
  nameWithType: ApplicationVersionMatch.MatchExactVersion
  fullName: System.Security.Policy.ApplicationVersionMatch.MatchExactVersion
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Security.Policy
  summary: "Match on the exact version."
  syntax:
    content: MatchExactVersion
    return:
      type: System.Security.Policy.ApplicationVersionMatch
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Security.Policy.ApplicationVersionMatch.MatchAllVersions
  parent: System.Security.Policy.ApplicationVersionMatch
  isExternal: false
  name: MatchAllVersions
  nameWithType: ApplicationVersionMatch.MatchAllVersions
  fullName: System.Security.Policy.ApplicationVersionMatch.MatchAllVersions
- uid: System.Security.Policy.ApplicationVersionMatch
  parent: System.Security.Policy
  isExternal: false
  name: ApplicationVersionMatch
  nameWithType: ApplicationVersionMatch
  fullName: System.Security.Policy.ApplicationVersionMatch
- uid: System.Security.Policy.ApplicationVersionMatch.MatchExactVersion
  parent: System.Security.Policy.ApplicationVersionMatch
  isExternal: false
  name: MatchExactVersion
  nameWithType: ApplicationVersionMatch.MatchExactVersion
  fullName: System.Security.Policy.ApplicationVersionMatch.MatchExactVersion
