### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
  id: NamedPipeTransportSecurityElement
  children:
  - System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.#ctor
  - System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.Properties
  - System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.ProtectionLevel
  langs:
  - csharp
  name: NamedPipeTransportSecurityElement
  nameWithType: NamedPipeTransportSecurityElement
  fullName: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
  type: Class
  summary: "Specifies the transport security for a named pipe. This class cannot be inherited."
  syntax:
    content: 'public sealed class NamedPipeTransportSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
  langs:
  - csharp
  name: NamedPipeTransportSecurityElement()
  nameWithType: NamedPipeTransportSecurityElement.NamedPipeTransportSecurityElement()
  fullName: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.NamedPipeTransportSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.NamedPipeTransportSecurityElement&quot;></see> class."
  syntax:
    content: public NamedPipeTransportSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: NamedPipeTransportSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.ProtectionLevel
  id: ProtectionLevel
  parent: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
  langs:
  - csharp
  name: ProtectionLevel
  nameWithType: NamedPipeTransportSecurityElement.ProtectionLevel
  fullName: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.ProtectionLevel
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Specifies the protection for this named pipe."
  syntax:
    content: public System.Net.Security.ProtectionLevel ProtectionLevel { get; set; }
    return:
      type: System.Net.Security.ProtectionLevel
      description: "A <see cref=&quot;T:System.Net.Security.ProtectionLevel&quot;></see>. The default is <see cref=&quot;T:System.Net.Security.ProtectionLevel&quot;></see>."
  overload: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.ProtectionLevel*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
  isExternal: false
  name: NamedPipeTransportSecurityElement()
  nameWithType: NamedPipeTransportSecurityElement.NamedPipeTransportSecurityElement()
  fullName: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.NamedPipeTransportSecurityElement()
- uid: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.Properties
  parent: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
  isExternal: false
  name: Properties
  nameWithType: NamedPipeTransportSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.ProtectionLevel
  parent: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
  isExternal: false
  name: ProtectionLevel
  nameWithType: NamedPipeTransportSecurityElement.ProtectionLevel
  fullName: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.ProtectionLevel
- uid: System.Net.Security.ProtectionLevel
  parent: System.Net.Security
  isExternal: false
  name: ProtectionLevel
  nameWithType: ProtectionLevel
  fullName: System.Net.Security.ProtectionLevel
- uid: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
  isExternal: false
  name: NamedPipeTransportSecurityElement
  nameWithType: NamedPipeTransportSecurityElement.NamedPipeTransportSecurityElement
- uid: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
  isExternal: false
  name: Properties
  nameWithType: NamedPipeTransportSecurityElement.Properties
- uid: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement.ProtectionLevel*
  parent: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
  isExternal: false
  name: ProtectionLevel
  nameWithType: NamedPipeTransportSecurityElement.ProtectionLevel
