### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  id: ApplicationContainerSettingsElement
  children:
  - System.ServiceModel.Configuration.ApplicationContainerSettingsElement.#ctor
  - System.ServiceModel.Configuration.ApplicationContainerSettingsElement.PackageFullName
  - System.ServiceModel.Configuration.ApplicationContainerSettingsElement.Properties
  - System.ServiceModel.Configuration.ApplicationContainerSettingsElement.SessionId
  langs:
  - csharp
  name: ApplicationContainerSettingsElement
  nameWithType: ApplicationContainerSettingsElement
  fullName: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  type: Class
  summary: "Specifies settings for the application container settings element."
  syntax:
    content: 'public sealed class ApplicationContainerSettingsElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  langs:
  - csharp
  name: ApplicationContainerSettingsElement()
  nameWithType: ApplicationContainerSettingsElement.ApplicationContainerSettingsElement()
  fullName: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.ApplicationContainerSettingsElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.ApplicationContainerSettingsElement&quot;></see> class."
  syntax:
    content: public ApplicationContainerSettingsElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.PackageFullName
  id: PackageFullName
  parent: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  langs:
  - csharp
  name: PackageFullName
  nameWithType: ApplicationContainerSettingsElement.PackageFullName
  fullName: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.PackageFullName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets the full name of the package."
  syntax:
    content: public string PackageFullName { get; set; }
    return:
      type: System.String
      description: "The full name of the package."
  overload: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.PackageFullName*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  langs:
  - csharp
  name: Properties
  nameWithType: ApplicationContainerSettingsElement.Properties
  fullName: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.SessionId
  id: SessionId
  parent: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  langs:
  - csharp
  name: SessionId
  nameWithType: ApplicationContainerSettingsElement.SessionId
  fullName: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.SessionId
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets the unique session identifier for the <see cref=&quot;T:System.ServiceModel.Configuration.ApplicationContainerSettingsElement&quot;></see>."
  syntax:
    content: public int SessionId { get; set; }
    return:
      type: System.Int32
      description: "The unique session identifier."
  overload: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.SessionId*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.#ctor
  parent: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  isExternal: false
  name: ApplicationContainerSettingsElement()
  nameWithType: ApplicationContainerSettingsElement.ApplicationContainerSettingsElement()
  fullName: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.ApplicationContainerSettingsElement()
- uid: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.PackageFullName
  parent: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  isExternal: false
  name: PackageFullName
  nameWithType: ApplicationContainerSettingsElement.PackageFullName
  fullName: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.PackageFullName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.Properties
  parent: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  isExternal: false
  name: Properties
  nameWithType: ApplicationContainerSettingsElement.Properties
  fullName: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.SessionId
  parent: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  isExternal: false
  name: SessionId
  nameWithType: ApplicationContainerSettingsElement.SessionId
  fullName: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.SessionId
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.#ctor*
  parent: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  isExternal: false
  name: ApplicationContainerSettingsElement
  nameWithType: ApplicationContainerSettingsElement.ApplicationContainerSettingsElement
- uid: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.PackageFullName*
  parent: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  isExternal: false
  name: PackageFullName
  nameWithType: ApplicationContainerSettingsElement.PackageFullName
- uid: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.Properties*
  parent: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  isExternal: false
  name: Properties
  nameWithType: ApplicationContainerSettingsElement.Properties
- uid: System.ServiceModel.Configuration.ApplicationContainerSettingsElement.SessionId*
  parent: System.ServiceModel.Configuration.ApplicationContainerSettingsElement
  isExternal: false
  name: SessionId
  nameWithType: ApplicationContainerSettingsElement.SessionId
