### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  id: NamedPipeConnectionPoolSettings
  children:
  - System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.GroupName
  - System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.IdleTimeout
  - System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
  langs:
  - csharp
  name: NamedPipeConnectionPoolSettings
  nameWithType: NamedPipeConnectionPoolSettings
  fullName: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  type: Class
  summary: "Represents settings that control the behavior of the named pipe connection pool."
  syntax:
    content: public sealed class NamedPipeConnectionPoolSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.GroupName
  id: GroupName
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  langs:
  - csharp
  name: GroupName
  nameWithType: NamedPipeConnectionPoolSettings.GroupName
  fullName: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.GroupName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Gets or sets the group name of the connection pool group on the client."
  remarks: "The default value can be changed to isolate the connections for a particular client into separate groups."
  syntax:
    content: public string GroupName { get; set; }
    return:
      type: System.String
      description: "The name of the connection pool group on the client. The default name is &quot;default&quot;."
  overload: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.GroupName*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "The value is ."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.IdleTimeout
  id: IdleTimeout
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  langs:
  - csharp
  name: IdleTimeout
  nameWithType: NamedPipeConnectionPoolSettings.IdleTimeout
  fullName: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.IdleTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Gets or sets the maximum time the connection can be idle in the connection pool before being disconnected."
  syntax:
    content: public TimeSpan IdleTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "Returns a &lt;xref:System.TimeSpan&gt; structure that indicates the maximum time the connection can be idle in the connection pool before being disconnected."
  overload: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.IdleTimeout*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "The value is less than zero."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
  id: MaxOutboundConnectionsPerEndpoint
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  langs:
  - csharp
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
  fullName: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Gets or sets the maximum number of outbound connections for each endpoint that is cached in the connection pool."
  remarks: "This limits the number of connections that are cached for each unique endpoint. If this value is exceeded by having more active client connections, then the service may appear unresponsive to the client and this value should be adjusted to exceed the maximum number of expected connections that are cached for each unique endpoint."
  syntax:
    content: public int MaxOutboundConnectionsPerEndpoint { get; set; }
    return:
      type: System.Int32
      description: "The maximum number of allowed outbound connections for each endpoint that is cached in the connection pool. The default value is 10."
  overload: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "The value is less than or equal to zero."
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.GroupName
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  isExternal: false
  name: GroupName
  nameWithType: NamedPipeConnectionPoolSettings.GroupName
  fullName: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.GroupName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.IdleTimeout
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  isExternal: false
  name: IdleTimeout
  nameWithType: NamedPipeConnectionPoolSettings.IdleTimeout
  fullName: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.IdleTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  isExternal: false
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
  fullName: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.GroupName*
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  isExternal: false
  name: GroupName
  nameWithType: NamedPipeConnectionPoolSettings.GroupName
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.IdleTimeout*
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  isExternal: false
  name: IdleTimeout
  nameWithType: NamedPipeConnectionPoolSettings.IdleTimeout
- uid: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint*
  parent: System.ServiceModel.Channels.NamedPipeConnectionPoolSettings
  isExternal: false
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: NamedPipeConnectionPoolSettings.MaxOutboundConnectionsPerEndpoint
