### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Routing.Configuration.BackupEndpointElement
  id: BackupEndpointElement
  children:
  - System.ServiceModel.Routing.Configuration.BackupEndpointElement.#ctor
  - System.ServiceModel.Routing.Configuration.BackupEndpointElement.EndpointName
  langs:
  - csharp
  name: BackupEndpointElement
  nameWithType: BackupEndpointElement
  fullName: System.ServiceModel.Routing.Configuration.BackupEndpointElement
  type: Class
  summary: "Represents a configuration element that defines a backup endpoint element."
  syntax:
    content: 'public class BackupEndpointElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.BackupEndpointElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Routing.Configuration.BackupEndpointElement
  langs:
  - csharp
  name: BackupEndpointElement()
  nameWithType: BackupEndpointElement.BackupEndpointElement()
  fullName: System.ServiceModel.Routing.Configuration.BackupEndpointElement.BackupEndpointElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Creates a new instance of the <see cref=&quot;T:System.ServiceModel.Routing.Configuration.BackupEndpointElement&quot;></see> class."
  syntax:
    content: public BackupEndpointElement ();
    parameters: []
  overload: System.ServiceModel.Routing.Configuration.BackupEndpointElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.BackupEndpointElement.EndpointName
  id: EndpointName
  parent: System.ServiceModel.Routing.Configuration.BackupEndpointElement
  langs:
  - csharp
  name: EndpointName
  nameWithType: BackupEndpointElement.EndpointName
  fullName: System.ServiceModel.Routing.Configuration.BackupEndpointElement.EndpointName
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Gets or sets the name used to identify this endpoint in the configuration file."
  remarks: "The specified name acts as a key that references a configured client endpoint element that has the same name."
  syntax:
    content: public string EndpointName { get; set; }
    return:
      type: System.String
      description: "The name."
  overload: System.ServiceModel.Routing.Configuration.BackupEndpointElement.EndpointName*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Routing.Configuration.BackupEndpointElement.#ctor
  parent: System.ServiceModel.Routing.Configuration.BackupEndpointElement
  isExternal: false
  name: BackupEndpointElement()
  nameWithType: BackupEndpointElement.BackupEndpointElement()
  fullName: System.ServiceModel.Routing.Configuration.BackupEndpointElement.BackupEndpointElement()
- uid: System.ServiceModel.Routing.Configuration.BackupEndpointElement.EndpointName
  parent: System.ServiceModel.Routing.Configuration.BackupEndpointElement
  isExternal: false
  name: EndpointName
  nameWithType: BackupEndpointElement.EndpointName
  fullName: System.ServiceModel.Routing.Configuration.BackupEndpointElement.EndpointName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Routing.Configuration.BackupEndpointElement.#ctor*
  parent: System.ServiceModel.Routing.Configuration.BackupEndpointElement
  isExternal: false
  name: BackupEndpointElement
  nameWithType: BackupEndpointElement.BackupEndpointElement
- uid: System.ServiceModel.Routing.Configuration.BackupEndpointElement.EndpointName*
  parent: System.ServiceModel.Routing.Configuration.BackupEndpointElement
  isExternal: false
  name: EndpointName
  nameWithType: BackupEndpointElement.EndpointName
