### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  id: SendMessageChannelCacheElement
  children:
  - System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.#ctor
  - System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.AllowUnsafeCaching
  - System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.BehaviorType
  - System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.ChannelSettings
  - System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.CreateBehavior
  - System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.FactorySettings
  - System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.Properties
  langs:
  - csharp
  name: SendMessageChannelCacheElement
  nameWithType: SendMessageChannelCacheElement
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  type: Class
  summary: "Creates and maintains the sub-element that configures use of the <see cref=&quot;T:System.ServiceModel.Activities.SendMessageChannelCache&quot;></see>, in the service behaviors section of a workflow configuration file. This is a sealed class."
  syntax:
    content: 'public sealed class SendMessageChannelCacheElement : System.ServiceModel.Configuration.BehaviorExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  - System.ServiceModel.Configuration.BehaviorExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  langs:
  - csharp
  name: SendMessageChannelCacheElement()
  nameWithType: SendMessageChannelCacheElement.SendMessageChannelCacheElement()
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.SendMessageChannelCacheElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "Creates a  new instance of the <see cref=&quot;T:System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement&quot;></see> class."
  syntax:
    content: public SendMessageChannelCacheElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.AllowUnsafeCaching
  id: AllowUnsafeCaching
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  langs:
  - csharp
  name: AllowUnsafeCaching
  nameWithType: SendMessageChannelCacheElement.AllowUnsafeCaching
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.AllowUnsafeCaching
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "Gets a value indicating whether the cache associated with an instance of workflow is turned on or off."
  remarks: "In the majority of the cases when there are no custom bindings and/or behaviors, we turn on cache by default. In the case where the user did plug in their own binding and behaviors, the caching of the channel factories could become unsecure, therefore, we turn off our cache by default. But the user can set the AllowUnsafeCachingback on which requires them to carefully read the appropriate MSDN document and make a decision that strikes a balanace between security and performance."
  syntax:
    content: public bool AllowUnsafeCaching { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if the workflow instance cache is turned on; otherwise, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>."
  overload: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.AllowUnsafeCaching*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.BehaviorType
  id: BehaviorType
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  langs:
  - csharp
  name: BehaviorType
  nameWithType: SendMessageChannelCacheElement.BehaviorType
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.BehaviorType
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "Gets or sets the type of the <see cref=&quot;T:System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement&quot;></see>."
  syntax:
    content: public override Type BehaviorType { get; }
    return:
      type: System.Type
      description: "A type object."
  overload: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.BehaviorType*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.ChannelSettings
  id: ChannelSettings
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  langs:
  - csharp
  name: ChannelSettings
  nameWithType: SendMessageChannelCacheElement.ChannelSettings
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.ChannelSettings
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "Gets or sets the settings of the channel cache."
  syntax:
    content: public System.ServiceModel.Activities.Configuration.ChannelSettingsElement ChannelSettings { get; }
    return:
      type: System.ServiceModel.Activities.Configuration.ChannelSettingsElement
      description: "The settings of the channel cache."
  overload: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.ChannelSettings*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.CreateBehavior
  id: CreateBehavior
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  langs:
  - csharp
  name: CreateBehavior()
  nameWithType: SendMessageChannelCacheElement.CreateBehavior()
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.CreateBehavior()
  type: Method
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  syntax:
    content: protected override object CreateBehavior ();
    parameters: []
    return:
      type: System.Object
      description: "To be added."
  overload: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.CreateBehavior*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.FactorySettings
  id: FactorySettings
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  langs:
  - csharp
  name: FactorySettings
  nameWithType: SendMessageChannelCacheElement.FactorySettings
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.FactorySettings
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "Gets or sets the settings of the channel factory cache."
  remarks: "The channel factory cache represents cached channel factories. For more information about channel factories, see <xref:System.ServiceModel.ChannelFactory> and <xref:System.ServiceModel.ChannelFactory%601>."
  syntax:
    content: public System.ServiceModel.Activities.Configuration.FactorySettingsElement FactorySettings { get; }
    return:
      type: System.ServiceModel.Activities.Configuration.FactorySettingsElement
      description: "The settings of the channel factory cache."
  overload: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.FactorySettings*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  langs:
  - csharp
  name: Properties
  nameWithType: SendMessageChannelCacheElement.Properties
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.BehaviorExtensionElement
  isExternal: false
  name: System.ServiceModel.Configuration.BehaviorExtensionElement
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.#ctor
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  isExternal: false
  name: SendMessageChannelCacheElement()
  nameWithType: SendMessageChannelCacheElement.SendMessageChannelCacheElement()
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.SendMessageChannelCacheElement()
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.AllowUnsafeCaching
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  isExternal: false
  name: AllowUnsafeCaching
  nameWithType: SendMessageChannelCacheElement.AllowUnsafeCaching
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.AllowUnsafeCaching
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.BehaviorType
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  isExternal: false
  name: BehaviorType
  nameWithType: SendMessageChannelCacheElement.BehaviorType
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.BehaviorType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.ChannelSettings
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  isExternal: false
  name: ChannelSettings
  nameWithType: SendMessageChannelCacheElement.ChannelSettings
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.ChannelSettings
- uid: System.ServiceModel.Activities.Configuration.ChannelSettingsElement
  parent: System.ServiceModel.Activities.Configuration
  isExternal: false
  name: ChannelSettingsElement
  nameWithType: ChannelSettingsElement
  fullName: System.ServiceModel.Activities.Configuration.ChannelSettingsElement
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.CreateBehavior
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  isExternal: false
  name: CreateBehavior()
  nameWithType: SendMessageChannelCacheElement.CreateBehavior()
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.CreateBehavior()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.FactorySettings
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  isExternal: false
  name: FactorySettings
  nameWithType: SendMessageChannelCacheElement.FactorySettings
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.FactorySettings
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  parent: System.ServiceModel.Activities.Configuration
  isExternal: false
  name: FactorySettingsElement
  nameWithType: FactorySettingsElement
  fullName: System.ServiceModel.Activities.Configuration.FactorySettingsElement
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.Properties
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  isExternal: false
  name: Properties
  nameWithType: SendMessageChannelCacheElement.Properties
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.#ctor*
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  isExternal: false
  name: SendMessageChannelCacheElement
  nameWithType: SendMessageChannelCacheElement.SendMessageChannelCacheElement
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.AllowUnsafeCaching*
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  isExternal: false
  name: AllowUnsafeCaching
  nameWithType: SendMessageChannelCacheElement.AllowUnsafeCaching
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.BehaviorType*
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  isExternal: false
  name: BehaviorType
  nameWithType: SendMessageChannelCacheElement.BehaviorType
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.ChannelSettings*
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  isExternal: false
  name: ChannelSettings
  nameWithType: SendMessageChannelCacheElement.ChannelSettings
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.CreateBehavior*
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  isExternal: false
  name: CreateBehavior
  nameWithType: SendMessageChannelCacheElement.CreateBehavior
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.FactorySettings*
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  isExternal: false
  name: FactorySettings
  nameWithType: SendMessageChannelCacheElement.FactorySettings
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.Properties*
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  isExternal: false
  name: Properties
  nameWithType: SendMessageChannelCacheElement.Properties
