### YamlMime:ManagedReference
items:
- uid: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement
  id: SchemaImporterExtensionElement
  children:
  - System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.#ctor
  - System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.#ctor(System.String,System.String)
  - System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.#ctor(System.String,System.Type)
  - System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.Name
  - System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.Properties
  - System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.Type
  langs:
  - csharp
  name: SchemaImporterExtensionElement
  nameWithType: SchemaImporterExtensionElement
  fullName: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement
  type: Class
  summary: "Handles the configuration for the <see cref=&quot;T:System.Xml.Serialization.XmlSchemaImporter&quot;></see> class. This class cannot be inherited."
  remarks: "This class is used by the serialization infrastructure to handle the configuration elements and cannot be used directly. For more information about configuration files, see [Configuration File Schema](../Topic/Configuration%20File%20Schema%20for%20the%20.NET%20Framework.md).  \n  \n Instead, to configure the <xref:System.Xml.Serialization.XmlSchemaImporter>, create an application configuration file and use the following XML elements to specify types used by the class when mapping XSD types to .Net Framework types:  \n  \n-   [\\<system.xml.serialization> Element](../Topic/%3Csystem.xml.serialization%3E%20Element.md)  \n  \n-   [\\<schemaImporterExtensions> Element](../Topic/%3CschemaImporterExtensions%3E%20Element.md)  \n  \n-   [\\<add> Element for \\<xmlSchemaImporterExtensions>](../Topic/%3Cadd%3E%20Element%20for%20%3CxmlSchemaImporterExtensions%3E.md)"
  syntax:
    content: 'public sealed class SchemaImporterExtensionElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.#ctor
  id: '#ctor'
  parent: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement
  langs:
  - csharp
  name: SchemaImporterExtensionElement()
  nameWithType: SchemaImporterExtensionElement.SchemaImporterExtensionElement()
  fullName: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.SchemaImporterExtensionElement()
  type: Constructor
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Xml.Serialization.Configuration.SchemaImporterExtensionElement&quot;></see> class."
  syntax:
    content: public SchemaImporterExtensionElement ();
    parameters: []
  overload: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement
  langs:
  - csharp
  name: SchemaImporterExtensionElement(String,String)
  nameWithType: SchemaImporterExtensionElement.SchemaImporterExtensionElement(String,String)
  fullName: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.SchemaImporterExtensionElement(String,String)
  type: Constructor
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Xml.Serialization.Configuration.SchemaImporterExtensionElement&quot;></see> class and specifies the name and type of the extension."
  syntax:
    content: public SchemaImporterExtensionElement (string name, string type);
    parameters:
    - id: name
      type: System.String
      description: "The name of the new extension. The name must be unique."
    - id: type
      type: System.String
      description: "The type of the new extension, specified as a string."
  overload: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.#ctor(System.String,System.Type)
  id: '#ctor(System.String,System.Type)'
  parent: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement
  langs:
  - csharp
  name: SchemaImporterExtensionElement(String,Type)
  nameWithType: SchemaImporterExtensionElement.SchemaImporterExtensionElement(String,Type)
  fullName: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.SchemaImporterExtensionElement(String,Type)
  type: Constructor
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Xml.Serialization.Configuration.SchemaImporterExtensionElement&quot;></see> class using the specified name and type."
  syntax:
    content: public SchemaImporterExtensionElement (string name, Type type);
    parameters:
    - id: name
      type: System.String
      description: "The name of the new extension. The name must be unique."
    - id: type
      type: System.Type
      description: "The <xref:System.Type> of the new extension."
  overload: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.Name
  id: Name
  parent: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement
  langs:
  - csharp
  name: Name
  nameWithType: SchemaImporterExtensionElement.Name
  fullName: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.Name
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: "Gets or sets the name of the extension."
  remarks: "The name must be unique."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "The name of the extension."
  overload: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.Name*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.Properties
  id: Properties
  parent: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement
  langs:
  - csharp
  name: Properties
  nameWithType: SchemaImporterExtensionElement.Properties
  fullName: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.Properties
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.Type
  id: Type
  parent: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement
  langs:
  - csharp
  name: Type
  nameWithType: SchemaImporterExtensionElement.Type
  fullName: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.Type
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: "Gets or sets the type of the extension."
  syntax:
    content: public Type Type { get; set; }
    return:
      type: System.Type
      description: "A type of the extension."
  overload: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.Type*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.#ctor
  parent: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement
  isExternal: false
  name: SchemaImporterExtensionElement()
  nameWithType: SchemaImporterExtensionElement.SchemaImporterExtensionElement()
  fullName: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.SchemaImporterExtensionElement()
- uid: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.#ctor(System.String,System.String)
  parent: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement
  isExternal: false
  name: SchemaImporterExtensionElement(String,String)
  nameWithType: SchemaImporterExtensionElement.SchemaImporterExtensionElement(String,String)
  fullName: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.SchemaImporterExtensionElement(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.#ctor(System.String,System.Type)
  parent: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement
  isExternal: false
  name: SchemaImporterExtensionElement(String,Type)
  nameWithType: SchemaImporterExtensionElement.SchemaImporterExtensionElement(String,Type)
  fullName: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.SchemaImporterExtensionElement(String,Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.Name
  parent: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement
  isExternal: false
  name: Name
  nameWithType: SchemaImporterExtensionElement.Name
  fullName: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.Name
- uid: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.Properties
  parent: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement
  isExternal: false
  name: Properties
  nameWithType: SchemaImporterExtensionElement.Properties
  fullName: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.Type
  parent: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement
  isExternal: false
  name: Type
  nameWithType: SchemaImporterExtensionElement.Type
  fullName: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.Type
- uid: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.#ctor*
  parent: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement
  isExternal: false
  name: SchemaImporterExtensionElement
  nameWithType: SchemaImporterExtensionElement.SchemaImporterExtensionElement
- uid: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.Name*
  parent: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement
  isExternal: false
  name: Name
  nameWithType: SchemaImporterExtensionElement.Name
- uid: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.Properties*
  parent: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement
  isExternal: false
  name: Properties
  nameWithType: SchemaImporterExtensionElement.Properties
- uid: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement.Type*
  parent: System.Xml.Serialization.Configuration.SchemaImporterExtensionElement
  isExternal: false
  name: Type
  nameWithType: SchemaImporterExtensionElement.Type
