### YamlMime:ManagedReference
items:
- uid: System.Data.SqlClient.ApplicationIntent
  id: ApplicationIntent
  children:
  - System.Data.SqlClient.ApplicationIntent.ReadOnly
  - System.Data.SqlClient.ApplicationIntent.ReadWrite
  langs:
  - csharp
  name: ApplicationIntent
  nameWithType: ApplicationIntent
  fullName: System.Data.SqlClient.ApplicationIntent
  type: Enum
  summary: "Specifies a value for &lt;xref:System.Data.SqlClient.SqlConnectionStringBuilder.ApplicationIntent%2A&gt;. Possible values are <xref uid=&quot;langword_csharp_ReadWrite&quot; name=&quot;ReadWrite&quot; href=&quot;&quot;></xref> and <xref uid=&quot;langword_csharp_ReadOnly&quot; name=&quot;ReadOnly&quot; href=&quot;&quot;></xref>."
  syntax:
    content: public enum ApplicationIntent
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.SqlClient.ApplicationIntent.ReadOnly
  id: ReadOnly
  parent: System.Data.SqlClient.ApplicationIntent
  langs:
  - csharp
  name: ReadOnly
  nameWithType: ApplicationIntent.ReadOnly
  fullName: System.Data.SqlClient.ApplicationIntent.ReadOnly
  type: Field
  assemblies:
  - System.Data
  namespace: System.Data.SqlClient
  summary: "The application workload type when connecting to a server is read only."
  syntax:
    content: ReadOnly
    return:
      type: System.Data.SqlClient.ApplicationIntent
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.SqlClient.ApplicationIntent.ReadWrite
  id: ReadWrite
  parent: System.Data.SqlClient.ApplicationIntent
  langs:
  - csharp
  name: ReadWrite
  nameWithType: ApplicationIntent.ReadWrite
  fullName: System.Data.SqlClient.ApplicationIntent.ReadWrite
  type: Field
  assemblies:
  - System.Data
  namespace: System.Data.SqlClient
  summary: "The application workload type when connecting to a server is read write."
  syntax:
    content: ReadWrite
    return:
      type: System.Data.SqlClient.ApplicationIntent
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Data.SqlClient.ApplicationIntent.ReadOnly
  parent: System.Data.SqlClient.ApplicationIntent
  isExternal: false
  name: ReadOnly
  nameWithType: ApplicationIntent.ReadOnly
  fullName: System.Data.SqlClient.ApplicationIntent.ReadOnly
- uid: System.Data.SqlClient.ApplicationIntent
  parent: System.Data.SqlClient
  isExternal: false
  name: ApplicationIntent
  nameWithType: ApplicationIntent
  fullName: System.Data.SqlClient.ApplicationIntent
- uid: System.Data.SqlClient.ApplicationIntent.ReadWrite
  parent: System.Data.SqlClient.ApplicationIntent
  isExternal: false
  name: ReadWrite
  nameWithType: ApplicationIntent.ReadWrite
  fullName: System.Data.SqlClient.ApplicationIntent.ReadWrite
