### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  id: ProfileElement
  children:
  - System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.#ctor
  - System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ElementKey
  - System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ImplementationVisibility
  - System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Name
  - System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Properties
  - System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Workflows
  langs:
  - csharp
  name: ProfileElement
  nameWithType: ProfileElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  type: Class
  summary: "A configuration element that represents a <see cref=&quot;T:System.Activities.Tracking.TrackingProfile&quot;></see> and is used for adding a profile through the behavior element."
  syntax:
    content: 'public class ProfileElement : System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement.GetStringPairKey(System.String,System.String)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  langs:
  - csharp
  name: ProfileElement()
  nameWithType: ProfileElement.ProfileElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ProfileElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Activities.Tracking.Configuration.ProfileElement&quot;></see> class."
  syntax:
    content: public ProfileElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ElementKey
  id: ElementKey
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  langs:
  - csharp
  name: ElementKey
  nameWithType: ProfileElement.ElementKey
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ElementKey
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Gets a key that uniquely identifies the profile."
  syntax:
    content: public override object ElementKey { get; }
    return:
      type: System.Object
      description: "The element key."
  overload: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ElementKey*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ImplementationVisibility
  id: ImplementationVisibility
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  langs:
  - csharp
  name: ImplementationVisibility
  nameWithType: ProfileElement.ImplementationVisibility
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ImplementationVisibility
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Gets or sets the visibility mode of the tracking profile."
  remarks: "Tracking records from activities that form the implementation of activities can be filtered using the visibility modes described by <xref:System.Activities.Tracking.ImplementationVisibility>. This flag is used to subscribe for tracking records for all activities or only for the activities visible from the root of the workflow.       When the flag is set to <xref:System.Activities.Tracking.ImplementationVisibility>, only the root activity and its implementation are tracked. If the implementation contains activities that are composite activities, then the composite activity is tracked but not its implementation.       For more information, see <xref:System.Activities.Tracking.TrackingProfile.ImplementationVisibility%2A>."
  syntax:
    content: public System.Activities.Tracking.ImplementationVisibility ImplementationVisibility { get; set; }
    return:
      type: System.Activities.Tracking.ImplementationVisibility
      description: "The visibility mode of the tracking profile"
  overload: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ImplementationVisibility*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Name
  id: Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  langs:
  - csharp
  name: Name
  nameWithType: ProfileElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Name
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Gets or sets the name of the tracking profile."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "The name of the tracking profile."
  overload: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Name*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  langs:
  - csharp
  name: Properties
  nameWithType: ProfileElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Gets a <see cref=&quot;T:System.Configuration.ConfigurationPropertyCollection&quot;></see> that contains the properties associated with this element."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "The properties collection."
  overload: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Workflows
  id: Workflows
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  langs:
  - csharp
  name: Workflows
  nameWithType: ProfileElement.Workflows
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Workflows
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Gets the collection of <see cref=&quot;T:System.ServiceModel.Activities.Tracking.Configuration.ProfileWorkflowElement&quot;></see> elements associated with this <see cref=&quot;T:System.ServiceModel.Activities.Tracking.Configuration.ProfileElement&quot;></see>."
  remarks: "There is one <xref:System.ServiceModel.Activities.Tracking.Configuration.ProfileWorkflowElement> for each workflow in the profile."
  syntax:
    content: public System.ServiceModel.Activities.Tracking.Configuration.ProfileWorkflowElementCollection Workflows { get; }
    return:
      type: System.ServiceModel.Activities.Tracking.Configuration.ProfileWorkflowElementCollection
      description: "A collection of profile workflow query elements."
  overload: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Workflows*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  isExternal: false
  name: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.#ctor
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: ProfileElement()
  nameWithType: ProfileElement.ProfileElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ProfileElement()
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ElementKey
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: ElementKey
  nameWithType: ProfileElement.ElementKey
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ElementKey
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ImplementationVisibility
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: ImplementationVisibility
  nameWithType: ProfileElement.ImplementationVisibility
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ImplementationVisibility
- uid: System.Activities.Tracking.ImplementationVisibility
  parent: System.Activities.Tracking
  isExternal: false
  name: ImplementationVisibility
  nameWithType: ImplementationVisibility
  fullName: System.Activities.Tracking.ImplementationVisibility
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: Name
  nameWithType: ProfileElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Name
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: Properties
  nameWithType: ProfileElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Workflows
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: Workflows
  nameWithType: ProfileElement.Workflows
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Workflows
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileWorkflowElementCollection
  parent: System.ServiceModel.Activities.Tracking.Configuration
  isExternal: false
  name: ProfileWorkflowElementCollection
  nameWithType: ProfileWorkflowElementCollection
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileWorkflowElementCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.#ctor*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: ProfileElement
  nameWithType: ProfileElement.ProfileElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ElementKey*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: ElementKey
  nameWithType: ProfileElement.ElementKey
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ImplementationVisibility*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: ImplementationVisibility
  nameWithType: ProfileElement.ImplementationVisibility
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Name*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: Name
  nameWithType: ProfileElement.Name
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Properties*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: Properties
  nameWithType: ProfileElement.Properties
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Workflows*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: Workflows
  nameWithType: ProfileElement.Workflows
