### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ExtensionElement
  id: ExtensionElement
  children:
  - System.ServiceModel.Configuration.ExtensionElement.#ctor
  - System.ServiceModel.Configuration.ExtensionElement.#ctor(System.String)
  - System.ServiceModel.Configuration.ExtensionElement.#ctor(System.String,System.String)
  - System.ServiceModel.Configuration.ExtensionElement.Name
  - System.ServiceModel.Configuration.ExtensionElement.Properties
  - System.ServiceModel.Configuration.ExtensionElement.Type
  langs:
  - csharp
  name: ExtensionElement
  nameWithType: ExtensionElement
  fullName: System.ServiceModel.Configuration.ExtensionElement
  type: Class
  summary: "Represents a configuration element that defines an extension, which enables the user to create user-defined bindings, behaviors, etc."
  syntax:
    content: 'public class ExtensionElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ExtensionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ExtensionElement
  langs:
  - csharp
  name: ExtensionElement()
  nameWithType: ExtensionElement.ExtensionElement()
  fullName: System.ServiceModel.Configuration.ExtensionElement.ExtensionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.ExtensionElement&quot;></see> class."
  syntax:
    content: public ExtensionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.ExtensionElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ExtensionElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.Configuration.ExtensionElement
  langs:
  - csharp
  name: ExtensionElement(String)
  nameWithType: ExtensionElement.ExtensionElement(String)
  fullName: System.ServiceModel.Configuration.ExtensionElement.ExtensionElement(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.ExtensionElement&quot;></see> class with a specified name."
  syntax:
    content: public ExtensionElement (string name);
    parameters:
    - id: name
      type: System.String
      description: "A unique name of this configuration element."
  overload: System.ServiceModel.Configuration.ExtensionElement.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "\n    name is  or empty."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ExtensionElement.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.ServiceModel.Configuration.ExtensionElement
  langs:
  - csharp
  name: ExtensionElement(String,String)
  nameWithType: ExtensionElement.ExtensionElement(String,String)
  fullName: System.ServiceModel.Configuration.ExtensionElement.ExtensionElement(String,String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.ExtensionElement&quot;></see> class with a specified name and type."
  syntax:
    content: public ExtensionElement (string name, string type);
    parameters:
    - id: name
      type: System.String
      description: "A unique name of this configuration element."
    - id: type
      type: System.String
      description: "The type of this configuration element."
  overload: System.ServiceModel.Configuration.ExtensionElement.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "\n    type is  or empty.  \n  \n -or-  \n  \n name is  or empty."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ExtensionElement.Name
  id: Name
  parent: System.ServiceModel.Configuration.ExtensionElement
  langs:
  - csharp
  name: Name
  nameWithType: ExtensionElement.Name
  fullName: System.ServiceModel.Configuration.ExtensionElement.Name
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets a unique name of this configuration element."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "A unique name of this configuration element."
  overload: System.ServiceModel.Configuration.ExtensionElement.Name*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ExtensionElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ExtensionElement
  langs:
  - csharp
  name: Properties
  nameWithType: ExtensionElement.Properties
  fullName: System.ServiceModel.Configuration.ExtensionElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets a <see cref=&quot;T:System.Configuration.ConfigurationPropertyCollection&quot;></see> instance that contains a collection of <see cref=&quot;T:System.Configuration.ConfigurationProperty&quot;></see> objects that can be attributes or <see cref=&quot;T:System.Configuration.ConfigurationElement&quot;></see> objects of this configuration element."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A <see cref=&quot;T:System.Configuration.ConfigurationPropertyCollection&quot;></see> instance that contains a collection of <see cref=&quot;T:System.Configuration.ConfigurationProperty&quot;></see> objects that can be attributes or <see cref=&quot;T:System.Configuration.ConfigurationElement&quot;></see> objects of this configuration element."
  overload: System.ServiceModel.Configuration.ExtensionElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ExtensionElement.Type
  id: Type
  parent: System.ServiceModel.Configuration.ExtensionElement
  langs:
  - csharp
  name: Type
  nameWithType: ExtensionElement.Type
  fullName: System.ServiceModel.Configuration.ExtensionElement.Type
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets the type of this configuration element."
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "The type of this configuration element."
  overload: System.ServiceModel.Configuration.ExtensionElement.Type*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.ExtensionElement.#ctor
  parent: System.ServiceModel.Configuration.ExtensionElement
  isExternal: false
  name: ExtensionElement()
  nameWithType: ExtensionElement.ExtensionElement()
  fullName: System.ServiceModel.Configuration.ExtensionElement.ExtensionElement()
- uid: System.ServiceModel.Configuration.ExtensionElement.#ctor(System.String)
  parent: System.ServiceModel.Configuration.ExtensionElement
  isExternal: false
  name: ExtensionElement(String)
  nameWithType: ExtensionElement.ExtensionElement(String)
  fullName: System.ServiceModel.Configuration.ExtensionElement.ExtensionElement(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.ExtensionElement.#ctor(System.String,System.String)
  parent: System.ServiceModel.Configuration.ExtensionElement
  isExternal: false
  name: ExtensionElement(String,String)
  nameWithType: ExtensionElement.ExtensionElement(String,String)
  fullName: System.ServiceModel.Configuration.ExtensionElement.ExtensionElement(String,String)
- uid: System.ServiceModel.Configuration.ExtensionElement.Name
  parent: System.ServiceModel.Configuration.ExtensionElement
  isExternal: false
  name: Name
  nameWithType: ExtensionElement.Name
  fullName: System.ServiceModel.Configuration.ExtensionElement.Name
- uid: System.ServiceModel.Configuration.ExtensionElement.Properties
  parent: System.ServiceModel.Configuration.ExtensionElement
  isExternal: false
  name: Properties
  nameWithType: ExtensionElement.Properties
  fullName: System.ServiceModel.Configuration.ExtensionElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ExtensionElement.Type
  parent: System.ServiceModel.Configuration.ExtensionElement
  isExternal: false
  name: Type
  nameWithType: ExtensionElement.Type
  fullName: System.ServiceModel.Configuration.ExtensionElement.Type
- uid: System.ServiceModel.Configuration.ExtensionElement.#ctor*
  parent: System.ServiceModel.Configuration.ExtensionElement
  isExternal: false
  name: ExtensionElement
  nameWithType: ExtensionElement.ExtensionElement
- uid: System.ServiceModel.Configuration.ExtensionElement.Name*
  parent: System.ServiceModel.Configuration.ExtensionElement
  isExternal: false
  name: Name
  nameWithType: ExtensionElement.Name
- uid: System.ServiceModel.Configuration.ExtensionElement.Properties*
  parent: System.ServiceModel.Configuration.ExtensionElement
  isExternal: false
  name: Properties
  nameWithType: ExtensionElement.Properties
- uid: System.ServiceModel.Configuration.ExtensionElement.Type*
  parent: System.ServiceModel.Configuration.ExtensionElement
  isExternal: false
  name: Type
  nameWithType: ExtensionElement.Type
