### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection
  id: SystemIdentityModelSection
  children:
  - System.IdentityModel.Configuration.SystemIdentityModelSection.#ctor
  - System.IdentityModel.Configuration.SystemIdentityModelSection.Current
  - System.IdentityModel.Configuration.SystemIdentityModelSection.DefaultIdentityConfigurationElement
  - System.IdentityModel.Configuration.SystemIdentityModelSection.IdentityConfigurationElements
  - System.IdentityModel.Configuration.SystemIdentityModelSection.SectionName
  langs:
  - csharp
  name: SystemIdentityModelSection
  nameWithType: SystemIdentityModelSection
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection
  type: Class
  summary: "Represents the <xref uid=&quot;langword_csharp_&lt;system.identityModel&gt;&quot; name=&quot;&lt;system.identityModel&gt;&quot; href=&quot;&quot;></xref> section in a configuration file. This class cannot be inherited."
  remarks: "Within the `<system.identityModel>` section, multiple identity configurations may be defined, each with a unique name and defining a specific configuration; for example, `<identityConfiguration name=&quot;alternate&quot; >`. The collection of the identity configuration elements defined in the identity model section can be retrieved by using the <xref:System.IdentityModel.Configuration.SystemIdentityModelSection.IdentityConfigurationElements%2A> property.       If a name is not specified on an identity configuration element, the element defines the default identity configuration. The default identity configuration is always used for passive federation scenarios. Only one default configuration may exist in the identity model configuration section. It can be retrieved by using the <xref:System.IdentityModel.Configuration.SystemIdentityModelSection.DefaultIdentityConfigurationElement%2A> property."
  syntax:
    content: 'public sealed class SystemIdentityModelSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  langs:
  - csharp
  name: SystemIdentityModelSection()
  nameWithType: SystemIdentityModelSection.SystemIdentityModelSection()
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.SystemIdentityModelSection()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.IdentityModel.Configuration.SystemIdentityModelSection&quot;></see> class."
  syntax:
    content: public SystemIdentityModelSection ();
    parameters: []
  overload: System.IdentityModel.Configuration.SystemIdentityModelSection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.Current
  id: Current
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  langs:
  - csharp
  name: Current
  nameWithType: SystemIdentityModelSection.Current
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.Current
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Gets the current <see cref=&quot;T:System.IdentityModel.Configuration.SystemIdentityModelSection&quot;></see> reference."
  syntax:
    content: public static System.IdentityModel.Configuration.SystemIdentityModelSection Current { get; }
    return:
      type: System.IdentityModel.Configuration.SystemIdentityModelSection
      description: "The current <see cref=&quot;T:System.IdentityModel.Configuration.SystemIdentityModelSection&quot;></see> reference."
  overload: System.IdentityModel.Configuration.SystemIdentityModelSection.Current*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.DefaultIdentityConfigurationElement
  id: DefaultIdentityConfigurationElement
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  langs:
  - csharp
  name: DefaultIdentityConfigurationElement
  nameWithType: SystemIdentityModelSection.DefaultIdentityConfigurationElement
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.DefaultIdentityConfigurationElement
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Gets the default (unnamed) <see cref=&quot;T:System.IdentityModel.Configuration.IdentityConfigurationElement&quot;></see> from the configuration file."
  remarks: "The `<system.identityModel>` section can contain only one default `<identityConfiguration>` element. The default identity configuration is always used for passive federation scenarios."
  syntax:
    content: public static System.IdentityModel.Configuration.IdentityConfigurationElement DefaultIdentityConfigurationElement { get; }
    return:
      type: System.IdentityModel.Configuration.IdentityConfigurationElement
      description: "The default (unnamed) <xref uid=&quot;langword_csharp_&lt;identityConfiguration&gt;&quot; name=&quot;&lt;identityConfiguration&gt;&quot; href=&quot;&quot;></xref> element."
  overload: System.IdentityModel.Configuration.SystemIdentityModelSection.DefaultIdentityConfigurationElement*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.IdentityConfigurationElements
  id: IdentityConfigurationElements
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  langs:
  - csharp
  name: IdentityConfigurationElements
  nameWithType: SystemIdentityModelSection.IdentityConfigurationElements
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.IdentityConfigurationElements
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Gets the <see cref=&quot;T:System.IdentityModel.Configuration.IdentityConfigurationElementCollection&quot;></see> from the configuration file."
  syntax:
    content: public System.IdentityModel.Configuration.IdentityConfigurationElementCollection IdentityConfigurationElements { get; }
    return:
      type: System.IdentityModel.Configuration.IdentityConfigurationElementCollection
      description: "A collection that contains all of the <xref uid=&quot;langword_csharp_&lt;identityConfiguration&gt;&quot; name=&quot;&lt;identityConfiguration&gt;&quot; href=&quot;&quot;></xref> elements in the <xref uid=&quot;langword_csharp_&lt;system.identityModel&gt;&quot; name=&quot;&lt;system.identityModel&gt;&quot; href=&quot;&quot;></xref> section."
  overload: System.IdentityModel.Configuration.SystemIdentityModelSection.IdentityConfigurationElements*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.SectionName
  id: SectionName
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  langs:
  - csharp
  name: SectionName
  nameWithType: SystemIdentityModelSection.SectionName
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.SectionName
  type: Field
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "The name of the configuration section as defined by Windows Identity Foundation (WIF); system.identityModel."
  syntax:
    content: public const string SectionName;
    return:
      type: System.String
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.#ctor
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  isExternal: false
  name: SystemIdentityModelSection()
  nameWithType: SystemIdentityModelSection.SystemIdentityModelSection()
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.SystemIdentityModelSection()
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.Current
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  isExternal: false
  name: Current
  nameWithType: SystemIdentityModelSection.Current
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.Current
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection
  parent: System.IdentityModel.Configuration
  isExternal: false
  name: SystemIdentityModelSection
  nameWithType: SystemIdentityModelSection
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.DefaultIdentityConfigurationElement
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  isExternal: false
  name: DefaultIdentityConfigurationElement
  nameWithType: SystemIdentityModelSection.DefaultIdentityConfigurationElement
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.DefaultIdentityConfigurationElement
- uid: System.IdentityModel.Configuration.IdentityConfigurationElement
  parent: System.IdentityModel.Configuration
  isExternal: false
  name: IdentityConfigurationElement
  nameWithType: IdentityConfigurationElement
  fullName: System.IdentityModel.Configuration.IdentityConfigurationElement
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.IdentityConfigurationElements
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  isExternal: false
  name: IdentityConfigurationElements
  nameWithType: SystemIdentityModelSection.IdentityConfigurationElements
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.IdentityConfigurationElements
- uid: System.IdentityModel.Configuration.IdentityConfigurationElementCollection
  parent: System.IdentityModel.Configuration
  isExternal: false
  name: IdentityConfigurationElementCollection
  nameWithType: IdentityConfigurationElementCollection
  fullName: System.IdentityModel.Configuration.IdentityConfigurationElementCollection
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.SectionName
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  isExternal: false
  name: SectionName
  nameWithType: SystemIdentityModelSection.SectionName
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.SectionName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.#ctor*
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  isExternal: false
  name: SystemIdentityModelSection
  nameWithType: SystemIdentityModelSection.SystemIdentityModelSection
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.Current*
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  isExternal: false
  name: Current
  nameWithType: SystemIdentityModelSection.Current
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.DefaultIdentityConfigurationElement*
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  isExternal: false
  name: DefaultIdentityConfigurationElement
  nameWithType: SystemIdentityModelSection.DefaultIdentityConfigurationElement
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.IdentityConfigurationElements*
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  isExternal: false
  name: IdentityConfigurationElements
  nameWithType: SystemIdentityModelSection.IdentityConfigurationElements
