### YamlMime:ManagedReference
items:
- uid: System.Xml.Serialization.Configuration.DateTimeSerializationSection
  id: DateTimeSerializationSection
  children:
  - System.Xml.Serialization.Configuration.DateTimeSerializationSection.#ctor
  - System.Xml.Serialization.Configuration.DateTimeSerializationSection.Mode
  - System.Xml.Serialization.Configuration.DateTimeSerializationSection.Properties
  langs:
  - csharp
  name: DateTimeSerializationSection
  nameWithType: DateTimeSerializationSection
  fullName: System.Xml.Serialization.Configuration.DateTimeSerializationSection
  type: Class
  summary: "Handles configuration settings for XML serialization of &lt;xref:System.DateTime&gt; instances."
  remarks: "This class handles the configuration element [\\<dateTimeSerialization> Element](../Topic/%3CdateTimeSerialization%3E%20Element.md) found under the [\\<system.xml.serialization> Element](../Topic/%3Csystem.xml.serialization%3E%20Element.md). For more information about configuration files, see [Configuration File Schema](../Topic/Configuration%20File%20Schema%20for%20the%20.NET%20Framework.md)."
  syntax:
    content: 'public sealed class DateTimeSerializationSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Xml.Serialization.Configuration.DateTimeSerializationSection.#ctor
  id: '#ctor'
  parent: System.Xml.Serialization.Configuration.DateTimeSerializationSection
  langs:
  - csharp
  name: DateTimeSerializationSection()
  nameWithType: DateTimeSerializationSection.DateTimeSerializationSection()
  fullName: System.Xml.Serialization.Configuration.DateTimeSerializationSection.DateTimeSerializationSection()
  type: Constructor
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Xml.Serialization.Configuration.DateTimeSerializationSection&quot;></see> class."
  syntax:
    content: public DateTimeSerializationSection ();
    parameters: []
  overload: System.Xml.Serialization.Configuration.DateTimeSerializationSection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Xml.Serialization.Configuration.DateTimeSerializationSection.Mode
  id: Mode
  parent: System.Xml.Serialization.Configuration.DateTimeSerializationSection
  langs:
  - csharp
  name: Mode
  nameWithType: DateTimeSerializationSection.Mode
  fullName: System.Xml.Serialization.Configuration.DateTimeSerializationSection.Mode
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: "Gets or sets a value that determines the serialization format."
  remarks: "This property is used when handling the `mode` attribute of the [\\<dateTimeSerialization> Element](../Topic/%3CdateTimeSerialization%3E%20Element.md)."
  syntax:
    content: public System.Xml.Serialization.Configuration.DateTimeSerializationSection.DateTimeSerializationMode Mode { get; set; }
    return:
      type: System.Xml.Serialization.Configuration.DateTimeSerializationSection.DateTimeSerializationMode
      description: "One of the &lt;xref:System.Xml.Serialization.Configuration.DateTimeSerializationSection.DateTimeSerializationMode&gt; values."
  overload: System.Xml.Serialization.Configuration.DateTimeSerializationSection.Mode*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Xml.Serialization.Configuration.DateTimeSerializationSection.Properties
  id: Properties
  parent: System.Xml.Serialization.Configuration.DateTimeSerializationSection
  langs:
  - csharp
  name: Properties
  nameWithType: DateTimeSerializationSection.Properties
  fullName: System.Xml.Serialization.Configuration.DateTimeSerializationSection.Properties
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Xml.Serialization.Configuration.DateTimeSerializationSection.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Xml.Serialization.Configuration.DateTimeSerializationSection.#ctor
  parent: System.Xml.Serialization.Configuration.DateTimeSerializationSection
  isExternal: false
  name: DateTimeSerializationSection()
  nameWithType: DateTimeSerializationSection.DateTimeSerializationSection()
  fullName: System.Xml.Serialization.Configuration.DateTimeSerializationSection.DateTimeSerializationSection()
- uid: System.Xml.Serialization.Configuration.DateTimeSerializationSection.Mode
  parent: System.Xml.Serialization.Configuration.DateTimeSerializationSection
  isExternal: false
  name: Mode
  nameWithType: DateTimeSerializationSection.Mode
  fullName: System.Xml.Serialization.Configuration.DateTimeSerializationSection.Mode
- uid: System.Xml.Serialization.Configuration.DateTimeSerializationSection.DateTimeSerializationMode
  parent: System.Xml.Serialization.Configuration
  isExternal: false
  name: DateTimeSerializationSection+DateTimeSerializationMode
  nameWithType: DateTimeSerializationSection+DateTimeSerializationMode
  fullName: System.Xml.Serialization.Configuration.DateTimeSerializationSection+DateTimeSerializationMode
- uid: System.Xml.Serialization.Configuration.DateTimeSerializationSection.Properties
  parent: System.Xml.Serialization.Configuration.DateTimeSerializationSection
  isExternal: false
  name: Properties
  nameWithType: DateTimeSerializationSection.Properties
  fullName: System.Xml.Serialization.Configuration.DateTimeSerializationSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Xml.Serialization.Configuration.DateTimeSerializationSection.#ctor*
  parent: System.Xml.Serialization.Configuration.DateTimeSerializationSection
  isExternal: false
  name: DateTimeSerializationSection
  nameWithType: DateTimeSerializationSection.DateTimeSerializationSection
- uid: System.Xml.Serialization.Configuration.DateTimeSerializationSection.Mode*
  parent: System.Xml.Serialization.Configuration.DateTimeSerializationSection
  isExternal: false
  name: Mode
  nameWithType: DateTimeSerializationSection.Mode
- uid: System.Xml.Serialization.Configuration.DateTimeSerializationSection.Properties*
  parent: System.Xml.Serialization.Configuration.DateTimeSerializationSection
  isExternal: false
  name: Properties
  nameWithType: DateTimeSerializationSection.Properties
