### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.UrlMapping
  id: UrlMapping
  children:
  - System.Web.Configuration.UrlMapping.#ctor(System.String,System.String)
  - System.Web.Configuration.UrlMapping.MappedUrl
  - System.Web.Configuration.UrlMapping.Properties
  - System.Web.Configuration.UrlMapping.Url
  langs:
  - csharp
  name: UrlMapping
  nameWithType: UrlMapping
  fullName: System.Web.Configuration.UrlMapping
  type: Class
  summary: "Maps a URL that is displayed to users to the URL of a page in your Web application. This class cannot be inherited."
  remarks: "The UrlMapping class allows you to map a URL that is displayed to users to a URL that exists in your Web application. Adding a UrlMapping object to a <xref:System.Web.Configuration.UrlMappingCollection> is the programmatic equivalent to including an `add` element in the `urlMappings` section of a configuration file.       Each UrlMapping object contains two properties identifying a URL. One property specifies the URL shown to the user; the other specifies a URL in your Web application. Trailing white-space characters are ignored in both the <xref:System.Web.Configuration.UrlMapping.Url%2A> and <xref:System.Web.Configuration.UrlMapping.MappedUrl%2A> properties.      > [!NOTE] >  The UrlMapping property can write information into the related section of the configuration file according to the restrictions defined by the section property <xref:System.Configuration.SectionInformation.AllowDefinition%2A> whose value is <xref:System.Configuration.ConfigurationAllowDefinition>. Any attempt to write in a configuration file at a level not allowed in the hierarchy will result in an error message generated by the parser. However, you can use this class to read configuration information at any level in the hierarchy."
  example:
  - "The following example uses the <xref:System.Web.Configuration.UrlMappingsSection> of the Web.config file to map two URLs, and adds a mapping for an additional URL. When you modify and save the Web.config file, your application restarts.  \n  \n [!CODE [System.Web.Configuration.UrlMapping2#3](../CodeSnippet/VS_Snippets_WebNet/System.Web.Configuration.UrlMapping2#3)]  \n[!code-cs[System.Web.Configuration.UrlMapping2#1](~/add/codesnippet/CSharp/t-system.web.configurati_10_2.aspx)]\n[!code-vb[System.Web.Configuration.UrlMapping2#1](~/add/codesnippet/VisualBasic/t-system.web.configurati_10_2.aspx)]"
  syntax:
    content: 'public sealed class UrlMapping : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.UrlMapping.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.UrlMapping
  langs:
  - csharp
  name: UrlMapping(String,String)
  nameWithType: UrlMapping.UrlMapping(String,String)
  fullName: System.Web.Configuration.UrlMapping.UrlMapping(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Web.Configuration.UrlMapping&quot;></see> class."
  remarks: "The UrlMapping constructor is intended primarily for internal use by ASP.NET. You do not need to derive from this class, and because it can be used to modify the Web.config file, you will probably never need to use it in code."
  example:
  - "The following example uses the <xref:System.Web.Configuration.UrlMappingsSection> of the Web.config file to map two URLs, and adds a mapping for an additional URL. When you modify and save the Web.config file, your application restarts.  \n  \n [!CODE [System.Web.Configuration.UrlMapping2#3](../CodeSnippet/VS_Snippets_WebNet/System.Web.Configuration.UrlMapping2#3)]  \n[!code-cs[System.Web.Configuration.UrlMapping2#1](~/add/codesnippet/CSharp/m-system.web.configurati_60_2.aspx)]\n[!code-vb[System.Web.Configuration.UrlMapping2#1](~/add/codesnippet/VisualBasic/m-system.web.configurati_60_2.aspx)]"
  syntax:
    content: public UrlMapping (string url, string mappedUrl);
    parameters:
    - id: url
      type: System.String
      description: "The URL to be displayed to the user."
    - id: mappedUrl
      type: System.String
      description: "A URL that exists in your Web application."
  overload: System.Web.Configuration.UrlMapping.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.UrlMapping.MappedUrl
  id: MappedUrl
  parent: System.Web.Configuration.UrlMapping
  langs:
  - csharp
  name: MappedUrl
  nameWithType: UrlMapping.MappedUrl
  fullName: System.Web.Configuration.UrlMapping.MappedUrl
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "A URL in your Web application."
  remarks: "The MappedUrl property is the programmatic equivalent of the `mappedUrl` attribute of the `add` element in the `urlMappings` section of a configuration file.      > [!NOTE] >  When using IIS 5.0, if you use the MappedUrl property to map from a supported page type (such as an .aspx file) to an unsupported page type (such as an .asp page), an error will occur. This type of mapping is supported in IIS version 6.0."
  example:
  - "The following code example shows how to obtain the MappedUrl property. This example is from a larger example for the <xref:System.Web.Configuration.UrlMapping> class.  \n  \n [!code-cs[System.Web.Configuration.UrlMapping2#4](~/add/codesnippet/CSharp/p-system.web.configurati_113_1.aspx)]\n [!code-vb[System.Web.Configuration.UrlMapping2#4](~/add/codesnippet/VisualBasic/p-system.web.configurati_113_1.aspx)]"
  syntax:
    content: public string MappedUrl { get; }
    return:
      type: System.String
      description: "The URL in your Web application that has been mapped to the value specified by the &lt;xref:System.Web.Configuration.UrlMapping.Url%2A&gt; property."
  overload: System.Web.Configuration.UrlMapping.MappedUrl*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.UrlMapping.Properties
  id: Properties
  parent: System.Web.Configuration.UrlMapping
  langs:
  - csharp
  name: Properties
  nameWithType: UrlMapping.Properties
  fullName: System.Web.Configuration.UrlMapping.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Web.Configuration.UrlMapping.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.UrlMapping.Url
  id: Url
  parent: System.Web.Configuration.UrlMapping
  langs:
  - csharp
  name: Url
  nameWithType: UrlMapping.Url
  fullName: System.Web.Configuration.UrlMapping.Url
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets the URL that is displayed to the user."
  remarks: "The Url property is the programmatic equivalent of the `Url` attribute of the `add` element in the `urlMappings` section of a configuration file."
  example:
  - For an example, see the <xref:System.Web.Configuration.UrlMapping> class overview.
  syntax:
    content: public string Url { get; }
    return:
      type: System.String
      description: "The URL that is displayed to the user."
  overload: System.Web.Configuration.UrlMapping.Url*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.UrlMapping.#ctor(System.String,System.String)
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: UrlMapping(String,String)
  nameWithType: UrlMapping.UrlMapping(String,String)
  fullName: System.Web.Configuration.UrlMapping.UrlMapping(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.UrlMapping.MappedUrl
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: MappedUrl
  nameWithType: UrlMapping.MappedUrl
  fullName: System.Web.Configuration.UrlMapping.MappedUrl
- uid: System.Web.Configuration.UrlMapping.Properties
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: Properties
  nameWithType: UrlMapping.Properties
  fullName: System.Web.Configuration.UrlMapping.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.UrlMapping.Url
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: Url
  nameWithType: UrlMapping.Url
  fullName: System.Web.Configuration.UrlMapping.Url
- uid: System.Web.Configuration.UrlMapping.#ctor*
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: UrlMapping
  nameWithType: UrlMapping.UrlMapping
- uid: System.Web.Configuration.UrlMapping.MappedUrl*
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: MappedUrl
  nameWithType: UrlMapping.MappedUrl
- uid: System.Web.Configuration.UrlMapping.Properties*
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: Properties
  nameWithType: UrlMapping.Properties
- uid: System.Web.Configuration.UrlMapping.Url*
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: Url
  nameWithType: UrlMapping.Url
