### YamlMime:ManagedReference
items:
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  id: WorkflowRuntimeServiceElement
  children:
  - System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.#ctor
  - System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters
  - System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Type
  langs:
  - csharp
  name: WorkflowRuntimeServiceElement
  nameWithType: WorkflowRuntimeServiceElement
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  type: Class
  summary: "Represents a configuration element for a service to be added to the workflow runtime engine."
  remarks: "> [!NOTE] >  [!INCLUDE[DeprecatedContent](~/add/includes/deprecatedcontent-md.md)]       A WorkflowRuntimeServiceElement specifies a host service that should be initialized and activated by the workflow runtime engine. It corresponds to a host service specified in the <`Services`> element in a configuration file. Because the service specified in a WorkflowRuntimeServiceElement will be initialized by the workflow runtime engine it must have at least one constructor that matches one of the following four signatures (the workflow runtime engine will try to match these signatures in the order shown):       Service(WorkflowRuntime runtime, NameValueCollection parameters)       Service(WorkflowRuntime runtime)       Service(NameValueCollection parameters)       Service()"
  syntax:
    content: >-
      [System.Obsolete("The System.Workflow.* types are deprecated.  Instead, please use the new types from System.Activities.*")]

      public class WorkflowRuntimeServiceElement : System.Configuration.ConfigurationElement
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.#ctor
  id: '#ctor'
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  langs:
  - csharp
  name: WorkflowRuntimeServiceElement()
  nameWithType: WorkflowRuntimeServiceElement.WorkflowRuntimeServiceElement()
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.WorkflowRuntimeServiceElement()
  type: Constructor
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement&quot;></see> class."
  remarks: "If you use this constructor, you must explicitly set <xref:System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Type%2A>."
  syntax:
    content: public WorkflowRuntimeServiceElement ();
    parameters: []
  overload: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  id: OnDeserializeUnrecognizedAttribute(System.String,System.String)
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  langs:
  - csharp
  name: OnDeserializeUnrecognizedAttribute(String,String)
  nameWithType: WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute(String,String)
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute(String,String)
  type: Method
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime.Configuration
  summary: "Called when an unknown attribute is encountered while deserializing the <see cref=&quot;T:System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement&quot;></see>."
  remarks: "The name-value pair specified by name and value is added to the <xref:System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters%2A> collection. Any attributes other than `type` that are specified in an <`add`> element to the <`Services`> element in the configuration file are added as a name-value pair to the <xref:System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters%2A> collection."
  syntax:
    content: protected override bool OnDeserializeUnrecognizedAttribute (string name, string value);
    parameters:
    - id: name
      type: System.String
      description: "The name of the unrecognized attribute."
    - id: value
      type: System.String
      description: "The value of the unrecognized attribute."
    return:
      type: System.Boolean
      description: "To be added."
  overload: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters
  id: Parameters
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  langs:
  - csharp
  name: Parameters
  nameWithType: WorkflowRuntimeServiceElement.Parameters
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters
  type: Property
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime.Configuration
  summary: "Gets the parameters for this service."
  syntax:
    content: public System.Collections.Specialized.NameValueCollection Parameters { get; }
    return:
      type: System.Collections.Specialized.NameValueCollection
      description: "A <see cref=&quot;T:System.Collections.Specialized.NameValueCollection&quot;></see> that specifies the parameters for the service."
  overload: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Type
  id: Type
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  langs:
  - csharp
  name: Type
  nameWithType: WorkflowRuntimeServiceElement.Type
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Type
  type: Property
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime.Configuration
  summary: "Gets or sets the assembly-qualified type name of the service."
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "The assembly-qualified type name of the service."
  overload: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Type*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "An attempt to set Type to a null reference is made."
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.#ctor
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  isExternal: false
  name: WorkflowRuntimeServiceElement()
  nameWithType: WorkflowRuntimeServiceElement.WorkflowRuntimeServiceElement()
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.WorkflowRuntimeServiceElement()
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  isExternal: false
  name: OnDeserializeUnrecognizedAttribute(String,String)
  nameWithType: WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute(String,String)
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute(String,String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  isExternal: false
  name: Parameters
  nameWithType: WorkflowRuntimeServiceElement.Parameters
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters
- uid: System.Collections.Specialized.NameValueCollection
  parent: System.Collections.Specialized
  isExternal: false
  name: NameValueCollection
  nameWithType: NameValueCollection
  fullName: System.Collections.Specialized.NameValueCollection
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Type
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  isExternal: false
  name: Type
  nameWithType: WorkflowRuntimeServiceElement.Type
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Type
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.#ctor*
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  isExternal: false
  name: WorkflowRuntimeServiceElement
  nameWithType: WorkflowRuntimeServiceElement.WorkflowRuntimeServiceElement
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute*
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  isExternal: false
  name: OnDeserializeUnrecognizedAttribute
  nameWithType: WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters*
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  isExternal: false
  name: Parameters
  nameWithType: WorkflowRuntimeServiceElement.Parameters
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Type*
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  isExternal: false
  name: Type
  nameWithType: WorkflowRuntimeServiceElement.Type
