### YamlMime:ManagedReference
items:
- uid: System.Configuration.SubclassTypeValidator
  id: SubclassTypeValidator
  children:
  - System.Configuration.SubclassTypeValidator.#ctor(System.Type)
  - System.Configuration.SubclassTypeValidator.CanValidate(System.Type)
  - System.Configuration.SubclassTypeValidator.Validate(System.Object)
  langs:
  - csharp
  name: SubclassTypeValidator
  nameWithType: SubclassTypeValidator
  fullName: System.Configuration.SubclassTypeValidator
  type: Class
  summary: "Validates that an object is a derived class of a specified type."
  remarks: "The SubclassTypeValidator class is used to ensure that an object meets specific criteria. The criteria for validation is established when an instance of the SubclassTypeValidator class is created.       The <xref:System.Configuration.SubclassTypeValidator.CanValidate%2A> method determines whether the type of the object being validated is in fact a <xref:System.Type>. The object being validated is passed as a parameter of the <xref:System.Configuration.SubclassTypeValidator.Validate%2A> method. This method first verifies that the object to validate is not `null`, and then verifies that the object is a derived class of the expected type."
  syntax:
    content: 'public sealed class SubclassTypeValidator : System.Configuration.ConfigurationValidatorBase'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationValidatorBase
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SubclassTypeValidator.#ctor(System.Type)
  id: '#ctor(System.Type)'
  parent: System.Configuration.SubclassTypeValidator
  langs:
  - csharp
  name: SubclassTypeValidator(Type)
  nameWithType: SubclassTypeValidator.SubclassTypeValidator(Type)
  fullName: System.Configuration.SubclassTypeValidator.SubclassTypeValidator(Type)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.SubclassTypeValidator&quot;></see> class."
  remarks: "The criteria for validation is based on the `baseClass` parameter."
  syntax:
    content: public SubclassTypeValidator (Type baseClass);
    parameters:
    - id: baseClass
      type: System.Type
      description: "The base class to validate against."
  overload: System.Configuration.SubclassTypeValidator.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "\n    baseClass is ."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SubclassTypeValidator.CanValidate(System.Type)
  id: CanValidate(System.Type)
  parent: System.Configuration.SubclassTypeValidator
  langs:
  - csharp
  name: CanValidate(Type)
  nameWithType: SubclassTypeValidator.CanValidate(Type)
  fullName: System.Configuration.SubclassTypeValidator.CanValidate(Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Determines whether an object can be validated based on type."
  remarks: "The CanValidate method determines whether the type of the object being validated is in fact a <xref:System.Type>."
  syntax:
    content: public override bool CanValidate (Type type);
    parameters:
    - id: type
      type: System.Type
      description: "The object type."
    return:
      type: System.Boolean
      description: "To be added."
  overload: System.Configuration.SubclassTypeValidator.CanValidate*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SubclassTypeValidator.Validate(System.Object)
  id: Validate(System.Object)
  parent: System.Configuration.SubclassTypeValidator
  langs:
  - csharp
  name: Validate(Object)
  nameWithType: SubclassTypeValidator.Validate(Object)
  fullName: System.Configuration.SubclassTypeValidator.Validate(Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Determines whether the value of an object is valid."
  remarks: "When an instance of the <xref:System.Configuration.SubclassTypeValidator> class is created, the base class is provided and used as evaluation criteria. The object to validate is passed as a parameter of the Validate method. This method performs the validation check between the base class and the parameter object."
  syntax:
    content: public override void Validate (object value);
    parameters:
    - id: value
      type: System.Object
      description: "The object value."
  overload: System.Configuration.SubclassTypeValidator.Validate*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "\n    value is not of a <xref:System.Type> that can be derived from baseClass as defined in the constructor."
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.SubclassTypeValidator.#ctor(System.Type)
  parent: System.Configuration.SubclassTypeValidator
  isExternal: false
  name: SubclassTypeValidator(Type)
  nameWithType: SubclassTypeValidator.SubclassTypeValidator(Type)
  fullName: System.Configuration.SubclassTypeValidator.SubclassTypeValidator(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.SubclassTypeValidator.CanValidate(System.Type)
  parent: System.Configuration.SubclassTypeValidator
  isExternal: false
  name: CanValidate(Type)
  nameWithType: SubclassTypeValidator.CanValidate(Type)
  fullName: System.Configuration.SubclassTypeValidator.CanValidate(Type)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.SubclassTypeValidator.Validate(System.Object)
  parent: System.Configuration.SubclassTypeValidator
  isExternal: false
  name: Validate(Object)
  nameWithType: SubclassTypeValidator.Validate(Object)
  fullName: System.Configuration.SubclassTypeValidator.Validate(Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.SubclassTypeValidator.#ctor*
  parent: System.Configuration.SubclassTypeValidator
  isExternal: false
  name: SubclassTypeValidator
  nameWithType: SubclassTypeValidator.SubclassTypeValidator
- uid: System.Configuration.SubclassTypeValidator.CanValidate*
  parent: System.Configuration.SubclassTypeValidator
  isExternal: false
  name: CanValidate
  nameWithType: SubclassTypeValidator.CanValidate
- uid: System.Configuration.SubclassTypeValidator.Validate*
  parent: System.Configuration.SubclassTypeValidator
  isExternal: false
  name: Validate
  nameWithType: SubclassTypeValidator.Validate
