### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationSettings
  id: ConfigurationSettings
  children:
  - System.Configuration.ConfigurationSettings.AppSettings
  - System.Configuration.ConfigurationSettings.GetConfig(System.String)
  langs:
  - csharp
  name: ConfigurationSettings
  nameWithType: ConfigurationSettings
  fullName: System.Configuration.ConfigurationSettings
  type: Class
  summary: "Provides runtime versions 1.0 and 1.1 support for reading configuration sections and common configuration settings."
  remarks: "Using the static methods and properties of the ConfigurationSettings type is the recommended method for reading configuration information at runtime for versions 1.0 and 1.1 applications.      > [!NOTE] >  The ConfigurationSettings class provides backward compatibility only. For new applications you should use the <xref:System.Configuration.ConfigurationManager> class or <xref:System.Web.Configuration.WebConfigurationManager> class instead. To use these two classes, you must add a reference in your project or application to the System.Configuration namespace."
  syntax:
    content: public sealed class ConfigurationSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationSettings.AppSettings
  id: AppSettings
  parent: System.Configuration.ConfigurationSettings
  langs:
  - csharp
  name: AppSettings
  nameWithType: ConfigurationSettings.AppSettings
  fullName: System.Configuration.ConfigurationSettings.AppSettings
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Gets a read-only <see cref=&quot;T:System.Collections.Specialized.NameValueCollection&quot;></see> of the application settings section of the configuration file."
  remarks: "The `appSettings` section element of the configuration file contains a series of name/value pairs that your application can use for any purpose.       This method is deprecated and is maintained for backward compatibility. Please use the GetSection method instead.      > [!NOTE] >  The <xref:System.Configuration.ConfigurationSettings> class provides backward compatibility only. You should use the <xref:System.Configuration.ConfigurationManager> class or <xref:System.Web.Configuration.WebConfigurationManager> class instead."
  syntax:
    content: public static System.Collections.Specialized.NameValueCollection AppSettings { get; }
    return:
      type: System.Collections.Specialized.NameValueCollection
      description: "A read-only <see cref=&quot;T:System.Collections.Specialized.NameValueCollection&quot;></see> of the application settings section from the configuration file."
  overload: System.Configuration.ConfigurationSettings.AppSettings*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationSettings.GetConfig(System.String)
  id: GetConfig(System.String)
  parent: System.Configuration.ConfigurationSettings
  langs:
  - csharp
  name: GetConfig(String)
  nameWithType: ConfigurationSettings.GetConfig(String)
  fullName: System.Configuration.ConfigurationSettings.GetConfig(String)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Returns the <see cref=&quot;T:System.Configuration.ConfigurationSection&quot;></see> object for the passed configuration section name and path."
  remarks: "This method is deprecated and is maintained for backward compatibility. Please use the GetSection method instead."
  syntax:
    content: public static object GetConfig (string sectionName);
    parameters:
    - id: sectionName
      type: System.String
      description: "A configuration name and path, such as &quot;system.net/settings&quot;."
    return:
      type: System.Object
      description: "To be added."
  overload: System.Configuration.ConfigurationSettings.GetConfig*
  exceptions:
  - type: System.Configuration.ConfigurationException
    commentId: T:System.Configuration.ConfigurationException
    description: "Unable to retrieve the requested section."
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationSettings.AppSettings
  parent: System.Configuration.ConfigurationSettings
  isExternal: false
  name: AppSettings
  nameWithType: ConfigurationSettings.AppSettings
  fullName: System.Configuration.ConfigurationSettings.AppSettings
- uid: System.Collections.Specialized.NameValueCollection
  parent: System.Collections.Specialized
  isExternal: false
  name: NameValueCollection
  nameWithType: NameValueCollection
  fullName: System.Collections.Specialized.NameValueCollection
- uid: System.Configuration.ConfigurationSettings.GetConfig(System.String)
  parent: System.Configuration.ConfigurationSettings
  isExternal: false
  name: GetConfig(String)
  nameWithType: ConfigurationSettings.GetConfig(String)
  fullName: System.Configuration.ConfigurationSettings.GetConfig(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationSettings.AppSettings*
  parent: System.Configuration.ConfigurationSettings
  isExternal: false
  name: AppSettings
  nameWithType: ConfigurationSettings.AppSettings
- uid: System.Configuration.ConfigurationSettings.GetConfig*
  parent: System.Configuration.ConfigurationSettings
  isExternal: false
  name: GetConfig
  nameWithType: ConfigurationSettings.GetConfig
