### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler
  id: HttpCapabilitiesSectionHandler
  children:
  - System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor
  - System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: HttpCapabilitiesSectionHandler
  nameWithType: HttpCapabilitiesSectionHandler
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler
  type: Class
  summary: "Assists in reading in the <xref uid=&quot;langword_csharp_&lt;browserCaps&gt;&quot; name=&quot;&lt;browserCaps&gt;&quot; href=&quot;&quot;></xref> section of a configuration file and creating an instance of the <see cref=&quot;T:System.Web.HttpBrowserCapabilities&quot;></see> class that contains the capabilities information for the client browser."
  remarks: "The HttpCapabilitiesSectionHandler class and the corresponding `<browserCaps>` configuration section have been deprecated in the .NET Framework version 2.0. The preferred method for managing browser capabilities is through browser definition files that are compiled for use by the <xref:System.Web.Configuration.BrowserCapabilitiesFactory> class. The goal of both configuration methodologies is to generate an instance of the <xref:System.Web.HttpBrowserCapabilities> class that can be accessed from the <xref:System.Web.HttpRequest.Browser%2A> property of the <xref:System.Web.HttpRequest> class.       Using the browser definition files to store browser capabilities affords advantages over the alternative. It offers improved performance because the browser definition information is parsed from the XML configuration file and compiled into a class ahead of time. The browser definition files are also easier to maintain:      -   The definitions are hierarchical, and thus rely less on regular expressions to determine the browser capabilities.      -   The definitions can be organized in multiple files, making them easier to manage.      -   The definitions can be defined at any level, either at the Machine.config level or a specific application level. This eliminates the need to copy the entire set of definitions for the purpose of overriding the capabilities for a specific browser."
  syntax:
    content: 'public class HttpCapabilitiesSectionHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  langs:
  - csharp
  name: HttpCapabilitiesSectionHandler()
  nameWithType: HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Web.Configuration.HttpCapabilitiesSectionHandler&quot;></see> class."
  syntax:
    content: public HttpCapabilitiesSectionHandler ();
    parameters: []
  overload: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Creates an instance of the <see cref=&quot;T:System.Web.HttpBrowserCapabilities&quot;></see> class that contains the capabilities information for the client browser."
  remarks: "This class derives its browser definition data from the `<browserCaps>` configuration section. This section is deprecated in the .NET Framework version 2.0."
  syntax:
    content: public object Create (object parent, object configurationContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "The parent configuration node."
    - id: configurationContext
      type: System.Object
      description: "The configuration context of the current configuration file."
    - id: section
      type: System.Xml.XmlNode
      description: "The section of the configuration file that contains the information."
    return:
      type: System.Object
      description: "To be added."
  overload: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: HttpCapabilitiesSectionHandler()
  nameWithType: HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor*
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: HttpCapabilitiesSectionHandler
  nameWithType: HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create*
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: Create
  nameWithType: HttpCapabilitiesSectionHandler.Create
