### YamlMime:ManagedReference
items:
- uid: System.Diagnostics.DiagnosticsConfigurationHandler
  id: DiagnosticsConfigurationHandler
  children:
  - System.Diagnostics.DiagnosticsConfigurationHandler.#ctor
  - System.Diagnostics.DiagnosticsConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: DiagnosticsConfigurationHandler
  nameWithType: DiagnosticsConfigurationHandler
  fullName: System.Diagnostics.DiagnosticsConfigurationHandler
  type: Class
  summary: "Handles the diagnostics section of configuration files."
  remarks: "The DiagnosticsConfigurationHandler method is a section handler that participates in the resolution of configuration settings in the [\\<system.diagnostics>](../Topic/%3Csystem.diagnostics%3E%20Element.md) portion of configuration files."
  syntax:
    content: >-
      [System.Obsolete("This class has been deprecated.  http://go.microsoft.com/fwlink/?linkid=14202")]

      public class DiagnosticsConfigurationHandler : System.Configuration.IConfigurationSectionHandler
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.#ctor
  id: '#ctor'
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  langs:
  - csharp
  name: DiagnosticsConfigurationHandler()
  nameWithType: DiagnosticsConfigurationHandler.DiagnosticsConfigurationHandler()
  fullName: System.Diagnostics.DiagnosticsConfigurationHandler.DiagnosticsConfigurationHandler()
  type: Constructor
  assemblies:
  - System
  namespace: System.Diagnostics
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Diagnostics.DiagnosticsConfigurationHandler&quot;></see> class."
  syntax:
    content: public DiagnosticsConfigurationHandler ();
    parameters: []
  overload: System.Diagnostics.DiagnosticsConfigurationHandler.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: DiagnosticsConfigurationHandler.Create(Object,Object,XmlNode)
  fullName: System.Diagnostics.DiagnosticsConfigurationHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System
  namespace: System.Diagnostics
  summary: "Parses the configuration settings for the [\\"
  remarks: "The Create method populates a <xref:System.Collections.Hashtable> with the values obtained from the [\\<system.diagnostics>](../Topic/%3Csystem.diagnostics%3E%20Element.md) section of a configuration file and returns the hashtable."
  syntax:
    content: public virtual object Create (object parent, object configContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "The object inherited from the parent path"
    - id: configContext
      type: System.Object
      description: "Reserved. Used in ASP.NET to convey the virtual path of the configuration being evaluated."
    - id: section
      type: System.Xml.XmlNode
      description: "The root XML node at the section to handle."
    return:
      type: System.Object
      description: "To be added."
  overload: System.Diagnostics.DiagnosticsConfigurationHandler.Create*
  exceptions:
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "Switches could not be found.       -or-       Assert could not be found.       -or-       Trace could not be found.       -or-       Performance counters could not be found."
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.#ctor
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  isExternal: false
  name: DiagnosticsConfigurationHandler()
  nameWithType: DiagnosticsConfigurationHandler.DiagnosticsConfigurationHandler()
  fullName: System.Diagnostics.DiagnosticsConfigurationHandler.DiagnosticsConfigurationHandler()
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: DiagnosticsConfigurationHandler.Create(Object,Object,XmlNode)
  fullName: System.Diagnostics.DiagnosticsConfigurationHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.#ctor*
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  isExternal: false
  name: DiagnosticsConfigurationHandler
  nameWithType: DiagnosticsConfigurationHandler.DiagnosticsConfigurationHandler
- uid: System.Diagnostics.DiagnosticsConfigurationHandler.Create*
  parent: System.Diagnostics.DiagnosticsConfigurationHandler
  isExternal: false
  name: Create
  nameWithType: DiagnosticsConfigurationHandler.Create
