### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.InvalidDeploymentException
  id: InvalidDeploymentException
  children:
  - System.Deployment.Application.InvalidDeploymentException.#ctor
  - System.Deployment.Application.InvalidDeploymentException.#ctor(System.String)
  - System.Deployment.Application.InvalidDeploymentException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.InvalidDeploymentException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: InvalidDeploymentException
  nameWithType: InvalidDeploymentException
  fullName: System.Deployment.Application.InvalidDeploymentException
  type: Class
  summary: "Indicates that [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] could not read either the deployment or application manifests."
  remarks: "InvalidDeploymentException indicates the existence of a corrupt deployment or application manifest in a [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] application. The error might occur because the manifests are poorly formed, have unrecognized elements for their schemas, or have mismatched digital signatures.       You are more likely to have corruption  if you manually edit the deployment or application manifest files with a text editor. You can usually correct this problem by regenerating your [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] deployment, which will create new deployment and application manifests. For more detailed debugging steps, see the following links."
  syntax:
    content: 'public class InvalidDeploymentException : System.Deployment.Application.DeploymentException'
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Deployment.Application.DeploymentException
  implements: []
  inheritedMembers:
  - System.Deployment.Application.DeploymentException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.InvalidDeploymentException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.InvalidDeploymentException
  langs:
  - csharp
  name: InvalidDeploymentException()
  nameWithType: InvalidDeploymentException.InvalidDeploymentException()
  fullName: System.Deployment.Application.InvalidDeploymentException.InvalidDeploymentException()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Deployment.Application.InvalidDeploymentException&quot;></see> class."
  syntax:
    content: public InvalidDeploymentException ();
    parameters: []
  overload: System.Deployment.Application.InvalidDeploymentException.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.InvalidDeploymentException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.InvalidDeploymentException
  langs:
  - csharp
  name: InvalidDeploymentException(String)
  nameWithType: InvalidDeploymentException.InvalidDeploymentException(String)
  fullName: System.Deployment.Application.InvalidDeploymentException.InvalidDeploymentException(String)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Deployment.Application.InvalidDeploymentException&quot;></see> class with the specified message that describes the exception."
  syntax:
    content: public InvalidDeploymentException (string message);
    parameters:
    - id: message
      type: System.String
      description: "The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture."
  overload: System.Deployment.Application.InvalidDeploymentException.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.InvalidDeploymentException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.InvalidDeploymentException
  langs:
  - csharp
  name: InvalidDeploymentException(SerializationInfo,StreamingContext)
  nameWithType: InvalidDeploymentException.InvalidDeploymentException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.InvalidDeploymentException.InvalidDeploymentException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Deployment.Application.InvalidDeploymentException&quot;></see> class."
  syntax:
    content: protected InvalidDeploymentException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: "The object that holds the serialized object data."
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: "The contextual information about the source or destination."
  overload: System.Deployment.Application.InvalidDeploymentException.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.InvalidDeploymentException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.InvalidDeploymentException
  langs:
  - csharp
  name: InvalidDeploymentException(String,Exception)
  nameWithType: InvalidDeploymentException.InvalidDeploymentException(String,Exception)
  fullName: System.Deployment.Application.InvalidDeploymentException.InvalidDeploymentException(String,Exception)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Deployment.Application.InvalidDeploymentException&quot;></see> class."
  syntax:
    content: public InvalidDeploymentException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture."
    - id: innerException
      type: System.Exception
      description: "The exception that is the cause of the current exception. If the `innerException` parameter is not , the current exception is raised in a  block that handles the inner exception."
  overload: System.Deployment.Application.InvalidDeploymentException.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Deployment.Application.DeploymentException
  isExternal: false
  name: System.Deployment.Application.DeploymentException
- uid: System.Deployment.Application.InvalidDeploymentException.#ctor
  parent: System.Deployment.Application.InvalidDeploymentException
  isExternal: false
  name: InvalidDeploymentException()
  nameWithType: InvalidDeploymentException.InvalidDeploymentException()
  fullName: System.Deployment.Application.InvalidDeploymentException.InvalidDeploymentException()
- uid: System.Deployment.Application.InvalidDeploymentException.#ctor(System.String)
  parent: System.Deployment.Application.InvalidDeploymentException
  isExternal: false
  name: InvalidDeploymentException(String)
  nameWithType: InvalidDeploymentException.InvalidDeploymentException(String)
  fullName: System.Deployment.Application.InvalidDeploymentException.InvalidDeploymentException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.InvalidDeploymentException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.InvalidDeploymentException
  isExternal: false
  name: InvalidDeploymentException(SerializationInfo,StreamingContext)
  nameWithType: InvalidDeploymentException.InvalidDeploymentException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.InvalidDeploymentException.InvalidDeploymentException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.InvalidDeploymentException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.InvalidDeploymentException
  isExternal: false
  name: InvalidDeploymentException(String,Exception)
  nameWithType: InvalidDeploymentException.InvalidDeploymentException(String,Exception)
  fullName: System.Deployment.Application.InvalidDeploymentException.InvalidDeploymentException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Deployment.Application.InvalidDeploymentException.#ctor*
  parent: System.Deployment.Application.InvalidDeploymentException
  isExternal: false
  name: InvalidDeploymentException
  nameWithType: InvalidDeploymentException.InvalidDeploymentException
