### YamlMime:ManagedReference
items:
- uid: System.Configuration.PropertyValueOrigin
  id: PropertyValueOrigin
  children:
  - System.Configuration.PropertyValueOrigin.Default
  - System.Configuration.PropertyValueOrigin.Inherited
  - System.Configuration.PropertyValueOrigin.SetHere
  langs:
  - csharp
  name: PropertyValueOrigin
  nameWithType: PropertyValueOrigin
  fullName: System.Configuration.PropertyValueOrigin
  type: Enum
  summary: "Specifies the level in the configuration hierarchy where a configuration property value originated."
  syntax:
    content: public enum PropertyValueOrigin
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.PropertyValueOrigin.Default
  id: Default
  parent: System.Configuration.PropertyValueOrigin
  langs:
  - csharp
  name: Default
  nameWithType: PropertyValueOrigin.Default
  fullName: System.Configuration.PropertyValueOrigin.Default
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "The configuration property value originates from the &lt;xref:System.Configuration.ConfigurationProperty.DefaultValue%2A&gt; property."
  syntax:
    content: Default
    return:
      type: System.Configuration.PropertyValueOrigin
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.PropertyValueOrigin.Inherited
  id: Inherited
  parent: System.Configuration.PropertyValueOrigin
  langs:
  - csharp
  name: Inherited
  nameWithType: PropertyValueOrigin.Inherited
  fullName: System.Configuration.PropertyValueOrigin.Inherited
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "The configuration property value is inherited from a parent level in the configuration."
  syntax:
    content: Inherited
    return:
      type: System.Configuration.PropertyValueOrigin
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.PropertyValueOrigin.SetHere
  id: SetHere
  parent: System.Configuration.PropertyValueOrigin
  langs:
  - csharp
  name: SetHere
  nameWithType: PropertyValueOrigin.SetHere
  fullName: System.Configuration.PropertyValueOrigin.SetHere
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "The configuration property value is defined at the current level of the hierarchy."
  syntax:
    content: SetHere
    return:
      type: System.Configuration.PropertyValueOrigin
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.PropertyValueOrigin.Default
  parent: System.Configuration.PropertyValueOrigin
  isExternal: false
  name: Default
  nameWithType: PropertyValueOrigin.Default
  fullName: System.Configuration.PropertyValueOrigin.Default
- uid: System.Configuration.PropertyValueOrigin
  parent: System.Configuration
  isExternal: false
  name: PropertyValueOrigin
  nameWithType: PropertyValueOrigin
  fullName: System.Configuration.PropertyValueOrigin
- uid: System.Configuration.PropertyValueOrigin.Inherited
  parent: System.Configuration.PropertyValueOrigin
  isExternal: false
  name: Inherited
  nameWithType: PropertyValueOrigin.Inherited
  fullName: System.Configuration.PropertyValueOrigin.Inherited
- uid: System.Configuration.PropertyValueOrigin.SetHere
  parent: System.Configuration.PropertyValueOrigin
  isExternal: false
  name: SetHere
  nameWithType: PropertyValueOrigin.SetHere
  fullName: System.Configuration.PropertyValueOrigin.SetHere
