### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection
  id: NetPipeSection
  children:
  - System.ServiceModel.Activation.Configuration.NetPipeSection.#ctor
  - System.ServiceModel.Activation.Configuration.NetPipeSection.AllowAccounts
  - System.ServiceModel.Activation.Configuration.NetPipeSection.InitializeDefault
  - System.ServiceModel.Activation.Configuration.NetPipeSection.MaxPendingAccepts
  - System.ServiceModel.Activation.Configuration.NetPipeSection.MaxPendingConnections
  - System.ServiceModel.Activation.Configuration.NetPipeSection.Properties
  - System.ServiceModel.Activation.Configuration.NetPipeSection.ReceiveTimeout
  langs:
  - csharp
  name: NetPipeSection
  nameWithType: NetPipeSection
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection
  type: Class
  summary: "Contains configuration elements for the NetPipeActivator sharing service. This class cannot be inherited."
  remarks: "The Named Pipe Activation Service manages the lifetime of the named pipe connection, and handles activation requests that arrive over named pipes. This class contains properties that configure this service."
  syntax:
    content: 'public sealed class NetPipeSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  langs:
  - csharp
  name: NetPipeSection()
  nameWithType: NetPipeSection.NetPipeSection()
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection.NetPipeSection()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Activation.Configuration.NetPipeSection&quot;></see> class."
  syntax:
    content: public NetPipeSection ();
    parameters: []
  overload: System.ServiceModel.Activation.Configuration.NetPipeSection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.AllowAccounts
  id: AllowAccounts
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  langs:
  - csharp
  name: AllowAccounts
  nameWithType: NetPipeSection.AllowAccounts
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection.AllowAccounts
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "Gets the user accounts for processes that host [!INCLUDE[indigo1](~/add/includes/indigo1-md.md)] services and are granted connection access to the sharing service."
  syntax:
    content: public System.ServiceModel.Activation.Configuration.SecurityIdentifierElementCollection AllowAccounts { get; }
    return:
      type: System.ServiceModel.Activation.Configuration.SecurityIdentifierElementCollection
      description: "A <see cref=&quot;T:System.ServiceModel.Activation.Configuration.SecurityIdentifierElementCollection&quot;></see> that contains user accounts for processes that host [!INCLUDE[indigo2](~/add/includes/indigo2-md.md)] services and are granted connection access to the sharing service. The default values returned are LocalSystem, Admin, NS, LS, and IIS_USRS."
  overload: System.ServiceModel.Activation.Configuration.NetPipeSection.AllowAccounts*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.InitializeDefault
  id: InitializeDefault
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  langs:
  - csharp
  name: InitializeDefault()
  nameWithType: NetPipeSection.InitializeDefault()
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection.InitializeDefault()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  syntax:
    content: protected override void InitializeDefault ();
    parameters: []
  overload: System.ServiceModel.Activation.Configuration.NetPipeSection.InitializeDefault*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.MaxPendingAccepts
  id: MaxPendingAccepts
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  langs:
  - csharp
  name: MaxPendingAccepts
  nameWithType: NetPipeSection.MaxPendingAccepts
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection.MaxPendingAccepts
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "Gets or sets the maximum outstanding concurrent accepting threads on the listening endpoint for the sharing service."
  syntax:
    content: public int MaxPendingAccepts { get; set; }
    return:
      type: System.Int32
      description: "The maximum outstanding concurrent accepting threads on the listening endpoint for the sharing service. The default is 2."
  overload: System.ServiceModel.Activation.Configuration.NetPipeSection.MaxPendingAccepts*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.MaxPendingConnections
  id: MaxPendingConnections
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  langs:
  - csharp
  name: MaxPendingConnections
  nameWithType: NetPipeSection.MaxPendingConnections
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection.MaxPendingConnections
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "Gets or sets the maximum number of pending connections for this sharing service."
  syntax:
    content: public int MaxPendingConnections { get; set; }
    return:
      type: System.Int32
      description: "The maximum number of pending connections for this sharing service."
  overload: System.ServiceModel.Activation.Configuration.NetPipeSection.MaxPendingConnections*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.Properties
  id: Properties
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  langs:
  - csharp
  name: Properties
  nameWithType: NetPipeSection.Properties
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Activation.Configuration.NetPipeSection.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.ReceiveTimeout
  id: ReceiveTimeout
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  langs:
  - csharp
  name: ReceiveTimeout
  nameWithType: NetPipeSection.ReceiveTimeout
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection.ReceiveTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "Gets or sets the timeout for the NetPipeActivator sharing service."
  remarks: "This property specifies the timeout for reading the framing data and performing connection dispatching from the underlying connections."
  syntax:
    content: public TimeSpan ReceiveTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "The default is 10 seconds."
  overload: System.ServiceModel.Activation.Configuration.NetPipeSection.ReceiveTimeout*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.#ctor
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  isExternal: false
  name: NetPipeSection()
  nameWithType: NetPipeSection.NetPipeSection()
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection.NetPipeSection()
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.AllowAccounts
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  isExternal: false
  name: AllowAccounts
  nameWithType: NetPipeSection.AllowAccounts
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection.AllowAccounts
- uid: System.ServiceModel.Activation.Configuration.SecurityIdentifierElementCollection
  parent: System.ServiceModel.Activation.Configuration
  isExternal: false
  name: SecurityIdentifierElementCollection
  nameWithType: SecurityIdentifierElementCollection
  fullName: System.ServiceModel.Activation.Configuration.SecurityIdentifierElementCollection
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.InitializeDefault
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  isExternal: false
  name: InitializeDefault()
  nameWithType: NetPipeSection.InitializeDefault()
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection.InitializeDefault()
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.MaxPendingAccepts
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  isExternal: false
  name: MaxPendingAccepts
  nameWithType: NetPipeSection.MaxPendingAccepts
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection.MaxPendingAccepts
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.MaxPendingConnections
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  isExternal: false
  name: MaxPendingConnections
  nameWithType: NetPipeSection.MaxPendingConnections
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection.MaxPendingConnections
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.Properties
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  isExternal: false
  name: Properties
  nameWithType: NetPipeSection.Properties
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.ReceiveTimeout
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  isExternal: false
  name: ReceiveTimeout
  nameWithType: NetPipeSection.ReceiveTimeout
  fullName: System.ServiceModel.Activation.Configuration.NetPipeSection.ReceiveTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.#ctor*
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  isExternal: false
  name: NetPipeSection
  nameWithType: NetPipeSection.NetPipeSection
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.AllowAccounts*
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  isExternal: false
  name: AllowAccounts
  nameWithType: NetPipeSection.AllowAccounts
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.InitializeDefault*
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  isExternal: false
  name: InitializeDefault
  nameWithType: NetPipeSection.InitializeDefault
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.MaxPendingAccepts*
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  isExternal: false
  name: MaxPendingAccepts
  nameWithType: NetPipeSection.MaxPendingAccepts
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.MaxPendingConnections*
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  isExternal: false
  name: MaxPendingConnections
  nameWithType: NetPipeSection.MaxPendingConnections
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.Properties*
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  isExternal: false
  name: Properties
  nameWithType: NetPipeSection.Properties
- uid: System.ServiceModel.Activation.Configuration.NetPipeSection.ReceiveTimeout*
  parent: System.ServiceModel.Activation.Configuration.NetPipeSection
  isExternal: false
  name: ReceiveTimeout
  nameWithType: NetPipeSection.ReceiveTimeout
