### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.AuthenticationSection
  id: AuthenticationSection
  children:
  - System.Web.Configuration.AuthenticationSection.#ctor
  - System.Web.Configuration.AuthenticationSection.Forms
  - System.Web.Configuration.AuthenticationSection.Mode
  - System.Web.Configuration.AuthenticationSection.Passport
  - System.Web.Configuration.AuthenticationSection.Properties
  - System.Web.Configuration.AuthenticationSection.Reset(System.Configuration.ConfigurationElement)
  langs:
  - csharp
  name: AuthenticationSection
  nameWithType: AuthenticationSection
  fullName: System.Web.Configuration.AuthenticationSection
  type: Class
  summary: "Configures the authentication for a Web application. This class cannot be inherited."
  remarks: "The AuthenticationSection class provides a way to programmatically access and modify the `authentication` section of a configuration file.      > [!NOTE] >  The AuthenticationSection can write information into the related section of the configuration file according to the restrictions defined by the section property <xref:System.Configuration.SectionInformation.AllowDefinition%2A> whose value is <xref:System.Configuration.ConfigurationAllowDefinition>. Any attempt to write in a configuration file at a level not allowed in the hierarchy will result in an error message generated by the parser. However, you can use this class to read configuration information at any level in the hierarchy. For safety and scalability, it is recommended that you use an external repository, such as a database, to keep the users&quot; credentials."
  example:
  - "This section provides two code examples. The first demonstrates how to specify values declaratively for several attributes of the `authentication` section, which can also be accessed as members of the AuthenticationSection class. The second demonstrates how to use the AuthenticationSection class.  \n  \n The following configuration file example shows how to specify values declaratively for the `authentication` section.  \n  \n> [!NOTE]\n>  If you use the `credentials` section, be sure to follow the guidelines explained at [ASP.NET Authentication](../Topic/ASP.NET%20Authentication.md). For scalability and better security, it is recommended the use of an external database to store the users' credentials. For more information about building secure ASP.NET applications search the Microsoft MSDN Web site (http://msdn.microsoft.com) for \"Securing Your ASP.NET Application\", and \"Building Secure ASP.NET Applications: Authentication, Authorization, and Secure Communication\".  \n  \n```  \n<authentication mode=\"Forms\">  \n  <forms name=\"MyAppCookieName\" loginUrl=\"login.aspx\">  \n    <credentials passwordFormat=\"SHA1\">  \n      <user name=\"Kim\"  \n         password=\"07B7F3EE06F278DB966BE960E7CBBD103DF30CA6\"/>  \n      <user name=\"John\"  \n         password=\"BA56E5E0366D003E98EA1C7F04ABF8FCB3753889\"/>  \n    </credentials>  \n  </forms>  \n</authentication>  \n```  \n  \n The following code example demonstrates how to use the AuthenticationSection class.  \n  \n [!code-cs[System.Web.Configuration.AuthenticationSection#1](~/add/codesnippet/CSharp/t-system.web.configurati_68_1.cs)]\n [!code-vb[System.Web.Configuration.AuthenticationSection#1](~/add/codesnippet/VisualBasic/t-system.web.configurati_68_1.vb)]"
  syntax:
    content: 'public sealed class AuthenticationSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.AuthenticationSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.AuthenticationSection
  langs:
  - csharp
  name: AuthenticationSection()
  nameWithType: AuthenticationSection.AuthenticationSection()
  fullName: System.Web.Configuration.AuthenticationSection.AuthenticationSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Web.Configuration.AuthenticationSection&quot;></see> class."
  remarks: "The AuthenticationSection constructor is not intended to be used directly from your code. It is called by the ASP.NET configuration system. You obtain an instance of the <xref:System.Web.Configuration.AuthenticationSection> class by using the <xref:System.Configuration.Configuration.GetSection%2A> method."
  example:
  - "The following code example shows how to obtain a <xref:System.Web.Configuration.AuthenticationSection> object.  \n  \n [!code-cs[System.Web.Configuration.AuthenticationSection#2](~/add/codesnippet/CSharp/m-system.web.configurati_46_1.cs)]\n [!code-vb[System.Web.Configuration.AuthenticationSection#2](~/add/codesnippet/VisualBasic/m-system.web.configurati_46_1.vb)]"
  syntax:
    content: public AuthenticationSection ();
    parameters: []
  overload: System.Web.Configuration.AuthenticationSection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.AuthenticationSection.Forms
  id: Forms
  parent: System.Web.Configuration.AuthenticationSection
  langs:
  - csharp
  name: Forms
  nameWithType: AuthenticationSection.Forms
  fullName: System.Web.Configuration.AuthenticationSection.Forms
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets the Forms element property."
  remarks: ''
  example:
  - "The following code example shows how to use the Forms element property.  \n  \n [!code-cs[System.Web.Configuration.AuthenticationSection#5](~/add/codesnippet/CSharp/p-system.web.configurati_29_1.cs)]\n [!code-vb[System.Web.Configuration.AuthenticationSection#5](~/add/codesnippet/VisualBasic/p-system.web.configurati_29_1.vb)]"
  syntax:
    content: public System.Web.Configuration.FormsAuthenticationConfiguration Forms { get; }
    return:
      type: System.Web.Configuration.FormsAuthenticationConfiguration
      description: "A Forms element property that contains information used during forms-based authentication."
  overload: System.Web.Configuration.AuthenticationSection.Forms*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.AuthenticationSection.Mode
  id: Mode
  parent: System.Web.Configuration.AuthenticationSection
  langs:
  - csharp
  name: Mode
  nameWithType: AuthenticationSection.Mode
  fullName: System.Web.Configuration.AuthenticationSection.Mode
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets or sets the authentication modality."
  remarks: ''
  example:
  - "The following code example shows how to use the Mode property.  \n  \n [!code-cs[System.Web.Configuration.AuthenticationSection#4](~/add/codesnippet/CSharp/p-system.web.configurati_400_1.cs)]\n [!code-vb[System.Web.Configuration.AuthenticationSection#4](~/add/codesnippet/VisualBasic/p-system.web.configurati_400_1.vb)]"
  syntax:
    content: public System.Web.Configuration.AuthenticationMode Mode { get; set; }
    return:
      type: System.Web.Configuration.AuthenticationMode
      description: "One of the <see cref=&quot;T:System.Web.Configuration.AuthenticationMode&quot;></see> values."
  overload: System.Web.Configuration.AuthenticationSection.Mode*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.AuthenticationSection.Passport
  id: Passport
  parent: System.Web.Configuration.AuthenticationSection
  langs:
  - csharp
  name: Passport
  nameWithType: AuthenticationSection.Passport
  fullName: System.Web.Configuration.AuthenticationSection.Passport
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets the Passport element property."
  remarks: ''
  example:
  - "The following code example shows how to use the Passport element property.  \n  \n [!code-cs[System.Web.Configuration.AuthenticationSection#3](~/add/codesnippet/CSharp/p-system.web.configurati_165_1.cs)]\n [!code-vb[System.Web.Configuration.AuthenticationSection#3](~/add/codesnippet/VisualBasic/p-system.web.configurati_165_1.vb)]"
  syntax:
    content: public System.Web.Configuration.PassportAuthentication Passport { get; }
    return:
      type: System.Web.Configuration.PassportAuthentication
      description: "A Passport element property that contains information used during passport-based authentication."
  overload: System.Web.Configuration.AuthenticationSection.Passport*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.AuthenticationSection.Properties
  id: Properties
  parent: System.Web.Configuration.AuthenticationSection
  langs:
  - csharp
  name: Properties
  nameWithType: AuthenticationSection.Properties
  fullName: System.Web.Configuration.AuthenticationSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Web.Configuration.AuthenticationSection.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.AuthenticationSection.Reset(System.Configuration.ConfigurationElement)
  id: Reset(System.Configuration.ConfigurationElement)
  parent: System.Web.Configuration.AuthenticationSection
  langs:
  - csharp
  name: Reset(ConfigurationElement)
  nameWithType: AuthenticationSection.Reset(ConfigurationElement)
  fullName: System.Web.Configuration.AuthenticationSection.Reset(ConfigurationElement)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override void Reset (System.Configuration.ConfigurationElement parentElement);
    parameters:
    - id: parentElement
      type: System.Configuration.ConfigurationElement
      description: "To be added."
  overload: System.Web.Configuration.AuthenticationSection.Reset*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.AuthenticationSection.#ctor
  parent: System.Web.Configuration.AuthenticationSection
  isExternal: false
  name: AuthenticationSection()
  nameWithType: AuthenticationSection.AuthenticationSection()
  fullName: System.Web.Configuration.AuthenticationSection.AuthenticationSection()
- uid: System.Web.Configuration.AuthenticationSection.Forms
  parent: System.Web.Configuration.AuthenticationSection
  isExternal: false
  name: Forms
  nameWithType: AuthenticationSection.Forms
  fullName: System.Web.Configuration.AuthenticationSection.Forms
- uid: System.Web.Configuration.FormsAuthenticationConfiguration
  parent: System.Web.Configuration
  isExternal: false
  name: FormsAuthenticationConfiguration
  nameWithType: FormsAuthenticationConfiguration
  fullName: System.Web.Configuration.FormsAuthenticationConfiguration
- uid: System.Web.Configuration.AuthenticationSection.Mode
  parent: System.Web.Configuration.AuthenticationSection
  isExternal: false
  name: Mode
  nameWithType: AuthenticationSection.Mode
  fullName: System.Web.Configuration.AuthenticationSection.Mode
- uid: System.Web.Configuration.AuthenticationMode
  parent: System.Web.Configuration
  isExternal: false
  name: AuthenticationMode
  nameWithType: AuthenticationMode
  fullName: System.Web.Configuration.AuthenticationMode
- uid: System.Web.Configuration.AuthenticationSection.Passport
  parent: System.Web.Configuration.AuthenticationSection
  isExternal: false
  name: Passport
  nameWithType: AuthenticationSection.Passport
  fullName: System.Web.Configuration.AuthenticationSection.Passport
- uid: System.Web.Configuration.PassportAuthentication
  parent: System.Web.Configuration
  isExternal: false
  name: PassportAuthentication
  nameWithType: PassportAuthentication
  fullName: System.Web.Configuration.PassportAuthentication
- uid: System.Web.Configuration.AuthenticationSection.Properties
  parent: System.Web.Configuration.AuthenticationSection
  isExternal: false
  name: Properties
  nameWithType: AuthenticationSection.Properties
  fullName: System.Web.Configuration.AuthenticationSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.AuthenticationSection.Reset(System.Configuration.ConfigurationElement)
  parent: System.Web.Configuration.AuthenticationSection
  isExternal: false
  name: Reset(ConfigurationElement)
  nameWithType: AuthenticationSection.Reset(ConfigurationElement)
  fullName: System.Web.Configuration.AuthenticationSection.Reset(ConfigurationElement)
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.AuthenticationSection.#ctor*
  parent: System.Web.Configuration.AuthenticationSection
  isExternal: false
  name: AuthenticationSection
  nameWithType: AuthenticationSection.AuthenticationSection
- uid: System.Web.Configuration.AuthenticationSection.Forms*
  parent: System.Web.Configuration.AuthenticationSection
  isExternal: false
  name: Forms
  nameWithType: AuthenticationSection.Forms
- uid: System.Web.Configuration.AuthenticationSection.Mode*
  parent: System.Web.Configuration.AuthenticationSection
  isExternal: false
  name: Mode
  nameWithType: AuthenticationSection.Mode
- uid: System.Web.Configuration.AuthenticationSection.Passport*
  parent: System.Web.Configuration.AuthenticationSection
  isExternal: false
  name: Passport
  nameWithType: AuthenticationSection.Passport
- uid: System.Web.Configuration.AuthenticationSection.Properties*
  parent: System.Web.Configuration.AuthenticationSection
  isExternal: false
  name: Properties
  nameWithType: AuthenticationSection.Properties
- uid: System.Web.Configuration.AuthenticationSection.Reset*
  parent: System.Web.Configuration.AuthenticationSection
  isExternal: false
  name: Reset
  nameWithType: AuthenticationSection.Reset
