### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ConfigurationChannelFactory`1
  id: ConfigurationChannelFactory`1
  children:
  - System.ServiceModel.Configuration.ConfigurationChannelFactory`1.#ctor(System.String,System.Configuration.Configuration,System.ServiceModel.EndpointAddress)
  langs:
  - csharp
  name: ConfigurationChannelFactory<TChannel>
  nameWithType: ConfigurationChannelFactory<TChannel>
  fullName: System.ServiceModel.Configuration.ConfigurationChannelFactory<TChannel>
  type: Class
  syntax:
    content: 'public sealed class ConfigurationChannelFactory<TChannel> : System.ServiceModel.ChannelFactory<TChannel>'
    typeParameters:
    - id: TChannel
      description: "To be added."
  inheritance:
  - System.ServiceModel.ChannelFactory`1
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ConfigurationChannelFactory`1.#ctor(System.String,System.Configuration.Configuration,System.ServiceModel.EndpointAddress)
  id: '#ctor(System.String,System.Configuration.Configuration,System.ServiceModel.EndpointAddress)'
  parent: System.ServiceModel.Configuration.ConfigurationChannelFactory`1
  langs:
  - csharp
  name: ConfigurationChannelFactory(String,Configuration,EndpointAddress)
  nameWithType: ConfigurationChannelFactory<TChannel>.ConfigurationChannelFactory(String,Configuration,EndpointAddress)
  fullName: System.ServiceModel.Configuration.ConfigurationChannelFactory<TChannel>.ConfigurationChannelFactory(String,Configuration,EndpointAddress)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: public ConfigurationChannelFactory (string endpointConfigurationName, System.Configuration.Configuration configuration, System.ServiceModel.EndpointAddress remoteAddress);
    parameters:
    - id: endpointConfigurationName
      type: System.String
      description: "To be added."
    - id: configuration
      type: System.Configuration.Configuration
      description: "To be added."
    - id: remoteAddress
      type: System.ServiceModel.EndpointAddress
      description: "To be added."
  overload: System.ServiceModel.Configuration.ConfigurationChannelFactory`1.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.ChannelFactory`1
  isExternal: false
  name: System.ServiceModel.ChannelFactory<TChannel>
- uid: System.ServiceModel.Configuration.ConfigurationChannelFactory`1.#ctor(System.String,System.Configuration.Configuration,System.ServiceModel.EndpointAddress)
  parent: System.ServiceModel.Configuration.ConfigurationChannelFactory`1
  isExternal: false
  name: ConfigurationChannelFactory(String,Configuration,EndpointAddress)
  nameWithType: ConfigurationChannelFactory<TChannel>.ConfigurationChannelFactory(String,Configuration,EndpointAddress)
  fullName: System.ServiceModel.Configuration.ConfigurationChannelFactory<TChannel>.ConfigurationChannelFactory(String,Configuration,EndpointAddress)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Configuration
  parent: System.Configuration
  isExternal: false
  name: Configuration
  nameWithType: Configuration
  fullName: System.Configuration.Configuration
- uid: System.ServiceModel.EndpointAddress
  parent: System.ServiceModel
  isExternal: true
  name: EndpointAddress
  nameWithType: EndpointAddress
  fullName: System.ServiceModel.EndpointAddress
- uid: System.ServiceModel.Configuration.ConfigurationChannelFactory`1.#ctor*
  parent: System.ServiceModel.Configuration.ConfigurationChannelFactory`1
  isExternal: false
  name: ConfigurationChannelFactory<TChannel>
  nameWithType: ConfigurationChannelFactory<TChannel>.ConfigurationChannelFactory<TChannel>
