### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingElement
  id: SettingElement
  children:
  - System.Configuration.SettingElement.#ctor
  - System.Configuration.SettingElement.#ctor(System.String,System.Configuration.SettingsSerializeAs)
  - System.Configuration.SettingElement.Equals(System.Object)
  - System.Configuration.SettingElement.GetHashCode
  - System.Configuration.SettingElement.Name
  - System.Configuration.SettingElement.Properties
  - System.Configuration.SettingElement.SerializeAs
  - System.Configuration.SettingElement.Value
  langs:
  - csharp
  name: SettingElement
  nameWithType: SettingElement
  fullName: System.Configuration.SettingElement
  type: Class
  summary: "Represents a simplified configuration element used for updating elements in the configuration. This class cannot be inherited."
  remarks: "Represents a configuration element within a configuration file."
  syntax:
    content: 'public sealed class SettingElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SettingElement.#ctor
  id: '#ctor'
  parent: System.Configuration.SettingElement
  langs:
  - csharp
  name: SettingElement()
  nameWithType: SettingElement.SettingElement()
  fullName: System.Configuration.SettingElement.SettingElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.SettingElement&quot;></see> class."
  syntax:
    content: public SettingElement ();
    parameters: []
  overload: System.Configuration.SettingElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SettingElement.#ctor(System.String,System.Configuration.SettingsSerializeAs)
  id: '#ctor(System.String,System.Configuration.SettingsSerializeAs)'
  parent: System.Configuration.SettingElement
  langs:
  - csharp
  name: SettingElement(String,SettingsSerializeAs)
  nameWithType: SettingElement.SettingElement(String,SettingsSerializeAs)
  fullName: System.Configuration.SettingElement.SettingElement(String,SettingsSerializeAs)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.SettingElement&quot;></see> class based on supplied parameters."
  syntax:
    content: public SettingElement (string name, System.Configuration.SettingsSerializeAs serializeAs);
    parameters:
    - id: name
      type: System.String
      description: "The name of the  object."
    - id: serializeAs
      type: System.Configuration.SettingsSerializeAs
      description: "A  object. This object is an enumeration used as the serialization scheme to store configuration settings."
  overload: System.Configuration.SettingElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SettingElement.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.Configuration.SettingElement
  langs:
  - csharp
  name: Equals(Object)
  nameWithType: SettingElement.Equals(Object)
  fullName: System.Configuration.SettingElement.Equals(Object)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Compares the current <see cref=&quot;T:System.Configuration.SettingElement&quot;></see> instance to the specified object."
  syntax:
    content: public override bool Equals (object settings);
    parameters:
    - id: settings
      type: System.Object
      description: "The object to compare with."
    return:
      type: System.Boolean
      description: "To be added."
  overload: System.Configuration.SettingElement.Equals*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SettingElement.GetHashCode
  id: GetHashCode
  parent: System.Configuration.SettingElement
  langs:
  - csharp
  name: GetHashCode()
  nameWithType: SettingElement.GetHashCode()
  fullName: System.Configuration.SettingElement.GetHashCode()
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Gets a unique value representing the <see cref=&quot;T:System.Configuration.SettingElement&quot;></see> current instance."
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: "To be added."
  overload: System.Configuration.SettingElement.GetHashCode*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SettingElement.Name
  id: Name
  parent: System.Configuration.SettingElement
  langs:
  - csharp
  name: Name
  nameWithType: SettingElement.Name
  fullName: System.Configuration.SettingElement.Name
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Gets or sets the name of the <see cref=&quot;T:System.Configuration.SettingElement&quot;></see> object."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "The name of the <see cref=&quot;T:System.Configuration.SettingElement&quot;></see> object."
  overload: System.Configuration.SettingElement.Name*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SettingElement.Properties
  id: Properties
  parent: System.Configuration.SettingElement
  langs:
  - csharp
  name: Properties
  nameWithType: SettingElement.Properties
  fullName: System.Configuration.SettingElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Configuration.SettingElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SettingElement.SerializeAs
  id: SerializeAs
  parent: System.Configuration.SettingElement
  langs:
  - csharp
  name: SerializeAs
  nameWithType: SettingElement.SerializeAs
  fullName: System.Configuration.SettingElement.SerializeAs
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Gets or sets the serialization mechanism used to persist the values of the <see cref=&quot;T:System.Configuration.SettingElement&quot;></see> object."
  remarks: "The <xref:System.Configuration.SettingsSerializeAs> object is an enumeration used as the serialization scheme to store configuration settings."
  syntax:
    content: public System.Configuration.SettingsSerializeAs SerializeAs { get; set; }
    return:
      type: System.Configuration.SettingsSerializeAs
      description: "A <see cref=&quot;T:System.Configuration.SettingsSerializeAs&quot;></see> object."
  overload: System.Configuration.SettingElement.SerializeAs*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SettingElement.Value
  id: Value
  parent: System.Configuration.SettingElement
  langs:
  - csharp
  name: Value
  nameWithType: SettingElement.Value
  fullName: System.Configuration.SettingElement.Value
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Gets or sets the value of a <see cref=&quot;T:System.Configuration.SettingElement&quot;></see> object by using a <see cref=&quot;T:System.Configuration.SettingValueElement&quot;></see> object."
  syntax:
    content: public System.Configuration.SettingValueElement Value { get; set; }
    return:
      type: System.Configuration.SettingValueElement
      description: "A <see cref=&quot;T:System.Configuration.SettingValueElement&quot;></see> object containing the value of the <see cref=&quot;T:System.Configuration.SettingElement&quot;></see> object."
  overload: System.Configuration.SettingElement.Value*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Configuration.SettingElement.#ctor
  parent: System.Configuration.SettingElement
  isExternal: false
  name: SettingElement()
  nameWithType: SettingElement.SettingElement()
  fullName: System.Configuration.SettingElement.SettingElement()
- uid: System.Configuration.SettingElement.#ctor(System.String,System.Configuration.SettingsSerializeAs)
  parent: System.Configuration.SettingElement
  isExternal: false
  name: SettingElement(String,SettingsSerializeAs)
  nameWithType: SettingElement.SettingElement(String,SettingsSerializeAs)
  fullName: System.Configuration.SettingElement.SettingElement(String,SettingsSerializeAs)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsSerializeAs
  parent: System.Configuration
  isExternal: false
  name: SettingsSerializeAs
  nameWithType: SettingsSerializeAs
  fullName: System.Configuration.SettingsSerializeAs
- uid: System.Configuration.SettingElement.Equals(System.Object)
  parent: System.Configuration.SettingElement
  isExternal: false
  name: Equals(Object)
  nameWithType: SettingElement.Equals(Object)
  fullName: System.Configuration.SettingElement.Equals(Object)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.SettingElement.GetHashCode
  parent: System.Configuration.SettingElement
  isExternal: false
  name: GetHashCode()
  nameWithType: SettingElement.GetHashCode()
  fullName: System.Configuration.SettingElement.GetHashCode()
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.SettingElement.Name
  parent: System.Configuration.SettingElement
  isExternal: false
  name: Name
  nameWithType: SettingElement.Name
  fullName: System.Configuration.SettingElement.Name
- uid: System.Configuration.SettingElement.Properties
  parent: System.Configuration.SettingElement
  isExternal: false
  name: Properties
  nameWithType: SettingElement.Properties
  fullName: System.Configuration.SettingElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Configuration.SettingElement.SerializeAs
  parent: System.Configuration.SettingElement
  isExternal: false
  name: SerializeAs
  nameWithType: SettingElement.SerializeAs
  fullName: System.Configuration.SettingElement.SerializeAs
- uid: System.Configuration.SettingElement.Value
  parent: System.Configuration.SettingElement
  isExternal: false
  name: Value
  nameWithType: SettingElement.Value
  fullName: System.Configuration.SettingElement.Value
- uid: System.Configuration.SettingValueElement
  parent: System.Configuration
  isExternal: false
  name: SettingValueElement
  nameWithType: SettingValueElement
  fullName: System.Configuration.SettingValueElement
- uid: System.Configuration.SettingElement.#ctor*
  parent: System.Configuration.SettingElement
  isExternal: false
  name: SettingElement
  nameWithType: SettingElement.SettingElement
- uid: System.Configuration.SettingElement.Equals*
  parent: System.Configuration.SettingElement
  isExternal: false
  name: Equals
  nameWithType: SettingElement.Equals
- uid: System.Configuration.SettingElement.GetHashCode*
  parent: System.Configuration.SettingElement
  isExternal: false
  name: GetHashCode
  nameWithType: SettingElement.GetHashCode
- uid: System.Configuration.SettingElement.Name*
  parent: System.Configuration.SettingElement
  isExternal: false
  name: Name
  nameWithType: SettingElement.Name
- uid: System.Configuration.SettingElement.Properties*
  parent: System.Configuration.SettingElement
  isExternal: false
  name: Properties
  nameWithType: SettingElement.Properties
- uid: System.Configuration.SettingElement.SerializeAs*
  parent: System.Configuration.SettingElement
  isExternal: false
  name: SerializeAs
  nameWithType: SettingElement.SerializeAs
- uid: System.Configuration.SettingElement.Value*
  parent: System.Configuration.SettingElement
  isExternal: false
  name: Value
  nameWithType: SettingElement.Value
