### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  id: NetNamedPipeSecurityElement
  children:
  - System.ServiceModel.Configuration.NetNamedPipeSecurityElement.#ctor
  - System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Mode
  - System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Properties
  - System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Transport
  langs:
  - csharp
  name: NetNamedPipeSecurityElement
  nameWithType: NetNamedPipeSecurityElement
  fullName: System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  type: Class
  summary: "Represents a configuration element that specifies security settings for a named pipe binding. This class cannot be inherited."
  syntax:
    content: 'public sealed class NetNamedPipeSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  langs:
  - csharp
  name: NetNamedPipeSecurityElement()
  nameWithType: NetNamedPipeSecurityElement.NetNamedPipeSecurityElement()
  fullName: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.NetNamedPipeSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.NetNamedPipeSecurityElement&quot;></see> class."
  syntax:
    content: public NetNamedPipeSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Mode
  id: Mode
  parent: System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  langs:
  - csharp
  name: Mode
  nameWithType: NetNamedPipeSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets the type of security that is applied to this binding."
  syntax:
    content: public System.ServiceModel.NetNamedPipeSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.NetNamedPipeSecurityMode
      description: "A <see cref=&quot;T:System.ServiceModel.NetNamedPipeSecurityMode&quot;></see> that specifies the type of security applied to this binding. The default value is <see cref=&quot;T:System.ServiceModel.NetNamedPipeSecurityMode&quot;></see>."
  overload: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Mode*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: NetNamedPipeSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Transport
  id: Transport
  parent: System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  langs:
  - csharp
  name: Transport
  nameWithType: NetNamedPipeSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets the security settings for the transport."
  syntax:
    content: public System.ServiceModel.Configuration.NamedPipeTransportSecurityElement Transport { get; }
    return:
      type: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
      description: "The security settings for the transport."
  overload: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Transport*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  isExternal: false
  name: NetNamedPipeSecurityElement()
  nameWithType: NetNamedPipeSecurityElement.NetNamedPipeSecurityElement()
  fullName: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.NetNamedPipeSecurityElement()
- uid: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Mode
  parent: System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  isExternal: false
  name: Mode
  nameWithType: NetNamedPipeSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Mode
- uid: System.ServiceModel.NetNamedPipeSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: NetNamedPipeSecurityMode
  nameWithType: NetNamedPipeSecurityMode
  fullName: System.ServiceModel.NetNamedPipeSecurityMode
- uid: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Properties
  parent: System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  isExternal: false
  name: Properties
  nameWithType: NetNamedPipeSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Transport
  parent: System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  isExternal: false
  name: Transport
  nameWithType: NetNamedPipeSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Transport
- uid: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: NamedPipeTransportSecurityElement
  nameWithType: NamedPipeTransportSecurityElement
  fullName: System.ServiceModel.Configuration.NamedPipeTransportSecurityElement
- uid: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  isExternal: false
  name: NetNamedPipeSecurityElement
  nameWithType: NetNamedPipeSecurityElement.NetNamedPipeSecurityElement
- uid: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Mode*
  parent: System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  isExternal: false
  name: Mode
  nameWithType: NetNamedPipeSecurityElement.Mode
- uid: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  isExternal: false
  name: Properties
  nameWithType: NetNamedPipeSecurityElement.Properties
- uid: System.ServiceModel.Configuration.NetNamedPipeSecurityElement.Transport*
  parent: System.ServiceModel.Configuration.NetNamedPipeSecurityElement
  isExternal: false
  name: Transport
  nameWithType: NetNamedPipeSecurityElement.Transport
