### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.PeerResolverElement
  id: PeerResolverElement
  children:
  - System.ServiceModel.Configuration.PeerResolverElement.#ctor
  - System.ServiceModel.Configuration.PeerResolverElement.Custom
  - System.ServiceModel.Configuration.PeerResolverElement.Mode
  - System.ServiceModel.Configuration.PeerResolverElement.Properties
  - System.ServiceModel.Configuration.PeerResolverElement.ReferralPolicy
  langs:
  - csharp
  name: PeerResolverElement
  nameWithType: PeerResolverElement
  fullName: System.ServiceModel.Configuration.PeerResolverElement
  type: Class
  summary: "Defines the configuration element for a peer resolver."
  syntax:
    content: 'public sealed class PeerResolverElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.PeerResolverElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.PeerResolverElement
  langs:
  - csharp
  name: PeerResolverElement()
  nameWithType: PeerResolverElement.PeerResolverElement()
  fullName: System.ServiceModel.Configuration.PeerResolverElement.PeerResolverElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.PeerResolverElement&quot;></see> class."
  syntax:
    content: public PeerResolverElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.PeerResolverElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.PeerResolverElement.Custom
  id: Custom
  parent: System.ServiceModel.Configuration.PeerResolverElement
  langs:
  - csharp
  name: Custom
  nameWithType: PeerResolverElement.Custom
  fullName: System.ServiceModel.Configuration.PeerResolverElement.Custom
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets the configuration element for this peer resolver if it is a custom peer resolver implementation."
  remarks: "This property contains an instance of <xref:System.ServiceModel.Configuration.PeerCustomResolverElement> if the <xref:System.ServiceModel.Configuration.PeerResolverElement.Mode%2A> property is set to <xref:System.ServiceModel.PeerResolvers.PeerResolverMode>."
  syntax:
    content: public System.ServiceModel.Configuration.PeerCustomResolverElement Custom { get; }
    return:
      type: System.ServiceModel.Configuration.PeerCustomResolverElement
      description: "<see cref=&quot;T:System.ServiceModel.Configuration.PeerCustomResolverElement&quot;></see> that contains the configuration element for the peer resolver if it is a custom peer resolver implementation."
  overload: System.ServiceModel.Configuration.PeerResolverElement.Custom*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.PeerResolverElement.Mode
  id: Mode
  parent: System.ServiceModel.Configuration.PeerResolverElement
  langs:
  - csharp
  name: Mode
  nameWithType: PeerResolverElement.Mode
  fullName: System.ServiceModel.Configuration.PeerResolverElement.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets and sets the type of the peer resolver represented by this configuration element."
  syntax:
    content: public System.ServiceModel.PeerResolvers.PeerResolverMode Mode { get; set; }
    return:
      type: System.ServiceModel.PeerResolvers.PeerResolverMode
      description: "<see cref=&quot;T:System.ServiceModel.PeerResolvers.PeerResolverMode&quot;></see> enumeration value that specifies the type of peer resolvder represented by this configuration element."
  overload: System.ServiceModel.Configuration.PeerResolverElement.Mode*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.PeerResolverElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.PeerResolverElement
  langs:
  - csharp
  name: Properties
  nameWithType: PeerResolverElement.Properties
  fullName: System.ServiceModel.Configuration.PeerResolverElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.PeerResolverElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.PeerResolverElement.ReferralPolicy
  id: ReferralPolicy
  parent: System.ServiceModel.Configuration.PeerResolverElement
  langs:
  - csharp
  name: ReferralPolicy
  nameWithType: PeerResolverElement.ReferralPolicy
  fullName: System.ServiceModel.Configuration.PeerResolverElement.ReferralPolicy
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets and sets the referral policy for peer resolvers configured with this element."
  syntax:
    content: public System.ServiceModel.PeerResolvers.PeerReferralPolicy ReferralPolicy { get; set; }
    return:
      type: System.ServiceModel.PeerResolvers.PeerReferralPolicy
      description: "<see cref=&quot;T:System.ServiceModel.PeerResolvers.PeerReferralPolicy&quot;></see> that specifies the referral policy for peer resolvers configured with this element."
  overload: System.ServiceModel.Configuration.PeerResolverElement.ReferralPolicy*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.PeerResolverElement.#ctor
  parent: System.ServiceModel.Configuration.PeerResolverElement
  isExternal: false
  name: PeerResolverElement()
  nameWithType: PeerResolverElement.PeerResolverElement()
  fullName: System.ServiceModel.Configuration.PeerResolverElement.PeerResolverElement()
- uid: System.ServiceModel.Configuration.PeerResolverElement.Custom
  parent: System.ServiceModel.Configuration.PeerResolverElement
  isExternal: false
  name: Custom
  nameWithType: PeerResolverElement.Custom
  fullName: System.ServiceModel.Configuration.PeerResolverElement.Custom
- uid: System.ServiceModel.Configuration.PeerCustomResolverElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: PeerCustomResolverElement
  nameWithType: PeerCustomResolverElement
  fullName: System.ServiceModel.Configuration.PeerCustomResolverElement
- uid: System.ServiceModel.Configuration.PeerResolverElement.Mode
  parent: System.ServiceModel.Configuration.PeerResolverElement
  isExternal: false
  name: Mode
  nameWithType: PeerResolverElement.Mode
  fullName: System.ServiceModel.Configuration.PeerResolverElement.Mode
- uid: System.ServiceModel.PeerResolvers.PeerResolverMode
  parent: System.ServiceModel.PeerResolvers
  isExternal: false
  name: PeerResolverMode
  nameWithType: PeerResolverMode
  fullName: System.ServiceModel.PeerResolvers.PeerResolverMode
- uid: System.ServiceModel.Configuration.PeerResolverElement.Properties
  parent: System.ServiceModel.Configuration.PeerResolverElement
  isExternal: false
  name: Properties
  nameWithType: PeerResolverElement.Properties
  fullName: System.ServiceModel.Configuration.PeerResolverElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.PeerResolverElement.ReferralPolicy
  parent: System.ServiceModel.Configuration.PeerResolverElement
  isExternal: false
  name: ReferralPolicy
  nameWithType: PeerResolverElement.ReferralPolicy
  fullName: System.ServiceModel.Configuration.PeerResolverElement.ReferralPolicy
- uid: System.ServiceModel.PeerResolvers.PeerReferralPolicy
  parent: System.ServiceModel.PeerResolvers
  isExternal: false
  name: PeerReferralPolicy
  nameWithType: PeerReferralPolicy
  fullName: System.ServiceModel.PeerResolvers.PeerReferralPolicy
- uid: System.ServiceModel.Configuration.PeerResolverElement.#ctor*
  parent: System.ServiceModel.Configuration.PeerResolverElement
  isExternal: false
  name: PeerResolverElement
  nameWithType: PeerResolverElement.PeerResolverElement
- uid: System.ServiceModel.Configuration.PeerResolverElement.Custom*
  parent: System.ServiceModel.Configuration.PeerResolverElement
  isExternal: false
  name: Custom
  nameWithType: PeerResolverElement.Custom
- uid: System.ServiceModel.Configuration.PeerResolverElement.Mode*
  parent: System.ServiceModel.Configuration.PeerResolverElement
  isExternal: false
  name: Mode
  nameWithType: PeerResolverElement.Mode
- uid: System.ServiceModel.Configuration.PeerResolverElement.Properties*
  parent: System.ServiceModel.Configuration.PeerResolverElement
  isExternal: false
  name: Properties
  nameWithType: PeerResolverElement.Properties
- uid: System.ServiceModel.Configuration.PeerResolverElement.ReferralPolicy*
  parent: System.ServiceModel.Configuration.PeerResolverElement
  isExternal: false
  name: ReferralPolicy
  nameWithType: PeerResolverElement.ReferralPolicy
