### YamlMime:ManagedReference
items:
- uid: System.Configuration.DictionarySectionHandler
  id: DictionarySectionHandler
  children:
  - System.Configuration.DictionarySectionHandler.#ctor
  - System.Configuration.DictionarySectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  - System.Configuration.DictionarySectionHandler.KeyAttributeName
  - System.Configuration.DictionarySectionHandler.ValueAttributeName
  langs:
  - csharp
  name: DictionarySectionHandler
  nameWithType: DictionarySectionHandler
  fullName: System.Configuration.DictionarySectionHandler
  type: Class
  summary: "Provides key/value pair configuration information from a configuration section."
  remarks: "This class implements the `IConfigSectionHandler` interface. The DictionarySectionHandler defines rules for manipulating XML configuration sections."
  syntax:
    content: 'public class DictionarySectionHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.DictionarySectionHandler.#ctor
  id: '#ctor'
  parent: System.Configuration.DictionarySectionHandler
  langs:
  - csharp
  name: DictionarySectionHandler()
  nameWithType: DictionarySectionHandler.DictionarySectionHandler()
  fullName: System.Configuration.DictionarySectionHandler.DictionarySectionHandler()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.DictionarySectionHandler&quot;></see> class."
  syntax:
    content: public DictionarySectionHandler ();
    parameters: []
  overload: System.Configuration.DictionarySectionHandler.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.DictionarySectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.DictionarySectionHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: DictionarySectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.DictionarySectionHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Creates a new configuration handler and adds it to the section-handler collection based on the specified parameters."
  remarks: "The `parent` object parameter acts as the configuration settings in the corresponding parent configuration section. The `context` object parameter is the virtual path for which the configuration section handler computes configuration values. Normally this parameter is reserved and is `null`.  The `section` parameter is the <xref:System.Xml.XmlNode> that contains the configuration information to be handled. The `section` parameter provides direct access to the XML contents of the configuration section."
  syntax:
    content: public virtual object Create (object parent, object context, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "Parent object."
    - id: context
      type: System.Object
      description: "Configuration context object."
    - id: section
      type: System.Xml.XmlNode
      description: "Section XML node."
    return:
      type: System.Object
      description: "To be added."
  overload: System.Configuration.DictionarySectionHandler.Create*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.DictionarySectionHandler.KeyAttributeName
  id: KeyAttributeName
  parent: System.Configuration.DictionarySectionHandler
  langs:
  - csharp
  name: KeyAttributeName
  nameWithType: DictionarySectionHandler.KeyAttributeName
  fullName: System.Configuration.DictionarySectionHandler.KeyAttributeName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Gets the XML attribute name to use as the key in a key/value pair."
  syntax:
    content: protected virtual string KeyAttributeName { get; }
    return:
      type: System.String
      description: "A string value containing the name of the key attribute."
  overload: System.Configuration.DictionarySectionHandler.KeyAttributeName*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.DictionarySectionHandler.ValueAttributeName
  id: ValueAttributeName
  parent: System.Configuration.DictionarySectionHandler
  langs:
  - csharp
  name: ValueAttributeName
  nameWithType: DictionarySectionHandler.ValueAttributeName
  fullName: System.Configuration.DictionarySectionHandler.ValueAttributeName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Gets the XML attribute name to use as the value in a key/value pair."
  syntax:
    content: protected virtual string ValueAttributeName { get; }
    return:
      type: System.String
      description: "A string value containing the name of the value attribute."
  overload: System.Configuration.DictionarySectionHandler.ValueAttributeName*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.DictionarySectionHandler.#ctor
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: DictionarySectionHandler()
  nameWithType: DictionarySectionHandler.DictionarySectionHandler()
  fullName: System.Configuration.DictionarySectionHandler.DictionarySectionHandler()
- uid: System.Configuration.DictionarySectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: DictionarySectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.DictionarySectionHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.DictionarySectionHandler.KeyAttributeName
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: KeyAttributeName
  nameWithType: DictionarySectionHandler.KeyAttributeName
  fullName: System.Configuration.DictionarySectionHandler.KeyAttributeName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.DictionarySectionHandler.ValueAttributeName
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: ValueAttributeName
  nameWithType: DictionarySectionHandler.ValueAttributeName
  fullName: System.Configuration.DictionarySectionHandler.ValueAttributeName
- uid: System.Configuration.DictionarySectionHandler.#ctor*
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: DictionarySectionHandler
  nameWithType: DictionarySectionHandler.DictionarySectionHandler
- uid: System.Configuration.DictionarySectionHandler.Create*
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: Create
  nameWithType: DictionarySectionHandler.Create
- uid: System.Configuration.DictionarySectionHandler.KeyAttributeName*
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: KeyAttributeName
  nameWithType: DictionarySectionHandler.KeyAttributeName
- uid: System.Configuration.DictionarySectionHandler.ValueAttributeName*
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: ValueAttributeName
  nameWithType: DictionarySectionHandler.ValueAttributeName
