### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Routing.Configuration.RoutingSection
  id: RoutingSection
  children:
  - System.ServiceModel.Routing.Configuration.RoutingSection.#ctor
  - System.ServiceModel.Routing.Configuration.RoutingSection.BackupLists
  - System.ServiceModel.Routing.Configuration.RoutingSection.CreateFilterTable(System.String)
  - System.ServiceModel.Routing.Configuration.RoutingSection.Filters
  - System.ServiceModel.Routing.Configuration.RoutingSection.FilterTables
  - System.ServiceModel.Routing.Configuration.RoutingSection.NamespaceTable
  langs:
  - csharp
  name: RoutingSection
  nameWithType: RoutingSection
  fullName: System.ServiceModel.Routing.Configuration.RoutingSection
  type: Class
  summary: "Represents a collection of elements that are used to configure routing."
  syntax:
    content: 'public class RoutingSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.RoutingSection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Routing.Configuration.RoutingSection
  langs:
  - csharp
  name: RoutingSection()
  nameWithType: RoutingSection.RoutingSection()
  fullName: System.ServiceModel.Routing.Configuration.RoutingSection.RoutingSection()
  type: Constructor
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Routing.Configuration.RoutingSection&quot;></see> class."
  syntax:
    content: public RoutingSection ();
    parameters: []
  overload: System.ServiceModel.Routing.Configuration.RoutingSection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.RoutingSection.BackupLists
  id: BackupLists
  parent: System.ServiceModel.Routing.Configuration.RoutingSection
  langs:
  - csharp
  name: BackupLists
  nameWithType: RoutingSection.BackupLists
  fullName: System.ServiceModel.Routing.Configuration.RoutingSection.BackupLists
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Gets the configuration element that contains a collection of <see cref=&quot;T:System.ServiceModel.Routing.Configuration.BackupEndpointElement&quot;></see> objects."
  syntax:
    content: public System.ServiceModel.Routing.Configuration.BackupListCollection BackupLists { get; }
    return:
      type: System.ServiceModel.Routing.Configuration.BackupListCollection
      description: "A collection that defines the configuration section that contains a collection of <see cref=&quot;T:System.ServiceModel.Routing.Configuration.BackupEndpointElement&quot;></see> objects."
  overload: System.ServiceModel.Routing.Configuration.RoutingSection.BackupLists*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.RoutingSection.CreateFilterTable(System.String)
  id: CreateFilterTable(System.String)
  parent: System.ServiceModel.Routing.Configuration.RoutingSection
  langs:
  - csharp
  name: CreateFilterTable(String)
  nameWithType: RoutingSection.CreateFilterTable(String)
  fullName: System.ServiceModel.Routing.Configuration.RoutingSection.CreateFilterTable(String)
  type: Method
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Creates a filter table using the specified name."
  remarks: "A routing table with the specified name must exist in the configuration file for the current AppDomain; otherwise an <xref:System.InvalidOperationException> occurs."
  syntax:
    content: public static System.ServiceModel.Dispatcher.MessageFilterTable<System.Collections.Generic.IEnumerable<System.ServiceModel.Description.ServiceEndpoint>> CreateFilterTable (string name);
    parameters:
    - id: name
      type: System.String
      description: "The name of the filter table to create."
    return:
      type: System.ServiceModel.Dispatcher.MessageFilterTable{System.Collections.Generic.IEnumerable{System.ServiceModel.Description.ServiceEndpoint}}
      description: "To be added."
  overload: System.ServiceModel.Routing.Configuration.RoutingSection.CreateFilterTable*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.RoutingSection.Filters
  id: Filters
  parent: System.ServiceModel.Routing.Configuration.RoutingSection
  langs:
  - csharp
  name: Filters
  nameWithType: RoutingSection.Filters
  fullName: System.ServiceModel.Routing.Configuration.RoutingSection.Filters
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Gets the configuration element that contains a collection of <see cref=&quot;T:System.ServiceModel.Routing.Configuration.FilterElement&quot;></see> objects."
  syntax:
    content: public System.ServiceModel.Routing.Configuration.FilterElementCollection Filters { get; }
    return:
      type: System.ServiceModel.Routing.Configuration.FilterElementCollection
      description: "A collection that defines the configuration section that contains a collection of <see cref=&quot;T:System.ServiceModel.Routing.Configuration.FilterElement&quot;></see>."
  overload: System.ServiceModel.Routing.Configuration.RoutingSection.Filters*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.RoutingSection.FilterTables
  id: FilterTables
  parent: System.ServiceModel.Routing.Configuration.RoutingSection
  langs:
  - csharp
  name: FilterTables
  nameWithType: RoutingSection.FilterTables
  fullName: System.ServiceModel.Routing.Configuration.RoutingSection.FilterTables
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Gets the configuration element that contains a collection of <see cref=&quot;T:System.ServiceModel.Routing.Configuration.FilterTableEntryElement&quot;></see> objects."
  syntax:
    content: public System.ServiceModel.Routing.Configuration.FilterTableCollection FilterTables { get; }
    return:
      type: System.ServiceModel.Routing.Configuration.FilterTableCollection
      description: "A collection that defines the configuration section that contains a collection of <see cref=&quot;T:System.ServiceModel.Routing.Configuration.FilterTableEntryElement&quot;></see> objects."
  overload: System.ServiceModel.Routing.Configuration.RoutingSection.FilterTables*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.RoutingSection.NamespaceTable
  id: NamespaceTable
  parent: System.ServiceModel.Routing.Configuration.RoutingSection
  langs:
  - csharp
  name: NamespaceTable
  nameWithType: RoutingSection.NamespaceTable
  fullName: System.ServiceModel.Routing.Configuration.RoutingSection.NamespaceTable
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Gets the configuration element that contains a collection of <see cref=&quot;T:System.ServiceModel.Routing.Configuration.NamespaceElement&quot;></see> objects."
  syntax:
    content: public System.ServiceModel.Routing.Configuration.NamespaceElementCollection NamespaceTable { get; }
    return:
      type: System.ServiceModel.Routing.Configuration.NamespaceElementCollection
      description: "A collection that defines the configuration section that contains a collection of <see cref=&quot;T:System.ServiceModel.Routing.Configuration.NamespaceElement&quot;></see> objects."
  overload: System.ServiceModel.Routing.Configuration.RoutingSection.NamespaceTable*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.ServiceModel.Routing.Configuration.RoutingSection.#ctor
  parent: System.ServiceModel.Routing.Configuration.RoutingSection
  isExternal: false
  name: RoutingSection()
  nameWithType: RoutingSection.RoutingSection()
  fullName: System.ServiceModel.Routing.Configuration.RoutingSection.RoutingSection()
- uid: System.ServiceModel.Routing.Configuration.RoutingSection.BackupLists
  parent: System.ServiceModel.Routing.Configuration.RoutingSection
  isExternal: false
  name: BackupLists
  nameWithType: RoutingSection.BackupLists
  fullName: System.ServiceModel.Routing.Configuration.RoutingSection.BackupLists
- uid: System.ServiceModel.Routing.Configuration.BackupListCollection
  parent: System.ServiceModel.Routing.Configuration
  isExternal: false
  name: BackupListCollection
  nameWithType: BackupListCollection
  fullName: System.ServiceModel.Routing.Configuration.BackupListCollection
- uid: System.ServiceModel.Routing.Configuration.RoutingSection.CreateFilterTable(System.String)
  parent: System.ServiceModel.Routing.Configuration.RoutingSection
  isExternal: false
  name: CreateFilterTable(String)
  nameWithType: RoutingSection.CreateFilterTable(String)
  fullName: System.ServiceModel.Routing.Configuration.RoutingSection.CreateFilterTable(String)
- uid: System.ServiceModel.Dispatcher.MessageFilterTable{System.Collections.Generic.IEnumerable{System.ServiceModel.Description.ServiceEndpoint}}
  parent: System.ServiceModel.Dispatcher
  isExternal: false
  name: MessageFilterTable<IEnumerable<ServiceEndpoint>>
  nameWithType: MessageFilterTable<IEnumerable<ServiceEndpoint>>
  fullName: System.ServiceModel.Dispatcher.MessageFilterTable<System.Collections.Generic.IEnumerable<System.ServiceModel.Description.ServiceEndpoint>>
  spec.csharp:
  - uid: System.ServiceModel.Dispatcher.MessageFilterTable`1
    name: MessageFilterTable
    nameWithType: MessageFilterTable
    fullName: MessageFilterTable<System.Collections.Generic.IEnumerable<System.ServiceModel.Description.ServiceEndpoint>>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: IEnumerable<System.ServiceModel.Description.ServiceEndpoint>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.ServiceModel.Description.ServiceEndpoint
    name: ServiceEndpoint
    nameWithType: ServiceEndpoint
    fullName: ServiceEndpoint
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Routing.Configuration.RoutingSection.Filters
  parent: System.ServiceModel.Routing.Configuration.RoutingSection
  isExternal: false
  name: Filters
  nameWithType: RoutingSection.Filters
  fullName: System.ServiceModel.Routing.Configuration.RoutingSection.Filters
- uid: System.ServiceModel.Routing.Configuration.FilterElementCollection
  parent: System.ServiceModel.Routing.Configuration
  isExternal: false
  name: FilterElementCollection
  nameWithType: FilterElementCollection
  fullName: System.ServiceModel.Routing.Configuration.FilterElementCollection
- uid: System.ServiceModel.Routing.Configuration.RoutingSection.FilterTables
  parent: System.ServiceModel.Routing.Configuration.RoutingSection
  isExternal: false
  name: FilterTables
  nameWithType: RoutingSection.FilterTables
  fullName: System.ServiceModel.Routing.Configuration.RoutingSection.FilterTables
- uid: System.ServiceModel.Routing.Configuration.FilterTableCollection
  parent: System.ServiceModel.Routing.Configuration
  isExternal: false
  name: FilterTableCollection
  nameWithType: FilterTableCollection
  fullName: System.ServiceModel.Routing.Configuration.FilterTableCollection
- uid: System.ServiceModel.Routing.Configuration.RoutingSection.NamespaceTable
  parent: System.ServiceModel.Routing.Configuration.RoutingSection
  isExternal: false
  name: NamespaceTable
  nameWithType: RoutingSection.NamespaceTable
  fullName: System.ServiceModel.Routing.Configuration.RoutingSection.NamespaceTable
- uid: System.ServiceModel.Routing.Configuration.NamespaceElementCollection
  parent: System.ServiceModel.Routing.Configuration
  isExternal: false
  name: NamespaceElementCollection
  nameWithType: NamespaceElementCollection
  fullName: System.ServiceModel.Routing.Configuration.NamespaceElementCollection
- uid: System.ServiceModel.Routing.Configuration.RoutingSection.#ctor*
  parent: System.ServiceModel.Routing.Configuration.RoutingSection
  isExternal: false
  name: RoutingSection
  nameWithType: RoutingSection.RoutingSection
- uid: System.ServiceModel.Routing.Configuration.RoutingSection.BackupLists*
  parent: System.ServiceModel.Routing.Configuration.RoutingSection
  isExternal: false
  name: BackupLists
  nameWithType: RoutingSection.BackupLists
- uid: System.ServiceModel.Routing.Configuration.RoutingSection.CreateFilterTable*
  parent: System.ServiceModel.Routing.Configuration.RoutingSection
  isExternal: false
  name: CreateFilterTable
  nameWithType: RoutingSection.CreateFilterTable
- uid: System.ServiceModel.Routing.Configuration.RoutingSection.Filters*
  parent: System.ServiceModel.Routing.Configuration.RoutingSection
  isExternal: false
  name: Filters
  nameWithType: RoutingSection.Filters
- uid: System.ServiceModel.Routing.Configuration.RoutingSection.FilterTables*
  parent: System.ServiceModel.Routing.Configuration.RoutingSection
  isExternal: false
  name: FilterTables
  nameWithType: RoutingSection.FilterTables
- uid: System.ServiceModel.Routing.Configuration.RoutingSection.NamespaceTable*
  parent: System.ServiceModel.Routing.Configuration.RoutingSection
  isExternal: false
  name: NamespaceTable
  nameWithType: RoutingSection.NamespaceTable
