### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.WebConfigurationFileMap
  id: WebConfigurationFileMap
  children:
  - System.Web.Configuration.WebConfigurationFileMap.#ctor
  - System.Web.Configuration.WebConfigurationFileMap.#ctor(System.String)
  - System.Web.Configuration.WebConfigurationFileMap.Clone
  - System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories
  langs:
  - csharp
  name: WebConfigurationFileMap
  nameWithType: WebConfigurationFileMap
  fullName: System.Web.Configuration.WebConfigurationFileMap
  type: Class
  summary: "Defines the configuration file mappings for a Web application. This class cannot be inherited."
  remarks: "The WebConfigurationFileMap class is used to specify the Web configuration file hierarchy. By default, the configuration system uses the IIS metabase to determine the Web file hierarchy. If IIS is not installed, or if an application targets a version of the .NET Framework that is not the latest version that is installed on the server, the WebConfigurationFileMap class provides a means to define a custom hierarchy.       The WebConfigurationFileMap class can specify a single path or multiple paths related to configuration files."
  syntax:
    content: 'public sealed class WebConfigurationFileMap : System.Configuration.ConfigurationFileMap'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationFileMap
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationFileMap.MachineConfigFilename
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.WebConfigurationFileMap.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.WebConfigurationFileMap
  langs:
  - csharp
  name: WebConfigurationFileMap()
  nameWithType: WebConfigurationFileMap.WebConfigurationFileMap()
  fullName: System.Web.Configuration.WebConfigurationFileMap.WebConfigurationFileMap()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Creates a new instance of the <see cref=&quot;T:System.Web.Configuration.WebConfigurationFileMap&quot;></see> class."
  syntax:
    content: public WebConfigurationFileMap ();
    parameters: []
  overload: System.Web.Configuration.WebConfigurationFileMap.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.WebConfigurationFileMap.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Web.Configuration.WebConfigurationFileMap
  langs:
  - csharp
  name: WebConfigurationFileMap(String)
  nameWithType: WebConfigurationFileMap.WebConfigurationFileMap(String)
  fullName: System.Web.Configuration.WebConfigurationFileMap.WebConfigurationFileMap(String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Web.Configuration.WebConfigurationFileMap&quot;></see> class by using the specified machine configuration file name."
  remarks: "You use this constructor when you are targeting a version of the [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] that is earlier than the latest one that is installed on the computer. The method enables you to specify a machine configuration file that is appropriate to the version of the [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] that you are targeting.      > [!NOTE] >  Even though the constructor only accepts the path to the Machine.config file, the configuration system will also read the root Web.config file in the same directory where the Machine.config file exists."
  syntax:
    content: public WebConfigurationFileMap (string machineConfigFileName);
    parameters:
    - id: machineConfigFileName
      type: System.String
      description: "The machine configuration file name with the complete physical path (for example, `c:\\Windows\\Microsoft.NET\\Framework\\v2.0.50727\\CONFIG\\machine.config`)."
  overload: System.Web.Configuration.WebConfigurationFileMap.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.WebConfigurationFileMap.Clone
  id: Clone
  parent: System.Web.Configuration.WebConfigurationFileMap
  langs:
  - csharp
  name: Clone()
  nameWithType: WebConfigurationFileMap.Clone()
  fullName: System.Web.Configuration.WebConfigurationFileMap.Clone()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Creates a new instance of a <see cref=&quot;T:System.Web.Configuration.WebConfigurationFileMap&quot;></see> class with the same value as the existing instance."
  syntax:
    content: public override object Clone ();
    parameters: []
    return:
      type: System.Object
      description: "To be added."
  overload: System.Web.Configuration.WebConfigurationFileMap.Clone*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories
  id: VirtualDirectories
  parent: System.Web.Configuration.WebConfigurationFileMap
  langs:
  - csharp
  name: VirtualDirectories
  nameWithType: WebConfigurationFileMap.VirtualDirectories
  fullName: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets the listed collection of virtual directories for a Web application."
  remarks: "The virtual directories of a Web application may not necessarily map to the physical directories on the server. The <xref:System.Web.Configuration.VirtualDirectoryMapping> class is independent of IIS."
  syntax:
    content: public System.Web.Configuration.VirtualDirectoryMappingCollection VirtualDirectories { get; }
    return:
      type: System.Web.Configuration.VirtualDirectoryMappingCollection
      description: "A collection of <see cref=&quot;T:System.Web.Configuration.VirtualDirectoryMapping&quot;></see> objects."
  overload: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationFileMap
  isExternal: false
  name: System.Configuration.ConfigurationFileMap
- uid: System.Web.Configuration.WebConfigurationFileMap.#ctor
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: WebConfigurationFileMap()
  nameWithType: WebConfigurationFileMap.WebConfigurationFileMap()
  fullName: System.Web.Configuration.WebConfigurationFileMap.WebConfigurationFileMap()
- uid: System.Web.Configuration.WebConfigurationFileMap.#ctor(System.String)
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: WebConfigurationFileMap(String)
  nameWithType: WebConfigurationFileMap.WebConfigurationFileMap(String)
  fullName: System.Web.Configuration.WebConfigurationFileMap.WebConfigurationFileMap(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.WebConfigurationFileMap.Clone
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: Clone()
  nameWithType: WebConfigurationFileMap.Clone()
  fullName: System.Web.Configuration.WebConfigurationFileMap.Clone()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: VirtualDirectories
  nameWithType: WebConfigurationFileMap.VirtualDirectories
  fullName: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories
- uid: System.Web.Configuration.VirtualDirectoryMappingCollection
  parent: System.Web.Configuration
  isExternal: false
  name: VirtualDirectoryMappingCollection
  nameWithType: VirtualDirectoryMappingCollection
  fullName: System.Web.Configuration.VirtualDirectoryMappingCollection
- uid: System.Web.Configuration.WebConfigurationFileMap.#ctor*
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: WebConfigurationFileMap
  nameWithType: WebConfigurationFileMap.WebConfigurationFileMap
- uid: System.Web.Configuration.WebConfigurationFileMap.Clone*
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: Clone
  nameWithType: WebConfigurationFileMap.Clone
- uid: System.Web.Configuration.WebConfigurationFileMap.VirtualDirectories*
  parent: System.Web.Configuration.WebConfigurationFileMap
  isExternal: false
  name: VirtualDirectories
  nameWithType: WebConfigurationFileMap.VirtualDirectories
