### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement
  id: BookmarkResumptionQueryElement
  children:
  - System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.#ctor
  - System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Name
  - System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.NewTrackingQuery
  - System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Properties
  langs:
  - csharp
  name: BookmarkResumptionQueryElement
  nameWithType: BookmarkResumptionQueryElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement
  type: Class
  summary: "A configuration element that represents a <see cref=&quot;T:System.Activities.Tracking.BookmarkResumptionQuery&quot;></see>."
  syntax:
    content: 'public class BookmarkResumptionQueryElement : System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement.GetStringPairKey(System.String,System.String)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.Annotations
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.ElementKey
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement.UpdateTrackingQuery(System.Activities.Tracking.TrackingQuery)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement
  langs:
  - csharp
  name: BookmarkResumptionQueryElement()
  nameWithType: BookmarkResumptionQueryElement.BookmarkResumptionQueryElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.BookmarkResumptionQueryElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement&quot;></see> class."
  syntax:
    content: public BookmarkResumptionQueryElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Name
  id: Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement
  langs:
  - csharp
  name: Name
  nameWithType: BookmarkResumptionQueryElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Name
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Gets or sets the name of the bookmark."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "The bookmark name."
  overload: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Name*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.NewTrackingQuery
  id: NewTrackingQuery
  parent: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement
  langs:
  - csharp
  name: NewTrackingQuery()
  nameWithType: BookmarkResumptionQueryElement.NewTrackingQuery()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.NewTrackingQuery()
  type: Method
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Creates the <see cref=&quot;T:System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement&quot;></see>."
  syntax:
    content: protected override System.Activities.Tracking.TrackingQuery NewTrackingQuery ();
    parameters: []
    return:
      type: System.Activities.Tracking.TrackingQuery
      description: "To be added."
  overload: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.NewTrackingQuery*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement
  langs:
  - csharp
  name: Properties
  nameWithType: BookmarkResumptionQueryElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Gets a <see cref=&quot;T:System.Configuration.ConfigurationPropertyCollection&quot;></see> that contains the properties associated with this element."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A collection of properties."
  overload: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
  isExternal: false
  name: System.ServiceModel.Activities.Tracking.Configuration.TrackingQueryElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.#ctor
  parent: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement
  isExternal: false
  name: BookmarkResumptionQueryElement()
  nameWithType: BookmarkResumptionQueryElement.BookmarkResumptionQueryElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.BookmarkResumptionQueryElement()
- uid: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement
  isExternal: false
  name: Name
  nameWithType: BookmarkResumptionQueryElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Name
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.NewTrackingQuery
  parent: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement
  isExternal: false
  name: NewTrackingQuery()
  nameWithType: BookmarkResumptionQueryElement.NewTrackingQuery()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.NewTrackingQuery()
- uid: System.Activities.Tracking.TrackingQuery
  parent: System.Activities.Tracking
  isExternal: false
  name: TrackingQuery
  nameWithType: TrackingQuery
  fullName: System.Activities.Tracking.TrackingQuery
- uid: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement
  isExternal: false
  name: Properties
  nameWithType: BookmarkResumptionQueryElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.#ctor*
  parent: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement
  isExternal: false
  name: BookmarkResumptionQueryElement
  nameWithType: BookmarkResumptionQueryElement.BookmarkResumptionQueryElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Name*
  parent: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement
  isExternal: false
  name: Name
  nameWithType: BookmarkResumptionQueryElement.Name
- uid: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.NewTrackingQuery*
  parent: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement
  isExternal: false
  name: NewTrackingQuery
  nameWithType: BookmarkResumptionQueryElement.NewTrackingQuery
- uid: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement.Properties*
  parent: System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElement
  isExternal: false
  name: Properties
  nameWithType: BookmarkResumptionQueryElement.Properties
