### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ComContractsSection
  id: ComContractsSection
  children:
  - System.ServiceModel.Configuration.ComContractsSection.#ctor
  - System.ServiceModel.Configuration.ComContractsSection.ComContracts
  - System.ServiceModel.Configuration.ComContractsSection.Properties
  langs:
  - csharp
  name: ComContractsSection
  nameWithType: ComContractsSection
  fullName: System.ServiceModel.Configuration.ComContractsSection
  type: Class
  summary: "Represents a configuration section that contains elements for specifying the namespace and contract name for a COM+ integration contract. This class cannot be inherited."
  remarks: "The COM+ integration service contracts are currently restricted to the “http://tempuri.org” namespace, and contract name is derived from the supporting COM interface. You can, however, specify alternatives by using the `comContracts` section in the configuration file. For example, you can use the following configuration to specify the namespace and contract name for a service contract       [!CODE [S_UEComContractsSection#0](../CodeSnippet/VS_Snippets_CFX/s_uecomcontractssection#0)]       When the service is initialized, the specified namespaces and contract names are applied to the generated service descriptions.       When this section is empty, the service initialization applies a default namespace and contract name taken from the supporting COM interface ID."
  syntax:
    content: 'public sealed class ComContractsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ComContractsSection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ComContractsSection
  langs:
  - csharp
  name: ComContractsSection()
  nameWithType: ComContractsSection.ComContractsSection()
  fullName: System.ServiceModel.Configuration.ComContractsSection.ComContractsSection()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.ComContractsSection&quot;></see> class."
  syntax:
    content: public ComContractsSection ();
    parameters: []
  overload: System.ServiceModel.Configuration.ComContractsSection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ComContractsSection.ComContracts
  id: ComContracts
  parent: System.ServiceModel.Configuration.ComContractsSection
  langs:
  - csharp
  name: ComContracts
  nameWithType: ComContractsSection.ComContracts
  fullName: System.ServiceModel.Configuration.ComContractsSection.ComContracts
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets all the COM+ integration service contracts specified in the section."
  syntax:
    content: public System.ServiceModel.Configuration.ComContractElementCollection ComContracts { get; }
    return:
      type: System.ServiceModel.Configuration.ComContractElementCollection
      description: "A <see cref=&quot;T:System.ServiceModel.Configuration.ComContractElementCollection&quot;></see> that contains all the COM+ integration service contracts specified in the section."
  overload: System.ServiceModel.Configuration.ComContractsSection.ComContracts*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ComContractsSection.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ComContractsSection
  langs:
  - csharp
  name: Properties
  nameWithType: ComContractsSection.Properties
  fullName: System.ServiceModel.Configuration.ComContractsSection.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.ComContractsSection.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.ServiceModel.Configuration.ComContractsSection.#ctor
  parent: System.ServiceModel.Configuration.ComContractsSection
  isExternal: false
  name: ComContractsSection()
  nameWithType: ComContractsSection.ComContractsSection()
  fullName: System.ServiceModel.Configuration.ComContractsSection.ComContractsSection()
- uid: System.ServiceModel.Configuration.ComContractsSection.ComContracts
  parent: System.ServiceModel.Configuration.ComContractsSection
  isExternal: false
  name: ComContracts
  nameWithType: ComContractsSection.ComContracts
  fullName: System.ServiceModel.Configuration.ComContractsSection.ComContracts
- uid: System.ServiceModel.Configuration.ComContractElementCollection
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ComContractElementCollection
  nameWithType: ComContractElementCollection
  fullName: System.ServiceModel.Configuration.ComContractElementCollection
- uid: System.ServiceModel.Configuration.ComContractsSection.Properties
  parent: System.ServiceModel.Configuration.ComContractsSection
  isExternal: false
  name: Properties
  nameWithType: ComContractsSection.Properties
  fullName: System.ServiceModel.Configuration.ComContractsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ComContractsSection.#ctor*
  parent: System.ServiceModel.Configuration.ComContractsSection
  isExternal: false
  name: ComContractsSection
  nameWithType: ComContractsSection.ComContractsSection
- uid: System.ServiceModel.Configuration.ComContractsSection.ComContracts*
  parent: System.ServiceModel.Configuration.ComContractsSection
  isExternal: false
  name: ComContracts
  nameWithType: ComContractsSection.ComContracts
- uid: System.ServiceModel.Configuration.ComContractsSection.Properties*
  parent: System.ServiceModel.Configuration.ComContractsSection
  isExternal: false
  name: Properties
  nameWithType: ComContractsSection.Properties
