### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  id: FindCriteriaElement
  children:
  - System.ServiceModel.Discovery.Configuration.FindCriteriaElement.#ctor
  - System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ContractTypeNames
  - System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Duration
  - System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Extensions
  - System.ServiceModel.Discovery.Configuration.FindCriteriaElement.MaxResults
  - System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Properties
  - System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ScopeMatchBy
  - System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Scopes
  langs:
  - csharp
  name: FindCriteriaElement
  nameWithType: FindCriteriaElement
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  type: Class
  summary: "Manages a configuration element that contains a set of criteria used by a client application to search for workflow services over a network or the Internet."
  syntax:
    content: 'public sealed class FindCriteriaElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  langs:
  - csharp
  name: FindCriteriaElement()
  nameWithType: FindCriteriaElement.FindCriteriaElement()
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.FindCriteriaElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Creates a new instance of the <see cref=&quot;T:System.ServiceModel.Discovery.Configuration.FindCriteriaElement&quot;></see> class."
  syntax:
    content: public FindCriteriaElement ();
    parameters: []
  overload: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ContractTypeNames
  id: ContractTypeNames
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  langs:
  - csharp
  name: ContractTypeNames
  nameWithType: FindCriteriaElement.ContractTypeNames
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ContractTypeNames
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Gets a collection of configuration elements that contain the names of workflow service contract types."
  syntax:
    content: public System.ServiceModel.Discovery.Configuration.ContractTypeNameElementCollection ContractTypeNames { get; }
    return:
      type: System.ServiceModel.Discovery.Configuration.ContractTypeNameElementCollection
      description: "A collection of elements."
  overload: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ContractTypeNames*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Duration
  id: Duration
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  langs:
  - csharp
  name: Duration
  nameWithType: FindCriteriaElement.Duration
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Duration
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Gets or sets the maximum time to wait for replies from services on a network or the Internet."
  syntax:
    content: public TimeSpan Duration { get; set; }
    return:
      type: System.TimeSpan
      description: "A timespan object the defines the waiting period."
  overload: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Duration*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Extensions
  id: Extensions
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  langs:
  - csharp
  name: Extensions
  nameWithType: FindCriteriaElement.Extensions
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Extensions
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Gets the <see cref=&quot;T:System.ServiceModel.Configuration.XmlElementElementCollection&quot;></see> object that provide extensions for a <see cref=&quot;T:System.ServiceModel.Discovery.Configuration.FindCriteriaElement&quot;></see>."
  syntax:
    content: public System.ServiceModel.Configuration.XmlElementElementCollection Extensions { get; }
    return:
      type: System.ServiceModel.Configuration.XmlElementElementCollection
      description: "A collection of elements."
  overload: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Extensions*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.MaxResults
  id: MaxResults
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  langs:
  - csharp
  name: MaxResults
  nameWithType: FindCriteriaElement.MaxResults
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.MaxResults
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Gets or sets the maximum number of replies to wait for, from services on a network or the Internet."
  remarks: "If MaxResults replies are received before <xref:System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Duration%2A> has elapsed, the find operation ends."
  syntax:
    content: public int MaxResults { get; set; }
    return:
      type: System.Int32
      description: "A maximum number."
  overload: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.MaxResults*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Properties
  id: Properties
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  langs:
  - csharp
  name: Properties
  nameWithType: FindCriteriaElement.Properties
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ScopeMatchBy
  id: ScopeMatchBy
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  langs:
  - csharp
  name: ScopeMatchBy
  nameWithType: FindCriteriaElement.ScopeMatchBy
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ScopeMatchBy
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Gets or sets a URI that designates the name and location of a service that is being searched for and against which members of the &lt;xref:System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Scopes%2A&gt; collection are matched."
  syntax:
    content: public Uri ScopeMatchBy { get; set; }
    return:
      type: System.Uri
      description: "The URI of a service application."
  overload: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ScopeMatchBy*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Scopes
  id: Scopes
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  langs:
  - csharp
  name: Scopes
  nameWithType: FindCriteriaElement.Scopes
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Scopes
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Gets a collection of <see cref=&quot;T:System.ServiceModel.Discovery.Configuration.FindCriteriaElement&quot;></see> objects that contain absolute URIs that are used during a find operation to locate a specific service or services."
  remarks: "If the specific service is found, a successful match has been made between the service URI and the Scope URI, sometimes with the help of scope rules that handle complications of matching."
  syntax:
    content: public System.ServiceModel.Discovery.Configuration.ScopeElementCollection Scopes { get; }
    return:
      type: System.ServiceModel.Discovery.Configuration.ScopeElementCollection
      description: "A collection of elements that contain URIs."
  overload: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Scopes*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.#ctor
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: FindCriteriaElement()
  nameWithType: FindCriteriaElement.FindCriteriaElement()
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.FindCriteriaElement()
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ContractTypeNames
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: ContractTypeNames
  nameWithType: FindCriteriaElement.ContractTypeNames
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ContractTypeNames
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElementCollection
  parent: System.ServiceModel.Discovery.Configuration
  isExternal: false
  name: ContractTypeNameElementCollection
  nameWithType: ContractTypeNameElementCollection
  fullName: System.ServiceModel.Discovery.Configuration.ContractTypeNameElementCollection
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Duration
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: Duration
  nameWithType: FindCriteriaElement.Duration
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Duration
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Extensions
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: Extensions
  nameWithType: FindCriteriaElement.Extensions
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Extensions
- uid: System.ServiceModel.Configuration.XmlElementElementCollection
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: XmlElementElementCollection
  nameWithType: XmlElementElementCollection
  fullName: System.ServiceModel.Configuration.XmlElementElementCollection
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.MaxResults
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: MaxResults
  nameWithType: FindCriteriaElement.MaxResults
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.MaxResults
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Properties
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: Properties
  nameWithType: FindCriteriaElement.Properties
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ScopeMatchBy
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: ScopeMatchBy
  nameWithType: FindCriteriaElement.ScopeMatchBy
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ScopeMatchBy
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Scopes
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: Scopes
  nameWithType: FindCriteriaElement.Scopes
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Scopes
- uid: System.ServiceModel.Discovery.Configuration.ScopeElementCollection
  parent: System.ServiceModel.Discovery.Configuration
  isExternal: false
  name: ScopeElementCollection
  nameWithType: ScopeElementCollection
  fullName: System.ServiceModel.Discovery.Configuration.ScopeElementCollection
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.#ctor*
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: FindCriteriaElement
  nameWithType: FindCriteriaElement.FindCriteriaElement
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ContractTypeNames*
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: ContractTypeNames
  nameWithType: FindCriteriaElement.ContractTypeNames
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Duration*
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: Duration
  nameWithType: FindCriteriaElement.Duration
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Extensions*
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: Extensions
  nameWithType: FindCriteriaElement.Extensions
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.MaxResults*
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: MaxResults
  nameWithType: FindCriteriaElement.MaxResults
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Properties*
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: Properties
  nameWithType: FindCriteriaElement.Properties
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ScopeMatchBy*
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: ScopeMatchBy
  nameWithType: FindCriteriaElement.ScopeMatchBy
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Scopes*
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: Scopes
  nameWithType: FindCriteriaElement.Scopes
