### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ComContractElementCollection
  id: ComContractElementCollection
  children:
  - System.ServiceModel.Configuration.ComContractElementCollection.#ctor
  - System.ServiceModel.Configuration.ComContractElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ComContractElementCollection.ThrowOnDuplicate
  langs:
  - csharp
  name: ComContractElementCollection
  nameWithType: ComContractElementCollection
  fullName: System.ServiceModel.Configuration.ComContractElementCollection
  type: Class
  summary: "Represents a collection of <xref href=&quot;System.ServiceModel.Configuration.ComContractElement&quot;></xref> instances. This class cannot be inherited."
  syntax:
    content: >-
      [System.Configuration.ConfigurationCollection(typeof(System.ServiceModel.Configuration.ComContractElement), AddItemName="comContract")]

      public sealed class ComContractElementCollection : System.ServiceModel.Configuration.ServiceModelEnhancedConfigurationElementCollection<System.ServiceModel.Configuration.ComContractElement>
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationElementCollection
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1
  - System.ServiceModel.Configuration.ServiceModelEnhancedConfigurationElementCollection`1
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.AddElementName
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Configuration.ConfigurationElement,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Int32,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseClear
  - System.Configuration.ConfigurationElementCollection.BaseGet(System.Int32)
  - System.Configuration.ConfigurationElementCollection.BaseGet(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseGetAllKeys
  - System.Configuration.ConfigurationElementCollection.BaseGetKey(System.Int32)
  - System.Configuration.ConfigurationElementCollection.BaseIndexOf(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseIsRemoved(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseRemove(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseRemoveAt(System.Int32)
  - System.Configuration.ConfigurationElementCollection.ClearElementName
  - System.Configuration.ConfigurationElementCollection.CopyTo(System.Configuration.ConfigurationElement[],System.Int32)
  - System.Configuration.ConfigurationElementCollection.Count
  - System.Configuration.ConfigurationElementCollection.CreateNewElement(System.String)
  - System.Configuration.ConfigurationElementCollection.EmitClear
  - System.Configuration.ConfigurationElementCollection.Equals(System.Object)
  - System.Configuration.ConfigurationElementCollection.GetEnumerator
  - System.Configuration.ConfigurationElementCollection.GetHashCode
  - System.Configuration.ConfigurationElementCollection.IsElementName(System.String)
  - System.Configuration.ConfigurationElementCollection.IsElementRemovable(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.IsModified
  - System.Configuration.ConfigurationElementCollection.IsReadOnly
  - System.Configuration.ConfigurationElementCollection.IsSynchronized
  - System.Configuration.ConfigurationElementCollection.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElementCollection.RemoveElementName
  - System.Configuration.ConfigurationElementCollection.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.ResetModified
  - System.Configuration.ConfigurationElementCollection.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.SetReadOnly
  - System.Configuration.ConfigurationElementCollection.SyncRoot
  - System.Configuration.ConfigurationElementCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  - System.Configuration.ConfigurationElementCollection.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Add(`0)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Clear
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.CollectionType
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.ContainsKey(System.Object)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.CopyTo(`0[],System.Int32)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.CreateNewElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.ElementName
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.IndexOf(`0)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Item(System.Int32)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Item(System.Object)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Remove(`0)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.RemoveAt(System.Int32)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.RemoveAt(System.Object)
  - System.ServiceModel.Configuration.ServiceModelEnhancedConfigurationElementCollection`1.BaseAdd(System.Configuration.ConfigurationElement)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComContractElementCollection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ComContractElementCollection
  langs:
  - csharp
  name: ComContractElementCollection()
  nameWithType: ComContractElementCollection.ComContractElementCollection()
  fullName: System.ServiceModel.Configuration.ComContractElementCollection.ComContractElementCollection()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <xref href=&quot;System.ServiceModel.Configuration.ComContractElementCollection&quot;></xref> class."
  syntax:
    content: public ComContractElementCollection ();
    parameters: []
  overload: System.ServiceModel.Configuration.ComContractElementCollection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComContractElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  id: GetElementKey(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Configuration.ComContractElementCollection
  langs:
  - csharp
  name: GetElementKey(ConfigurationElement)
  nameWithType: ComContractElementCollection.GetElementKey(ConfigurationElement)
  fullName: System.ServiceModel.Configuration.ComContractElementCollection.GetElementKey(ConfigurationElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override object GetElementKey (System.Configuration.ConfigurationElement element);
    parameters:
    - id: element
      type: System.Configuration.ConfigurationElement
      description: "To be added."
    return:
      type: System.Object
      description: "To be added."
  overload: System.ServiceModel.Configuration.ComContractElementCollection.GetElementKey*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComContractElementCollection.ThrowOnDuplicate
  id: ThrowOnDuplicate
  parent: System.ServiceModel.Configuration.ComContractElementCollection
  langs:
  - csharp
  name: ThrowOnDuplicate
  nameWithType: ComContractElementCollection.ThrowOnDuplicate
  fullName: System.ServiceModel.Configuration.ComContractElementCollection.ThrowOnDuplicate
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override bool ThrowOnDuplicate { get; }
    return:
      type: System.Boolean
      description: "To be added."
  overload: System.ServiceModel.Configuration.ComContractElementCollection.ThrowOnDuplicate*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelEnhancedConfigurationElementCollection`1
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelEnhancedConfigurationElementCollection<System.ServiceModel.Configuration.ComContractElement>
- uid: System.ServiceModel.Configuration.ComContractElementCollection.#ctor
  parent: System.ServiceModel.Configuration.ComContractElementCollection
  isExternal: false
  name: ComContractElementCollection()
  nameWithType: ComContractElementCollection.ComContractElementCollection()
  fullName: System.ServiceModel.Configuration.ComContractElementCollection.ComContractElementCollection()
- uid: System.ServiceModel.Configuration.ComContractElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Configuration.ComContractElementCollection
  isExternal: false
  name: GetElementKey(ConfigurationElement)
  nameWithType: ComContractElementCollection.GetElementKey(ConfigurationElement)
  fullName: System.ServiceModel.Configuration.ComContractElementCollection.GetElementKey(ConfigurationElement)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.ComContractElementCollection.ThrowOnDuplicate
  parent: System.ServiceModel.Configuration.ComContractElementCollection
  isExternal: false
  name: ThrowOnDuplicate
  nameWithType: ComContractElementCollection.ThrowOnDuplicate
  fullName: System.ServiceModel.Configuration.ComContractElementCollection.ThrowOnDuplicate
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.ComContractElementCollection.#ctor*
  parent: System.ServiceModel.Configuration.ComContractElementCollection
  isExternal: false
  name: ComContractElementCollection
  nameWithType: ComContractElementCollection.ComContractElementCollection
- uid: System.ServiceModel.Configuration.ComContractElementCollection.GetElementKey*
  parent: System.ServiceModel.Configuration.ComContractElementCollection
  isExternal: false
  name: GetElementKey
  nameWithType: ComContractElementCollection.GetElementKey
- uid: System.ServiceModel.Configuration.ComContractElementCollection.ThrowOnDuplicate*
  parent: System.ServiceModel.Configuration.ComContractElementCollection
  isExternal: false
  name: ThrowOnDuplicate
  nameWithType: ComContractElementCollection.ThrowOnDuplicate
