### YamlMime:ManagedReference
items:
- uid: System.Configuration.GenericEnumConverter
  id: GenericEnumConverter
  children:
  - System.Configuration.GenericEnumConverter.#ctor(System.Type)
  - System.Configuration.GenericEnumConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.Configuration.GenericEnumConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  name: GenericEnumConverter
  nameWithType: GenericEnumConverter
  fullName: System.Configuration.GenericEnumConverter
  type: Class
  summary: "Converts between a string and an enumeration type."
  remarks: "This type, like all the other configuration converter types, converts strings found in the configuration file to and from the related strongly typed properties.       In particular, the GenericEnumConverter object converts a <xref:System.String> value, assigned to a configuration property, to an <xref:System.Enum> value and vice versa."
  example:
  - "The following code example shows how to access a custom section property that uses the GenericEnumConverter type.  \n  \n [!code-cs[System.Configuration.GenericEnumConverter#1](~/add/codesnippet/CSharp/t-system.configuration.g_1.cs)]\n [!code-vb[System.Configuration.GenericEnumConverter#1](~/add/codesnippet/VisualBasic/t-system.configuration.g_1.vb)]  \n  \n The following code example shows how to define a custom enumerator property accessed in the previous example. Notice that there is no need to specify the GenericEnumConverter type; it is implicitly invoked by the system.  \n  \n [!code-cs[System.Configuration.ConfigurationConvertersCustomSection#5](~/add/codesnippet/CSharp/t-system.configuration.g_2.cs)]\n [!code-vb[System.Configuration.ConfigurationConvertersCustomSection#5](~/add/codesnippet/VisualBasic/t-system.configuration.g_2.vb)]  \n  \n The following example is a configuration excerpt used by the previous example.  \n  \n```  \n<?xml version=\"1.0\" encoding=\"utf-8\"?>  \n<configuration>  \n  \n  <configSections>  \n    <section name=\"CustomSection\"   \n      type=\"Samples.AspNet.CustomSection,   \n      ConfigurationConverters,   \n      Version=1.0.0.0, Culture=neutral,   \n      PublicKeyToken=null\"   \n      allowDefinition=\"Everywhere\"   \n      allowExeDefinition=\"MachineToApplication\"   \n      restartOnExternalChanges=\"true\" />  \n  </configSections>  \n  \n  <CustomSection fileName=\"default.txt\" maxIdleTime=\"90\" timeDelay=\"infinite\" cdStr=\"str0, str1\" permission=\"Read\" maxUsers=\"Infinite\"/>  \n  \n</configuration>  \n```"
  syntax:
    content: 'public sealed class GenericEnumConverter : System.Configuration.ConfigurationConverterBase'
  inheritance:
  - System.Object
  - System.ComponentModel.TypeConverter
  - System.Configuration.ConfigurationConverterBase
  implements: []
  inheritedMembers:
  - System.ComponentModel.TypeConverter.CanConvertFrom(System.Type)
  - System.ComponentModel.TypeConverter.CanConvertTo(System.Type)
  - System.ComponentModel.TypeConverter.ConvertFrom(System.Object)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.String)
  - System.ComponentModel.TypeConverter.ConvertTo(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.Object)
  - System.ComponentModel.TypeConverter.CreateInstance(System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.CreateInstance(System.ComponentModel.ITypeDescriptorContext,System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.GetConvertFromException(System.Object)
  - System.ComponentModel.TypeConverter.GetConvertToException(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object,System.Attribute[])
  - System.ComponentModel.TypeConverter.GetProperties(System.Object)
  - System.ComponentModel.TypeConverter.GetPropertiesSupported
  - System.ComponentModel.TypeConverter.GetPropertiesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValues
  - System.ComponentModel.TypeConverter.GetStandardValues(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.IsValid(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.IsValid(System.Object)
  - System.ComponentModel.TypeConverter.SortProperties(System.ComponentModel.PropertyDescriptorCollection,System.String[])
  - System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.GenericEnumConverter.#ctor(System.Type)
  id: '#ctor(System.Type)'
  parent: System.Configuration.GenericEnumConverter
  langs:
  - csharp
  name: GenericEnumConverter(Type)
  nameWithType: GenericEnumConverter.GenericEnumConverter(Type)
  fullName: System.Configuration.GenericEnumConverter.GenericEnumConverter(Type)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.GenericEnumConverter&quot;></see> class."
  remarks: "Normally, you use the converter types provided by the system. The only time you need to use the GenericEnumConverter constructor is when you create your own conversion type."
  syntax:
    content: public GenericEnumConverter (Type typeEnum);
    parameters:
    - id: typeEnum
      type: System.Type
      description: "The enumeration type to convert."
  overload: System.Configuration.GenericEnumConverter.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "\n    typeEnum is ."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.GenericEnumConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.GenericEnumConverter
  langs:
  - csharp
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: GenericEnumConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.GenericEnumConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Converts a &lt;xref:System.String&gt; to an &lt;xref:System.Enum&gt; type."
  remarks: "The system uses the ConvertFrom method when it reads from a configuration file to convert a <xref:System.String> value to an <xref:System.Enum> type."
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object data);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "The  object used for type conversions."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "The <xref:System.Globalization.CultureInfo> object used during conversion."
    - id: data
      type: System.Object
      description: "The <xref:System.String> object to convert."
    return:
      type: System.Object
      description: "To be added."
  overload: System.Configuration.GenericEnumConverter.ConvertFrom*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "\n    data is null or an empty string (\"\").  \n  \n \\- or -  \n  \n data starts with a numeric character.  \n  \n \\- or -  \n  \n data includes white space."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.GenericEnumConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.GenericEnumConverter
  langs:
  - csharp
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: GenericEnumConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.GenericEnumConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Converts an &lt;xref:System.Enum&gt; type to a &lt;xref:System.String&gt; value."
  remarks: "The system uses the ConvertTo method when it writes to a configuration file to convert a <xref:System.Enum> type to a <xref:System.String> value."
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object value, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "The  object used for type conversions."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "The <xref:System.Globalization.CultureInfo> object used during conversion."
    - id: value
      type: System.Object
      description: "The value to convert to."
    - id: type
      type: System.Type
      description: "The type to convert to."
    return:
      type: System.Object
      description: "To be added."
  overload: System.Configuration.GenericEnumConverter.ConvertTo*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationConverterBase
  isExternal: false
  name: System.Configuration.ConfigurationConverterBase
- uid: System.Configuration.GenericEnumConverter.#ctor(System.Type)
  parent: System.Configuration.GenericEnumConverter
  isExternal: false
  name: GenericEnumConverter(Type)
  nameWithType: GenericEnumConverter.GenericEnumConverter(Type)
  fullName: System.Configuration.GenericEnumConverter.GenericEnumConverter(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.GenericEnumConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.GenericEnumConverter
  isExternal: false
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: GenericEnumConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.GenericEnumConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: false
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: true
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Configuration.GenericEnumConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.GenericEnumConverter
  isExternal: false
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: GenericEnumConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.GenericEnumConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
- uid: System.Configuration.GenericEnumConverter.#ctor*
  parent: System.Configuration.GenericEnumConverter
  isExternal: false
  name: GenericEnumConverter
  nameWithType: GenericEnumConverter.GenericEnumConverter
- uid: System.Configuration.GenericEnumConverter.ConvertFrom*
  parent: System.Configuration.GenericEnumConverter
  isExternal: false
  name: ConvertFrom
  nameWithType: GenericEnumConverter.ConvertFrom
- uid: System.Configuration.GenericEnumConverter.ConvertTo*
  parent: System.Configuration.GenericEnumConverter
  isExternal: false
  name: ConvertTo
  nameWithType: GenericEnumConverter.ConvertTo
