### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.ChannelCacheSettings
  id: ChannelCacheSettings
  children:
  - System.ServiceModel.Activities.ChannelCacheSettings.#ctor
  - System.ServiceModel.Activities.ChannelCacheSettings.IdleTimeout
  - System.ServiceModel.Activities.ChannelCacheSettings.LeaseTimeout
  - System.ServiceModel.Activities.ChannelCacheSettings.MaxItemsInCache
  langs:
  - csharp
  name: ChannelCacheSettings
  nameWithType: ChannelCacheSettings
  fullName: System.ServiceModel.Activities.ChannelCacheSettings
  type: Class
  summary: "Represents settings that define operational characteristics of a channel cache."
  remarks: ''
  example:
  - "The following example shows how to create a ChannelCacheSettings instance.  \n  \n [!code-cs[ChannelCache#0](~/add/codesnippet/CSharp/t-system.servicemodel.ac_21_1.cs)]"
  syntax:
    content: public class ChannelCacheSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.ChannelCacheSettings.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  langs:
  - csharp
  name: ChannelCacheSettings()
  nameWithType: ChannelCacheSettings.ChannelCacheSettings()
  fullName: System.ServiceModel.Activities.ChannelCacheSettings.ChannelCacheSettings()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Creates a new instance of the <see cref=&quot;T:System.ServiceModel.Activities.ChannelCacheSettings&quot;></see> class."
  remarks: ''
  example:
  - "The following example shows how to create a <xref:System.ServiceModel.Activities.ChannelCacheSettings> instance.  \n  \n [!code-cs[ChannelCache#0](~/add/codesnippet/CSharp/m-system.servicemodel.ac_8_1.cs)]"
  syntax:
    content: public ChannelCacheSettings ();
    parameters: []
  overload: System.ServiceModel.Activities.ChannelCacheSettings.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.ChannelCacheSettings.IdleTimeout
  id: IdleTimeout
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  langs:
  - csharp
  name: IdleTimeout
  nameWithType: ChannelCacheSettings.IdleTimeout
  fullName: System.ServiceModel.Activities.ChannelCacheSettings.IdleTimeout
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Gets the maximum interval of time for which the object can remain idle in the cache before being disposed."
  remarks: ''
  example:
  - "The following example shows how to set the IdleTimeout property.  \n  \n [!code-cs[ChannelCache#0](~/add/codesnippet/CSharp/p-system.servicemodel.ac_2_1.cs)]"
  syntax:
    content: public TimeSpan IdleTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "An interval of time."
  overload: System.ServiceModel.Activities.ChannelCacheSettings.IdleTimeout*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.ChannelCacheSettings.LeaseTimeout
  id: LeaseTimeout
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  langs:
  - csharp
  name: LeaseTimeout
  nameWithType: ChannelCacheSettings.LeaseTimeout
  fullName: System.ServiceModel.Activities.ChannelCacheSettings.LeaseTimeout
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Gets the interval of time after which an object is removed from the cache."
  remarks: ''
  example:
  - "The following example shows how to set the LeaseTimeout property.  \n  \n [!code-cs[ChannelCache#0](~/add/codesnippet/CSharp/p-system.servicemodel.ac_6_1.cs)]"
  syntax:
    content: public TimeSpan LeaseTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "An interval of time."
  overload: System.ServiceModel.Activities.ChannelCacheSettings.LeaseTimeout*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.ChannelCacheSettings.MaxItemsInCache
  id: MaxItemsInCache
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  langs:
  - csharp
  name: MaxItemsInCache
  nameWithType: ChannelCacheSettings.MaxItemsInCache
  fullName: System.ServiceModel.Activities.ChannelCacheSettings.MaxItemsInCache
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Gets the maximum number of objects that can be in the cache."
  remarks: ''
  example:
  - "The following example shows how to set the MaxItemsInCache property.  \n  \n [!code-cs[ChannelCache#0](~/add/codesnippet/CSharp/p-system.servicemodel.ac_1_1.cs)]"
  syntax:
    content: public int MaxItemsInCache { get; set; }
    return:
      type: System.Int32
      description: "A maximum number of objects."
  overload: System.ServiceModel.Activities.ChannelCacheSettings.MaxItemsInCache*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.Activities.ChannelCacheSettings.#ctor
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  isExternal: false
  name: ChannelCacheSettings()
  nameWithType: ChannelCacheSettings.ChannelCacheSettings()
  fullName: System.ServiceModel.Activities.ChannelCacheSettings.ChannelCacheSettings()
- uid: System.ServiceModel.Activities.ChannelCacheSettings.IdleTimeout
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  isExternal: false
  name: IdleTimeout
  nameWithType: ChannelCacheSettings.IdleTimeout
  fullName: System.ServiceModel.Activities.ChannelCacheSettings.IdleTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Activities.ChannelCacheSettings.LeaseTimeout
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  isExternal: false
  name: LeaseTimeout
  nameWithType: ChannelCacheSettings.LeaseTimeout
  fullName: System.ServiceModel.Activities.ChannelCacheSettings.LeaseTimeout
- uid: System.ServiceModel.Activities.ChannelCacheSettings.MaxItemsInCache
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  isExternal: false
  name: MaxItemsInCache
  nameWithType: ChannelCacheSettings.MaxItemsInCache
  fullName: System.ServiceModel.Activities.ChannelCacheSettings.MaxItemsInCache
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Activities.ChannelCacheSettings.#ctor*
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  isExternal: false
  name: ChannelCacheSettings
  nameWithType: ChannelCacheSettings.ChannelCacheSettings
- uid: System.ServiceModel.Activities.ChannelCacheSettings.IdleTimeout*
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  isExternal: false
  name: IdleTimeout
  nameWithType: ChannelCacheSettings.IdleTimeout
- uid: System.ServiceModel.Activities.ChannelCacheSettings.LeaseTimeout*
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  isExternal: false
  name: LeaseTimeout
  nameWithType: ChannelCacheSettings.LeaseTimeout
- uid: System.ServiceModel.Activities.ChannelCacheSettings.MaxItemsInCache*
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  isExternal: false
  name: MaxItemsInCache
  nameWithType: ChannelCacheSettings.MaxItemsInCache
