### YamlMime:ManagedReference
items:
- uid: System.Net.Mime.MediaTypeNames.Application
  id: MediaTypeNames.Application
  children:
  - System.Net.Mime.MediaTypeNames.Application.Octet
  - System.Net.Mime.MediaTypeNames.Application.Pdf
  - System.Net.Mime.MediaTypeNames.Application.Rtf
  - System.Net.Mime.MediaTypeNames.Application.Soap
  - System.Net.Mime.MediaTypeNames.Application.Zip
  langs:
  - csharp
  name: MediaTypeNames+Application
  nameWithType: MediaTypeNames+Application
  fullName: System.Net.Mime.MediaTypeNames+Application
  type: Class
  syntax:
    content: public static class MediaTypeNames.Application
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Mime.MediaTypeNames.Application.Octet
  id: Octet
  parent: System.Net.Mime.MediaTypeNames.Application
  langs:
  - csharp
  name: Octet
  nameWithType: MediaTypeNames+Application.Octet
  fullName: System.Net.Mime.MediaTypeNames+Application.Octet
  type: Field
  assemblies:
  - System
  namespace: System.Net.Mime
  syntax:
    content: public const string Octet;
    return:
      type: System.String
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Mime.MediaTypeNames.Application.Pdf
  id: Pdf
  parent: System.Net.Mime.MediaTypeNames.Application
  langs:
  - csharp
  name: Pdf
  nameWithType: MediaTypeNames+Application.Pdf
  fullName: System.Net.Mime.MediaTypeNames+Application.Pdf
  type: Field
  assemblies:
  - System
  namespace: System.Net.Mime
  syntax:
    content: public const string Pdf;
    return:
      type: System.String
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Mime.MediaTypeNames.Application.Rtf
  id: Rtf
  parent: System.Net.Mime.MediaTypeNames.Application
  langs:
  - csharp
  name: Rtf
  nameWithType: MediaTypeNames+Application.Rtf
  fullName: System.Net.Mime.MediaTypeNames+Application.Rtf
  type: Field
  assemblies:
  - System
  namespace: System.Net.Mime
  syntax:
    content: public const string Rtf;
    return:
      type: System.String
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Mime.MediaTypeNames.Application.Soap
  id: Soap
  parent: System.Net.Mime.MediaTypeNames.Application
  langs:
  - csharp
  name: Soap
  nameWithType: MediaTypeNames+Application.Soap
  fullName: System.Net.Mime.MediaTypeNames+Application.Soap
  type: Field
  assemblies:
  - System
  namespace: System.Net.Mime
  syntax:
    content: public const string Soap;
    return:
      type: System.String
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Mime.MediaTypeNames.Application.Zip
  id: Zip
  parent: System.Net.Mime.MediaTypeNames.Application
  langs:
  - csharp
  name: Zip
  nameWithType: MediaTypeNames+Application.Zip
  fullName: System.Net.Mime.MediaTypeNames+Application.Zip
  type: Field
  assemblies:
  - System
  namespace: System.Net.Mime
  syntax:
    content: public const string Zip;
    return:
      type: System.String
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Net.Mime.MediaTypeNames.Application.Octet
  parent: System.Net.Mime.MediaTypeNames.Application
  isExternal: false
  name: Octet
  nameWithType: MediaTypeNames+Application.Octet
  fullName: System.Net.Mime.MediaTypeNames+Application.Octet
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Net.Mime.MediaTypeNames.Application.Pdf
  parent: System.Net.Mime.MediaTypeNames.Application
  isExternal: false
  name: Pdf
  nameWithType: MediaTypeNames+Application.Pdf
  fullName: System.Net.Mime.MediaTypeNames+Application.Pdf
- uid: System.Net.Mime.MediaTypeNames.Application.Rtf
  parent: System.Net.Mime.MediaTypeNames.Application
  isExternal: false
  name: Rtf
  nameWithType: MediaTypeNames+Application.Rtf
  fullName: System.Net.Mime.MediaTypeNames+Application.Rtf
- uid: System.Net.Mime.MediaTypeNames.Application.Soap
  parent: System.Net.Mime.MediaTypeNames.Application
  isExternal: false
  name: Soap
  nameWithType: MediaTypeNames+Application.Soap
  fullName: System.Net.Mime.MediaTypeNames+Application.Soap
- uid: System.Net.Mime.MediaTypeNames.Application.Zip
  parent: System.Net.Mime.MediaTypeNames.Application
  isExternal: false
  name: Zip
  nameWithType: MediaTypeNames+Application.Zip
  fullName: System.Net.Mime.MediaTypeNames+Application.Zip
