### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Routing.Configuration.FilterTableCollection
  id: FilterTableCollection
  children:
  - System.ServiceModel.Routing.Configuration.FilterTableCollection.#ctor
  - System.ServiceModel.Routing.Configuration.FilterTableCollection.Add(System.ServiceModel.Routing.Configuration.FilterTableEntryCollection)
  - System.ServiceModel.Routing.Configuration.FilterTableCollection.Clear
  - System.ServiceModel.Routing.Configuration.FilterTableCollection.CreateNewElement
  - System.ServiceModel.Routing.Configuration.FilterTableCollection.GetElementKey(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Routing.Configuration.FilterTableCollection.Item(System.String)
  - System.ServiceModel.Routing.Configuration.FilterTableCollection.Remove(System.ServiceModel.Routing.Configuration.FilterTableEntryCollection)
  langs:
  - csharp
  name: FilterTableCollection
  nameWithType: FilterTableCollection
  fullName: System.ServiceModel.Routing.Configuration.FilterTableCollection
  type: Class
  summary: "Represents the configuration element that contains a collection of <see cref=&quot;T:System.ServiceModel.Routing.Configuration.FilterTableEntryCollection&quot;></see> instances."
  syntax:
    content: >-
      [System.Configuration.ConfigurationCollection(typeof(System.ServiceModel.Routing.Configuration.FilterTableEntryCollection), AddItemName="filterTable")]

      public class FilterTableCollection : System.Configuration.ConfigurationElementCollection
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationElementCollection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.AddElementName
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Configuration.ConfigurationElement,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Int32,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseClear
  - System.Configuration.ConfigurationElementCollection.BaseGet(System.Int32)
  - System.Configuration.ConfigurationElementCollection.BaseGet(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseGetAllKeys
  - System.Configuration.ConfigurationElementCollection.BaseGetKey(System.Int32)
  - System.Configuration.ConfigurationElementCollection.BaseIndexOf(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseIsRemoved(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseRemove(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseRemoveAt(System.Int32)
  - System.Configuration.ConfigurationElementCollection.ClearElementName
  - System.Configuration.ConfigurationElementCollection.CollectionType
  - System.Configuration.ConfigurationElementCollection.CopyTo(System.Configuration.ConfigurationElement[],System.Int32)
  - System.Configuration.ConfigurationElementCollection.Count
  - System.Configuration.ConfigurationElementCollection.CreateNewElement(System.String)
  - System.Configuration.ConfigurationElementCollection.ElementName
  - System.Configuration.ConfigurationElementCollection.EmitClear
  - System.Configuration.ConfigurationElementCollection.Equals(System.Object)
  - System.Configuration.ConfigurationElementCollection.GetEnumerator
  - System.Configuration.ConfigurationElementCollection.GetHashCode
  - System.Configuration.ConfigurationElementCollection.IsElementName(System.String)
  - System.Configuration.ConfigurationElementCollection.IsElementRemovable(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.IsModified
  - System.Configuration.ConfigurationElementCollection.IsReadOnly
  - System.Configuration.ConfigurationElementCollection.IsSynchronized
  - System.Configuration.ConfigurationElementCollection.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElementCollection.RemoveElementName
  - System.Configuration.ConfigurationElementCollection.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.ResetModified
  - System.Configuration.ConfigurationElementCollection.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.SetReadOnly
  - System.Configuration.ConfigurationElementCollection.SyncRoot
  - System.Configuration.ConfigurationElementCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  - System.Configuration.ConfigurationElementCollection.ThrowOnDuplicate
  - System.Configuration.ConfigurationElementCollection.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.FilterTableCollection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Routing.Configuration.FilterTableCollection
  langs:
  - csharp
  name: FilterTableCollection()
  nameWithType: FilterTableCollection.FilterTableCollection()
  fullName: System.ServiceModel.Routing.Configuration.FilterTableCollection.FilterTableCollection()
  type: Constructor
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Creates a new instance of the <see cref=&quot;T:System.ServiceModel.Routing.Configuration.FilterTableCollection&quot;></see> class."
  syntax:
    content: public FilterTableCollection ();
    parameters: []
  overload: System.ServiceModel.Routing.Configuration.FilterTableCollection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.FilterTableCollection.Add(System.ServiceModel.Routing.Configuration.FilterTableEntryCollection)
  id: Add(System.ServiceModel.Routing.Configuration.FilterTableEntryCollection)
  parent: System.ServiceModel.Routing.Configuration.FilterTableCollection
  langs:
  - csharp
  name: Add(FilterTableEntryCollection)
  nameWithType: FilterTableCollection.Add(FilterTableEntryCollection)
  fullName: System.ServiceModel.Routing.Configuration.FilterTableCollection.Add(FilterTableEntryCollection)
  type: Method
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Adds a new <see cref=&quot;T:System.ServiceModel.Routing.Configuration.FilterTableEntryCollection&quot;></see> to the collection."
  syntax:
    content: public void Add (System.ServiceModel.Routing.Configuration.FilterTableEntryCollection element);
    parameters:
    - id: element
      type: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection
      description: "The filter table entry to be added."
  overload: System.ServiceModel.Routing.Configuration.FilterTableCollection.Add*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.FilterTableCollection.Clear
  id: Clear
  parent: System.ServiceModel.Routing.Configuration.FilterTableCollection
  langs:
  - csharp
  name: Clear()
  nameWithType: FilterTableCollection.Clear()
  fullName: System.ServiceModel.Routing.Configuration.FilterTableCollection.Clear()
  type: Method
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Removes all elements from the collection."
  syntax:
    content: public void Clear ();
    parameters: []
  overload: System.ServiceModel.Routing.Configuration.FilterTableCollection.Clear*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.FilterTableCollection.CreateNewElement
  id: CreateNewElement
  parent: System.ServiceModel.Routing.Configuration.FilterTableCollection
  langs:
  - csharp
  name: CreateNewElement()
  nameWithType: FilterTableCollection.CreateNewElement()
  fullName: System.ServiceModel.Routing.Configuration.FilterTableCollection.CreateNewElement()
  type: Method
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Creates a new <see cref=&quot;T:System.Configuration.ConfigurationElement&quot;></see>."
  syntax:
    content: protected override System.Configuration.ConfigurationElement CreateNewElement ();
    parameters: []
    return:
      type: System.Configuration.ConfigurationElement
      description: "To be added."
  overload: System.ServiceModel.Routing.Configuration.FilterTableCollection.CreateNewElement*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.FilterTableCollection.GetElementKey(System.Configuration.ConfigurationElement)
  id: GetElementKey(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Routing.Configuration.FilterTableCollection
  langs:
  - csharp
  name: GetElementKey(ConfigurationElement)
  nameWithType: FilterTableCollection.GetElementKey(ConfigurationElement)
  fullName: System.ServiceModel.Routing.Configuration.FilterTableCollection.GetElementKey(ConfigurationElement)
  type: Method
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Gets the element key for the specified configuration element."
  syntax:
    content: protected override object GetElementKey (System.Configuration.ConfigurationElement element);
    parameters:
    - id: element
      type: System.Configuration.ConfigurationElement
      description: "The configuration element to return the key for."
    return:
      type: System.Object
      description: "To be added."
  overload: System.ServiceModel.Routing.Configuration.FilterTableCollection.GetElementKey*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.FilterTableCollection.Item(System.String)
  id: Item(System.String)
  parent: System.ServiceModel.Routing.Configuration.FilterTableCollection
  langs:
  - csharp
  name: Item(String)
  nameWithType: FilterTableCollection.Item(String)
  fullName: System.ServiceModel.Routing.Configuration.FilterTableCollection.Item(String)
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Gets the <see cref=&quot;T:System.ServiceModel.Routing.Configuration.FilterTableEntryCollection&quot;></see> with the specified index."
  syntax:
    content: public System.ServiceModel.Routing.Configuration.FilterTableEntryCollection this[string name] { get; }
    parameters:
    - id: name
      type: System.String
      description: "The key of the element to be accessed."
    return:
      type: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection
      description: "A filter table entry that matches the specified key."
  overload: System.ServiceModel.Routing.Configuration.FilterTableCollection.Item*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.FilterTableCollection.Remove(System.ServiceModel.Routing.Configuration.FilterTableEntryCollection)
  id: Remove(System.ServiceModel.Routing.Configuration.FilterTableEntryCollection)
  parent: System.ServiceModel.Routing.Configuration.FilterTableCollection
  langs:
  - csharp
  name: Remove(FilterTableEntryCollection)
  nameWithType: FilterTableCollection.Remove(FilterTableEntryCollection)
  fullName: System.ServiceModel.Routing.Configuration.FilterTableCollection.Remove(FilterTableEntryCollection)
  type: Method
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Removes the first occurrence of the specified <see cref=&quot;T:System.ServiceModel.Routing.Configuration.FilterTableEntryCollection&quot;></see> from the collection."
  syntax:
    content: public void Remove (System.ServiceModel.Routing.Configuration.FilterTableEntryCollection element);
    parameters:
    - id: element
      type: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection
      description: "The filter table entry to remove from the collection."
  overload: System.ServiceModel.Routing.Configuration.FilterTableCollection.Remove*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElementCollection
  isExternal: false
  name: System.Configuration.ConfigurationElementCollection
- uid: System.ServiceModel.Routing.Configuration.FilterTableCollection.#ctor
  parent: System.ServiceModel.Routing.Configuration.FilterTableCollection
  isExternal: false
  name: FilterTableCollection()
  nameWithType: FilterTableCollection.FilterTableCollection()
  fullName: System.ServiceModel.Routing.Configuration.FilterTableCollection.FilterTableCollection()
- uid: System.ServiceModel.Routing.Configuration.FilterTableCollection.Add(System.ServiceModel.Routing.Configuration.FilterTableEntryCollection)
  parent: System.ServiceModel.Routing.Configuration.FilterTableCollection
  isExternal: false
  name: Add(FilterTableEntryCollection)
  nameWithType: FilterTableCollection.Add(FilterTableEntryCollection)
  fullName: System.ServiceModel.Routing.Configuration.FilterTableCollection.Add(FilterTableEntryCollection)
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection
  parent: System.ServiceModel.Routing.Configuration
  isExternal: false
  name: FilterTableEntryCollection
  nameWithType: FilterTableEntryCollection
  fullName: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection
- uid: System.ServiceModel.Routing.Configuration.FilterTableCollection.Clear
  parent: System.ServiceModel.Routing.Configuration.FilterTableCollection
  isExternal: false
  name: Clear()
  nameWithType: FilterTableCollection.Clear()
  fullName: System.ServiceModel.Routing.Configuration.FilterTableCollection.Clear()
- uid: System.ServiceModel.Routing.Configuration.FilterTableCollection.CreateNewElement
  parent: System.ServiceModel.Routing.Configuration.FilterTableCollection
  isExternal: false
  name: CreateNewElement()
  nameWithType: FilterTableCollection.CreateNewElement()
  fullName: System.ServiceModel.Routing.Configuration.FilterTableCollection.CreateNewElement()
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Routing.Configuration.FilterTableCollection.GetElementKey(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Routing.Configuration.FilterTableCollection
  isExternal: false
  name: GetElementKey(ConfigurationElement)
  nameWithType: FilterTableCollection.GetElementKey(ConfigurationElement)
  fullName: System.ServiceModel.Routing.Configuration.FilterTableCollection.GetElementKey(ConfigurationElement)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Routing.Configuration.FilterTableCollection.Item(System.String)
  parent: System.ServiceModel.Routing.Configuration.FilterTableCollection
  isExternal: false
  name: Item(String)
  nameWithType: FilterTableCollection.Item(String)
  fullName: System.ServiceModel.Routing.Configuration.FilterTableCollection.Item(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Routing.Configuration.FilterTableCollection.Remove(System.ServiceModel.Routing.Configuration.FilterTableEntryCollection)
  parent: System.ServiceModel.Routing.Configuration.FilterTableCollection
  isExternal: false
  name: Remove(FilterTableEntryCollection)
  nameWithType: FilterTableCollection.Remove(FilterTableEntryCollection)
  fullName: System.ServiceModel.Routing.Configuration.FilterTableCollection.Remove(FilterTableEntryCollection)
- uid: System.ServiceModel.Routing.Configuration.FilterTableCollection.#ctor*
  parent: System.ServiceModel.Routing.Configuration.FilterTableCollection
  isExternal: false
  name: FilterTableCollection
  nameWithType: FilterTableCollection.FilterTableCollection
- uid: System.ServiceModel.Routing.Configuration.FilterTableCollection.Add*
  parent: System.ServiceModel.Routing.Configuration.FilterTableCollection
  isExternal: false
  name: Add
  nameWithType: FilterTableCollection.Add
- uid: System.ServiceModel.Routing.Configuration.FilterTableCollection.Clear*
  parent: System.ServiceModel.Routing.Configuration.FilterTableCollection
  isExternal: false
  name: Clear
  nameWithType: FilterTableCollection.Clear
- uid: System.ServiceModel.Routing.Configuration.FilterTableCollection.CreateNewElement*
  parent: System.ServiceModel.Routing.Configuration.FilterTableCollection
  isExternal: false
  name: CreateNewElement
  nameWithType: FilterTableCollection.CreateNewElement
- uid: System.ServiceModel.Routing.Configuration.FilterTableCollection.GetElementKey*
  parent: System.ServiceModel.Routing.Configuration.FilterTableCollection
  isExternal: false
  name: GetElementKey
  nameWithType: FilterTableCollection.GetElementKey
- uid: System.ServiceModel.Routing.Configuration.FilterTableCollection.Item*
  parent: System.ServiceModel.Routing.Configuration.FilterTableCollection
  isExternal: false
  name: Item
  nameWithType: FilterTableCollection.Item
- uid: System.ServiceModel.Routing.Configuration.FilterTableCollection.Remove*
  parent: System.ServiceModel.Routing.Configuration.FilterTableCollection
  isExternal: false
  name: Remove
  nameWithType: FilterTableCollection.Remove
