### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.XmlElementElement
  id: XmlElementElement
  children:
  - System.ServiceModel.Configuration.XmlElementElement.#ctor
  - System.ServiceModel.Configuration.XmlElementElement.#ctor(System.Xml.XmlElement)
  - System.ServiceModel.Configuration.XmlElementElement.Copy(System.ServiceModel.Configuration.XmlElementElement)
  - System.ServiceModel.Configuration.XmlElementElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.ServiceModel.Configuration.XmlElementElement.PostDeserialize
  - System.ServiceModel.Configuration.XmlElementElement.Properties
  - System.ServiceModel.Configuration.XmlElementElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.ServiceModel.Configuration.XmlElementElement.XmlElement
  langs:
  - csharp
  name: XmlElementElement
  nameWithType: XmlElementElement
  fullName: System.ServiceModel.Configuration.XmlElementElement
  type: Class
  summary: "Represents the configuration settings for an XML element. This class cannot be inherited."
  syntax:
    content: 'public sealed class XmlElementElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.XmlElementElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.XmlElementElement
  langs:
  - csharp
  name: XmlElementElement()
  nameWithType: XmlElementElement.XmlElementElement()
  fullName: System.ServiceModel.Configuration.XmlElementElement.XmlElementElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.XmlElementElement&quot;></see> class."
  syntax:
    content: public XmlElementElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.XmlElementElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.XmlElementElement.#ctor(System.Xml.XmlElement)
  id: '#ctor(System.Xml.XmlElement)'
  parent: System.ServiceModel.Configuration.XmlElementElement
  langs:
  - csharp
  name: XmlElementElement(XmlElement)
  nameWithType: XmlElementElement.XmlElementElement(XmlElement)
  fullName: System.ServiceModel.Configuration.XmlElementElement.XmlElementElement(XmlElement)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.XmlElementElement&quot;></see> class with the specified XML element."
  syntax:
    content: public XmlElementElement (System.Xml.XmlElement element);
    parameters:
    - id: element
      type: System.Xml.XmlElement
      description: "The  from which this instance is initialized."
  overload: System.ServiceModel.Configuration.XmlElementElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.XmlElementElement.Copy(System.ServiceModel.Configuration.XmlElementElement)
  id: Copy(System.ServiceModel.Configuration.XmlElementElement)
  parent: System.ServiceModel.Configuration.XmlElementElement
  langs:
  - csharp
  name: Copy(XmlElementElement)
  nameWithType: XmlElementElement.Copy(XmlElementElement)
  fullName: System.ServiceModel.Configuration.XmlElementElement.Copy(XmlElementElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Copies the content of the specified <see cref=&quot;T:System.Xml.XmlElement&quot;></see> to this instance."
  syntax:
    content: public void Copy (System.ServiceModel.Configuration.XmlElementElement source);
    parameters:
    - id: source
      type: System.ServiceModel.Configuration.XmlElementElement
      description: "The  to copy from."
  overload: System.ServiceModel.Configuration.XmlElementElement.Copy*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "\n    source is ."
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "The configuration file is read-only."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.XmlElementElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  id: DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.ServiceModel.Configuration.XmlElementElement
  langs:
  - csharp
  name: DeserializeElement(XmlReader,Boolean)
  nameWithType: XmlElementElement.DeserializeElement(XmlReader,Boolean)
  fullName: System.ServiceModel.Configuration.XmlElementElement.DeserializeElement(XmlReader,Boolean)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override void DeserializeElement (System.Xml.XmlReader reader, bool serializeCollectionKey);
    parameters:
    - id: reader
      type: System.Xml.XmlReader
      description: "To be added."
    - id: serializeCollectionKey
      type: System.Boolean
      description: "To be added."
  overload: System.ServiceModel.Configuration.XmlElementElement.DeserializeElement*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.XmlElementElement.PostDeserialize
  id: PostDeserialize
  parent: System.ServiceModel.Configuration.XmlElementElement
  langs:
  - csharp
  name: PostDeserialize()
  nameWithType: XmlElementElement.PostDeserialize()
  fullName: System.ServiceModel.Configuration.XmlElementElement.PostDeserialize()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override void PostDeserialize ();
    parameters: []
  overload: System.ServiceModel.Configuration.XmlElementElement.PostDeserialize*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.XmlElementElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.XmlElementElement
  langs:
  - csharp
  name: Properties
  nameWithType: XmlElementElement.Properties
  fullName: System.ServiceModel.Configuration.XmlElementElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.XmlElementElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.XmlElementElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  id: SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  parent: System.ServiceModel.Configuration.XmlElementElement
  langs:
  - csharp
  name: SerializeToXmlElement(XmlWriter,String)
  nameWithType: XmlElementElement.SerializeToXmlElement(XmlWriter,String)
  fullName: System.ServiceModel.Configuration.XmlElementElement.SerializeToXmlElement(XmlWriter,String)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override bool SerializeToXmlElement (System.Xml.XmlWriter writer, string elementName);
    parameters:
    - id: writer
      type: System.Xml.XmlWriter
      description: "To be added."
    - id: elementName
      type: System.String
      description: "To be added."
    return:
      type: System.Boolean
      description: "To be added."
  overload: System.ServiceModel.Configuration.XmlElementElement.SerializeToXmlElement*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.XmlElementElement.XmlElement
  id: XmlElement
  parent: System.ServiceModel.Configuration.XmlElementElement
  langs:
  - csharp
  name: XmlElement
  nameWithType: XmlElementElement.XmlElement
  fullName: System.ServiceModel.Configuration.XmlElementElement.XmlElement
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets the <see cref=&quot;T:System.Xml.XmlElement&quot;></see> that this class encapsulates."
  syntax:
    content: public System.Xml.XmlElement XmlElement { get; set; }
    return:
      type: System.Xml.XmlElement
      description: "The <see cref=&quot;T:System.Xml.XmlElement&quot;></see> that this class encapsulates."
  overload: System.ServiceModel.Configuration.XmlElementElement.XmlElement*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.XmlElementElement.#ctor
  parent: System.ServiceModel.Configuration.XmlElementElement
  isExternal: false
  name: XmlElementElement()
  nameWithType: XmlElementElement.XmlElementElement()
  fullName: System.ServiceModel.Configuration.XmlElementElement.XmlElementElement()
- uid: System.ServiceModel.Configuration.XmlElementElement.#ctor(System.Xml.XmlElement)
  parent: System.ServiceModel.Configuration.XmlElementElement
  isExternal: false
  name: XmlElementElement(XmlElement)
  nameWithType: XmlElementElement.XmlElementElement(XmlElement)
  fullName: System.ServiceModel.Configuration.XmlElementElement.XmlElementElement(XmlElement)
- uid: System.Xml.XmlElement
  parent: System.Xml
  isExternal: false
  name: XmlElement
  nameWithType: XmlElement
  fullName: System.Xml.XmlElement
- uid: System.ServiceModel.Configuration.XmlElementElement.Copy(System.ServiceModel.Configuration.XmlElementElement)
  parent: System.ServiceModel.Configuration.XmlElementElement
  isExternal: false
  name: Copy(XmlElementElement)
  nameWithType: XmlElementElement.Copy(XmlElementElement)
  fullName: System.ServiceModel.Configuration.XmlElementElement.Copy(XmlElementElement)
- uid: System.ServiceModel.Configuration.XmlElementElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: XmlElementElement
  nameWithType: XmlElementElement
  fullName: System.ServiceModel.Configuration.XmlElementElement
- uid: System.ServiceModel.Configuration.XmlElementElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.ServiceModel.Configuration.XmlElementElement
  isExternal: false
  name: DeserializeElement(XmlReader,Boolean)
  nameWithType: XmlElementElement.DeserializeElement(XmlReader,Boolean)
  fullName: System.ServiceModel.Configuration.XmlElementElement.DeserializeElement(XmlReader,Boolean)
- uid: System.Xml.XmlReader
  parent: System.Xml
  isExternal: true
  name: XmlReader
  nameWithType: XmlReader
  fullName: System.Xml.XmlReader
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.XmlElementElement.PostDeserialize
  parent: System.ServiceModel.Configuration.XmlElementElement
  isExternal: false
  name: PostDeserialize()
  nameWithType: XmlElementElement.PostDeserialize()
  fullName: System.ServiceModel.Configuration.XmlElementElement.PostDeserialize()
- uid: System.ServiceModel.Configuration.XmlElementElement.Properties
  parent: System.ServiceModel.Configuration.XmlElementElement
  isExternal: false
  name: Properties
  nameWithType: XmlElementElement.Properties
  fullName: System.ServiceModel.Configuration.XmlElementElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.XmlElementElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  parent: System.ServiceModel.Configuration.XmlElementElement
  isExternal: false
  name: SerializeToXmlElement(XmlWriter,String)
  nameWithType: XmlElementElement.SerializeToXmlElement(XmlWriter,String)
  fullName: System.ServiceModel.Configuration.XmlElementElement.SerializeToXmlElement(XmlWriter,String)
- uid: System.Xml.XmlWriter
  parent: System.Xml
  isExternal: true
  name: XmlWriter
  nameWithType: XmlWriter
  fullName: System.Xml.XmlWriter
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.XmlElementElement.XmlElement
  parent: System.ServiceModel.Configuration.XmlElementElement
  isExternal: false
  name: XmlElement
  nameWithType: XmlElementElement.XmlElement
  fullName: System.ServiceModel.Configuration.XmlElementElement.XmlElement
- uid: System.ServiceModel.Configuration.XmlElementElement.#ctor*
  parent: System.ServiceModel.Configuration.XmlElementElement
  isExternal: false
  name: XmlElementElement
  nameWithType: XmlElementElement.XmlElementElement
- uid: System.ServiceModel.Configuration.XmlElementElement.Copy*
  parent: System.ServiceModel.Configuration.XmlElementElement
  isExternal: false
  name: Copy
  nameWithType: XmlElementElement.Copy
- uid: System.ServiceModel.Configuration.XmlElementElement.DeserializeElement*
  parent: System.ServiceModel.Configuration.XmlElementElement
  isExternal: false
  name: DeserializeElement
  nameWithType: XmlElementElement.DeserializeElement
- uid: System.ServiceModel.Configuration.XmlElementElement.PostDeserialize*
  parent: System.ServiceModel.Configuration.XmlElementElement
  isExternal: false
  name: PostDeserialize
  nameWithType: XmlElementElement.PostDeserialize
- uid: System.ServiceModel.Configuration.XmlElementElement.Properties*
  parent: System.ServiceModel.Configuration.XmlElementElement
  isExternal: false
  name: Properties
  nameWithType: XmlElementElement.Properties
- uid: System.ServiceModel.Configuration.XmlElementElement.SerializeToXmlElement*
  parent: System.ServiceModel.Configuration.XmlElementElement
  isExternal: false
  name: SerializeToXmlElement
  nameWithType: XmlElementElement.SerializeToXmlElement
- uid: System.ServiceModel.Configuration.XmlElementElement.XmlElement*
  parent: System.ServiceModel.Configuration.XmlElementElement
  isExternal: false
  name: XmlElement
  nameWithType: XmlElementElement.XmlElement
