### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.FullTrustAssembly
  id: FullTrustAssembly
  children:
  - System.Web.Configuration.FullTrustAssembly.#ctor(System.String,System.String,System.String)
  - System.Web.Configuration.FullTrustAssembly.AssemblyName
  - System.Web.Configuration.FullTrustAssembly.Properties
  - System.Web.Configuration.FullTrustAssembly.PublicKey
  - System.Web.Configuration.FullTrustAssembly.Version
  langs:
  - csharp
  name: FullTrustAssembly
  nameWithType: FullTrustAssembly
  fullName: System.Web.Configuration.FullTrustAssembly
  type: Class
  summary: "Configures a full trust assembly. This class cannot be inherited."
  syntax:
    content: 'public sealed class FullTrustAssembly : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.FullTrustAssembly.#ctor(System.String,System.String,System.String)
  id: '#ctor(System.String,System.String,System.String)'
  parent: System.Web.Configuration.FullTrustAssembly
  langs:
  - csharp
  name: FullTrustAssembly(String,String,String)
  nameWithType: FullTrustAssembly.FullTrustAssembly(String,String,String)
  fullName: System.Web.Configuration.FullTrustAssembly.FullTrustAssembly(String,String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Web.Configuration.FullTrustAssembly&quot;></see> class."
  syntax:
    content: public FullTrustAssembly (string assemblyName, string version, string publicKey);
    parameters:
    - id: assemblyName
      type: System.String
      description: "The assembly name."
    - id: version
      type: System.String
      description: "The assembly version number."
    - id: publicKey
      type: System.String
      description: "The hexadecimal string representation of the public key that is associated with the assembly."
  overload: System.Web.Configuration.FullTrustAssembly.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.FullTrustAssembly.AssemblyName
  id: AssemblyName
  parent: System.Web.Configuration.FullTrustAssembly
  langs:
  - csharp
  name: AssemblyName
  nameWithType: FullTrustAssembly.AssemblyName
  fullName: System.Web.Configuration.FullTrustAssembly.AssemblyName
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets or sets the assembly name."
  syntax:
    content: public string AssemblyName { get; set; }
    return:
      type: System.String
      description: "The assembly name."
  overload: System.Web.Configuration.FullTrustAssembly.AssemblyName*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.FullTrustAssembly.Properties
  id: Properties
  parent: System.Web.Configuration.FullTrustAssembly
  langs:
  - csharp
  name: Properties
  nameWithType: FullTrustAssembly.Properties
  fullName: System.Web.Configuration.FullTrustAssembly.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Web.Configuration.FullTrustAssembly.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.FullTrustAssembly.PublicKey
  id: PublicKey
  parent: System.Web.Configuration.FullTrustAssembly
  langs:
  - csharp
  name: PublicKey
  nameWithType: FullTrustAssembly.PublicKey
  fullName: System.Web.Configuration.FullTrustAssembly.PublicKey
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets or sets the assembly public key."
  syntax:
    content: public string PublicKey { get; set; }
    return:
      type: System.String
      description: "The hexadecimal representation of the public key that is associated with the assembly."
  overload: System.Web.Configuration.FullTrustAssembly.PublicKey*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.FullTrustAssembly.Version
  id: Version
  parent: System.Web.Configuration.FullTrustAssembly
  langs:
  - csharp
  name: Version
  nameWithType: FullTrustAssembly.Version
  fullName: System.Web.Configuration.FullTrustAssembly.Version
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets or sets the assembly version number."
  syntax:
    content: public string Version { get; set; }
    return:
      type: System.String
      description: "The assembly version number."
  overload: System.Web.Configuration.FullTrustAssembly.Version*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.FullTrustAssembly.#ctor(System.String,System.String,System.String)
  parent: System.Web.Configuration.FullTrustAssembly
  isExternal: false
  name: FullTrustAssembly(String,String,String)
  nameWithType: FullTrustAssembly.FullTrustAssembly(String,String,String)
  fullName: System.Web.Configuration.FullTrustAssembly.FullTrustAssembly(String,String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.FullTrustAssembly.AssemblyName
  parent: System.Web.Configuration.FullTrustAssembly
  isExternal: false
  name: AssemblyName
  nameWithType: FullTrustAssembly.AssemblyName
  fullName: System.Web.Configuration.FullTrustAssembly.AssemblyName
- uid: System.Web.Configuration.FullTrustAssembly.Properties
  parent: System.Web.Configuration.FullTrustAssembly
  isExternal: false
  name: Properties
  nameWithType: FullTrustAssembly.Properties
  fullName: System.Web.Configuration.FullTrustAssembly.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.FullTrustAssembly.PublicKey
  parent: System.Web.Configuration.FullTrustAssembly
  isExternal: false
  name: PublicKey
  nameWithType: FullTrustAssembly.PublicKey
  fullName: System.Web.Configuration.FullTrustAssembly.PublicKey
- uid: System.Web.Configuration.FullTrustAssembly.Version
  parent: System.Web.Configuration.FullTrustAssembly
  isExternal: false
  name: Version
  nameWithType: FullTrustAssembly.Version
  fullName: System.Web.Configuration.FullTrustAssembly.Version
- uid: System.Web.Configuration.FullTrustAssembly.#ctor*
  parent: System.Web.Configuration.FullTrustAssembly
  isExternal: false
  name: FullTrustAssembly
  nameWithType: FullTrustAssembly.FullTrustAssembly
- uid: System.Web.Configuration.FullTrustAssembly.AssemblyName*
  parent: System.Web.Configuration.FullTrustAssembly
  isExternal: false
  name: AssemblyName
  nameWithType: FullTrustAssembly.AssemblyName
- uid: System.Web.Configuration.FullTrustAssembly.Properties*
  parent: System.Web.Configuration.FullTrustAssembly
  isExternal: false
  name: Properties
  nameWithType: FullTrustAssembly.Properties
- uid: System.Web.Configuration.FullTrustAssembly.PublicKey*
  parent: System.Web.Configuration.FullTrustAssembly
  isExternal: false
  name: PublicKey
  nameWithType: FullTrustAssembly.PublicKey
- uid: System.Web.Configuration.FullTrustAssembly.Version*
  parent: System.Web.Configuration.FullTrustAssembly
  isExternal: false
  name: Version
  nameWithType: FullTrustAssembly.Version
