### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ServiceActivationElementCollection
  id: ServiceActivationElementCollection
  children:
  - System.ServiceModel.Configuration.ServiceActivationElementCollection.#ctor
  - System.ServiceModel.Configuration.ServiceActivationElementCollection.CreateNewElement
  - System.ServiceModel.Configuration.ServiceActivationElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceActivationElementCollection.ThrowOnDuplicate
  langs:
  - csharp
  name: ServiceActivationElementCollection
  nameWithType: ServiceActivationElementCollection
  fullName: System.ServiceModel.Configuration.ServiceActivationElementCollection
  type: Class
  summary: "Handles a collection of configuration elements that activate a service and can be merged across a hierarchy of configuration files."
  syntax:
    content: >-
      [System.Configuration.ConfigurationCollection(typeof(System.ServiceModel.Configuration.ServiceActivationElement))]

      public sealed class ServiceActivationElementCollection : System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection<System.ServiceModel.Configuration.ServiceActivationElement>
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationElementCollection
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.AddElementName
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Configuration.ConfigurationElement,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Int32,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseClear
  - System.Configuration.ConfigurationElementCollection.BaseGet(System.Int32)
  - System.Configuration.ConfigurationElementCollection.BaseGet(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseGetAllKeys
  - System.Configuration.ConfigurationElementCollection.BaseGetKey(System.Int32)
  - System.Configuration.ConfigurationElementCollection.BaseIndexOf(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseIsRemoved(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseRemove(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseRemoveAt(System.Int32)
  - System.Configuration.ConfigurationElementCollection.ClearElementName
  - System.Configuration.ConfigurationElementCollection.CopyTo(System.Configuration.ConfigurationElement[],System.Int32)
  - System.Configuration.ConfigurationElementCollection.Count
  - System.Configuration.ConfigurationElementCollection.CreateNewElement(System.String)
  - System.Configuration.ConfigurationElementCollection.EmitClear
  - System.Configuration.ConfigurationElementCollection.Equals(System.Object)
  - System.Configuration.ConfigurationElementCollection.GetEnumerator
  - System.Configuration.ConfigurationElementCollection.GetHashCode
  - System.Configuration.ConfigurationElementCollection.IsElementName(System.String)
  - System.Configuration.ConfigurationElementCollection.IsElementRemovable(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.IsModified
  - System.Configuration.ConfigurationElementCollection.IsReadOnly
  - System.Configuration.ConfigurationElementCollection.IsSynchronized
  - System.Configuration.ConfigurationElementCollection.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElementCollection.RemoveElementName
  - System.Configuration.ConfigurationElementCollection.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.ResetModified
  - System.Configuration.ConfigurationElementCollection.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.SetReadOnly
  - System.Configuration.ConfigurationElementCollection.SyncRoot
  - System.Configuration.ConfigurationElementCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  - System.Configuration.ConfigurationElementCollection.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Add(`0)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.BaseAdd(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Clear
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.CollectionType
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.ContainsKey(System.Object)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.CopyTo(`0[],System.Int32)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.ElementName
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.IndexOf(`0)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Item(System.Int32)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Item(System.Object)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.Remove(`0)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.RemoveAt(System.Int32)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1.RemoveAt(System.Object)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ServiceActivationElementCollection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ServiceActivationElementCollection
  langs:
  - csharp
  name: ServiceActivationElementCollection()
  nameWithType: ServiceActivationElementCollection.ServiceActivationElementCollection()
  fullName: System.ServiceModel.Configuration.ServiceActivationElementCollection.ServiceActivationElementCollection()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Creates a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.ServiceActivationElementCollection&quot;></see> class."
  syntax:
    content: public ServiceActivationElementCollection ();
    parameters: []
  overload: System.ServiceModel.Configuration.ServiceActivationElementCollection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ServiceActivationElementCollection.CreateNewElement
  id: CreateNewElement
  parent: System.ServiceModel.Configuration.ServiceActivationElementCollection
  langs:
  - csharp
  name: CreateNewElement()
  nameWithType: ServiceActivationElementCollection.CreateNewElement()
  fullName: System.ServiceModel.Configuration.ServiceActivationElementCollection.CreateNewElement()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationElement CreateNewElement ();
    parameters: []
    return:
      type: System.Configuration.ConfigurationElement
      description: "To be added."
  overload: System.ServiceModel.Configuration.ServiceActivationElementCollection.CreateNewElement*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ServiceActivationElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  id: GetElementKey(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Configuration.ServiceActivationElementCollection
  langs:
  - csharp
  name: GetElementKey(ConfigurationElement)
  nameWithType: ServiceActivationElementCollection.GetElementKey(ConfigurationElement)
  fullName: System.ServiceModel.Configuration.ServiceActivationElementCollection.GetElementKey(ConfigurationElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override object GetElementKey (System.Configuration.ConfigurationElement element);
    parameters:
    - id: element
      type: System.Configuration.ConfigurationElement
      description: "To be added."
    return:
      type: System.Object
      description: "To be added."
  overload: System.ServiceModel.Configuration.ServiceActivationElementCollection.GetElementKey*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ServiceActivationElementCollection.ThrowOnDuplicate
  id: ThrowOnDuplicate
  parent: System.ServiceModel.Configuration.ServiceActivationElementCollection
  langs:
  - csharp
  name: ThrowOnDuplicate
  nameWithType: ServiceActivationElementCollection.ThrowOnDuplicate
  fullName: System.ServiceModel.Configuration.ServiceActivationElementCollection.ThrowOnDuplicate
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override bool ThrowOnDuplicate { get; }
    return:
      type: System.Boolean
      description: "To be added."
  overload: System.ServiceModel.Configuration.ServiceActivationElementCollection.ThrowOnDuplicate*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection`1
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElementCollection<System.ServiceModel.Configuration.ServiceActivationElement>
- uid: System.ServiceModel.Configuration.ServiceActivationElementCollection.#ctor
  parent: System.ServiceModel.Configuration.ServiceActivationElementCollection
  isExternal: false
  name: ServiceActivationElementCollection()
  nameWithType: ServiceActivationElementCollection.ServiceActivationElementCollection()
  fullName: System.ServiceModel.Configuration.ServiceActivationElementCollection.ServiceActivationElementCollection()
- uid: System.ServiceModel.Configuration.ServiceActivationElementCollection.CreateNewElement
  parent: System.ServiceModel.Configuration.ServiceActivationElementCollection
  isExternal: false
  name: CreateNewElement()
  nameWithType: ServiceActivationElementCollection.CreateNewElement()
  fullName: System.ServiceModel.Configuration.ServiceActivationElementCollection.CreateNewElement()
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.ServiceActivationElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Configuration.ServiceActivationElementCollection
  isExternal: false
  name: GetElementKey(ConfigurationElement)
  nameWithType: ServiceActivationElementCollection.GetElementKey(ConfigurationElement)
  fullName: System.ServiceModel.Configuration.ServiceActivationElementCollection.GetElementKey(ConfigurationElement)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Configuration.ServiceActivationElementCollection.ThrowOnDuplicate
  parent: System.ServiceModel.Configuration.ServiceActivationElementCollection
  isExternal: false
  name: ThrowOnDuplicate
  nameWithType: ServiceActivationElementCollection.ThrowOnDuplicate
  fullName: System.ServiceModel.Configuration.ServiceActivationElementCollection.ThrowOnDuplicate
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.ServiceActivationElementCollection.#ctor*
  parent: System.ServiceModel.Configuration.ServiceActivationElementCollection
  isExternal: false
  name: ServiceActivationElementCollection
  nameWithType: ServiceActivationElementCollection.ServiceActivationElementCollection
- uid: System.ServiceModel.Configuration.ServiceActivationElementCollection.CreateNewElement*
  parent: System.ServiceModel.Configuration.ServiceActivationElementCollection
  isExternal: false
  name: CreateNewElement
  nameWithType: ServiceActivationElementCollection.CreateNewElement
- uid: System.ServiceModel.Configuration.ServiceActivationElementCollection.GetElementKey*
  parent: System.ServiceModel.Configuration.ServiceActivationElementCollection
  isExternal: false
  name: GetElementKey
  nameWithType: ServiceActivationElementCollection.GetElementKey
- uid: System.ServiceModel.Configuration.ServiceActivationElementCollection.ThrowOnDuplicate*
  parent: System.ServiceModel.Configuration.ServiceActivationElementCollection
  isExternal: false
  name: ThrowOnDuplicate
  nameWithType: ServiceActivationElementCollection.ThrowOnDuplicate
