### YamlMime:ManagedReference
items:
- uid: System.Data.Services.Configuration.DataServicesSectionGroup
  id: DataServicesSectionGroup
  children:
  - System.Data.Services.Configuration.DataServicesSectionGroup.#ctor
  - System.Data.Services.Configuration.DataServicesSectionGroup.Features
  langs:
  - csharp
  name: DataServicesSectionGroup
  nameWithType: DataServicesSectionGroup
  fullName: System.Data.Services.Configuration.DataServicesSectionGroup
  type: Class
  summary: "Represents the DataServicesSectionGroup configuration section group."
  syntax:
    content: 'public sealed class DataServicesSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Services.Configuration.DataServicesSectionGroup.#ctor
  id: '#ctor'
  parent: System.Data.Services.Configuration.DataServicesSectionGroup
  langs:
  - csharp
  name: DataServicesSectionGroup()
  nameWithType: DataServicesSectionGroup.DataServicesSectionGroup()
  fullName: System.Data.Services.Configuration.DataServicesSectionGroup.DataServicesSectionGroup()
  type: Constructor
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Data.Services.Configuration.DataServicesSectionGroup&quot;></see> class."
  syntax:
    content: public DataServicesSectionGroup ();
    parameters: []
  overload: System.Data.Services.Configuration.DataServicesSectionGroup.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Data.Services.Configuration.DataServicesSectionGroup.Features
  id: Features
  parent: System.Data.Services.Configuration.DataServicesSectionGroup
  langs:
  - csharp
  name: Features
  nameWithType: DataServicesSectionGroup.Features
  fullName: System.Data.Services.Configuration.DataServicesSectionGroup.Features
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services.Configuration
  summary: "Gets the DataServicesFeaturesSection instance associated with the DataServicesSectionGroup."
  syntax:
    content: public System.Data.Services.Configuration.DataServicesFeaturesSection Features { get; }
    return:
      type: System.Data.Services.Configuration.DataServicesFeaturesSection
      description: "A DataServicesFeaturesSection instance."
  overload: System.Data.Services.Configuration.DataServicesSectionGroup.Features*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: System.Configuration.ConfigurationSectionGroup
- uid: System.Data.Services.Configuration.DataServicesSectionGroup.#ctor
  parent: System.Data.Services.Configuration.DataServicesSectionGroup
  isExternal: false
  name: DataServicesSectionGroup()
  nameWithType: DataServicesSectionGroup.DataServicesSectionGroup()
  fullName: System.Data.Services.Configuration.DataServicesSectionGroup.DataServicesSectionGroup()
- uid: System.Data.Services.Configuration.DataServicesSectionGroup.Features
  parent: System.Data.Services.Configuration.DataServicesSectionGroup
  isExternal: false
  name: Features
  nameWithType: DataServicesSectionGroup.Features
  fullName: System.Data.Services.Configuration.DataServicesSectionGroup.Features
- uid: System.Data.Services.Configuration.DataServicesFeaturesSection
  parent: System.Data.Services.Configuration
  isExternal: false
  name: DataServicesFeaturesSection
  nameWithType: DataServicesFeaturesSection
  fullName: System.Data.Services.Configuration.DataServicesFeaturesSection
- uid: System.Data.Services.Configuration.DataServicesSectionGroup.#ctor*
  parent: System.Data.Services.Configuration.DataServicesSectionGroup
  isExternal: false
  name: DataServicesSectionGroup
  nameWithType: DataServicesSectionGroup.DataServicesSectionGroup
- uid: System.Data.Services.Configuration.DataServicesSectionGroup.Features*
  parent: System.Data.Services.Configuration.DataServicesSectionGroup
  isExternal: false
  name: Features
  nameWithType: DataServicesSectionGroup.Features
