### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.EndpointCollectionElement
  id: EndpointCollectionElement
  children:
  - System.ServiceModel.Configuration.EndpointCollectionElement.#ctor
  - System.ServiceModel.Configuration.EndpointCollectionElement.ConfiguredEndpoints
  - System.ServiceModel.Configuration.EndpointCollectionElement.ContainsKey(System.String)
  - System.ServiceModel.Configuration.EndpointCollectionElement.EndpointName
  - System.ServiceModel.Configuration.EndpointCollectionElement.EndpointType
  - System.ServiceModel.Configuration.EndpointCollectionElement.GetDefaultStandardEndpointElement
  - System.ServiceModel.Configuration.EndpointCollectionElement.TryAdd(System.String,System.ServiceModel.Description.ServiceEndpoint,System.Configuration.Configuration)
  langs:
  - csharp
  name: EndpointCollectionElement
  nameWithType: EndpointCollectionElement
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement
  type: Class
  summary: "Manages a collection of service endpoints in a configuration file."
  syntax:
    content: 'public abstract class EndpointCollectionElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  langs:
  - csharp
  name: EndpointCollectionElement()
  nameWithType: EndpointCollectionElement.EndpointCollectionElement()
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement.EndpointCollectionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Creates a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.EndpointCollectionElement&quot;></see> class."
  syntax:
    content: protected EndpointCollectionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.EndpointCollectionElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.ConfiguredEndpoints
  id: ConfiguredEndpoints
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  langs:
  - csharp
  name: ConfiguredEndpoints
  nameWithType: EndpointCollectionElement.ConfiguredEndpoints
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement.ConfiguredEndpoints
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "When implemented in a derived class, provides a read-only collection of <see cref=&quot;T:System.ServiceModel.Configuration.StandardEndpointElement&quot;></see> methods and properties."
  syntax:
    content: public abstract System.Collections.ObjectModel.ReadOnlyCollection<System.ServiceModel.Configuration.StandardEndpointElement> ConfiguredEndpoints { get; }
    return:
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.ServiceModel.Configuration.StandardEndpointElement}
      description: "A read-only collection of <see cref=&quot;T:System.ServiceModel.Configuration.StandardEndpointElement&quot;></see> methods and properties."
  overload: System.ServiceModel.Configuration.EndpointCollectionElement.ConfiguredEndpoints*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.ContainsKey(System.String)
  id: ContainsKey(System.String)
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  langs:
  - csharp
  name: ContainsKey(String)
  nameWithType: EndpointCollectionElement.ContainsKey(String)
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement.ContainsKey(String)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Determines whether the service element in a configuration file contains an endpoint element with the same name as the specified string."
  syntax:
    content: public abstract bool ContainsKey (string name);
    parameters:
    - id: name
      type: System.String
      description: "The name of the key in a key/value pair that represents an endpoint element name and value."
    return:
      type: System.Boolean
      description: "To be added."
  overload: System.ServiceModel.Configuration.EndpointCollectionElement.ContainsKey*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.EndpointName
  id: EndpointName
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  langs:
  - csharp
  name: EndpointName
  nameWithType: EndpointCollectionElement.EndpointName
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement.EndpointName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "When implemented in a derived class, gets the value of the name attribute of a service endpoint element."
  syntax:
    content: public string EndpointName { get; }
    return:
      type: System.String
      description: "The value of the name attribute in a service endpoint element."
  overload: System.ServiceModel.Configuration.EndpointCollectionElement.EndpointName*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.EndpointType
  id: EndpointType
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  langs:
  - csharp
  name: EndpointType
  nameWithType: EndpointCollectionElement.EndpointType
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement.EndpointType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "When implemented in a derived class, gets the type of the service endpoint."
  syntax:
    content: public abstract Type EndpointType { get; }
    return:
      type: System.Type
      description: "A service endpoint type."
  overload: System.ServiceModel.Configuration.EndpointCollectionElement.EndpointType*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.GetDefaultStandardEndpointElement
  id: GetDefaultStandardEndpointElement
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  langs:
  - csharp
  name: GetDefaultStandardEndpointElement()
  nameWithType: EndpointCollectionElement.GetDefaultStandardEndpointElement()
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement.GetDefaultStandardEndpointElement()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "When implemented in a derived class, returns the default <see cref=&quot;T:System.ServiceModel.Configuration.StandardEndpointElement&quot;></see>."
  syntax:
    content: protected abstract System.ServiceModel.Configuration.StandardEndpointElement GetDefaultStandardEndpointElement ();
    parameters: []
    return:
      type: System.ServiceModel.Configuration.StandardEndpointElement
      description: "To be added."
  overload: System.ServiceModel.Configuration.EndpointCollectionElement.GetDefaultStandardEndpointElement*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.TryAdd(System.String,System.ServiceModel.Description.ServiceEndpoint,System.Configuration.Configuration)
  id: TryAdd(System.String,System.ServiceModel.Description.ServiceEndpoint,System.Configuration.Configuration)
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  langs:
  - csharp
  name: TryAdd(String,ServiceEndpoint,Configuration)
  nameWithType: EndpointCollectionElement.TryAdd(String,ServiceEndpoint,Configuration)
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement.TryAdd(String,ServiceEndpoint,Configuration)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "When implemented in a derived class, adds the specified endpoint to the collection of service endpoints in a configuration file."
  syntax:
    content: protected abstract bool TryAdd (string name, System.ServiceModel.Description.ServiceEndpoint endpoint, System.Configuration.Configuration config);
    parameters:
    - id: name
      type: System.String
      description: "The name of the service endpoint that contains the endpoint collection."
    - id: endpoint
      type: System.ServiceModel.Description.ServiceEndpoint
      description: "The service endpoint element to be added to the collection."
    - id: config
      type: System.Configuration.Configuration
      description: "The configuration file that receives the service endpoint."
    return:
      type: System.Boolean
      description: "To be added."
  overload: System.ServiceModel.Configuration.EndpointCollectionElement.TryAdd*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.#ctor
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  isExternal: false
  name: EndpointCollectionElement()
  nameWithType: EndpointCollectionElement.EndpointCollectionElement()
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement.EndpointCollectionElement()
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.ConfiguredEndpoints
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  isExternal: false
  name: ConfiguredEndpoints
  nameWithType: EndpointCollectionElement.ConfiguredEndpoints
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement.ConfiguredEndpoints
- uid: System.Collections.ObjectModel.ReadOnlyCollection{System.ServiceModel.Configuration.StandardEndpointElement}
  parent: System.Collections.ObjectModel
  isExternal: true
  name: ReadOnlyCollection<StandardEndpointElement>
  nameWithType: ReadOnlyCollection<StandardEndpointElement>
  fullName: System.Collections.ObjectModel.ReadOnlyCollection<System.ServiceModel.Configuration.StandardEndpointElement>
  spec.csharp:
  - uid: System.Collections.ObjectModel.ReadOnlyCollection`1
    name: ReadOnlyCollection
    nameWithType: ReadOnlyCollection
    fullName: ReadOnlyCollection<System.ServiceModel.Configuration.StandardEndpointElement>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.ServiceModel.Configuration.StandardEndpointElement
    name: StandardEndpointElement
    nameWithType: StandardEndpointElement
    fullName: StandardEndpointElement
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.ContainsKey(System.String)
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  isExternal: false
  name: ContainsKey(String)
  nameWithType: EndpointCollectionElement.ContainsKey(String)
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement.ContainsKey(String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.EndpointName
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  isExternal: false
  name: EndpointName
  nameWithType: EndpointCollectionElement.EndpointName
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement.EndpointName
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.EndpointType
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  isExternal: false
  name: EndpointType
  nameWithType: EndpointCollectionElement.EndpointType
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement.EndpointType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.GetDefaultStandardEndpointElement
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  isExternal: false
  name: GetDefaultStandardEndpointElement()
  nameWithType: EndpointCollectionElement.GetDefaultStandardEndpointElement()
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement.GetDefaultStandardEndpointElement()
- uid: System.ServiceModel.Configuration.StandardEndpointElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: StandardEndpointElement
  nameWithType: StandardEndpointElement
  fullName: System.ServiceModel.Configuration.StandardEndpointElement
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.TryAdd(System.String,System.ServiceModel.Description.ServiceEndpoint,System.Configuration.Configuration)
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  isExternal: false
  name: TryAdd(String,ServiceEndpoint,Configuration)
  nameWithType: EndpointCollectionElement.TryAdd(String,ServiceEndpoint,Configuration)
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement.TryAdd(String,ServiceEndpoint,Configuration)
- uid: System.ServiceModel.Description.ServiceEndpoint
  parent: System.ServiceModel.Description
  isExternal: true
  name: ServiceEndpoint
  nameWithType: ServiceEndpoint
  fullName: System.ServiceModel.Description.ServiceEndpoint
- uid: System.Configuration.Configuration
  parent: System.Configuration
  isExternal: false
  name: Configuration
  nameWithType: Configuration
  fullName: System.Configuration.Configuration
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.#ctor*
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  isExternal: false
  name: EndpointCollectionElement
  nameWithType: EndpointCollectionElement.EndpointCollectionElement
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.ConfiguredEndpoints*
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  isExternal: false
  name: ConfiguredEndpoints
  nameWithType: EndpointCollectionElement.ConfiguredEndpoints
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.ContainsKey*
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  isExternal: false
  name: ContainsKey
  nameWithType: EndpointCollectionElement.ContainsKey
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.EndpointName*
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  isExternal: false
  name: EndpointName
  nameWithType: EndpointCollectionElement.EndpointName
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.EndpointType*
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  isExternal: false
  name: EndpointType
  nameWithType: EndpointCollectionElement.EndpointType
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.GetDefaultStandardEndpointElement*
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  isExternal: false
  name: GetDefaultStandardEndpointElement
  nameWithType: EndpointCollectionElement.GetDefaultStandardEndpointElement
- uid: System.ServiceModel.Configuration.EndpointCollectionElement.TryAdd*
  parent: System.ServiceModel.Configuration.EndpointCollectionElement
  isExternal: false
  name: TryAdd
  nameWithType: EndpointCollectionElement.TryAdd
