### YamlMime:ManagedReference
items:
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility
  id: AssemblyVersionCompatibility
  children:
  - System.Configuration.Assemblies.AssemblyVersionCompatibility.SameDomain
  - System.Configuration.Assemblies.AssemblyVersionCompatibility.SameMachine
  - System.Configuration.Assemblies.AssemblyVersionCompatibility.SameProcess
  langs:
  - csharp
  name: AssemblyVersionCompatibility
  nameWithType: AssemblyVersionCompatibility
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility
  type: Enum
  summary: "Defines the different types of assembly version compatibility. This feature is not available in version 1.0 of the .NET Framework."
  remarks: "`AssemblyVersionCompatibility` defines the compatibility of an assembly with other versions of the same assembly, indicating if it cannot execute side-by-side with other versions (for example, due to conflicts over a device driver).       If no compatibility is specified, an assembly is side-by-side compatible in all scopes.       An assembly cannot be more specific with regard to exactly which previous versions it is not side-by-side compatible with. Therefore, if the `AssemblyVersionCompatibility` is specified, it means the assembly is non side-by-side with all know versions. If not specified, it means it is side-by-side with all known versions."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public enum AssemblyVersionCompatibility
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameDomain
  id: SameDomain
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  langs:
  - csharp
  name: SameDomain
  nameWithType: AssemblyVersionCompatibility.SameDomain
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameDomain
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "The assembly cannot execute with other versions if they are executing in the same application domain."
  syntax:
    content: SameDomain
    return:
      type: System.Configuration.Assemblies.AssemblyVersionCompatibility
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameMachine
  id: SameMachine
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  langs:
  - csharp
  name: SameMachine
  nameWithType: AssemblyVersionCompatibility.SameMachine
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameMachine
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "The assembly cannot execute with other versions if they are executing on the same machine."
  syntax:
    content: SameMachine
    return:
      type: System.Configuration.Assemblies.AssemblyVersionCompatibility
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameProcess
  id: SameProcess
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  langs:
  - csharp
  name: SameProcess
  nameWithType: AssemblyVersionCompatibility.SameProcess
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameProcess
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "The assembly cannot execute with other versions if they are executing in the same process."
  syntax:
    content: SameProcess
    return:
      type: System.Configuration.Assemblies.AssemblyVersionCompatibility
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameDomain
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  isExternal: false
  name: SameDomain
  nameWithType: AssemblyVersionCompatibility.SameDomain
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameDomain
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility
  parent: System.Configuration.Assemblies
  isExternal: false
  name: AssemblyVersionCompatibility
  nameWithType: AssemblyVersionCompatibility
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameMachine
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  isExternal: false
  name: SameMachine
  nameWithType: AssemblyVersionCompatibility.SameMachine
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameMachine
- uid: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameProcess
  parent: System.Configuration.Assemblies.AssemblyVersionCompatibility
  isExternal: false
  name: SameProcess
  nameWithType: AssemblyVersionCompatibility.SameProcess
  fullName: System.Configuration.Assemblies.AssemblyVersionCompatibility.SameProcess
