### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.TrustLevel
  id: TrustLevel
  children:
  - System.Web.Configuration.TrustLevel.#ctor(System.String,System.String)
  - System.Web.Configuration.TrustLevel.Name
  - System.Web.Configuration.TrustLevel.PolicyFile
  - System.Web.Configuration.TrustLevel.Properties
  langs:
  - csharp
  name: TrustLevel
  nameWithType: TrustLevel
  fullName: System.Web.Configuration.TrustLevel
  type: Class
  summary: "Defines the mapping of specific security levels to named policy files. This class cannot be inherited."
  remarks: "You can extend the security of your Web application by creating your own named TrustLevel object that is mapped to a file specified by the `policyFile` attribute."
  example:
  - "The following code example demonstrates how to use the TrustLevel type.  \n  \n [!code-cs[System.Web.Configuration.TrustLevel#1](~/add/codesnippet/CSharp/t-system.web.configurati_38_1.cs)]\n [!code-vb[System.Web.Configuration.TrustLevel#1](~/add/codesnippet/VisualBasic/t-system.web.configurati_38_1.vb)]"
  syntax:
    content: 'public sealed class TrustLevel : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.TrustLevel.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.TrustLevel
  langs:
  - csharp
  name: TrustLevel(String,String)
  nameWithType: TrustLevel.TrustLevel(String,String)
  fullName: System.Web.Configuration.TrustLevel.TrustLevel(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Creates an instance of the <see cref=&quot;T:System.Web.Configuration.TrustLevel&quot;></see> class that is initialized based on the provided values, which define the mapping of specific security levels to named policy files."
  remarks: "The TrustLevel constructor creates a <xref:System.Web.Configuration.TrustLevel> object by using the supplied parameters."
  example:
  - "The following code example demonstrates how to use the TrustLevel constructor. This code example is part of a larger example provided for the <xref:System.Web.Configuration.TrustLevel> class.  \n  \n [!code-cs[System.Web.Configuration.TrustLevel#4](~/add/codesnippet/CSharp/m-system.web.configurati_43_1.cs)]\n [!code-vb[System.Web.Configuration.TrustLevel#4](~/add/codesnippet/VisualBasic/m-system.web.configurati_43_1.vb)]"
  syntax:
    content: public TrustLevel (string name, string policyFile);
    parameters:
    - id: name
      type: System.String
      description: "A named security level that is mapped to a policy file."
    - id: policyFile
      type: System.String
      description: "The configuration file that contains security policy settings for the named security level."
  overload: System.Web.Configuration.TrustLevel.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.TrustLevel.Name
  id: Name
  parent: System.Web.Configuration.TrustLevel
  langs:
  - csharp
  name: Name
  nameWithType: TrustLevel.Name
  fullName: System.Web.Configuration.TrustLevel.Name
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets or sets a named security level that is mapped to a policy file."
  remarks: ''
  example:
  - "The following code example demonstrates how to use the Name property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.TrustLevel> class.  \n  \n [!code-cs[System.Web.Configuration.TrustLevel#3](~/add/codesnippet/CSharp/p-system.web.configurati_0_1.cs)]\n [!code-vb[System.Web.Configuration.TrustLevel#3](~/add/codesnippet/VisualBasic/p-system.web.configurati_0_1.vb)]"
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "The Name that is mapped to a policy file."
  overload: System.Web.Configuration.TrustLevel.Name*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.TrustLevel.PolicyFile
  id: PolicyFile
  parent: System.Web.Configuration.TrustLevel
  langs:
  - csharp
  name: PolicyFile
  nameWithType: TrustLevel.PolicyFile
  fullName: System.Web.Configuration.TrustLevel.PolicyFile
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets or sets the configuration file reference that contains the security policy settings for the named security level."
  remarks: ''
  example:
  - "The following code example demonstrates how to use the PolicyFile property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.TrustLevel> class.  \n  \n [!code-cs[System.Web.Configuration.TrustLevel#5](~/add/codesnippet/CSharp/p-system.web.configurati_352_1.cs)]\n [!code-vb[System.Web.Configuration.TrustLevel#5](~/add/codesnippet/VisualBasic/p-system.web.configurati_352_1.vb)]"
  syntax:
    content: public string PolicyFile { get; set; }
    return:
      type: System.String
      description: "The configuration file reference that contains the security policy settings for the associated security level."
  overload: System.Web.Configuration.TrustLevel.PolicyFile*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.TrustLevel.Properties
  id: Properties
  parent: System.Web.Configuration.TrustLevel
  langs:
  - csharp
  name: Properties
  nameWithType: TrustLevel.Properties
  fullName: System.Web.Configuration.TrustLevel.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Web.Configuration.TrustLevel.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.TrustLevel.#ctor(System.String,System.String)
  parent: System.Web.Configuration.TrustLevel
  isExternal: false
  name: TrustLevel(String,String)
  nameWithType: TrustLevel.TrustLevel(String,String)
  fullName: System.Web.Configuration.TrustLevel.TrustLevel(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.TrustLevel.Name
  parent: System.Web.Configuration.TrustLevel
  isExternal: false
  name: Name
  nameWithType: TrustLevel.Name
  fullName: System.Web.Configuration.TrustLevel.Name
- uid: System.Web.Configuration.TrustLevel.PolicyFile
  parent: System.Web.Configuration.TrustLevel
  isExternal: false
  name: PolicyFile
  nameWithType: TrustLevel.PolicyFile
  fullName: System.Web.Configuration.TrustLevel.PolicyFile
- uid: System.Web.Configuration.TrustLevel.Properties
  parent: System.Web.Configuration.TrustLevel
  isExternal: false
  name: Properties
  nameWithType: TrustLevel.Properties
  fullName: System.Web.Configuration.TrustLevel.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.TrustLevel.#ctor*
  parent: System.Web.Configuration.TrustLevel
  isExternal: false
  name: TrustLevel
  nameWithType: TrustLevel.TrustLevel
- uid: System.Web.Configuration.TrustLevel.Name*
  parent: System.Web.Configuration.TrustLevel
  isExternal: false
  name: Name
  nameWithType: TrustLevel.Name
- uid: System.Web.Configuration.TrustLevel.PolicyFile*
  parent: System.Web.Configuration.TrustLevel
  isExternal: false
  name: PolicyFile
  nameWithType: TrustLevel.PolicyFile
- uid: System.Web.Configuration.TrustLevel.Properties*
  parent: System.Web.Configuration.TrustLevel
  isExternal: false
  name: Properties
  nameWithType: TrustLevel.Properties
