### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  id: TcpConnectionPoolSettingsElement
  children:
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.#ctor
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties
  langs:
  - csharp
  name: TcpConnectionPoolSettingsElement
  nameWithType: TcpConnectionPoolSettingsElement
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  type: Class
  summary: "Represents a configuration element that specifies additional connection pool settings for a TCP transport. This class cannot be inherited."
  syntax:
    content: 'public sealed class TcpConnectionPoolSettingsElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: TcpConnectionPoolSettingsElement()
  nameWithType: TcpConnectionPoolSettingsElement.TcpConnectionPoolSettingsElement()
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.TcpConnectionPoolSettingsElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement&quot;></see> class."
  syntax:
    content: public TcpConnectionPoolSettingsElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName
  id: GroupName
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: GroupName
  nameWithType: TcpConnectionPoolSettingsElement.GroupName
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets a string that defines the name of the connection pool used for outgoing channels."
  remarks: "In streamed mode, connections are not shared, meaning that connection pooling is disabled. The default is a &quot;default&quot; string. You can modify this value to isolate the connections for a particular client into separate groups."
  syntax:
    content: public string GroupName { get; set; }
    return:
      type: System.String
      description: "The name of the connection pool used for outgoing channels."
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
  id: IdleTimeout
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: IdleTimeout
  nameWithType: TcpConnectionPoolSettingsElement.IdleTimeout
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets the maximum time the connection can be idle before being disconnected."
  syntax:
    content: public TimeSpan IdleTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "A positive &lt;xref:System.TimeSpan&gt; that specifies the maximum time the connection can be idle before being disconnected. The default is 00:02:00."
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout
  id: LeaseTimeout
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: LeaseTimeout
  nameWithType: TcpConnectionPoolSettingsElement.LeaseTimeout
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets the time span after which an active connection is closed."
  remarks: "A connection is closed after it is returned to the connection cache and not during active transmission. The connection cache used by the TCP transport creates new connections as required for each endpoint, up to the cache limit that is set by <xref:System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint%2A>."
  syntax:
    content: public TimeSpan LeaseTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "A &lt;xref:System.TimeSpan&gt; structure that indicates the duration after which the TCP connection is closed."
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  id: MaxOutboundConnectionsPerEndpoint
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets the maximum number of connections to a remote endpoint initiated by the service."
  remarks: "Connections in excess of the limit are queued until a space below the limit becomes available. This property limits the duration in which connections remain queued before an exception is thrown.       This property limits the number of simultaneous active connections from the client to a particular service endpoint. If this value is exceeded by having more active client connections, the service may appear unresponsive to the client. In this case, this value should be adjusted to exceed the maximum number of expected simultaneous client connections to a specific endpoint.       This setting can also be set on the service side, in which case the value is used to set the <xref:System.ServiceModel.Channels.MaxPooledConnections%2A> on the <xref:System.ServiceModel.Channels.TcpChannelListener>."
  syntax:
    content: public int MaxOutboundConnectionsPerEndpoint { get; set; }
    return:
      type: System.Int32
      description: "The maximum number of connections to a remote endpoint initiated by the service. The default is 10."
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: Properties
  nameWithType: TcpConnectionPoolSettingsElement.Properties
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.#ctor
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: TcpConnectionPoolSettingsElement()
  nameWithType: TcpConnectionPoolSettingsElement.TcpConnectionPoolSettingsElement()
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.TcpConnectionPoolSettingsElement()
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: GroupName
  nameWithType: TcpConnectionPoolSettingsElement.GroupName
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: IdleTimeout
  nameWithType: TcpConnectionPoolSettingsElement.IdleTimeout
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: LeaseTimeout
  nameWithType: TcpConnectionPoolSettingsElement.LeaseTimeout
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: Properties
  nameWithType: TcpConnectionPoolSettingsElement.Properties
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.#ctor*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: TcpConnectionPoolSettingsElement
  nameWithType: TcpConnectionPoolSettingsElement.TcpConnectionPoolSettingsElement
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: GroupName
  nameWithType: TcpConnectionPoolSettingsElement.GroupName
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: IdleTimeout
  nameWithType: TcpConnectionPoolSettingsElement.IdleTimeout
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: LeaseTimeout
  nameWithType: TcpConnectionPoolSettingsElement.LeaseTimeout
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: Properties
  nameWithType: TcpConnectionPoolSettingsElement.Properties
