### YamlMime:ManagedReference
items:
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  id: ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  children:
  - System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult
  - System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.IsCompleted
  - System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.OnCompleted(System.Action)
  - System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.UnsafeOnCompleted(System.Action)
  langs:
  - csharp
  name: ConfiguredTaskAwaitable+ConfiguredTaskAwaiter
  nameWithType: ConfiguredTaskAwaitable+ConfiguredTaskAwaiter
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter
  type: Struct
  syntax:
    content: 'public struct ConfiguredTaskAwaitable.ConfiguredTaskAwaiter : System.Runtime.CompilerServices.ICriticalNotifyCompletion'
  inheritance:
  - System.ValueType
  implements:
  - System.Runtime.CompilerServices.ICriticalNotifyCompletion
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult
  id: GetResult
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  langs:
  - csharp
  name: GetResult()
  nameWithType: ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult()
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult()
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Runtime.CompilerServices
  syntax:
    content: public void GetResult ();
    parameters: []
  overload: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.IsCompleted
  id: IsCompleted
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  langs:
  - csharp
  name: IsCompleted
  nameWithType: ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.IsCompleted
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.IsCompleted
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Runtime.CompilerServices
  syntax:
    content: public bool IsCompleted { get; }
    return:
      type: System.Boolean
      description: "To be added."
  overload: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.IsCompleted*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.OnCompleted(System.Action)
  id: OnCompleted(System.Action)
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  langs:
  - csharp
  name: OnCompleted(Action)
  nameWithType: ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.OnCompleted(Action)
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.OnCompleted(Action)
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Runtime.CompilerServices
  syntax:
    content: public void OnCompleted (Action continuation);
    parameters:
    - id: continuation
      type: System.Action
      description: "To be added."
  overload: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.OnCompleted*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.UnsafeOnCompleted(System.Action)
  id: UnsafeOnCompleted(System.Action)
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  langs:
  - csharp
  name: UnsafeOnCompleted(Action)
  nameWithType: ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.UnsafeOnCompleted(Action)
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.UnsafeOnCompleted(Action)
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Runtime.CompilerServices
  syntax:
    content: public void UnsafeOnCompleted (Action continuation);
    parameters:
    - id: continuation
      type: System.Action
      description: "To be added."
  overload: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.UnsafeOnCompleted*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ValueType
  isExternal: false
  name: System.ValueType
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  isExternal: false
  name: GetResult()
  nameWithType: ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult()
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult()
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.IsCompleted
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  isExternal: false
  name: IsCompleted
  nameWithType: ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.IsCompleted
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.IsCompleted
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.OnCompleted(System.Action)
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  isExternal: false
  name: OnCompleted(Action)
  nameWithType: ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.OnCompleted(Action)
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.OnCompleted(Action)
- uid: System.Action
  parent: System
  isExternal: true
  name: Action
  nameWithType: Action
  fullName: System.Action
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.UnsafeOnCompleted(System.Action)
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  isExternal: false
  name: UnsafeOnCompleted(Action)
  nameWithType: ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.UnsafeOnCompleted(Action)
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.UnsafeOnCompleted(Action)
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult*
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  isExternal: false
  name: GetResult
  nameWithType: ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.IsCompleted*
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  isExternal: false
  name: IsCompleted
  nameWithType: ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.IsCompleted
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.OnCompleted*
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  isExternal: false
  name: OnCompleted
  nameWithType: ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.OnCompleted
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.UnsafeOnCompleted*
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  isExternal: false
  name: UnsafeOnCompleted
  nameWithType: ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.UnsafeOnCompleted
