### YamlMime:ManagedReference
items:
- uid: System.EnvironmentVariableTarget
  id: EnvironmentVariableTarget
  children:
  - System.EnvironmentVariableTarget.Machine
  - System.EnvironmentVariableTarget.Process
  - System.EnvironmentVariableTarget.User
  langs:
  - csharp
  name: EnvironmentVariableTarget
  nameWithType: EnvironmentVariableTarget
  fullName: System.EnvironmentVariableTarget
  type: Enum
  summary: "Specifies the location where an environment variable is stored or retrieved in a set or get operation."
  remarks: "The EnvironmentVariableTarget enumeration is used by certain overloads of the <xref:System.Environment.SetEnvironmentVariable%2A>, <xref:System.Environment.GetEnvironmentVariable%2A>, and <xref:System.Environment.GetEnvironmentVariables%2A> methods to specify the location, or target, where the name and value of an environment variable is stored or retrieved.       The target can be one of three locations: the environment block associated with the current process, the Windows operating system registry key reserved for environment variables associated with the current user, or the registry key reserved for environment variables associated with all users on the local machine."
  example:
  - "The following code example demonstrates the EnvironmentVariableTarget enumeration in methods that create, modify, and delete environment variables.  \n  \n [!code-cpp[environment.getsetenvar#1](~/add/codesnippet/CPP/t-system.environmentvari_1.cpp)]\n [!code-vb[environment.getsetenvar#1](~/add/codesnippet/VisualBasic/t-system.environmentvari_1.vb)]\n [!code-cs[environment.getsetenvar#1](~/add/codesnippet/CSharp/t-system.environmentvari_1.cs)]"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public enum EnvironmentVariableTarget
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.EnvironmentVariableTarget.Machine
  id: Machine
  parent: System.EnvironmentVariableTarget
  langs:
  - csharp
  name: Machine
  nameWithType: EnvironmentVariableTarget.Machine
  fullName: System.EnvironmentVariableTarget.Machine
  type: Field
  assemblies:
  - mscorlib
  namespace: System
  summary: "The environment variable is stored or retrieved from the <xref uid=&quot;langword_csharp_HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Control\\Session Manager\\Environment&quot; name=&quot;HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Control\\Session Manager\\Environment&quot; href=&quot;&quot;></xref> key in the Windows operating system registry."
  remarks: "When a user creates the environment variable in a set operation, the operating system stores the environment variable in the system registry, but not in the current process. If any user on the local machine starts a new process, the operating system copies the environment variable from the registry to that process.       When the process terminates, the operating system destroys the environment variable in that process. However, the environment variable in the registry persists until a user removes it programmatically or by means of an operating system tool."
  syntax:
    content: Machine
    return:
      type: System.EnvironmentVariableTarget
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.EnvironmentVariableTarget.Process
  id: Process
  parent: System.EnvironmentVariableTarget
  langs:
  - csharp
  name: Process
  nameWithType: EnvironmentVariableTarget.Process
  fullName: System.EnvironmentVariableTarget.Process
  type: Field
  assemblies:
  - mscorlib
  namespace: System
  summary: "The environment variable is stored or retrieved from the environment block associated with the current process."
  remarks: "The user creates the environment variable in a set operation.       When the process terminates, the operating system destroys the environment variable in that process."
  syntax:
    content: Process
    return:
      type: System.EnvironmentVariableTarget
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.EnvironmentVariableTarget.User
  id: User
  parent: System.EnvironmentVariableTarget
  langs:
  - csharp
  name: User
  nameWithType: EnvironmentVariableTarget.User
  fullName: System.EnvironmentVariableTarget.User
  type: Field
  assemblies:
  - mscorlib
  namespace: System
  summary: "The environment variable is stored or retrieved from the <xref uid=&quot;langword_csharp_HKEY_CURRENT_USER\\Environment&quot; name=&quot;HKEY_CURRENT_USER\\Environment&quot; href=&quot;&quot;></xref> key in the Windows operating system registry."
  remarks: "When the user creates the environment variable in a set operation, the operating system stores the environment variable in the system registry, but not in the current process. If the user starts a new process, the operating system copies the environment variable from the registry to that process.       When the process terminates, the operating system destroys the environment variable in that process. However, the environment variable in the registry persists until the user removes it programmatically or by means of an operating system tool."
  syntax:
    content: User
    return:
      type: System.EnvironmentVariableTarget
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.EnvironmentVariableTarget.Machine
  parent: System.EnvironmentVariableTarget
  isExternal: false
  name: Machine
  nameWithType: EnvironmentVariableTarget.Machine
  fullName: System.EnvironmentVariableTarget.Machine
- uid: System.EnvironmentVariableTarget
  parent: System
  isExternal: false
  name: EnvironmentVariableTarget
  nameWithType: EnvironmentVariableTarget
  fullName: System.EnvironmentVariableTarget
- uid: System.EnvironmentVariableTarget.Process
  parent: System.EnvironmentVariableTarget
  isExternal: false
  name: Process
  nameWithType: EnvironmentVariableTarget.Process
  fullName: System.EnvironmentVariableTarget.Process
- uid: System.EnvironmentVariableTarget.User
  parent: System.EnvironmentVariableTarget
  isExternal: false
  name: User
  nameWithType: EnvironmentVariableTarget.User
  fullName: System.EnvironmentVariableTarget.User
