### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DeploymentException
  id: DeploymentException
  children:
  - System.Deployment.Application.DeploymentException.#ctor
  - System.Deployment.Application.DeploymentException.#ctor(System.String)
  - System.Deployment.Application.DeploymentException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.DeploymentException.#ctor(System.String,System.Exception)
  - System.Deployment.Application.DeploymentException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  langs:
  - csharp
  name: DeploymentException
  nameWithType: DeploymentException
  fullName: System.Deployment.Application.DeploymentException
  type: Class
  summary: "Defines a base class for all deployment-related exceptions."
  remarks: "DeploymentException is the base class of all deployment-related exceptions thrown by the <xref:System.Deployment.Application.ApplicationDeployment> class."
  syntax:
    content: 'public class DeploymentException : SystemException'
  inheritance:
  - System.Exception
  - System.SystemException
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.DeploymentException
  langs:
  - csharp
  name: DeploymentException()
  nameWithType: DeploymentException.DeploymentException()
  fullName: System.Deployment.Application.DeploymentException.DeploymentException()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Deployment.Application.DeploymentException&quot;></see> class."
  syntax:
    content: public DeploymentException ();
    parameters: []
  overload: System.Deployment.Application.DeploymentException.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.DeploymentException
  langs:
  - csharp
  name: DeploymentException(String)
  nameWithType: DeploymentException.DeploymentException(String)
  fullName: System.Deployment.Application.DeploymentException.DeploymentException(String)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Deployment.Application.DeploymentException&quot;></see> class."
  syntax:
    content: public DeploymentException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Represents text as a series of Unicode characters."
  overload: System.Deployment.Application.DeploymentException.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.DeploymentException
  langs:
  - csharp
  name: DeploymentException(SerializationInfo,StreamingContext)
  nameWithType: DeploymentException.DeploymentException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DeploymentException.DeploymentException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Deployment.Application.DeploymentException&quot;></see> class."
  syntax:
    content: protected DeploymentException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: "Stores all the data needed to serialize or deserialize an object. This class cannot be inherited."
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: "Describes the source and destination of a given serialized stream, and provides an additional caller-defined context."
  overload: System.Deployment.Application.DeploymentException.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.DeploymentException
  langs:
  - csharp
  name: DeploymentException(String,Exception)
  nameWithType: DeploymentException.DeploymentException(String,Exception)
  fullName: System.Deployment.Application.DeploymentException.DeploymentException(String,Exception)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Deployment.Application.DeploymentException&quot;></see> class."
  syntax:
    content: public DeploymentException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Represents text as a series of Unicode characters."
    - id: innerException
      type: System.Exception
      description: "Represents errors that occur during application execution."
  overload: System.Deployment.Application.DeploymentException.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.DeploymentException
  langs:
  - csharp
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: DeploymentException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DeploymentException.GetObjectData(SerializationInfo,StreamingContext)
  type: Method
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Sets the <see cref=&quot;T:System.Runtime.Serialization.SerializationInfo&quot;></see> with information about the exception."
  syntax:
    content: public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "The  that holds the serialized object data about the exception being thrown."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "The <xref:System.Runtime.Serialization.StreamingContext> that contains contextual information about the source or destination."
  overload: System.Deployment.Application.DeploymentException.GetObjectData*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.SystemException
  isExternal: false
  name: System.SystemException
- uid: System.Deployment.Application.DeploymentException.#ctor
  parent: System.Deployment.Application.DeploymentException
  isExternal: false
  name: DeploymentException()
  nameWithType: DeploymentException.DeploymentException()
  fullName: System.Deployment.Application.DeploymentException.DeploymentException()
- uid: System.Deployment.Application.DeploymentException.#ctor(System.String)
  parent: System.Deployment.Application.DeploymentException
  isExternal: false
  name: DeploymentException(String)
  nameWithType: DeploymentException.DeploymentException(String)
  fullName: System.Deployment.Application.DeploymentException.DeploymentException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.DeploymentException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.DeploymentException
  isExternal: false
  name: DeploymentException(SerializationInfo,StreamingContext)
  nameWithType: DeploymentException.DeploymentException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DeploymentException.DeploymentException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.DeploymentException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.DeploymentException
  isExternal: false
  name: DeploymentException(String,Exception)
  nameWithType: DeploymentException.DeploymentException(String,Exception)
  fullName: System.Deployment.Application.DeploymentException.DeploymentException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Deployment.Application.DeploymentException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.DeploymentException
  isExternal: false
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: DeploymentException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DeploymentException.GetObjectData(SerializationInfo,StreamingContext)
- uid: System.Deployment.Application.DeploymentException.#ctor*
  parent: System.Deployment.Application.DeploymentException
  isExternal: false
  name: DeploymentException
  nameWithType: DeploymentException.DeploymentException
- uid: System.Deployment.Application.DeploymentException.GetObjectData*
  parent: System.Deployment.Application.DeploymentException
  isExternal: false
  name: GetObjectData
  nameWithType: DeploymentException.GetObjectData
