### YamlMime:ManagedReference
items:
- uid: System.Configuration.ProtectedConfigurationProviderCollection
  id: ProtectedConfigurationProviderCollection
  children:
  - System.Configuration.ProtectedConfigurationProviderCollection.#ctor
  - System.Configuration.ProtectedConfigurationProviderCollection.Add(System.Configuration.Provider.ProviderBase)
  - System.Configuration.ProtectedConfigurationProviderCollection.Item(System.String)
  langs:
  - csharp
  name: ProtectedConfigurationProviderCollection
  nameWithType: ProtectedConfigurationProviderCollection
  fullName: System.Configuration.ProtectedConfigurationProviderCollection
  type: Class
  summary: "Provides a collection of <see cref=&quot;T:System.Configuration.ProtectedConfigurationProvider&quot;></see> objects."
  remarks: "The <xref:System.Configuration.ProtectedConfiguration.Providers%2A> property of the <xref:System.Configuration.ProtectedConfiguration> class is a ProtectedConfigurationProviderCollection collection of all protected-configuration providers available to your application.       You can encrypt sections of a configuration file to protect sensitive information used by your application. This improves security by making unauthorized access difficult, even if an attacker gains access to your configuration file.       The .NET Framework includes two protected configuration providers that can be used to encrypt sections of a configuration file: the <xref:System.Configuration.RsaProtectedConfigurationProvider> class, which uses the <xref:System.Security.Cryptography.RSACryptoServiceProvider> class to encrypt configuration sections, and the <xref:System.Configuration.DpapiProtectedConfigurationProvider> class, which uses the Windows Data Protection API (DPAPI) to encrypt configuration sections.       You might have a requirement to encrypt sensitive information using an algorithm other than the RSA or DPAPI providers. In this case, you can build your own custom protected-configuration provider. The <xref:System.Configuration.ProtectedConfigurationProvider> class is an abstract base class that you must inherit from to create your own protected-configuration provider.       For more information about protected configuration, see [Encrypting Configuration Information Using Protected Configuration](../Topic/Encrypting%20Configuration%20Information%20Using%20Protected%20Configuration.md)."
  syntax:
    content: 'public class ProtectedConfigurationProviderCollection : System.Configuration.Provider.ProviderCollection'
  inheritance:
  - System.Object
  - System.Configuration.Provider.ProviderCollection
  implements: []
  inheritedMembers:
  - System.Configuration.Provider.ProviderCollection.Clear
  - System.Configuration.Provider.ProviderCollection.CopyTo(System.Configuration.Provider.ProviderBase[],System.Int32)
  - System.Configuration.Provider.ProviderCollection.Count
  - System.Configuration.Provider.ProviderCollection.GetEnumerator
  - System.Configuration.Provider.ProviderCollection.IsSynchronized
  - System.Configuration.Provider.ProviderCollection.Remove(System.String)
  - System.Configuration.Provider.ProviderCollection.SetReadOnly
  - System.Configuration.Provider.ProviderCollection.SyncRoot
  - System.Configuration.Provider.ProviderCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProtectedConfigurationProviderCollection.#ctor
  id: '#ctor'
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  langs:
  - csharp
  name: ProtectedConfigurationProviderCollection()
  nameWithType: ProtectedConfigurationProviderCollection.ProtectedConfigurationProviderCollection()
  fullName: System.Configuration.ProtectedConfigurationProviderCollection.ProtectedConfigurationProviderCollection()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.ProtectedConfigurationProviderCollection&quot;></see> class using default settings."
  remarks: "The ProtectedConfigurationProviderCollection constructor is not intended to be used directly from your code. It is called by the ASP.NET configuration system. You obtain an instance of the <xref:System.Configuration.ProtectedConfigurationProviderCollection> class by using the <xref:System.Configuration.ProtectedConfiguration.Providers%2A> property of the <xref:System.Configuration.ProtectedConfiguration> class."
  syntax:
    content: public ProtectedConfigurationProviderCollection ();
    parameters: []
  overload: System.Configuration.ProtectedConfigurationProviderCollection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProtectedConfigurationProviderCollection.Add(System.Configuration.Provider.ProviderBase)
  id: Add(System.Configuration.Provider.ProviderBase)
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  langs:
  - csharp
  name: Add(ProviderBase)
  nameWithType: ProtectedConfigurationProviderCollection.Add(ProviderBase)
  fullName: System.Configuration.ProtectedConfigurationProviderCollection.Add(ProviderBase)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Adds a <see cref=&quot;T:System.Configuration.ProtectedConfigurationProvider&quot;></see> object to the collection."
  syntax:
    content: public override void Add (System.Configuration.Provider.ProviderBase provider);
    parameters:
    - id: provider
      type: System.Configuration.Provider.ProviderBase
      description: "A  object to add to the collection."
  overload: System.Configuration.ProtectedConfigurationProviderCollection.Add*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "\n    provider is ."
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "\n    provider is not a  object."
  - type: System.Configuration.ConfigurationException
    commentId: T:System.Configuration.ConfigurationException
    description: "The  object to add already exists in the collection.  \n  \n \\- or -  \n  \n The collection is read-only."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProtectedConfigurationProviderCollection.Item(System.String)
  id: Item(System.String)
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  langs:
  - csharp
  name: Item(String)
  nameWithType: ProtectedConfigurationProviderCollection.Item(String)
  fullName: System.Configuration.ProtectedConfigurationProviderCollection.Item(String)
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets a <see cref=&quot;T:System.Configuration.ProtectedConfigurationProvider&quot;></see> object in the collection with the specified name."
  syntax:
    content: public System.Configuration.ProtectedConfigurationProvider this[string name] { get; }
    parameters:
    - id: name
      type: System.String
      description: "The name of a  object in the collection."
    return:
      type: System.Configuration.ProtectedConfigurationProvider
      description: "The <see cref=&quot;T:System.Configuration.ProtectedConfigurationProvider&quot;></see> object with the specified name, or <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref> if there is no object with that name."
  overload: System.Configuration.ProtectedConfigurationProviderCollection.Item*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: System.Configuration.Provider.ProviderCollection
- uid: System.Configuration.ProtectedConfigurationProviderCollection.#ctor
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  isExternal: false
  name: ProtectedConfigurationProviderCollection()
  nameWithType: ProtectedConfigurationProviderCollection.ProtectedConfigurationProviderCollection()
  fullName: System.Configuration.ProtectedConfigurationProviderCollection.ProtectedConfigurationProviderCollection()
- uid: System.Configuration.ProtectedConfigurationProviderCollection.Add(System.Configuration.Provider.ProviderBase)
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  isExternal: false
  name: Add(ProviderBase)
  nameWithType: ProtectedConfigurationProviderCollection.Add(ProviderBase)
  fullName: System.Configuration.ProtectedConfigurationProviderCollection.Add(ProviderBase)
- uid: System.Configuration.Provider.ProviderBase
  parent: System.Configuration.Provider
  isExternal: false
  name: ProviderBase
  nameWithType: ProviderBase
  fullName: System.Configuration.Provider.ProviderBase
- uid: System.Configuration.ProtectedConfigurationProviderCollection.Item(System.String)
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  isExternal: false
  name: Item(String)
  nameWithType: ProtectedConfigurationProviderCollection.Item(String)
  fullName: System.Configuration.ProtectedConfigurationProviderCollection.Item(String)
- uid: System.Configuration.ProtectedConfigurationProvider
  parent: System.Configuration
  isExternal: false
  name: ProtectedConfigurationProvider
  nameWithType: ProtectedConfigurationProvider
  fullName: System.Configuration.ProtectedConfigurationProvider
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ProtectedConfigurationProviderCollection.#ctor*
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  isExternal: false
  name: ProtectedConfigurationProviderCollection
  nameWithType: ProtectedConfigurationProviderCollection.ProtectedConfigurationProviderCollection
- uid: System.Configuration.ProtectedConfigurationProviderCollection.Add*
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  isExternal: false
  name: Add
  nameWithType: ProtectedConfigurationProviderCollection.Add
- uid: System.Configuration.ProtectedConfigurationProviderCollection.Item*
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  isExternal: false
  name: Item
  nameWithType: ProtectedConfigurationProviderCollection.Item
