### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.WindowsClientElement
  id: WindowsClientElement
  children:
  - System.ServiceModel.Configuration.WindowsClientElement.#ctor
  - System.ServiceModel.Configuration.WindowsClientElement.AllowedImpersonationLevel
  - System.ServiceModel.Configuration.WindowsClientElement.AllowNtlm
  - System.ServiceModel.Configuration.WindowsClientElement.Copy(System.ServiceModel.Configuration.WindowsClientElement)
  - System.ServiceModel.Configuration.WindowsClientElement.Properties
  langs:
  - csharp
  name: WindowsClientElement
  nameWithType: WindowsClientElement
  fullName: System.ServiceModel.Configuration.WindowsClientElement
  type: Class
  summary: "Represents a configuration element that specifies the settings for a Windows credential to be used to represent the client. This class cannot be inherited."
  syntax:
    content: 'public sealed class WindowsClientElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.WindowsClientElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.WindowsClientElement
  langs:
  - csharp
  name: WindowsClientElement()
  nameWithType: WindowsClientElement.WindowsClientElement()
  fullName: System.ServiceModel.Configuration.WindowsClientElement.WindowsClientElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.WindowsClientElement&quot;></see> class."
  syntax:
    content: public WindowsClientElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.WindowsClientElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.WindowsClientElement.AllowedImpersonationLevel
  id: AllowedImpersonationLevel
  parent: System.ServiceModel.Configuration.WindowsClientElement
  langs:
  - csharp
  name: AllowedImpersonationLevel
  nameWithType: WindowsClientElement.AllowedImpersonationLevel
  fullName: System.ServiceModel.Configuration.WindowsClientElement.AllowedImpersonationLevel
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets the permissible impersonation level."
  remarks: "See <xref:System.Security.Principal.TokenImpersonationLevel> for a description of the enumeration."
  syntax:
    content: public System.Security.Principal.TokenImpersonationLevel AllowedImpersonationLevel { get; set; }
    return:
      type: System.Security.Principal.TokenImpersonationLevel
      description: "A valid &lt;xref:System.Security.Principal.TokenImpersonationLevel&gt; value that specifies the permissible impersonation level. The default is &lt;xref:System.Security.Principal.TokenImpersonationLevel&gt;."
  overload: System.ServiceModel.Configuration.WindowsClientElement.AllowedImpersonationLevel*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.WindowsClientElement.AllowNtlm
  id: AllowNtlm
  parent: System.ServiceModel.Configuration.WindowsClientElement
  langs:
  - csharp
  name: AllowNtlm
  nameWithType: WindowsClientElement.AllowNtlm
  fullName: System.ServiceModel.Configuration.WindowsClientElement.AllowNtlm
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets a boolean value that specifies whether NTLM authentication is allowed."
  remarks: "When this property is set to `true`, Windows security is enabled at the workgroup level. Otherwise, Windows security is only supported at the domain level."
  syntax:
    content: public bool AllowNtlm { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if Windows security is enabled in the workgroup scenario; otherwise, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>. The default is <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>."
  overload: System.ServiceModel.Configuration.WindowsClientElement.AllowNtlm*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.WindowsClientElement.Copy(System.ServiceModel.Configuration.WindowsClientElement)
  id: Copy(System.ServiceModel.Configuration.WindowsClientElement)
  parent: System.ServiceModel.Configuration.WindowsClientElement
  langs:
  - csharp
  name: Copy(WindowsClientElement)
  nameWithType: WindowsClientElement.Copy(WindowsClientElement)
  fullName: System.ServiceModel.Configuration.WindowsClientElement.Copy(WindowsClientElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Copies the content of the specified configuration element to this configuration element."
  syntax:
    content: public void Copy (System.ServiceModel.Configuration.WindowsClientElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.WindowsClientElement
      description: "The configuration element to be copied."
  overload: System.ServiceModel.Configuration.WindowsClientElement.Copy*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "\n    from is ."
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "The configuration file is read-only."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.WindowsClientElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.WindowsClientElement
  langs:
  - csharp
  name: Properties
  nameWithType: WindowsClientElement.Properties
  fullName: System.ServiceModel.Configuration.WindowsClientElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.WindowsClientElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.WindowsClientElement.#ctor
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: WindowsClientElement()
  nameWithType: WindowsClientElement.WindowsClientElement()
  fullName: System.ServiceModel.Configuration.WindowsClientElement.WindowsClientElement()
- uid: System.ServiceModel.Configuration.WindowsClientElement.AllowedImpersonationLevel
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: AllowedImpersonationLevel
  nameWithType: WindowsClientElement.AllowedImpersonationLevel
  fullName: System.ServiceModel.Configuration.WindowsClientElement.AllowedImpersonationLevel
- uid: System.Security.Principal.TokenImpersonationLevel
  parent: System.Security.Principal
  isExternal: true
  name: TokenImpersonationLevel
  nameWithType: TokenImpersonationLevel
  fullName: System.Security.Principal.TokenImpersonationLevel
- uid: System.ServiceModel.Configuration.WindowsClientElement.AllowNtlm
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: AllowNtlm
  nameWithType: WindowsClientElement.AllowNtlm
  fullName: System.ServiceModel.Configuration.WindowsClientElement.AllowNtlm
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.WindowsClientElement.Copy(System.ServiceModel.Configuration.WindowsClientElement)
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: Copy(WindowsClientElement)
  nameWithType: WindowsClientElement.Copy(WindowsClientElement)
  fullName: System.ServiceModel.Configuration.WindowsClientElement.Copy(WindowsClientElement)
- uid: System.ServiceModel.Configuration.WindowsClientElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: WindowsClientElement
  nameWithType: WindowsClientElement
  fullName: System.ServiceModel.Configuration.WindowsClientElement
- uid: System.ServiceModel.Configuration.WindowsClientElement.Properties
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: Properties
  nameWithType: WindowsClientElement.Properties
  fullName: System.ServiceModel.Configuration.WindowsClientElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.WindowsClientElement.#ctor*
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: WindowsClientElement
  nameWithType: WindowsClientElement.WindowsClientElement
- uid: System.ServiceModel.Configuration.WindowsClientElement.AllowedImpersonationLevel*
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: AllowedImpersonationLevel
  nameWithType: WindowsClientElement.AllowedImpersonationLevel
- uid: System.ServiceModel.Configuration.WindowsClientElement.AllowNtlm*
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: AllowNtlm
  nameWithType: WindowsClientElement.AllowNtlm
- uid: System.ServiceModel.Configuration.WindowsClientElement.Copy*
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: Copy
  nameWithType: WindowsClientElement.Copy
- uid: System.ServiceModel.Configuration.WindowsClientElement.Properties*
  parent: System.ServiceModel.Configuration.WindowsClientElement
  isExternal: false
  name: Properties
  nameWithType: WindowsClientElement.Properties
