### YamlMime:ManagedReference
items:
- uid: System.ComponentModel.SettingsBindableAttribute
  id: SettingsBindableAttribute
  children:
  - System.ComponentModel.SettingsBindableAttribute.#ctor(System.Boolean)
  - System.ComponentModel.SettingsBindableAttribute.Bindable
  - System.ComponentModel.SettingsBindableAttribute.Equals(System.Object)
  - System.ComponentModel.SettingsBindableAttribute.GetHashCode
  - System.ComponentModel.SettingsBindableAttribute.No
  - System.ComponentModel.SettingsBindableAttribute.Yes
  langs:
  - csharp
  name: SettingsBindableAttribute
  nameWithType: SettingsBindableAttribute
  fullName: System.ComponentModel.SettingsBindableAttribute
  type: Class
  summary: "Specifies when a component property can be bound to an application setting."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class SettingsBindableAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ComponentModel.SettingsBindableAttribute.#ctor(System.Boolean)
  id: '#ctor(System.Boolean)'
  parent: System.ComponentModel.SettingsBindableAttribute
  langs:
  - csharp
  name: SettingsBindableAttribute(Boolean)
  nameWithType: SettingsBindableAttribute.SettingsBindableAttribute(Boolean)
  fullName: System.ComponentModel.SettingsBindableAttribute.SettingsBindableAttribute(Boolean)
  type: Constructor
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ComponentModel.SettingsBindableAttribute&quot;></see> class."
  syntax:
    content: public SettingsBindableAttribute (bool bindable);
    parameters:
    - id: bindable
      type: System.Boolean
      description: "\n     to specify that a property is appropriate to bind settings to; otherwise, ."
  overload: System.ComponentModel.SettingsBindableAttribute.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ComponentModel.SettingsBindableAttribute.Bindable
  id: Bindable
  parent: System.ComponentModel.SettingsBindableAttribute
  langs:
  - csharp
  name: Bindable
  nameWithType: SettingsBindableAttribute.Bindable
  fullName: System.ComponentModel.SettingsBindableAttribute.Bindable
  type: Property
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "Gets a value indicating whether a property is appropriate to bind settings to."
  syntax:
    content: public bool Bindable { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if the property is appropriate to bind settings to; otherwise, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>."
  overload: System.ComponentModel.SettingsBindableAttribute.Bindable*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ComponentModel.SettingsBindableAttribute.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.ComponentModel.SettingsBindableAttribute
  langs:
  - csharp
  name: Equals(Object)
  nameWithType: SettingsBindableAttribute.Equals(Object)
  fullName: System.ComponentModel.SettingsBindableAttribute.Equals(Object)
  type: Method
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "Returns a value that indicates whether this instance is equal to a specified object."
  syntax:
    content: public override bool Equals (object obj);
    parameters:
    - id: obj
      type: System.Object
      description: "An <xref:System.Object> to compare with this instance or a null reference ( in Visual Basic)."
    return:
      type: System.Boolean
      description: "To be added."
  overload: System.ComponentModel.SettingsBindableAttribute.Equals*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ComponentModel.SettingsBindableAttribute.GetHashCode
  id: GetHashCode
  parent: System.ComponentModel.SettingsBindableAttribute
  langs:
  - csharp
  name: GetHashCode()
  nameWithType: SettingsBindableAttribute.GetHashCode()
  fullName: System.ComponentModel.SettingsBindableAttribute.GetHashCode()
  type: Method
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "Returns the hash code for this instance."
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: "To be added."
  overload: System.ComponentModel.SettingsBindableAttribute.GetHashCode*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ComponentModel.SettingsBindableAttribute.No
  id: No
  parent: System.ComponentModel.SettingsBindableAttribute
  langs:
  - csharp
  name: No
  nameWithType: SettingsBindableAttribute.No
  fullName: System.ComponentModel.SettingsBindableAttribute.No
  type: Field
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "Specifies that a property is not appropriate to bind settings to."
  syntax:
    content: public static readonly System.ComponentModel.SettingsBindableAttribute No;
    return:
      type: System.ComponentModel.SettingsBindableAttribute
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ComponentModel.SettingsBindableAttribute.Yes
  id: Yes
  parent: System.ComponentModel.SettingsBindableAttribute
  langs:
  - csharp
  name: Yes
  nameWithType: SettingsBindableAttribute.Yes
  fullName: System.ComponentModel.SettingsBindableAttribute.Yes
  type: Field
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "Specifies that a property is appropriate to bind settings to."
  syntax:
    content: public static readonly System.ComponentModel.SettingsBindableAttribute Yes;
    return:
      type: System.ComponentModel.SettingsBindableAttribute
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.ComponentModel.SettingsBindableAttribute.#ctor(System.Boolean)
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: SettingsBindableAttribute(Boolean)
  nameWithType: SettingsBindableAttribute.SettingsBindableAttribute(Boolean)
  fullName: System.ComponentModel.SettingsBindableAttribute.SettingsBindableAttribute(Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ComponentModel.SettingsBindableAttribute.Bindable
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: Bindable
  nameWithType: SettingsBindableAttribute.Bindable
  fullName: System.ComponentModel.SettingsBindableAttribute.Bindable
- uid: System.ComponentModel.SettingsBindableAttribute.Equals(System.Object)
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: Equals(Object)
  nameWithType: SettingsBindableAttribute.Equals(Object)
  fullName: System.ComponentModel.SettingsBindableAttribute.Equals(Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.SettingsBindableAttribute.GetHashCode
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: GetHashCode()
  nameWithType: SettingsBindableAttribute.GetHashCode()
  fullName: System.ComponentModel.SettingsBindableAttribute.GetHashCode()
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ComponentModel.SettingsBindableAttribute.No
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: No
  nameWithType: SettingsBindableAttribute.No
  fullName: System.ComponentModel.SettingsBindableAttribute.No
- uid: System.ComponentModel.SettingsBindableAttribute
  parent: System.ComponentModel
  isExternal: false
  name: SettingsBindableAttribute
  nameWithType: SettingsBindableAttribute
  fullName: System.ComponentModel.SettingsBindableAttribute
- uid: System.ComponentModel.SettingsBindableAttribute.Yes
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: Yes
  nameWithType: SettingsBindableAttribute.Yes
  fullName: System.ComponentModel.SettingsBindableAttribute.Yes
- uid: System.ComponentModel.SettingsBindableAttribute.#ctor*
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: SettingsBindableAttribute
  nameWithType: SettingsBindableAttribute.SettingsBindableAttribute
- uid: System.ComponentModel.SettingsBindableAttribute.Bindable*
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: Bindable
  nameWithType: SettingsBindableAttribute.Bindable
- uid: System.ComponentModel.SettingsBindableAttribute.Equals*
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: Equals
  nameWithType: SettingsBindableAttribute.Equals
- uid: System.ComponentModel.SettingsBindableAttribute.GetHashCode*
  parent: System.ComponentModel.SettingsBindableAttribute
  isExternal: false
  name: GetHashCode
  nameWithType: SettingsBindableAttribute.GetHashCode
