### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.FormsAuthPasswordFormat
  id: FormsAuthPasswordFormat
  children:
  - System.Web.Configuration.FormsAuthPasswordFormat.Clear
  - System.Web.Configuration.FormsAuthPasswordFormat.MD5
  - System.Web.Configuration.FormsAuthPasswordFormat.SHA1
  langs:
  - csharp
  name: FormsAuthPasswordFormat
  nameWithType: FormsAuthPasswordFormat
  fullName: System.Web.Configuration.FormsAuthPasswordFormat
  type: Enum
  summary: "Defines the encryption format for storing passwords."
  remarks: "To programmatically configure the type of encryption used to store passwords in a Web application, use the <xref:System.Web.Configuration.AuthenticationSection> class. This class is also used internally by <xref:System.Web.Security.FormsAuthentication> in the processing of authentication tickets."
  example:
  - "The following code example shows how to use the FormsAuthPasswordFormat enumeration. Refer to the code example in the <xref:System.Web.Configuration.FormsAuthenticationUserCollection> class topic to learn how to get the collection.  \n  \n [!code-vb[System.Web.Configuration.FormsAuthenticationCredentials#3](~/add/codesnippet/VisualBasic/t-system.web.configurati_88_1.vb)]\n [!code-cs[System.Web.Configuration.FormsAuthenticationCredentials#3](~/add/codesnippet/CSharp/t-system.web.configurati_88_1.cs)]"
  syntax:
    content: public enum FormsAuthPasswordFormat
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.FormsAuthPasswordFormat.Clear
  id: Clear
  parent: System.Web.Configuration.FormsAuthPasswordFormat
  langs:
  - csharp
  name: Clear
  nameWithType: FormsAuthPasswordFormat.Clear
  fullName: System.Web.Configuration.FormsAuthPasswordFormat.Clear
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifies that passwords are not encrypted. This field is constant."
  syntax:
    content: Clear
    return:
      type: System.Web.Configuration.FormsAuthPasswordFormat
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.FormsAuthPasswordFormat.MD5
  id: MD5
  parent: System.Web.Configuration.FormsAuthPasswordFormat
  langs:
  - csharp
  name: MD5
  nameWithType: FormsAuthPasswordFormat.MD5
  fullName: System.Web.Configuration.FormsAuthPasswordFormat.MD5
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifies that passwords are encrypted using the MD5 hash algorithm. This field is constant."
  syntax:
    content: MD5
    return:
      type: System.Web.Configuration.FormsAuthPasswordFormat
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.FormsAuthPasswordFormat.SHA1
  id: SHA1
  parent: System.Web.Configuration.FormsAuthPasswordFormat
  langs:
  - csharp
  name: SHA1
  nameWithType: FormsAuthPasswordFormat.SHA1
  fullName: System.Web.Configuration.FormsAuthPasswordFormat.SHA1
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Specifies that passwords are encrypted using the SHA1 hash algorithm. This field is constant."
  syntax:
    content: SHA1
    return:
      type: System.Web.Configuration.FormsAuthPasswordFormat
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.FormsAuthPasswordFormat.Clear
  parent: System.Web.Configuration.FormsAuthPasswordFormat
  isExternal: false
  name: Clear
  nameWithType: FormsAuthPasswordFormat.Clear
  fullName: System.Web.Configuration.FormsAuthPasswordFormat.Clear
- uid: System.Web.Configuration.FormsAuthPasswordFormat
  parent: System.Web.Configuration
  isExternal: false
  name: FormsAuthPasswordFormat
  nameWithType: FormsAuthPasswordFormat
  fullName: System.Web.Configuration.FormsAuthPasswordFormat
- uid: System.Web.Configuration.FormsAuthPasswordFormat.MD5
  parent: System.Web.Configuration.FormsAuthPasswordFormat
  isExternal: false
  name: MD5
  nameWithType: FormsAuthPasswordFormat.MD5
  fullName: System.Web.Configuration.FormsAuthPasswordFormat.MD5
- uid: System.Web.Configuration.FormsAuthPasswordFormat.SHA1
  parent: System.Web.Configuration.FormsAuthPasswordFormat
  isExternal: false
  name: SHA1
  nameWithType: FormsAuthPasswordFormat.SHA1
  fullName: System.Web.Configuration.FormsAuthPasswordFormat.SHA1
