### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsSerializeAs
  id: SettingsSerializeAs
  children:
  - System.Configuration.SettingsSerializeAs.Binary
  - System.Configuration.SettingsSerializeAs.ProviderSpecific
  - System.Configuration.SettingsSerializeAs.String
  - System.Configuration.SettingsSerializeAs.Xml
  langs:
  - csharp
  name: SettingsSerializeAs
  nameWithType: SettingsSerializeAs
  fullName: System.Configuration.SettingsSerializeAs
  type: Enum
  summary: "Determines the serialization scheme used to store application settings."
  remarks: "The SettingsSerializeAsenumeration is used to specify the serialization mechanism used by the application settings provider to persist the values of application settings properties. For example, the ttribute uses this enumeration in its constructor to request that a property or group of properties be persisted using the specified serialization mechanism."
  syntax:
    content: public enum SettingsSerializeAs
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SettingsSerializeAs.Binary
  id: Binary
  parent: System.Configuration.SettingsSerializeAs
  langs:
  - csharp
  name: Binary
  nameWithType: SettingsSerializeAs.Binary
  fullName: System.Configuration.SettingsSerializeAs.Binary
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "The settings property is serialized using binary object serialization."
  syntax:
    content: Binary
    return:
      type: System.Configuration.SettingsSerializeAs
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SettingsSerializeAs.ProviderSpecific
  id: ProviderSpecific
  parent: System.Configuration.SettingsSerializeAs
  langs:
  - csharp
  name: ProviderSpecific
  nameWithType: SettingsSerializeAs.ProviderSpecific
  fullName: System.Configuration.SettingsSerializeAs.ProviderSpecific
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "The settings provider has implicit knowledge of the property or its type and picks an appropriate serialization mechanism. Often used for custom serialization."
  syntax:
    content: ProviderSpecific
    return:
      type: System.Configuration.SettingsSerializeAs
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SettingsSerializeAs.String
  id: String
  parent: System.Configuration.SettingsSerializeAs
  langs:
  - csharp
  name: String
  nameWithType: SettingsSerializeAs.String
  fullName: System.Configuration.SettingsSerializeAs.String
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "The settings property is serialized as plain text."
  syntax:
    content: String
    return:
      type: System.Configuration.SettingsSerializeAs
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SettingsSerializeAs.Xml
  id: Xml
  parent: System.Configuration.SettingsSerializeAs
  langs:
  - csharp
  name: Xml
  nameWithType: SettingsSerializeAs.Xml
  fullName: System.Configuration.SettingsSerializeAs.Xml
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "The settings property is serialized as XML using XML serialization."
  syntax:
    content: Xml
    return:
      type: System.Configuration.SettingsSerializeAs
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.SettingsSerializeAs.Binary
  parent: System.Configuration.SettingsSerializeAs
  isExternal: false
  name: Binary
  nameWithType: SettingsSerializeAs.Binary
  fullName: System.Configuration.SettingsSerializeAs.Binary
- uid: System.Configuration.SettingsSerializeAs
  parent: System.Configuration
  isExternal: false
  name: SettingsSerializeAs
  nameWithType: SettingsSerializeAs
  fullName: System.Configuration.SettingsSerializeAs
- uid: System.Configuration.SettingsSerializeAs.ProviderSpecific
  parent: System.Configuration.SettingsSerializeAs
  isExternal: false
  name: ProviderSpecific
  nameWithType: SettingsSerializeAs.ProviderSpecific
  fullName: System.Configuration.SettingsSerializeAs.ProviderSpecific
- uid: System.Configuration.SettingsSerializeAs.String
  parent: System.Configuration.SettingsSerializeAs
  isExternal: false
  name: String
  nameWithType: SettingsSerializeAs.String
  fullName: System.Configuration.SettingsSerializeAs.String
- uid: System.Configuration.SettingsSerializeAs.Xml
  parent: System.Configuration.SettingsSerializeAs
  isExternal: false
  name: Xml
  nameWithType: SettingsSerializeAs.Xml
  fullName: System.Configuration.SettingsSerializeAs.Xml
