### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.UserPrincipalNameElement
  id: UserPrincipalNameElement
  children:
  - System.ServiceModel.Configuration.UserPrincipalNameElement.#ctor
  - System.ServiceModel.Configuration.UserPrincipalNameElement.Properties
  - System.ServiceModel.Configuration.UserPrincipalNameElement.Value
  langs:
  - csharp
  name: UserPrincipalNameElement
  nameWithType: UserPrincipalNameElement
  fullName: System.ServiceModel.Configuration.UserPrincipalNameElement
  type: Class
  summary: "Represents a configuration element that specifies a user principal name. This class cannot be inherited."
  remarks: "A user principal name is the logon name type of a user on a network. The user principal name consists of the user object name used in Active Directory, followed by the symbol (@) and then, typically, the Domain Name System parent domain. For example, Jeff in the Fabrikam.com domain tree might have the user principal name [jeff@fabrikam.com](mailto:jeffsmith@fabrikam.com)."
  syntax:
    content: 'public sealed class UserPrincipalNameElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.UserPrincipalNameElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.UserPrincipalNameElement
  langs:
  - csharp
  name: UserPrincipalNameElement()
  nameWithType: UserPrincipalNameElement.UserPrincipalNameElement()
  fullName: System.ServiceModel.Configuration.UserPrincipalNameElement.UserPrincipalNameElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.UserPrincipalNameElement&quot;></see> class."
  syntax:
    content: public UserPrincipalNameElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.UserPrincipalNameElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.UserPrincipalNameElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.UserPrincipalNameElement
  langs:
  - csharp
  name: Properties
  nameWithType: UserPrincipalNameElement.Properties
  fullName: System.ServiceModel.Configuration.UserPrincipalNameElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.UserPrincipalNameElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.UserPrincipalNameElement.Value
  id: Value
  parent: System.ServiceModel.Configuration.UserPrincipalNameElement
  langs:
  - csharp
  name: Value
  nameWithType: UserPrincipalNameElement.Value
  fullName: System.ServiceModel.Configuration.UserPrincipalNameElement.Value
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets the value set for this configuration element."
  syntax:
    content: public string Value { get; set; }
    return:
      type: System.String
      description: "A string that specifies a user account name (sometimes referred to as the user logon name) and a domain name identifying the domain in which the user account is located."
  overload: System.ServiceModel.Configuration.UserPrincipalNameElement.Value*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.UserPrincipalNameElement.#ctor
  parent: System.ServiceModel.Configuration.UserPrincipalNameElement
  isExternal: false
  name: UserPrincipalNameElement()
  nameWithType: UserPrincipalNameElement.UserPrincipalNameElement()
  fullName: System.ServiceModel.Configuration.UserPrincipalNameElement.UserPrincipalNameElement()
- uid: System.ServiceModel.Configuration.UserPrincipalNameElement.Properties
  parent: System.ServiceModel.Configuration.UserPrincipalNameElement
  isExternal: false
  name: Properties
  nameWithType: UserPrincipalNameElement.Properties
  fullName: System.ServiceModel.Configuration.UserPrincipalNameElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.UserPrincipalNameElement.Value
  parent: System.ServiceModel.Configuration.UserPrincipalNameElement
  isExternal: false
  name: Value
  nameWithType: UserPrincipalNameElement.Value
  fullName: System.ServiceModel.Configuration.UserPrincipalNameElement.Value
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.UserPrincipalNameElement.#ctor*
  parent: System.ServiceModel.Configuration.UserPrincipalNameElement
  isExternal: false
  name: UserPrincipalNameElement
  nameWithType: UserPrincipalNameElement.UserPrincipalNameElement
- uid: System.ServiceModel.Configuration.UserPrincipalNameElement.Properties*
  parent: System.ServiceModel.Configuration.UserPrincipalNameElement
  isExternal: false
  name: Properties
  nameWithType: UserPrincipalNameElement.Properties
- uid: System.ServiceModel.Configuration.UserPrincipalNameElement.Value*
  parent: System.ServiceModel.Configuration.UserPrincipalNameElement
  isExternal: false
  name: Value
  nameWithType: UserPrincipalNameElement.Value
