### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  id: ContractTypeNameElement
  children:
  - System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.#ctor
  - System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.#ctor(System.String,System.String)
  - System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Name
  - System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Namespace
  - System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Properties
  langs:
  - csharp
  name: ContractTypeNameElement
  nameWithType: ContractTypeNameElement
  fullName: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  type: Class
  summary: "Represents a workflow element that identifies by name the workflow service contract being searched for."
  remarks: "A contract type name is a property that refers to the set of criteria typically used when searching for a service. The set of criteria, or contract, is a collection of operations that specify what the endpoint communicates to the outside world. Each operation is a message exchange. For example, a request message and an associated reply message form a request/reply message exchange."
  syntax:
    content: 'public sealed class ContractTypeNameElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  langs:
  - csharp
  name: ContractTypeNameElement()
  nameWithType: ContractTypeNameElement.ContractTypeNameElement()
  fullName: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.ContractTypeNameElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Creates a new instance of the <see cref=&quot;T:System.ServiceModel.Discovery.Configuration.ContractTypeNameElement&quot;></see> class."
  syntax:
    content: public ContractTypeNameElement ();
    parameters: []
  overload: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  langs:
  - csharp
  name: ContractTypeNameElement(String,String)
  nameWithType: ContractTypeNameElement.ContractTypeNameElement(String,String)
  fullName: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.ContractTypeNameElement(String,String)
  type: Constructor
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Creates a new instance of the <see cref=&quot;T:System.ServiceModel.Discovery.Configuration.ContractTypeNameElement&quot;></see> class using the specified contract type name and namespace name."
  syntax:
    content: public ContractTypeNameElement (string name, string ns);
    parameters:
    - id: name
      type: System.String
      description: "The type name of a workflow service contract."
    - id: ns
      type: System.String
      description: "The namespace name of the workflow service contract."
  overload: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Name
  id: Name
  parent: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  langs:
  - csharp
  name: Name
  nameWithType: ContractTypeNameElement.Name
  fullName: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Name
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Gets or sets the name of the contract type."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "An alphanumeric name."
  overload: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Name*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Namespace
  id: Namespace
  parent: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  langs:
  - csharp
  name: Namespace
  nameWithType: ContractTypeNameElement.Namespace
  fullName: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Namespace
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Gets or sets the namespace of the contract type."
  syntax:
    content: public string Namespace { get; set; }
    return:
      type: System.String
      description: "An alphanumeric name."
  overload: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Namespace*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Properties
  id: Properties
  parent: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  langs:
  - csharp
  name: Properties
  nameWithType: ContractTypeNameElement.Properties
  fullName: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.#ctor
  parent: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  isExternal: false
  name: ContractTypeNameElement()
  nameWithType: ContractTypeNameElement.ContractTypeNameElement()
  fullName: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.ContractTypeNameElement()
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.#ctor(System.String,System.String)
  parent: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  isExternal: false
  name: ContractTypeNameElement(String,String)
  nameWithType: ContractTypeNameElement.ContractTypeNameElement(String,String)
  fullName: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.ContractTypeNameElement(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Name
  parent: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  isExternal: false
  name: Name
  nameWithType: ContractTypeNameElement.Name
  fullName: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Name
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Namespace
  parent: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  isExternal: false
  name: Namespace
  nameWithType: ContractTypeNameElement.Namespace
  fullName: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Namespace
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Properties
  parent: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  isExternal: false
  name: Properties
  nameWithType: ContractTypeNameElement.Properties
  fullName: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.#ctor*
  parent: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  isExternal: false
  name: ContractTypeNameElement
  nameWithType: ContractTypeNameElement.ContractTypeNameElement
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Name*
  parent: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  isExternal: false
  name: Name
  nameWithType: ContractTypeNameElement.Name
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Namespace*
  parent: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  isExternal: false
  name: Namespace
  nameWithType: ContractTypeNameElement.Namespace
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement.Properties*
  parent: System.ServiceModel.Discovery.Configuration.ContractTypeNameElement
  isExternal: false
  name: Properties
  nameWithType: ContractTypeNameElement.Properties
