### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.WSFederationHttpSecurityElement
  id: WSFederationHttpSecurityElement
  children:
  - System.ServiceModel.Configuration.WSFederationHttpSecurityElement.#ctor
  - System.ServiceModel.Configuration.WSFederationHttpSecurityElement.Message
  - System.ServiceModel.Configuration.WSFederationHttpSecurityElement.Mode
  - System.ServiceModel.Configuration.WSFederationHttpSecurityElement.Properties
  langs:
  - csharp
  name: WSFederationHttpSecurityElement
  nameWithType: WSFederationHttpSecurityElement
  fullName: System.ServiceModel.Configuration.WSFederationHttpSecurityElement
  type: Class
  summary: "Represents an XML element that defines the security settings for a wsFederationHttp binding. This class cannot be inherited."
  syntax:
    content: 'public sealed class WSFederationHttpSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.WSFederationHttpSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.WSFederationHttpSecurityElement
  langs:
  - csharp
  name: WSFederationHttpSecurityElement()
  nameWithType: WSFederationHttpSecurityElement.WSFederationHttpSecurityElement()
  fullName: System.ServiceModel.Configuration.WSFederationHttpSecurityElement.WSFederationHttpSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.WSFederationHttpSecurityElement&quot;></see> class."
  syntax:
    content: public WSFederationHttpSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.WSFederationHttpSecurityElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.WSFederationHttpSecurityElement.Message
  id: Message
  parent: System.ServiceModel.Configuration.WSFederationHttpSecurityElement
  langs:
  - csharp
  name: Message
  nameWithType: WSFederationHttpSecurityElement.Message
  fullName: System.ServiceModel.Configuration.WSFederationHttpSecurityElement.Message
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets the security settings for the message."
  syntax:
    content: public System.ServiceModel.Configuration.FederatedMessageSecurityOverHttpElement Message { get; }
    return:
      type: System.ServiceModel.Configuration.FederatedMessageSecurityOverHttpElement
      description: "A <see cref=&quot;T:System.ServiceModel.Configuration.FederatedMessageSecurityOverHttpElement&quot;></see> that specifies the security settings for the message."
  overload: System.ServiceModel.Configuration.WSFederationHttpSecurityElement.Message*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.WSFederationHttpSecurityElement.Mode
  id: Mode
  parent: System.ServiceModel.Configuration.WSFederationHttpSecurityElement
  langs:
  - csharp
  name: Mode
  nameWithType: WSFederationHttpSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.WSFederationHttpSecurityElement.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets the type of security that is applied to this binding."
  syntax:
    content: public System.ServiceModel.WSFederationHttpSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.WSFederationHttpSecurityMode
      description: "A <see cref=&quot;T:System.ServiceModel.WSFederationHttpSecurityMode&quot;></see> that specifies the type of security that is applied to this binding. The default value is &lt;xref:System.ServiceModel.Configuration.WSFederationHttpSecurityElement.Message%2A&gt;."
  overload: System.ServiceModel.Configuration.WSFederationHttpSecurityElement.Mode*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.WSFederationHttpSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.WSFederationHttpSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: WSFederationHttpSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.WSFederationHttpSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.WSFederationHttpSecurityElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.WSFederationHttpSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.WSFederationHttpSecurityElement
  isExternal: false
  name: WSFederationHttpSecurityElement()
  nameWithType: WSFederationHttpSecurityElement.WSFederationHttpSecurityElement()
  fullName: System.ServiceModel.Configuration.WSFederationHttpSecurityElement.WSFederationHttpSecurityElement()
- uid: System.ServiceModel.Configuration.WSFederationHttpSecurityElement.Message
  parent: System.ServiceModel.Configuration.WSFederationHttpSecurityElement
  isExternal: false
  name: Message
  nameWithType: WSFederationHttpSecurityElement.Message
  fullName: System.ServiceModel.Configuration.WSFederationHttpSecurityElement.Message
- uid: System.ServiceModel.Configuration.FederatedMessageSecurityOverHttpElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: FederatedMessageSecurityOverHttpElement
  nameWithType: FederatedMessageSecurityOverHttpElement
  fullName: System.ServiceModel.Configuration.FederatedMessageSecurityOverHttpElement
- uid: System.ServiceModel.Configuration.WSFederationHttpSecurityElement.Mode
  parent: System.ServiceModel.Configuration.WSFederationHttpSecurityElement
  isExternal: false
  name: Mode
  nameWithType: WSFederationHttpSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.WSFederationHttpSecurityElement.Mode
- uid: System.ServiceModel.WSFederationHttpSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: WSFederationHttpSecurityMode
  nameWithType: WSFederationHttpSecurityMode
  fullName: System.ServiceModel.WSFederationHttpSecurityMode
- uid: System.ServiceModel.Configuration.WSFederationHttpSecurityElement.Properties
  parent: System.ServiceModel.Configuration.WSFederationHttpSecurityElement
  isExternal: false
  name: Properties
  nameWithType: WSFederationHttpSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.WSFederationHttpSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.WSFederationHttpSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.WSFederationHttpSecurityElement
  isExternal: false
  name: WSFederationHttpSecurityElement
  nameWithType: WSFederationHttpSecurityElement.WSFederationHttpSecurityElement
- uid: System.ServiceModel.Configuration.WSFederationHttpSecurityElement.Message*
  parent: System.ServiceModel.Configuration.WSFederationHttpSecurityElement
  isExternal: false
  name: Message
  nameWithType: WSFederationHttpSecurityElement.Message
- uid: System.ServiceModel.Configuration.WSFederationHttpSecurityElement.Mode*
  parent: System.ServiceModel.Configuration.WSFederationHttpSecurityElement
  isExternal: false
  name: Mode
  nameWithType: WSFederationHttpSecurityElement.Mode
- uid: System.ServiceModel.Configuration.WSFederationHttpSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.WSFederationHttpSecurityElement
  isExternal: false
  name: Properties
  nameWithType: WSFederationHttpSecurityElement.Properties
