### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ServicesSection
  id: ServicesSection
  children:
  - System.ServiceModel.Configuration.ServicesSection.#ctor
  - System.ServiceModel.Configuration.ServicesSection.PostDeserialize
  - System.ServiceModel.Configuration.ServicesSection.Properties
  - System.ServiceModel.Configuration.ServicesSection.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServicesSection.Services
  langs:
  - csharp
  name: ServicesSection
  nameWithType: ServicesSection
  fullName: System.ServiceModel.Configuration.ServicesSection
  type: Class
  summary: "Represents the configuration section that contains services."
  remarks: "Services are defined in the services section of the configuration file. Each service has its own service configuration section."
  syntax:
    content: 'public sealed class ServicesSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ServicesSection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ServicesSection
  langs:
  - csharp
  name: ServicesSection()
  nameWithType: ServicesSection.ServicesSection()
  fullName: System.ServiceModel.Configuration.ServicesSection.ServicesSection()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.ServicesSection&quot;></see> class."
  syntax:
    content: public ServicesSection ();
    parameters: []
  overload: System.ServiceModel.Configuration.ServicesSection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ServicesSection.PostDeserialize
  id: PostDeserialize
  parent: System.ServiceModel.Configuration.ServicesSection
  langs:
  - csharp
  name: PostDeserialize()
  nameWithType: ServicesSection.PostDeserialize()
  fullName: System.ServiceModel.Configuration.ServicesSection.PostDeserialize()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override void PostDeserialize ();
    parameters: []
  overload: System.ServiceModel.Configuration.ServicesSection.PostDeserialize*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ServicesSection.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ServicesSection
  langs:
  - csharp
  name: Properties
  nameWithType: ServicesSection.Properties
  fullName: System.ServiceModel.Configuration.ServicesSection.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.ServicesSection.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ServicesSection.Reset(System.Configuration.ConfigurationElement)
  id: Reset(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Configuration.ServicesSection
  langs:
  - csharp
  name: Reset(ConfigurationElement)
  nameWithType: ServicesSection.Reset(ConfigurationElement)
  fullName: System.ServiceModel.Configuration.ServicesSection.Reset(ConfigurationElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override void Reset (System.Configuration.ConfigurationElement parentElement);
    parameters:
    - id: parentElement
      type: System.Configuration.ConfigurationElement
      description: "To be added."
  overload: System.ServiceModel.Configuration.ServicesSection.Reset*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ServicesSection.Services
  id: Services
  parent: System.ServiceModel.Configuration.ServicesSection
  langs:
  - csharp
  name: Services
  nameWithType: ServicesSection.Services
  fullName: System.ServiceModel.Configuration.ServicesSection.Services
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets all the services configured in this section."
  syntax:
    content: public System.ServiceModel.Configuration.ServiceElementCollection Services { get; }
    return:
      type: System.ServiceModel.Configuration.ServiceElementCollection
      description: "A <see cref=&quot;T:System.ServiceModel.Configuration.ServiceElementCollection&quot;></see> that contains all the services configured in this section."
  overload: System.ServiceModel.Configuration.ServicesSection.Services*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.ServiceModel.Configuration.ServicesSection.#ctor
  parent: System.ServiceModel.Configuration.ServicesSection
  isExternal: false
  name: ServicesSection()
  nameWithType: ServicesSection.ServicesSection()
  fullName: System.ServiceModel.Configuration.ServicesSection.ServicesSection()
- uid: System.ServiceModel.Configuration.ServicesSection.PostDeserialize
  parent: System.ServiceModel.Configuration.ServicesSection
  isExternal: false
  name: PostDeserialize()
  nameWithType: ServicesSection.PostDeserialize()
  fullName: System.ServiceModel.Configuration.ServicesSection.PostDeserialize()
- uid: System.ServiceModel.Configuration.ServicesSection.Properties
  parent: System.ServiceModel.Configuration.ServicesSection
  isExternal: false
  name: Properties
  nameWithType: ServicesSection.Properties
  fullName: System.ServiceModel.Configuration.ServicesSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ServicesSection.Reset(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Configuration.ServicesSection
  isExternal: false
  name: Reset(ConfigurationElement)
  nameWithType: ServicesSection.Reset(ConfigurationElement)
  fullName: System.ServiceModel.Configuration.ServicesSection.Reset(ConfigurationElement)
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.ServicesSection.Services
  parent: System.ServiceModel.Configuration.ServicesSection
  isExternal: false
  name: Services
  nameWithType: ServicesSection.Services
  fullName: System.ServiceModel.Configuration.ServicesSection.Services
- uid: System.ServiceModel.Configuration.ServiceElementCollection
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceElementCollection
  nameWithType: ServiceElementCollection
  fullName: System.ServiceModel.Configuration.ServiceElementCollection
- uid: System.ServiceModel.Configuration.ServicesSection.#ctor*
  parent: System.ServiceModel.Configuration.ServicesSection
  isExternal: false
  name: ServicesSection
  nameWithType: ServicesSection.ServicesSection
- uid: System.ServiceModel.Configuration.ServicesSection.PostDeserialize*
  parent: System.ServiceModel.Configuration.ServicesSection
  isExternal: false
  name: PostDeserialize
  nameWithType: ServicesSection.PostDeserialize
- uid: System.ServiceModel.Configuration.ServicesSection.Properties*
  parent: System.ServiceModel.Configuration.ServicesSection
  isExternal: false
  name: Properties
  nameWithType: ServicesSection.Properties
- uid: System.ServiceModel.Configuration.ServicesSection.Reset*
  parent: System.ServiceModel.Configuration.ServicesSection
  isExternal: false
  name: Reset
  nameWithType: ServicesSection.Reset
- uid: System.ServiceModel.Configuration.ServicesSection.Services*
  parent: System.ServiceModel.Configuration.ServicesSection
  isExternal: false
  name: Services
  nameWithType: ServicesSection.Services
