### YamlMime:ManagedReference
items:
- uid: System.Configuration.WhiteSpaceTrimStringConverter
  id: WhiteSpaceTrimStringConverter
  children:
  - System.Configuration.WhiteSpaceTrimStringConverter.#ctor
  - System.Configuration.WhiteSpaceTrimStringConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.Configuration.WhiteSpaceTrimStringConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  name: WhiteSpaceTrimStringConverter
  nameWithType: WhiteSpaceTrimStringConverter
  fullName: System.Configuration.WhiteSpaceTrimStringConverter
  type: Class
  summary: "Converts a string to its canonical format."
  remarks: "This WhiteSpaceTrimStringConverter object converts between a configuration string value and its canonical representation. Canonical representation means that all white spaces are trimmed from the beginning and end of a string value."
  example:
  - "The following code example shows how to apply WhiteSpaceTrimStringConverter to a custom string property `FileName`.  \n  \n [!code-cs[System.Configuration.ConfigurationConvertersCustomSection#0](~/add/codesnippet/CSharp/t-system.configuration.w_1.cs)]\n [!code-vb[System.Configuration.ConfigurationConvertersCustomSection#0](~/add/codesnippet/VisualBasic/t-system.configuration.w_1.vb)]  \n  \n The following is a configuration excerpt used by the previous example.  \n  \n```  \n<?xml version=\"1.0\" encoding=\"utf-8\"?>  \n<configuration>  \n  \n  <configSections>  \n    <section name=\"CustomSection\"   \n      type=\"Samples.AspNet.CustomSection,   \n      ConfigurationConverters,   \n      Version=1.0.0.0, Culture=neutral,   \n      PublicKeyToken=null\"   \n      allowDefinition=\"Everywhere\"   \n      allowExeDefinition=\"MachineToApplication\"   \n      restartOnExternalChanges=\"true\" />  \n  </configSections>  \n  \n  <CustomSection fileName=\"default.txt\" maxIdleTime=\"90\" timeDelay=\"infinite\" cdStr=\"str0, str1\" permission=\"Read\" maxUsers=\"Infinite\"/>  \n  \n</configuration>  \n```"
  syntax:
    content: 'public sealed class WhiteSpaceTrimStringConverter : System.Configuration.ConfigurationConverterBase'
  inheritance:
  - System.Object
  - System.ComponentModel.TypeConverter
  - System.Configuration.ConfigurationConverterBase
  implements: []
  inheritedMembers:
  - System.ComponentModel.TypeConverter.CanConvertFrom(System.Type)
  - System.ComponentModel.TypeConverter.CanConvertTo(System.Type)
  - System.ComponentModel.TypeConverter.ConvertFrom(System.Object)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.String)
  - System.ComponentModel.TypeConverter.ConvertTo(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.Object)
  - System.ComponentModel.TypeConverter.CreateInstance(System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.CreateInstance(System.ComponentModel.ITypeDescriptorContext,System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.GetConvertFromException(System.Object)
  - System.ComponentModel.TypeConverter.GetConvertToException(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object,System.Attribute[])
  - System.ComponentModel.TypeConverter.GetProperties(System.Object)
  - System.ComponentModel.TypeConverter.GetPropertiesSupported
  - System.ComponentModel.TypeConverter.GetPropertiesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValues
  - System.ComponentModel.TypeConverter.GetStandardValues(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.IsValid(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.IsValid(System.Object)
  - System.ComponentModel.TypeConverter.SortProperties(System.ComponentModel.PropertyDescriptorCollection,System.String[])
  - System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.WhiteSpaceTrimStringConverter.#ctor
  id: '#ctor'
  parent: System.Configuration.WhiteSpaceTrimStringConverter
  langs:
  - csharp
  name: WhiteSpaceTrimStringConverter()
  nameWithType: WhiteSpaceTrimStringConverter.WhiteSpaceTrimStringConverter()
  fullName: System.Configuration.WhiteSpaceTrimStringConverter.WhiteSpaceTrimStringConverter()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.WhiteSpaceTrimStringConverter&quot;></see> class."
  remarks: "Normally, you use the converter types provided by the system. The only time you need to use the WhiteSpaceTrimStringConverter constructor is when you create your own conversion type."
  syntax:
    content: public WhiteSpaceTrimStringConverter ();
    parameters: []
  overload: System.Configuration.WhiteSpaceTrimStringConverter.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.WhiteSpaceTrimStringConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.WhiteSpaceTrimStringConverter
  langs:
  - csharp
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: WhiteSpaceTrimStringConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.WhiteSpaceTrimStringConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Converts a &lt;xref:System.String&gt; to canonical form."
  remarks: "The system uses the ConvertFrom method when reading from a configuration file to convert a <xref:System.String> value to its canonical form."
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object data);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "The  object used for type conversions."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "The <xref:System.Globalization.CultureInfo> object used during conversion."
    - id: data
      type: System.Object
      description: "The <xref:System.String> object to convert."
    return:
      type: System.Object
      description: "To be added."
  overload: System.Configuration.WhiteSpaceTrimStringConverter.ConvertFrom*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.WhiteSpaceTrimStringConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.WhiteSpaceTrimStringConverter
  langs:
  - csharp
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: WhiteSpaceTrimStringConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.WhiteSpaceTrimStringConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Converts a &lt;xref:System.String&gt; to canonical form."
  remarks: "The system uses the ConvertTo method when writing to a configuration file to convert a <xref:System.String> value to its canonical form."
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object value, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "The  object used for type conversions."
    - id: ci
      type: System.Globalization.CultureInfo
      description: "The <xref:System.Globalization.CultureInfo> object used during conversion."
    - id: value
      type: System.Object
      description: "The value to convert to."
    - id: type
      type: System.Type
      description: "The type to convert to."
    return:
      type: System.Object
      description: "To be added."
  overload: System.Configuration.WhiteSpaceTrimStringConverter.ConvertTo*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationConverterBase
  isExternal: false
  name: System.Configuration.ConfigurationConverterBase
- uid: System.Configuration.WhiteSpaceTrimStringConverter.#ctor
  parent: System.Configuration.WhiteSpaceTrimStringConverter
  isExternal: false
  name: WhiteSpaceTrimStringConverter()
  nameWithType: WhiteSpaceTrimStringConverter.WhiteSpaceTrimStringConverter()
  fullName: System.Configuration.WhiteSpaceTrimStringConverter.WhiteSpaceTrimStringConverter()
- uid: System.Configuration.WhiteSpaceTrimStringConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.WhiteSpaceTrimStringConverter
  isExternal: false
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: WhiteSpaceTrimStringConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.WhiteSpaceTrimStringConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: false
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: true
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Configuration.WhiteSpaceTrimStringConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.WhiteSpaceTrimStringConverter
  isExternal: false
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: WhiteSpaceTrimStringConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.WhiteSpaceTrimStringConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.WhiteSpaceTrimStringConverter.#ctor*
  parent: System.Configuration.WhiteSpaceTrimStringConverter
  isExternal: false
  name: WhiteSpaceTrimStringConverter
  nameWithType: WhiteSpaceTrimStringConverter.WhiteSpaceTrimStringConverter
- uid: System.Configuration.WhiteSpaceTrimStringConverter.ConvertFrom*
  parent: System.Configuration.WhiteSpaceTrimStringConverter
  isExternal: false
  name: ConvertFrom
  nameWithType: WhiteSpaceTrimStringConverter.ConvertFrom
- uid: System.Configuration.WhiteSpaceTrimStringConverter.ConvertTo*
  parent: System.Configuration.WhiteSpaceTrimStringConverter
  isExternal: false
  name: ConvertTo
  nameWithType: WhiteSpaceTrimStringConverter.ConvertTo
