### YamlMime:ManagedReference
items:
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
  id: ExtendedProtectionPolicyElement
  children:
  - System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.#ctor
  - System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.BuildPolicy
  - System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.CustomServiceNames
  - System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.PolicyEnforcement
  - System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.Properties
  - System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.ProtectionScenario
  langs:
  - csharp
  name: ExtendedProtectionPolicyElement
  nameWithType: ExtendedProtectionPolicyElement
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
  type: Class
  summary: "The ExtendedProtectionPolicyElement class represents a configuration element for an <see cref=&quot;T:System.Security.Authentication.ExtendedProtection.ExtendedProtectionPolicy&quot;></see>."
  remarks: "An <xref:System.Security.Authentication.ExtendedProtection.ExtendedProtectionPolicy> can be configured for server applications using standard configuration files."
  syntax:
    content: 'public sealed class ExtendedProtectionPolicyElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.#ctor
  id: '#ctor'
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
  langs:
  - csharp
  name: ExtendedProtectionPolicyElement()
  nameWithType: ExtendedProtectionPolicyElement.ExtendedProtectionPolicyElement()
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.ExtendedProtectionPolicyElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Security.Authentication.ExtendedProtection.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement&quot;></see> class."
  remarks: "When this constructor is used to initialize a new instance of the <xref:System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement> class, the <xref:System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.PolicyEnforcement%2A> property is set to <xref:System.Security.Authentication.ExtendedProtection.PolicyEnforcement>, the <xref:System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.ProtectionScenario%2A> property is set to <xref:System.Security.Authentication.ExtendedProtection.ProtectionScenario>, and the <xref:System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElementCollection> property is set to `null`.       The properties on the <xref:System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement> class instance should be set to appropriate values for the application before calling the <xref:System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.BuildPolicy%2A> method."
  syntax:
    content: public ExtendedProtectionPolicyElement ();
    parameters: []
  overload: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.BuildPolicy
  id: BuildPolicy
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
  langs:
  - csharp
  name: BuildPolicy()
  nameWithType: ExtendedProtectionPolicyElement.BuildPolicy()
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.BuildPolicy()
  type: Method
  assemblies:
  - System
  namespace: System.Security.Authentication.ExtendedProtection.Configuration
  summary: "The BuildPolicy method builds a new <see cref=&quot;T:System.Security.Authentication.ExtendedProtection.ExtendedProtectionPolicy&quot;></see> instance based on the properties set on the <see cref=&quot;T:System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement&quot;></see> class."
  remarks: "The properties on the <xref:System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement> class instance must be set before calling the BuildPolicy method."
  syntax:
    content: public System.Security.Authentication.ExtendedProtection.ExtendedProtectionPolicy BuildPolicy ();
    parameters: []
    return:
      type: System.Security.Authentication.ExtendedProtection.ExtendedProtectionPolicy
      description: "To be added."
  overload: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.BuildPolicy*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.CustomServiceNames
  id: CustomServiceNames
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
  langs:
  - csharp
  name: CustomServiceNames
  nameWithType: ExtendedProtectionPolicyElement.CustomServiceNames
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.CustomServiceNames
  type: Property
  assemblies:
  - System
  namespace: System.Security.Authentication.ExtendedProtection.Configuration
  summary: "Gets or sets the custom Service Provider Name (SPN) list used to match against a client&quot;s SPN for this configuration policy element."
  syntax:
    content: public System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElementCollection CustomServiceNames { get; }
    return:
      type: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElementCollection
      description: "Returns a <see cref=&quot;T:System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElementCollection&quot;></see> that includes the custom SPN list used to match against a client&quot;s SPN."
  overload: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.CustomServiceNames*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.PolicyEnforcement
  id: PolicyEnforcement
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
  langs:
  - csharp
  name: PolicyEnforcement
  nameWithType: ExtendedProtectionPolicyElement.PolicyEnforcement
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.PolicyEnforcement
  type: Property
  assemblies:
  - System
  namespace: System.Security.Authentication.ExtendedProtection.Configuration
  summary: "Gets or sets the policy enforcement value for this configuration policy element."
  remarks: "This value is an <xref:System.Security.Authentication.ExtendedProtection.PolicyEnforcement> value."
  syntax:
    content: public System.Security.Authentication.ExtendedProtection.PolicyEnforcement PolicyEnforcement { get; set; }
    return:
      type: System.Security.Authentication.ExtendedProtection.PolicyEnforcement
      description: "Returns a <see cref=&quot;T:System.Security.Authentication.ExtendedProtection.PolicyEnforcement&quot;></see> value that indicates when the extended protection policy should be enforced."
  overload: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.PolicyEnforcement*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.Properties
  id: Properties
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
  langs:
  - csharp
  name: Properties
  nameWithType: ExtendedProtectionPolicyElement.Properties
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Security.Authentication.ExtendedProtection.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.ProtectionScenario
  id: ProtectionScenario
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
  langs:
  - csharp
  name: ProtectionScenario
  nameWithType: ExtendedProtectionPolicyElement.ProtectionScenario
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.ProtectionScenario
  type: Property
  assemblies:
  - System
  namespace: System.Security.Authentication.ExtendedProtection.Configuration
  summary: "Gets or sets the kind of protection enforced by the extended protection policy for this configuration policy element."
  syntax:
    content: public System.Security.Authentication.ExtendedProtection.ProtectionScenario ProtectionScenario { get; set; }
    return:
      type: System.Security.Authentication.ExtendedProtection.ProtectionScenario
      description: "A <see cref=&quot;T:System.Security.Authentication.ExtendedProtection.ProtectionScenario&quot;></see> value that indicates the kind of protection enforced by the policy."
  overload: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.ProtectionScenario*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.#ctor
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
  isExternal: false
  name: ExtendedProtectionPolicyElement()
  nameWithType: ExtendedProtectionPolicyElement.ExtendedProtectionPolicyElement()
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.ExtendedProtectionPolicyElement()
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.BuildPolicy
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
  isExternal: false
  name: BuildPolicy()
  nameWithType: ExtendedProtectionPolicyElement.BuildPolicy()
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.BuildPolicy()
- uid: System.Security.Authentication.ExtendedProtection.ExtendedProtectionPolicy
  parent: System.Security.Authentication.ExtendedProtection
  isExternal: false
  name: ExtendedProtectionPolicy
  nameWithType: ExtendedProtectionPolicy
  fullName: System.Security.Authentication.ExtendedProtection.ExtendedProtectionPolicy
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.CustomServiceNames
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
  isExternal: false
  name: CustomServiceNames
  nameWithType: ExtendedProtectionPolicyElement.CustomServiceNames
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.CustomServiceNames
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElementCollection
  parent: System.Security.Authentication.ExtendedProtection.Configuration
  isExternal: false
  name: ServiceNameElementCollection
  nameWithType: ServiceNameElementCollection
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ServiceNameElementCollection
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.PolicyEnforcement
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
  isExternal: false
  name: PolicyEnforcement
  nameWithType: ExtendedProtectionPolicyElement.PolicyEnforcement
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.PolicyEnforcement
- uid: System.Security.Authentication.ExtendedProtection.PolicyEnforcement
  parent: System.Security.Authentication.ExtendedProtection
  isExternal: false
  name: PolicyEnforcement
  nameWithType: PolicyEnforcement
  fullName: System.Security.Authentication.ExtendedProtection.PolicyEnforcement
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.Properties
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
  isExternal: false
  name: Properties
  nameWithType: ExtendedProtectionPolicyElement.Properties
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.ProtectionScenario
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
  isExternal: false
  name: ProtectionScenario
  nameWithType: ExtendedProtectionPolicyElement.ProtectionScenario
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.ProtectionScenario
- uid: System.Security.Authentication.ExtendedProtection.ProtectionScenario
  parent: System.Security.Authentication.ExtendedProtection
  isExternal: false
  name: ProtectionScenario
  nameWithType: ProtectionScenario
  fullName: System.Security.Authentication.ExtendedProtection.ProtectionScenario
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.#ctor*
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
  isExternal: false
  name: ExtendedProtectionPolicyElement
  nameWithType: ExtendedProtectionPolicyElement.ExtendedProtectionPolicyElement
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.BuildPolicy*
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
  isExternal: false
  name: BuildPolicy
  nameWithType: ExtendedProtectionPolicyElement.BuildPolicy
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.CustomServiceNames*
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
  isExternal: false
  name: CustomServiceNames
  nameWithType: ExtendedProtectionPolicyElement.CustomServiceNames
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.PolicyEnforcement*
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
  isExternal: false
  name: PolicyEnforcement
  nameWithType: ExtendedProtectionPolicyElement.PolicyEnforcement
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.Properties*
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
  isExternal: false
  name: Properties
  nameWithType: ExtendedProtectionPolicyElement.Properties
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement.ProtectionScenario*
  parent: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
  isExternal: false
  name: ProtectionScenario
  nameWithType: ExtendedProtectionPolicyElement.ProtectionScenario
