### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  id: ServiceModelConfigurationElement
  children:
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.#ctor
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  langs:
  - csharp
  name: ServiceModelConfigurationElement
  nameWithType: ServiceModelConfigurationElement
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  type: Class
  summary: "Represents a service model configuration element."
  syntax:
    content: 'public abstract class ServiceModelConfigurationElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  langs:
  - csharp
  name: ServiceModelConfigurationElement()
  nameWithType: ServiceModelConfigurationElement.ServiceModelConfigurationElement()
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElement.ServiceModelConfigurationElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.ServiceModelConfigurationElement&quot;></see> class."
  syntax:
    content: protected ServiceModelConfigurationElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.ServiceModelConfigurationElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  id: SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  parent: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  langs:
  - csharp
  name: SetPropertyValueIfNotDefaultValue(String,T)
  nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(String,T)
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(String,T)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected void SetPropertyValueIfNotDefaultValue<T> (string propertyName, T value);
    parameters:
    - id: propertyName
      type: System.String
      description: "To be added."
    - id: value
      type: T
      description: "To be added."
  overload: System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement.#ctor
  parent: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: ServiceModelConfigurationElement()
  nameWithType: ServiceModelConfigurationElement.ServiceModelConfigurationElement()
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElement.ServiceModelConfigurationElement()
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  parent: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: SetPropertyValueIfNotDefaultValue(String,T)
  nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(String,T)
  fullName: System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue(String,T)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: T
  isExternal: true
  name: T
  nameWithType: T
  fullName: T
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement.#ctor*
  parent: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: ServiceModelConfigurationElement
  nameWithType: ServiceModelConfigurationElement.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>*
  parent: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: SetPropertyValueIfNotDefaultValue<T>
  nameWithType: ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue<T>
