### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.OutputCacheSettingsSection
  id: OutputCacheSettingsSection
  children:
  - System.Web.Configuration.OutputCacheSettingsSection.#ctor
  - System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles
  - System.Web.Configuration.OutputCacheSettingsSection.Properties
  langs:
  - csharp
  name: OutputCacheSettingsSection
  nameWithType: OutputCacheSettingsSection
  fullName: System.Web.Configuration.OutputCacheSettingsSection
  type: Class
  summary: "Configures the output cache settings for application pages . This class cannot be inherited."
  remarks: "The OutputCacheSettingsSection class allows you to programmatically access and modify the `outputCacheSettings` element of the `caching` section in a configuration file. The output cache settings define the dependencies (the relationships between items stored in the cache and files, cache keys, or <xref:System.Web.Caching.CacheDependency> objects) that are used in output caching, for instance, by the [@ OutputCache](http://msdn.microsoft.com/en-us/28a9e101-fb44-4198-9cb6-b8a52312fec2) directive or by the <xref:System.Web.Configuration.OutputCacheProfile>.      > [!NOTE] >  The OutputCacheSettingsSection can write information into the related section of the configuration file according to the restrictions defined by the section property <xref:System.Configuration.SectionInformation.AllowDefinition%2A> whose value is <xref:System.Configuration.ConfigurationAllowDefinition>. Any attempt to write in a configuration file at a level not allowed in the hierarchy will result in an error message generated by the parser. However, you can use this class to read configuration information at any level in the hierarchy."
  example:
  - "The following code example shows how to obtain the OutputCacheSettingsSection object from the configuration file of an existing Web application.  \n  \n [!code-cs[System.Web.Configuration.OutputCacheSettingsSection#1](~/add/codesnippet/CSharp/t-system.web.configurati_9_1.cs)]\n [!code-vb[System.Web.Configuration.OutputCacheSettingsSection#1](~/add/codesnippet/VisualBasic/t-system.web.configurati_9_1.vb)]"
  syntax:
    content: 'public sealed class OutputCacheSettingsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.OutputCacheSettingsSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.OutputCacheSettingsSection
  langs:
  - csharp
  name: OutputCacheSettingsSection()
  nameWithType: OutputCacheSettingsSection.OutputCacheSettingsSection()
  fullName: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheSettingsSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Web.Configuration.OutputCacheSettingsSection&quot;></see> class."
  remarks: "The OutputCacheSettingsSection constructor is not intended to be used directly from your code. It is called by the ASP.NET configuration system. You obtain an instance of the <xref:System.Web.Configuration.OutputCacheSettingsSection> class by using the <xref:System.Configuration.Configuration.GetSection%2A> method."
  syntax:
    content: public OutputCacheSettingsSection ();
    parameters: []
  overload: System.Web.Configuration.OutputCacheSettingsSection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles
  id: OutputCacheProfiles
  parent: System.Web.Configuration.OutputCacheSettingsSection
  langs:
  - csharp
  name: OutputCacheProfiles
  nameWithType: OutputCacheSettingsSection.OutputCacheProfiles
  fullName: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets a <see cref=&quot;T:System.Web.Configuration.OutputCacheProfileCollection&quot;></see>."
  remarks: "The OutputCacheProfiles property allows you to programmatically access the `outputCacheProfiles` element in a configuration file. You can use the OutputCacheProfiles property to modify the `outputCacheProfiles` element programmatically.       The `outputCacheProfiles` section contains <xref:System.Web.Configuration.OutputCacheProfile> objects that represent output cache settings that may be used by pages in the application.  These settings can be applied to a page by setting the `CacheProfile` attribute of the [@ OutputCache](http://msdn.microsoft.com/en-us/28a9e101-fb44-4198-9cb6-b8a52312fec2) directive. Apply the profile to control caching attributes such as dependencies, cache location, and cache expiration time.       The [@ OutputCache](http://msdn.microsoft.com/en-us/28a9e101-fb44-4198-9cb6-b8a52312fec2) directive can override all the settings contained by an <xref:System.Web.Configuration.OutputCacheProfile> except the <xref:System.Web.Configuration.OutputCacheProfile.Enabled%2A> property. This is to ensure you can enable or disable the <xref:System.Web.Configuration.OutputCacheProfile> without having to modify the directives in all the pages that might have overridden it."
  example:
  - "The following code example shows how to use the OutputCacheProfiles property.  \n  \n [!code-cs[System.Web.Configuration.OutputCacheSettingsSection#3](~/add/codesnippet/CSharp/p-system.web.configurati_105_1.cs)]\n [!code-vb[System.Web.Configuration.OutputCacheSettingsSection#3](~/add/codesnippet/VisualBasic/p-system.web.configurati_105_1.vb)]"
  syntax:
    content: public System.Web.Configuration.OutputCacheProfileCollection OutputCacheProfiles { get; }
    return:
      type: System.Web.Configuration.OutputCacheProfileCollection
      description: "A <see cref=&quot;T:System.Web.Configuration.OutputCacheProfileCollection&quot;></see> of <see cref=&quot;T:System.Web.Configuration.OutputCacheProfile&quot;></see> objects"
  overload: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.OutputCacheSettingsSection.Properties
  id: Properties
  parent: System.Web.Configuration.OutputCacheSettingsSection
  langs:
  - csharp
  name: Properties
  nameWithType: OutputCacheSettingsSection.Properties
  fullName: System.Web.Configuration.OutputCacheSettingsSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Web.Configuration.OutputCacheSettingsSection.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.OutputCacheSettingsSection.#ctor
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: OutputCacheSettingsSection()
  nameWithType: OutputCacheSettingsSection.OutputCacheSettingsSection()
  fullName: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheSettingsSection()
- uid: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: OutputCacheProfiles
  nameWithType: OutputCacheSettingsSection.OutputCacheProfiles
  fullName: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles
- uid: System.Web.Configuration.OutputCacheProfileCollection
  parent: System.Web.Configuration
  isExternal: false
  name: OutputCacheProfileCollection
  nameWithType: OutputCacheProfileCollection
  fullName: System.Web.Configuration.OutputCacheProfileCollection
- uid: System.Web.Configuration.OutputCacheSettingsSection.Properties
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: Properties
  nameWithType: OutputCacheSettingsSection.Properties
  fullName: System.Web.Configuration.OutputCacheSettingsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.OutputCacheSettingsSection.#ctor*
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: OutputCacheSettingsSection
  nameWithType: OutputCacheSettingsSection.OutputCacheSettingsSection
- uid: System.Web.Configuration.OutputCacheSettingsSection.OutputCacheProfiles*
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: OutputCacheProfiles
  nameWithType: OutputCacheSettingsSection.OutputCacheProfiles
- uid: System.Web.Configuration.OutputCacheSettingsSection.Properties*
  parent: System.Web.Configuration.OutputCacheSettingsSection
  isExternal: false
  name: Properties
  nameWithType: OutputCacheSettingsSection.Properties
