### YamlMime:ManagedReference
items:
- uid: System.Configuration.SpecialSetting
  id: SpecialSetting
  children:
  - System.Configuration.SpecialSetting.ConnectionString
  - System.Configuration.SpecialSetting.WebServiceUrl
  langs:
  - csharp
  name: SpecialSetting
  nameWithType: SpecialSetting
  fullName: System.Configuration.SpecialSetting
  type: Enum
  summary: "Specifies the special setting category of a application settings property."
  remarks: "The SpecialSetting enumeration defines a set of special categories that are applied to application settings properties with the ttribute class.      > [!CAUTION] >  The default settings provider, <xref:System.Configuration.LocalFileSettingsProvider>, does not encrypt or otherwise protect connection strings. It simple stores this type of settings in a separate `<connectionstrings>` section in the appropriate configuration file."
  syntax:
    content: public enum SpecialSetting
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SpecialSetting.ConnectionString
  id: ConnectionString
  parent: System.Configuration.SpecialSetting
  langs:
  - csharp
  name: ConnectionString
  nameWithType: SpecialSetting.ConnectionString
  fullName: System.Configuration.SpecialSetting.ConnectionString
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "The configuration property represents a connection string, typically for a data store or network resource."
  syntax:
    content: ConnectionString
    return:
      type: System.Configuration.SpecialSetting
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SpecialSetting.WebServiceUrl
  id: WebServiceUrl
  parent: System.Configuration.SpecialSetting
  langs:
  - csharp
  name: WebServiceUrl
  nameWithType: SpecialSetting.WebServiceUrl
  fullName: System.Configuration.SpecialSetting.WebServiceUrl
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "The configuration property represents a Uniform Resource Locator (URL) to a Web service."
  syntax:
    content: WebServiceUrl
    return:
      type: System.Configuration.SpecialSetting
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.SpecialSetting.ConnectionString
  parent: System.Configuration.SpecialSetting
  isExternal: false
  name: ConnectionString
  nameWithType: SpecialSetting.ConnectionString
  fullName: System.Configuration.SpecialSetting.ConnectionString
- uid: System.Configuration.SpecialSetting
  parent: System.Configuration
  isExternal: false
  name: SpecialSetting
  nameWithType: SpecialSetting
  fullName: System.Configuration.SpecialSetting
- uid: System.Configuration.SpecialSetting.WebServiceUrl
  parent: System.Configuration.SpecialSetting
  isExternal: false
  name: WebServiceUrl
  nameWithType: SpecialSetting.WebServiceUrl
  fullName: System.Configuration.SpecialSetting.WebServiceUrl
