### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ServiceTimeoutsElement
  id: ServiceTimeoutsElement
  children:
  - System.ServiceModel.Configuration.ServiceTimeoutsElement.#ctor
  - System.ServiceModel.Configuration.ServiceTimeoutsElement.BehaviorType
  - System.ServiceModel.Configuration.ServiceTimeoutsElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.ServiceTimeoutsElement.CreateBehavior
  - System.ServiceModel.Configuration.ServiceTimeoutsElement.Properties
  - System.ServiceModel.Configuration.ServiceTimeoutsElement.TransactionTimeout
  langs:
  - csharp
  name: ServiceTimeoutsElement
  nameWithType: ServiceTimeoutsElement
  fullName: System.ServiceModel.Configuration.ServiceTimeoutsElement
  type: Class
  summary: "Represents a configuration element that specifies the timeout for a service. This class cannot be inherited."
  syntax:
    content: 'public sealed class ServiceTimeoutsElement : System.ServiceModel.Configuration.BehaviorExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  - System.ServiceModel.Configuration.BehaviorExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ServiceTimeoutsElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ServiceTimeoutsElement
  langs:
  - csharp
  name: ServiceTimeoutsElement()
  nameWithType: ServiceTimeoutsElement.ServiceTimeoutsElement()
  fullName: System.ServiceModel.Configuration.ServiceTimeoutsElement.ServiceTimeoutsElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.ServiceTimeoutsElement&quot;></see> class."
  syntax:
    content: public ServiceTimeoutsElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.ServiceTimeoutsElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ServiceTimeoutsElement.BehaviorType
  id: BehaviorType
  parent: System.ServiceModel.Configuration.ServiceTimeoutsElement
  langs:
  - csharp
  name: BehaviorType
  nameWithType: ServiceTimeoutsElement.BehaviorType
  fullName: System.ServiceModel.Configuration.ServiceTimeoutsElement.BehaviorType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets the type of this behavior element."
  syntax:
    content: public override Type BehaviorType { get; }
    return:
      type: System.Type
      description: "The type of the behavior."
  overload: System.ServiceModel.Configuration.ServiceTimeoutsElement.BehaviorType*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ServiceTimeoutsElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  id: CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.ServiceTimeoutsElement
  langs:
  - csharp
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: ServiceTimeoutsElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.ServiceTimeoutsElement.CopyFrom(ServiceModelExtensionElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Copies the content of the specified configuration element to this configuration element."
  syntax:
    content: public override void CopyFrom (System.ServiceModel.Configuration.ServiceModelExtensionElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.ServiceModelExtensionElement
      description: "The configuration element to be copied."
  overload: System.ServiceModel.Configuration.ServiceTimeoutsElement.CopyFrom*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ServiceTimeoutsElement.CreateBehavior
  id: CreateBehavior
  parent: System.ServiceModel.Configuration.ServiceTimeoutsElement
  langs:
  - csharp
  name: CreateBehavior()
  nameWithType: ServiceTimeoutsElement.CreateBehavior()
  fullName: System.ServiceModel.Configuration.ServiceTimeoutsElement.CreateBehavior()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override object CreateBehavior ();
    parameters: []
    return:
      type: System.Object
      description: "To be added."
  overload: System.ServiceModel.Configuration.ServiceTimeoutsElement.CreateBehavior*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ServiceTimeoutsElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ServiceTimeoutsElement
  langs:
  - csharp
  name: Properties
  nameWithType: ServiceTimeoutsElement.Properties
  fullName: System.ServiceModel.Configuration.ServiceTimeoutsElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.ServiceTimeoutsElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ServiceTimeoutsElement.TransactionTimeout
  id: TransactionTimeout
  parent: System.ServiceModel.Configuration.ServiceTimeoutsElement
  langs:
  - csharp
  name: TransactionTimeout
  nameWithType: ServiceTimeoutsElement.TransactionTimeout
  fullName: System.ServiceModel.Configuration.ServiceTimeoutsElement.TransactionTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets the period within which a transaction must complete."
  syntax:
    content: public TimeSpan TransactionTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "A &lt;xref:System.TimeSpan&gt; object that represents the time within which transactions must complete or be automatically aborted."
  overload: System.ServiceModel.Configuration.ServiceTimeoutsElement.TransactionTimeout*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.BehaviorExtensionElement
  isExternal: false
  name: System.ServiceModel.Configuration.BehaviorExtensionElement
- uid: System.ServiceModel.Configuration.ServiceTimeoutsElement.#ctor
  parent: System.ServiceModel.Configuration.ServiceTimeoutsElement
  isExternal: false
  name: ServiceTimeoutsElement()
  nameWithType: ServiceTimeoutsElement.ServiceTimeoutsElement()
  fullName: System.ServiceModel.Configuration.ServiceTimeoutsElement.ServiceTimeoutsElement()
- uid: System.ServiceModel.Configuration.ServiceTimeoutsElement.BehaviorType
  parent: System.ServiceModel.Configuration.ServiceTimeoutsElement
  isExternal: false
  name: BehaviorType
  nameWithType: ServiceTimeoutsElement.BehaviorType
  fullName: System.ServiceModel.Configuration.ServiceTimeoutsElement.BehaviorType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.ServiceTimeoutsElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.ServiceTimeoutsElement
  isExternal: false
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: ServiceTimeoutsElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.ServiceTimeoutsElement.CopyFrom(ServiceModelExtensionElement)
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelExtensionElement
  nameWithType: ServiceModelExtensionElement
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement
- uid: System.ServiceModel.Configuration.ServiceTimeoutsElement.CreateBehavior
  parent: System.ServiceModel.Configuration.ServiceTimeoutsElement
  isExternal: false
  name: CreateBehavior()
  nameWithType: ServiceTimeoutsElement.CreateBehavior()
  fullName: System.ServiceModel.Configuration.ServiceTimeoutsElement.CreateBehavior()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Configuration.ServiceTimeoutsElement.Properties
  parent: System.ServiceModel.Configuration.ServiceTimeoutsElement
  isExternal: false
  name: Properties
  nameWithType: ServiceTimeoutsElement.Properties
  fullName: System.ServiceModel.Configuration.ServiceTimeoutsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ServiceTimeoutsElement.TransactionTimeout
  parent: System.ServiceModel.Configuration.ServiceTimeoutsElement
  isExternal: false
  name: TransactionTimeout
  nameWithType: ServiceTimeoutsElement.TransactionTimeout
  fullName: System.ServiceModel.Configuration.ServiceTimeoutsElement.TransactionTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Configuration.ServiceTimeoutsElement.#ctor*
  parent: System.ServiceModel.Configuration.ServiceTimeoutsElement
  isExternal: false
  name: ServiceTimeoutsElement
  nameWithType: ServiceTimeoutsElement.ServiceTimeoutsElement
- uid: System.ServiceModel.Configuration.ServiceTimeoutsElement.BehaviorType*
  parent: System.ServiceModel.Configuration.ServiceTimeoutsElement
  isExternal: false
  name: BehaviorType
  nameWithType: ServiceTimeoutsElement.BehaviorType
- uid: System.ServiceModel.Configuration.ServiceTimeoutsElement.CopyFrom*
  parent: System.ServiceModel.Configuration.ServiceTimeoutsElement
  isExternal: false
  name: CopyFrom
  nameWithType: ServiceTimeoutsElement.CopyFrom
- uid: System.ServiceModel.Configuration.ServiceTimeoutsElement.CreateBehavior*
  parent: System.ServiceModel.Configuration.ServiceTimeoutsElement
  isExternal: false
  name: CreateBehavior
  nameWithType: ServiceTimeoutsElement.CreateBehavior
- uid: System.ServiceModel.Configuration.ServiceTimeoutsElement.Properties*
  parent: System.ServiceModel.Configuration.ServiceTimeoutsElement
  isExternal: false
  name: Properties
  nameWithType: ServiceTimeoutsElement.Properties
- uid: System.ServiceModel.Configuration.ServiceTimeoutsElement.TransactionTimeout*
  parent: System.ServiceModel.Configuration.ServiceTimeoutsElement
  isExternal: false
  name: TransactionTimeout
  nameWithType: ServiceTimeoutsElement.TransactionTimeout
