### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  id: BasicHttpMessageSecurityElement
  children:
  - System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.#ctor
  - System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.AlgorithmSuite
  - System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.ClientCredentialType
  - System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.Properties
  langs:
  - csharp
  name: BasicHttpMessageSecurityElement
  nameWithType: BasicHttpMessageSecurityElement
  fullName: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  type: Class
  summary: "An XML element that configures HTTP message security."
  syntax:
    content: 'public sealed class BasicHttpMessageSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  langs:
  - csharp
  name: BasicHttpMessageSecurityElement()
  nameWithType: BasicHttpMessageSecurityElement.BasicHttpMessageSecurityElement()
  fullName: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.BasicHttpMessageSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.BasicHttpMessageSecurityElement&quot;></see> class."
  syntax:
    content: public BasicHttpMessageSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.AlgorithmSuite
  id: AlgorithmSuite
  parent: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  langs:
  - csharp
  name: AlgorithmSuite
  nameWithType: BasicHttpMessageSecurityElement.AlgorithmSuite
  fullName: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.AlgorithmSuite
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Specifies the algorithms to use with the <see cref=&quot;T:System.ServiceModel.Configuration.BasicHttpMessageSecurityElement&quot;></see> class."
  syntax:
    content: public System.ServiceModel.Security.SecurityAlgorithmSuite AlgorithmSuite { get; set; }
    return:
      type: System.ServiceModel.Security.SecurityAlgorithmSuite
      description: "A <see cref=&quot;T:System.ServiceModel.Security.SecurityAlgorithmSuite&quot;></see>. The default is &lt;xref:System.ServiceModel.Security.SecurityAlgorithmSuite.Basic256%2A&gt; ."
  overload: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.AlgorithmSuite*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.ClientCredentialType
  id: ClientCredentialType
  parent: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  langs:
  - csharp
  name: ClientCredentialType
  nameWithType: BasicHttpMessageSecurityElement.ClientCredentialType
  fullName: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.ClientCredentialType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Specifies the type of client credential to use with the <see cref=&quot;T:System.ServiceModel.Configuration.BasicHttpMessageSecurityElement&quot;></see> class."
  syntax:
    content: public System.ServiceModel.BasicHttpMessageCredentialType ClientCredentialType { get; set; }
    return:
      type: System.ServiceModel.BasicHttpMessageCredentialType
      description: "A &lt;xref:System.ServiceModel.BasicHttpMessageCredentialType&gt; . The default is UserName."
  overload: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.ClientCredentialType*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: BasicHttpMessageSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  isExternal: false
  name: BasicHttpMessageSecurityElement()
  nameWithType: BasicHttpMessageSecurityElement.BasicHttpMessageSecurityElement()
  fullName: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.BasicHttpMessageSecurityElement()
- uid: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.AlgorithmSuite
  parent: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  isExternal: false
  name: AlgorithmSuite
  nameWithType: BasicHttpMessageSecurityElement.AlgorithmSuite
  fullName: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.AlgorithmSuite
- uid: System.ServiceModel.Security.SecurityAlgorithmSuite
  parent: System.ServiceModel.Security
  isExternal: false
  name: SecurityAlgorithmSuite
  nameWithType: SecurityAlgorithmSuite
  fullName: System.ServiceModel.Security.SecurityAlgorithmSuite
- uid: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.ClientCredentialType
  parent: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  isExternal: false
  name: ClientCredentialType
  nameWithType: BasicHttpMessageSecurityElement.ClientCredentialType
  fullName: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.ClientCredentialType
- uid: System.ServiceModel.BasicHttpMessageCredentialType
  parent: System.ServiceModel
  isExternal: true
  name: BasicHttpMessageCredentialType
  nameWithType: BasicHttpMessageCredentialType
  fullName: System.ServiceModel.BasicHttpMessageCredentialType
- uid: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.Properties
  parent: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  isExternal: false
  name: Properties
  nameWithType: BasicHttpMessageSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  isExternal: false
  name: BasicHttpMessageSecurityElement
  nameWithType: BasicHttpMessageSecurityElement.BasicHttpMessageSecurityElement
- uid: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.AlgorithmSuite*
  parent: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  isExternal: false
  name: AlgorithmSuite
  nameWithType: BasicHttpMessageSecurityElement.AlgorithmSuite
- uid: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.ClientCredentialType*
  parent: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  isExternal: false
  name: ClientCredentialType
  nameWithType: BasicHttpMessageSecurityElement.ClientCredentialType
- uid: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.BasicHttpMessageSecurityElement
  isExternal: false
  name: Properties
  nameWithType: BasicHttpMessageSecurityElement.Properties
