### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.CustomErrorsRedirectMode
  id: CustomErrorsRedirectMode
  children:
  - System.Web.Configuration.CustomErrorsRedirectMode.ResponseRedirect
  - System.Web.Configuration.CustomErrorsRedirectMode.ResponseRewrite
  langs:
  - csharp
  name: CustomErrorsRedirectMode
  nameWithType: CustomErrorsRedirectMode
  fullName: System.Web.Configuration.CustomErrorsRedirectMode
  type: Enum
  summary: "Specifies values for how the URL of the original request is handled when a custom error page is displayed."
  remarks: "You use the CustomErrorsRedirectMode values when you set the <xref:System.Web.Configuration.CustomErrorsSection.RedirectMode%2A> property."
  syntax:
    content: public enum CustomErrorsRedirectMode
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRedirect
  id: ResponseRedirect
  parent: System.Web.Configuration.CustomErrorsRedirectMode
  langs:
  - csharp
  name: ResponseRedirect
  nameWithType: CustomErrorsRedirectMode.ResponseRedirect
  fullName: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRedirect
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Display the error page and change the URL of the original request."
  syntax:
    content: ResponseRedirect
    return:
      type: System.Web.Configuration.CustomErrorsRedirectMode
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRewrite
  id: ResponseRewrite
  parent: System.Web.Configuration.CustomErrorsRedirectMode
  langs:
  - csharp
  name: ResponseRewrite
  nameWithType: CustomErrorsRedirectMode.ResponseRewrite
  fullName: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRewrite
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Display the error page without changing the original URL."
  syntax:
    content: ResponseRewrite
    return:
      type: System.Web.Configuration.CustomErrorsRedirectMode
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRedirect
  parent: System.Web.Configuration.CustomErrorsRedirectMode
  isExternal: false
  name: ResponseRedirect
  nameWithType: CustomErrorsRedirectMode.ResponseRedirect
  fullName: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRedirect
- uid: System.Web.Configuration.CustomErrorsRedirectMode
  parent: System.Web.Configuration
  isExternal: false
  name: CustomErrorsRedirectMode
  nameWithType: CustomErrorsRedirectMode
  fullName: System.Web.Configuration.CustomErrorsRedirectMode
- uid: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRewrite
  parent: System.Web.Configuration.CustomErrorsRedirectMode
  isExternal: false
  name: ResponseRewrite
  nameWithType: CustomErrorsRedirectMode.ResponseRewrite
  fullName: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRewrite
