### YamlMime:ManagedReference
items:
- uid: System.Configuration.PositiveTimeSpanValidator
  id: PositiveTimeSpanValidator
  children:
  - System.Configuration.PositiveTimeSpanValidator.#ctor
  - System.Configuration.PositiveTimeSpanValidator.CanValidate(System.Type)
  - System.Configuration.PositiveTimeSpanValidator.Validate(System.Object)
  langs:
  - csharp
  name: PositiveTimeSpanValidator
  nameWithType: PositiveTimeSpanValidator
  fullName: System.Configuration.PositiveTimeSpanValidator
  type: Class
  summary: "Provides validation of a &lt;xref:System.TimeSpan&gt; object. This class cannot be inherited."
  remarks: "The PositiveTimeSpanValidator is used to ensure a <xref:System.TimeSpan> object meets specific criteria. The <xref:System.Configuration.PositiveTimeSpanValidator.CanValidate%2A> method determines whether the object type being validated matches the expected type. The object being validated is passed as a parameter of the <xref:System.Configuration.PositiveTimeSpanValidator.Validate%2A> method. To pass validation, the object being validated must be a positive <xref:System.TimeSpan> value."
  example:
  - "The following code example demonstrates how to use the PositiveTimeSpanValidator type.  \n  \n [!code-cs[System.Configuration.PositiveTimeSpanValidator#1](~/add/codesnippet/CSharp/t-system.configuration.p_2_1.cs)]\n [!code-vb[System.Configuration.PositiveTimeSpanValidator#1](~/add/codesnippet/VisualBasic/t-system.configuration.p_2_1.vb)]"
  syntax:
    content: 'public class PositiveTimeSpanValidator : System.Configuration.ConfigurationValidatorBase'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationValidatorBase
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.PositiveTimeSpanValidator.#ctor
  id: '#ctor'
  parent: System.Configuration.PositiveTimeSpanValidator
  langs:
  - csharp
  name: PositiveTimeSpanValidator()
  nameWithType: PositiveTimeSpanValidator.PositiveTimeSpanValidator()
  fullName: System.Configuration.PositiveTimeSpanValidator.PositiveTimeSpanValidator()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.PositiveTimeSpanValidator&quot;></see> class."
  remarks: ''
  example:
  - "The following code example demonstrates how to use the PositiveTimeSpanValidator constructor. This code example is part of a larger example provided for the <xref:System.Configuration.PositiveTimeSpanValidator> class.  \n  \n [!code-cs[System.Configuration.PositiveTimeSpanValidator#2](~/add/codesnippet/CSharp/m-system.configuration.p_1_1.cs)]\n [!code-vb[System.Configuration.PositiveTimeSpanValidator#2](~/add/codesnippet/VisualBasic/m-system.configuration.p_1_1.vb)]"
  syntax:
    content: public PositiveTimeSpanValidator ();
    parameters: []
  overload: System.Configuration.PositiveTimeSpanValidator.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.PositiveTimeSpanValidator.CanValidate(System.Type)
  id: CanValidate(System.Type)
  parent: System.Configuration.PositiveTimeSpanValidator
  langs:
  - csharp
  name: CanValidate(Type)
  nameWithType: PositiveTimeSpanValidator.CanValidate(Type)
  fullName: System.Configuration.PositiveTimeSpanValidator.CanValidate(Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Determines whether the object type can be validated."
  remarks: ''
  example:
  - "The following code example demonstrates how to use the CanValidate method. This code example is part of a larger example provided for the <xref:System.Configuration.PositiveTimeSpanValidator> class.  \n  \n [!code-cs[System.Configuration.PositiveTimeSpanValidator#3](~/add/codesnippet/CSharp/m-system.configuration.p_2_1.cs)]\n [!code-vb[System.Configuration.PositiveTimeSpanValidator#3](~/add/codesnippet/VisualBasic/m-system.configuration.p_2_1.vb)]"
  syntax:
    content: public override bool CanValidate (Type type);
    parameters:
    - id: type
      type: System.Type
      description: "The object type."
    return:
      type: System.Boolean
      description: "To be added."
  overload: System.Configuration.PositiveTimeSpanValidator.CanValidate*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.PositiveTimeSpanValidator.Validate(System.Object)
  id: Validate(System.Object)
  parent: System.Configuration.PositiveTimeSpanValidator
  langs:
  - csharp
  name: Validate(Object)
  nameWithType: PositiveTimeSpanValidator.Validate(Object)
  fullName: System.Configuration.PositiveTimeSpanValidator.Validate(Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Determines whether the value of an object is valid."
  remarks: "The object to validate is passed as a parameter of the Validate method. To pass validation, the object being validated must be a positive <xref:System.TimeSpan> value."
  example:
  - "The following code example demonstrates how to use the Validate method. This code example is part of a larger example provided for the <xref:System.Configuration.PositiveTimeSpanValidator> class.  \n  \n [!code-cs[System.Configuration.PositiveTimeSpanValidator#4](~/add/codesnippet/CSharp/m-system.configuration.p_0_1.cs)]\n [!code-vb[System.Configuration.PositiveTimeSpanValidator#4](~/add/codesnippet/VisualBasic/m-system.configuration.p_0_1.vb)]"
  syntax:
    content: public override void Validate (object value);
    parameters:
    - id: value
      type: System.Object
      description: "The value of an object."
  overload: System.Configuration.PositiveTimeSpanValidator.Validate*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "\n    value is ."
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "\n    value cannot be resolved as a positive <xref:System.TimeSpan> value."
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.PositiveTimeSpanValidator.#ctor
  parent: System.Configuration.PositiveTimeSpanValidator
  isExternal: false
  name: PositiveTimeSpanValidator()
  nameWithType: PositiveTimeSpanValidator.PositiveTimeSpanValidator()
  fullName: System.Configuration.PositiveTimeSpanValidator.PositiveTimeSpanValidator()
- uid: System.Configuration.PositiveTimeSpanValidator.CanValidate(System.Type)
  parent: System.Configuration.PositiveTimeSpanValidator
  isExternal: false
  name: CanValidate(Type)
  nameWithType: PositiveTimeSpanValidator.CanValidate(Type)
  fullName: System.Configuration.PositiveTimeSpanValidator.CanValidate(Type)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.PositiveTimeSpanValidator.Validate(System.Object)
  parent: System.Configuration.PositiveTimeSpanValidator
  isExternal: false
  name: Validate(Object)
  nameWithType: PositiveTimeSpanValidator.Validate(Object)
  fullName: System.Configuration.PositiveTimeSpanValidator.Validate(Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.PositiveTimeSpanValidator.#ctor*
  parent: System.Configuration.PositiveTimeSpanValidator
  isExternal: false
  name: PositiveTimeSpanValidator
  nameWithType: PositiveTimeSpanValidator.PositiveTimeSpanValidator
- uid: System.Configuration.PositiveTimeSpanValidator.CanValidate*
  parent: System.Configuration.PositiveTimeSpanValidator
  isExternal: false
  name: CanValidate
  nameWithType: PositiveTimeSpanValidator.CanValidate
- uid: System.Configuration.PositiveTimeSpanValidator.Validate*
  parent: System.Configuration.PositiveTimeSpanValidator
  isExternal: false
  name: Validate
  nameWithType: PositiveTimeSpanValidator.Validate
