### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement
  id: TcpTransportSecurityElement
  children:
  - System.ServiceModel.Configuration.TcpTransportSecurityElement.#ctor
  - System.ServiceModel.Configuration.TcpTransportSecurityElement.ClientCredentialType
  - System.ServiceModel.Configuration.TcpTransportSecurityElement.ExtendedProtectionPolicy
  - System.ServiceModel.Configuration.TcpTransportSecurityElement.Properties
  - System.ServiceModel.Configuration.TcpTransportSecurityElement.ProtectionLevel
  - System.ServiceModel.Configuration.TcpTransportSecurityElement.SslProtocols
  langs:
  - csharp
  name: TcpTransportSecurityElement
  nameWithType: TcpTransportSecurityElement
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement
  type: Class
  summary: "An XML element that defines the security settings for a TcpTransport binding. This class cannot be inherited."
  syntax:
    content: 'public sealed class TcpTransportSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  langs:
  - csharp
  name: TcpTransportSecurityElement()
  nameWithType: TcpTransportSecurityElement.TcpTransportSecurityElement()
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.TcpTransportSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.TcpTransportSecurityElement&quot;></see> class."
  syntax:
    content: public TcpTransportSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.TcpTransportSecurityElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.ClientCredentialType
  id: ClientCredentialType
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  langs:
  - csharp
  name: ClientCredentialType
  nameWithType: TcpTransportSecurityElement.ClientCredentialType
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.ClientCredentialType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets and sets the type of client credential used for authentication."
  syntax:
    content: public System.ServiceModel.TcpClientCredentialType ClientCredentialType { get; set; }
    return:
      type: System.ServiceModel.TcpClientCredentialType
      description: "A &lt;xref:System.ServiceModel.TcpClientCredentialType&gt; that specifies the type of client credential used for authentication."
  overload: System.ServiceModel.Configuration.TcpTransportSecurityElement.ClientCredentialType*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.ExtendedProtectionPolicy
  id: ExtendedProtectionPolicy
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  langs:
  - csharp
  name: ExtendedProtectionPolicy
  nameWithType: TcpTransportSecurityElement.ExtendedProtectionPolicy
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.ExtendedProtectionPolicy
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Get a <see cref=&quot;T:System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement&quot;></see> instance which contains the configuration settings to use for extended protection for a session."
  syntax:
    content: public System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement ExtendedProtectionPolicy { get; }
    return:
      type: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
      description: "Returns <see cref=&quot;T:System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement&quot;></see>."
  overload: System.ServiceModel.Configuration.TcpTransportSecurityElement.ExtendedProtectionPolicy*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: TcpTransportSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.TcpTransportSecurityElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.ProtectionLevel
  id: ProtectionLevel
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  langs:
  - csharp
  name: ProtectionLevel
  nameWithType: TcpTransportSecurityElement.ProtectionLevel
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.ProtectionLevel
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets a value that defines message level security at the level of the named pipe."
  remarks: "Signing messages mitigates the risk of a third party tampering with the message while it is being transferred. Encryption provides data-level privacy during transport."
  syntax:
    content: public System.Net.Security.ProtectionLevel ProtectionLevel { get; set; }
    return:
      type: System.Net.Security.ProtectionLevel
      description: "A &lt;xref:System.ServiceModel.TcpTransportSecurity.ProtectionLevel%2A&gt; value that defines message level security at the level of the named pipe."
  overload: System.ServiceModel.Configuration.TcpTransportSecurityElement.ProtectionLevel*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.SslProtocols
  id: SslProtocols
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  langs:
  - csharp
  name: SslProtocols
  nameWithType: TcpTransportSecurityElement.SslProtocols
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.SslProtocols
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: 'Gets the list of SSL/TLS protocols to negotiate when using a client credential type of TcpClientCredentialType.Certificate. The value can be a combination of one of more of the following enumeration members: Ssl3, Tls, Tls11, Tls12.'
  remarks: "The default value is Ssl3 &#124; Tls &#124; Tls11 &#124; Tls12. Versions of the framework prior to 4.6 only support Ssl3 and Tls. If these are not included, communication with earlier versions of the framework will not be possible. Specifying Tls11 and/or Tls12 will disable the usage of Ssl3, even if it has been included."
  syntax:
    content: public System.Security.Authentication.SslProtocols SslProtocols { get; }
    return:
      type: System.Security.Authentication.SslProtocols
      description: "The list of SSL/TLS protocols."
  overload: System.ServiceModel.Configuration.TcpTransportSecurityElement.SslProtocols*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: TcpTransportSecurityElement()
  nameWithType: TcpTransportSecurityElement.TcpTransportSecurityElement()
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.TcpTransportSecurityElement()
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.ClientCredentialType
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: ClientCredentialType
  nameWithType: TcpTransportSecurityElement.ClientCredentialType
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.ClientCredentialType
- uid: System.ServiceModel.TcpClientCredentialType
  parent: System.ServiceModel
  isExternal: true
  name: TcpClientCredentialType
  nameWithType: TcpClientCredentialType
  fullName: System.ServiceModel.TcpClientCredentialType
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.ExtendedProtectionPolicy
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: ExtendedProtectionPolicy
  nameWithType: TcpTransportSecurityElement.ExtendedProtectionPolicy
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.ExtendedProtectionPolicy
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
  parent: System.Security.Authentication.ExtendedProtection.Configuration
  isExternal: false
  name: ExtendedProtectionPolicyElement
  nameWithType: ExtendedProtectionPolicyElement
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.Properties
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: Properties
  nameWithType: TcpTransportSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.ProtectionLevel
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: ProtectionLevel
  nameWithType: TcpTransportSecurityElement.ProtectionLevel
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.ProtectionLevel
- uid: System.Net.Security.ProtectionLevel
  parent: System.Net.Security
  isExternal: false
  name: ProtectionLevel
  nameWithType: ProtectionLevel
  fullName: System.Net.Security.ProtectionLevel
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.SslProtocols
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: SslProtocols
  nameWithType: TcpTransportSecurityElement.SslProtocols
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.SslProtocols
- uid: System.Security.Authentication.SslProtocols
  parent: System.Security.Authentication
  isExternal: true
  name: SslProtocols
  nameWithType: SslProtocols
  fullName: System.Security.Authentication.SslProtocols
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: TcpTransportSecurityElement
  nameWithType: TcpTransportSecurityElement.TcpTransportSecurityElement
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.ClientCredentialType*
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: ClientCredentialType
  nameWithType: TcpTransportSecurityElement.ClientCredentialType
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.ExtendedProtectionPolicy*
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: ExtendedProtectionPolicy
  nameWithType: TcpTransportSecurityElement.ExtendedProtectionPolicy
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: Properties
  nameWithType: TcpTransportSecurityElement.Properties
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.ProtectionLevel*
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: ProtectionLevel
  nameWithType: TcpTransportSecurityElement.ProtectionLevel
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.SslProtocols*
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: SslProtocols
  nameWithType: TcpTransportSecurityElement.SslProtocols
