### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  id: BufferedReceiveElement
  children:
  - System.ServiceModel.Activities.Configuration.BufferedReceiveElement.#ctor
  - System.ServiceModel.Activities.Configuration.BufferedReceiveElement.BehaviorType
  - System.ServiceModel.Activities.Configuration.BufferedReceiveElement.CreateBehavior
  - System.ServiceModel.Activities.Configuration.BufferedReceiveElement.MaxPendingMessagesPerChannel
  - System.ServiceModel.Activities.Configuration.BufferedReceiveElement.Properties
  langs:
  - csharp
  name: BufferedReceiveElement
  nameWithType: BufferedReceiveElement
  fullName: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  type: Class
  summary: "Defines the configuration element that controls the buffering of data received from the client by the workflow service operation. This is a sealed class."
  syntax:
    content: 'public sealed class BufferedReceiveElement : System.ServiceModel.Configuration.BehaviorExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  - System.ServiceModel.Configuration.BehaviorExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  langs:
  - csharp
  name: BufferedReceiveElement()
  nameWithType: BufferedReceiveElement.BufferedReceiveElement()
  fullName: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.BufferedReceiveElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "Creates a new instance of the <see cref=&quot;T:System.ServiceModel.Activities.Configuration.BufferedReceiveElement&quot;></see> class."
  syntax:
    content: public BufferedReceiveElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.BehaviorType
  id: BehaviorType
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  langs:
  - csharp
  name: BehaviorType
  nameWithType: BufferedReceiveElement.BehaviorType
  fullName: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.BehaviorType
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "Gets the behavior type of the service element that controls the workflow runtime buffering of messages received from a client instance of workflow."
  syntax:
    content: public override Type BehaviorType { get; }
    return:
      type: System.Type
      description: "A type object."
  overload: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.BehaviorType*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.CreateBehavior
  id: CreateBehavior
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  langs:
  - csharp
  name: CreateBehavior()
  nameWithType: BufferedReceiveElement.CreateBehavior()
  fullName: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.CreateBehavior()
  type: Method
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  syntax:
    content: protected override object CreateBehavior ();
    parameters: []
    return:
      type: System.Object
      description: "To be added."
  overload: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.CreateBehavior*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.MaxPendingMessagesPerChannel
  id: MaxPendingMessagesPerChannel
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  langs:
  - csharp
  name: MaxPendingMessagesPerChannel
  nameWithType: BufferedReceiveElement.MaxPendingMessagesPerChannel
  fullName: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.MaxPendingMessagesPerChannel
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "Gets or sets the maximum number of messages which can be buffered for a communications channel during a workflow service operation."
  syntax:
    content: public int MaxPendingMessagesPerChannel { get; set; }
    return:
      type: System.Int32
      description: "An integer."
  overload: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.MaxPendingMessagesPerChannel*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  langs:
  - csharp
  name: Properties
  nameWithType: BufferedReceiveElement.Properties
  fullName: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.BehaviorExtensionElement
  isExternal: false
  name: System.ServiceModel.Configuration.BehaviorExtensionElement
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.#ctor
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  isExternal: false
  name: BufferedReceiveElement()
  nameWithType: BufferedReceiveElement.BufferedReceiveElement()
  fullName: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.BufferedReceiveElement()
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.BehaviorType
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  isExternal: false
  name: BehaviorType
  nameWithType: BufferedReceiveElement.BehaviorType
  fullName: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.BehaviorType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.CreateBehavior
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  isExternal: false
  name: CreateBehavior()
  nameWithType: BufferedReceiveElement.CreateBehavior()
  fullName: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.CreateBehavior()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.MaxPendingMessagesPerChannel
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  isExternal: false
  name: MaxPendingMessagesPerChannel
  nameWithType: BufferedReceiveElement.MaxPendingMessagesPerChannel
  fullName: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.MaxPendingMessagesPerChannel
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.Properties
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  isExternal: false
  name: Properties
  nameWithType: BufferedReceiveElement.Properties
  fullName: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.#ctor*
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  isExternal: false
  name: BufferedReceiveElement
  nameWithType: BufferedReceiveElement.BufferedReceiveElement
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.BehaviorType*
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  isExternal: false
  name: BehaviorType
  nameWithType: BufferedReceiveElement.BehaviorType
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.CreateBehavior*
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  isExternal: false
  name: CreateBehavior
  nameWithType: BufferedReceiveElement.CreateBehavior
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.MaxPendingMessagesPerChannel*
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  isExternal: false
  name: MaxPendingMessagesPerChannel
  nameWithType: BufferedReceiveElement.MaxPendingMessagesPerChannel
- uid: System.ServiceModel.Activities.Configuration.BufferedReceiveElement.Properties*
  parent: System.ServiceModel.Activities.Configuration.BufferedReceiveElement
  isExternal: false
  name: Properties
  nameWithType: BufferedReceiveElement.Properties
