### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Routing.RoutingConfiguration
  id: RoutingConfiguration
  children:
  - System.ServiceModel.Routing.RoutingConfiguration.#ctor
  - System.ServiceModel.Routing.RoutingConfiguration.#ctor(System.ServiceModel.Dispatcher.MessageFilterTable{System.Collections.Generic.IEnumerable{System.ServiceModel.Description.ServiceEndpoint}},System.Boolean)
  - System.ServiceModel.Routing.RoutingConfiguration.EnsureOrderedDispatch
  - System.ServiceModel.Routing.RoutingConfiguration.FilterTable
  - System.ServiceModel.Routing.RoutingConfiguration.RouteOnHeadersOnly
  - System.ServiceModel.Routing.RoutingConfiguration.SoapProcessingEnabled
  langs:
  - csharp
  name: RoutingConfiguration
  nameWithType: RoutingConfiguration
  fullName: System.ServiceModel.Routing.RoutingConfiguration
  type: Class
  summary: "Defines the configuration information used by <see cref=&quot;T:System.ServiceModel.Routing.RoutingExtension&quot;></see>."
  syntax:
    content: public sealed class RoutingConfiguration
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.RoutingConfiguration.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Routing.RoutingConfiguration
  langs:
  - csharp
  name: RoutingConfiguration()
  nameWithType: RoutingConfiguration.RoutingConfiguration()
  fullName: System.ServiceModel.Routing.RoutingConfiguration.RoutingConfiguration()
  type: Constructor
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing
  summary: "Creates a new instance of the <see cref=&quot;T:System.ServiceModel.Routing.RoutingConfiguration&quot;></see> class."
  syntax:
    content: public RoutingConfiguration ();
    parameters: []
  overload: System.ServiceModel.Routing.RoutingConfiguration.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.RoutingConfiguration.#ctor(System.ServiceModel.Dispatcher.MessageFilterTable{System.Collections.Generic.IEnumerable{System.ServiceModel.Description.ServiceEndpoint}},System.Boolean)
  id: '#ctor(System.ServiceModel.Dispatcher.MessageFilterTable{System.Collections.Generic.IEnumerable{System.ServiceModel.Description.ServiceEndpoint}},System.Boolean)'
  parent: System.ServiceModel.Routing.RoutingConfiguration
  langs:
  - csharp
  name: RoutingConfiguration(MessageFilterTable<IEnumerable<ServiceEndpoint>>,Boolean)
  nameWithType: RoutingConfiguration.RoutingConfiguration(MessageFilterTable<IEnumerable<ServiceEndpoint>>,Boolean)
  fullName: System.ServiceModel.Routing.RoutingConfiguration.RoutingConfiguration(MessageFilterTable<IEnumerable<ServiceEndpoint>>,Boolean)
  type: Constructor
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing
  summary: "Creates a new instance of the <see cref=&quot;T:System.ServiceModel.Routing.RoutingConfiguration&quot;></see> class using the specified &lt;xref:System.ServiceModel.Dispatcher.MessageFilterTable%601&gt; and routeOnHeadersOnly parameter."
  syntax:
    content: public RoutingConfiguration (System.ServiceModel.Dispatcher.MessageFilterTable<System.Collections.Generic.IEnumerable<System.ServiceModel.Description.ServiceEndpoint>> filterTable, bool routeOnHeadersOnly);
    parameters:
    - id: filterTable
      type: System.ServiceModel.Dispatcher.MessageFilterTable{System.Collections.Generic.IEnumerable{System.ServiceModel.Description.ServiceEndpoint}}
      description: "The message filter table to use for this configuration."
    - id: routeOnHeadersOnly
      type: System.Boolean
      description: "\n     if the <xref:System.ServiceModel.Dispatcher.MessageFilterTable%601> can only examine message headers; otherwise, . The default is ."
  overload: System.ServiceModel.Routing.RoutingConfiguration.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.RoutingConfiguration.EnsureOrderedDispatch
  id: EnsureOrderedDispatch
  parent: System.ServiceModel.Routing.RoutingConfiguration
  langs:
  - csharp
  name: EnsureOrderedDispatch
  nameWithType: RoutingConfiguration.EnsureOrderedDispatch
  fullName: System.ServiceModel.Routing.RoutingConfiguration.EnsureOrderedDispatch
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing
  summary: "Gets a value that indicates whether messages are to be dispatched in the order they were sent."
  syntax:
    content: public bool EnsureOrderedDispatch { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if messages are to be dispatched in the order they were sent; otherwise, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>."
  overload: System.ServiceModel.Routing.RoutingConfiguration.EnsureOrderedDispatch*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.RoutingConfiguration.FilterTable
  id: FilterTable
  parent: System.ServiceModel.Routing.RoutingConfiguration
  langs:
  - csharp
  name: FilterTable
  nameWithType: RoutingConfiguration.FilterTable
  fullName: System.ServiceModel.Routing.RoutingConfiguration.FilterTable
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing
  summary: "Gets or sets the &lt;xref:System.ServiceModel.Dispatcher.MessageFilterTable%601&gt; used by this configuration."
  syntax:
    content: public System.ServiceModel.Dispatcher.MessageFilterTable<System.Collections.Generic.IEnumerable<System.ServiceModel.Description.ServiceEndpoint>> FilterTable { get; }
    return:
      type: System.ServiceModel.Dispatcher.MessageFilterTable{System.Collections.Generic.IEnumerable{System.ServiceModel.Description.ServiceEndpoint}}
      description: "The message filter table."
  overload: System.ServiceModel.Routing.RoutingConfiguration.FilterTable*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.RoutingConfiguration.RouteOnHeadersOnly
  id: RouteOnHeadersOnly
  parent: System.ServiceModel.Routing.RoutingConfiguration
  langs:
  - csharp
  name: RouteOnHeadersOnly
  nameWithType: RoutingConfiguration.RouteOnHeadersOnly
  fullName: System.ServiceModel.Routing.RoutingConfiguration.RouteOnHeadersOnly
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing
  summary: "Gets or sets a value that indicates whether the filter can examine the message body."
  syntax:
    content: public bool RouteOnHeadersOnly { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if the filter can only examine message headers; otherwise, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>. The default is **true**."
  overload: System.ServiceModel.Routing.RoutingConfiguration.RouteOnHeadersOnly*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.RoutingConfiguration.SoapProcessingEnabled
  id: SoapProcessingEnabled
  parent: System.ServiceModel.Routing.RoutingConfiguration
  langs:
  - csharp
  name: SoapProcessingEnabled
  nameWithType: RoutingConfiguration.SoapProcessingEnabled
  fullName: System.ServiceModel.Routing.RoutingConfiguration.SoapProcessingEnabled
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing
  summary: "Gets or sets a value that indicates whether messages should be processed between SOAP &lt;xref:System.ServiceModel.Channels.MessageVersion&gt;s."
  remarks: "SOAP processing is the process where messages are converted between SOAP <xref:System.ServiceModel.Channels.MessageVersion>s.       Setting this value to `false` indicates that the <xref:System.ServiceModel.Routing.RoutingBehavior> should not install the <xref:System.ServiceModel.Routing.SoapProcessingBehavior> on the client endpoints. If set to `false`, you must add your own message inspector or other code to handle some aspects of messages before they are sent. It is also possible to disable SOAP processing on each endpoint. [!INCLUDE[crdefault](~/add/includes/crdefault-md.md)] the <xref:System.ServiceModel.Routing.SoapProcessingBehavior> class.       By default, the <xref:System.ServiceModel.Routing.RoutingBehavior> creates and attaches a new <xref:System.ServiceModel.Routing.SoapProcessingBehavior> with <xref:System.ServiceModel.Routing.SoapProcessingBehavior.ProcessMessages%2A> set to `true` for each client endpoint. If you do not want to use the <xref:System.ServiceModel.Routing.SoapProcessingBehavior> on a specific endpoint, create a new <xref:System.ServiceModel.Routing.SoapProcessingBehavior> with this value set to `false` and then attach it to the endpoint on which you do not want processing to occur. If the <xref:System.ServiceModel.Routing.RoutingBehavior> observes that a client already has a <xref:System.ServiceModel.Routing.SoapProcessingBehavior>, it does not attempt to attach another.       To disable the application of <xref:System.ServiceModel.Routing.SoapProcessingBehavior> on any endpoint, disable SOAP processing on the <xref:System.ServiceModel.Routing.RoutingBehavior>and the <xref:System.ServiceModel.Routing.RoutingConfiguration>.       If SoapProcessingEnabled is `true`, the <xref:System.ServiceModel.Routing.SoapProcessingBehavior> is added to the client endpoint <xref:System.ServiceModel.Description.ServiceEndpoint.Behaviors%2A> collection."
  syntax:
    content: public bool SoapProcessingEnabled { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if messages should be processed; otherwise, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>. The default value is <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>."
  overload: System.ServiceModel.Routing.RoutingConfiguration.SoapProcessingEnabled*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.Routing.RoutingConfiguration.#ctor
  parent: System.ServiceModel.Routing.RoutingConfiguration
  isExternal: false
  name: RoutingConfiguration()
  nameWithType: RoutingConfiguration.RoutingConfiguration()
  fullName: System.ServiceModel.Routing.RoutingConfiguration.RoutingConfiguration()
- uid: System.ServiceModel.Routing.RoutingConfiguration.#ctor(System.ServiceModel.Dispatcher.MessageFilterTable{System.Collections.Generic.IEnumerable{System.ServiceModel.Description.ServiceEndpoint}},System.Boolean)
  parent: System.ServiceModel.Routing.RoutingConfiguration
  isExternal: false
  name: RoutingConfiguration(MessageFilterTable<IEnumerable<ServiceEndpoint>>,Boolean)
  nameWithType: RoutingConfiguration.RoutingConfiguration(MessageFilterTable<IEnumerable<ServiceEndpoint>>,Boolean)
  fullName: System.ServiceModel.Routing.RoutingConfiguration.RoutingConfiguration(MessageFilterTable<IEnumerable<ServiceEndpoint>>,Boolean)
- uid: System.ServiceModel.Dispatcher.MessageFilterTable{System.Collections.Generic.IEnumerable{System.ServiceModel.Description.ServiceEndpoint}}
  parent: System.ServiceModel.Dispatcher
  isExternal: false
  name: MessageFilterTable<IEnumerable<ServiceEndpoint>>
  nameWithType: MessageFilterTable<IEnumerable<ServiceEndpoint>>
  fullName: System.ServiceModel.Dispatcher.MessageFilterTable<System.Collections.Generic.IEnumerable<System.ServiceModel.Description.ServiceEndpoint>>
  spec.csharp:
  - uid: System.ServiceModel.Dispatcher.MessageFilterTable`1
    name: MessageFilterTable
    nameWithType: MessageFilterTable
    fullName: MessageFilterTable<System.Collections.Generic.IEnumerable<System.ServiceModel.Description.ServiceEndpoint>>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: IEnumerable<System.ServiceModel.Description.ServiceEndpoint>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.ServiceModel.Description.ServiceEndpoint
    name: ServiceEndpoint
    nameWithType: ServiceEndpoint
    fullName: ServiceEndpoint
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Routing.RoutingConfiguration.EnsureOrderedDispatch
  parent: System.ServiceModel.Routing.RoutingConfiguration
  isExternal: false
  name: EnsureOrderedDispatch
  nameWithType: RoutingConfiguration.EnsureOrderedDispatch
  fullName: System.ServiceModel.Routing.RoutingConfiguration.EnsureOrderedDispatch
- uid: System.ServiceModel.Routing.RoutingConfiguration.FilterTable
  parent: System.ServiceModel.Routing.RoutingConfiguration
  isExternal: false
  name: FilterTable
  nameWithType: RoutingConfiguration.FilterTable
  fullName: System.ServiceModel.Routing.RoutingConfiguration.FilterTable
- uid: System.ServiceModel.Routing.RoutingConfiguration.RouteOnHeadersOnly
  parent: System.ServiceModel.Routing.RoutingConfiguration
  isExternal: false
  name: RouteOnHeadersOnly
  nameWithType: RoutingConfiguration.RouteOnHeadersOnly
  fullName: System.ServiceModel.Routing.RoutingConfiguration.RouteOnHeadersOnly
- uid: System.ServiceModel.Routing.RoutingConfiguration.SoapProcessingEnabled
  parent: System.ServiceModel.Routing.RoutingConfiguration
  isExternal: false
  name: SoapProcessingEnabled
  nameWithType: RoutingConfiguration.SoapProcessingEnabled
  fullName: System.ServiceModel.Routing.RoutingConfiguration.SoapProcessingEnabled
- uid: System.ServiceModel.Routing.RoutingConfiguration.#ctor*
  parent: System.ServiceModel.Routing.RoutingConfiguration
  isExternal: false
  name: RoutingConfiguration
  nameWithType: RoutingConfiguration.RoutingConfiguration
- uid: System.ServiceModel.Routing.RoutingConfiguration.EnsureOrderedDispatch*
  parent: System.ServiceModel.Routing.RoutingConfiguration
  isExternal: false
  name: EnsureOrderedDispatch
  nameWithType: RoutingConfiguration.EnsureOrderedDispatch
- uid: System.ServiceModel.Routing.RoutingConfiguration.FilterTable*
  parent: System.ServiceModel.Routing.RoutingConfiguration
  isExternal: false
  name: FilterTable
  nameWithType: RoutingConfiguration.FilterTable
- uid: System.ServiceModel.Routing.RoutingConfiguration.RouteOnHeadersOnly*
  parent: System.ServiceModel.Routing.RoutingConfiguration
  isExternal: false
  name: RouteOnHeadersOnly
  nameWithType: RoutingConfiguration.RouteOnHeadersOnly
- uid: System.ServiceModel.Routing.RoutingConfiguration.SoapProcessingEnabled*
  parent: System.ServiceModel.Routing.RoutingConfiguration
  isExternal: false
  name: SoapProcessingEnabled
  nameWithType: RoutingConfiguration.SoapProcessingEnabled
