### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  id: X509InitiatorCertificateServiceElement
  children:
  - System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.#ctor
  - System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Authentication
  - System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Certificate
  - System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Copy(System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement)
  - System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Properties
  langs:
  - csharp
  name: X509InitiatorCertificateServiceElement
  nameWithType: X509InitiatorCertificateServiceElement
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  type: Class
  summary: "Represent a configuration element that specifies the sender&quot;s requirement for an X.509 certificate, which is used by the recipient when replying to the sender. This class cannot be inherited."
  syntax:
    content: 'public sealed class X509InitiatorCertificateServiceElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  langs:
  - csharp
  name: X509InitiatorCertificateServiceElement()
  nameWithType: X509InitiatorCertificateServiceElement.X509InitiatorCertificateServiceElement()
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.X509InitiatorCertificateServiceElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement&quot;></see> class."
  syntax:
    content: public X509InitiatorCertificateServiceElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Authentication
  id: Authentication
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  langs:
  - csharp
  name: Authentication
  nameWithType: X509InitiatorCertificateServiceElement.Authentication
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Authentication
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets the client certificate used for authentication."
  syntax:
    content: public System.ServiceModel.Configuration.X509ClientCertificateAuthenticationElement Authentication { get; }
    return:
      type: System.ServiceModel.Configuration.X509ClientCertificateAuthenticationElement
      description: "A <see cref=&quot;T:System.ServiceModel.Security.X509ClientCertificateAuthentication&quot;></see> that contains the client certificate used for authentication."
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Authentication*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Certificate
  id: Certificate
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  langs:
  - csharp
  name: Certificate
  nameWithType: X509InitiatorCertificateServiceElement.Certificate
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Certificate
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets the certificate that is used to represent the service when communicating back to the client."
  syntax:
    content: public System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement Certificate { get; }
    return:
      type: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
      description: "A <see cref=&quot;T:System.Security.Cryptography.X509Certificates.X509Certificate2&quot;></see> that is used to represent the service when communicating back to the client."
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Certificate*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Copy(System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement)
  id: Copy(System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement)
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  langs:
  - csharp
  name: Copy(X509InitiatorCertificateServiceElement)
  nameWithType: X509InitiatorCertificateServiceElement.Copy(X509InitiatorCertificateServiceElement)
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Copy(X509InitiatorCertificateServiceElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Copies the content of the specified configuration element to this configuration element."
  syntax:
    content: public void Copy (System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
      description: "The configuration element to be copied."
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Copy*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "\n    from is ."
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "The configuration file is read-only."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  langs:
  - csharp
  name: Properties
  nameWithType: X509InitiatorCertificateServiceElement.Properties
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.#ctor
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  isExternal: false
  name: X509InitiatorCertificateServiceElement()
  nameWithType: X509InitiatorCertificateServiceElement.X509InitiatorCertificateServiceElement()
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.X509InitiatorCertificateServiceElement()
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Authentication
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  isExternal: false
  name: Authentication
  nameWithType: X509InitiatorCertificateServiceElement.Authentication
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Authentication
- uid: System.ServiceModel.Configuration.X509ClientCertificateAuthenticationElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: X509ClientCertificateAuthenticationElement
  nameWithType: X509ClientCertificateAuthenticationElement
  fullName: System.ServiceModel.Configuration.X509ClientCertificateAuthenticationElement
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Certificate
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  isExternal: false
  name: Certificate
  nameWithType: X509InitiatorCertificateServiceElement.Certificate
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Certificate
- uid: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: X509ClientCertificateCredentialsElement
  nameWithType: X509ClientCertificateCredentialsElement
  fullName: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Copy(System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement)
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  isExternal: false
  name: Copy(X509InitiatorCertificateServiceElement)
  nameWithType: X509InitiatorCertificateServiceElement.Copy(X509InitiatorCertificateServiceElement)
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Copy(X509InitiatorCertificateServiceElement)
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: X509InitiatorCertificateServiceElement
  nameWithType: X509InitiatorCertificateServiceElement
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Properties
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  isExternal: false
  name: Properties
  nameWithType: X509InitiatorCertificateServiceElement.Properties
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.#ctor*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  isExternal: false
  name: X509InitiatorCertificateServiceElement
  nameWithType: X509InitiatorCertificateServiceElement.X509InitiatorCertificateServiceElement
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Authentication*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  isExternal: false
  name: Authentication
  nameWithType: X509InitiatorCertificateServiceElement.Authentication
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Certificate*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  isExternal: false
  name: Certificate
  nameWithType: X509InitiatorCertificateServiceElement.Certificate
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Copy*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  isExternal: false
  name: Copy
  nameWithType: X509InitiatorCertificateServiceElement.Copy
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement.Properties*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateServiceElement
  isExternal: false
  name: Properties
  nameWithType: X509InitiatorCertificateServiceElement.Properties
