### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Routing.Configuration.FilterElement
  id: FilterElement
  children:
  - System.ServiceModel.Routing.Configuration.FilterElement.#ctor
  - System.ServiceModel.Routing.Configuration.FilterElement.CustomType
  - System.ServiceModel.Routing.Configuration.FilterElement.Filter1
  - System.ServiceModel.Routing.Configuration.FilterElement.Filter2
  - System.ServiceModel.Routing.Configuration.FilterElement.FilterData
  - System.ServiceModel.Routing.Configuration.FilterElement.FilterType
  - System.ServiceModel.Routing.Configuration.FilterElement.Name
  langs:
  - csharp
  name: FilterElement
  nameWithType: FilterElement
  fullName: System.ServiceModel.Routing.Configuration.FilterElement
  type: Class
  summary: "Represents a configuration element that defines a filter element. This element is used to define the type of filter, as well as any supporting data or parameters required by the filter."
  syntax:
    content: 'public class FilterElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.FilterElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Routing.Configuration.FilterElement
  langs:
  - csharp
  name: FilterElement()
  nameWithType: FilterElement.FilterElement()
  fullName: System.ServiceModel.Routing.Configuration.FilterElement.FilterElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Routing.Configuration.FilterElement&quot;></see> class."
  syntax:
    content: public FilterElement ();
    parameters: []
  overload: System.ServiceModel.Routing.Configuration.FilterElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.FilterElement.CustomType
  id: CustomType
  parent: System.ServiceModel.Routing.Configuration.FilterElement
  langs:
  - csharp
  name: CustomType
  nameWithType: FilterElement.CustomType
  fullName: System.ServiceModel.Routing.Configuration.FilterElement.CustomType
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Gets or sets the fully-qualified type name of the custom type to be used as a filter."
  remarks: "If <xref:System.ServiceModel.Routing.Configuration.FilterElement.FilterType%2A> is set to custom, CustomType is the fully-qualified type name of the class to create. <xref:System.ServiceModel.Routing.Configuration.FilterElement.FilterData%2A> can also contain values to be used during evaluation of the CustomType filter. The CustomType must implement a constructor that accepts a string value, which contains the <xref:System.ServiceModel.Routing.Configuration.FilterElement.FilterData%2A> information.       [!INCLUDE[crdefault](~/add/includes/crdefault-md.md)] <xref:System.ServiceModel.Routing.Configuration.FilterElement.FilterData%2A>."
  syntax:
    content: public string CustomType { get; set; }
    return:
      type: System.String
      description: "The fully-qualified type."
  overload: System.ServiceModel.Routing.Configuration.FilterElement.CustomType*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.FilterElement.Filter1
  id: Filter1
  parent: System.ServiceModel.Routing.Configuration.FilterElement
  langs:
  - csharp
  name: Filter1
  nameWithType: FilterElement.Filter1
  fullName: System.ServiceModel.Routing.Configuration.FilterElement.Filter1
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Gets or sets the filter1 data of this configuration element. This value is only used when &lt;xref:System.ServiceModel.Routing.Configuration.FilterElement.FilterType%2A&gt; is set to And."
  remarks: "The content of Filter1 is only used during evaluation of the AND filter. [!INCLUDE[crdefault](~/add/includes/crdefault-md.md)]<xref:System.ServiceModel.Routing.Configuration.FilterElement.FilterData%2A>."
  syntax:
    content: public string Filter1 { get; set; }
    return:
      type: System.String
      description: "The filter1 value of this element."
  overload: System.ServiceModel.Routing.Configuration.FilterElement.Filter1*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.FilterElement.Filter2
  id: Filter2
  parent: System.ServiceModel.Routing.Configuration.FilterElement
  langs:
  - csharp
  name: Filter2
  nameWithType: FilterElement.Filter2
  fullName: System.ServiceModel.Routing.Configuration.FilterElement.Filter2
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Gets or sets the filter2 data of this configuration element. This value is only used when &lt;xref:System.ServiceModel.Routing.Configuration.FilterElement.FilterType%2A&gt; is set to AND."
  remarks: "The content of Filter2 is only used during evaluation of the AND filters. [!INCLUDE[crdefault](~/add/includes/crdefault-md.md)]<xref:System.ServiceModel.Routing.Configuration.FilterElement.FilterData%2A>."
  syntax:
    content: public string Filter2 { get; set; }
    return:
      type: System.String
      description: "The filter2 value of this element."
  overload: System.ServiceModel.Routing.Configuration.FilterElement.Filter2*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.FilterElement.FilterData
  id: FilterData
  parent: System.ServiceModel.Routing.Configuration.FilterElement
  langs:
  - csharp
  name: FilterData
  nameWithType: FilterElement.FilterData
  fullName: System.ServiceModel.Routing.Configuration.FilterElement.FilterData
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Gets or sets the filter data of this configuration element."
  remarks: "The following table describes the meaning of FilterData based on the value of <xref:System.ServiceModel.Routing.Configuration.FilterType>.  \n  \n|Filter  Type|Description|Filter Data Meaning|Example Filter|  \n|------------------|-----------------|-------------------------|--------------------|  \n|Action|Uses the ActionMessageFilter that comes with WCF.|The Action to filter upon.|\\<filter name=\"action1\" filterType=\"Action\" filterData=\"http://ACTION\" />|  \n|Address|Uses the EndpointAddressMessageFilter that comes with WCF with ignore host name == true.|The address to filter upon (in the To header).|\\<filter name=\"address1\" filterType=\"Address\" filterData=\"http://host/vdir/s.svc/b\"  />|  \n|AddressPrefix|Uses the PrefixEndpointAddressMessageFilter that comes with WCF with ignore host name == true.|The address to filter upon using longest prefix matching.|\\<filter name=\"prefix1\" filterType=\"AddressPrefix\" filterData=\"http://host\" />|  \n|StrictAnd|A custom AndMessageFilter that always evaluates both conditions before returning.|filterData is not used, instead filter1 and filter2 have the names of the corresponding messages filters (also in the table), which should be ANDed together.|\\<filter name=\"and1\" filterType=\"And\" filter1=\"address1\" filter2=\"action1\" />|  \n|Custom|A user-defined type that extends MessageFilter and has a constructor taking a string.|customType attribute is the fully-qualified type name of the class to create, filterData is the string to pass to the constructor when creating the filter.|\\<filter name=\"custom1\" filterType=\"Custom\" customType=\"CustomAssembly.CustomMsgFilter, CustomAssembly\" filterData=\"Custom Data\" />|  \n|EndpointName|A custom message filter for use solely in the Routing Service, which filters messages based on the name of the service endpoint.|The name of the service endpoint, for example: “serviceEndpoint1”.  This should be one of the endpoints exposed on the Routing Service.|\\<filter name=\"stock1\" filterType=\"Endpoint\" filterData=\"SvcEndpoint\" />|  \n|MatchAll|Uses the MatchAllMessageFilter that comes with WCF.|N/A|\\<filter name=\"matchAll1\" filterType=\"MatchAll\" />|  \n|XPath|Uses the XPathMessageFilter that comes with WCF.|The XPath query to use when matching messages.|\\<filter name=\"XPath1\" filterType=\"XPath\" filterData=\"//ns:element\" />|"
  syntax:
    content: public string FilterData { get; set; }
    return:
      type: System.String
      description: "The filter data of this element."
  overload: System.ServiceModel.Routing.Configuration.FilterElement.FilterData*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.FilterElement.FilterType
  id: FilterType
  parent: System.ServiceModel.Routing.Configuration.FilterElement
  langs:
  - csharp
  name: FilterType
  nameWithType: FilterElement.FilterType
  fullName: System.ServiceModel.Routing.Configuration.FilterElement.FilterType
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Gets or sets the <see cref=&quot;T:System.ServiceModel.Routing.Configuration.FilterType&quot;></see> of this configuration element."
  syntax:
    content: public System.ServiceModel.Routing.Configuration.FilterType FilterType { get; set; }
    return:
      type: System.ServiceModel.Routing.Configuration.FilterType
      description: "The filter type of this element."
  overload: System.ServiceModel.Routing.Configuration.FilterElement.FilterType*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.FilterElement.Name
  id: Name
  parent: System.ServiceModel.Routing.Configuration.FilterElement
  langs:
  - csharp
  name: Name
  nameWithType: FilterElement.Name
  fullName: System.ServiceModel.Routing.Configuration.FilterElement.Name
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Gets or sets the name of this configuration element."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "The unique name of this configuration element."
  overload: System.ServiceModel.Routing.Configuration.FilterElement.Name*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Routing.Configuration.FilterElement.#ctor
  parent: System.ServiceModel.Routing.Configuration.FilterElement
  isExternal: false
  name: FilterElement()
  nameWithType: FilterElement.FilterElement()
  fullName: System.ServiceModel.Routing.Configuration.FilterElement.FilterElement()
- uid: System.ServiceModel.Routing.Configuration.FilterElement.CustomType
  parent: System.ServiceModel.Routing.Configuration.FilterElement
  isExternal: false
  name: CustomType
  nameWithType: FilterElement.CustomType
  fullName: System.ServiceModel.Routing.Configuration.FilterElement.CustomType
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Routing.Configuration.FilterElement.Filter1
  parent: System.ServiceModel.Routing.Configuration.FilterElement
  isExternal: false
  name: Filter1
  nameWithType: FilterElement.Filter1
  fullName: System.ServiceModel.Routing.Configuration.FilterElement.Filter1
- uid: System.ServiceModel.Routing.Configuration.FilterElement.Filter2
  parent: System.ServiceModel.Routing.Configuration.FilterElement
  isExternal: false
  name: Filter2
  nameWithType: FilterElement.Filter2
  fullName: System.ServiceModel.Routing.Configuration.FilterElement.Filter2
- uid: System.ServiceModel.Routing.Configuration.FilterElement.FilterData
  parent: System.ServiceModel.Routing.Configuration.FilterElement
  isExternal: false
  name: FilterData
  nameWithType: FilterElement.FilterData
  fullName: System.ServiceModel.Routing.Configuration.FilterElement.FilterData
- uid: System.ServiceModel.Routing.Configuration.FilterElement.FilterType
  parent: System.ServiceModel.Routing.Configuration.FilterElement
  isExternal: false
  name: FilterType
  nameWithType: FilterElement.FilterType
  fullName: System.ServiceModel.Routing.Configuration.FilterElement.FilterType
- uid: System.ServiceModel.Routing.Configuration.FilterType
  parent: System.ServiceModel.Routing.Configuration
  isExternal: false
  name: FilterType
  nameWithType: FilterType
  fullName: System.ServiceModel.Routing.Configuration.FilterType
- uid: System.ServiceModel.Routing.Configuration.FilterElement.Name
  parent: System.ServiceModel.Routing.Configuration.FilterElement
  isExternal: false
  name: Name
  nameWithType: FilterElement.Name
  fullName: System.ServiceModel.Routing.Configuration.FilterElement.Name
- uid: System.ServiceModel.Routing.Configuration.FilterElement.#ctor*
  parent: System.ServiceModel.Routing.Configuration.FilterElement
  isExternal: false
  name: FilterElement
  nameWithType: FilterElement.FilterElement
- uid: System.ServiceModel.Routing.Configuration.FilterElement.CustomType*
  parent: System.ServiceModel.Routing.Configuration.FilterElement
  isExternal: false
  name: CustomType
  nameWithType: FilterElement.CustomType
- uid: System.ServiceModel.Routing.Configuration.FilterElement.Filter1*
  parent: System.ServiceModel.Routing.Configuration.FilterElement
  isExternal: false
  name: Filter1
  nameWithType: FilterElement.Filter1
- uid: System.ServiceModel.Routing.Configuration.FilterElement.Filter2*
  parent: System.ServiceModel.Routing.Configuration.FilterElement
  isExternal: false
  name: Filter2
  nameWithType: FilterElement.Filter2
- uid: System.ServiceModel.Routing.Configuration.FilterElement.FilterData*
  parent: System.ServiceModel.Routing.Configuration.FilterElement
  isExternal: false
  name: FilterData
  nameWithType: FilterElement.FilterData
- uid: System.ServiceModel.Routing.Configuration.FilterElement.FilterType*
  parent: System.ServiceModel.Routing.Configuration.FilterElement
  isExternal: false
  name: FilterType
  nameWithType: FilterElement.FilterType
- uid: System.ServiceModel.Routing.Configuration.FilterElement.Name*
  parent: System.ServiceModel.Routing.Configuration.FilterElement
  isExternal: false
  name: Name
  nameWithType: FilterElement.Name
