### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.X509CertificateValidationElement
  id: X509CertificateValidationElement
  children:
  - System.IdentityModel.Configuration.X509CertificateValidationElement.#ctor
  - System.IdentityModel.Configuration.X509CertificateValidationElement.CertificateValidationMode
  - System.IdentityModel.Configuration.X509CertificateValidationElement.CertificateValidator
  - System.IdentityModel.Configuration.X509CertificateValidationElement.Properties
  - System.IdentityModel.Configuration.X509CertificateValidationElement.RevocationMode
  - System.IdentityModel.Configuration.X509CertificateValidationElement.TrustedStoreLocation
  langs:
  - csharp
  name: X509CertificateValidationElement
  nameWithType: X509CertificateValidationElement
  fullName: System.IdentityModel.Configuration.X509CertificateValidationElement
  type: Class
  summary: "Represents the <xref uid=&quot;langword_csharp_&lt;certificateValidation&gt;&quot; name=&quot;&lt;certificateValidation&gt;&quot; href=&quot;&quot;></xref> element in a configuration file. This class cannot be inherited."
  remarks: "The `<certificateValidation>` element configures the settings that token handlers will use to validate certificates, unless those handlers have their own validators set."
  syntax:
    content: 'public sealed class X509CertificateValidationElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Configuration.X509CertificateValidationElement.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Configuration.X509CertificateValidationElement
  langs:
  - csharp
  name: X509CertificateValidationElement()
  nameWithType: X509CertificateValidationElement.X509CertificateValidationElement()
  fullName: System.IdentityModel.Configuration.X509CertificateValidationElement.X509CertificateValidationElement()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.IdentityModel.Configuration.X509CertificateValidationElement&quot;></see> class."
  syntax:
    content: public X509CertificateValidationElement ();
    parameters: []
  overload: System.IdentityModel.Configuration.X509CertificateValidationElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Configuration.X509CertificateValidationElement.CertificateValidationMode
  id: CertificateValidationMode
  parent: System.IdentityModel.Configuration.X509CertificateValidationElement
  langs:
  - csharp
  name: CertificateValidationMode
  nameWithType: X509CertificateValidationElement.CertificateValidationMode
  fullName: System.IdentityModel.Configuration.X509CertificateValidationElement.CertificateValidationMode
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Gets or sets the certificate validation mode."
  remarks: "This property is optional. It represents the `certificateValidationMode` attribute of the `<certificateValidation>` element."
  syntax:
    content: public System.ServiceModel.Security.X509CertificateValidationMode CertificateValidationMode { get; set; }
    return:
      type: System.ServiceModel.Security.X509CertificateValidationMode
      description: "The certificate validation mode. The default is &lt;xref:System.ServiceModel.Security.X509CertificateValidationMode&gt;."
  overload: System.IdentityModel.Configuration.X509CertificateValidationElement.CertificateValidationMode*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Configuration.X509CertificateValidationElement.CertificateValidator
  id: CertificateValidator
  parent: System.IdentityModel.Configuration.X509CertificateValidationElement
  langs:
  - csharp
  name: CertificateValidator
  nameWithType: X509CertificateValidationElement.CertificateValidator
  fullName: System.IdentityModel.Configuration.X509CertificateValidationElement.CertificateValidator
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Gets or sets the [qualifyHint=False"
  remarks: "This property is optional. It represents the `<certificateValidator>` child element of the `<certificateValidation>` element."
  syntax:
    content: public System.IdentityModel.Configuration.CustomTypeElement CertificateValidator { get; set; }
    return:
      type: System.IdentityModel.Configuration.CustomTypeElement
      description: "An element that wraps the type of the X.509 certificate validator."
  overload: System.IdentityModel.Configuration.X509CertificateValidationElement.CertificateValidator*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Configuration.X509CertificateValidationElement.Properties
  id: Properties
  parent: System.IdentityModel.Configuration.X509CertificateValidationElement
  langs:
  - csharp
  name: Properties
  nameWithType: X509CertificateValidationElement.Properties
  fullName: System.IdentityModel.Configuration.X509CertificateValidationElement.Properties
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.IdentityModel.Configuration.X509CertificateValidationElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Configuration.X509CertificateValidationElement.RevocationMode
  id: RevocationMode
  parent: System.IdentityModel.Configuration.X509CertificateValidationElement
  langs:
  - csharp
  name: RevocationMode
  nameWithType: X509CertificateValidationElement.RevocationMode
  fullName: System.IdentityModel.Configuration.X509CertificateValidationElement.RevocationMode
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Gets or sets the revocation mode."
  remarks: "This property is optional. It represents the `revocationMode` attribute of the `<certificateValidation>` element."
  syntax:
    content: public System.Security.Cryptography.X509Certificates.X509RevocationMode RevocationMode { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.X509RevocationMode
      description: "The revocation mode. The default is <see cref=&quot;T:System.Security.Cryptography.X509Certificates.X509RevocationMode&quot;></see>."
  overload: System.IdentityModel.Configuration.X509CertificateValidationElement.RevocationMode*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.IdentityModel.Configuration.X509CertificateValidationElement.TrustedStoreLocation
  id: TrustedStoreLocation
  parent: System.IdentityModel.Configuration.X509CertificateValidationElement
  langs:
  - csharp
  name: TrustedStoreLocation
  nameWithType: X509CertificateValidationElement.TrustedStoreLocation
  fullName: System.IdentityModel.Configuration.X509CertificateValidationElement.TrustedStoreLocation
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Gets or sets the trusted store location for X.509 certificates."
  remarks: "This property is optional. It represents the `trustedSToreLocation` attribute of the `<certificateValidation>` element."
  syntax:
    content: public System.Security.Cryptography.X509Certificates.StoreLocation TrustedStoreLocation { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.StoreLocation
      description: "The store location for X.509 certificates. The default is <see cref=&quot;T:System.Security.Cryptography.X509Certificates.StoreLocation&quot;></see>."
  overload: System.IdentityModel.Configuration.X509CertificateValidationElement.TrustedStoreLocation*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.IdentityModel.Configuration.X509CertificateValidationElement.#ctor
  parent: System.IdentityModel.Configuration.X509CertificateValidationElement
  isExternal: false
  name: X509CertificateValidationElement()
  nameWithType: X509CertificateValidationElement.X509CertificateValidationElement()
  fullName: System.IdentityModel.Configuration.X509CertificateValidationElement.X509CertificateValidationElement()
- uid: System.IdentityModel.Configuration.X509CertificateValidationElement.CertificateValidationMode
  parent: System.IdentityModel.Configuration.X509CertificateValidationElement
  isExternal: false
  name: CertificateValidationMode
  nameWithType: X509CertificateValidationElement.CertificateValidationMode
  fullName: System.IdentityModel.Configuration.X509CertificateValidationElement.CertificateValidationMode
- uid: System.ServiceModel.Security.X509CertificateValidationMode
  parent: System.ServiceModel.Security
  isExternal: true
  name: X509CertificateValidationMode
  nameWithType: X509CertificateValidationMode
  fullName: System.ServiceModel.Security.X509CertificateValidationMode
- uid: System.IdentityModel.Configuration.X509CertificateValidationElement.CertificateValidator
  parent: System.IdentityModel.Configuration.X509CertificateValidationElement
  isExternal: false
  name: CertificateValidator
  nameWithType: X509CertificateValidationElement.CertificateValidator
  fullName: System.IdentityModel.Configuration.X509CertificateValidationElement.CertificateValidator
- uid: System.IdentityModel.Configuration.CustomTypeElement
  parent: System.IdentityModel.Configuration
  isExternal: false
  name: CustomTypeElement
  nameWithType: CustomTypeElement
  fullName: System.IdentityModel.Configuration.CustomTypeElement
- uid: System.IdentityModel.Configuration.X509CertificateValidationElement.Properties
  parent: System.IdentityModel.Configuration.X509CertificateValidationElement
  isExternal: false
  name: Properties
  nameWithType: X509CertificateValidationElement.Properties
  fullName: System.IdentityModel.Configuration.X509CertificateValidationElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.IdentityModel.Configuration.X509CertificateValidationElement.RevocationMode
  parent: System.IdentityModel.Configuration.X509CertificateValidationElement
  isExternal: false
  name: RevocationMode
  nameWithType: X509CertificateValidationElement.RevocationMode
  fullName: System.IdentityModel.Configuration.X509CertificateValidationElement.RevocationMode
- uid: System.Security.Cryptography.X509Certificates.X509RevocationMode
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: X509RevocationMode
  nameWithType: X509RevocationMode
  fullName: System.Security.Cryptography.X509Certificates.X509RevocationMode
- uid: System.IdentityModel.Configuration.X509CertificateValidationElement.TrustedStoreLocation
  parent: System.IdentityModel.Configuration.X509CertificateValidationElement
  isExternal: false
  name: TrustedStoreLocation
  nameWithType: X509CertificateValidationElement.TrustedStoreLocation
  fullName: System.IdentityModel.Configuration.X509CertificateValidationElement.TrustedStoreLocation
- uid: System.Security.Cryptography.X509Certificates.StoreLocation
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: StoreLocation
  nameWithType: StoreLocation
  fullName: System.Security.Cryptography.X509Certificates.StoreLocation
- uid: System.IdentityModel.Configuration.X509CertificateValidationElement.#ctor*
  parent: System.IdentityModel.Configuration.X509CertificateValidationElement
  isExternal: false
  name: X509CertificateValidationElement
  nameWithType: X509CertificateValidationElement.X509CertificateValidationElement
- uid: System.IdentityModel.Configuration.X509CertificateValidationElement.CertificateValidationMode*
  parent: System.IdentityModel.Configuration.X509CertificateValidationElement
  isExternal: false
  name: CertificateValidationMode
  nameWithType: X509CertificateValidationElement.CertificateValidationMode
- uid: System.IdentityModel.Configuration.X509CertificateValidationElement.CertificateValidator*
  parent: System.IdentityModel.Configuration.X509CertificateValidationElement
  isExternal: false
  name: CertificateValidator
  nameWithType: X509CertificateValidationElement.CertificateValidator
- uid: System.IdentityModel.Configuration.X509CertificateValidationElement.Properties*
  parent: System.IdentityModel.Configuration.X509CertificateValidationElement
  isExternal: false
  name: Properties
  nameWithType: X509CertificateValidationElement.Properties
- uid: System.IdentityModel.Configuration.X509CertificateValidationElement.RevocationMode*
  parent: System.IdentityModel.Configuration.X509CertificateValidationElement
  isExternal: false
  name: RevocationMode
  nameWithType: X509CertificateValidationElement.RevocationMode
- uid: System.IdentityModel.Configuration.X509CertificateValidationElement.TrustedStoreLocation*
  parent: System.IdentityModel.Configuration.X509CertificateValidationElement
  isExternal: false
  name: TrustedStoreLocation
  nameWithType: X509CertificateValidationElement.TrustedStoreLocation
