### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection
  id: FilterTableEntryCollection
  children:
  - System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.#ctor
  - System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.Add(System.ServiceModel.Routing.Configuration.FilterTableEntryElement)
  - System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.Clear
  - System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.CreateNewElement
  - System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.GetElementKey(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.Name
  - System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.Remove(System.ServiceModel.Routing.Configuration.FilterTableEntryElement)
  langs:
  - csharp
  name: FilterTableEntryCollection
  nameWithType: FilterTableEntryCollection
  fullName: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection
  type: Class
  summary: "Represents the configuration element that contains a collection of <see cref=&quot;T:System.ServiceModel.Routing.Configuration.FilterTableEntryElement&quot;></see> instances."
  syntax:
    content: >-
      [System.Configuration.ConfigurationCollection(typeof(System.ServiceModel.Routing.Configuration.FilterTableEntryElement))]

      public class FilterTableEntryCollection : System.Configuration.ConfigurationElementCollection
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationElementCollection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.AddElementName
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Configuration.ConfigurationElement,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Int32,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseClear
  - System.Configuration.ConfigurationElementCollection.BaseGet(System.Int32)
  - System.Configuration.ConfigurationElementCollection.BaseGet(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseGetAllKeys
  - System.Configuration.ConfigurationElementCollection.BaseGetKey(System.Int32)
  - System.Configuration.ConfigurationElementCollection.BaseIndexOf(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseIsRemoved(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseRemove(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseRemoveAt(System.Int32)
  - System.Configuration.ConfigurationElementCollection.ClearElementName
  - System.Configuration.ConfigurationElementCollection.CollectionType
  - System.Configuration.ConfigurationElementCollection.CopyTo(System.Configuration.ConfigurationElement[],System.Int32)
  - System.Configuration.ConfigurationElementCollection.Count
  - System.Configuration.ConfigurationElementCollection.CreateNewElement(System.String)
  - System.Configuration.ConfigurationElementCollection.ElementName
  - System.Configuration.ConfigurationElementCollection.EmitClear
  - System.Configuration.ConfigurationElementCollection.Equals(System.Object)
  - System.Configuration.ConfigurationElementCollection.GetEnumerator
  - System.Configuration.ConfigurationElementCollection.GetHashCode
  - System.Configuration.ConfigurationElementCollection.IsElementName(System.String)
  - System.Configuration.ConfigurationElementCollection.IsElementRemovable(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.IsModified
  - System.Configuration.ConfigurationElementCollection.IsReadOnly
  - System.Configuration.ConfigurationElementCollection.IsSynchronized
  - System.Configuration.ConfigurationElementCollection.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElementCollection.RemoveElementName
  - System.Configuration.ConfigurationElementCollection.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.ResetModified
  - System.Configuration.ConfigurationElementCollection.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.SetReadOnly
  - System.Configuration.ConfigurationElementCollection.SyncRoot
  - System.Configuration.ConfigurationElementCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  - System.Configuration.ConfigurationElementCollection.ThrowOnDuplicate
  - System.Configuration.ConfigurationElementCollection.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection
  langs:
  - csharp
  name: FilterTableEntryCollection()
  nameWithType: FilterTableEntryCollection.FilterTableEntryCollection()
  fullName: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.FilterTableEntryCollection()
  type: Constructor
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Creates a new instance of the <see cref=&quot;T:System.ServiceModel.Routing.Configuration.FilterTableEntryCollection&quot;></see> class."
  syntax:
    content: public FilterTableEntryCollection ();
    parameters: []
  overload: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.Add(System.ServiceModel.Routing.Configuration.FilterTableEntryElement)
  id: Add(System.ServiceModel.Routing.Configuration.FilterTableEntryElement)
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection
  langs:
  - csharp
  name: Add(FilterTableEntryElement)
  nameWithType: FilterTableEntryCollection.Add(FilterTableEntryElement)
  fullName: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.Add(FilterTableEntryElement)
  type: Method
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Adds a new <see cref=&quot;T:System.ServiceModel.Routing.Configuration.FilterTableEntryElement&quot;></see> to the collection."
  syntax:
    content: public void Add (System.ServiceModel.Routing.Configuration.FilterTableEntryElement element);
    parameters:
    - id: element
      type: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
      description: "The filter table entry to be added."
  overload: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.Add*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.Clear
  id: Clear
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection
  langs:
  - csharp
  name: Clear()
  nameWithType: FilterTableEntryCollection.Clear()
  fullName: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.Clear()
  type: Method
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Removes all elements from the collection."
  syntax:
    content: public void Clear ();
    parameters: []
  overload: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.Clear*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.CreateNewElement
  id: CreateNewElement
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection
  langs:
  - csharp
  name: CreateNewElement()
  nameWithType: FilterTableEntryCollection.CreateNewElement()
  fullName: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.CreateNewElement()
  type: Method
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Creates a new <see cref=&quot;T:System.Configuration.ConfigurationElement&quot;></see>."
  syntax:
    content: protected override System.Configuration.ConfigurationElement CreateNewElement ();
    parameters: []
    return:
      type: System.Configuration.ConfigurationElement
      description: "To be added."
  overload: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.CreateNewElement*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.GetElementKey(System.Configuration.ConfigurationElement)
  id: GetElementKey(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection
  langs:
  - csharp
  name: GetElementKey(ConfigurationElement)
  nameWithType: FilterTableEntryCollection.GetElementKey(ConfigurationElement)
  fullName: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.GetElementKey(ConfigurationElement)
  type: Method
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Gets the element key for the specified configuration element."
  syntax:
    content: protected override object GetElementKey (System.Configuration.ConfigurationElement element);
    parameters:
    - id: element
      type: System.Configuration.ConfigurationElement
      description: "The configuration element to return the key for."
    return:
      type: System.Object
      description: "To be added."
  overload: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.GetElementKey*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.Name
  id: Name
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection
  langs:
  - csharp
  name: Name
  nameWithType: FilterTableEntryCollection.Name
  fullName: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.Name
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Gets or sets the name of this configuration element."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "The unique name of this configuration element."
  overload: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.Name*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.Remove(System.ServiceModel.Routing.Configuration.FilterTableEntryElement)
  id: Remove(System.ServiceModel.Routing.Configuration.FilterTableEntryElement)
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection
  langs:
  - csharp
  name: Remove(FilterTableEntryElement)
  nameWithType: FilterTableEntryCollection.Remove(FilterTableEntryElement)
  fullName: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.Remove(FilterTableEntryElement)
  type: Method
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Removes the first occurrence of the specified <see cref=&quot;T:System.ServiceModel.Routing.Configuration.FilterTableEntryElement&quot;></see> from the collection."
  syntax:
    content: public void Remove (System.ServiceModel.Routing.Configuration.FilterTableEntryElement element);
    parameters:
    - id: element
      type: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
      description: "The filter table entry to remove from the collection."
  overload: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.Remove*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElementCollection
  isExternal: false
  name: System.Configuration.ConfigurationElementCollection
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.#ctor
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection
  isExternal: false
  name: FilterTableEntryCollection()
  nameWithType: FilterTableEntryCollection.FilterTableEntryCollection()
  fullName: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.FilterTableEntryCollection()
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.Add(System.ServiceModel.Routing.Configuration.FilterTableEntryElement)
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection
  isExternal: false
  name: Add(FilterTableEntryElement)
  nameWithType: FilterTableEntryCollection.Add(FilterTableEntryElement)
  fullName: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.Add(FilterTableEntryElement)
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  parent: System.ServiceModel.Routing.Configuration
  isExternal: false
  name: FilterTableEntryElement
  nameWithType: FilterTableEntryElement
  fullName: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.Clear
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection
  isExternal: false
  name: Clear()
  nameWithType: FilterTableEntryCollection.Clear()
  fullName: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.Clear()
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.CreateNewElement
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection
  isExternal: false
  name: CreateNewElement()
  nameWithType: FilterTableEntryCollection.CreateNewElement()
  fullName: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.CreateNewElement()
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.GetElementKey(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection
  isExternal: false
  name: GetElementKey(ConfigurationElement)
  nameWithType: FilterTableEntryCollection.GetElementKey(ConfigurationElement)
  fullName: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.GetElementKey(ConfigurationElement)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.Name
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection
  isExternal: false
  name: Name
  nameWithType: FilterTableEntryCollection.Name
  fullName: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.Name
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.Remove(System.ServiceModel.Routing.Configuration.FilterTableEntryElement)
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection
  isExternal: false
  name: Remove(FilterTableEntryElement)
  nameWithType: FilterTableEntryCollection.Remove(FilterTableEntryElement)
  fullName: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.Remove(FilterTableEntryElement)
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.#ctor*
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection
  isExternal: false
  name: FilterTableEntryCollection
  nameWithType: FilterTableEntryCollection.FilterTableEntryCollection
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.Add*
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection
  isExternal: false
  name: Add
  nameWithType: FilterTableEntryCollection.Add
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.Clear*
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection
  isExternal: false
  name: Clear
  nameWithType: FilterTableEntryCollection.Clear
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.CreateNewElement*
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection
  isExternal: false
  name: CreateNewElement
  nameWithType: FilterTableEntryCollection.CreateNewElement
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.GetElementKey*
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection
  isExternal: false
  name: GetElementKey
  nameWithType: FilterTableEntryCollection.GetElementKey
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.Name*
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection
  isExternal: false
  name: Name
  nameWithType: FilterTableEntryCollection.Name
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection.Remove*
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryCollection
  isExternal: false
  name: Remove
  nameWithType: FilterTableEntryCollection.Remove
