### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationCollectionAttribute
  id: ConfigurationCollectionAttribute
  children:
  - System.Configuration.ConfigurationCollectionAttribute.#ctor(System.Type)
  - System.Configuration.ConfigurationCollectionAttribute.AddItemName
  - System.Configuration.ConfigurationCollectionAttribute.ClearItemsName
  - System.Configuration.ConfigurationCollectionAttribute.CollectionType
  - System.Configuration.ConfigurationCollectionAttribute.ItemType
  - System.Configuration.ConfigurationCollectionAttribute.RemoveItemName
  langs:
  - csharp
  name: ConfigurationCollectionAttribute
  nameWithType: ConfigurationCollectionAttribute
  fullName: System.Configuration.ConfigurationCollectionAttribute
  type: Class
  summary: "Declaratively instructs the .NET Framework to create an instance of a configuration element collection. This class cannot be inherited."
  remarks: "You use the ConfigurationCollectionAttribute attribute to decorate a <xref:System.Configuration.ConfigurationElementCollection> element. This instructs the .NET Framework to create an instance of the collection and to initialize it using your custom <xref:System.Configuration.ConfigurationElement> values.      > [!NOTE] >  The simplest way to create a custom configuration element is to use the attributed (declarative) model. You declare the elements and decorate them with the ConfigurationCollectionAttribute attribute. For each element marked with this attribute, the .NET Framework uses reflection to read the decorating parameters and create a related <xref:System.Configuration.ConfigurationElementCollection> instance. You can also use the programmatic model. In this case it is your responsibility to declare the custom public collection but also to override the <xref:System.Configuration.ConfigurationElementCollection> member and return the properties collection.       The .NET Framework configuration system provides attribute types that you can use during the creation of custom configuration elements. There are two kinds of attributes:      -   The attributes that instruct the .NET Framework how to create instances of the custom configuration element properties. These types include:          -   ConfigurationCollectionAttribute          -   <xref:System.Configuration.ConfigurationPropertyAttribute>      -   The attributes that instruct the .NET Framework how to validate the custom configuration element properties. These types include:          -   <xref:System.Configuration.IntegerValidatorAttribute>          -   <xref:System.Configuration.LongValidatorAttribute>          -   <xref:System.Configuration.RegexStringValidatorAttribute>          -   <xref:System.Configuration.StringValidatorAttribute>          -   <xref:System.Configuration.TimeSpanValidatorAttribute>"
  example:
  - "The following example shows how to use the ConfigurationCollectionAttribute.  \n  \n This example consists of three classes: `UrlsSection`, `UrlsCollection` and `UrlConfigElement`.The `UrlsSection` class uses the ConfigurationCollectionAttribute to define a custom configuration section. This section contains a URL collection (defined by the `UrlsCollection` class) of URL elements (defined by the `UrlConfigElement` class). When you run the example, an instance of the `UrlsSection` class is created and the following configuration elements are generated in the application configuration file:  \n  \n```  \n<configuration>  \n    <configSections>  \n        <section name=\"MyUrls\" type=\"UrlsSection,   \n          ConfigurationCollectionAttribute, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null\" />  \n    </configSections>  \n    <MyUrls>  \n        <urls>  \n            <remove name=\"Contoso\" />  \n            <add name=\"Contoso\" url=\"http://www.contoso.com\" port=\"0\" />  \n        </urls>  \n    </MyUrls>  \n</configuration  \n```  \n  \n [!code-cs[System.Configuration.ConfigurationCollectionAttribute#1](~/add/codesnippet/CSharp/t-system.configuration.c_7_1.cs)]\n [!code-vb[System.Configuration.ConfigurationCollectionAttribute#1](~/add/codesnippet/VisualBasic/t-system.configuration.c_7_1.vb)]  \n  \n [!code-cs[System.Configuration.ConfigurationCollectionAttribute#31](~/add/codesnippet/CSharp/t-system.configuration.c_7_2.cs)]\n [!code-vb[System.Configuration.ConfigurationCollectionAttribute#31](~/add/codesnippet/VisualBasic/t-system.configuration.c_7_2.vb)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Property)]

      public sealed class ConfigurationCollectionAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationCollectionAttribute.#ctor(System.Type)
  id: '#ctor(System.Type)'
  parent: System.Configuration.ConfigurationCollectionAttribute
  langs:
  - csharp
  name: ConfigurationCollectionAttribute(Type)
  nameWithType: ConfigurationCollectionAttribute.ConfigurationCollectionAttribute(Type)
  fullName: System.Configuration.ConfigurationCollectionAttribute.ConfigurationCollectionAttribute(Type)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.ConfigurationCollectionAttribute&quot;></see> class."
  remarks: "You use this constructor to tell the .NET Framework the custom type of the property collection to be created."
  example:
  - "The following example shows how to use the ConfigurationCollectionAttribute.  \n  \n [!code-cs[System.Configuration.ConfigurationCollectionAttribute#20](~/add/codesnippet/CSharp/m-system.configuration.c_25_1.cs)]\n [!code-vb[System.Configuration.ConfigurationCollectionAttribute#20](~/add/codesnippet/VisualBasic/m-system.configuration.c_25_1.vb)]"
  syntax:
    content: public ConfigurationCollectionAttribute (Type itemType);
    parameters:
    - id: itemType
      type: System.Type
      description: "The type of the property collection to create."
  overload: System.Configuration.ConfigurationCollectionAttribute.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "\n    itemType is ."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationCollectionAttribute.AddItemName
  id: AddItemName
  parent: System.Configuration.ConfigurationCollectionAttribute
  langs:
  - csharp
  name: AddItemName
  nameWithType: ConfigurationCollectionAttribute.AddItemName
  fullName: System.Configuration.ConfigurationCollectionAttribute.AddItemName
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets or sets the name of the <xref uid=&quot;langword_csharp_&lt;add&gt;&quot; name=&quot;&lt;add&gt;&quot; href=&quot;&quot;></xref> configuration element."
  remarks: "The AddItemName property allows you to assign a different name to the configuration element. For example, you could use `addUrl` instead of &quot;add&quot;."
  example:
  - "The following example shows how to use the AddItemName property.  \n  \n [!code-cs[System.Configuration.ConfigurationCollectionAttribute#20](~/add/codesnippet/CSharp/p-system.configuration.c_47_1.cs)]\n [!code-vb[System.Configuration.ConfigurationCollectionAttribute#20](~/add/codesnippet/VisualBasic/p-system.configuration.c_47_1.vb)]"
  syntax:
    content: public string AddItemName { get; set; }
    return:
      type: System.String
      description: "The name that substitutes the standard name &quot;add&quot; for the configuration item."
  overload: System.Configuration.ConfigurationCollectionAttribute.AddItemName*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationCollectionAttribute.ClearItemsName
  id: ClearItemsName
  parent: System.Configuration.ConfigurationCollectionAttribute
  langs:
  - csharp
  name: ClearItemsName
  nameWithType: ConfigurationCollectionAttribute.ClearItemsName
  fullName: System.Configuration.ConfigurationCollectionAttribute.ClearItemsName
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets or sets the name for the <xref uid=&quot;langword_csharp_&lt;clear&gt;&quot; name=&quot;&lt;clear&gt;&quot; href=&quot;&quot;></xref> configuration element."
  remarks: "The ClearItemsName property allows you to assign a different name to the `<clear>` configuration element. For example, you could use `clearUrls` instead of &quot;clear&quot;."
  example:
  - "The following example shows how to use the ClearItemsName.  \n  \n [!code-cs[System.Configuration.ConfigurationCollectionAttribute#20](~/add/codesnippet/CSharp/p-system.configuration.c_18_1.cs)]\n [!code-vb[System.Configuration.ConfigurationCollectionAttribute#20](~/add/codesnippet/VisualBasic/p-system.configuration.c_18_1.vb)]"
  syntax:
    content: public string ClearItemsName { get; set; }
    return:
      type: System.String
      description: "The name that replaces the standard name &quot;clear&quot; for the configuration item."
  overload: System.Configuration.ConfigurationCollectionAttribute.ClearItemsName*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationCollectionAttribute.CollectionType
  id: CollectionType
  parent: System.Configuration.ConfigurationCollectionAttribute
  langs:
  - csharp
  name: CollectionType
  nameWithType: ConfigurationCollectionAttribute.CollectionType
  fullName: System.Configuration.ConfigurationCollectionAttribute.CollectionType
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets or sets the type of the <see cref=&quot;T:System.Configuration.ConfigurationCollectionAttribute&quot;></see> attribute."
  syntax:
    content: public System.Configuration.ConfigurationElementCollectionType CollectionType { get; set; }
    return:
      type: System.Configuration.ConfigurationElementCollectionType
      description: "The type of the <see cref=&quot;T:System.Configuration.ConfigurationCollectionAttribute&quot;></see>."
  overload: System.Configuration.ConfigurationCollectionAttribute.CollectionType*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationCollectionAttribute.ItemType
  id: ItemType
  parent: System.Configuration.ConfigurationCollectionAttribute
  langs:
  - csharp
  name: ItemType
  nameWithType: ConfigurationCollectionAttribute.ItemType
  fullName: System.Configuration.ConfigurationCollectionAttribute.ItemType
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets the type of the collection element."
  remarks: "The ItemType property is used by reflection to get the configuration element type."
  syntax:
    content: public Type ItemType { get; }
    return:
      type: System.Type
      description: "The type of the collection element."
  overload: System.Configuration.ConfigurationCollectionAttribute.ItemType*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ConfigurationCollectionAttribute.RemoveItemName
  id: RemoveItemName
  parent: System.Configuration.ConfigurationCollectionAttribute
  langs:
  - csharp
  name: RemoveItemName
  nameWithType: ConfigurationCollectionAttribute.RemoveItemName
  fullName: System.Configuration.ConfigurationCollectionAttribute.RemoveItemName
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets or sets the name for the <xref uid=&quot;langword_csharp_&lt;remove&gt;&quot; name=&quot;&lt;remove&gt;&quot; href=&quot;&quot;></xref> configuration element."
  remarks: "The RemoveItemName property allows you to assign a different name to the `<remove>` configuration element. For example, you could use `removeUrl` instead of &quot;remove&quot;."
  example:
  - "The following example shows how to use the RemoveItemName property.  \n  \n [!code-cs[System.Configuration.ConfigurationCollectionAttribute#20](~/add/codesnippet/CSharp/p-system.configuration.c_41_1.cs)]\n [!code-vb[System.Configuration.ConfigurationCollectionAttribute#20](~/add/codesnippet/VisualBasic/p-system.configuration.c_41_1.vb)]"
  syntax:
    content: public string RemoveItemName { get; set; }
    return:
      type: System.String
      description: "The name that replaces the standard name &quot;remove&quot; for the configuration element."
  overload: System.Configuration.ConfigurationCollectionAttribute.RemoveItemName*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.ConfigurationCollectionAttribute.#ctor(System.Type)
  parent: System.Configuration.ConfigurationCollectionAttribute
  isExternal: false
  name: ConfigurationCollectionAttribute(Type)
  nameWithType: ConfigurationCollectionAttribute.ConfigurationCollectionAttribute(Type)
  fullName: System.Configuration.ConfigurationCollectionAttribute.ConfigurationCollectionAttribute(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.ConfigurationCollectionAttribute.AddItemName
  parent: System.Configuration.ConfigurationCollectionAttribute
  isExternal: false
  name: AddItemName
  nameWithType: ConfigurationCollectionAttribute.AddItemName
  fullName: System.Configuration.ConfigurationCollectionAttribute.AddItemName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationCollectionAttribute.ClearItemsName
  parent: System.Configuration.ConfigurationCollectionAttribute
  isExternal: false
  name: ClearItemsName
  nameWithType: ConfigurationCollectionAttribute.ClearItemsName
  fullName: System.Configuration.ConfigurationCollectionAttribute.ClearItemsName
- uid: System.Configuration.ConfigurationCollectionAttribute.CollectionType
  parent: System.Configuration.ConfigurationCollectionAttribute
  isExternal: false
  name: CollectionType
  nameWithType: ConfigurationCollectionAttribute.CollectionType
  fullName: System.Configuration.ConfigurationCollectionAttribute.CollectionType
- uid: System.Configuration.ConfigurationElementCollectionType
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElementCollectionType
  nameWithType: ConfigurationElementCollectionType
  fullName: System.Configuration.ConfigurationElementCollectionType
- uid: System.Configuration.ConfigurationCollectionAttribute.ItemType
  parent: System.Configuration.ConfigurationCollectionAttribute
  isExternal: false
  name: ItemType
  nameWithType: ConfigurationCollectionAttribute.ItemType
  fullName: System.Configuration.ConfigurationCollectionAttribute.ItemType
- uid: System.Configuration.ConfigurationCollectionAttribute.RemoveItemName
  parent: System.Configuration.ConfigurationCollectionAttribute
  isExternal: false
  name: RemoveItemName
  nameWithType: ConfigurationCollectionAttribute.RemoveItemName
  fullName: System.Configuration.ConfigurationCollectionAttribute.RemoveItemName
- uid: System.Configuration.ConfigurationCollectionAttribute.#ctor*
  parent: System.Configuration.ConfigurationCollectionAttribute
  isExternal: false
  name: ConfigurationCollectionAttribute
  nameWithType: ConfigurationCollectionAttribute.ConfigurationCollectionAttribute
- uid: System.Configuration.ConfigurationCollectionAttribute.AddItemName*
  parent: System.Configuration.ConfigurationCollectionAttribute
  isExternal: false
  name: AddItemName
  nameWithType: ConfigurationCollectionAttribute.AddItemName
- uid: System.Configuration.ConfigurationCollectionAttribute.ClearItemsName*
  parent: System.Configuration.ConfigurationCollectionAttribute
  isExternal: false
  name: ClearItemsName
  nameWithType: ConfigurationCollectionAttribute.ClearItemsName
- uid: System.Configuration.ConfigurationCollectionAttribute.CollectionType*
  parent: System.Configuration.ConfigurationCollectionAttribute
  isExternal: false
  name: CollectionType
  nameWithType: ConfigurationCollectionAttribute.CollectionType
- uid: System.Configuration.ConfigurationCollectionAttribute.ItemType*
  parent: System.Configuration.ConfigurationCollectionAttribute
  isExternal: false
  name: ItemType
  nameWithType: ConfigurationCollectionAttribute.ItemType
- uid: System.Configuration.ConfigurationCollectionAttribute.RemoveItemName*
  parent: System.Configuration.ConfigurationCollectionAttribute
  isExternal: false
  name: RemoveItemName
  nameWithType: ConfigurationCollectionAttribute.RemoveItemName
