### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.IConfigurationManagerHelper
  id: IConfigurationManagerHelper
  children:
  - System.Configuration.Internal.IConfigurationManagerHelper.EnsureNetConfigLoaded
  langs:
  - csharp
  name: IConfigurationManagerHelper
  nameWithType: IConfigurationManagerHelper
  fullName: System.Configuration.Internal.IConfigurationManagerHelper
  type: Interface
  summary: "Defines an interface used by the .NET Framework to support configuration management."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public interface IConfigurationManagerHelper
  implements: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.Internal.IConfigurationManagerHelper.EnsureNetConfigLoaded
  id: EnsureNetConfigLoaded
  parent: System.Configuration.Internal.IConfigurationManagerHelper
  langs:
  - csharp
  name: EnsureNetConfigLoaded()
  nameWithType: IConfigurationManagerHelper.EnsureNetConfigLoaded()
  fullName: System.Configuration.Internal.IConfigurationManagerHelper.EnsureNetConfigLoaded()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Ensures that the networking configuration is loaded."
  remarks: "This method is used to prevent deadlocks in the networking classes by ensuring that networking configuration is loaded before networking requests are made."
  syntax:
    content: public void EnsureNetConfigLoaded ();
    parameters: []
  overload: System.Configuration.Internal.IConfigurationManagerHelper.EnsureNetConfigLoaded*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.Internal.IConfigurationManagerHelper.EnsureNetConfigLoaded
  parent: System.Configuration.Internal.IConfigurationManagerHelper
  isExternal: false
  name: EnsureNetConfigLoaded()
  nameWithType: IConfigurationManagerHelper.EnsureNetConfigLoaded()
  fullName: System.Configuration.Internal.IConfigurationManagerHelper.EnsureNetConfigLoaded()
- uid: System.Configuration.Internal.IConfigurationManagerHelper.EnsureNetConfigLoaded*
  parent: System.Configuration.Internal.IConfigurationManagerHelper
  isExternal: false
  name: EnsureNetConfigLoaded
  nameWithType: IConfigurationManagerHelper.EnsureNetConfigLoaded
