### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ExtensionsSection
  id: ExtensionsSection
  children:
  - System.ServiceModel.Configuration.ExtensionsSection.#ctor
  - System.ServiceModel.Configuration.ExtensionsSection.BehaviorExtensions
  - System.ServiceModel.Configuration.ExtensionsSection.BindingElementExtensions
  - System.ServiceModel.Configuration.ExtensionsSection.BindingExtensions
  - System.ServiceModel.Configuration.ExtensionsSection.EndpointExtensions
  - System.ServiceModel.Configuration.ExtensionsSection.InitializeDefault
  - System.ServiceModel.Configuration.ExtensionsSection.Properties
  langs:
  - csharp
  name: ExtensionsSection
  nameWithType: ExtensionsSection
  fullName: System.ServiceModel.Configuration.ExtensionsSection
  type: Class
  summary: "Represents a configuration section that contains all the extension definitions."
  syntax:
    content: 'public class ExtensionsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ExtensionsSection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ExtensionsSection
  langs:
  - csharp
  name: ExtensionsSection()
  nameWithType: ExtensionsSection.ExtensionsSection()
  fullName: System.ServiceModel.Configuration.ExtensionsSection.ExtensionsSection()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.ExtensionsSection&quot;></see> class."
  syntax:
    content: public ExtensionsSection ();
    parameters: []
  overload: System.ServiceModel.Configuration.ExtensionsSection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ExtensionsSection.BehaviorExtensions
  id: BehaviorExtensions
  parent: System.ServiceModel.Configuration.ExtensionsSection
  langs:
  - csharp
  name: BehaviorExtensions
  nameWithType: ExtensionsSection.BehaviorExtensions
  fullName: System.ServiceModel.Configuration.ExtensionsSection.BehaviorExtensions
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets all the behavior extensions that are defined in the section."
  remarks: "Behavior extensions enable the user to create user-defined behavior elements. These elements can be used alongside the standard [!INCLUDE[indigo1](~/add/includes/indigo1-md.md)] behavior elements."
  syntax:
    content: public System.ServiceModel.Configuration.ExtensionElementCollection BehaviorExtensions { get; }
    return:
      type: System.ServiceModel.Configuration.ExtensionElementCollection
      description: "A collection of behavior extensions."
  overload: System.ServiceModel.Configuration.ExtensionsSection.BehaviorExtensions*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ExtensionsSection.BindingElementExtensions
  id: BindingElementExtensions
  parent: System.ServiceModel.Configuration.ExtensionsSection
  langs:
  - csharp
  name: BindingElementExtensions
  nameWithType: ExtensionsSection.BindingElementExtensions
  fullName: System.ServiceModel.Configuration.ExtensionsSection.BindingElementExtensions
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets all the binding element extensions that are defined in the section."
  syntax:
    content: public System.ServiceModel.Configuration.ExtensionElementCollection BindingElementExtensions { get; }
    return:
      type: System.ServiceModel.Configuration.ExtensionElementCollection
      description: "A collection of binding element extensions."
  overload: System.ServiceModel.Configuration.ExtensionsSection.BindingElementExtensions*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ExtensionsSection.BindingExtensions
  id: BindingExtensions
  parent: System.ServiceModel.Configuration.ExtensionsSection
  langs:
  - csharp
  name: BindingExtensions
  nameWithType: ExtensionsSection.BindingExtensions
  fullName: System.ServiceModel.Configuration.ExtensionsSection.BindingExtensions
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets all the binding extensions that are defined in the section."
  remarks: "Binding extensions enable the user to create user-defined binding elements for use as part of custom bindings. Programmatically, a binding extension is a type that implements the abstract class BindingElement."
  syntax:
    content: public System.ServiceModel.Configuration.ExtensionElementCollection BindingExtensions { get; }
    return:
      type: System.ServiceModel.Configuration.ExtensionElementCollection
      description: "A collection of binding extensions."
  overload: System.ServiceModel.Configuration.ExtensionsSection.BindingExtensions*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ExtensionsSection.EndpointExtensions
  id: EndpointExtensions
  parent: System.ServiceModel.Configuration.ExtensionsSection
  langs:
  - csharp
  name: EndpointExtensions
  nameWithType: ExtensionsSection.EndpointExtensions
  fullName: System.ServiceModel.Configuration.ExtensionsSection.EndpointExtensions
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets an <see cref=&quot;T:System.ServiceModel.Configuration.ExtensionElementCollection&quot;></see> object  that contains the specified endpoint extension."
  syntax:
    content: public System.ServiceModel.Configuration.ExtensionElementCollection EndpointExtensions { get; }
    return:
      type: System.ServiceModel.Configuration.ExtensionElementCollection
      description: "A collection of endpoint extensions."
  overload: System.ServiceModel.Configuration.ExtensionsSection.EndpointExtensions*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ExtensionsSection.InitializeDefault
  id: InitializeDefault
  parent: System.ServiceModel.Configuration.ExtensionsSection
  langs:
  - csharp
  name: InitializeDefault()
  nameWithType: ExtensionsSection.InitializeDefault()
  fullName: System.ServiceModel.Configuration.ExtensionsSection.InitializeDefault()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a default set of values for this configuration section."
  syntax:
    content: protected override void InitializeDefault ();
    parameters: []
  overload: System.ServiceModel.Configuration.ExtensionsSection.InitializeDefault*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ExtensionsSection.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ExtensionsSection
  langs:
  - csharp
  name: Properties
  nameWithType: ExtensionsSection.Properties
  fullName: System.ServiceModel.Configuration.ExtensionsSection.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets a <see cref=&quot;T:System.Configuration.ConfigurationPropertyCollection&quot;></see> instance that contains a collection of <see cref=&quot;T:System.Configuration.ConfigurationProperty&quot;></see> objects that can be attributes or <see cref=&quot;T:System.Configuration.ConfigurationElement&quot;></see> objects of this configuration element."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A <see cref=&quot;T:System.Configuration.ConfigurationPropertyCollection&quot;></see> instance that contains a collection of <see cref=&quot;T:System.Configuration.ConfigurationProperty&quot;></see> objects that can be attributes or <see cref=&quot;T:System.Configuration.ConfigurationElement&quot;></see> objects of this configuration element."
  overload: System.ServiceModel.Configuration.ExtensionsSection.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.ServiceModel.Configuration.ExtensionsSection.#ctor
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: ExtensionsSection()
  nameWithType: ExtensionsSection.ExtensionsSection()
  fullName: System.ServiceModel.Configuration.ExtensionsSection.ExtensionsSection()
- uid: System.ServiceModel.Configuration.ExtensionsSection.BehaviorExtensions
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: BehaviorExtensions
  nameWithType: ExtensionsSection.BehaviorExtensions
  fullName: System.ServiceModel.Configuration.ExtensionsSection.BehaviorExtensions
- uid: System.ServiceModel.Configuration.ExtensionElementCollection
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ExtensionElementCollection
  nameWithType: ExtensionElementCollection
  fullName: System.ServiceModel.Configuration.ExtensionElementCollection
- uid: System.ServiceModel.Configuration.ExtensionsSection.BindingElementExtensions
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: BindingElementExtensions
  nameWithType: ExtensionsSection.BindingElementExtensions
  fullName: System.ServiceModel.Configuration.ExtensionsSection.BindingElementExtensions
- uid: System.ServiceModel.Configuration.ExtensionsSection.BindingExtensions
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: BindingExtensions
  nameWithType: ExtensionsSection.BindingExtensions
  fullName: System.ServiceModel.Configuration.ExtensionsSection.BindingExtensions
- uid: System.ServiceModel.Configuration.ExtensionsSection.EndpointExtensions
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: EndpointExtensions
  nameWithType: ExtensionsSection.EndpointExtensions
  fullName: System.ServiceModel.Configuration.ExtensionsSection.EndpointExtensions
- uid: System.ServiceModel.Configuration.ExtensionsSection.InitializeDefault
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: InitializeDefault()
  nameWithType: ExtensionsSection.InitializeDefault()
  fullName: System.ServiceModel.Configuration.ExtensionsSection.InitializeDefault()
- uid: System.ServiceModel.Configuration.ExtensionsSection.Properties
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: Properties
  nameWithType: ExtensionsSection.Properties
  fullName: System.ServiceModel.Configuration.ExtensionsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ExtensionsSection.#ctor*
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: ExtensionsSection
  nameWithType: ExtensionsSection.ExtensionsSection
- uid: System.ServiceModel.Configuration.ExtensionsSection.BehaviorExtensions*
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: BehaviorExtensions
  nameWithType: ExtensionsSection.BehaviorExtensions
- uid: System.ServiceModel.Configuration.ExtensionsSection.BindingElementExtensions*
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: BindingElementExtensions
  nameWithType: ExtensionsSection.BindingElementExtensions
- uid: System.ServiceModel.Configuration.ExtensionsSection.BindingExtensions*
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: BindingExtensions
  nameWithType: ExtensionsSection.BindingExtensions
- uid: System.ServiceModel.Configuration.ExtensionsSection.EndpointExtensions*
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: EndpointExtensions
  nameWithType: ExtensionsSection.EndpointExtensions
- uid: System.ServiceModel.Configuration.ExtensionsSection.InitializeDefault*
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: InitializeDefault
  nameWithType: ExtensionsSection.InitializeDefault
- uid: System.ServiceModel.Configuration.ExtensionsSection.Properties*
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: Properties
  nameWithType: ExtensionsSection.Properties
