### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsContext
  id: SettingsContext
  children:
  - System.Configuration.SettingsContext.#ctor
  langs:
  - csharp
  name: SettingsContext
  nameWithType: SettingsContext
  fullName: System.Configuration.SettingsContext
  type: Class
  summary: "Provides contextual information that the provider can use when persisting settings."
  remarks: "The SettingsContext class is the base class used by applications to provide contextual information to the settings provider. Although the class is not abstract, an application can choose to create a specialized class that inherits from SettingsContext class and provides additional information to specific types of providers. The provider can then examine contextual settings when writing properties.       The primary purpose of the SettingsContext class is to provide features that use the <xref:System.Configuration.SettingsBase> class and related infrastructure. The SettingsContext class provides additional feature-specific contextual information about the property data being stored by the <xref:System.Configuration.SettingsBase> instance. Therefore, it is very simple to store additional information in a SettingsContext class without deriving from it (or from other Settings* classes) in order to support additional feature-specific context information.       For example, ASP.NET uses the SettingsContext class to pass along the username associated with the data managed by a <xref:System.Configuration.SettingsBase> instance, as well as a property indicating whether the user is considered authenticated. In this way, ASP.NET uses the SettingsContext class to identify authenticated versus anonymous Profile data."
  syntax:
    content: 'public class SettingsContext : System.Collections.Hashtable'
  inheritance:
  - System.Object
  - System.Collections.Hashtable
  implements: []
  inheritedMembers:
  - System.Collections.Hashtable.Add(System.Object,System.Object)
  - System.Collections.Hashtable.Clear
  - System.Collections.Hashtable.Clone
  - System.Collections.Hashtable.comparer
  - System.Collections.Hashtable.Contains(System.Object)
  - System.Collections.Hashtable.ContainsKey(System.Object)
  - System.Collections.Hashtable.ContainsValue(System.Object)
  - System.Collections.Hashtable.CopyTo(System.Array,System.Int32)
  - System.Collections.Hashtable.Count
  - System.Collections.Hashtable.EqualityComparer
  - System.Collections.Hashtable.GetEnumerator
  - System.Collections.Hashtable.GetHash(System.Object)
  - System.Collections.Hashtable.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Collections.Hashtable.hcp
  - System.Collections.Hashtable.IsFixedSize
  - System.Collections.Hashtable.IsReadOnly
  - System.Collections.Hashtable.IsSynchronized
  - System.Collections.Hashtable.Item(System.Object)
  - System.Collections.Hashtable.KeyEquals(System.Object,System.Object)
  - System.Collections.Hashtable.Keys
  - System.Collections.Hashtable.OnDeserialization(System.Object)
  - System.Collections.Hashtable.Remove(System.Object)
  - System.Collections.Hashtable.Synchronized(System.Collections.Hashtable)
  - System.Collections.Hashtable.SyncRoot
  - System.Collections.Hashtable.System#Collections#IEnumerable#GetEnumerator
  - System.Collections.Hashtable.Values
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SettingsContext.#ctor
  id: '#ctor'
  parent: System.Configuration.SettingsContext
  langs:
  - csharp
  name: SettingsContext()
  nameWithType: SettingsContext.SettingsContext()
  fullName: System.Configuration.SettingsContext.SettingsContext()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.SettingsContext&quot;></see> class."
  syntax:
    content: public SettingsContext ();
    parameters: []
  overload: System.Configuration.SettingsContext.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Collections.Hashtable
  isExternal: false
  name: System.Collections.Hashtable
- uid: System.Configuration.SettingsContext.#ctor
  parent: System.Configuration.SettingsContext
  isExternal: false
  name: SettingsContext()
  nameWithType: SettingsContext.SettingsContext()
  fullName: System.Configuration.SettingsContext.SettingsContext()
- uid: System.Configuration.SettingsContext.#ctor*
  parent: System.Configuration.SettingsContext
  isExternal: false
  name: SettingsContext
  nameWithType: SettingsContext.SettingsContext
