### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ClaimTypeElement
  id: ClaimTypeElement
  children:
  - System.ServiceModel.Configuration.ClaimTypeElement.#ctor
  - System.ServiceModel.Configuration.ClaimTypeElement.#ctor(System.String,System.Boolean)
  - System.ServiceModel.Configuration.ClaimTypeElement.ClaimType
  - System.ServiceModel.Configuration.ClaimTypeElement.IsOptional
  - System.ServiceModel.Configuration.ClaimTypeElement.Properties
  langs:
  - csharp
  name: ClaimTypeElement
  nameWithType: ClaimTypeElement
  fullName: System.ServiceModel.Configuration.ClaimTypeElement
  type: Class
  summary: "Represents a configuration element that contains the type of claim. This class cannot be inherited."
  syntax:
    content: 'public sealed class ClaimTypeElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ClaimTypeElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ClaimTypeElement
  langs:
  - csharp
  name: ClaimTypeElement()
  nameWithType: ClaimTypeElement.ClaimTypeElement()
  fullName: System.ServiceModel.Configuration.ClaimTypeElement.ClaimTypeElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.ClaimTypeElement&quot;></see> class."
  syntax:
    content: public ClaimTypeElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.ClaimTypeElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ClaimTypeElement.#ctor(System.String,System.Boolean)
  id: '#ctor(System.String,System.Boolean)'
  parent: System.ServiceModel.Configuration.ClaimTypeElement
  langs:
  - csharp
  name: ClaimTypeElement(String,Boolean)
  nameWithType: ClaimTypeElement.ClaimTypeElement(String,Boolean)
  fullName: System.ServiceModel.Configuration.ClaimTypeElement.ClaimTypeElement(String,Boolean)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.ClaimTypeElement&quot;></see> class."
  syntax:
    content: public ClaimTypeElement (string claimType, bool isOptional);
    parameters:
    - id: claimType
      type: System.String
      description: "A uniform resource identifier (URI) that specifies the type of claim. Predefined claim types are available as static properties of the  class."
    - id: isOptional
      type: System.Boolean
      description: "A boolean value that specifies whether the claim is optional."
  overload: System.ServiceModel.Configuration.ClaimTypeElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ClaimTypeElement.ClaimType
  id: ClaimType
  parent: System.ServiceModel.Configuration.ClaimTypeElement
  langs:
  - csharp
  name: ClaimType
  nameWithType: ClaimTypeElement.ClaimType
  fullName: System.ServiceModel.Configuration.ClaimTypeElement.ClaimType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets a string representation of a uniform resource identifier (URI) that specifies the type of claim."
  remarks: "Predefined claim types are available as static properties of the <xref:System.IdentityModel.Claims.ClaimTypes> class."
  syntax:
    content: public string ClaimType { get; set; }
    return:
      type: System.String
      description: "A uniform resource identifier (URI) that specifies the type of claim."
  overload: System.ServiceModel.Configuration.ClaimTypeElement.ClaimType*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ClaimTypeElement.IsOptional
  id: IsOptional
  parent: System.ServiceModel.Configuration.ClaimTypeElement
  langs:
  - csharp
  name: IsOptional
  nameWithType: ClaimTypeElement.IsOptional
  fullName: System.ServiceModel.Configuration.ClaimTypeElement.IsOptional
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets a boolean value that specifies whether the claim is optional."
  syntax:
    content: public bool IsOptional { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if the claim is optional; otherwise, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>."
  overload: System.ServiceModel.Configuration.ClaimTypeElement.IsOptional*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ClaimTypeElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ClaimTypeElement
  langs:
  - csharp
  name: Properties
  nameWithType: ClaimTypeElement.Properties
  fullName: System.ServiceModel.Configuration.ClaimTypeElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.ClaimTypeElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.ClaimTypeElement.#ctor
  parent: System.ServiceModel.Configuration.ClaimTypeElement
  isExternal: false
  name: ClaimTypeElement()
  nameWithType: ClaimTypeElement.ClaimTypeElement()
  fullName: System.ServiceModel.Configuration.ClaimTypeElement.ClaimTypeElement()
- uid: System.ServiceModel.Configuration.ClaimTypeElement.#ctor(System.String,System.Boolean)
  parent: System.ServiceModel.Configuration.ClaimTypeElement
  isExternal: false
  name: ClaimTypeElement(String,Boolean)
  nameWithType: ClaimTypeElement.ClaimTypeElement(String,Boolean)
  fullName: System.ServiceModel.Configuration.ClaimTypeElement.ClaimTypeElement(String,Boolean)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.ClaimTypeElement.ClaimType
  parent: System.ServiceModel.Configuration.ClaimTypeElement
  isExternal: false
  name: ClaimType
  nameWithType: ClaimTypeElement.ClaimType
  fullName: System.ServiceModel.Configuration.ClaimTypeElement.ClaimType
- uid: System.ServiceModel.Configuration.ClaimTypeElement.IsOptional
  parent: System.ServiceModel.Configuration.ClaimTypeElement
  isExternal: false
  name: IsOptional
  nameWithType: ClaimTypeElement.IsOptional
  fullName: System.ServiceModel.Configuration.ClaimTypeElement.IsOptional
- uid: System.ServiceModel.Configuration.ClaimTypeElement.Properties
  parent: System.ServiceModel.Configuration.ClaimTypeElement
  isExternal: false
  name: Properties
  nameWithType: ClaimTypeElement.Properties
  fullName: System.ServiceModel.Configuration.ClaimTypeElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ClaimTypeElement.#ctor*
  parent: System.ServiceModel.Configuration.ClaimTypeElement
  isExternal: false
  name: ClaimTypeElement
  nameWithType: ClaimTypeElement.ClaimTypeElement
- uid: System.ServiceModel.Configuration.ClaimTypeElement.ClaimType*
  parent: System.ServiceModel.Configuration.ClaimTypeElement
  isExternal: false
  name: ClaimType
  nameWithType: ClaimTypeElement.ClaimType
- uid: System.ServiceModel.Configuration.ClaimTypeElement.IsOptional*
  parent: System.ServiceModel.Configuration.ClaimTypeElement
  isExternal: false
  name: IsOptional
  nameWithType: ClaimTypeElement.IsOptional
- uid: System.ServiceModel.Configuration.ClaimTypeElement.Properties*
  parent: System.ServiceModel.Configuration.ClaimTypeElement
  isExternal: false
  name: Properties
  nameWithType: ClaimTypeElement.Properties
