### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.FcnMode
  id: FcnMode
  children:
  - System.Web.Configuration.FcnMode.Default
  - System.Web.Configuration.FcnMode.Disabled
  - System.Web.Configuration.FcnMode.NotSet
  - System.Web.Configuration.FcnMode.Single
  langs:
  - csharp
  name: FcnMode
  nameWithType: FcnMode
  fullName: System.Web.Configuration.FcnMode
  type: Enum
  summary: "Specifies behavior for file change notification (FCN) in the application."
  syntax:
    content: public enum FcnMode
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.FcnMode.Default
  id: Default
  parent: System.Web.Configuration.FcnMode
  langs:
  - csharp
  name: Default
  nameWithType: FcnMode.Default
  fullName: System.Web.Configuration.FcnMode.Default
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "For each subdirectory, the application creates an object that monitors the subdirectory. This is the default behavior."
  syntax:
    content: Default
    return:
      type: System.Web.Configuration.FcnMode
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.FcnMode.Disabled
  id: Disabled
  parent: System.Web.Configuration.FcnMode
  langs:
  - csharp
  name: Disabled
  nameWithType: FcnMode.Disabled
  fullName: System.Web.Configuration.FcnMode.Disabled
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "File change notification is disabled."
  syntax:
    content: Disabled
    return:
      type: System.Web.Configuration.FcnMode
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.FcnMode.NotSet
  id: NotSet
  parent: System.Web.Configuration.FcnMode
  langs:
  - csharp
  name: NotSet
  nameWithType: FcnMode.NotSet
  fullName: System.Web.Configuration.FcnMode.NotSet
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "File change notification is not set, so the application creates an object that monitors each subdirectory. This is the default behavior."
  syntax:
    content: NotSet
    return:
      type: System.Web.Configuration.FcnMode
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.FcnMode.Single
  id: Single
  parent: System.Web.Configuration.FcnMode
  langs:
  - csharp
  name: Single
  nameWithType: FcnMode.Single
  fullName: System.Web.Configuration.FcnMode.Single
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "The application creates one object to monitor the main directory and uses this object to monitor each subdirectory."
  syntax:
    content: Single
    return:
      type: System.Web.Configuration.FcnMode
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.FcnMode.Default
  parent: System.Web.Configuration.FcnMode
  isExternal: false
  name: Default
  nameWithType: FcnMode.Default
  fullName: System.Web.Configuration.FcnMode.Default
- uid: System.Web.Configuration.FcnMode
  parent: System.Web.Configuration
  isExternal: false
  name: FcnMode
  nameWithType: FcnMode
  fullName: System.Web.Configuration.FcnMode
- uid: System.Web.Configuration.FcnMode.Disabled
  parent: System.Web.Configuration.FcnMode
  isExternal: false
  name: Disabled
  nameWithType: FcnMode.Disabled
  fullName: System.Web.Configuration.FcnMode.Disabled
- uid: System.Web.Configuration.FcnMode.NotSet
  parent: System.Web.Configuration.FcnMode
  isExternal: false
  name: NotSet
  nameWithType: FcnMode.NotSet
  fullName: System.Web.Configuration.FcnMode.NotSet
- uid: System.Web.Configuration.FcnMode.Single
  parent: System.Web.Configuration.FcnMode
  isExternal: false
  name: Single
  nameWithType: FcnMode.Single
  fullName: System.Web.Configuration.FcnMode.Single
