### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ProtocolMappingSection
  id: ProtocolMappingSection
  children:
  - System.ServiceModel.Configuration.ProtocolMappingSection.#ctor
  - System.ServiceModel.Configuration.ProtocolMappingSection.InitializeDefault
  - System.ServiceModel.Configuration.ProtocolMappingSection.Properties
  - System.ServiceModel.Configuration.ProtocolMappingSection.ProtocolMappingCollection
  langs:
  - csharp
  name: ProtocolMappingSection
  nameWithType: ProtocolMappingSection
  fullName: System.ServiceModel.Configuration.ProtocolMappingSection
  type: Class
  summary: "Defines a collection of protocol mapping. This class is sealed."
  syntax:
    content: 'public sealed class ProtocolMappingSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ProtocolMappingSection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ProtocolMappingSection
  langs:
  - csharp
  name: ProtocolMappingSection()
  nameWithType: ProtocolMappingSection.ProtocolMappingSection()
  fullName: System.ServiceModel.Configuration.ProtocolMappingSection.ProtocolMappingSection()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Creates a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.ProtocolMappingSection&quot;></see> class."
  syntax:
    content: public ProtocolMappingSection ();
    parameters: []
  overload: System.ServiceModel.Configuration.ProtocolMappingSection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ProtocolMappingSection.InitializeDefault
  id: InitializeDefault
  parent: System.ServiceModel.Configuration.ProtocolMappingSection
  langs:
  - csharp
  name: InitializeDefault()
  nameWithType: ProtocolMappingSection.InitializeDefault()
  fullName: System.ServiceModel.Configuration.ProtocolMappingSection.InitializeDefault()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override void InitializeDefault ();
    parameters: []
  overload: System.ServiceModel.Configuration.ProtocolMappingSection.InitializeDefault*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ProtocolMappingSection.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ProtocolMappingSection
  langs:
  - csharp
  name: Properties
  nameWithType: ProtocolMappingSection.Properties
  fullName: System.ServiceModel.Configuration.ProtocolMappingSection.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.ProtocolMappingSection.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.ProtocolMappingSection.ProtocolMappingCollection
  id: ProtocolMappingCollection
  parent: System.ServiceModel.Configuration.ProtocolMappingSection
  langs:
  - csharp
  name: ProtocolMappingCollection
  nameWithType: ProtocolMappingSection.ProtocolMappingCollection
  fullName: System.ServiceModel.Configuration.ProtocolMappingSection.ProtocolMappingCollection
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets the name of the collection of protocol mapping elements."
  syntax:
    content: public System.ServiceModel.Configuration.ProtocolMappingElementCollection ProtocolMappingCollection { get; }
    return:
      type: System.ServiceModel.Configuration.ProtocolMappingElementCollection
      description: "A collection of protocol mapping elements."
  overload: System.ServiceModel.Configuration.ProtocolMappingSection.ProtocolMappingCollection*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.ServiceModel.Configuration.ProtocolMappingSection.#ctor
  parent: System.ServiceModel.Configuration.ProtocolMappingSection
  isExternal: false
  name: ProtocolMappingSection()
  nameWithType: ProtocolMappingSection.ProtocolMappingSection()
  fullName: System.ServiceModel.Configuration.ProtocolMappingSection.ProtocolMappingSection()
- uid: System.ServiceModel.Configuration.ProtocolMappingSection.InitializeDefault
  parent: System.ServiceModel.Configuration.ProtocolMappingSection
  isExternal: false
  name: InitializeDefault()
  nameWithType: ProtocolMappingSection.InitializeDefault()
  fullName: System.ServiceModel.Configuration.ProtocolMappingSection.InitializeDefault()
- uid: System.ServiceModel.Configuration.ProtocolMappingSection.Properties
  parent: System.ServiceModel.Configuration.ProtocolMappingSection
  isExternal: false
  name: Properties
  nameWithType: ProtocolMappingSection.Properties
  fullName: System.ServiceModel.Configuration.ProtocolMappingSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ProtocolMappingSection.ProtocolMappingCollection
  parent: System.ServiceModel.Configuration.ProtocolMappingSection
  isExternal: false
  name: ProtocolMappingCollection
  nameWithType: ProtocolMappingSection.ProtocolMappingCollection
  fullName: System.ServiceModel.Configuration.ProtocolMappingSection.ProtocolMappingCollection
- uid: System.ServiceModel.Configuration.ProtocolMappingElementCollection
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ProtocolMappingElementCollection
  nameWithType: ProtocolMappingElementCollection
  fullName: System.ServiceModel.Configuration.ProtocolMappingElementCollection
- uid: System.ServiceModel.Configuration.ProtocolMappingSection.#ctor*
  parent: System.ServiceModel.Configuration.ProtocolMappingSection
  isExternal: false
  name: ProtocolMappingSection
  nameWithType: ProtocolMappingSection.ProtocolMappingSection
- uid: System.ServiceModel.Configuration.ProtocolMappingSection.InitializeDefault*
  parent: System.ServiceModel.Configuration.ProtocolMappingSection
  isExternal: false
  name: InitializeDefault
  nameWithType: ProtocolMappingSection.InitializeDefault
- uid: System.ServiceModel.Configuration.ProtocolMappingSection.Properties*
  parent: System.ServiceModel.Configuration.ProtocolMappingSection
  isExternal: false
  name: Properties
  nameWithType: ProtocolMappingSection.Properties
- uid: System.ServiceModel.Configuration.ProtocolMappingSection.ProtocolMappingCollection*
  parent: System.ServiceModel.Configuration.ProtocolMappingSection
  isExternal: false
  name: ProtocolMappingCollection
  nameWithType: ProtocolMappingSection.ProtocolMappingCollection
