### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  id: AnnotationElement
  children:
  - System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.#ctor
  - System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.ElementKey
  - System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Name
  - System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Properties
  - System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Value
  langs:
  - csharp
  name: AnnotationElement
  nameWithType: AnnotationElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  type: Class
  summary: "A configuration element that represents an annotation that is added to an emitted tracking record."
  syntax:
    content: 'public class AnnotationElement : System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement.GetStringPairKey(System.String,System.String)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  langs:
  - csharp
  name: AnnotationElement()
  nameWithType: AnnotationElement.AnnotationElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.AnnotationElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement&quot;></see> class."
  syntax:
    content: public AnnotationElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.ElementKey
  id: ElementKey
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  langs:
  - csharp
  name: ElementKey
  nameWithType: AnnotationElement.ElementKey
  fullName: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.ElementKey
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Gets a key that uniquely identifies the annotation."
  syntax:
    content: public override object ElementKey { get; }
    return:
      type: System.Object
      description: "The element key."
  overload: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.ElementKey*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Name
  id: Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  langs:
  - csharp
  name: Name
  nameWithType: AnnotationElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Name
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Gets or sets the name of the annotation."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "The name of the annotation."
  overload: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Name*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  langs:
  - csharp
  name: Properties
  nameWithType: AnnotationElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Gets a <see cref=&quot;T:System.Configuration.ConfigurationPropertyCollection&quot;></see> that contains the properties for the configuration element."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "The collection of properties."
  overload: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Value
  id: Value
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  langs:
  - csharp
  name: Value
  nameWithType: AnnotationElement.Value
  fullName: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Value
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "Gets or sets the value of the annotation."
  syntax:
    content: public string Value { get; set; }
    return:
      type: System.String
      description: "The value of the annotation."
  overload: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Value*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  isExternal: false
  name: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.#ctor
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  isExternal: false
  name: AnnotationElement()
  nameWithType: AnnotationElement.AnnotationElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.AnnotationElement()
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.ElementKey
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  isExternal: false
  name: ElementKey
  nameWithType: AnnotationElement.ElementKey
  fullName: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.ElementKey
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  isExternal: false
  name: Name
  nameWithType: AnnotationElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Name
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  isExternal: false
  name: Properties
  nameWithType: AnnotationElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Value
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  isExternal: false
  name: Value
  nameWithType: AnnotationElement.Value
  fullName: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Value
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.#ctor*
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  isExternal: false
  name: AnnotationElement
  nameWithType: AnnotationElement.AnnotationElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.ElementKey*
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  isExternal: false
  name: ElementKey
  nameWithType: AnnotationElement.ElementKey
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Name*
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  isExternal: false
  name: Name
  nameWithType: AnnotationElement.Name
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Properties*
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  isExternal: false
  name: Properties
  nameWithType: AnnotationElement.Properties
- uid: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement.Value*
  parent: System.ServiceModel.Activities.Tracking.Configuration.AnnotationElement
  isExternal: false
  name: Value
  nameWithType: AnnotationElement.Value
