### YamlMime:ManagedReference
items:
- uid: System.Windows.Forms.FlowLayoutSettings
  id: FlowLayoutSettings
  children:
  - System.Windows.Forms.FlowLayoutSettings.FlowDirection
  - System.Windows.Forms.FlowLayoutSettings.GetFlowBreak(System.Object)
  - System.Windows.Forms.FlowLayoutSettings.LayoutEngine
  - System.Windows.Forms.FlowLayoutSettings.SetFlowBreak(System.Object,System.Boolean)
  - System.Windows.Forms.FlowLayoutSettings.WrapContents
  langs:
  - csharp
  name: FlowLayoutSettings
  nameWithType: FlowLayoutSettings
  fullName: System.Windows.Forms.FlowLayoutSettings
  type: Class
  summary: "Collects the characteristics associated with flow layouts."
  remarks: "The FlowLayoutSettings class collects and manages the characteristics associated with the flow layout scheme. This class is used internally by the <xref:System.Windows.Forms.FlowLayoutPanel> and <xref:System.Windows.Forms.ToolStrip> classes, as well as the flow layout engine. The FlowLayoutSettings class is used by the layout engine to determine how to layout the container&quot;s child controls.       The FlowLayoutSettings class manages the following information:      -   The flow direction of consecutive controls.      -   Whether the contents should be wrapped or clipped if the child controls cannot be contained within their parent.       FlowLayoutSettings does not have a public constructor."
  syntax:
    content: >-
      [System.ComponentModel.DefaultProperty("FlowDirection")]

      public class FlowLayoutSettings : System.Windows.Forms.LayoutSettings
  inheritance:
  - System.Object
  - System.Windows.Forms.LayoutSettings
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Windows.Forms.FlowLayoutSettings.FlowDirection
  id: FlowDirection
  parent: System.Windows.Forms.FlowLayoutSettings
  langs:
  - csharp
  name: FlowDirection
  nameWithType: FlowLayoutSettings.FlowDirection
  fullName: System.Windows.Forms.FlowLayoutSettings.FlowDirection
  type: Property
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms
  summary: "Gets or sets a value indicating the flow direction of consecutive controls."
  remarks: "FlowDirection is the default property for the <xref:System.Windows.Forms.FlowLayoutSettings> class."
  syntax:
    content: public System.Windows.Forms.FlowDirection FlowDirection { get; set; }
    return:
      type: System.Windows.Forms.FlowDirection
      description: "A <see cref=&quot;T:System.Windows.Forms.FlowDirection&quot;></see> indicating the flow direction of consecutive controls in the container. The default is <see cref=&quot;T:System.Windows.Forms.FlowDirection&quot;></see>."
  overload: System.Windows.Forms.FlowLayoutSettings.FlowDirection*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Windows.Forms.FlowLayoutSettings.GetFlowBreak(System.Object)
  id: GetFlowBreak(System.Object)
  parent: System.Windows.Forms.FlowLayoutSettings
  langs:
  - csharp
  name: GetFlowBreak(Object)
  nameWithType: FlowLayoutSettings.GetFlowBreak(Object)
  fullName: System.Windows.Forms.FlowLayoutSettings.GetFlowBreak(Object)
  type: Method
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms
  summary: "Returns a value that represents the flow break setting of the control."
  syntax:
    content: public bool GetFlowBreak (object child);
    parameters:
    - id: child
      type: System.Object
      description: "The child control."
    return:
      type: System.Boolean
      description: "To be added."
  overload: System.Windows.Forms.FlowLayoutSettings.GetFlowBreak*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Windows.Forms.FlowLayoutSettings.LayoutEngine
  id: LayoutEngine
  parent: System.Windows.Forms.FlowLayoutSettings
  langs:
  - csharp
  name: LayoutEngine
  nameWithType: FlowLayoutSettings.LayoutEngine
  fullName: System.Windows.Forms.FlowLayoutSettings.LayoutEngine
  type: Property
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms
  summary: "Gets the current flow layout engine."
  remarks: "The <xref:System.Windows.Forms.TableLayoutSettings.LayoutEngine%2A> property is typically used in two contexts:      -   A container that uses a flow layout.      -   A control contained within a flow layout container (for example, a button contained in a cell of a <xref:System.Windows.Forms.FlowLayoutPanel>)."
  syntax:
    content: public override System.Windows.Forms.Layout.LayoutEngine LayoutEngine { get; }
    return:
      type: System.Windows.Forms.Layout.LayoutEngine
      description: "The <see cref=&quot;T:System.Windows.Forms.Layout.LayoutEngine&quot;></see> currently being used."
  overload: System.Windows.Forms.FlowLayoutSettings.LayoutEngine*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Windows.Forms.FlowLayoutSettings.SetFlowBreak(System.Object,System.Boolean)
  id: SetFlowBreak(System.Object,System.Boolean)
  parent: System.Windows.Forms.FlowLayoutSettings
  langs:
  - csharp
  name: SetFlowBreak(Object,Boolean)
  nameWithType: FlowLayoutSettings.SetFlowBreak(Object,Boolean)
  fullName: System.Windows.Forms.FlowLayoutSettings.SetFlowBreak(Object,Boolean)
  type: Method
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms
  summary: "Sets the value that represents the flow break setting of the control."
  syntax:
    content: public void SetFlowBreak (object child, bool value);
    parameters:
    - id: child
      type: System.Object
      description: "The child control."
    - id: value
      type: System.Boolean
      description: "The flow break value to set."
  overload: System.Windows.Forms.FlowLayoutSettings.SetFlowBreak*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Windows.Forms.FlowLayoutSettings.WrapContents
  id: WrapContents
  parent: System.Windows.Forms.FlowLayoutSettings
  langs:
  - csharp
  name: WrapContents
  nameWithType: FlowLayoutSettings.WrapContents
  fullName: System.Windows.Forms.FlowLayoutSettings.WrapContents
  type: Property
  assemblies:
  - System.Windows.Forms
  namespace: System.Windows.Forms
  summary: "Gets or sets a value indicating whether the contents should be wrapped or clipped when they exceed the original boundaries of their container."
  remarks: "If the area of the container is too small to display all the child controls, then at least one control will be clipped regardless of the WrapContents value.       Subsequent resizing of the container will reapply the layout to the contained controls."
  syntax:
    content: public bool WrapContents { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if the contents should be wrapped; otherwise, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref> if the contents should be clipped. The default is <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>."
  overload: System.Windows.Forms.FlowLayoutSettings.WrapContents*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Windows.Forms.LayoutSettings
  isExternal: false
  name: System.Windows.Forms.LayoutSettings
- uid: System.Windows.Forms.FlowLayoutSettings.FlowDirection
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: FlowDirection
  nameWithType: FlowLayoutSettings.FlowDirection
  fullName: System.Windows.Forms.FlowLayoutSettings.FlowDirection
- uid: System.Windows.Forms.FlowDirection
  parent: System.Windows.Forms
  isExternal: false
  name: FlowDirection
  nameWithType: FlowDirection
  fullName: System.Windows.Forms.FlowDirection
- uid: System.Windows.Forms.FlowLayoutSettings.GetFlowBreak(System.Object)
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: GetFlowBreak(Object)
  nameWithType: FlowLayoutSettings.GetFlowBreak(Object)
  fullName: System.Windows.Forms.FlowLayoutSettings.GetFlowBreak(Object)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Forms.FlowLayoutSettings.LayoutEngine
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: LayoutEngine
  nameWithType: FlowLayoutSettings.LayoutEngine
  fullName: System.Windows.Forms.FlowLayoutSettings.LayoutEngine
- uid: System.Windows.Forms.Layout.LayoutEngine
  parent: System.Windows.Forms.Layout
  isExternal: false
  name: LayoutEngine
  nameWithType: LayoutEngine
  fullName: System.Windows.Forms.Layout.LayoutEngine
- uid: System.Windows.Forms.FlowLayoutSettings.SetFlowBreak(System.Object,System.Boolean)
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: SetFlowBreak(Object,Boolean)
  nameWithType: FlowLayoutSettings.SetFlowBreak(Object,Boolean)
  fullName: System.Windows.Forms.FlowLayoutSettings.SetFlowBreak(Object,Boolean)
- uid: System.Windows.Forms.FlowLayoutSettings.WrapContents
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: WrapContents
  nameWithType: FlowLayoutSettings.WrapContents
  fullName: System.Windows.Forms.FlowLayoutSettings.WrapContents
- uid: System.Windows.Forms.FlowLayoutSettings.FlowDirection*
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: FlowDirection
  nameWithType: FlowLayoutSettings.FlowDirection
- uid: System.Windows.Forms.FlowLayoutSettings.GetFlowBreak*
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: GetFlowBreak
  nameWithType: FlowLayoutSettings.GetFlowBreak
- uid: System.Windows.Forms.FlowLayoutSettings.LayoutEngine*
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: LayoutEngine
  nameWithType: FlowLayoutSettings.LayoutEngine
- uid: System.Windows.Forms.FlowLayoutSettings.SetFlowBreak*
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: SetFlowBreak
  nameWithType: FlowLayoutSettings.SetFlowBreak
- uid: System.Windows.Forms.FlowLayoutSettings.WrapContents*
  parent: System.Windows.Forms.FlowLayoutSettings
  isExternal: false
  name: WrapContents
  nameWithType: FlowLayoutSettings.WrapContents
