### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.StandardEndpointsSection
  id: StandardEndpointsSection
  children:
  - System.ServiceModel.Configuration.StandardEndpointsSection.#ctor
  - System.ServiceModel.Configuration.StandardEndpointsSection.EndpointCollections
  - System.ServiceModel.Configuration.StandardEndpointsSection.GetSection(System.Configuration.Configuration)
  - System.ServiceModel.Configuration.StandardEndpointsSection.Item(System.String)
  - System.ServiceModel.Configuration.StandardEndpointsSection.MexEndpoint
  - System.ServiceModel.Configuration.StandardEndpointsSection.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.ServiceModel.Configuration.StandardEndpointsSection.Properties
  langs:
  - csharp
  name: StandardEndpointsSection
  nameWithType: StandardEndpointsSection
  fullName: System.ServiceModel.Configuration.StandardEndpointsSection
  type: Class
  summary: "Represents a configuration section of standard endpoints. This class cannot be inherited."
  syntax:
    content: 'public sealed class StandardEndpointsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.StandardEndpointsSection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.StandardEndpointsSection
  langs:
  - csharp
  name: StandardEndpointsSection()
  nameWithType: StandardEndpointsSection.StandardEndpointsSection()
  fullName: System.ServiceModel.Configuration.StandardEndpointsSection.StandardEndpointsSection()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Creates a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.StandardEndpointsSection&quot;></see> class."
  syntax:
    content: public StandardEndpointsSection ();
    parameters: []
  overload: System.ServiceModel.Configuration.StandardEndpointsSection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.StandardEndpointsSection.EndpointCollections
  id: EndpointCollections
  parent: System.ServiceModel.Configuration.StandardEndpointsSection
  langs:
  - csharp
  name: EndpointCollections
  nameWithType: StandardEndpointsSection.EndpointCollections
  fullName: System.ServiceModel.Configuration.StandardEndpointsSection.EndpointCollections
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Returns a collection of standard endpoints."
  syntax:
    content: public System.Collections.Generic.List<System.ServiceModel.Configuration.EndpointCollectionElement> EndpointCollections { get; }
    return:
      type: System.Collections.Generic.List{System.ServiceModel.Configuration.EndpointCollectionElement}
      description: "A generic list."
  overload: System.ServiceModel.Configuration.StandardEndpointsSection.EndpointCollections*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.StandardEndpointsSection.GetSection(System.Configuration.Configuration)
  id: GetSection(System.Configuration.Configuration)
  parent: System.ServiceModel.Configuration.StandardEndpointsSection
  langs:
  - csharp
  name: GetSection(Configuration)
  nameWithType: StandardEndpointsSection.GetSection(Configuration)
  fullName: System.ServiceModel.Configuration.StandardEndpointsSection.GetSection(Configuration)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Returns the standard endpoints section from the specified configuration file."
  syntax:
    content: public static System.ServiceModel.Configuration.StandardEndpointsSection GetSection (System.Configuration.Configuration config);
    parameters:
    - id: config
      type: System.Configuration.Configuration
      description: "An object that contains one or more XML sections of configuration settings."
    return:
      type: System.ServiceModel.Configuration.StandardEndpointsSection
      description: "To be added."
  overload: System.ServiceModel.Configuration.StandardEndpointsSection.GetSection*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "\n    config is ."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.StandardEndpointsSection.Item(System.String)
  id: Item(System.String)
  parent: System.ServiceModel.Configuration.StandardEndpointsSection
  langs:
  - csharp
  name: Item(String)
  nameWithType: StandardEndpointsSection.Item(String)
  fullName: System.ServiceModel.Configuration.StandardEndpointsSection.Item(String)
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Returns an endpoint element collection that contains the specified endpoint."
  syntax:
    content: public System.ServiceModel.Configuration.EndpointCollectionElement this[string endpoint] { get; }
    parameters:
    - id: endpoint
      type: System.String
      description: "A name of an endpoint."
    return:
      type: System.ServiceModel.Configuration.EndpointCollectionElement
      description: "An endpoint collection element."
  overload: System.ServiceModel.Configuration.StandardEndpointsSection.Item*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.StandardEndpointsSection.MexEndpoint
  id: MexEndpoint
  parent: System.ServiceModel.Configuration.StandardEndpointsSection
  langs:
  - csharp
  name: MexEndpoint
  nameWithType: StandardEndpointsSection.MexEndpoint
  fullName: System.ServiceModel.Configuration.StandardEndpointsSection.MexEndpoint
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Returns a collection element that contains metadata exchange endpoints."
  syntax:
    content: public System.ServiceModel.Configuration.ServiceMetadataEndpointCollectionElement MexEndpoint { get; }
    return:
      type: System.ServiceModel.Configuration.ServiceMetadataEndpointCollectionElement
      description: "A metadata exchange collection element."
  overload: System.ServiceModel.Configuration.StandardEndpointsSection.MexEndpoint*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.StandardEndpointsSection.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  id: OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  parent: System.ServiceModel.Configuration.StandardEndpointsSection
  langs:
  - csharp
  name: OnDeserializeUnrecognizedElement(String,XmlReader)
  nameWithType: StandardEndpointsSection.OnDeserializeUnrecognizedElement(String,XmlReader)
  fullName: System.ServiceModel.Configuration.StandardEndpointsSection.OnDeserializeUnrecognizedElement(String,XmlReader)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override bool OnDeserializeUnrecognizedElement (string elementName, System.Xml.XmlReader reader);
    parameters:
    - id: elementName
      type: System.String
      description: "To be added."
    - id: reader
      type: System.Xml.XmlReader
      description: "To be added."
    return:
      type: System.Boolean
      description: "To be added."
  overload: System.ServiceModel.Configuration.StandardEndpointsSection.OnDeserializeUnrecognizedElement*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.StandardEndpointsSection.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.StandardEndpointsSection
  langs:
  - csharp
  name: Properties
  nameWithType: StandardEndpointsSection.Properties
  fullName: System.ServiceModel.Configuration.StandardEndpointsSection.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.StandardEndpointsSection.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.ServiceModel.Configuration.StandardEndpointsSection.#ctor
  parent: System.ServiceModel.Configuration.StandardEndpointsSection
  isExternal: false
  name: StandardEndpointsSection()
  nameWithType: StandardEndpointsSection.StandardEndpointsSection()
  fullName: System.ServiceModel.Configuration.StandardEndpointsSection.StandardEndpointsSection()
- uid: System.ServiceModel.Configuration.StandardEndpointsSection.EndpointCollections
  parent: System.ServiceModel.Configuration.StandardEndpointsSection
  isExternal: false
  name: EndpointCollections
  nameWithType: StandardEndpointsSection.EndpointCollections
  fullName: System.ServiceModel.Configuration.StandardEndpointsSection.EndpointCollections
- uid: System.Collections.Generic.List{System.ServiceModel.Configuration.EndpointCollectionElement}
  parent: System.Collections.Generic
  isExternal: true
  name: List<EndpointCollectionElement>
  nameWithType: List<EndpointCollectionElement>
  fullName: System.Collections.Generic.List<System.ServiceModel.Configuration.EndpointCollectionElement>
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: List<System.ServiceModel.Configuration.EndpointCollectionElement>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.ServiceModel.Configuration.EndpointCollectionElement
    name: EndpointCollectionElement
    nameWithType: EndpointCollectionElement
    fullName: EndpointCollectionElement
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.ServiceModel.Configuration.StandardEndpointsSection.GetSection(System.Configuration.Configuration)
  parent: System.ServiceModel.Configuration.StandardEndpointsSection
  isExternal: false
  name: GetSection(Configuration)
  nameWithType: StandardEndpointsSection.GetSection(Configuration)
  fullName: System.ServiceModel.Configuration.StandardEndpointsSection.GetSection(Configuration)
- uid: System.ServiceModel.Configuration.StandardEndpointsSection
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: StandardEndpointsSection
  nameWithType: StandardEndpointsSection
  fullName: System.ServiceModel.Configuration.StandardEndpointsSection
- uid: System.Configuration.Configuration
  parent: System.Configuration
  isExternal: false
  name: Configuration
  nameWithType: Configuration
  fullName: System.Configuration.Configuration
- uid: System.ServiceModel.Configuration.StandardEndpointsSection.Item(System.String)
  parent: System.ServiceModel.Configuration.StandardEndpointsSection
  isExternal: false
  name: Item(String)
  nameWithType: StandardEndpointsSection.Item(String)
  fullName: System.ServiceModel.Configuration.StandardEndpointsSection.Item(String)
- uid: System.ServiceModel.Configuration.EndpointCollectionElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: EndpointCollectionElement
  nameWithType: EndpointCollectionElement
  fullName: System.ServiceModel.Configuration.EndpointCollectionElement
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.StandardEndpointsSection.MexEndpoint
  parent: System.ServiceModel.Configuration.StandardEndpointsSection
  isExternal: false
  name: MexEndpoint
  nameWithType: StandardEndpointsSection.MexEndpoint
  fullName: System.ServiceModel.Configuration.StandardEndpointsSection.MexEndpoint
- uid: System.ServiceModel.Configuration.ServiceMetadataEndpointCollectionElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceMetadataEndpointCollectionElement
  nameWithType: ServiceMetadataEndpointCollectionElement
  fullName: System.ServiceModel.Configuration.ServiceMetadataEndpointCollectionElement
- uid: System.ServiceModel.Configuration.StandardEndpointsSection.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  parent: System.ServiceModel.Configuration.StandardEndpointsSection
  isExternal: false
  name: OnDeserializeUnrecognizedElement(String,XmlReader)
  nameWithType: StandardEndpointsSection.OnDeserializeUnrecognizedElement(String,XmlReader)
  fullName: System.ServiceModel.Configuration.StandardEndpointsSection.OnDeserializeUnrecognizedElement(String,XmlReader)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xml.XmlReader
  parent: System.Xml
  isExternal: true
  name: XmlReader
  nameWithType: XmlReader
  fullName: System.Xml.XmlReader
- uid: System.ServiceModel.Configuration.StandardEndpointsSection.Properties
  parent: System.ServiceModel.Configuration.StandardEndpointsSection
  isExternal: false
  name: Properties
  nameWithType: StandardEndpointsSection.Properties
  fullName: System.ServiceModel.Configuration.StandardEndpointsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.StandardEndpointsSection.#ctor*
  parent: System.ServiceModel.Configuration.StandardEndpointsSection
  isExternal: false
  name: StandardEndpointsSection
  nameWithType: StandardEndpointsSection.StandardEndpointsSection
- uid: System.ServiceModel.Configuration.StandardEndpointsSection.EndpointCollections*
  parent: System.ServiceModel.Configuration.StandardEndpointsSection
  isExternal: false
  name: EndpointCollections
  nameWithType: StandardEndpointsSection.EndpointCollections
- uid: System.ServiceModel.Configuration.StandardEndpointsSection.GetSection*
  parent: System.ServiceModel.Configuration.StandardEndpointsSection
  isExternal: false
  name: GetSection
  nameWithType: StandardEndpointsSection.GetSection
- uid: System.ServiceModel.Configuration.StandardEndpointsSection.Item*
  parent: System.ServiceModel.Configuration.StandardEndpointsSection
  isExternal: false
  name: Item
  nameWithType: StandardEndpointsSection.Item
- uid: System.ServiceModel.Configuration.StandardEndpointsSection.MexEndpoint*
  parent: System.ServiceModel.Configuration.StandardEndpointsSection
  isExternal: false
  name: MexEndpoint
  nameWithType: StandardEndpointsSection.MexEndpoint
- uid: System.ServiceModel.Configuration.StandardEndpointsSection.OnDeserializeUnrecognizedElement*
  parent: System.ServiceModel.Configuration.StandardEndpointsSection
  isExternal: false
  name: OnDeserializeUnrecognizedElement
  nameWithType: StandardEndpointsSection.OnDeserializeUnrecognizedElement
- uid: System.ServiceModel.Configuration.StandardEndpointsSection.Properties*
  parent: System.ServiceModel.Configuration.StandardEndpointsSection
  isExternal: false
  name: Properties
  nameWithType: StandardEndpointsSection.Properties
