### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.DiagnosticsElement
  id: DiagnosticsElement
  children:
  - System.Web.Services.Configuration.DiagnosticsElement.#ctor
  - System.Web.Services.Configuration.DiagnosticsElement.Properties
  - System.Web.Services.Configuration.DiagnosticsElement.SuppressReturningExceptions
  langs:
  - csharp
  name: DiagnosticsElement
  nameWithType: DiagnosticsElement
  fullName: System.Web.Services.Configuration.DiagnosticsElement
  type: Class
  summary: "Represents the [\\"
  remarks: "The DiagnosticsElement class represents the [\\<diagnostics>](http://msdn.microsoft.com/en-us/e4ca05d1-1e10-4873-9ef6-75e55851d888) element in a Web.config file. Set the <xref:System.Web.Services.Configuration.DiagnosticsElement.SuppressReturningExceptions%2A> property to true in order to return exceptions to the client for debugging purposes."
  syntax:
    content: 'public sealed class DiagnosticsElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Services.Configuration.DiagnosticsElement.#ctor
  id: '#ctor'
  parent: System.Web.Services.Configuration.DiagnosticsElement
  langs:
  - csharp
  name: DiagnosticsElement()
  nameWithType: DiagnosticsElement.DiagnosticsElement()
  fullName: System.Web.Services.Configuration.DiagnosticsElement.DiagnosticsElement()
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Web.Services.Configuration.DiagnosticsElement&quot;></see> class."
  syntax:
    content: public DiagnosticsElement ();
    parameters: []
  overload: System.Web.Services.Configuration.DiagnosticsElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Services.Configuration.DiagnosticsElement.Properties
  id: Properties
  parent: System.Web.Services.Configuration.DiagnosticsElement
  langs:
  - csharp
  name: Properties
  nameWithType: DiagnosticsElement.Properties
  fullName: System.Web.Services.Configuration.DiagnosticsElement.Properties
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Web.Services.Configuration.DiagnosticsElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Services.Configuration.DiagnosticsElement.SuppressReturningExceptions
  id: SuppressReturningExceptions
  parent: System.Web.Services.Configuration.DiagnosticsElement
  langs:
  - csharp
  name: SuppressReturningExceptions
  nameWithType: DiagnosticsElement.SuppressReturningExceptions
  fullName: System.Web.Services.Configuration.DiagnosticsElement.SuppressReturningExceptions
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Gets or sets a value that indicates whether the service returns exceptions."
  syntax:
    content: public bool SuppressReturningExceptions { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> if the service returns exceptions; otherwise, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>. The default is <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>."
  overload: System.Web.Services.Configuration.DiagnosticsElement.SuppressReturningExceptions*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Services.Configuration.DiagnosticsElement.#ctor
  parent: System.Web.Services.Configuration.DiagnosticsElement
  isExternal: false
  name: DiagnosticsElement()
  nameWithType: DiagnosticsElement.DiagnosticsElement()
  fullName: System.Web.Services.Configuration.DiagnosticsElement.DiagnosticsElement()
- uid: System.Web.Services.Configuration.DiagnosticsElement.Properties
  parent: System.Web.Services.Configuration.DiagnosticsElement
  isExternal: false
  name: Properties
  nameWithType: DiagnosticsElement.Properties
  fullName: System.Web.Services.Configuration.DiagnosticsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Services.Configuration.DiagnosticsElement.SuppressReturningExceptions
  parent: System.Web.Services.Configuration.DiagnosticsElement
  isExternal: false
  name: SuppressReturningExceptions
  nameWithType: DiagnosticsElement.SuppressReturningExceptions
  fullName: System.Web.Services.Configuration.DiagnosticsElement.SuppressReturningExceptions
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Services.Configuration.DiagnosticsElement.#ctor*
  parent: System.Web.Services.Configuration.DiagnosticsElement
  isExternal: false
  name: DiagnosticsElement
  nameWithType: DiagnosticsElement.DiagnosticsElement
- uid: System.Web.Services.Configuration.DiagnosticsElement.Properties*
  parent: System.Web.Services.Configuration.DiagnosticsElement
  isExternal: false
  name: Properties
  nameWithType: DiagnosticsElement.Properties
- uid: System.Web.Services.Configuration.DiagnosticsElement.SuppressReturningExceptions*
  parent: System.Web.Services.Configuration.DiagnosticsElement
  isExternal: false
  name: SuppressReturningExceptions
  nameWithType: DiagnosticsElement.SuppressReturningExceptions
