### YamlMime:ManagedReference
items:
- uid: System.Configuration.SingleTagSectionHandler
  id: SingleTagSectionHandler
  children:
  - System.Configuration.SingleTagSectionHandler.#ctor
  - System.Configuration.SingleTagSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: SingleTagSectionHandler
  nameWithType: SingleTagSectionHandler
  fullName: System.Configuration.SingleTagSectionHandler
  type: Class
  summary: "Handles configuration sections that are represented by a single XML tag in the .config file."
  syntax:
    content: 'public class SingleTagSectionHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SingleTagSectionHandler.#ctor
  id: '#ctor'
  parent: System.Configuration.SingleTagSectionHandler
  langs:
  - csharp
  name: SingleTagSectionHandler()
  nameWithType: SingleTagSectionHandler.SingleTagSectionHandler()
  fullName: System.Configuration.SingleTagSectionHandler.SingleTagSectionHandler()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.SingleTagSectionHandler&quot;></see> class."
  syntax:
    content: public SingleTagSectionHandler ();
    parameters: []
  overload: System.Configuration.SingleTagSectionHandler.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.SingleTagSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.SingleTagSectionHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: SingleTagSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.SingleTagSectionHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Used internally to create a new instance of this object."
  syntax:
    content: public virtual object Create (object parent, object context, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "The parent of this object."
    - id: context
      type: System.Object
      description: "The context of this object."
    - id: section
      type: System.Xml.XmlNode
      description: "The  object in the configuration."
    return:
      type: System.Object
      description: "To be added."
  overload: System.Configuration.SingleTagSectionHandler.Create*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.SingleTagSectionHandler.#ctor
  parent: System.Configuration.SingleTagSectionHandler
  isExternal: false
  name: SingleTagSectionHandler()
  nameWithType: SingleTagSectionHandler.SingleTagSectionHandler()
  fullName: System.Configuration.SingleTagSectionHandler.SingleTagSectionHandler()
- uid: System.Configuration.SingleTagSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.SingleTagSectionHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: SingleTagSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.SingleTagSectionHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.SingleTagSectionHandler.#ctor*
  parent: System.Configuration.SingleTagSectionHandler
  isExternal: false
  name: SingleTagSectionHandler
  nameWithType: SingleTagSectionHandler.SingleTagSectionHandler
- uid: System.Configuration.SingleTagSectionHandler.Create*
  parent: System.Configuration.SingleTagSectionHandler
  isExternal: false
  name: Create
  nameWithType: SingleTagSectionHandler.Create
