### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DeploymentDownloadException
  id: DeploymentDownloadException
  children:
  - System.Deployment.Application.DeploymentDownloadException.#ctor
  - System.Deployment.Application.DeploymentDownloadException.#ctor(System.String)
  - System.Deployment.Application.DeploymentDownloadException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.DeploymentDownloadException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: DeploymentDownloadException
  nameWithType: DeploymentDownloadException
  fullName: System.Deployment.Application.DeploymentDownloadException
  type: Class
  summary: "Indicates that there was an error downloading either the [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] manifests or the deployment&quot;s files to the client computer."
  remarks: "A DeploymentDownloadException can indicate that a number of problems occurred when the user tried to download a [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] application update:      -   The client&quot;s computer&quot;s network connection is down.      -   The Web server, FTP server, or file share hosting the update is unavailable.      -   One or more of the files in the [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] deployment was not found.       To obtain detailed error information about an exception, consult the [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] error log. For more information, see [Troubleshooting ClickOnce Deployments](../Topic/Troubleshooting%20ClickOnce%20Deployments.md)."
  example:
  - "The following code example installs an application update synchronously, and reports to the user if there was a problem downloading either the manifests or the deployment's files.  \n  \n [!code-cs[ClickOnceAPI#5](~/add/codesnippet/CSharp/ClickOnceAPI/Form1.cs#5)]\n [!code-cpp[ClickOnceAPI#5](~/add/codesnippet/CPP/t-system.deployment.appl_2_1.cpp)]\n [!code-vb[ClickOnceAPI#5](~/add/codesnippet/VisualBasic/ClickOnceAPIVB/Form1.vb#5)]"
  syntax:
    content: 'public class DeploymentDownloadException : System.Deployment.Application.DeploymentException'
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Deployment.Application.DeploymentException
  implements: []
  inheritedMembers:
  - System.Deployment.Application.DeploymentException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.DeploymentDownloadException
  langs:
  - csharp
  name: DeploymentDownloadException()
  nameWithType: DeploymentDownloadException.DeploymentDownloadException()
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Deployment.Application.DeploymentDownloadException&quot;></see> class."
  syntax:
    content: public DeploymentDownloadException ();
    parameters: []
  overload: System.Deployment.Application.DeploymentDownloadException.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.DeploymentDownloadException
  langs:
  - csharp
  name: DeploymentDownloadException(String)
  nameWithType: DeploymentDownloadException.DeploymentDownloadException(String)
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException(String)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Deployment.Application.DeploymentDownloadException&quot;></see> class with a message that describes the exception."
  syntax:
    content: public DeploymentDownloadException (string message);
    parameters:
    - id: message
      type: System.String
      description: "The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture."
  overload: System.Deployment.Application.DeploymentDownloadException.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.DeploymentDownloadException
  langs:
  - csharp
  name: DeploymentDownloadException(SerializationInfo,StreamingContext)
  nameWithType: DeploymentDownloadException.DeploymentDownloadException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Deployment.Application.DeploymentDownloadException&quot;></see> class."
  syntax:
    content: protected DeploymentDownloadException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: "The object that holds the serialized object data."
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: "The contextual information about the source or destination."
  overload: System.Deployment.Application.DeploymentDownloadException.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.DeploymentDownloadException
  langs:
  - csharp
  name: DeploymentDownloadException(String,Exception)
  nameWithType: DeploymentDownloadException.DeploymentDownloadException(String,Exception)
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException(String,Exception)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Deployment.Application.DeploymentDownloadException&quot;></see> class."
  syntax:
    content: public DeploymentDownloadException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture."
    - id: innerException
      type: System.Exception
      description: "The exception that is the cause of the current exception. If the `innerException` parameter is not , the current exception is raised in a  block that handles the inner exception."
  overload: System.Deployment.Application.DeploymentDownloadException.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Deployment.Application.DeploymentException
  isExternal: false
  name: System.Deployment.Application.DeploymentException
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor
  parent: System.Deployment.Application.DeploymentDownloadException
  isExternal: false
  name: DeploymentDownloadException()
  nameWithType: DeploymentDownloadException.DeploymentDownloadException()
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException()
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor(System.String)
  parent: System.Deployment.Application.DeploymentDownloadException
  isExternal: false
  name: DeploymentDownloadException(String)
  nameWithType: DeploymentDownloadException.DeploymentDownloadException(String)
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.DeploymentDownloadException
  isExternal: false
  name: DeploymentDownloadException(SerializationInfo,StreamingContext)
  nameWithType: DeploymentDownloadException.DeploymentDownloadException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.DeploymentDownloadException
  isExternal: false
  name: DeploymentDownloadException(String,Exception)
  nameWithType: DeploymentDownloadException.DeploymentDownloadException(String,Exception)
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor*
  parent: System.Deployment.Application.DeploymentDownloadException
  isExternal: false
  name: DeploymentDownloadException
  nameWithType: DeploymentDownloadException.DeploymentDownloadException
