### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.AuthorizationRuleAction
  id: AuthorizationRuleAction
  children:
  - System.Web.Configuration.AuthorizationRuleAction.Allow
  - System.Web.Configuration.AuthorizationRuleAction.Deny
  langs:
  - csharp
  name: AuthorizationRuleAction
  nameWithType: AuthorizationRuleAction
  fullName: System.Web.Configuration.AuthorizationRuleAction
  type: Enum
  summary: "Specifies the type of authorization to apply when accessing a resource."
  remarks: "Use the <xref:System.Web.Configuration.AuthorizationRule.Action%2A> property to programmatically configure the authorization action to be used by a Web application."
  example:
  - "The following code example shows how use the <xref:System.Web.Configuration.AuthorizationRule.Action%2A> property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.AuthorizationRule> class.  \n  \n [!code-cs[System.Web.Configuration.Authorization#4](~/add/codesnippet/CSharp/t-system.web.configurati_31_1.cs)]\n [!code-vb[System.Web.Configuration.Authorization#4](~/add/codesnippet/VisualBasic/t-system.web.configurati_31_1.vb)]"
  syntax:
    content: public enum AuthorizationRuleAction
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.AuthorizationRuleAction.Allow
  id: Allow
  parent: System.Web.Configuration.AuthorizationRuleAction
  langs:
  - csharp
  name: Allow
  nameWithType: AuthorizationRuleAction.Allow
  fullName: System.Web.Configuration.AuthorizationRuleAction.Allow
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "The authorization type allows access to the resource."
  syntax:
    content: Allow
    return:
      type: System.Web.Configuration.AuthorizationRuleAction
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.AuthorizationRuleAction.Deny
  id: Deny
  parent: System.Web.Configuration.AuthorizationRuleAction
  langs:
  - csharp
  name: Deny
  nameWithType: AuthorizationRuleAction.Deny
  fullName: System.Web.Configuration.AuthorizationRuleAction.Deny
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "The authorization type denies access to the resource."
  syntax:
    content: Deny
    return:
      type: System.Web.Configuration.AuthorizationRuleAction
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.AuthorizationRuleAction.Allow
  parent: System.Web.Configuration.AuthorizationRuleAction
  isExternal: false
  name: Allow
  nameWithType: AuthorizationRuleAction.Allow
  fullName: System.Web.Configuration.AuthorizationRuleAction.Allow
- uid: System.Web.Configuration.AuthorizationRuleAction
  parent: System.Web.Configuration
  isExternal: false
  name: AuthorizationRuleAction
  nameWithType: AuthorizationRuleAction
  fullName: System.Web.Configuration.AuthorizationRuleAction
- uid: System.Web.Configuration.AuthorizationRuleAction.Deny
  parent: System.Web.Configuration.AuthorizationRuleAction
  isExternal: false
  name: Deny
  nameWithType: AuthorizationRuleAction.Deny
  fullName: System.Web.Configuration.AuthorizationRuleAction.Deny
