### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.WS2007FederationHttpBindingCollectionElement
  id: WS2007FederationHttpBindingCollectionElement
  children:
  - System.ServiceModel.Configuration.WS2007FederationHttpBindingCollectionElement.#ctor
  langs:
  - csharp
  name: WS2007FederationHttpBindingCollectionElement
  nameWithType: WS2007FederationHttpBindingCollectionElement
  fullName: System.ServiceModel.Configuration.WS2007FederationHttpBindingCollectionElement
  type: Class
  summary: "Represents a configuration element that contains a collection of <see cref=&quot;T:System.ServiceModel.Configuration.WS2007FederationHttpBindingElement&quot;></see> instances."
  remarks: ''
  example:
  - '[\<ws2007FederationHttpBinding>](../Topic/%3Cws2007FederationHttpBinding%3E.md)'
  syntax:
    content: 'public class WS2007FederationHttpBindingCollectionElement : System.ServiceModel.Configuration.StandardBindingCollectionElement<System.ServiceModel.WS2007FederationHttpBinding,System.ServiceModel.Configuration.WS2007FederationHttpBindingElement>'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.BindingCollectionElement
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.BindingCollectionElement.BindingName
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.Bindings
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.BindingType
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.ConfiguredBindings
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.ContainsKey(System.String)
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.GetDefault
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.Properties
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.TryAdd(System.String,System.ServiceModel.Channels.Binding,System.Configuration.Configuration)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.WS2007FederationHttpBindingCollectionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.WS2007FederationHttpBindingCollectionElement
  langs:
  - csharp
  name: WS2007FederationHttpBindingCollectionElement()
  nameWithType: WS2007FederationHttpBindingCollectionElement.WS2007FederationHttpBindingCollectionElement()
  fullName: System.ServiceModel.Configuration.WS2007FederationHttpBindingCollectionElement.WS2007FederationHttpBindingCollectionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.WS2007FederationHttpBindingCollectionElement&quot;></see> class."
  syntax:
    content: public WS2007FederationHttpBindingCollectionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.WS2007FederationHttpBindingCollectionElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.StandardBindingCollectionElement`2
  isExternal: false
  name: System.ServiceModel.Configuration.StandardBindingCollectionElement<System.ServiceModel.WS2007FederationHttpBinding,System.ServiceModel.Configuration.WS2007FederationHttpBindingElement>
- uid: System.ServiceModel.Configuration.WS2007FederationHttpBindingCollectionElement.#ctor
  parent: System.ServiceModel.Configuration.WS2007FederationHttpBindingCollectionElement
  isExternal: false
  name: WS2007FederationHttpBindingCollectionElement()
  nameWithType: WS2007FederationHttpBindingCollectionElement.WS2007FederationHttpBindingCollectionElement()
  fullName: System.ServiceModel.Configuration.WS2007FederationHttpBindingCollectionElement.WS2007FederationHttpBindingCollectionElement()
- uid: System.ServiceModel.Configuration.WS2007FederationHttpBindingCollectionElement.#ctor*
  parent: System.ServiceModel.Configuration.WS2007FederationHttpBindingCollectionElement
  isExternal: false
  name: WS2007FederationHttpBindingCollectionElement
  nameWithType: WS2007FederationHttpBindingCollectionElement.WS2007FederationHttpBindingCollectionElement
