### YamlMime:ManagedReference
items:
- uid: System.Management.ComparisonSettings
  id: ComparisonSettings
  children:
  - System.Management.ComparisonSettings.IgnoreCase
  - System.Management.ComparisonSettings.IgnoreClass
  - System.Management.ComparisonSettings.IgnoreDefaultValues
  - System.Management.ComparisonSettings.IgnoreFlavor
  - System.Management.ComparisonSettings.IgnoreObjectSource
  - System.Management.ComparisonSettings.IgnoreQualifiers
  - System.Management.ComparisonSettings.IncludeAll
  langs:
  - csharp
  name: ComparisonSettings
  nameWithType: ComparisonSettings
  fullName: System.Management.ComparisonSettings
  type: Enum
  summary: "Describes the object comparison modes that can be used with &lt;xref:System.Management.ManagementBaseObject.CompareTo%2A&gt;. Note that these values may be combined."
  syntax:
    content: >-
      [System.Flags]

      public enum ComparisonSettings
  inheritance:
  - System.Enum
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Management.ComparisonSettings.IgnoreCase
  id: IgnoreCase
  parent: System.Management.ComparisonSettings
  langs:
  - csharp
  name: IgnoreCase
  nameWithType: ComparisonSettings.IgnoreCase
  fullName: System.Management.ComparisonSettings.IgnoreCase
  type: Field
  assemblies:
  - System.Management
  namespace: System.Management
  summary: 'A mode that compares string values in a case-insensitive manner. This applies to strings and to qualifier values. Property and qualifier names are always compared in a case-insensitive manner whether this flag is specified or not. Value: 16.'
  syntax:
    content: IgnoreCase
    return:
      type: System.Management.ComparisonSettings
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Management.ComparisonSettings.IgnoreClass
  id: IgnoreClass
  parent: System.Management.ComparisonSettings
  langs:
  - csharp
  name: IgnoreClass
  nameWithType: ComparisonSettings.IgnoreClass
  fullName: System.Management.ComparisonSettings.IgnoreClass
  type: Field
  assemblies:
  - System.Management
  namespace: System.Management
  summary: 'A mode that assumes that the objects being compared are instances of                    the same class. Consequently, this value causes comparison of instance-related information only. Use this flag to optimize performance. If the objects are not of the same class, the results are undefined. Value: 8.'
  syntax:
    content: IgnoreClass
    return:
      type: System.Management.ComparisonSettings
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Management.ComparisonSettings.IgnoreDefaultValues
  id: IgnoreDefaultValues
  parent: System.Management.ComparisonSettings
  langs:
  - csharp
  name: IgnoreDefaultValues
  nameWithType: ComparisonSettings.IgnoreDefaultValues
  fullName: System.Management.ComparisonSettings.IgnoreDefaultValues
  type: Field
  assemblies:
  - System.Management
  namespace: System.Management
  summary: 'A mode that ignores the default values of properties. This value is only meaningful when comparing classes. Value: 4.'
  syntax:
    content: IgnoreDefaultValues
    return:
      type: System.Management.ComparisonSettings
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Management.ComparisonSettings.IgnoreFlavor
  id: IgnoreFlavor
  parent: System.Management.ComparisonSettings
  langs:
  - csharp
  name: IgnoreFlavor
  nameWithType: ComparisonSettings.IgnoreFlavor
  fullName: System.Management.ComparisonSettings.IgnoreFlavor
  type: Field
  assemblies:
  - System.Management
  namespace: System.Management
  summary: 'A mode that ignores qualifier *flavors*. This flag still takes qualifier values into account, but ignores flavor distinctions such as propagation rules and override restrictions. Value: 32.'
  syntax:
    content: IgnoreFlavor
    return:
      type: System.Management.ComparisonSettings
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Management.ComparisonSettings.IgnoreObjectSource
  id: IgnoreObjectSource
  parent: System.Management.ComparisonSettings
  langs:
  - csharp
  name: IgnoreObjectSource
  nameWithType: ComparisonSettings.IgnoreObjectSource
  fullName: System.Management.ComparisonSettings.IgnoreObjectSource
  type: Field
  assemblies:
  - System.Management
  namespace: System.Management
  summary: 'A mode that ignores the source of the objects, namely the server and the namespace they came from, in comparison to other objects. Value: 2.'
  syntax:
    content: IgnoreObjectSource
    return:
      type: System.Management.ComparisonSettings
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Management.ComparisonSettings.IgnoreQualifiers
  id: IgnoreQualifiers
  parent: System.Management.ComparisonSettings
  langs:
  - csharp
  name: IgnoreQualifiers
  nameWithType: ComparisonSettings.IgnoreQualifiers
  fullName: System.Management.ComparisonSettings.IgnoreQualifiers
  type: Field
  assemblies:
  - System.Management
  namespace: System.Management
  summary: 'A mode that compares the objects, ignoring *qualifiers*. Value: 1.'
  syntax:
    content: IgnoreQualifiers
    return:
      type: System.Management.ComparisonSettings
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Management.ComparisonSettings.IncludeAll
  id: IncludeAll
  parent: System.Management.ComparisonSettings
  langs:
  - csharp
  name: IncludeAll
  nameWithType: ComparisonSettings.IncludeAll
  fullName: System.Management.ComparisonSettings.IncludeAll
  type: Field
  assemblies:
  - System.Management
  namespace: System.Management
  summary: 'A mode that compares all elements of the compared objects. Value: 0.'
  syntax:
    content: IncludeAll
    return:
      type: System.Management.ComparisonSettings
      description: "To be added."
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Management.ComparisonSettings.IgnoreCase
  parent: System.Management.ComparisonSettings
  isExternal: false
  name: IgnoreCase
  nameWithType: ComparisonSettings.IgnoreCase
  fullName: System.Management.ComparisonSettings.IgnoreCase
- uid: System.Management.ComparisonSettings
  parent: System.Management
  isExternal: false
  name: ComparisonSettings
  nameWithType: ComparisonSettings
  fullName: System.Management.ComparisonSettings
- uid: System.Management.ComparisonSettings.IgnoreClass
  parent: System.Management.ComparisonSettings
  isExternal: false
  name: IgnoreClass
  nameWithType: ComparisonSettings.IgnoreClass
  fullName: System.Management.ComparisonSettings.IgnoreClass
- uid: System.Management.ComparisonSettings.IgnoreDefaultValues
  parent: System.Management.ComparisonSettings
  isExternal: false
  name: IgnoreDefaultValues
  nameWithType: ComparisonSettings.IgnoreDefaultValues
  fullName: System.Management.ComparisonSettings.IgnoreDefaultValues
- uid: System.Management.ComparisonSettings.IgnoreFlavor
  parent: System.Management.ComparisonSettings
  isExternal: false
  name: IgnoreFlavor
  nameWithType: ComparisonSettings.IgnoreFlavor
  fullName: System.Management.ComparisonSettings.IgnoreFlavor
- uid: System.Management.ComparisonSettings.IgnoreObjectSource
  parent: System.Management.ComparisonSettings
  isExternal: false
  name: IgnoreObjectSource
  nameWithType: ComparisonSettings.IgnoreObjectSource
  fullName: System.Management.ComparisonSettings.IgnoreObjectSource
- uid: System.Management.ComparisonSettings.IgnoreQualifiers
  parent: System.Management.ComparisonSettings
  isExternal: false
  name: IgnoreQualifiers
  nameWithType: ComparisonSettings.IgnoreQualifiers
  fullName: System.Management.ComparisonSettings.IgnoreQualifiers
- uid: System.Management.ComparisonSettings.IncludeAll
  parent: System.Management.ComparisonSettings
  isExternal: false
  name: IncludeAll
  nameWithType: ComparisonSettings.IncludeAll
  fullName: System.Management.ComparisonSettings.IncludeAll
