### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection
  id: CommonBehaviorsSection
  children:
  - System.ServiceModel.Configuration.CommonBehaviorsSection.#ctor
  - System.ServiceModel.Configuration.CommonBehaviorsSection.EndpointBehaviors
  - System.ServiceModel.Configuration.CommonBehaviorsSection.Properties
  - System.ServiceModel.Configuration.CommonBehaviorsSection.ServiceBehaviors
  langs:
  - csharp
  name: CommonBehaviorsSection
  nameWithType: CommonBehaviorsSection
  fullName: System.ServiceModel.Configuration.CommonBehaviorsSection
  type: Class
  summary: "Represents the configuration section that contains a list of behaviors that is applied to all [!INCLUDE[indigo1](~/add/includes/indigo1-md.md)] services on the machine before the behaviors in the <xref uid=&quot;langword_csharp_behaviors&quot; name=&quot;behaviors&quot; href=&quot;&quot;></xref> section are applied."
  remarks: "This configuration section is defined in the Machine.config file. It contains a list of behaviors that is applied to all [!INCLUDE[indigo2](~/add/includes/indigo2-md.md)] services on the machine before the behaviors in the `behaviors` section are applied. If a behavior is defined in both sections, the behavior in the `behaviors` sections is given preference."
  syntax:
    content: 'public class CommonBehaviorsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  langs:
  - csharp
  name: CommonBehaviorsSection()
  nameWithType: CommonBehaviorsSection.CommonBehaviorsSection()
  fullName: System.ServiceModel.Configuration.CommonBehaviorsSection.CommonBehaviorsSection()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.CommonBehaviorsSection&quot;></see> class."
  syntax:
    content: public CommonBehaviorsSection ();
    parameters: []
  overload: System.ServiceModel.Configuration.CommonBehaviorsSection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.EndpointBehaviors
  id: EndpointBehaviors
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  langs:
  - csharp
  name: EndpointBehaviors
  nameWithType: CommonBehaviorsSection.EndpointBehaviors
  fullName: System.ServiceModel.Configuration.CommonBehaviorsSection.EndpointBehaviors
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets all the child entries that are <xref uid=&quot;langword_csharp_EndpointBehavior&quot; name=&quot;EndpointBehavior&quot; href=&quot;&quot;></xref> elements identified by their unique name."
  syntax:
    content: public System.ServiceModel.Configuration.CommonEndpointBehaviorElement EndpointBehaviors { get; }
    return:
      type: System.ServiceModel.Configuration.CommonEndpointBehaviorElement
      description: "The child entries that are <xref uid=&quot;langword_csharp_EndpointBehavior&quot; name=&quot;EndpointBehavior&quot; href=&quot;&quot;></xref> elements identified by their unique name."
  overload: System.ServiceModel.Configuration.CommonBehaviorsSection.EndpointBehaviors*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  langs:
  - csharp
  name: Properties
  nameWithType: CommonBehaviorsSection.Properties
  fullName: System.ServiceModel.Configuration.CommonBehaviorsSection.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets a <see cref=&quot;T:System.Configuration.ConfigurationPropertyCollection&quot;></see> instance that contains a collection of <see cref=&quot;T:System.Configuration.ConfigurationProperty&quot;></see> objects that can be attributes or <see cref=&quot;T:System.Configuration.ConfigurationElement&quot;></see> objects of this configuration element."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A <see cref=&quot;T:System.Configuration.ConfigurationPropertyCollection&quot;></see> instance that contains a collection of <see cref=&quot;T:System.Configuration.ConfigurationProperty&quot;></see> objects that can be attributes or <see cref=&quot;T:System.Configuration.ConfigurationElement&quot;></see> objects of this configuration element."
  overload: System.ServiceModel.Configuration.CommonBehaviorsSection.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.ServiceBehaviors
  id: ServiceBehaviors
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  langs:
  - csharp
  name: ServiceBehaviors
  nameWithType: CommonBehaviorsSection.ServiceBehaviors
  fullName: System.ServiceModel.Configuration.CommonBehaviorsSection.ServiceBehaviors
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets all the child entries that are <xref uid=&quot;langword_csharp_serviceBehavior&quot; name=&quot;serviceBehavior&quot; href=&quot;&quot;></xref> elements identified by their unique name."
  syntax:
    content: public System.ServiceModel.Configuration.CommonServiceBehaviorElement ServiceBehaviors { get; }
    return:
      type: System.ServiceModel.Configuration.CommonServiceBehaviorElement
      description: "The child entries that are <xref uid=&quot;langword_csharp_serviceBehavior&quot; name=&quot;serviceBehavior&quot; href=&quot;&quot;></xref> elements identified by their unique name."
  overload: System.ServiceModel.Configuration.CommonBehaviorsSection.ServiceBehaviors*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.#ctor
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  isExternal: false
  name: CommonBehaviorsSection()
  nameWithType: CommonBehaviorsSection.CommonBehaviorsSection()
  fullName: System.ServiceModel.Configuration.CommonBehaviorsSection.CommonBehaviorsSection()
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.EndpointBehaviors
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  isExternal: false
  name: EndpointBehaviors
  nameWithType: CommonBehaviorsSection.EndpointBehaviors
  fullName: System.ServiceModel.Configuration.CommonBehaviorsSection.EndpointBehaviors
- uid: System.ServiceModel.Configuration.CommonEndpointBehaviorElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: CommonEndpointBehaviorElement
  nameWithType: CommonEndpointBehaviorElement
  fullName: System.ServiceModel.Configuration.CommonEndpointBehaviorElement
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.Properties
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  isExternal: false
  name: Properties
  nameWithType: CommonBehaviorsSection.Properties
  fullName: System.ServiceModel.Configuration.CommonBehaviorsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.ServiceBehaviors
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  isExternal: false
  name: ServiceBehaviors
  nameWithType: CommonBehaviorsSection.ServiceBehaviors
  fullName: System.ServiceModel.Configuration.CommonBehaviorsSection.ServiceBehaviors
- uid: System.ServiceModel.Configuration.CommonServiceBehaviorElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: CommonServiceBehaviorElement
  nameWithType: CommonServiceBehaviorElement
  fullName: System.ServiceModel.Configuration.CommonServiceBehaviorElement
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.#ctor*
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  isExternal: false
  name: CommonBehaviorsSection
  nameWithType: CommonBehaviorsSection.CommonBehaviorsSection
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.EndpointBehaviors*
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  isExternal: false
  name: EndpointBehaviors
  nameWithType: CommonBehaviorsSection.EndpointBehaviors
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.Properties*
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  isExternal: false
  name: Properties
  nameWithType: CommonBehaviorsSection.Properties
- uid: System.ServiceModel.Configuration.CommonBehaviorsSection.ServiceBehaviors*
  parent: System.ServiceModel.Configuration.CommonBehaviorsSection
  isExternal: false
  name: ServiceBehaviors
  nameWithType: CommonBehaviorsSection.ServiceBehaviors
