### YamlMime:ManagedReference
items:
- uid: System.Transactions.Configuration.MachineSettingsSection
  id: MachineSettingsSection
  children:
  - System.Transactions.Configuration.MachineSettingsSection.#ctor
  - System.Transactions.Configuration.MachineSettingsSection.MaxTimeout
  - System.Transactions.Configuration.MachineSettingsSection.Properties
  langs:
  - csharp
  name: MachineSettingsSection
  nameWithType: MachineSettingsSection
  fullName: System.Transactions.Configuration.MachineSettingsSection
  type: Class
  summary: "Represents an XML section in a configuration file encapsulating all settings that can be modified only at the machine level. This class cannot be inherited."
  remarks: "Property values of this class can only be set in the machine.config file."
  example:
  - "An example configuration file used by your transaction application can be as follows,  \n  \n `<configuration>`  \n  \n `<system.transactions>`  \n  \n `<defaultSettings distributedTransactionManagerName=\"F04M25\" timeout=\"02:00:00\"/>`  \n  \n `<machineSettings maxTimeout=\"02:00:00\"/>`  \n  \n `</system.transactions>`  \n  \n `</configuration>`  \n  \n This example specifies the default values of a transaction. Specifically, it sets the the computer name of the Distributed Transaction Coordinator (MSDTC) that is responsible for coordinating all distributed transactions started locally, and the default time after which a transaction times out. In addition, it specifies a setting that can only be modified at the machine level, which is the maximum amount of time allowed before a transaction times out."
  syntax:
    content: 'public sealed class MachineSettingsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Transactions.Configuration.MachineSettingsSection.#ctor
  id: '#ctor'
  parent: System.Transactions.Configuration.MachineSettingsSection
  langs:
  - csharp
  name: MachineSettingsSection()
  nameWithType: MachineSettingsSection.MachineSettingsSection()
  fullName: System.Transactions.Configuration.MachineSettingsSection.MachineSettingsSection()
  type: Constructor
  assemblies:
  - System.Transactions
  namespace: System.Transactions.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Transactions.Configuration.MachineSettingsSection&quot;></see> class."
  syntax:
    content: public MachineSettingsSection ();
    parameters: []
  overload: System.Transactions.Configuration.MachineSettingsSection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Transactions.Configuration.MachineSettingsSection.MaxTimeout
  id: MaxTimeout
  parent: System.Transactions.Configuration.MachineSettingsSection
  langs:
  - csharp
  name: MaxTimeout
  nameWithType: MachineSettingsSection.MaxTimeout
  fullName: System.Transactions.Configuration.MachineSettingsSection.MaxTimeout
  type: Property
  assemblies:
  - System.Transactions
  namespace: System.Transactions.Configuration
  summary: "Gets a maximum amount of time allowed before a transaction times out."
  remarks: "This property can only be set in the machine.config file. A value of 00:00:00 (or zero) is interpreted as infinity."
  syntax:
    content: public TimeSpan MaxTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "A &lt;xref:System.TimeSpan&gt; object that contains the maximum allowable time. The default value is 00:10:00."
  overload: System.Transactions.Configuration.MachineSettingsSection.MaxTimeout*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "An attempt to set this property to negative values."
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Transactions.Configuration.MachineSettingsSection.Properties
  id: Properties
  parent: System.Transactions.Configuration.MachineSettingsSection
  langs:
  - csharp
  name: Properties
  nameWithType: MachineSettingsSection.Properties
  fullName: System.Transactions.Configuration.MachineSettingsSection.Properties
  type: Property
  assemblies:
  - System.Transactions
  namespace: System.Transactions.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Transactions.Configuration.MachineSettingsSection.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Transactions.Configuration.MachineSettingsSection.#ctor
  parent: System.Transactions.Configuration.MachineSettingsSection
  isExternal: false
  name: MachineSettingsSection()
  nameWithType: MachineSettingsSection.MachineSettingsSection()
  fullName: System.Transactions.Configuration.MachineSettingsSection.MachineSettingsSection()
- uid: System.Transactions.Configuration.MachineSettingsSection.MaxTimeout
  parent: System.Transactions.Configuration.MachineSettingsSection
  isExternal: false
  name: MaxTimeout
  nameWithType: MachineSettingsSection.MaxTimeout
  fullName: System.Transactions.Configuration.MachineSettingsSection.MaxTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Transactions.Configuration.MachineSettingsSection.Properties
  parent: System.Transactions.Configuration.MachineSettingsSection
  isExternal: false
  name: Properties
  nameWithType: MachineSettingsSection.Properties
  fullName: System.Transactions.Configuration.MachineSettingsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Transactions.Configuration.MachineSettingsSection.#ctor*
  parent: System.Transactions.Configuration.MachineSettingsSection
  isExternal: false
  name: MachineSettingsSection
  nameWithType: MachineSettingsSection.MachineSettingsSection
- uid: System.Transactions.Configuration.MachineSettingsSection.MaxTimeout*
  parent: System.Transactions.Configuration.MachineSettingsSection
  isExternal: false
  name: MaxTimeout
  nameWithType: MachineSettingsSection.MaxTimeout
- uid: System.Transactions.Configuration.MachineSettingsSection.Properties*
  parent: System.Transactions.Configuration.MachineSettingsSection
  isExternal: false
  name: Properties
  nameWithType: MachineSettingsSection.Properties
