### YamlMime:ManagedReference
items:
- uid: System.Configuration.ApplicationScopedSettingAttribute
  id: ApplicationScopedSettingAttribute
  children:
  - System.Configuration.ApplicationScopedSettingAttribute.#ctor
  langs:
  - csharp
  name: ApplicationScopedSettingAttribute
  nameWithType: ApplicationScopedSettingAttribute
  fullName: System.Configuration.ApplicationScopedSettingAttribute
  type: Class
  summary: "Specifies that an application settings property has a common value for all users of an application. This class cannot be inherited."
  remarks: "Application settings properties have a scope that is based either at the application or the user level. As the categories imply, application-scoped settings properties present uniform values to all users of the application, whereas user-scoped properties have dedicated values for each user of the application.       The ApplicationScopedSettingAttribute indicates that a property should be considered an application-level setting, and that appropriate storage decisions should be made accordingly by the settings provider.       A scope attribute is required for each settings property. If a property is not applied with either a ApplicationScopedSettingAttribute or <xref:System.Configuration.UserScopedSettingAttribute>, the property is not recognized by the settings providerâ€”it is not serialized. It is invalid, however, to apply both attributes to the same property. Such an attempt will cause a <xref:System.Configuration.ConfigurationErrorsException> to be thrown."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class ApplicationScopedSettingAttribute : System.Configuration.SettingAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.SettingAttribute
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ApplicationScopedSettingAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.ApplicationScopedSettingAttribute
  langs:
  - csharp
  name: ApplicationScopedSettingAttribute()
  nameWithType: ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
  fullName: System.Configuration.ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.ApplicationScopedSettingAttribute&quot;></see> class."
  remarks: "Each application settings property must be applied with a single scope attribute in order for it to be recognized and serialized by the settings provider."
  syntax:
    content: public ApplicationScopedSettingAttribute ();
    parameters: []
  overload: System.Configuration.ApplicationScopedSettingAttribute.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.SettingAttribute
  isExternal: false
  name: System.Configuration.SettingAttribute
- uid: System.Configuration.ApplicationScopedSettingAttribute.#ctor
  parent: System.Configuration.ApplicationScopedSettingAttribute
  isExternal: false
  name: ApplicationScopedSettingAttribute()
  nameWithType: ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
  fullName: System.Configuration.ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
- uid: System.Configuration.ApplicationScopedSettingAttribute.#ctor*
  parent: System.Configuration.ApplicationScopedSettingAttribute
  isExternal: false
  name: ApplicationScopedSettingAttribute
  nameWithType: ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute
