### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.WebPartsSection
  id: WebPartsSection
  children:
  - System.Web.Configuration.WebPartsSection.#ctor
  - System.Web.Configuration.WebPartsSection.EnableExport
  - System.Web.Configuration.WebPartsSection.GetRuntimeObject
  - System.Web.Configuration.WebPartsSection.Personalization
  - System.Web.Configuration.WebPartsSection.Properties
  - System.Web.Configuration.WebPartsSection.Transformers
  langs:
  - csharp
  name: WebPartsSection
  nameWithType: WebPartsSection
  fullName: System.Web.Configuration.WebPartsSection
  type: Class
  summary: "Provides programmatic access to the <xref uid=&quot;langword_csharp_webParts&quot; name=&quot;webParts&quot; href=&quot;&quot;></xref> configuration file section. This class cannot be inherited."
  remarks: "The `webParts` configuration file section allows you to specify a Web Parts personalization provider, set personalization authorizations, and add custom classes that extend the <xref:System.Web.UI.WebControls.WebParts.WebPartTransformer> class for use by Web Parts connections."
  example:
  - "This example demonstrates how to specify values declaratively for several attributes of the `webParts` section, which can also be accessed as members of the WebPartsSection class.  \n  \n The following configuration file example shows how to specify values declaratively for the `webParts` section.  \n  \n```  \n<system.web>  \n  <webParts>  \n    <personalization  \n      defaultProvider=\" AspNetSqlPersonalizationProvider \">  \n        <!â€”- Providers may only be defined at the   \n            application level -->  \n      <providers>  \n        <add name=\"AspNetSqlPersonalizationProvider\"  \ntype=\"System.Web.UI.WebControls.WebParts.SqlPersonalizationProvider\"  \n        connectionStringName=\"LocalSqlServer\"  \n        applicationName=\"/\" />        \n      </providers>  \n      <authorization>  \n        <deny users=\"*\" verbs=\"enterSharedScope\" />  \n        <allow users=\"Admin\" verbs=\"modifyState\" />  \n      </authorization>  \n    </personalization>  \n    <transformers>  \n      <add name=\"RowToFieldTransformer\"  \n        type=\"System.Web.UI.WebControls.WebParts.RowToFieldTransformer\" />  \n      <add name=\"RowToFilterTransformer\"  \n        type=\"System.Web.UI.WebControls.WebParts.RowToFilterTransformer\" />  \n      <add name=\"RowToParametersTransformer\"  \ntype=\"System.Web.UI.WebControls.WebParts.RowToParametersTransformer\" />  \n    </transformers>  \n  </webParts>  \n</system.web>  \n```  \n  \n The following code example demonstrates how to use the WebPartsSection class.  \n  \n [!code-cs[System.Web.Configuration.WebPartsSection#1](~/add/codesnippet/CSharp/t-system.web.configurati_23_1.cs)]\n [!code-vb[System.Web.Configuration.WebPartsSection#1](~/add/codesnippet/VisualBasic/t-system.web.configurati_23_1.vb)]"
  syntax:
    content: 'public sealed class WebPartsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.WebPartsSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.WebPartsSection
  langs:
  - csharp
  name: WebPartsSection()
  nameWithType: WebPartsSection.WebPartsSection()
  fullName: System.Web.Configuration.WebPartsSection.WebPartsSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Web.Configuration.WebPartsSection&quot;></see> class using default settings."
  remarks: "The WebPartsSection constructor is not intended to be used directly from your code. It is called by the ASP.NET configuration system. You obtain an instance of the <xref:System.Web.Configuration.WebPartsSection> class by using the <xref:System.Configuration.Configuration.GetSection%2A> method.       This constructor is not intended to be used directly from your code. It is called by the ASP.NET configuration system.       The following table shows the default settings that are used for this constructor.      |Setting|Default Value|   |-------------|-------------------|   |<xref:System.Web.Configuration.WebPartsSection.Personalization%2A>|An empty <xref:System.Web.Configuration.WebPartsPersonalization> object.|   |<xref:System.Web.Configuration.WebPartsSection.Transformers%2A>|A <xref:System.Web.Configuration.TransformerInfoCollection> collection containing a default <xref:System.Web.Configuration.TransformerInfo> object.|"
  syntax:
    content: public WebPartsSection ();
    parameters: []
  overload: System.Web.Configuration.WebPartsSection.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.WebPartsSection.EnableExport
  id: EnableExport
  parent: System.Web.Configuration.WebPartsSection
  langs:
  - csharp
  name: EnableExport
  nameWithType: WebPartsSection.EnableExport
  fullName: System.Web.Configuration.WebPartsSection.EnableExport
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets or sets a value indicating whether to enable the export of control data to an XML description file."
  syntax:
    content: public bool EnableExport { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> to enable the export of control data to an XML description file; otherwise, <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>."
  overload: System.Web.Configuration.WebPartsSection.EnableExport*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.WebPartsSection.GetRuntimeObject
  id: GetRuntimeObject
  parent: System.Web.Configuration.WebPartsSection
  langs:
  - csharp
  name: GetRuntimeObject()
  nameWithType: WebPartsSection.GetRuntimeObject()
  fullName: System.Web.Configuration.WebPartsSection.GetRuntimeObject()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override object GetRuntimeObject ();
    parameters: []
    return:
      type: System.Object
      description: "To be added."
  overload: System.Web.Configuration.WebPartsSection.GetRuntimeObject*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.WebPartsSection.Personalization
  id: Personalization
  parent: System.Web.Configuration.WebPartsSection
  langs:
  - csharp
  name: Personalization
  nameWithType: WebPartsSection.Personalization
  fullName: System.Web.Configuration.WebPartsSection.Personalization
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets a <see cref=&quot;T:System.Web.Configuration.WebPartsPersonalization&quot;></see> object that allows you to specify the Web Parts personalization provider and set Web Parts personalization authorizations."
  remarks: ''
  example:
  - "The following code example shows how to use the Personalization property.  \n  \n [!code-cs[System.Web.Configuration.WebPartsSection#3](~/add/codesnippet/CSharp/p-system.web.configurati_218_1.cs)]\n [!code-vb[System.Web.Configuration.WebPartsSection#3](~/add/codesnippet/VisualBasic/p-system.web.configurati_218_1.vb)]"
  syntax:
    content: public System.Web.Configuration.WebPartsPersonalization Personalization { get; }
    return:
      type: System.Web.Configuration.WebPartsPersonalization
      description: "A <see cref=&quot;T:System.Web.Configuration.WebPartsPersonalization&quot;></see> object that allows you to specify the personalization provider and set personalization authorizations."
  overload: System.Web.Configuration.WebPartsSection.Personalization*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.WebPartsSection.Properties
  id: Properties
  parent: System.Web.Configuration.WebPartsSection
  langs:
  - csharp
  name: Properties
  nameWithType: WebPartsSection.Properties
  fullName: System.Web.Configuration.WebPartsSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Web.Configuration.WebPartsSection.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Configuration.WebPartsSection.Transformers
  id: Transformers
  parent: System.Web.Configuration.WebPartsSection
  langs:
  - csharp
  name: Transformers
  nameWithType: WebPartsSection.Transformers
  fullName: System.Web.Configuration.WebPartsSection.Transformers
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets a collection of <see cref=&quot;T:System.Web.Configuration.TransformerInfo&quot;></see> objects."
  remarks: "<xref:System.Web.Configuration.TransformerInfo> objects specify custom classes that extend the <xref:System.Web.UI.WebControls.WebParts.WebPartTransformer> class for use by Web Part connections for the ASP.NET applications affected by the configuration file. These transformer classes act as bridges between connected Web Parts, translating data between Web Parts with incompatible connection points."
  example:
  - "The following code example shows how to use the Transformers property.  \n  \n [!code-cs[System.Web.Configuration.WebPartsSection#2](~/add/codesnippet/CSharp/p-system.web.configurati_303_1.cs)]\n [!code-vb[System.Web.Configuration.WebPartsSection#2](~/add/codesnippet/VisualBasic/p-system.web.configurati_303_1.vb)]"
  syntax:
    content: public System.Web.Configuration.TransformerInfoCollection Transformers { get; }
    return:
      type: System.Web.Configuration.TransformerInfoCollection
      description: "A <see cref=&quot;T:System.Web.Configuration.TransformerInfoCollection&quot;></see> collection of <see cref=&quot;T:System.Web.Configuration.TransformerInfo&quot;></see> objects."
  overload: System.Web.Configuration.WebPartsSection.Transformers*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.WebPartsSection.#ctor
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: WebPartsSection()
  nameWithType: WebPartsSection.WebPartsSection()
  fullName: System.Web.Configuration.WebPartsSection.WebPartsSection()
- uid: System.Web.Configuration.WebPartsSection.EnableExport
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: EnableExport
  nameWithType: WebPartsSection.EnableExport
  fullName: System.Web.Configuration.WebPartsSection.EnableExport
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.WebPartsSection.GetRuntimeObject
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: GetRuntimeObject()
  nameWithType: WebPartsSection.GetRuntimeObject()
  fullName: System.Web.Configuration.WebPartsSection.GetRuntimeObject()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.WebPartsSection.Personalization
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: Personalization
  nameWithType: WebPartsSection.Personalization
  fullName: System.Web.Configuration.WebPartsSection.Personalization
- uid: System.Web.Configuration.WebPartsPersonalization
  parent: System.Web.Configuration
  isExternal: false
  name: WebPartsPersonalization
  nameWithType: WebPartsPersonalization
  fullName: System.Web.Configuration.WebPartsPersonalization
- uid: System.Web.Configuration.WebPartsSection.Properties
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: Properties
  nameWithType: WebPartsSection.Properties
  fullName: System.Web.Configuration.WebPartsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.WebPartsSection.Transformers
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: Transformers
  nameWithType: WebPartsSection.Transformers
  fullName: System.Web.Configuration.WebPartsSection.Transformers
- uid: System.Web.Configuration.TransformerInfoCollection
  parent: System.Web.Configuration
  isExternal: false
  name: TransformerInfoCollection
  nameWithType: TransformerInfoCollection
  fullName: System.Web.Configuration.TransformerInfoCollection
- uid: System.Web.Configuration.WebPartsSection.#ctor*
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: WebPartsSection
  nameWithType: WebPartsSection.WebPartsSection
- uid: System.Web.Configuration.WebPartsSection.EnableExport*
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: EnableExport
  nameWithType: WebPartsSection.EnableExport
- uid: System.Web.Configuration.WebPartsSection.GetRuntimeObject*
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: GetRuntimeObject
  nameWithType: WebPartsSection.GetRuntimeObject
- uid: System.Web.Configuration.WebPartsSection.Personalization*
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: Personalization
  nameWithType: WebPartsSection.Personalization
- uid: System.Web.Configuration.WebPartsSection.Properties*
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: Properties
  nameWithType: WebPartsSection.Properties
- uid: System.Web.Configuration.WebPartsSection.Transformers*
  parent: System.Web.Configuration.WebPartsSection
  isExternal: false
  name: Transformers
  nameWithType: WebPartsSection.Transformers
