### YamlMime:ManagedReference
items:
- uid: System.Web.Hosting.ApplicationHost
  id: ApplicationHost
  children:
  - System.Web.Hosting.ApplicationHost.CreateApplicationHost(System.Type,System.String,System.String)
  langs:
  - csharp
  name: ApplicationHost
  nameWithType: ApplicationHost
  fullName: System.Web.Hosting.ApplicationHost
  type: Class
  summary: "Enables hosting of ASP.NET pages outside the Internet Information Services (IIS) application. This class enables the host to create application domains for processing ASP.NET requests."
  remarks: "ApplicationHost is introduced in the .NET Framework version 3.5.  For more information, see [Versions and Dependencies](../Topic/.NET%20Framework%20Versions%20and%20Dependencies.md)."
  syntax:
    content: public sealed class ApplicationHost
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Web.Hosting.ApplicationHost.CreateApplicationHost(System.Type,System.String,System.String)
  id: CreateApplicationHost(System.Type,System.String,System.String)
  parent: System.Web.Hosting.ApplicationHost
  langs:
  - csharp
  name: CreateApplicationHost(Type,String,String)
  nameWithType: ApplicationHost.CreateApplicationHost(Type,String,String)
  fullName: System.Web.Hosting.ApplicationHost.CreateApplicationHost(Type,String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Creates and configures an application domain for hosting ASP.NET."
  syntax:
    content: public static object CreateApplicationHost (Type hostType, string virtualDir, string physicalDir);
    parameters:
    - id: hostType
      type: System.Type
      description: "The name of a user-supplied class to be created in the new application domain."
    - id: virtualDir
      type: System.String
      description: "The virtual directory for the application domain; for example, /myapp."
    - id: physicalDir
      type: System.String
      description: "The physical directory for the application domain where ASP.NET pages are located; for example, c:\\mypages."
    return:
      type: System.Object
      description: "To be added."
  overload: System.Web.Hosting.ApplicationHost.CreateApplicationHost*
  exceptions:
  - type: System.PlatformNotSupportedException
    commentId: T:System.PlatformNotSupportedException
    description: "The Web host computer is not running the Windows NT platform or a Coriolis environment."
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Hosting.ApplicationHost.CreateApplicationHost(System.Type,System.String,System.String)
  parent: System.Web.Hosting.ApplicationHost
  isExternal: false
  name: CreateApplicationHost(Type,String,String)
  nameWithType: ApplicationHost.CreateApplicationHost(Type,String,String)
  fullName: System.Web.Hosting.ApplicationHost.CreateApplicationHost(Type,String,String)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Hosting.ApplicationHost.CreateApplicationHost*
  parent: System.Web.Hosting.ApplicationHost
  isExternal: false
  name: CreateApplicationHost
  nameWithType: ApplicationHost.CreateApplicationHost
