### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.WebRequestModuleElement
  id: WebRequestModuleElement
  children:
  - System.Net.Configuration.WebRequestModuleElement.#ctor
  - System.Net.Configuration.WebRequestModuleElement.#ctor(System.String,System.String)
  - System.Net.Configuration.WebRequestModuleElement.#ctor(System.String,System.Type)
  - System.Net.Configuration.WebRequestModuleElement.Prefix
  - System.Net.Configuration.WebRequestModuleElement.Properties
  - System.Net.Configuration.WebRequestModuleElement.Type
  langs:
  - csharp
  name: WebRequestModuleElement
  nameWithType: WebRequestModuleElement
  fullName: System.Net.Configuration.WebRequestModuleElement
  type: Class
  summary: "Represents a URI prefix and the associated class that handles creating Web requests for the prefix. This class cannot be inherited."
  remarks: "Using the <xref:System.Net.WebRequest> and <xref:System.Net.WebResponse> classes, applications can request resources for any valid <xref:System.Uri>. Use this configuration element to specify a module that is registered to work with the <xref:System.Net.WebRequest.Create%2A> overloads to create new requests.  \n  \n This class corresponds to the [\\<add> Element for webRequestModules (Network Settings)](../Topic/%3Cadd%3E%20Element%20for%20webRequestModules%20\\(Network%20Settings\\).md) configuration element.  \n  \n This class is used to specify modules registered to authenticate requests made with the <xref:System.Net.WebRequest> and <xref:System.Net.WebClient> classes.  \n  \n This class provides programmatic access to information that can be stored in configuration files.  \n  \n The .NET Framework version 2.0 provides Web request modules that create requests for resources with the following prefixes:  \n  \n-   HTTP  \n  \n-   HTTPS  \n  \n-   FTP  \n  \n-   FILE"
  syntax:
    content: 'public sealed class WebRequestModuleElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.WebRequestModuleElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.WebRequestModuleElement
  langs:
  - csharp
  name: WebRequestModuleElement()
  nameWithType: WebRequestModuleElement.WebRequestModuleElement()
  fullName: System.Net.Configuration.WebRequestModuleElement.WebRequestModuleElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Net.Configuration.WebRequestModuleElement&quot;></see> class."
  syntax:
    content: public WebRequestModuleElement ();
    parameters: []
  overload: System.Net.Configuration.WebRequestModuleElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.WebRequestModuleElement.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Net.Configuration.WebRequestModuleElement
  langs:
  - csharp
  name: WebRequestModuleElement(String,String)
  nameWithType: WebRequestModuleElement.WebRequestModuleElement(String,String)
  fullName: System.Net.Configuration.WebRequestModuleElement.WebRequestModuleElement(String,String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Net.Configuration.WebRequestModuleElement&quot;></see> class using the specified URI prefix and type information."
  remarks: "The `type` parameter contains the fully qualified type name followed by a comma (,) and the assembly information. The elements of the assembly information are separated with commas, for example, &quot;`System.Net.DigestClient, System, Version=2.0.3600.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot;`.       The <xref:System.Net.Configuration.WebRequestModuleElement.Prefix%2A> property is set to `prefix` and the <xref:System.Net.Configuration.WebRequestModuleElement.Type%2A> property is set to `type`."
  syntax:
    content: public WebRequestModuleElement (string prefix, string type);
    parameters:
    - id: prefix
      type: System.String
      description: "A string containing a URI prefix."
    - id: type
      type: System.String
      description: "A string containing the type and assembly information for the class that handles creating requests for resources that use the `prefix` URI prefix. For more information, see the Remarks section."
  overload: System.Net.Configuration.WebRequestModuleElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.WebRequestModuleElement.#ctor(System.String,System.Type)
  id: '#ctor(System.String,System.Type)'
  parent: System.Net.Configuration.WebRequestModuleElement
  langs:
  - csharp
  name: WebRequestModuleElement(String,Type)
  nameWithType: WebRequestModuleElement.WebRequestModuleElement(String,Type)
  fullName: System.Net.Configuration.WebRequestModuleElement.WebRequestModuleElement(String,Type)
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Net.Configuration.WebRequestModuleElement&quot;></see> class using the specified URI prefix and type identifier."
  remarks: "The <xref:System.Net.Configuration.WebRequestModuleElement.Prefix%2A> property is set to `prefix` and the <xref:System.Net.Configuration.WebRequestModuleElement.Type%2A> property is set to `type`."
  syntax:
    content: public WebRequestModuleElement (string prefix, Type type);
    parameters:
    - id: prefix
      type: System.String
      description: "A string containing a URI prefix."
    - id: type
      type: System.Type
      description: "A <xref:System.Type> that identifies the class that handles creating requests for resources that use the `prefix` URI prefix."
  overload: System.Net.Configuration.WebRequestModuleElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.WebRequestModuleElement.Prefix
  id: Prefix
  parent: System.Net.Configuration.WebRequestModuleElement
  langs:
  - csharp
  name: Prefix
  nameWithType: WebRequestModuleElement.Prefix
  fullName: System.Net.Configuration.WebRequestModuleElement.Prefix
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Gets or sets the URI prefix for the current Web request module."
  remarks: "The .NET Framework version 2.0 provides Web request modules that create requests for resources with the following prefixes:      -   HTTP      -   HTTPS      -   FTP      -   FILE"
  syntax:
    content: public string Prefix { get; set; }
    return:
      type: System.String
      description: "A string that contains a URI prefix."
  overload: System.Net.Configuration.WebRequestModuleElement.Prefix*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.WebRequestModuleElement.Properties
  id: Properties
  parent: System.Net.Configuration.WebRequestModuleElement
  langs:
  - csharp
  name: Properties
  nameWithType: WebRequestModuleElement.Properties
  fullName: System.Net.Configuration.WebRequestModuleElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.Net.Configuration.WebRequestModuleElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Net.Configuration.WebRequestModuleElement.Type
  id: Type
  parent: System.Net.Configuration.WebRequestModuleElement
  langs:
  - csharp
  name: Type
  nameWithType: WebRequestModuleElement.Type
  fullName: System.Net.Configuration.WebRequestModuleElement.Type
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Gets or sets a class that creates Web requests."
  remarks: "Using the <xref:System.Net.WebRequest> and <xref:System.Net.WebResponse> classes, applications can request resources for any valid <xref:System.Uri>. Use this property to specify a type that is registered to work with the <xref:System.Net.WebRequest.Create%2A> method to create new requests.       The .NET Framework version 2.0 provides Web request modules that create requests for resources with the following prefixes:      -   HTTP      -   HTTPS      -   FTP      -   FILE"
  syntax:
    content: public Type Type { get; set; }
    return:
      type: System.Type
      description: "A &lt;xref:System.Type&gt; instance that identifies a Web request module."
  overload: System.Net.Configuration.WebRequestModuleElement.Type*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.WebRequestModuleElement.#ctor
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: WebRequestModuleElement()
  nameWithType: WebRequestModuleElement.WebRequestModuleElement()
  fullName: System.Net.Configuration.WebRequestModuleElement.WebRequestModuleElement()
- uid: System.Net.Configuration.WebRequestModuleElement.#ctor(System.String,System.String)
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: WebRequestModuleElement(String,String)
  nameWithType: WebRequestModuleElement.WebRequestModuleElement(String,String)
  fullName: System.Net.Configuration.WebRequestModuleElement.WebRequestModuleElement(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Net.Configuration.WebRequestModuleElement.#ctor(System.String,System.Type)
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: WebRequestModuleElement(String,Type)
  nameWithType: WebRequestModuleElement.WebRequestModuleElement(String,Type)
  fullName: System.Net.Configuration.WebRequestModuleElement.WebRequestModuleElement(String,Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Net.Configuration.WebRequestModuleElement.Prefix
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: Prefix
  nameWithType: WebRequestModuleElement.Prefix
  fullName: System.Net.Configuration.WebRequestModuleElement.Prefix
- uid: System.Net.Configuration.WebRequestModuleElement.Properties
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: Properties
  nameWithType: WebRequestModuleElement.Properties
  fullName: System.Net.Configuration.WebRequestModuleElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.WebRequestModuleElement.Type
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: Type
  nameWithType: WebRequestModuleElement.Type
  fullName: System.Net.Configuration.WebRequestModuleElement.Type
- uid: System.Net.Configuration.WebRequestModuleElement.#ctor*
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: WebRequestModuleElement
  nameWithType: WebRequestModuleElement.WebRequestModuleElement
- uid: System.Net.Configuration.WebRequestModuleElement.Prefix*
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: Prefix
  nameWithType: WebRequestModuleElement.Prefix
- uid: System.Net.Configuration.WebRequestModuleElement.Properties*
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: Properties
  nameWithType: WebRequestModuleElement.Properties
- uid: System.Net.Configuration.WebRequestModuleElement.Type*
  parent: System.Net.Configuration.WebRequestModuleElement
  isExternal: false
  name: Type
  nameWithType: WebRequestModuleElement.Type
