### YamlMime:ManagedReference
items:
- uid: System.Configuration.CallbackValidatorAttribute
  id: CallbackValidatorAttribute
  children:
  - System.Configuration.CallbackValidatorAttribute.#ctor
  - System.Configuration.CallbackValidatorAttribute.CallbackMethodName
  - System.Configuration.CallbackValidatorAttribute.Type
  - System.Configuration.CallbackValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: CallbackValidatorAttribute
  nameWithType: CallbackValidatorAttribute
  fullName: System.Configuration.CallbackValidatorAttribute
  type: Class
  summary: "Specifies a <see cref=&quot;T:System.Configuration.CallbackValidator&quot;></see> object to use for code validation. This class cannot be inherited."
  remarks: "The CallbackValidatorAttribute attribute class provides an association between a <xref:System.Configuration.CallbackValidator> object and the code to validate. The CallbackValidatorAttribute class is derived from the <xref:System.Configuration.ConfigurationValidatorAttribute> class."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class CallbackValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.CallbackValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.CallbackValidatorAttribute
  langs:
  - csharp
  name: CallbackValidatorAttribute()
  nameWithType: CallbackValidatorAttribute.CallbackValidatorAttribute()
  fullName: System.Configuration.CallbackValidatorAttribute.CallbackValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.CallbackValidatorAttribute&quot;></see> class."
  syntax:
    content: public CallbackValidatorAttribute ();
    parameters: []
  overload: System.Configuration.CallbackValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.CallbackValidatorAttribute.CallbackMethodName
  id: CallbackMethodName
  parent: System.Configuration.CallbackValidatorAttribute
  langs:
  - csharp
  name: CallbackMethodName
  nameWithType: CallbackValidatorAttribute.CallbackMethodName
  fullName: System.Configuration.CallbackValidatorAttribute.CallbackMethodName
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets or sets the name of the callback method."
  syntax:
    content: public string CallbackMethodName { get; set; }
    return:
      type: System.String
      description: "The name of the method to call."
  overload: System.Configuration.CallbackValidatorAttribute.CallbackMethodName*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.CallbackValidatorAttribute.Type
  id: Type
  parent: System.Configuration.CallbackValidatorAttribute
  langs:
  - csharp
  name: Type
  nameWithType: CallbackValidatorAttribute.Type
  fullName: System.Configuration.CallbackValidatorAttribute.Type
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets or sets the type of the validator."
  syntax:
    content: public Type Type { get; set; }
    return:
      type: System.Type
      description: "The &lt;xref:System.Type&gt; of the current validator attribute instance."
  overload: System.Configuration.CallbackValidatorAttribute.Type*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.CallbackValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.CallbackValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: CallbackValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.CallbackValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gets the validator instance."
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "The current <see cref=&quot;T:System.Configuration.ConfigurationValidatorBase&quot;></see> instance."
  overload: System.Configuration.CallbackValidatorAttribute.ValidatorInstance*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "The value of the <xref:System.Configuration.CallbackValidatorAttribute.Type%2A> property is ."
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "The <xref:System.Configuration.CallbackValidatorAttribute.CallbackMethodName%2A> property is not set to a public static void method with one object parameter."
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.Configuration.CallbackValidatorAttribute.#ctor
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: CallbackValidatorAttribute()
  nameWithType: CallbackValidatorAttribute.CallbackValidatorAttribute()
  fullName: System.Configuration.CallbackValidatorAttribute.CallbackValidatorAttribute()
- uid: System.Configuration.CallbackValidatorAttribute.CallbackMethodName
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: CallbackMethodName
  nameWithType: CallbackValidatorAttribute.CallbackMethodName
  fullName: System.Configuration.CallbackValidatorAttribute.CallbackMethodName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.CallbackValidatorAttribute.Type
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: Type
  nameWithType: CallbackValidatorAttribute.Type
  fullName: System.Configuration.CallbackValidatorAttribute.Type
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.CallbackValidatorAttribute.ValidatorInstance
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: CallbackValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.CallbackValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.CallbackValidatorAttribute.#ctor*
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: CallbackValidatorAttribute
  nameWithType: CallbackValidatorAttribute.CallbackValidatorAttribute
- uid: System.Configuration.CallbackValidatorAttribute.CallbackMethodName*
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: CallbackMethodName
  nameWithType: CallbackValidatorAttribute.CallbackMethodName
- uid: System.Configuration.CallbackValidatorAttribute.Type*
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: Type
  nameWithType: CallbackValidatorAttribute.Type
- uid: System.Configuration.CallbackValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: CallbackValidatorAttribute.ValidatorInstance
