### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement
  id: UdpRetransmissionSettingsElement
  children:
  - System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.#ctor
  - System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.DelayLowerBound
  - System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.DelayUpperBound
  - System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.MaxDelayPerRetransmission
  - System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.MaxMulticastRetransmitCount
  - System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.MaxUnicastRetransmitCount
  - System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.Properties
  langs:
  - csharp
  name: UdpRetransmissionSettingsElement
  nameWithType: UdpRetransmissionSettingsElement
  fullName: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement
  type: Class
  summary: "Represents a UDP retransmission settings element."
  syntax:
    content: 'public sealed class UdpRetransmissionSettingsElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement
  langs:
  - csharp
  name: UdpRetransmissionSettingsElement()
  nameWithType: UdpRetransmissionSettingsElement.UdpRetransmissionSettingsElement()
  fullName: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.UdpRetransmissionSettingsElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Channels
  namespace: System.ServiceModel.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.UdpRetransmissionSettingsElement&quot;></see> class."
  syntax:
    content: public UdpRetransmissionSettingsElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.DelayLowerBound
  id: DelayLowerBound
  parent: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement
  langs:
  - csharp
  name: DelayLowerBound
  nameWithType: UdpRetransmissionSettingsElement.DelayLowerBound
  fullName: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.DelayLowerBound
  type: Property
  assemblies:
  - System.ServiceModel.Channels
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets the lower bound delay for the UDP retransmission settings element."
  syntax:
    content: public TimeSpan DelayLowerBound { get; set; }
    return:
      type: System.TimeSpan
      description: "The lower bound delay for the UDP retransmission settings element."
  overload: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.DelayLowerBound*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.DelayUpperBound
  id: DelayUpperBound
  parent: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement
  langs:
  - csharp
  name: DelayUpperBound
  nameWithType: UdpRetransmissionSettingsElement.DelayUpperBound
  fullName: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.DelayUpperBound
  type: Property
  assemblies:
  - System.ServiceModel.Channels
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets the upper bound delay for the UDP retransmission settings element."
  syntax:
    content: public TimeSpan DelayUpperBound { get; set; }
    return:
      type: System.TimeSpan
      description: "The upper bound delay for the UDP retransmission settings element."
  overload: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.DelayUpperBound*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.MaxDelayPerRetransmission
  id: MaxDelayPerRetransmission
  parent: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement
  langs:
  - csharp
  name: MaxDelayPerRetransmission
  nameWithType: UdpRetransmissionSettingsElement.MaxDelayPerRetransmission
  fullName: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.MaxDelayPerRetransmission
  type: Property
  assemblies:
  - System.ServiceModel.Channels
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets the maximum delay per retransmission for the UDP retransmission settings element."
  syntax:
    content: public TimeSpan MaxDelayPerRetransmission { get; set; }
    return:
      type: System.TimeSpan
      description: "The maximum delay for retransmission for the UDP retransmission settings element."
  overload: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.MaxDelayPerRetransmission*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.MaxMulticastRetransmitCount
  id: MaxMulticastRetransmitCount
  parent: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement
  langs:
  - csharp
  name: MaxMulticastRetransmitCount
  nameWithType: UdpRetransmissionSettingsElement.MaxMulticastRetransmitCount
  fullName: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.MaxMulticastRetransmitCount
  type: Property
  assemblies:
  - System.ServiceModel.Channels
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets the number of maximum multicast for retransmission for the UDP retransmission settings element."
  syntax:
    content: public int MaxMulticastRetransmitCount { get; set; }
    return:
      type: System.Int32
      description: "The number of maximum multicast for retransmission."
  overload: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.MaxMulticastRetransmitCount*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.MaxUnicastRetransmitCount
  id: MaxUnicastRetransmitCount
  parent: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement
  langs:
  - csharp
  name: MaxUnicastRetransmitCount
  nameWithType: UdpRetransmissionSettingsElement.MaxUnicastRetransmitCount
  fullName: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.MaxUnicastRetransmitCount
  type: Property
  assemblies:
  - System.ServiceModel.Channels
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets the number of maximum unicast for retransmission for the UDP retransmission settings element."
  syntax:
    content: public int MaxUnicastRetransmitCount { get; set; }
    return:
      type: System.Int32
      description: "The number of maximum unicast for retransmission for the UDP retransmission settings element."
  overload: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.MaxUnicastRetransmitCount*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement
  langs:
  - csharp
  name: Properties
  nameWithType: UdpRetransmissionSettingsElement.Properties
  fullName: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Channels
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.#ctor
  parent: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement
  isExternal: false
  name: UdpRetransmissionSettingsElement()
  nameWithType: UdpRetransmissionSettingsElement.UdpRetransmissionSettingsElement()
  fullName: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.UdpRetransmissionSettingsElement()
- uid: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.DelayLowerBound
  parent: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement
  isExternal: false
  name: DelayLowerBound
  nameWithType: UdpRetransmissionSettingsElement.DelayLowerBound
  fullName: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.DelayLowerBound
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.DelayUpperBound
  parent: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement
  isExternal: false
  name: DelayUpperBound
  nameWithType: UdpRetransmissionSettingsElement.DelayUpperBound
  fullName: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.DelayUpperBound
- uid: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.MaxDelayPerRetransmission
  parent: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement
  isExternal: false
  name: MaxDelayPerRetransmission
  nameWithType: UdpRetransmissionSettingsElement.MaxDelayPerRetransmission
  fullName: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.MaxDelayPerRetransmission
- uid: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.MaxMulticastRetransmitCount
  parent: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement
  isExternal: false
  name: MaxMulticastRetransmitCount
  nameWithType: UdpRetransmissionSettingsElement.MaxMulticastRetransmitCount
  fullName: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.MaxMulticastRetransmitCount
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.MaxUnicastRetransmitCount
  parent: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement
  isExternal: false
  name: MaxUnicastRetransmitCount
  nameWithType: UdpRetransmissionSettingsElement.MaxUnicastRetransmitCount
  fullName: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.MaxUnicastRetransmitCount
- uid: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.Properties
  parent: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement
  isExternal: false
  name: Properties
  nameWithType: UdpRetransmissionSettingsElement.Properties
  fullName: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.#ctor*
  parent: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement
  isExternal: false
  name: UdpRetransmissionSettingsElement
  nameWithType: UdpRetransmissionSettingsElement.UdpRetransmissionSettingsElement
- uid: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.DelayLowerBound*
  parent: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement
  isExternal: false
  name: DelayLowerBound
  nameWithType: UdpRetransmissionSettingsElement.DelayLowerBound
- uid: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.DelayUpperBound*
  parent: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement
  isExternal: false
  name: DelayUpperBound
  nameWithType: UdpRetransmissionSettingsElement.DelayUpperBound
- uid: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.MaxDelayPerRetransmission*
  parent: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement
  isExternal: false
  name: MaxDelayPerRetransmission
  nameWithType: UdpRetransmissionSettingsElement.MaxDelayPerRetransmission
- uid: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.MaxMulticastRetransmitCount*
  parent: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement
  isExternal: false
  name: MaxMulticastRetransmitCount
  nameWithType: UdpRetransmissionSettingsElement.MaxMulticastRetransmitCount
- uid: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.MaxUnicastRetransmitCount*
  parent: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement
  isExternal: false
  name: MaxUnicastRetransmitCount
  nameWithType: UdpRetransmissionSettingsElement.MaxUnicastRetransmitCount
- uid: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement.Properties*
  parent: System.ServiceModel.Configuration.UdpRetransmissionSettingsElement
  isExternal: false
  name: Properties
  nameWithType: UdpRetransmissionSettingsElement.Properties
