### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.RemoveBehaviorElement
  id: RemoveBehaviorElement
  children:
  - System.ServiceModel.Configuration.RemoveBehaviorElement.#ctor
  - System.ServiceModel.Configuration.RemoveBehaviorElement.BehaviorType
  - System.ServiceModel.Configuration.RemoveBehaviorElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.RemoveBehaviorElement.CreateBehavior
  - System.ServiceModel.Configuration.RemoveBehaviorElement.Name
  - System.ServiceModel.Configuration.RemoveBehaviorElement.Properties
  langs:
  - csharp
  name: RemoveBehaviorElement
  nameWithType: RemoveBehaviorElement
  fullName: System.ServiceModel.Configuration.RemoveBehaviorElement
  type: Class
  summary: "A configuration element to remove a particular service or endpoint behavior."
  syntax:
    content: 'public sealed class RemoveBehaviorElement : System.ServiceModel.Configuration.BehaviorExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  - System.ServiceModel.Configuration.BehaviorExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.RemoveBehaviorElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.RemoveBehaviorElement
  langs:
  - csharp
  name: RemoveBehaviorElement()
  nameWithType: RemoveBehaviorElement.RemoveBehaviorElement()
  fullName: System.ServiceModel.Configuration.RemoveBehaviorElement.RemoveBehaviorElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Creates a new instance of the <see cref=&quot;T:System.ServiceModel.Configuration.RemoveBehaviorElement&quot;></see> class."
  syntax:
    content: public RemoveBehaviorElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.RemoveBehaviorElement.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.RemoveBehaviorElement.BehaviorType
  id: BehaviorType
  parent: System.ServiceModel.Configuration.RemoveBehaviorElement
  langs:
  - csharp
  name: BehaviorType
  nameWithType: RemoveBehaviorElement.BehaviorType
  fullName: System.ServiceModel.Configuration.RemoveBehaviorElement.BehaviorType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets the type of the behavior that is removed."
  syntax:
    content: public override Type BehaviorType { get; }
    return:
      type: System.Type
      description: "A behavior type."
  overload: System.ServiceModel.Configuration.RemoveBehaviorElement.BehaviorType*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.RemoveBehaviorElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  id: CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.RemoveBehaviorElement
  langs:
  - csharp
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: RemoveBehaviorElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.RemoveBehaviorElement.CopyFrom(ServiceModelExtensionElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Copies content of the specified <see cref=&quot;T:System.ServiceModel.Configuration.ServiceModelExtensionElement&quot;></see> to the current <see cref=&quot;T:System.ServiceModel.Configuration.RemoveBehaviorElement&quot;></see> object."
  syntax:
    content: public override void CopyFrom (System.ServiceModel.Configuration.ServiceModelExtensionElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.ServiceModelExtensionElement
      description: "The service model extension element that supplies the content."
  overload: System.ServiceModel.Configuration.RemoveBehaviorElement.CopyFrom*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.RemoveBehaviorElement.CreateBehavior
  id: CreateBehavior
  parent: System.ServiceModel.Configuration.RemoveBehaviorElement
  langs:
  - csharp
  name: CreateBehavior()
  nameWithType: RemoveBehaviorElement.CreateBehavior()
  fullName: System.ServiceModel.Configuration.RemoveBehaviorElement.CreateBehavior()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override object CreateBehavior ();
    parameters: []
    return:
      type: System.Object
      description: "To be added."
  overload: System.ServiceModel.Configuration.RemoveBehaviorElement.CreateBehavior*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.RemoveBehaviorElement.Name
  id: Name
  parent: System.ServiceModel.Configuration.RemoveBehaviorElement
  langs:
  - csharp
  name: Name
  nameWithType: RemoveBehaviorElement.Name
  fullName: System.ServiceModel.Configuration.RemoveBehaviorElement.Name
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Gets or sets the name of the configuration element that removes the behavior."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "The element name."
  overload: System.ServiceModel.Configuration.RemoveBehaviorElement.Name*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Configuration.RemoveBehaviorElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.RemoveBehaviorElement
  langs:
  - csharp
  name: Properties
  nameWithType: RemoveBehaviorElement.Properties
  fullName: System.ServiceModel.Configuration.RemoveBehaviorElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "To be added."
  overload: System.ServiceModel.Configuration.RemoveBehaviorElement.Properties*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.ServiceModel.Configuration.BehaviorExtensionElement
  isExternal: false
  name: System.ServiceModel.Configuration.BehaviorExtensionElement
- uid: System.ServiceModel.Configuration.RemoveBehaviorElement.#ctor
  parent: System.ServiceModel.Configuration.RemoveBehaviorElement
  isExternal: false
  name: RemoveBehaviorElement()
  nameWithType: RemoveBehaviorElement.RemoveBehaviorElement()
  fullName: System.ServiceModel.Configuration.RemoveBehaviorElement.RemoveBehaviorElement()
- uid: System.ServiceModel.Configuration.RemoveBehaviorElement.BehaviorType
  parent: System.ServiceModel.Configuration.RemoveBehaviorElement
  isExternal: false
  name: BehaviorType
  nameWithType: RemoveBehaviorElement.BehaviorType
  fullName: System.ServiceModel.Configuration.RemoveBehaviorElement.BehaviorType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.RemoveBehaviorElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.RemoveBehaviorElement
  isExternal: false
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: RemoveBehaviorElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.RemoveBehaviorElement.CopyFrom(ServiceModelExtensionElement)
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelExtensionElement
  nameWithType: ServiceModelExtensionElement
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement
- uid: System.ServiceModel.Configuration.RemoveBehaviorElement.CreateBehavior
  parent: System.ServiceModel.Configuration.RemoveBehaviorElement
  isExternal: false
  name: CreateBehavior()
  nameWithType: RemoveBehaviorElement.CreateBehavior()
  fullName: System.ServiceModel.Configuration.RemoveBehaviorElement.CreateBehavior()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Configuration.RemoveBehaviorElement.Name
  parent: System.ServiceModel.Configuration.RemoveBehaviorElement
  isExternal: false
  name: Name
  nameWithType: RemoveBehaviorElement.Name
  fullName: System.ServiceModel.Configuration.RemoveBehaviorElement.Name
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.RemoveBehaviorElement.Properties
  parent: System.ServiceModel.Configuration.RemoveBehaviorElement
  isExternal: false
  name: Properties
  nameWithType: RemoveBehaviorElement.Properties
  fullName: System.ServiceModel.Configuration.RemoveBehaviorElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.RemoveBehaviorElement.#ctor*
  parent: System.ServiceModel.Configuration.RemoveBehaviorElement
  isExternal: false
  name: RemoveBehaviorElement
  nameWithType: RemoveBehaviorElement.RemoveBehaviorElement
- uid: System.ServiceModel.Configuration.RemoveBehaviorElement.BehaviorType*
  parent: System.ServiceModel.Configuration.RemoveBehaviorElement
  isExternal: false
  name: BehaviorType
  nameWithType: RemoveBehaviorElement.BehaviorType
- uid: System.ServiceModel.Configuration.RemoveBehaviorElement.CopyFrom*
  parent: System.ServiceModel.Configuration.RemoveBehaviorElement
  isExternal: false
  name: CopyFrom
  nameWithType: RemoveBehaviorElement.CopyFrom
- uid: System.ServiceModel.Configuration.RemoveBehaviorElement.CreateBehavior*
  parent: System.ServiceModel.Configuration.RemoveBehaviorElement
  isExternal: false
  name: CreateBehavior
  nameWithType: RemoveBehaviorElement.CreateBehavior
- uid: System.ServiceModel.Configuration.RemoveBehaviorElement.Name*
  parent: System.ServiceModel.Configuration.RemoveBehaviorElement
  isExternal: false
  name: Name
  nameWithType: RemoveBehaviorElement.Name
- uid: System.ServiceModel.Configuration.RemoveBehaviorElement.Properties*
  parent: System.ServiceModel.Configuration.RemoveBehaviorElement
  isExternal: false
  name: Properties
  nameWithType: RemoveBehaviorElement.Properties
