### YamlMime:ManagedReference
items:
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute
  id: ManagementConfigurationAttribute
  children:
  - System.Management.Instrumentation.ManagementConfigurationAttribute.#ctor
  - System.Management.Instrumentation.ManagementConfigurationAttribute.Mode
  - System.Management.Instrumentation.ManagementConfigurationAttribute.Schema
  langs:
  - csharp
  name: ManagementConfigurationAttribute
  nameWithType: ManagementConfigurationAttribute
  fullName: System.Management.Instrumentation.ManagementConfigurationAttribute
  type: Class
  summary: "The ManagementConfiguration attribute indicates that a property or field represents a read-write WMI property.       Note: the WMI .NET libraries are now considered in final state, and no further development, enhancements, or updates will be available for non-security related issues affecting these libraries. The [MI APIs](https://msdn.microsoft.com/en-us/library/jj152383%28v=vs.80%29.aspx) should be used for all new development."
  remarks: "The property or field must be public. The class that contains the property must be marked with the <xref:System.Management.Instrumentation.ManagementEntityAttribute> attribute.       Any fields or properties in the class that are not marked with this or another WMI Provider Extensions attribute will not be instrumented."
  example:
  - "The following example shows how to use the ManagementConfiguration attribute to mark a property. This property is exposed to WMI.  \n  \n [C#]  \n  \n```  \n// Use the ManagementConfiguration attribute to specify that a property  \n// is a read/write property in the provider. Consumers will be  \n// able to get and set this property value through WMI.  \n[ManagementConfiguration]  \npublic double ReadableWritableProperty  \n{  \n    get { return this.propertyValue; }  \n    set { this.propertyValue = value; }  \n}  \n```"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property | System.AttributeTargets.Field, AllowMultiple=false)]

      public sealed class ManagementConfigurationAttribute : System.Management.Instrumentation.ManagementMemberAttribute
  inheritance:
  - System.Attribute
  - System.Management.Instrumentation.ManagementMemberAttribute
  implements: []
  inheritedMembers:
  - System.Management.Instrumentation.ManagementMemberAttribute.Name
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute.#ctor
  id: '#ctor'
  parent: System.Management.Instrumentation.ManagementConfigurationAttribute
  langs:
  - csharp
  name: ManagementConfigurationAttribute()
  nameWithType: ManagementConfigurationAttribute.ManagementConfigurationAttribute()
  fullName: System.Management.Instrumentation.ManagementConfigurationAttribute.ManagementConfigurationAttribute()
  type: Constructor
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "Initializes a new instance of the &lt;xref:System.Management.ManagementConfigurationAttribute&gt; class. This is the default constructor."
  syntax:
    content: public ManagementConfigurationAttribute ();
    parameters: []
  overload: System.Management.Instrumentation.ManagementConfigurationAttribute.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute.Mode
  id: Mode
  parent: System.Management.Instrumentation.ManagementConfigurationAttribute
  langs:
  - csharp
  name: Mode
  nameWithType: ManagementConfigurationAttribute.Mode
  fullName: System.Management.Instrumentation.ManagementConfigurationAttribute.Mode
  type: Property
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "Gets or sets the mode of the property, which specifies whether changes to it are applied as soon as possible or when a commit method is called."
  remarks: "If there is a commit method defined, it is responsible for updating all read-write WMI properties that use the <xref:System.Management.Instrumentation.ManagementConfigurationType> mode. It is identified by the <xref:System.Management.Instrumentation.ManagementCommitAttribute>."
  syntax:
    content: public System.Management.Instrumentation.ManagementConfigurationType Mode { get; set; }
    return:
      type: System.Management.Instrumentation.ManagementConfigurationType
      description: "Returns a <see cref=&quot;T:System.Management.Instrumentation.ManagementConfigurationType&quot;></see> that indicates whether the WMI property uses <see cref=&quot;T:System.Management.Instrumentation.ManagementConfigurationType&quot;></see> or <see cref=&quot;T:System.Management.Instrumentation.ManagementConfigurationType&quot;></see> mode."
  overload: System.Management.Instrumentation.ManagementConfigurationAttribute.Mode*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute.Schema
  id: Schema
  parent: System.Management.Instrumentation.ManagementConfigurationAttribute
  langs:
  - csharp
  name: Schema
  nameWithType: ManagementConfigurationAttribute.Schema
  fullName: System.Management.Instrumentation.ManagementConfigurationAttribute.Schema
  type: Property
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "Gets or sets a value that defines the type of output that the property that is marked with the ManagementConfiguration attribute will return."
  remarks: "If the returned type is <xref:System.Object?displayProperty=fullName>, then the output should be treated as a value of type <xref:System.Object?displayProperty=fullName>."
  syntax:
    content: public Type Schema { get; set; }
    return:
      type: System.Type
      description: "A &lt;xref:System.Type&gt; value representing the type of output that the property marked with the ManagementConfiguration attribute will return."
  overload: System.Management.Instrumentation.ManagementConfigurationAttribute.Schema*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Management.Instrumentation.ManagementMemberAttribute
  isExternal: false
  name: System.Management.Instrumentation.ManagementMemberAttribute
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute.#ctor
  parent: System.Management.Instrumentation.ManagementConfigurationAttribute
  isExternal: false
  name: ManagementConfigurationAttribute()
  nameWithType: ManagementConfigurationAttribute.ManagementConfigurationAttribute()
  fullName: System.Management.Instrumentation.ManagementConfigurationAttribute.ManagementConfigurationAttribute()
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute.Mode
  parent: System.Management.Instrumentation.ManagementConfigurationAttribute
  isExternal: false
  name: Mode
  nameWithType: ManagementConfigurationAttribute.Mode
  fullName: System.Management.Instrumentation.ManagementConfigurationAttribute.Mode
- uid: System.Management.Instrumentation.ManagementConfigurationType
  parent: System.Management.Instrumentation
  isExternal: false
  name: ManagementConfigurationType
  nameWithType: ManagementConfigurationType
  fullName: System.Management.Instrumentation.ManagementConfigurationType
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute.Schema
  parent: System.Management.Instrumentation.ManagementConfigurationAttribute
  isExternal: false
  name: Schema
  nameWithType: ManagementConfigurationAttribute.Schema
  fullName: System.Management.Instrumentation.ManagementConfigurationAttribute.Schema
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute.#ctor*
  parent: System.Management.Instrumentation.ManagementConfigurationAttribute
  isExternal: false
  name: ManagementConfigurationAttribute
  nameWithType: ManagementConfigurationAttribute.ManagementConfigurationAttribute
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute.Mode*
  parent: System.Management.Instrumentation.ManagementConfigurationAttribute
  isExternal: false
  name: Mode
  nameWithType: ManagementConfigurationAttribute.Mode
- uid: System.Management.Instrumentation.ManagementConfigurationAttribute.Schema*
  parent: System.Management.Instrumentation.ManagementConfigurationAttribute
  isExternal: false
  name: Schema
  nameWithType: ManagementConfigurationAttribute.Schema
