### YamlMime:ManagedReference
items:
- uid: System.Configuration.ProtectedConfigurationProvider
  id: ProtectedConfigurationProvider
  children:
  - System.Configuration.ProtectedConfigurationProvider.#ctor
  - System.Configuration.ProtectedConfigurationProvider.Decrypt(System.Xml.XmlNode)
  - System.Configuration.ProtectedConfigurationProvider.Encrypt(System.Xml.XmlNode)
  langs:
  - csharp
  name: ProtectedConfigurationProvider
  nameWithType: ProtectedConfigurationProvider
  fullName: System.Configuration.ProtectedConfigurationProvider
  type: Class
  summary: "Is the base class to create providers for encrypting and decrypting protected-configuration data."
  remarks: "You can encrypt sections of a configuration file to protect sensitive information used by your application. This improves security by making it difficult for unauthorized access even if an attacker gains access to your configuration file.       The .NET Framework includes two protected configuration providers that can be used to encrypt sections of a configuration file. The <xref:System.Configuration.RsaProtectedConfigurationProvider> class uses the <xref:System.Security.Cryptography.RSACryptoServiceProvider> to encrypt configuration sections. The <xref:System.Configuration.DpapiProtectedConfigurationProvider> class uses the Windows Data Protection API (DPAPI) to encrypt configuration sections.       You might have a requirement to encrypt sensitive information using an algorithm other than the RSA or DPAPI providers. In this case, you can build your own custom protected-configuration provider. The ProtectedConfigurationProvider is an abstract base class that you must inherit from to create your own protected-configuration provider.       Whether you use a standard or a custom provider, you must ensure that it is configured with the `add` element in the `providers` section of the `configProtectedData`  configuration section. (See next example.)       For details, see [Implementing a Protected Configuration Provider](../Topic/Implementing%20a%20Protected%20Configuration%20Provider.md).      > [!NOTE] >  When ASP.NET encounters encrypted configuration data, it performs decryption transparently using the configured provider. No action is required on your side other than making sure that you configure the required provider."
  example:
  - "The following example shows how to implement a custom ProtectedConfigurationProvider.  \n  \n To be able to configure this provider, as shown in the next configuration excerpt, you must install it in the Global Assembly Cache (GAC). Refer to [Implementing a Protected Configuration Provider](../Topic/Implementing%20a%20Protected%20Configuration%20Provider.md) for more information.  \n  \n [!code-cs[System.Configuration.ProtectedConfigurationProvider#1](~/add/codesnippet/CSharp/t-system.configuration.p_7_1.cs)]\n [!code-vb[System.Configuration.ProtectedConfigurationProvider#1](~/add/codesnippet/VisualBasic/t-system.configuration.p_7_1.vb)]  \n  \n The following example shows how to use the previous custom ProtectedConfigurationProvider.  \n  \n [!code-vb[System.Configuration.UsingProtectedConfigurationProvider#11](~/add/codesnippet/VisualBasic/t-system.configuration.p_7_2.vb)]\n [!code-cs[System.Configuration.UsingProtectedConfigurationProvider#11](~/add/codesnippet/CSharp/t-system.configuration.p_7_2.cs)]  \n  \n The following is an excerpt of the configuration file used by the above examples.  \n  \n```  \n<?xml version=\"1.0\" encoding=\"utf-8\" ?>  \n<configuration>  \n  \n  <configProtectedData >  \n    <providers>  \n      <clear />  \n      <add keyContainerName=\"pcKey.txt\"   \n        name=\"TripleDESProtectedConfigurationProvider\"  \ntype=\"Samples.Aspnet.TripleDESProtectedConfigurationProvider, protectedconfigurationproviderlib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=79e01ae0f5cfc66f, processorArchitecture=MSIL\" />  \n    </providers>  \n  \n  </configProtectedData >  \n  \n  <connectionStrings>  \n    <add name=\"NorthwindConnectionString\"   \n      connectionString=\"Data Source=webnetue2;Initial Catalog=Northwind;User ID=aspnet_test;Password=test\"  \nproviderName=\"System.Data.SqlClient\" />  \n  </connectionStrings>  \n  \n</configuration>  \n```"
  syntax:
    content: 'public abstract class ProtectedConfigurationProvider : System.Configuration.Provider.ProviderBase'
  inheritance:
  - System.Object
  - System.Configuration.Provider.ProviderBase
  implements: []
  inheritedMembers:
  - System.Configuration.Provider.ProviderBase.Description
  - System.Configuration.Provider.ProviderBase.Initialize(System.String,System.Collections.Specialized.NameValueCollection)
  - System.Configuration.Provider.ProviderBase.Name
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProtectedConfigurationProvider.#ctor
  id: '#ctor'
  parent: System.Configuration.ProtectedConfigurationProvider
  langs:
  - csharp
  name: ProtectedConfigurationProvider()
  nameWithType: ProtectedConfigurationProvider.ProtectedConfigurationProvider()
  fullName: System.Configuration.ProtectedConfigurationProvider.ProtectedConfigurationProvider()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Initializes a new instance of the <see cref=&quot;T:System.Configuration.ProtectedConfigurationProvider&quot;></see> class using default settings."
  syntax:
    content: protected ProtectedConfigurationProvider ();
    parameters: []
  overload: System.Configuration.ProtectedConfigurationProvider.#ctor*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProtectedConfigurationProvider.Decrypt(System.Xml.XmlNode)
  id: Decrypt(System.Xml.XmlNode)
  parent: System.Configuration.ProtectedConfigurationProvider
  langs:
  - csharp
  name: Decrypt(XmlNode)
  nameWithType: ProtectedConfigurationProvider.Decrypt(XmlNode)
  fullName: System.Configuration.ProtectedConfigurationProvider.Decrypt(XmlNode)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Decrypts the passed <see cref=&quot;T:System.Xml.XmlNode&quot;></see> object from a configuration file."
  remarks: ''
  example:
  - "The following example shows how to use Decrypt method to perform custom decryption.  \n  \n [!code-cs[System.Configuration.ProtectedConfigurationProvider#2](~/add/codesnippet/CSharp/490b80fa-87ff-462a-bceb-_1.cs)]\n [!code-vb[System.Configuration.ProtectedConfigurationProvider#2](~/add/codesnippet/VisualBasic/490b80fa-87ff-462a-bceb-_1.vb)]"
  syntax:
    content: public abstract System.Xml.XmlNode Decrypt (System.Xml.XmlNode encryptedNode);
    parameters:
    - id: encryptedNode
      type: System.Xml.XmlNode
      description: "The  object to decrypt."
    return:
      type: System.Xml.XmlNode
      description: "To be added."
  overload: System.Configuration.ProtectedConfigurationProvider.Decrypt*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.Configuration.ProtectedConfigurationProvider.Encrypt(System.Xml.XmlNode)
  id: Encrypt(System.Xml.XmlNode)
  parent: System.Configuration.ProtectedConfigurationProvider
  langs:
  - csharp
  name: Encrypt(XmlNode)
  nameWithType: ProtectedConfigurationProvider.Encrypt(XmlNode)
  fullName: System.Configuration.ProtectedConfigurationProvider.Encrypt(XmlNode)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Encrypts the passed <see cref=&quot;T:System.Xml.XmlNode&quot;></see> object from a configuration file."
  remarks: ''
  example:
  - "The following example shows how to use Encrypt to perform custom encryption.  \n  \n [!code-cs[System.Configuration.ProtectedConfigurationProvider#3](~/add/codesnippet/CSharp/1cc011d4-bc06-4499-99c2-_1.cs)]\n [!code-vb[System.Configuration.ProtectedConfigurationProvider#3](~/add/codesnippet/VisualBasic/1cc011d4-bc06-4499-99c2-_1.vb)]"
  syntax:
    content: public abstract System.Xml.XmlNode Encrypt (System.Xml.XmlNode node);
    parameters:
    - id: node
      type: System.Xml.XmlNode
      description: "The  object to encrypt."
    return:
      type: System.Xml.XmlNode
      description: "To be added."
  overload: System.Configuration.ProtectedConfigurationProvider.Encrypt*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Configuration.Provider.ProviderBase
  isExternal: false
  name: System.Configuration.Provider.ProviderBase
- uid: System.Configuration.ProtectedConfigurationProvider.#ctor
  parent: System.Configuration.ProtectedConfigurationProvider
  isExternal: false
  name: ProtectedConfigurationProvider()
  nameWithType: ProtectedConfigurationProvider.ProtectedConfigurationProvider()
  fullName: System.Configuration.ProtectedConfigurationProvider.ProtectedConfigurationProvider()
- uid: System.Configuration.ProtectedConfigurationProvider.Decrypt(System.Xml.XmlNode)
  parent: System.Configuration.ProtectedConfigurationProvider
  isExternal: false
  name: Decrypt(XmlNode)
  nameWithType: ProtectedConfigurationProvider.Decrypt(XmlNode)
  fullName: System.Configuration.ProtectedConfigurationProvider.Decrypt(XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.ProtectedConfigurationProvider.Encrypt(System.Xml.XmlNode)
  parent: System.Configuration.ProtectedConfigurationProvider
  isExternal: false
  name: Encrypt(XmlNode)
  nameWithType: ProtectedConfigurationProvider.Encrypt(XmlNode)
  fullName: System.Configuration.ProtectedConfigurationProvider.Encrypt(XmlNode)
- uid: System.Configuration.ProtectedConfigurationProvider.#ctor*
  parent: System.Configuration.ProtectedConfigurationProvider
  isExternal: false
  name: ProtectedConfigurationProvider
  nameWithType: ProtectedConfigurationProvider.ProtectedConfigurationProvider
- uid: System.Configuration.ProtectedConfigurationProvider.Decrypt*
  parent: System.Configuration.ProtectedConfigurationProvider
  isExternal: false
  name: Decrypt
  nameWithType: ProtectedConfigurationProvider.Decrypt
- uid: System.Configuration.ProtectedConfigurationProvider.Encrypt*
  parent: System.Configuration.ProtectedConfigurationProvider
  isExternal: false
  name: Encrypt
  nameWithType: ProtectedConfigurationProvider.Encrypt
