### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Channels.NamedPipeSettings
  id: NamedPipeSettings
  children:
  - System.ServiceModel.Channels.NamedPipeSettings.ApplicationContainerSettings
  langs:
  - csharp
  name: NamedPipeSettings
  nameWithType: NamedPipeSettings
  fullName: System.ServiceModel.Channels.NamedPipeSettings
  type: Class
  summary: "Specifies named pipe settings."
  syntax:
    content: public sealed class NamedPipeSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net-11
  - net-20
  - netcore-10
- uid: System.ServiceModel.Channels.NamedPipeSettings.ApplicationContainerSettings
  id: ApplicationContainerSettings
  parent: System.ServiceModel.Channels.NamedPipeSettings
  langs:
  - csharp
  name: ApplicationContainerSettings
  nameWithType: NamedPipeSettings.ApplicationContainerSettings
  fullName: System.ServiceModel.Channels.NamedPipeSettings.ApplicationContainerSettings
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Channels
  summary: "Gets or sets the application container settings for the named pipe settings."
  syntax:
    content: public System.ServiceModel.Channels.ApplicationContainerSettings ApplicationContainerSettings { get; }
    return:
      type: System.ServiceModel.Channels.ApplicationContainerSettings
      description: "The application container settings for the named pipe settings."
  overload: System.ServiceModel.Channels.NamedPipeSettings.ApplicationContainerSettings*
  exceptions: []
  platform:
  - net-11
  - net-20
  - netcore-10
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.Channels.NamedPipeSettings.ApplicationContainerSettings
  parent: System.ServiceModel.Channels.NamedPipeSettings
  isExternal: false
  name: ApplicationContainerSettings
  nameWithType: NamedPipeSettings.ApplicationContainerSettings
  fullName: System.ServiceModel.Channels.NamedPipeSettings.ApplicationContainerSettings
- uid: System.ServiceModel.Channels.ApplicationContainerSettings
  parent: System.ServiceModel.Channels
  isExternal: false
  name: ApplicationContainerSettings
  nameWithType: ApplicationContainerSettings
  fullName: System.ServiceModel.Channels.ApplicationContainerSettings
- uid: System.ServiceModel.Channels.NamedPipeSettings.ApplicationContainerSettings*
  parent: System.ServiceModel.Channels.NamedPipeSettings
  isExternal: false
  name: ApplicationContainerSettings
  nameWithType: NamedPipeSettings.ApplicationContainerSettings
